import json

# Level 1 Part 44: (Portugese - Present)
L1_PART44 = {
    "portuguese": {"def": "葡萄牙人、葡萄牙語、葡萄牙的", "ipa": "/ˌpɔːtʃuˈɡiːz/", "trans": "無", "col": "speak portuguese", "ex": "She speaks Portuguese fluently."},
    "pose": {"def": "姿勢、樣子、裝腔作勢、擺姿勢、提出(問題)", "ipa": "/pəʊz/", "trans": "posed", "col": "pose a threat, pose for a photo", "ex": "He posed for a photograph."},
    "positive": {"def": "積極的、肯定的、正的、確定的", "ipa": "/ˈpɒzətɪv/", "trans": "positively", "col": "positive thinking, be positive about", "ex": "She has a very positive attitude."},
    "positively": {"def": "積極地、肯定地、斷然", "ipa": "/ˈpɒzətɪvli/", "trans": "positive (形容詞)", "col": "positively identify", "ex": "I can positively confirm the news."},
    "possess": {"def": "擁有、持有、支配、迷住", "ipa": "/pəˈzes/", "trans": "possessed, possession", "col": "possess wealth", "ex": "He possesses great courage."},
    "possession": {"def": "持有、擁有、財產、領土", "ipa": "/pəˈzeʃn/", "trans": "possessive", "col": "personal possessions, in possession of", "ex": "The ring is her most prized possession."},
    "possessive": {"def": "佔有慾強的、所有格的", "ipa": "/pəˈzesɪv/", "trans": "possessively", "col": "possessive case, be possessive of", "ex": "'My' is a possessive adjective."},
    "possibility": {"def": "可能性、可能的事、潛力", "ipa": "/ˌpɒsəˈbɪləti/", "trans": "possibilities, possible", "col": "beyond possibility, distinct possibility", "ex": "There is a possibility of rain."},
    "possible": {"def": "可能的、合理的、可行的", "ipa": "/ˈpɒsəbl/", "trans": "possibly, possibility", "col": "as soon as possible, make possible", "ex": "Is it possible to leave early?"},
    "possibly": {"def": "可能地、也許", "ipa": "/ˈpɒsəbli/", "trans": "possible (形容詞)", "col": "cannot possibly", "ex": "I cannot possibly finish it today."},
    "post": {"def": "郵政、郵寄、標竿、職位、發布、張貼", "ipa": "/pəʊst/", "trans": "posted, postage, postal", "col": "by post, air post", "ex": "I'll send it by post."},
    "postage": {"def": "郵資、郵費", "ipa": "/ˈpəʊstɪdʒ/", "trans": "無", "col": "postage stamp", "ex": "How much is the postage for this letter?"},
    "postal": {"def": "郵政的、郵寄的", "ipa": "/ˈpəʊstl/", "trans": "post (名詞)", "col": "postal service, postal code", "ex": "The postal service is quite reliable."},
    "postcard": {"def": "明信片", "ipa": "/ˈpəʊstkɑːd/", "trans": "postcards", "col": "send a postcard", "ex": "She sent me a postcard from France."},
    "poster": {"def": "海報、招貼", "ipa": "/ˈpəʊstə/", "trans": "posters", "col": "travel poster", "ex": "He hung a poster of his favorite band on the wall."},
    "postman": {"def": "郵差", "ipa": "/ˈpəʊstmən/", "trans": "postmen", "col": "local postman", "ex": "The postman delivered the mail."},
    "postpone": {"def": "延期、延緩", "ipa": "/pəˈspəʊn/", "trans": "postponed, postponement", "col": "postpone a meeting", "ex": "The match was postponed due to rain."},
    "postponement": {"def": "延期、延緩", "ipa": "/pəˈspəʊnmənt/", "trans": "postponements", "col": "unavoidable postponement", "ex": "The postponement of the trip was disappointing."},
    "postscript": {"def": "附言、備忘錄", "ipa": "/ˈpəʊstskrɪpt/", "trans": "postscripts", "col": "write a postscript", "ex": "He added a postscript to his letter."},
    "posture": {"def": "姿勢、儀態、態度、擺姿勢", "ipa": "/ˈpɒstʃə/", "trans": "postures", "col": "good posture", "ex": "He has very good posture."},
    "pot": {"def": "罐、壺、鍋、盆栽", "ipa": "/pɒt/", "trans": "pots, potted, pottery", "col": "coffee pot, flower pot", "ex": "She put the flower in a pot."},
    "potato": {"def": "馬鈴薯", "ipa": "/pəˈteɪtəʊ/", "trans": "potatoes", "col": "mashed potato, potato chips", "ex": "I like baked potatoes."},
    "potential": {"def": "潛力、電位、可能的、潛在的", "ipa": "/pəˈtenʃl/", "trans": "potentially", "col": "potential customer, realize potential", "ex": "He has the potential to be a great leader."},
    "potentially": {"def": "潛在地、可能地", "ipa": "/pəˈtenʃəli/", "trans": "potential (形容詞)", "col": "potentially dangerous", "ex": "The situation is potentially explosive."},
    "pottery": {"def": "陶器、製陶業、陶藝", "ipa": "/ˈpɒtəri/", "trans": "potter", "col": "piece of pottery", "ex": "She is taking a class in pottery."},
    "poultry": {"def": "家禽、禽肉", "ipa": "/ˈpəʊltri/", "trans": "無 (恆複)", "col": "raise poultry", "ex": "Chicken and turkey are poultry."},
    "pound": {"def": "英鎊、磅、猛擊、敲打", "ipa": "/paʊnd/", "trans": "pounds, pounded", "col": "pound sterling", "ex": "The book costs ten pounds."},
    "pour": {"def": "倒、灌、傾瀉、湧出", "ipa": "/pɔː/", "trans": "poured", "col": "pour water, it's pouring", "ex": "It's pouring with rain outside."},
    "poverty": {"def": "貧窮、貧困、貧乏", "ipa": "/ˈpɒvəti/", "trans": "poor (形容詞)", "col": "live in poverty", "ex": "They are living in extreme poverty."},
    "powder": {"def": "粉末、藥粉、火藥、擦粉、使成粉", "ipa": "/ˈpaʊdə/", "trans": "powders, powdery", "col": "talcum powder, baking powder", "ex": "The snow was like fine white powder."},
    "power": {"def": "權力、電力、動力、能量、加強動力", "ipa": "/ˈpaʊə/", "trans": "powers, powerful, powerless", "col": "nuclear power, come to power", "ex": "The king has absolute power."},
    "powerful": {"def": "強大的、有權力的、有說服力的", "ipa": "/ˈpaʊəfl/", "trans": "powerfully", "col": "powerful tool, powerful speaker", "ex": "This is a very powerful engine."},
    "powerless": {"def": "無能力的、無權力的", "ipa": "/ˈpʊələs/", "trans": "powerlessness", "col": "be powerless to", "ex": "They were powerless to stop the changes."},
    "practical": {"def": "實際的、實用的、實踐的", "ipa": "/ˈpræktɪkl/", "trans": "practically, practice", "col": "practical experience, practical joke", "ex": "This is a practical solution to the problem."},
    "practically": {"def": "幾乎、實際上", "ipa": "/ˈpræktɪkli/", "trans": "practical (形容詞)", "col": "practically impossible", "ex": "The job is practically finished."},
    "practice": {"def": "實踐、練習、業務、習慣", "ipa": "/ˈpræktɪs/", "trans": "practices, practise", "col": "in practice, make a practice of", "ex": "Practice makes perfect."},
    "practise": {"def": "練習、實踐、從事(業務)", "ipa": "/ˈpræktɪs/", "trans": "practised", "col": "practise law, practise piano", "ex": "He practises the piano every day."},
    "practitioner": {"def": "從業者、職業人士", "ipa": "/prækˈtɪʃənə/", "trans": "practitioners", "col": "general practitioner (GP)", "ex": "She is a legal practitioner."},
    "praise": {"def": "稱讚、讚揚、讚美、頌揚", "ipa": "/preɪz/", "trans": "praised, praiseworthy", "col": "in praise of, sing someone's praises", "ex": "He received high praise for his work."},
    "praiseworthy": {"def": "值得稱讚的", "ipa": "/ˈpreɪzwɜːði/", "trans": "praise (名詞)", "col": "praiseworthy effort", "ex": "His conduct was highly praiseworthy."},
    "pray": {"def": "祈禱、懇求", "ipa": "/preɪ/", "trans": "prayed, prayer", "col": "pray for peace", "ex": "They prayed for rain."},
    "prayer": {"def": "祈禱、禱告、祈禱者", "ipa": "/preə/", "trans": "prayers", "col": "say a prayer, answer a prayer", "ex": "The family gathered for prayer."},
    "preach": {"def": "傳教、講道、鼓吹", "ipa": "/priːtʃ/", "trans": "preached, preacher", "col": "preach to, preach a sermon", "ex": "He preaches to a large congregation."},
    "preacher": {"def": "傳教士、講道者", "ipa": "/ˈpriːtʃə/", "trans": "preachers", "col": "lay preacher", "ex": "He is a famous preacher."},
    "precaution": {"def": "預防措施、防備", "ipa": "/prɪˈkɔːʃn/", "trans": "precautions, precautionary", "col": "take precautions against", "ex": "Safety precautions must be observed."},
    "precede": {"def": "處在...之前、先於", "ipa": "/prɪˈsiːd/", "trans": "preceded, precedent, preceding", "col": "A precedes B", "ex": "He preceded me as chairman."},
    "precedent": {"def": "先例、判例、在先的", "ipa": "/ˈpresɪdənt/", "trans": "precedents", "col": "set a precedent", "ex": "This decision sets a legal precedent."},
    "precious": {"def": "珍貴的、寶貴的、做作的", "ipa": "/ˈpreʃəs/", "trans": "preciously", "col": "precious stones, precious time", "ex": "Time is precious."},
    "precise": {"def": "精確的、準確的、嚴謹的", "ipa": "/prɪˈsaɪs/", "trans": "precisely, precision", "col": "precise measurement", "ex": "He was very precise in his instructions."},
    "precisely": {"def": "精確地、正是", "ipa": "/prɪˈsaɪsli/", "trans": "precise (形容詞)", "col": "precisely at 8 o'clock", "ex": "That is precisely my point."},
    "precision": {"def": "精確、準確、精密度", "ipa": "/prɪˈsɪʒn/", "trans": "precise (形容詞)", "col": "historical precision, high precision", "ex": "This instrument measures with great precision."},
    "preclude": {"def": "排除、阻止、妨礙", "ipa": "/prɪˈkluːd/", "trans": "precluded", "col": "preclude any possibility", "ex": "His age precludes him from the job."},
    "precursor": {"def": "先驅、前導、前體", "ipa": "/priːˈkɜːsə/", "trans": "precursors", "col": "precursor to", "ex": "The treaty was a precursor to full peace."},
    "predatory": {"def": "捕食性的、掠奪性的", "ipa": "/ˈpredətri/", "trans": "predator", "col": "predatory bird, predatory animal", "ex": "Lions are predatory animals."},
    "predecessor": {"def": "前任、前輩、原有事物", "ipa": "/ˈpriːdəsesə/", "trans": "predecessors", "col": "immediate predecessor", "ex": "His predecessor was very popular."},
    "predicament": {"def": "困境、窘境", "ipa": "/prɪˈdɪkəmənt/", "trans": "predicaments", "col": "difficult predicament", "ex": "He was in a terrible predicament."},
    "predict": {"def": "預測、預言", "ipa": "/prɪˈdɪkt/", "trans": "predicted, predictable, prediction", "col": "predict the future", "ex": "It's hard to predict the outcome."},
    "predictable": {"def": "可預測的、墨守成規的", "ipa": "/prɪˈdɪktəbl/", "trans": "predictably", "col": "predictable result", "ex": "The movie has a very predictable ending."},
    "prediction": {"def": "預測、預言", "ipa": "/prɪˈdɪkʃn/", "trans": "predictions", "col": "make a prediction", "ex": "His prediction came true."},
    "predominance": {"def": "優勢、卓越、主導地位", "ipa": "/prɪˈdɒmɪnəns/", "trans": "predominant", "col": "economic predominance", "ex": "The company has a clear predominance in the market."},
    "predominant": {"def": "佔優勢的、卓越的、主要的", "ipa": "/prɪˈdɒmɪnənt/", "trans": "predominantly", "col": "predominant feature", "ex": "Red is the predominant color in the painting."},
    "predominate": {"def": "佔優勢、主導、支配", "ipa": "/prɪˈdɒmɪneɪt/", "trans": "predominated", "col": "predominate in", "ex": "Men predominate in this field."},
    "preface": {"def": "序言、開端、為...作序", "ipa": "/ˈprefəs/", "trans": "prefaces", "col": "preface to a book", "ex": "He wrote a short preface to the collection."},
    "prefer": {"def": "寧可、更喜歡、提拔", "ipa": "/prɪˈfɜː/", "trans": "preferred, preference, preferable", "col": "prefer A to B", "ex": "I prefer tea to coffee."},
    "preferable": {"def": "更可取的、更好的", "ipa": "/ˈprefrəbl/", "trans": "preferably", "col": "be preferable to", "ex": "Anything is preferable to war."},
    "preference": {"def": "偏好、偏愛、優先權", "ipa": "/ˈprefrəns/", "trans": "preferences", "col": "personal preference, give preference to", "ex": "He has a preference for spicy food."},
    "prefix": {"def": "前綴、字首、加前綴", "ipa": "/ˈpriːfɪks/", "trans": "prefixes", "col": "common prefix", "ex": "'Un-' is a common prefix."},
    "pregnancy": {"def": "懷孕、懷孕期", "ipa": "/ˈpreɡnənsi/", "trans": "pregnancies, pregnant", "col": "pregnancy test, during pregnancy", "ex": "She is in her third month of pregnancy."},
    "pregnant": {"def": "懷孕的、充滿的、含音深長的", "ipa": "/ˈpreɡnənt/", "trans": "pregnancy", "col": "be pregnant with", "ex": "She is six months pregnant."},
    "prejudice": {"def": "偏見、成見、損害、使抱偏見", "ipa": "/ˈpredʒədɪs/", "trans": "prejudiced", "col": "racial prejudice, without prejudice", "ex": "Prejudice can cloud one's judgment."},
    "preliminary": {"def": "初步的、開端的、初試、預賽", "ipa": "/prɪˈlɪmɪnəri/", "trans": "preliminaries", "col": "preliminary investigation, preliminary round", "ex": "The results are still preliminary."},
    "prelude": {"def": "序曲、開端、前奏", "ipa": "/ˈpreljuːd/", "trans": "preludes", "col": "prelude to war", "ex": "The unrest was a prelude to the revolution."},
    "premature": {"def": "過早的、未成熟的、早產的", "ipa": "/ˈpremətʃə/", "trans": "prematurely", "col": "premature death, premature baby", "ex": "The reports were somewhat premature."},
    "premier": {"def": "首相、總理、首位的、第一的", "ipa": "/ˈpremiə/", "trans": "premiers, premiership", "col": "vice premier", "ex": "The Premier met with the President."},
    "premiere": {"def": "首映、初次演出、首位的", "ipa": "/ˈpremieə/", "trans": "premieres", "col": "world premiere", "ex": "The movie will have its premiere tonight."},
    "premises": {"def": "建築物、房屋及其地基", "ipa": "/ˈpremɪsɪz/", "trans": "premise (前提)", "col": "on the premises, business premises", "ex": "The shop has moved to new premises."},
    "premium": {"def": "保險費、溢價、額外補貼、優質的", "ipa": "/ˈpriːmiəm/", "trans": "premiums", "col": "insurance premium, at a premium", "ex": "He paid a high premium for the insurance."},
    "preoccupy": {"def": "使全神貫注、先佔領", "ipa": "/priˈɒkjupaɪ/", "trans": "preoccupied", "col": "be preoccupied with", "ex": "He was preoccupied with his own thoughts."},
    "preparation": {"def": "準備、預備、調配劑", "ipa": "/ˌprepəˈreɪʃn/", "trans": "preparations, prepare", "col": "in preparation for", "ex": "The preparations for the party are complete."},
    "preparatory": {"def": "準備的、預備的", "ipa": "/prɪˈpærətri/", "trans": "prepare", "col": "preparatory school", "ex": "He is in a preparatory school."},
    "prepare": {"def": "準備、預備、烹調", "ipa": "/prɪˈpeə/", "trans": "prepared, preparation", "col": "prepare for, prepare a meal", "ex": "She path preparing for the exam."},
    "prepared": {"def": "準備好的、願意的", "ipa": "/prɪˈpeəd/", "trans": "prepare (動詞)", "col": "be prepared for", "ex": "I'm not prepared to answer that question."},
    "preposition": {"def": "介係詞", "ipa": "/ˌprepəˈzɪʃn/", "trans": "prepositions", "col": "prepositional phrase", "ex": "'In' and 'on' are prepositions."},
    "preposterous": {"def": "荒謬的、反常的", "ipa": "/prɪˈpɒstərəs/", "trans": "preposterously", "col": "preposterous idea", "ex": "That's a preposterous suggestion."},
    "prerequisite": {"def": "先決條件、必要的", "ipa": "/ˌpriːˈrekwəzɪt/", "trans": "prerequisites", "col": "prerequisite for success", "ex": "A degree is a prerequisite for the job."},
    "preschool": {"def": "幼兒園、學齡前的", "ipa": "/ˈpriːskuːl/", "trans": "preschoolers", "col": "preschool education", "ex": "He is attending a preschool."},
    "prescribe": {"def": "規定、指定、開藥", "ipa": "/prɪˈskraɪb/", "trans": "prescribed, prescription", "col": "prescribe medicine", "ex": "The doctor prescribed a course of antibiotics."},
    "prescription": {"def": "處方、藥方、建議", "ipa": "/prɪˈskrɪpʃn/", "trans": "prescriptions", "col": "fill a prescription", "ex": "You need a prescription for these pills."},
    "presence": {"def": "存在、出席、儀態、神色", "ipa": "/ˈprezns/", "trans": "present (形容詞/動詞)", "col": "presence of mind, physical presence", "ex": "Your presence is requested."},
    "present": {"def": "現在的、出席的、禮物、現在、呈現、贈送", "ipa": "/ˈpreznt/", "trans": "presents, presented, presence", "col": "at present, present tense", "ex": "I have a present for you."},
}

with open("batch_l1_p44.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART44, f, ensure_ascii=False, indent=2)
