import json

# Level 1 Part 37: (Overt - Parlor)
L1_PART37 = {
    "overt": {"def": "公開的、明顯的", "ipa": "/əʊˈvɜːt/", "trans": "overtly", "col": "overt hostility", "ex": "There was no overt sign of anger."},
    "overtake": {"def": "趕上、追過、突然降臨", "ipa": "/ˌəʊvəˈteɪk/", "trans": "overtook, overtaken", "col": "overtake on the left", "ex": "He tried to overtake the driver in front."},
    "overthrow": {"def": "推翻、瓦解、拋得太遠", "ipa": "/ˌəʊvəˈθrəʊ/", "trans": "overthrew, overthrown", "col": "overthrow the government", "ex": "The army overthrew the dictator."},
    "overtime": {"def": "加班、加班費、超時地", "ipa": "/ˈəʊvətaɪm/", "trans": "無", "col": "work overtime, pay overtime", "ex": "He had to work overtime to finish the job."},
    "overturn": {"def": "翻倒、推翻、瓦解", "ipa": "/ˌəʊvəˈtɜːn/", "trans": "overturned", "col": "overturn a decision", "ex": "The car hit the wall and overturned."},
    "overweight": {"def": "超重的、過胖的、過重的重量", "ipa": "/ˌəʊvəˈweɪt/", "trans": "underweight (過輕的)", "col": "be overweight", "ex": "I am a bit overweight."},
    "overwhelm": {"def": "淹沒、擊敗、使受不了", "ipa": "/ˌəʊvəˈwelm/", "trans": "overwhelmed", "col": "overwhelmed with joy", "ex": "The news overwhelmed him with grief."},
    "owe": {"def": "欠錢、歸功於", "ipa": "/əʊ/", "trans": "owed, owing", "col": "owe an apology, owe debt", "ex": "I owe you ten dollars."},
    "owing": {"def": "欠著的、由於 (owing to)", "ipa": "/ˈəʊɪŋ/", "trans": "owe (動詞)", "col": "owing to", "ex": "The game was cancelled owing to rain."},
    "owl": {"def": "貓頭鷹", "ipa": "/aʊl/", "trans": "owls", "col": "night owl", "ex": "The owl is hunting at night."},
    "own": {"def": "自己的、擁有、承認", "ipa": "/əʊn/", "trans": "owned, owner, ownership", "col": "on my own, come into one's own", "ex": "I have my own shop."},
    "owner": {"def": "物主、所有人", "ipa": "/ˈəʊnə/", "trans": "owners, ownership", "col": "pet owner, house owner", "ex": "Who is the owner of this car?"},
    "ownership": {"def": "所有權、占有", "ipa": "/ˈəʊnəʃɪp/", "trans": "owner (名詞)", "col": "private ownership, shared ownership", "ex": "The ownership of the land is in dispute."},
    "ox": {"def": "公牛、奴隸", "ipa": "/ɒks/", "trans": "oxen", "col": "as strong as an ox", "ex": "The ox is pulling the cart."},
    "oxide": {"def": "氧化物", "ipa": "/ˈɒksaɪd/", "trans": "oxides, oxidize", "col": "carbon monoxide", "ex": "Iron oxide is commonly known as rust."},
    "oxidize": {"def": "使氧化、生鏽", "ipa": "/ˈɒksɪdaɪz/", "trans": "oxidized", "col": "oxidize metal", "ex": "Iron oxidizes in the presence of air and moisture."},
    "oxygen": {"def": "氧氣", "ipa": "/ˈɒksɪdʒən/", "trans": "無", "col": "lack of oxygen", "ex": "Oxygen is essential for life."},
    "oyster": {"def": "牡蠣、蠔、沈默寡言者", "ipa": "/ˈɔɪstə/", "trans": "oysters", "col": "oyster sauce, raw oyster", "ex": "I like to eat oysters."},
    "pace": {"def": "步調、腳步、緩步而行", "ipa": "/peɪs/", "trans": "paced", "col": "keep pace with", "ex": "He is walking at a fast pace."},
    "Pacific": {"def": "太平洋(的)、和解的", "ipa": "/pəˈsɪfɪk/", "trans": "無", "col": "the Pacific Ocean", "ex": "Taiwan is an island in the Pacific."},
    "pack": {"def": "背包、包裹、一群、打包、包裝", "ipa": "/pæk/", "trans": "packed, package, packet", "col": "six-pack, pack up", "ex": "I have to pack my bags."},
    "package": {"def": "包裹、套件、包裝、打包", "ipa": "/ˈpækɪdʒ/", "trans": "packages, packaging", "col": "tour package, software package", "ex": "I sent a package to my friend."},
    "packet": {"def": "小包、封套、資料包", "ipa": "/ˈpækɪt/", "trans": "packets", "col": "packet of cigarettes", "ex": "He bought a packet of tea."},
    "packing": {"def": "包裝(物)、填料", "ipa": "/ˈpækɪŋ/", "trans": "pack (動詞)", "col": "packing material", "ex": "They are busy with the packing."},
    "pact": {"def": "協定、公約、契約", "ipa": "/pækt/", "trans": "pacts", "col": "peace pact, suicide pact", "ex": "The two countries signed a peace pact."},
    "pad": {"def": "墊、筆記本、印泥、躡手躡腳地走", "ipa": "/pæd/", "trans": "padded", "col": "mouse pad, sketch pad", "ex": "Wipe your feet on the pad."},
    "padded": {"def": "有襯墊的、誇大的", "ipa": "/ˈpædɪd/", "trans": "pad (名詞/動詞)", "col": "padded envelope", "ex": "The chair has a padded seat."},
    "paddle": {"def": "短槳、明輪、戲水、划槳", "ipa": "/ˈpædl/", "trans": "paddled", "col": "canoe paddle", "ex": "They use paddles to row the boat."},
    "page": {"def": "頁、篇幅、傳呼、侍從", "ipa": "/peɪdʒ/", "trans": "pages, pager", "col": "front page, web page", "ex": "Turn to page ten."},
    "pager": {"def": "呼叫器、傳呼機", "ipa": "/ˈpeɪdʒə/", "trans": "pagers", "col": "beeper/pager", "ex": "Pagers are rarely used today."},
    "paid": {"def": "付過錢的、受僱的", "ipa": "/peɪd/", "trans": "pay (動詞)", "col": "well paid, paid holiday", "ex": "He is a well-paid doctor."},
    "pail": {"def": "桶、提桶", "ipa": "/peɪl/", "trans": "pails", "col": "pail of water", "ex": "He carried a pail of water."},
    "pain": {"def": "痛苦、痛、辛苦", "ipa": "/peɪn/", "trans": "pains, painful", "col": "in pain, back pain", "ex": "I feel a sharp pain in my chest."},
    "painful": {"def": "痛苦的、討厭的", "ipa": "/ˈpeɪnfl/", "trans": "painfully", "col": "painful experience", "ex": "It was a painful decision."},
    "painfully": {"def": "/ˈpeɪnfəli/", "trans": "painful (形容詞)", "col": "painfully aware", "ex": "I was painfully aware of my mistake."},
    "painkiller": {"def": "止痛藥", "ipa": "/ˈpeɪnkɪlə/", "trans": "painkillers", "col": "take a painkiller", "ex": "The doctor prescribed some painkillers."},
    "painstaking": {"def": "辛勤的、艱苦的、煞費苦心的", "ipa": "/ˈpeɪnzteɪkɪŋ/", "trans": "painstakingly", "col": "painstaking work", "ex": "The research was a painstaking process."},
    "paint": {"def": "油漆、顏料、打扮、繪畫", "ipa": "/peɪnt/", "trans": "painted, painter, painting", "col": "wet paint, paint red", "ex": "Be careful, the paint is still wet."},
    "painter": {"def": "畫家、油漆匠", "ipa": "/ˈpeɪntə/", "trans": "painters", "col": "famed painter", "ex": "He is a famous painter."},
    "painting": {"def": "畫、繪畫藝術", "ipa": "/ˈpeɪntɪŋ/", "trans": "paintings", "col": "oil painting, cave painting", "ex": "I like his paintings."},
    "pair": {"def": "一對、一雙、成對", "ipa": "/peə/", "trans": "pairs, paired", "col": "pair of shoes, in pairs", "ex": "I bought a pair of shoes."},
    "palace": {"def": "宮殿、宏偉建築", "ipa": "/ˈpæləs/", "trans": "palaces", "col": "Buckingham Palace", "ex": "The King lives in the palace."},
    "pale": {"def": "蒼白的、淡色的、變蒼白", "ipa": "/peɪl/", "trans": "paler, palest", "col": "turn pale", "ex": "She turned pale with fear."},
    "palette": {"def": "調色板、色調", "ipa": "/ˈpælət/", "trans": "palettes", "col": "color palette", "ex": "The artist mixed paint on his palette."},
    "palm": {"def": "手掌、棕櫚樹、獎牌(獨佔)", "ipa": "/pɑːm/", "trans": "palms", "col": "palm tree, read palm", "ex": "He clapped his palms together."},
    "pancake": {"def": "薄煎餅", "ipa": "/ˈpænkeɪk/", "trans": "pancakes", "col": "tasty pancake", "ex": "I like pancakes with honey."},
    "pane": {"def": "窗格玻璃、嵌版", "ipa": "/peɪn/", "trans": "panes", "col": "window pane", "ex": "He broke a window pane."},
    "panel": {"def": "鑲版、控制板、專家小組", "ipa": "/ˈpænl/", "trans": "panels, panelist", "col": "control panel, solar panel", "ex": "We asked a panel of experts for advice."},
    "panic": {"def": "恐慌(的)、驚慌、使恐慌", "ipa": "/ˈpænɪk/", "trans": "panicked", "col": "moral panic, panic attack", "ex": "Don't panic!"},
    "panorama": {"def": "全景、視界、橫貫、概觀", "ipa": "/ˌpænəˈrɑːmə/", "trans": "panoramas, panoramic", "col": "stunning panorama", "ex": "We enjoyed the panorama of the city from the tower."},
    "panoramic": {"def": "全景的、概論的", "ipa": "/ˌpænəˈræmɪk/", "trans": "panorama (名詞)", "col": "panoramic view", "ex": "The hotel offers a panoramic view of the beach."},
    "pansy": {"def": "三色堇、同性戀(貶)", "ipa": "/ˈpænzi/", "trans": "pansies", "col": "wild pansy", "ex": "The garden was full of pansies."},
    "pant": {"def": "氣喘、心跳、渴望", "ipa": "/pænt/", "trans": "panted", "col": "pant for breath", "ex": "He was panting after the race."},
    "panther": {"def": "豹、英雄", "ipa": "/ˈpænθə/", "trans": "panthers", "col": "black panther", "ex": "A black panther is a very rare animal."},
    "pantry": {"def": "食品儲藏室、食櫥", "ipa": "/ˈpæntri/", "trans": "pantries", "col": "well-stocked pantry", "ex": "There's some bread in the pantry."},
    "pants": {"def": "褲子、長褲", "ipa": "/pænts/", "trans": "無 (恆複)", "col": "pair of pants", "ex": "He is wearing blue pants."},
    "papa/pappa": {"def": "爸爸", "ipa": "/pəˈpɑː/", "trans": "無", "col": "papa bear", "ex": "Papa, can I go out?"},
    "papaya": {"def": "木瓜", "ipa": "/pəˈpaɪə/", "trans": "papayas", "col": "ripe papaya", "ex": "I like to eat papaya."},
    "paper": {"def": "紙、報紙、論文、文件的", "ipa": "/ˈpeɪpə/", "trans": "papers, paperwork", "col": "toilet paper, wallpaper", "ex": "I need some paper to write on."},
    "paperback": {"def": "平裝本(的)", "ipa": "/ˈpeɪpəbæk/", "trans": "hardback (精裝本)", "col": "paperback book", "ex": "It's available in paperback."},
    "paperweight": {"def": "紙鎮", "ipa": "/ˈpeɪpəweɪt/", "trans": "paperweights", "col": "glass paperweight", "ex": "He used a rock as a paperweight."},
    "parable": {"def": "寓言、比喻", "ipa": "/ˈpærəbl/", "trans": "parables", "col": "biblical parable", "ex": "He told a parable about a good man."},
    "parachute": {"def": "降落傘、空降、傘降", "ipa": "/ˈpærəʃuːt/", "trans": "parachutes, parachuted", "col": "open parachute", "ex": "The pilot used a parachute to escape."},
    "parade": {"def": "遊行、閱兵、誇耀", "ipa": "/pəˈreɪd/", "trans": "parades, paraded", "col": "military parade, fashion parade", "ex": "We watched the parade on TV."},
    "paradigm": {"def": "典範、範例、變形表", "ipa": "/ˈpærədaɪm/", "trans": "paradigms", "col": "paradigm shift", "ex": "We need a new paradigm for education."},
    "paradise": {"def": "天堂、極樂世界", "ipa": "/ˈpærədaɪs/", "trans": "無", "col": "lost paradise", "ex": "The tropical island is a paradise."},
    "paradox": {"def": "悖論、自相矛盾的話/人/物", "ipa": "/ˈpærədɒks/", "trans": "paradoxes, paradoxical", "col": "twin paradox", "ex": "It's a paradox that he is rich but unhappy."},
    "paradoxical": {"def": "悖論的、自相矛盾的", "ipa": "/ˌpærəˈdɒksɪkl/", "trans": "paradoxically", "col": "paradoxical situation", "ex": "The result was paradoxical."},
    "paraffin": {"def": "石蠟、煤油", "ipa": "/ˈpærəfɪn/", "trans": "無", "col": "paraffin oil", "ex": "Paraffin is used to make candles."},
    "paragraph": {"def": "段落、短評", "ipa": "/ˈpærəɡrɑːf/", "trans": "paragraphs", "col": "next paragraph", "ex": "Read the first paragraph."},
    "parallel": {"def": "平行的、相似的、比擬、緯線", "ipa": "/ˈpærəlel/", "trans": "parallels", "col": "parallel line, in parallel", "ex": "The two roads are parallel."},
    "paralyse/paralyze": {"def": "使麻痺、使癱瘓", "ipa": "/ˈpærəlaɪz/", "trans": "paralysed, paralysis", "col": "be paralysed by", "ex": "The fear paralysed him."},
    "paralysis": {"def": "癱瘓、痲痺、中風", "ipa": "/pəˈræləsɪs/", "trans": "paralytic", "col": "sleep paralysis, infantile paralysis", "ex": "He suffered from paralysis after the accident."},
    "parameter": {"def": "參數、參量、起限定作用的因素", "ipa": "/pəˈræmɪtə/", "trans": "parameters", "col": "within parameters", "ex": "We must work within the parameters of the law."},
    "paramount": {"def": "至上的、最高的、主要的", "ipa": "/ˈpærəmaʊnt/", "trans": "無", "col": "of paramount importance", "ex": "Safety is of paramount importance."},
    "paranoia": {"def": "偏執狂、妄想症", "ipa": "/ˌpærəˈnɔɪə/", "trans": "paranoid", "col": "religious paranoia", "ex": "He suffers from paranoia."},
    "paranoid": {"def": "患妄想症的、多疑的", "ipa": "/ˈpærənɔɪd/", "trans": "paranoia (名詞)", "col": "paranoid schizophrenia", "ex": "Don't be so paranoid; nobody is following you."},
    "paraphrase": {"def": "改寫、釋意、解說", "ipa": "/ˈpærəfreɪz/", "trans": "paraphrased", "col": "loose paraphrase", "ex": "Could you paraphrase that for me?"},
    "parasite": {"def": "寄生蟲、食客", "ipa": "/ˈpærəsaɪt/", "trans": "parasites, parasitic", "col": "human parasite", "ex": "The tapeworm is a intestinal parasite."},
    "parasol": {"def": "陽傘", "ipa": "/ˈpærəsɒl/", "trans": "parasols", "col": "beach parasol", "ex": "She sat under a parasol."},
    "parcel": {"def": "包裹、小包、部分、分配", "ipa": "/ˈpɑːsl/", "trans": "parcels", "col": "part and parcel", "ex": "I sent the parcel by post."},
    "parch": {"def": "烘烤、使乾枯、枯萎", "ipa": "/pɑːtʃ/", "trans": "parched", "col": "parched land", "ex": "The dry weather parched the earth."},
    "parched": {"def": "焦渴的、烘乾的", "ipa": "/pɑːtʃt/", "trans": "parch (動詞)", "col": "parched throat", "ex": "I'm parched - I need a drink."},
    "pardon": {"def": "饒恕、寬恕、原諒、赦免、對不起?", "ipa": "/ˈpɑːdn/", "trans": "pardoned", "col": "beg your pardon, royal pardon", "ex": "Pardon me, I didn't mean to bump into you."},
    "parent": {"def": "父母、根源、源頭", "ipa": "/ˈpeərənt/", "trans": "parents, parenthood", "col": "single parent, parent company", "ex": "He lives with his parents."},
    "parenthood": {"def": "父母身份", "ipa": "/ˈpeərənthʊd/", "trans": "parent (名詞)", "col": "planned parenthood", "ex": "Parenthood is a big responsibility."},
    "Paris": {"def": "巴黎", "ipa": "/ˈpærɪs/", "trans": "Parisian (巴黎人/的)", "col": "capital of France", "ex": "Paris is known as the City of Light."},
    "parish": {"def": "教區、行政教區", "ipa": "/ˈpærɪʃ/", "trans": "parishes, parishioner", "col": "parish council", "ex": "The parish church dates back to the 12th century."},
    "parity": {"def": "同等、同格、平價、奇偶性", "ipa": "/ˈpærəti/", "trans": "parities", "col": "gender parity, nuclear parity", "ex": "Women are fighting for parity of pay."},
    "park": {"def": "公園、停車場、停(車)", "ipa": "/pɑːk/", "trans": "parks, parking", "col": "national park, amusement park", "ex": "Don't park your car here."},
    "parking": {"def": "停車", "ipa": "/ˈpɑːkɪŋ/", "trans": "park (名詞/動詞)", "col": "parking lot, parking space", "ex": "Parking is forbidden here."},
    "parliament": {"def": "議會、國會", "ipa": "/ˈpɑːləmənt/", "trans": "parliaments, parliamentary", "col": "member of parliament, act of parliament", "ex": "The laws are passed in parliament."},
    "parliamentary": {"def": "議會的、國會的", "ipa": "/ˌpɑːləˈmentri/", "trans": "parliament (名詞)", "col": "parliamentary debate", "ex": "He is a parliamentary candidate."},
    "parlor/parllour": {"def": "客廳、起居室、店", "ipa": "/ˈpɑːlə/", "trans": "parlors", "col": "beauty parlor, ice-cream parlor", "ex": "We went to an ice-cream parlor."},
}

with open("batch_l1_p37.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART37, f, ensure_ascii=False, indent=2)
