import json

# Level 1 Part 48: (Provoke - Punctuation)
L1_PART48 = {
    "provoke": {"def": "激怒、挑釁、惹起、激發", "ipa": "/prəˈvəʊk/", "trans": "provoked, provocation, provocative", "col": "provoke a reaction", "ex": "Don't provoke the dog."},
    "provoked": {"def": "被激發的、受挑釁的", "ipa": "/prəˈvəʊkt/", "trans": "provoke (動詞)", "col": "unprovoked attack", "ex": "The attack was unprovoked."},
    "prow": {"def": "船頭、優異、勇敢", "ipa": "/praʊ/", "trans": "prows", "col": "ship's prow", "ex": "The prow of the ship cut through the ice."},
    "prowess": {"def": "英勇、非凡技能、超凡才華", "ipa": "/ˈpraʊes/", "trans": "無", "col": "academic prowess, military prowess", "ex": "He is famous for his athletic prowess."},
    "prowl": {"def": "潛行、徘徊、尋找獵物", "ipa": "/praʊl/", "trans": "prowled", "col": "on the prowl", "ex": "The tiger was on the prowl for food."},
    "proxy": {"def": "代理人、代理權、委託書", "ipa": "/ˈpɒksi/", "trans": "proxies", "col": "vote by proxy", "ex": "You can vote by proxy."},
    "prude": {"def": "裝正經的人、過分拘謹的人", "ipa": "/pruːd/", "trans": "prudes, prudish", "col": "prudish attitude", "ex": "She doesn't want to seem like a prude."},
    "prudence": {"def": "審慎、慎重、節儉", "ipa": "/ˈpruːdns/", "trans": "prudent", "col": "financial prudence", "ex": "He exercised great prudence in his investments."},
    "prudent": {"def": "審慎的、慎重的、精明的", "ipa": "/ˈpruːdnt/", "trans": "prudently", "col": "prudent decision", "ex": "It was a prudent investment."},
    "prudential": {"def": "審慎的、慎重的、預防的", "ipa": "/pruˈdenʃl/", "trans": "prudence", "col": "prudential rules", "ex": "They follow strict prudential guidelines."},
    "prune": {"def": "乾梅子、深紫色、修剪、削減", "ipa": "/pruːn/", "trans": "pruned", "col": "prune trees", "ex": "The gardener is pruning the roses."},
    "prurient": {"def": "好色的、淫穢的、渴望的", "ipa": "/ˈprʊəriənt/", "trans": "prurience", "col": "prurient interest", "ex": "They have a prurient interest in others' lives."},
    "pry": {"def": "窺探、打聽、槓桿、撬開", "ipa": "/praɪ/", "trans": "pried", "col": "pry into secrets", "ex": "Don't pry into my private life."},
    "psalm": {"def": "讚美詩、聖歌", "ipa": "/sɑːm/", "trans": "psalms, psalmist", "col": "Book of Psalms", "ex": "They sang a psalm in church."},
    "pseudo": {"def": "偽的、假的、冒充的", "ipa": "/ˈsjuːdəʊ/", "trans": "無", "col": "pseudo-science", "ex": "It is a pseudo-intellectual argument."},
    "pseudonym": {"def": "假名、筆名", "ipa": "/ˈsjuːdənɪm/", "trans": "pseudonyms", "col": "write under a pseudonym", "ex": "The author wrote under a pseudonym."},
    "psyche": {"def": "靈魂、心智、精神", "ipa": "/ˈsaɪki/", "trans": "psychic", "col": "human psyche", "ex": "The experience left a scar on his psyche."},
    "psychiatrist": {"def": "精神病醫師", "ipa": "/saɪˈkaɪətrɪst/", "trans": "psychiatrists", "col": "consult a psychiatrist", "ex": "She is seeing a psychiatrist."},
    "psychiatry": {"def": "精神病學", "ipa": "/saɪˈkaɪətri/", "trans": "psychiatric", "col": "department of psychiatry", "ex": "He is a professor of psychiatry."},
    "psychic": {"def": "靈魂的、精神的、超自然的、靈媒", "ipa": "/ˈsaɪkɪk/", "trans": "psychically", "col": "psychic powers", "ex": "She claims to have psychic powers."},
    "psychoanalysis": {"def": "精神分析", "ipa": "/ˌsaɪkəʊəˈnæləsɪs/", "trans": "psychoanalyst", "col": "undergo psychoanalysis", "ex": "He is a pioneer of psychoanalysis."},
    "psychologist": {"def": "心理學家", "ipa": "/saɪˈkɒlədʒɪst/", "trans": "psychologists", "col": "child psychologist", "ex": "The psychologist analyzed his behavior."},
    "psychology": {"def": "心理學、心理狀態", "ipa": "/saɪˈɒlədʒi/", "trans": "psychological", "col": "social psychology", "ex": "He is studying psychology."},
    "psychosis": {"def": "精神病、精神錯亂", "ipa": "/saɪˈkəʊsɪs/", "trans": "psychotic", "col": "manic-depressive psychosis", "ex": "He is suffering from psychosis."},
    "pub": {"def": "酒吧、酒館", "ipa": "/pʌb/", "trans": "pubs", "col": "local pub", "ex": "Let's meet at the pub."},
    "puberty": {"def": "青春期、發育期", "ipa": "/ˈpjuːbəti/", "trans": "無", "col": "reach puberty", "ex": "He is going through puberty."},
    "public": {"def": "公眾的、公共的、公然的、大眾", "ipa": "/ˈpʌblɪk/", "trans": "publicly, publicity", "col": "public place, in public", "ex": "The building is open to the public."},
    "publication": {"def": "出版、發行、出版物、公布", "ipa": "/ˌpʌblɪˈkeɪʃn/", "trans": "publications, publish", "col": "date of publication", "ex": "He has many publications to his name."},
    "publicity": {"def": "宣傳、廣告、公開、大眾注意力", "ipa": "/pʌbˈlɪsəti/", "trans": "publicize", "col": "bad publicity, publicity stunt", "ex": "The movie got a lot of publicity."},
    "publicly": {"def": "公開地、公然地", "ipa": "/ˈpʌblɪkli/", "trans": "public (形容詞)", "col": "speak publicly", "ex": "He apologized publicly."},
    "publish": {"def": "出版、發行、發表、公布", "ipa": "/ˈpʌblɪʃ/", "trans": "published, publisher", "col": "publish a book", "ex": "The book was published last year."},
    "publisher": {"def": "出版商、發行人", "ipa": "/ˈpʌblɪʃə/", "trans": "publishers", "col": "major publisher", "ex": "He is a famous music publisher."},
    "puck": {"def": "冰球", "ipa": "/pʌk/", "trans": "pucks", "col": "hockey puck", "ex": "The player hit the puck into the net."},
    "pucker": {"def": "皺褶、皺紋、起皺、撅嘴", "ipa": "/ˈpʌkə/", "trans": "puckered", "col": "pucker up", "ex": "The lemon made her mouth pucker."},
    "pudding": {"def": "布丁、甜點", "ipa": "/ˈpʊdɪŋ/", "trans": "puddings", "col": "rice pudding", "ex": "What's for pudding?"},
    "puddle": {"def": "小水窪、泥潭", "ipa": "/ˈpʌdl/", "trans": "puddles", "col": "rain puddle", "ex": "The kids are splashing in the puddles."},
    "puff": {"def": "一口氣、噴煙、奶油酥、噴出、喘氣", "ipa": "/pʌf/", "trans": "puffed, puffy", "col": "puff of smoke, cream puff", "ex": "He blew out the candles with a puff."},
    "puffy": {"def": "膨脹的、肥滿的、喘氣的", "ipa": "/ˈpʌfi/", "trans": "puff (名詞/動詞)", "col": "puffy eyes", "ex": "Her eyes were puffy from crying."},
    "pugnacious": {"def": "好鬥的、好戰的", "ipa": "/pʌɡˈneɪʃəs/", "trans": "pugnacity", "col": "pugnacious attitude", "ex": "He was a pugnacious old man."},
    "pull": {"def": "拉、拖、拔、吸引力、拉力", "ipa": "/pʊl/", "trans": "pulled", "col": "pull out, pull through", "ex": "Don't pull my hair."},
    "pulley": {"def": "滑輪、滑車", "ipa": "/ˈpʊli/", "trans": "pulleys", "col": "pulley system", "ex": "The weights are lifted by a pulley."},
    "pulp": {"def": "果肉、紙漿、低級刊物、成漿", "ipa": "/pʌlp/", "trans": "pulpy", "col": "wood pulp, fruit pulp", "ex": "The wood is ground into pulp."},
    "pulsate": {"def": "搏動、悸動、震動", "ipa": "/pʌlˈseɪt/", "trans": "pulsated, pulsation", "col": "pulsate with life", "ex": "The city pulsated with light."},
    "pulse": {"def": "脈搏、脈衝、豆類、搏動", "ipa": "/pʌls/", "trans": "pulsed", "col": "check the pulse", "ex": "The doctor felt my pulse."},
    "pump": {"def": "泵、抽水機、輕便鞋、抽、灌", "ipa": "/pʌmp/", "trans": "pumped", "col": "petrol pump, pump up", "ex": "He used a pump to inflate the tires."},
    "pumpkin": {"def": "南瓜", "ipa": "/ˈpʌmpkɪn/", "trans": "pumpkins", "col": "pumpkin pie", "ex": "We carved a pumpkin for Halloween."},
    "pun": {"def": "雙關語、俏皮話、說雙關語", "ipa": "/pʌn/", "trans": "puns", "col": "play on words", "ex": "That's a clever pun."},
    "punch": {"def": "沖床、穿孔機、拳打、賓治酒、打", "ipa": "/pʌntʃ/", "trans": "punched", "col": "hole punch, punch in the face", "ex": "He gave me a punch in the arm."},
    "punctual": {"def": "準時的、守時的", "ipa": "/ˈpʌŋktʃuəl/", "trans": "punctually, punctuality", "col": "be punctual for", "ex": "Please be punctual for the meeting."},
    "punctuality": {"def": "準時、正點", "ipa": "/ˌpʌŋktʃuˈæləti/", "trans": "punctual (形容詞)", "col": "value punctuality", "ex": "He is famous for his punctuality."},
    "punctuate": {"def": "加標點、不時打斷", "ipa": "/ˈpʌŋktʃueɪt/", "trans": "punctuated, punctuation", "col": "punctuate a sentence", "ex": "He punctuates with gestures."},
    "punctuation": {"def": "標點符號、點標點", "ipa": "/ˌpʌŋktʃuˈeɪʃn/", "trans": "punctuated", "col": "punctuation mark", "ex": "Check the punctuation."},
}

with open("batch_l1_p48.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART48, f, ensure_ascii=False, indent=2)
