import json

# Level 1 Part 12: (Delighted - Done)
L1_PART12 = {
    "delighted": {"def": "欣喜的、快樂的", "ipa": "/dɪˈlaɪtɪd/", "trans": "delight (名詞/動詞)", "col": "be delighted with", "ex": "She was delighted to hear the news."},
    "delightful": {"def": "令人愉快的、迷人的", "ipa": "/dɪˈlaɪtfl/", "trans": "delightedly", "col": "delightful evening", "ex": "We had a delightful time at the party."},
    "deliver": {"def": "遞送、投遞、發表(演說)", "ipa": "/dɪˈlɪvə/", "trans": "delivery (名詞)", "col": "deliver a speech, home delivery", "ex": "The mailman delivered the package."},
    "delivery": {"def": "遞送、分娩", "ipa": "/dɪˈlɪvəri/", "trans": "deliver (動詞)", "col": "cash on delivery", "ex": "The delivery was late by an hour."},
    "demand": {"def": "需求、要求", "ipa": "/dɪˈmɑːnd/", "trans": "demanding (刻求的)", "col": "meet the demand", "ex": "There is a growing demand for solar power."},
    "demanding": {"def": "苛求的、費力的", "ipa": "/dɪˈmɑːndɪŋ/", "trans": "demand (名詞/動詞)", "col": "demanding job", "ex": "Teaching is a very demanding profession."},
    "democracy": {"def": "民主、民主國家", "ipa": "/dɪˈmɒkrəsi/", "trans": "democracies", "col": "parliamentary democracy", "ex": "Britain is a parliamentary democracy."},
    "democrat": {"def": "民主主義者、民主黨員", "ipa": "/ˈdeməkræt/", "trans": "Democrats", "col": "Democrat and Republican", "ex": "He voted for the Democrat candidate."},
    "democratic": {"def": "民主的、民主黨的", "ipa": "/ˌdeməˈkrætɪk/", "trans": "democratically", "col": "democratic society", "ex": "The country held its first democratic election."},
    "demonstrate": {"def": "論證、示範、示威", "ipa": "/ˈdemənstreɪt/", "trans": "demonstration (示範/示威)", "col": "demonstrate how to", "ex": "He demonstrated how to use the machine."},
    "demonstration": {"def": "示範、表露、示威運動", "ipa": "/ˌdemənˈstreɪʃn/", "trans": "demonstrate (動詞)", "col": "public demonstration", "ex": "They took part in a peaceful demonstration."},
    "dense": {"def": "濃厚的、密集的", "ipa": "/dens/", "trans": "densely, density (密度)", "col": "dense forest, dense fog", "ex": "The forest was so dense that no sunlight could enter."},
    "density": {"def": "密度", "ipa": "/ˈdensəti/", "trans": "densities", "col": "population density", "ex": "The density of the population is high in cities."},
    "dental": {"def": "牙齒的、牙科的", "ipa": "/ˈdentl/", "trans": "dentist", "col": "dental clinic, dental care", "ex": "You should have regular dental checkups."},
    "dentist": {"def": "牙醫", "ipa": "/ˈdentɪst/", "trans": "dentists", "col": "go to the dentist", "ex": "I have an appointment with the dentist."},
    "deny": {"def": "否認、拒絕", "ipa": "/dɪˈnaɪ/", "trans": "denial (否認)", "col": "deny the rumors", "ex": "He denied stealing the money."},
    "depart": {"def": "離開、出發", "ipa": "/dɪˈpɑːt/", "trans": "departure (離開)", "col": "depart for", "ex": "The train departs from Platform 2."},
    "department": {"def": "部門、系", "ipa": "/dɪˈpɑːtmənt/", "trans": "departments", "col": "department store, sales department", "ex": "He works in the marketing department."},
    "departure": {"def": "離開、出發", "ipa": "/dɪˈpɑːtʃə/", "trans": "depart (動詞)", "col": "departure lounge", "ex": "The departure was delayed for two hours."},
    "depend": {"def": "依靠、視...而定", "ipa": "/dɪˈpend/", "trans": "dependent, dependence", "col": "depend on", "ex": "It depends on the weather."},
    "dependence": {"def": "依賴、信任", "ipa": "/dɪˈpendəns/", "trans": "depend (動詞)", "col": "oil dependence", "ex": "The country is reducing its dependence on foreign oil."},
    "dependent": {"def": "依靠的、依賴的", "ipa": "/dɪˈpendənt/", "trans": "dependence (名詞)", "col": "be dependent on", "ex": "Children are dependent on their parents."},
    "depict": {"def": "描繪、描述", "ipa": "/dɪˈpɪkt/", "trans": "depicted", "col": "depict as", "ex": "The painting depicts a rural scene."},
    "deposit": {"def": "存款、押金、堆積", "ipa": "/dɪˈpɒzɪt/", "trans": "deposits", "col": "bank deposit, make a deposit", "ex": "I made a deposit into my savings account."},
    "depress": {"def": "使沮喪、使蕭條", "ipa": "/dɪˈpres/", "trans": "depressing, depressed", "col": "depress the economy", "ex": "The bad news depressed everyone."},
    "depressed": {"def": "感到沮喪的、蕭條的", "ipa": "/dɪˈprest/", "trans": "depression (名詞)", "col": "be depressed with", "ex": "She was depressed after losing her job."},
    "depressing": {"def": "令人沮喪的", "ipa": "/dɪˈpresɪŋ/", "trans": "depressing", "col": "depressing news", "ex": "The wet weather was very depressing."},
    "depression": {"def": "沮喪、蕭條、坑", "ipa": "/dɪˈpreʃn/", "trans": "depressed", "col": "Great Depression", "ex": "He suffers from deep depression."},
    "deprive": {"def": "剝奪、使喪失", "ipa": "/dɪˈpraɪv/", "trans": "deprived", "col": "deprive of", "ex": "The war deprived them of their homes."},
    "depth": {"def": "深度、深處", "ipa": "/depθ/", "trans": "depths", "col": "in depth, out of one's depth", "ex": "What is the depth of the water?"},
    "deputy": {"def": "代表、代理人、副職", "ipa": "/ˈdepjuti/", "trans": "deputies", "col": "deputy manager", "ex": "He is the deputy director of the company."},
    "derive": {"def": "取得、源自", "ipa": "/dɪˈraɪv/", "trans": "derived", "col": "derive from", "ex": "Many words in English derive from Latin."},
    "descend": {"def": "下降、傳下來", "ipa": "/dɪˈsend/", "trans": "descendant (後代)", "col": "descend the stairs", "ex": "The sun gradually descended."},
    "descendant": {"def": "後裔、後代", "ipa": "/dɪˈsendənt/", "trans": "descendants", "col": "direct descendant", "ex": "He is a direct descendant of the royal family."},
    "describe": {"def": "描述、形容", "ipa": "/dɪˈskraɪb/", "trans": "description (名詞)", "col": "describe as", "ex": "Could you describe the man you saw?"},
    "description": {"def": "描述、說明書", "ipa": "/dɪˈskrɪpʃn/", "trans": "describe (動詞)", "col": "detailed description", "ex": "The police have a description of the thief."},
    "desert": {"def": "沙漠、遺棄", "ipa": "/ˈdezət/", "trans": "deserted (荒廢的)", "col": "sahara desert", "ex": "Camels can live in the desert."},
    "deserve": {"def": "應得、值得", "ipa": "/dɪˈzɜːv/", "trans": "deservedly", "col": "deserve better", "ex": "He deserves a reward for his hard work."},
    "design": {"def": "設計、構思", "ipa": "/dɪˈzaɪn/", "trans": "designer (設計師)", "col": "fashion design, web design", "ex": "The building was designed by a famous architect."},
    "designer": {"def": "設計師", "ipa": "/dɪˈzaɪnə/", "trans": "designers", "col": "fashion designer", "ex": "She is a top-level interior designer."},
    "desirable": {"def": "值得擁有的、理想的", "ipa": "/dɪˈzaɪərəbl/", "trans": "desirably", "col": "most desirable", "ex": "It's a very desirable neighborhood to live in."},
    "desire": {"def": "慾望、渴望", "ipa": "/dɪˈzaɪə/", "trans": "desired, desirous", "col": "deep desire", "ex": "He has a strong desire for success."},
    "desk": {"def": "書桌、辦公桌、櫃台", "ipa": "/desk/", "trans": "desks", "col": "front desk", "ex": "I am sitting at my desk."},
    "despair": {"def": "絕望", "ipa": "/dɪˈspeə/", "trans": "despairingly", "col": "in despair", "ex": "Don't despair; help is on the way."},
    "desperate": {"def": "絕望的、拼命的", "ipa": "/ˈdespərət/", "trans": "desperately", "col": "desperate attempt", "ex": "They made a desperate attempt to escape."},
    "despite": {"def": "儘管、不管", "ipa": "/dɪˈspaɪt/", "trans": "無", "col": "despite the rain", "ex": "She went out despite the cold weather."},
    "dessert": {"def": "甜點", "ipa": "/dɪˈzɜːt/", "trans": "desserts", "col": "fruit dessert", "ex": "What would you like for dessert?"},
    "destination": {"def": "目的地", "ipa": "/ˌdestɪˈneɪʃn/", "trans": "destinations", "col": "tourist destination", "ex": "Spain is a popular tourist destination."},
    "destiny": {"def": "命運", "ipa": "/ˈdestəni/", "trans": "destined (注定的)", "col": "fulfil one's destiny", "ex": "He believed it was his destiny to be a writer."},
    "destroy": {"def": "破壞、毀滅", "ipa": "/dɪˈstrɔɪ/", "trans": "destruction (名詞), destructive (破壞性的)", "col": "destroy the environment", "ex": "The fire destroyed the entire building."},
    "destruction": {"def": "破壞、摧毀", "ipa": "/dɪˈstrʌkʃn/", "trans": "destroy (動詞)", "col": "mass destruction", "ex": "The war led to massive destruction."},
    "destructive": {"def": "破壞性的", "ipa": "/dɪˈstrʌktɪv/", "trans": "destructively", "col": "destructive power", "ex": "Pollution can have a destructive effect on the environment."},
    "detach": {"def": "分開、拆卸", "ipa": "/dɪˈtætʃ/", "trans": "detached (分開的)", "col": "detach from", "ex": "You can detach the laptop from the keyboard."},
    "detail": {"def": "細節、詳述", "ipa": "/ˈdiːteɪl/", "trans": "detailed (詳細的)", "col": "in detail", "ex": "Please tell me the story in detail."},
    "detailed": {"def": "詳細的", "ipa": "/ˈdiːteɪld/", "trans": "detail (名詞/動詞)", "col": "detailed analysis", "ex": "She gave a very detailed report of the incident."},
    "detain": {"def": "拘留、耽擱", "ipa": "/dɪˈteɪn/", "trans": "detained, detention", "col": "detain for questioning", "ex": "The suspect was detained by the police."},
    "detect": {"def": "察覺、偵測", "ipa": "/dɪˈtekt/", "trans": "detector (偵測器), detection (名詞)", "col": "detect cancer early", "ex": "The machine can detect small metal objects."},
    "detection": {"def": "偵測、察覺", "ipa": "/dɪˈtekʃn/", "trans": "detect (動詞)", "col": "smoke detection", "ex": "Early detection is key to treating the disease."},
    "detective": {"def": "偵探、警探", "ipa": "/dɪˈtektɪv/", "trans": "detectives", "col": "private detective", "ex": "Sherlock Holmes is a famous fictional detective."},
    "deter": {"def": "嚇阻、使斷念", "ipa": "/dɪˈtɜː/", "trans": "deterrence, deterrent", "col": "deter crime", "ex": "High prices deter many people from buying a car."},
    "detergent": {"def": "清潔劑、洗滌劑", "ipa": "/dɪˈtɜːdʒənt/", "trans": "detergents", "col": "laundry detergent", "ex": "You need more detergent for these dirty clothes."},
    "determination": {"def": "決心、決定", "ipa": "/dɪˌtɜːmɪˈneɪʃn/", "trans": "determine (動詞)", "col": "grim determination", "ex": "He fought with great determination."},
    "determine": {"def": "決定、下定決心", "ipa": "/dɪˈtɜːmɪn/", "trans": "determined, determination", "col": "determine the cause", "ex": "Scientists are trying to determine the cause of the disease."},
    "determined": {"def": "堅定的、下定決心的", "ipa": "/dɪˈtɜːmɪnd/", "trans": "determine (動詞)", "col": "be determined to do", "ex": "I am determined to pass the English exam."},
    "develop": {"def": "發展、開發、沖洗(照片)", "ipa": "/dɪˈveləp/", "trans": "development (名詞)", "col": "develop a habit, develop country", "ex": "The country is developing its natural resources."},
    "development": {"def": "發展、進展", "ipa": "/dɪˈveləpmənt/", "trans": "develop (動詞)", "col": "new development", "ex": "Science has seen rapid development in recent years."},
    "device": {"def": "裝置、器材、計畫", "ipa": "/dɪˈvaɪs/", "trans": "devices", "col": "electronic device, labor-saving device", "ex": "This is a very simple labor-saving device."},
    "devil": {"def": "魔鬼", "ipa": "/ˈdevl/", "trans": "devils", "col": "dare-devil", "ex": "He is as wicked as a devil."},
    "devise": {"def": "設計、發明、策劃", "ipa": "/dɪˈvaɪz/", "trans": "devised", "col": "devise a scheme", "ex": "We need to devise a new secret code."},
    "devote": {"def": "奉獻、致力於", "ipa": "/dɪˈvəʊt/", "trans": "devoted, devotion", "col": "devote time to", "ex": "She devoted all her time to her children."},
    "devoted": {"def": "忠誠的、致力於", "ipa": "/dɪˈvəʊtɪd/", "trans": "devote (動詞)", "col": "devoted husband", "ex": "He is highly devoted to his work."},
    "devotion": {"def": "熱愛、奉獻", "ipa": "/dɪˈvəʊʃn/", "trans": "devote (動詞)", "col": "selfless devotion", "ex": "His devotion to the company was recognized."},
    "dew": {"def": "露水", "ipa": "/djuː/", "trans": "dewy", "col": "dew drop", "ex": "The morning grass was wet with dew."},
    "diabetes": {"def": "糖尿病", "ipa": "/ˌdaɪəˈbiːtiːz/", "trans": "diabetic (糖尿病的)", "col": "suffer from diabetes", "ex": "He has been suffering from diabetes for years."},
    "diagnose": {"def": "診斷", "ipa": "/ˈdaɪəɡnəʊz/", "trans": "diagnosis (名詞)", "col": "diagnose as", "ex": "The doctor diagnosed the illness as pneumonia."},
    "diagnosis": {"def": "診斷、導出、診斷書", "ipa": "/ˌdaɪəɡˈnəʊsɪs/", "trans": "diagnoses (複數)", "col": "accurate diagnosis", "ex": "The doctor made a quick diagnosis."},
    "diagram": {"def": "圖表、圖解", "ipa": "/ˈdaɪəɡræm/", "trans": "diagrams", "col": "flow diagram", "ex": "The diagram shows how the system works."},
    "dial": {"def": "撥號盤、儀表、撥號", "ipa": "/ˈdaɪəl/", "trans": "dials, dialed", "col": "dial a number", "ex": "Dial 9 for an outside line."},
    "dialect": {"def": "方言", "ipa": "/ˈdaɪəlekt/", "trans": "dialects", "col": "local dialect", "ex": "They speak a local dialect of Italian."},
    "dialogue/dialog": {"def": "對話", "ipa": "/ˈdaɪəlɒɡ/", "trans": "dialogues", "col": "constructive dialogue", "ex": "The actors held a long dialogue on stage."},
    "diameter": {"def": "直徑", "ipa": "/daɪˈæmɪtə/", "trans": "diameters", "col": "inside diameter", "ex": "The diameter of the tree is three feet."},
    "diamond": {"def": "鑽石、金剛石、菱形", "ipa": "/ˈdaɪəmənd/", "trans": "diamonds", "col": "diamond ring", "ex": "She is wearing a beautiful diamond necklace."},
    "diaper/nappy": {"def": "尿布", "ipa": "/ˈdaɪəpə/", "trans": "diapers", "col": "change diapers", "ex": "It's time to change the baby's diaper."},
    "diary": {"def": "日記", "ipa": "/ˈdaɪəri/", "trans": "diaries", "col": "keep a diary", "ex": "I write in my diary every night."},
    "dictate": {"def": "口授、聽寫、命令", "ipa": "/dɪkˈteɪt/", "trans": "dictation (聽寫)", "col": "dictate a letter", "ex": "He dictated a letter to his secretary."},
    "dictation": {"def": "聽寫、命令", "ipa": "/dɪkˈteɪʃn/", "trans": "dictate (動詞)", "col": "take dictation", "ex": "The teacher gave a dictation in class."},
    "dictator": {"def": "獨裁者", "ipa": "/dɪkˈteɪtə/", "trans": "dictators, dictatorship", "col": "military dictator", "ex": "The country was ruled by a military dictator."},
    "dictionary": {"def": "字典", "ipa": "/ˈdɪkʃənəri/", "trans": "dictionaries", "col": "look up in a dictionary", "ex": "If you don't know the word, use a dictionary."},
    "die": {"def": "死亡", "ipa": "/daɪ/", "trans": "died, dying, death (名詞)", "col": "die of, die out", "ex": "Millions of people die of hunger each year."},
    "diet": {"def": "飲食、節食", "ipa": "/ˈdaɪət/", "trans": "dieter, dietary", "col": "on a diet, balanced diet", "ex": "She is on a diet to lose weight."},
    "differ": {"def": "不同、意見分歧", "ipa": "/ˈdɪfə/", "trans": "different (形容詞), difference (名詞)", "col": "differ from", "ex": "French differs from Italian in many ways."},
    "difference": {"def": "差異、價值", "ipa": "/ˈdɪfrəns/", "trans": "differ (動詞)", "col": "make a difference", "ex": "What's the difference between these two?"},
    "different": {"def": "不同的", "ipa": "/ˈdɪfrənt/", "trans": "differently", "col": "be different from", "ex": "The reality was very different from expectations."},
    "difficult": {"def": "困難的", "ipa": "/ˈdɪfɪkəlt/", "trans": "difficulty (名詞)", "col": "find it difficult to", "ex": "English is difficult but interesting."},
    "difficulty": {"def": "困難、難點", "ipa": "/ˈdɪfɪkəlti/", "trans": "difficulties", "col": "financial difficulty", "ex": "He overcame many difficulties."},
    "dig": {"def": "挖掘", "ipa": "/dɪɡ/", "trans": "dug, digging", "col": "dig out, dig a hole", "ex": "They are digging a deep hole in the garden."},
    "digest": {"def": "消化、領會、摘要", "ipa": "/daɪˈdʒest/", "trans": "digestion (消化)", "col": "digest food", "ex": "It takes time for the body to digest meat."},
    "digestion": {"def": "消化", "ipa": "/daɪˈdʒestʃən/", "trans": "digest (動詞)", "col": "poor digestion", "ex": "Drinking tea after dinner helps digestion."},
    "digital": {"def": "數位化的", "ipa": "/ˈdɪdʒɪtl/", "trans": "digitally", "col": "digital camera, digital clock", "ex": "We live in a digital age."},
    "dignity": {"def": "尊嚴、高貴", "ipa": "/ˈdɪɡnəti/", "trans": "dignified", "col": "human dignity", "ex": "They died with dignity."},
    "diligence": {"def": "勤奮", "ipa": "/ˈdɪlɪdʒəns/", "trans": "diligent (勤奮的)", "col": "reward for diligence", "ex": "Diligence is the mother of success."},
    "diligent": {"def": "勤奮的", "ipa": "/ˈdɪlɪdʒənt/", "trans": "diligently", "col": "diligent student", "ex": "He is a very diligent worker."},
    "dim": {"def": "昏暗的、模糊的", "ipa": "/dɪm/", "trans": "dimly", "col": "dim light", "ex": "The light was very dim in the room."},
    "dime": {"def": "一角硬幣 (美國/加拿大)", "ipa": "/daɪm/", "trans": "dimes", "col": "a dime a dozen", "ex": "Can you give me a dime for the machine?"},
    "dimension": {"def": "尺寸、空間、維度", "ipa": "/daɪˈmenʃn/", "trans": "dimensions", "col": "three dimensions", "ex": "What are the dimensions of the box?"},
    "diminish": {"def": "減少、削弱", "ipa": "/dɪˈmɪnɪʃ/", "trans": "diminished", "col": "diminish in value", "ex": "The noise gradually diminished."},
    "dine": {"def": "進正餐、用餐", "ipa": "/daɪn/", "trans": "dinner (名詞)", "col": "dine out", "ex": "We dined at a fancy restaurant."},
    "dinner": {"def": "晚餐、正餐", "ipa": "/ˈdɪnə/", "trans": "dinners", "col": "have dinner", "ex": "What's for dinner tonight?"},
    "dinosaur": {"def": "恐龍", "ipa": "/ˈdaɪnəsɔː/", "trans": "dinosaurs", "col": "toy dinosaur", "ex": "Dinosaurs lived millions of years ago."},
    "dip": {"def": "浸、沾", "ipa": "/dɪp/", "trans": "dipped", "col": "dip into", "ex": "She dipped her finger into the water."},
    "diploma": {"def": "畢業證書、文憑", "ipa": "/dɪˈpləʊmə/", "trans": "diplomas", "col": "high school diploma", "ex": "He received his high school diploma yesterday."},
    "diplomatic": {"def": "外交的、圓滑的", "ipa": "/ˌdɪpləˈmætɪk/", "trans": "diplomatically, diplomacy", "col": "diplomatic relations", "ex": "The two countries established diplomatic ties."},
    "direct": {"def": "直接的、導演、指引", "ipa": "/dəˈrekt/", "trans": "directly, direction, director", "col": "direct flight, direct contact", "ex": "Is there a direct flight to London?"},
    "direction": {"def": "方向、指引、趨勢", "ipa": "/dəˈrekʃn/", "trans": "directions, direct (動詞)", "col": "follow directions, in all directions", "ex": "Which direction are you headed?"},
    "directly": {"def": "/dəˈrektli/", "trans": "direct (形容詞)", "col": "directly involved", "ex": "He went directly to his office."},
    "director": {"def": "負責人、導演、董事", "ipa": "/dəˈrektə/", "trans": "directors", "col": "film director, board of directors", "ex": "He is the director of the company."},
    "dirt": {"def": "污垢、泥土", "ipa": "/dɜːt/", "trans": "dirty (髒的)", "col": "cover in dirt", "ex": "Her clothes were covered in dirt."},
    "dirty": {"def": "髒的", "ipa": "/ˈdɜːti/", "trans": "dirtiness", "col": "dirty hands", "ex": "Wash your dirty hands."},
    "disability": {"def": "殘疾、無能", "ipa": "/ˌdɪsəˈbɪləti/", "trans": "disabilities, disabled (殘疾的)", "col": "physical disability", "ex": "He overcame his disability and became a top athlete."},
    "disabled": {"def": "有殘疾的", "ipa": "/dɪsˈeɪbld/", "trans": "disability", "col": "disabled person", "ex": "The building has facilities for the disabled."},
    "disadvantage": {"def": "缺點、不利因素", "ipa": "/ˌdɪsədˈvɑːntɪdʒ/", "trans": "disadvantages", "col": "at a disadvantage", "ex": "Lack of money was a big disadvantage."},
    "disagree": {"def": "不同意、不符", "ipa": "/ˌdɪsəˈɡriː/", "trans": "disagreement (名詞)", "col": "disagree with", "ex": "I strongly disagree with your opinion."},
    "disagreement": {"def": "意見分歧、不和", "ipa": "/ˌdɪsəˈɡriːmənt/", "trans": "disagree (動詞)", "col": "serious disagreement", "ex": "The disagreement between the parents was obvious."},
    "disappear": {"def": "消失", "ipa": "/ˌdɪsəˈpɪə/", "trans": "disappearance (名詞)", "col": "disappear from sight", "ex": "The sun disappeared behind the clouds."},
    "disappoint": {"def": "使失望", "ipa": "/ˌdɪsəˈpɔɪnt/", "trans": "disappointed, disappointment", "col": "disappoint someone", "ex": "I'm sorry to disappoint you."},
    "disappointed": {"def": "感到失望的", "ipa": "/ˌdɪsəˈpɔɪntɪd/", "trans": "disappoint (動詞)", "col": "be disappointed with/at", "ex": "I am disappointed at the results."},
    "disappointing": {"def": "令人失望的", "ipa": "/ˌdɪsəˈpɔɪntɪŋ/", "trans": "disappointingly", "col": "disappointing news", "ex": "The team gave a disappointing performance."},
    "disappointment": {"def": "失望、令人失望的人事物", "ipa": "/ˌdɪsəˈpɔɪntmənt/", "trans": "disappoint (動詞)", "col": "great disappointment", "ex": "His failure was a big disappointment to us all."},
    "disapprove": {"def": "不贊成、不同意", "ipa": "/ˌdɪsəˈpruːv/", "trans": "disapproval (名詞)", "col": "disapprove of", "ex": "My parents disapprove of my boyfriend."},
    "disaster": {"def": "災難、大禍", "ipa": "/dɪˈzɑːstə/", "trans": "disastrous", "col": "natural disaster", "ex": "The earthquake was a major disaster."},
    "disastrous": {"def": "災難性的、極其糟糕的", "ipa": "/dɪˈzɑːstrəs/", "trans": "disaster (名詞)", "col": "disastrous consequences", "ex": "The flood had a disastrous effect on the area."},
    "disc/disk": {"def": "磁碟、圓盤", "ipa": "/dɪsk/", "trans": "discs", "col": "compact disc, floppy disk", "ex": "I saved the file onto a disk."},
    "discard": {"def": "丟棄、拋棄", "ipa": "/dɪˈskɑːd/", "trans": "discarded", "col": "discard old clothes", "ex": "She discarded her old books."},
    "discipline": {"def": "學科、紀律", "ipa": "/ˈdɪsəplɪn/", "trans": "disciplined", "col": "high discipline", "ex": "The children lack discipline."},
    "disclose": {"def": "揭露、透露", "ipa": "/dɪsˈkləʊz/", "trans": "disclosure (名詞)", "col": "disclose secrets", "ex": "The company refused to disclose details of the deal."},
    "disclosure": {"def": "揭發、透露之事", "ipa": "/dɪsˈkləʊʒə/", "trans": "disclose (動詞)", "col": "public disclosure", "ex": "The disclosure of the secret caused a scandal."},
    "disco": {"def": "迪斯可", "ipa": "/ˈdɪskəʊ/", "trans": "discos", "col": "go to the disco", "ex": "They spent all night at the disco."},
    "discomfort": {"def": "不適、不便", "ipa": "/dɪsˈkʌmfət/", "trans": "comfortable (形容詞)", "col": "cause discomfort", "ex": "He felt some discomfort in his chest."},
    "disconnect": {"def": "斷開、斷電", "ipa": "/ˌdɪskəˈnekt/", "trans": "disconnected", "col": "disconnect from", "ex": "You must disconnect the power before repairing."},
    "discount": {"def": "折扣", "ipa": "/ˈdɪskaʊnt/", "trans": "discounted", "col": "give a discount", "ex": "Members get a 10% discount."},
    "discourage": {"def": "使洩氣、阻礙", "ipa": "/dɪsˈkʌrɪdʒ/", "trans": "discouragement, discouraging", "col": "discourage someone from doing", "ex": "Don't let failures discourage you."},
    "discouraging": {"def": "令人洩氣的", "ipa": "/dɪsˈkʌrɪdʒɪŋ/", "trans": "discourage (動詞)", "col": "discouraging results", "ex": "The initial results were very discouraging."},
    "discover": {"def": "發現", "ipa": "/dɪsˈkʌvə/", "trans": "discovery (名詞), discoverer (發現者)", "col": "discover the truth", "ex": "Columbus discovered America in 1492."},
    "discovery": {"def": "發現、新發現的人事物", "ipa": "/dɪsˈkʌvəri/", "trans": "discover (動詞)", "col": "scientific discovery", "ex": "Scientists made an important discovery."},
    "discreet": {"def": "謹慎的", "ipa": "/dɪsˈkriːt/", "trans": "discreetly", "col": "be discreet", "ex": "He was very discreet about his personal life."},
    "discriminate": {"def": "歧視、辨別", "ipa": "/dɪˈskrɪmɪneɪt/", "trans": "discrimination (歧視)", "col": "discriminate against", "ex": "The law forbids companies to discriminate between employees."},
    "discrimination": {"def": "歧視、辨析力", "ipa": "/dɪˌskrɪmɪˈneɪʃn/", "trans": "discriminate (動詞)", "col": "racial discrimination, sex discrimination", "ex": "Many people have suffered from racial discrimination."},
    "discuss": {"def": "討論", "ipa": "/dɪˈskʌs/", "trans": "discussion (名詞)", "col": "discuss something with", "ex": "We discussed the problem for hours."},
    "discussion": {"def": "討論、商議", "ipa": "/dɪˈskʌʃn/", "trans": "discuss (動詞)", "col": "group discussion", "ex": "The matter is still under discussion."},
    "disease": {"def": "疾病", "ipa": "/dɪˈziːz/", "trans": "diseased", "col": "suffer from a disease", "ex": "He died of a heart disease."},
    "disgrace": {"def": "丟臉、恥辱", "ipa": "/dɪsˈɡreɪs/", "trans": "disgraceful (丟臉的)", "col": "be a disgrace to", "ex": "His behavior was a disgrace to the family."},
    "disgraceful": {"def": "丟臉的、可恥的", "ipa": "/dɪsˈɡreɪsfl/", "trans": "disgrace (名詞/動詞)", "col": "disgraceful conduct", "ex": "His treatment of his parents was disgraceful."},
    "disguise": {"def": "偽裝、掩飾", "ipa": "/dɪsˈɡaɪz/", "trans": "disguised", "col": "in disguise", "ex": "He was in disguise, so I didn't recognize him."},
    "dish": {"def": "盤子、一道菜", "ipa": "/dɪʃ/", "trans": "dishes", "col": "main dish, side dish", "ex": "She washed the dishes after dinner."},
    "dishonest": {"def": "不誠實的", "ipa": "/dɪsˈɒnɪst/", "trans": "honest (誠實的), dishonesty (不誠實)", "col": "dishonest behavior", "ex": "Lying is a dishonest act."},
    "dishonesty": {"def": "不誠實", "ipa": "/dɪsˈɒnɪsti/", "trans": "dishonest (形容詞)", "col": "be fired for dishonesty", "ex": "The official was punished for his dishonesty."},
    "disk/disc": {"def": "磁碟、圓盤", "ipa": "/dɪsk/", "trans": "disks", "col": "floppy disk", "ex": "Insert the disk into the computer."},
    "dislike": {"def": "不喜歡、厭惡", "ipa": "/dɪsˈlaɪk/", "trans": "disliked", "col": "dislike doing", "ex": "I dislike hot weather."},
    "dismay": {"def": "沮喪、憂慮、驚慌", "ipa": "/dɪsˈmeɪ/", "trans": "dismayed", "col": "to my dismay", "ex": "Much to my dismay, the store was closed."},
    "dismiss": {"def": "解僱、駁回、解散", "ipa": "/dɪsˈmɪs/", "trans": "dismissal (解僱)", "col": "dismiss from a job", "ex": "The teacher dismissed the class early."},
    "dismissal": {"def": "解僱、駁回、解散", "ipa": "/dɪsˈmɪsl/", "trans": "dismiss (動詞)", "col": "unfair dismissal", "ex": "They are appealing against their dismissal."},
    "disorder": {"def": "混亂、失調、騷亂", "ipa": "/dɪsˈɔːdə/", "trans": "disordered", "col": "mental disorder", "ex": "The room was in great disorder."},
    "dispatch/despatch": {"def": "派遣、派送", "ipa": "/dɪˈspætʃ/", "trans": "dispatched", "col": "dispatch a message", "ex": "The package was dispatched yesterday."},
    "display": {"def": "顯示、陳列、展示", "ipa": "/dɪˈspleɪ/", "trans": "displayed", "col": "on display, computer display", "ex": "Old photos were on display in the hall."},
    "disposable": {"def": "拋棄式的、可自由支配的", "ipa": "/dɪˈspəʊzəbl/", "trans": "dispose (處置)", "col": "disposable cup, disposable income", "ex": "Don't use disposable plastic bags."},
    "disposal": {"def": "處置、配置、廢止", "ipa": "/dɪˈspəʊzl/", "trans": "dispose (動詞)", "col": "waste disposal", "ex": "I am at your disposal."},
    "dispose": {"def": "配置、處置", "ipa": "/dɪˈspəʊz/", "trans": "disposal (名詞), disposable (拋棄式的)", "col": "dispose of", "ex": "You must dispose of the nuclear waste carefully."},
    "dispute": {"def": "爭執、爭端", "ipa": "/dɪˈspjuːt/", "trans": "disputed", "col": "labor dispute, land dispute", "ex": "They are in a dispute over the money."},
    "disregard": {"def": "忽視、漠視", "ipa": "/ˌdɪsrɪˈɡɑːd/", "trans": "disregarded", "col": "disregard the rules", "ex": "Don't disregard her feelings."},
    "disrupt": {"def": "瓦解、中斷、使混亂", "ipa": "/dɪsˈrʌpt/", "trans": "disruption (名詞)", "col": "disrupt the flight", "ex": "The accident disrupted the traffic."},
    "disruption": {"def": "中斷、混亂、瓦解", "ipa": "/dɪsˈrʌpʃn/", "trans": "disrupt (動詞)", "col": "cause disruption", "ex": "The heavy snow caused severe disruption to travel."},
    "dissatisfaction": {"def": "不滿、不平", "ipa": "/ˌdɪsˌsætɪsˈfækʃn/", "trans": "dissatisfied (不滿的)", "col": "express dissatisfaction", "ex": "There is a growing dissatisfaction with the government."},
    "dissatisfy": {"def": "不滿、使不快", "ipa": "/dɪsˈsætɪsfaɪ/", "trans": "dissatisfied, dissatisfaction", "col": "dissatisfied customer", "ex": "The poor service dissatisfied many customers."},
    "dissolve": {"def": "溶解、解散、消失", "ipa": "/dɪˈzɒlv/", "trans": "dissolved", "col": "dissolve in water", "ex": "Sugar dissolves in hot water."},
    "distance": {"def": "距離、遠處", "ipa": "/ˈdɪstəns/", "trans": "distant (遙遠的)", "col": "in the distance", "ex": "The station is at a walking distance."},
    "distant": {"def": "遙遠的、疏遠的", "ipa": "/ˈdɪstənt/", "trans": "distance (名詞)", "col": "distant planet", "ex": "He has a distant dream of traveling the world."},
    "distinct": {"def": "清楚的、截然不同的", "ipa": "/dɪˈstɪŋkt/", "trans": "distinctly, distinction (區別)", "col": "distinct smell", "ex": "Those are two distinct issues."},
    "distinction": {"def": "區別、特質、榮譽", "ipa": "/dɪˈstɪŋkʃn/", "trans": "distinct (形容詞)", "col": "make a distinction", "ex": "There is no clear distinction between the two."},
    "distinctive": {"def": "獨特的、特殊的", "ipa": "/dɪˈstɪŋktɪv/", "trans": "distinctively", "col": "distinctive flavor", "ex": "She has a very distinctive way of speaking."},
    "distinguish": {"def": "區別、識別、變得分傑出", "ipa": "/dɪˈstɪŋɡwɪʃ/", "trans": "distinguished, distinguishable", "col": "distinguish A from B", "ex": "He is so young but can distinguish right from wrong."},
    "distinguished": {"def": "傑出的、著名的", "ipa": "/dɪˈstɪŋɡwɪʃt/", "trans": "distinguish (動詞)", "col": "distinguished scientist", "ex": "He is a distinguished guest of our school."},
    "distort": {"def": "扭曲、曲解", "ipa": "/dɪˈstɔːt/", "trans": "distortion (名詞)", "col": "distort the truth", "ex": "The media distorted the politician's words."},
    "distortions/distortion": {"def": "扭曲、曲解", "ipa": "/dɪˈstɔːʃn/", "trans": "distort (動詞)", "col": "visual distortion", "ex": "The mirror caused a strange distortion of his face."},
    "distract": {"def": "分心、轉移(注意力)", "ipa": "/dɪˈstrækt/", "trans": "distraction (名詞)", "col": "distract from study", "ex": "Don't distract me while I'm driving."},
    "distraction": {"def": "注意力的分散、消遣", "ipa": "/dɪˈstrækʃn/", "trans": "distract (動詞)", "col": "cause distraction", "ex": "I can't work with all these distractions around me."},
    "distress": {"def": "悲傷、危難", "ipa": "/dɪˈstres/", "trans": "distressing (令人憂慮的)", "col": "in distress", "ex": "The ship sent out an SOS signal in distress."},
    "distribute": {"def": "分配、分發", "ipa": "/dɪˈstrɪbjuːt/", "trans": "distribution (分配), distributor (分銷商)", "col": "distribute maps", "ex": "The organizer distributed the task among the members."},
    "distribution": {"def": "分配、發行、分佈", "ipa": "/ˌdɪstrɪˈbjuːʃn/", "trans": "distribute (動詞)", "col": "even distribution", "ex": "What's the population distribution of this country?"},
    "district": {"def": "區域、地區、行政區", "ipa": "/ˈdɪstrɪkt/", "trans": "districts", "col": "business district", "ex": "They live in the business district of the city."},
    "disturb": {"def": "打擾、擾亂", "ipa": "/dɪˈstɜːb/", "trans": "disturbance (名詞), disturbing (令人不安的)", "col": "don't disturb", "ex": "I'm sorry to disturb you so late."},
    "disturbance": {"def": "擾亂、打擾、動亂", "ipa": "/dɪˈstɜːbəns/", "trans": "disturb (動詞)", "col": "cause disturbance", "ex": "The noisy neighbors caused a serious disturbance."},
    "disturbing": {"def": "令人不安的", "ipa": "/dɪˈstɜːbɪŋ/", "trans": "disturb (動詞)", "col": "disturbing news", "ex": "This is very disturbing news indeed."},
    "ditch": {"def": "壕溝、丟棄", "ipa": "/dɪtʃ/", "trans": "ditched", "col": "last-ditch", "ex": "The car went off the road and into a ditch."},
    "dive": {"def": "跳水、潛水", "ipa": "/daɪv/", "trans": "dived/dove, diver", "col": "deep sea diving", "ex": "He dived into the swimming pool."},
    "diver": {"def": "跳水員、潛水員", "ipa": "/ˈdaɪvə/", "trans": "divers", "col": "deep-sea diver", "ex": "The diver found an old treasure under the sea."},
    "divide": {"def": "劃分、除", "ipa": "/dɪˈvaɪd/", "trans": "divided, division (名詞)", "col": "divide into", "ex": "The apple was divided into four pieces."},
    "divine": {"def": "神聖的、非凡的", "ipa": "/dɪˈvaɪn/", "trans": "divinity", "col": "divine intervention", "ex": "The temple is dedicated to a divine being."},
    "division": {"def": "部分、除法、分部", "ipa": "/dɪˈvɪʒn/", "trans": "divide (動詞)", "col": "division of labor", "ex": "His work is in the international division."},
    "divorce": {"def": "離婚", "ipa": "/dɪˈvɔːs/", "trans": "divorced", "col": "get a divorce", "ex": "They decided to get a divorce."},
    "dizzy": {"def": "頭暈的", "ipa": "/ˈdɪzi/", "trans": "dizziness", "col": "feel dizzy", "ex": "I felt a bit dizzy after the long walk."},
    "do": {"def": "做、行、完成", "ipa": "/duː/", "trans": "did, done", "col": "do housework, do one's best", "ex": "What are you doing?"},
    "dock": {"def": "碼頭、船塢、對放", "ipa": "/dɒk/", "trans": "docked", "col": "floating dock", "ex": "The ship is in the dock for repairs."},
    "doctor/dr.": {"def": "醫生、博士", "ipa": "/ˈdɒktə/", "trans": "doctors", "col": "see a doctor", "ex": "My dream is to become a doctor."},
    "doctrine": {"def": "教義、主義、學說", "ipa": "/ˈdɒktrɪn/", "trans": "doctrines", "col": "religious doctrine", "ex": "He follows the religious doctrine strictly."},
    "document": {"def": "文件、公文", "ipa": "/ˈdɒkjumənt/", "trans": "documented, documentary (紀錄片)", "col": "legal document", "ex": "Please sign this important document."},
    "documentary": {"def": "紀錄片、紀實的", "ipa": "/ˌdɒkjuˈmentri/", "trans": "documentaries", "col": "nature documentary", "ex": "We watched a documentary on wild animals tonight."},
    "dodge": {"def": "閃躲、避開", "ipa": "/dɒdʒ/", "trans": "dodged", "col": "dodge a ball", "ex": "He dodged the ball and laughed."},
    "dog": {"def": "狗", "ipa": "/dɒɡ/", "trans": "dogs", "col": "pet dog, hot dog", "ex": "The dog is barking at the stranger."},
    "doll": {"def": "玩偶、洋娃娃", "ipa": "/dɒl/", "trans": "dolls", "col": "barbie doll", "ex": "The little girl is playing with her doll."},
    "dollar": {"def": "元 (貨幣)", "ipa": "/ˈdɒlə/", "trans": "dollars", "col": "ten dollars", "ex": "The shirt costs twenty dollars."},
    "dolphin": {"def": "海豚", "ipa": "/ˈdɒlfɪn/", "trans": "dolphins", "col": "wild dolphin", "ex": "Dolphins are very intelligent animals."},
    "domain": {"def": "領域、領地、網域", "ipa": "/dəˈmeɪn/", "trans": "domains", "col": "public domain", "ex": "Calculus is in the domain of mathematics."},
    "domestic": {"def": "國內的、家庭的、馴養的", "ipa": "/dəˈmestɪk/", "trans": "domestically", "col": "domestic flight, domestic animal", "ex": "Cats are domestic animals."},
    "dominant": {"def": "佔優勢的、支配的", "ipa": "/ˈdɒmɪnənt/", "trans": "dominate (動詞)", "col": "dominant culture", "ex": "She has a dominant personality."},
    "dominate": {"def": "支配、統治、俯瞰", "ipa": "/ˈdɒmɪneɪt/", "trans": "dominated, dominant", "col": "dominate the market", "ex": "The mountain dominates the landscape."},
    "donation": {"def": "捐贈、捐款", "ipa": "/dəʊˈneɪʃn/", "trans": "donate (動詞)", "col": "make a donation", "ex": "They made a large donation to charity."},
    "donkey": {"def": "驢子、笨蛋", "ipa": "/ˈdɒŋki/", "trans": "donkeys", "col": "ride a donkey", "ex": "Donkeys are very strong animals."},
    "donor": {"def": "捐贈者", "ipa": "/ˈdəʊnə/", "trans": "donors", "col": "blood donor, organ donor", "ex": "The identity of the donor is secret."},
    "door": {"def": "門", "ipa": "/dɔː/", "trans": "doors", "col": "open the door, front door", "ex": "Please lock the door when you leave."},
    "doorbell": {"def": "門鈴", "ipa": "/ˈdɔːbel/", "trans": "doorbells", "col": "ring the doorbell", "ex": "The doorbell is ringing."},
    "doorway": {"def": "門口、出入口", "ipa": "/ˈdɔːweɪ/", "trans": "doorways", "col": "stand in the doorway", "ex": "He was standing in the doorway of his room."},
    "dormitory/dorm": {"def": "宿舍", "ipa": "/ˈdɔːmətri/", "trans": "dormitories", "col": "college dormitory", "ex": "He lives in a college dormitory."},
    "dosage/dose": {"def": "劑量、服用", "ipa": "/dəʊs/", "trans": "doses", "col": "daily dose", "ex": "Take one dose after each meal."},
    "dot": {"def": "點、小圓點", "ipa": "/dɒt/", "trans": "dotted", "col": "dot com", "ex": "Join the dots to complete the picture."},
    "double": {"def": "兩倍的、雙倍的", "ipa": "/ˈdʌbl/", "trans": "doubled", "col": "double room, double check", "ex": "The population has doubled in ten years."},
    "doubt": {"def": "懷疑", "ipa": "/daʊt/", "trans": "doubtful, doubtless", "col": "no doubt, beyond doubt", "ex": "There is no doubt about it."},
    "doubtful": {"def": "懷疑的、不明確的", "ipa": "/ˈdaʊtfl/", "trans": "doubt (名詞/動詞)", "col": "be doubtful about", "ex": "It's doubtful whether he will come or not."},
    "doughnut/donut": {"def": "甜甜圈", "ipa": "/ˈdəʊnʌt/", "trans": "doughnuts", "col": "chocolate doughnut", "ex": "I like strawberry donuts best."},
    "dove": {"def": "白鴿、和平愛好者", "ipa": "/dʌv/", "trans": "doves", "col": "peace dove", "ex": "The dove is a symbol of peace."},
    "down": {"def": "向下、在下面", "ipa": "/daʊn/", "trans": "無", "col": "downstairs, sit down", "ex": "He sat down on the chair."},
    "downstairs": {"def": "樓下", "ipa": "/ˌdaʊnˈsteəz/", "trans": "無", "col": "go downstairs", "ex": "She is downstairs in the kitchen."},
    "downtown": {"def": "市中心、鬧區", "ipa": "/ˌdaʊnˈtaʊn/", "trans": "無", "col": "go downtown", "ex": "He works in downtown London."},
    "downward": {"def": "向下的", "ipa": "/ˈdaʊnwəd/", "trans": "downwards", "col": "downward trend", "ex": "The economy showed a downward trend."},
}

with open("batch_l1_p12.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART12, f, ensure_ascii=False, indent=2)
