import json

# Level 1 Part 3: (Ape - Basic)
L1_PART3 = {
    "ape": {"def": "猿類", "ipa": "/eɪp/", "trans": "apes", "col": "great ape", "ex": "Chimpanzees and gorillas are apes."},
    "appearance": {"def": "外貌、出現", "ipa": "/əˈpɪərəns/", "trans": "appear (動詞)", "col": "physical appearance", "ex": "Don't judge a book by its appearance."},
    "appetite": {"def": "胃口、食慾", "ipa": "/ˈæpɪtaɪt/", "trans": "appetizing (令人胃口大開的)", "col": "have a good appetite", "ex": "Exercise gives you a good appetite."},
    "apple": {"def": "蘋果", "ipa": "/ˈæpl/", "trans": "apples", "col": "apple pie", "ex": "An apple a day keeps the doctor away."},
    "appliance": {"def": "家用電器", "ipa": "/əˈplaɪəns/", "trans": "appliances", "col": "household appliance", "ex": "A fridge is a common household appliance."},
    "apply": {"def": "申請、塗抹、應用", "ipa": "/əˈplaɪ/", "trans": "application (名詞), applicant (申請人)", "col": "apply for a job", "ex": "I want to apply for this position."},
    "appoint": {"def": "任命、約定", "ipa": "/əˈpɔɪnt/", "trans": "appointment (預約)", "col": "appoint someone as manager", "ex": "The committee appointed him as leader."},
    "appointment": {"def": "預約、任命", "ipa": "/əˈpɔɪntmənt/", "trans": "appoint (動詞)", "col": "make an appointment", "ex": "I have a dentist appointment at 3 p.m."},
    "appreciate": {"def": "感激、欣賞", "ipa": "/əˈpriːʃieɪt/", "trans": "appreciation (名詞)", "col": "I appreciate your help", "ex": "We really appreciate everything you've done."},
    "approach": {"def": "接近、方法", "ipa": "/əˈprəʊtʃ/", "trans": "approachable (可親近的)", "col": "a new approach to", "ex": "The summer is approaching."},
    "appropriate": {"def": "適當的", "ipa": "/əˈprəʊpriət/", "trans": "appropriately", "col": "appropriate behavior", "ex": "Is this outfit appropriate for a wedding?"},
    "approval": {"def": "贊成、核准", "ipa": "/əˈpruːvl/", "trans": "approve (動詞)", "col": "letter of approval", "ex": "The project received official approval."},
    "approve": {"def": "贊成、核准", "ipa": "/əˈpruːv/", "trans": "approved, approval", "col": "approve of", "ex": "My parents don't approve of my new friend."},
    "apricot": {"def": "杏桃", "ipa": "/ˈeɪprɪkɒt/", "trans": "apricots", "col": "dried apricot", "ex": "She likes to eat sweet apricots."},
    "April": {"def": "四月", "ipa": "/ˈeɪprəl/", "trans": "無", "col": "April Fools' Day", "ex": "It often rains in April."},
    "apron": {"def": "圍裙", "ipa": "/ˈeɪprən/", "trans": "aprons", "col": "wear an apron", "ex": "Put on an apron before you start cooking."},
    "arch": {"def": "拱門、拱形", "ipa": "/ɑːtʃ/", "trans": "arches", "col": "stone arch", "ex": "The bridge has a narrow stone arch."},
    "area": {"def": "區域、面積", "ipa": "/ˈeəriə/", "trans": "areas", "col": "in this area", "ex": "There are many trees in this area."},
    "argue": {"def": "爭論、主張", "ipa": "/ˈɑːɡjuː/", "trans": "argument (名詞)", "col": "argue with someone", "ex": "They are always arguing about money."},
    "argument": {"def": "爭論、引數", "ipa": "/ˈɑːɡjumənt/", "trans": "argue (動詞)", "col": "have an argument", "ex": "The argument lasted for two hours."},
    "arise": {"def": "出現、發生", "ipa": "/əˈraɪz/", "trans": "arose, arisen", "col": "problems arise", "ex": "A new difficulty has arisen."},
    "arithmetic": {"def": "算術", "ipa": "/əˈrɪθmətɪk/", "trans": "arithmetical", "col": "simple arithmetic", "ex": "He is very good at mental arithmetic."},
    "arm": {"def": "手臂、武裝", "ipa": "/ɑːm/", "trans": "arms", "col": "shake arms", "ex": "She fell and broke her arm."},
    "armchair": {"def": "扶手椅", "ipa": "/ˈɑːmtʃeə/", "trans": "armchairs", "col": "sit in a comfortable armchair", "ex": "He likes reading in his favorite armchair."},
    "army": {"def": "軍隊", "ipa": "/ˈɑːmi/", "trans": "armies", "col": "join the army", "ex": "He served in the army for three years."},
    "around": {"def": "在...周圍、大約", "ipa": "/əˈraʊnd/", "trans": "無", "col": "around the corner", "ex": "I'll see you around 5 o'clock."},
    "arouse": {"def": "喚起、激起", "ipa": "/əˈraʊz/", "trans": "aroused, arousing", "col": "arouse someone's curiosity", "ex": "The noise aroused the sleeping child."},
    "arrange": {"def": "安排、整理", "ipa": "/əˈreɪndʒ/", "trans": "arrangement (名詞)", "col": "arrange flowers, arrange a meeting", "ex": "We arranged to meet at the station."},
    "arrangement": {"def": "安排、備置", "ipa": "/əˈreɪndʒmənt/", "trans": "arrange (動詞)", "col": "make arrangements for", "ex": "The flower arrangements were beautiful."},
    "arrest": {"def": "逮捕", "ipa": "/əˈrest/", "trans": "arrested, arresting", "col": "arrest a thief", "ex": "He was arrested for speeding."},
    "arrival": {"def": "到達、抵達者", "ipa": "/əˈraɪvl/", "trans": "arrive (動詞)", "col": "on arrival", "ex": "Expect the arrival of the next bus."},
    "arrive": {"def": "到達", "ipa": "/əˈraɪv/", "trans": "arrived, arrival", "col": "arrive at/in", "ex": "When did you arrive home?"},
    "arrow": {"def": "箭、箭頭", "ipa": "/ˈærəʊ/", "trans": "arrows", "col": "bow and arrow", "ex": "Follow the arrow to the exit."},
    "art": {"def": "藝術", "ipa": "/ɑːt/", "trans": "artist (藝術家), artistic (藝術的)", "col": "work of art", "ex": "Modern art can be hard to understand."},
    "article": {"def": "文章、冠詞、物品", "ipa": "/ˈɑːtɪkl/", "trans": "articles", "col": "newspaper article", "ex": "I read an interesting article on health."},
    "artificial": {"def": "人造的", "ipa": "/ˌɑːtɪˈfɪʃl/", "trans": "artificially", "col": "artificial intelligence, artificial flowers", "ex": "The island is completely artificial."},
    "artist": {"def": "藝術家", "ipa": "/ˈɑːtɪst/", "trans": "artistic, artistically", "col": "talented artist", "ex": "She wants to be a professional artist."},
    "artistic": {"def": "藝術的", "ipa": "/ɑːˈtɪstɪk/", "trans": "artist (名詞)", "col": "artistic talent", "ex": "The dancer has great artistic flair."},
    "as": {"def": "如同、作為", "ipa": "/æz/", "trans": "無", "col": "as soon as, as if", "ex": "He works as a lawyer."},
    "ash": {"def": "灰、灰燼", "ipa": "/æʃ/", "trans": "ashes", "col": "volcanic ash", "ex": "Cigarette ash was all over the carpet."},
    "ashamed": {"def": "羞愧的", "ipa": "/əˈʃeɪmd/", "trans": "shame (名詞/動詞)", "col": "be ashamed of", "ex": "You should be ashamed of yourself."},
    "Asia": {"def": "亞洲", "ipa": "/ˈeɪʒə/", "trans": "Asian (亞洲人/的)", "col": "Southeast Asia", "ex": "Japan is a country in Asia."},
    "Asian": {"def": "亞洲的、亞洲人", "ipa": "/ˈeɪʒn/", "trans": "Asians", "col": "Asian culture", "ex": "She likes Asian cuisine."},
    "aside": {"def": "在旁邊", "ipa": "/əˈsaɪd/", "trans": "無", "col": "set aside, stand aside", "ex": "He moved the box aside to enter."},
    "ask": {"def": "詢問、請求", "ipa": "/ɑːsk/", "trans": "asked, asking", "col": "ask for help, ask a question", "ex": "May I ask you something?"},
    "asleep": {"def": "睡著的", "ipa": "/əˈsliːp/", "trans": "sleep (動詞/名詞)", "col": "fall asleep", "ex": "The baby is fast asleep."},
    "aspect": {"def": "方面、層面", "ipa": "/ˈæspekt/", "trans": "aspects", "col": "every aspect of life", "ex": "This is a very important aspect of his personality."},
    "aspirin": {"def": "阿斯匹靈", "ipa": "/ˈæsprɪn/", "trans": "無", "col": "take an aspirin", "ex": "I take two aspirins for my headache."},
    "ass": {"def": "驢子、蠢人", "ipa": "/æs/", "trans": "asses", "col": "make an ass of oneself", "ex": "Don't be such a silly ass."},
    "assemble": {"def": "組成、集合", "ipa": "/əˈsembl/", "trans": "assembly (名詞)", "col": "assemble a machine", "ex": "All students must assemble in the hall."},
    "assembly": {"def": "集會、裝配", "ipa": "/əˈsembli/", "trans": "assemblies", "col": "school assembly, car assembly", "ex": "The group held a major assembly."},
    "assign": {"def": "分配、指派", "ipa": "/əˈsaɪn/", "trans": "assignment (任務)", "col": "assign homework", "ex": "The teacher assigned us a new project."},
    "assignment": {"def": "任務、作業", "ipa": "/əˈsaɪnmənt/", "trans": "assign (動詞)", "col": "daily assignment", "ex": "He finally completed the assignment."},
    "assist": {"def": "幫助、協助", "ipa": "/əˈsɪst/", "trans": "assistant (助手), assistance (名詞)", "col": "assist someone with", "ex": "Can you assist me with these bags?"},
    "assistance": {"def": "協助、援助", "ipa": "/əˈsɪstəns/", "trans": "assist (動詞)", "col": "financial assistance", "ex": "Do you need any further assistance?"},
    "assistant": {"def": "助理、店員", "ipa": "/əˈsɪstənt/", "trans": "assistants", "col": "shop assistant, teaching assistant", "ex": "She is the manager's personal assistant."},
    "associate": {"def": "關聯、合夥人", "ipa": "/əˈsəʊsieɪt/", "trans": "association (協會)", "col": "be associated with", "ex": "We associate blue with the sky."},
    "association": {"def": "協會、關聯", "ipa": "/əˌsəʊsiˈeɪʃn/", "trans": "associate (動詞)", "col": "football association", "ex": "He is a member of the heart association."},
    "assume": {"def": "假設、採取", "ipa": "/əˈsjuːm/", "trans": "assumption (名詞)", "col": "assume responsibility", "ex": "I assume that you are tired."},
    "assurance": {"def": "保證、信心", "ipa": "/əˈʃʊərəns/", "trans": "assure (動詞)", "col": "self-assurance", "ex": "She gave me a quiet assurance that everything's ok."},
    "assure": {"def": "向...保證", "ipa": "/əˈʃʊə/", "trans": "assuredly (無疑地)", "col": "assure someone that", "ex": "I can assure you that the info is correct."},
    "astonish": {"def": "使驚訝", "ipa": "/əˈstɒnɪʃ/", "trans": "astonished, astonishing", "col": "astonish everyone", "ex": "Her success astonished her friends."},
    "astronaut": {"def": "太空人", "ipa": "/ˈæstrənɔːt/", "trans": "astronauts", "col": "american astronaut", "ex": "He dreamed of becoming an astronaut."},
    "astronomy": {"def": "天文學", "ipa": "/əˈstrɒnəmi/", "trans": "astronomer (天文學家)", "col": "study astronomy", "ex": "He is deeply interested in astronomy."},
    "at": {"def": "在...", "ipa": "/æt/", "trans": "無", "col": "at home, at night", "ex": "I'll meet you at the gate."},
    "athlete": {"def": "運動員", "ipa": "/ˈæθliːt/", "trans": "athletic (運動的)", "col": "professional athlete", "ex": "He is a top athlete in his school."},
    "athletic": {"def": "運動的、體育的", "ipa": "/æθˈletɪk/", "trans": "athlete (名詞)", "col": "athletic club", "ex": "She has strong athletic abilities."},
    "Atlantic": {"def": "大西洋的", "ipa": "/ətˈlæntɪk/", "trans": "無", "col": "the Atlantic Ocean", "ex": "They sailed across the Atlantic."},
    "atmosphere": {"def": "大氣、氣氛", "ipa": "/ˈætməsfɪə/", "trans": "atmospheric (大氣的)", "col": "friendly atmosphere", "ex": "The planet has a thin atmosphere."},
    "atom": {"def": "原子", "ipa": "/ˈætəm/", "trans": "atomic (原子的)", "col": "atom bomb", "ex": "Water is made of hydrogen and oxygen atoms."},
    "atomic": {"def": "原子的", "ipa": "/əˈtɒmɪk/", "trans": "atom (名詞)", "col": "atomic energy", "ex": "The country is developing atomic power."},
    "attach": {"def": "附上、依附", "ipa": "/əˈtætʃ/", "trans": "attachment (附件)", "col": "attach a file", "ex": "Please attach your photo to the form."},
    "attachment": {"def": "附件、依戀", "ipa": "/əˈtætʃmənt/", "trans": "attach (動詞)", "col": "email attachment", "ex": "See the attachment for more details."},
    "attack": {"def": "攻擊", "ipa": "/əˈtæk/", "trans": "attacked, attacker", "col": "heart attack, cyber attack", "ex": "The dog attacked the mailman."},
    "attain": {"def": "達成、獲得", "ipa": "/əˈteɪn/", "trans": "attainment (成就)", "col": "attain a goal", "ex": "Few people attain this level of success."},
    "attempt": {"def": "企圖、嘗試", "ipa": "/əˈtempt/", "trans": "attempted", "col": "first attempt", "ex": "I made an attempt to solve the puzzle."},
    "attend": {"def": "出席、參加、照顧", "ipa": "/əˈtend/", "trans": "attendance (出席), attendant (服務員)", "col": "attend a meeting, attend to", "ex": "Did you attend the lecture?"},
    "attendance": {"def": "出席(次數)", "ipa": "/əˈtendəns/", "trans": "attend (動詞)", "col": "high attendance", "ex": "Attendance at the meeting was poor."},
    "attendant": {"def": "服務員、侍從", "ipa": "/əˈtendənt/", "trans": "attend (動詞)", "col": "flight attendant", "ex": "The car park attendant helped us."},
    "attention": {"def": "注意力", "ipa": "/əˈtenʃn/", "trans": "attentive (細心的)", "col": "pay attention to", "ex": "Give me your full attention."},
    "attentive": {"def": "細心的、注意的", "ipa": "/əˈtentɪv/", "trans": "attentively (副詞)", "col": "attentive listener", "ex": "The students were very attentive."},
    "attitude": {"def": "態度", "ipa": "/ˈætɪtjuːd/", "trans": "attitudes", "col": "positive attitude", "ex": "He has a very negative attitude."},
    "attract": {"def": "吸引", "ipa": "/əˈtrækt/", "trans": "attraction (吸引力), attractive (有吸引力的)", "col": "attract customers", "ex": "The flowers attract bees."},
    "attraction": {"def": "吸引力、景點", "ipa": "/əˈtrækʃn/", "trans": "attract (動詞)", "col": "tourist attraction", "ex": "The park is a major local attraction."},
    "attractive": {"def": "有吸引力的", "ipa": "/əˈtræktɪv/", "trans": "attract (動詞), attractively (副詞)", "col": "highly attractive", "ex": "She has an attractive smile."},
    "attribute": {"def": "屬性、歸因於", "ipa": "/ˈætrɪbjuːt/", "trans": "attribution (歸因)", "col": "attribute A to B", "ex": "Kindness is his best attribute."},
    "audience": {"def": "觀眾、聽眾", "ipa": "/ˈɔːdiəns/", "trans": "audiences", "col": "large audience", "ex": "The audience cheered for the dancer."},
    "August": {"def": "八月", "ipa": "/ˈɔːɡəst/", "trans": "無", "col": "in August", "ex": "Schools start in late August."},
    "aunt/auntie": {"def": "阿姨、姑姑", "ipa": "/ɑːnt/", "trans": "aunts", "col": "travel with aunt", "ex": "My aunt lives in London."},
    "Australia": {"def": "澳洲", "ipa": "/ɒˈstreɪliə/", "trans": "Australian (澳洲人/的)", "col": "trip to Australia", "ex": "Sydney is the largest city in Australia."},
    "Australian": {"def": "澳洲的、澳洲人", "ipa": "/ɒˈstreɪliən/", "trans": "Australians", "col": "Australian accent", "ex": "Have you ever met an Australian?"},
    "author": {"def": "作者", "ipa": "/ˈɔːθə/", "trans": "authority (權威)", "col": "famous author", "ex": "Who is the author of this book?"},
    "authority": {"def": "權威、當局", "ipa": "/ɔːˈθɒrəti/", "trans": "authorities", "col": "health authority", "ex": "You have no authority to tell me what to do."},
    "automatic": {"def": "自動的", "ipa": "/ˌɔːtəˈmætɪk/", "trans": "automatically", "col": "automatic door", "ex": "The car has an automatic transmission."},
    "automobile/auto": {"def": "汽車", "ipa": "/ˈɔːtəməbiːl/", "trans": "automobiles", "col": "automobile industry", "ex": "The auto industry is booming."},
    "autumn/fall": {"def": "秋天", "ipa": "/ˈɔːtəm/", "trans": "autumnal", "col": "colors of autumn", "ex": "The leaves turn red in autumn."},
    "available": {"def": "可利用的、有空的", "ipa": "/əˈveɪləbl/", "trans": "availability (名詞)", "col": "is available for", "ex": "This dress is available in three colors."},
    "avenue": {"def": "大道", "ipa": "/ˈævənjuː/", "trans": "avenues", "col": "Fifth Avenue", "ex": "They walked along a tree-lined avenue."},
    "average": {"def": "平均的", "ipa": "/ˈævərɪdʒ/", "trans": "averages", "col": "on average, above average", "ex": "The average age of the group is 20."},
    "avoid": {"def": "避免", "ipa": "/əˈvɔɪd/", "trans": "avoidable, avoidance", "col": "avoid contact", "ex": "Try to avoid eating junk food."},
    "await": {"def": "等待", "ipa": "/əˈweɪt/", "trans": "無", "col": "await results", "ex": "We are awaiting your reply."},
    "awake": {"def": "醒著的", "ipa": "/əˈweɪk/", "trans": "awaken (喚醒)", "col": "wide awake", "ex": "Is he awake yet?"},
    "awaken": {"def": "喚醒", "ipa": "/əˈweɪkən/", "trans": "awakening", "col": "awaken someone from sleep", "ex": "She was awakened by the noise."},
    "award": {"def": "獎項", "ipa": "/əˈwɔːd/", "trans": "awards", "col": "win an award", "ex": "The film won several awards."},
    "aware": {"def": "察覺的、意識到的", "ipa": "/əˈweə/", "trans": "awareness (意識)", "col": "be aware of", "ex": "Are you aware of the danger?"},
    "awareness": {"def": "意識、察覺", "ipa": "/əˈweənəs/", "trans": "aware (形容詞)", "col": "raise awareness", "ex": "The campaign aims to raise environmental awareness."},
    "away": {"def": "遠離、不在", "ipa": "/əˈweɪ/", "trans": "無", "col": "far away, go away", "ex": "The station is two miles away."},
    "awesome": {"def": "極好的、令人敬畏的", "ipa": "/ˈɔːsəm/", "trans": "awesomely", "col": "awesome sight", "ex": "The view from the mountain was awesome."},
    "awful": {"def": "糟透的", "ipa": "/ˈɔːfl/", "trans": "awfully", "col": "awful weather", "ex": "The food tasted awful."},
    "awkward": {"def": "尷尬的、笨拙的", "ipa": "/ˈɔːkwəd/", "trans": "awkwardly", "col": "awkward silence", "ex": "There was an awkward silence in the room."},
    "axe": {"def": "斧頭", "ipa": "/æks/", "trans": "axes", "col": "cut with an axe", "ex": "He chopped wood with an axe."},
    "baby": {"def": "嬰兒", "ipa": "/ˈbeɪbi/", "trans": "babies", "col": "baby boy", "ex": "The baby is crying for milk."},
    "babysit": {"def": "當保姆", "ipa": "/ˈbeɪbisɪt/", "trans": "babysitter", "col": "babysit for someone", "ex": "She babysits for her neighbors on weekends."},
    "babysitter": {"def": "保姆", "ipa": "/ˈbeɪbisɪtə/", "trans": "babysitters", "col": "need a babysitter", "ex": "They hired a babysitter for the evening."},
    "bachelor": {"def": "單身漢、學士", "ipa": "/ˈbætʃələ/", "trans": "bachelors", "col": "bachelor's degree", "ex": "He decided to remain a bachelor for life."},
    "back": {"def": "後面、回來", "ipa": "/bæk/", "trans": "backward (向後)", "col": "back and forth, get back", "ex": "She has a pain in her back."},
    "backbone": {"def": "脊椎、支柱", "ipa": "/ˈbæk bəʊn/", "trans": "backbones", "col": "the backbone of", "ex": "Agriculture is the backbone of the economy."},
    "background": {"def": "背景", "ipa": "/ˈbækɡraʊnd/", "trans": "backgrounds", "col": "educational background", "ex": "The mountains are in the background of the photo."},
    "backpack": {"def": "背包", "ipa": "/ˈbækpæk/", "trans": "backpacks", "col": "go backpacking", "ex": "He packed everything into his backpack."},
    "backward": {"def": "向後的", "ipa": "/ˈbæk wəd/", "trans": "backwards", "col": "step backward", "ex": "She took a step backward in surprise."},
    "bacon": {"def": "培根", "ipa": "/ˈbeɪkən/", "trans": "無", "col": "eggs and bacon", "ex": "I like bacon for breakfast."},
    "bacteria": {"def": "細菌", "ipa": "/bækˈtɪəriə/", "trans": "bacterium (單數)", "col": "harmful bacteria", "ex": "Keep your hands clean to avoid bacteria."},
    "bad": {"def": "壞的", "ipa": "/bæd/", "trans": "worse, worst", "col": "bad habit, bad mood", "ex": "Smoking is bad for your health."},
    "badly": {"def": "糟糕地", "ipa": "/ˈbædli/", "trans": "bad (形容詞)", "col": "need something badly", "ex": "The car was badly damaged."},
    "badminton": {"def": "羽毛球", "ipa": "/ˈbædmɪntən/", "trans": "無", "col": "play badminton", "ex": "We play badminton every Saturday."},
    "bag": {"def": "袋子", "ipa": "/bæɡ/", "trans": "bags", "col": "sleeping bag, handbag", "ex": "I am carrying a heavy bag."},
    "baggage/luggage": {"def": "行李", "ipa": "/ˈbæɡɪdʒ/", "trans": "無 (不可數)", "col": "checked baggage", "ex": "How many pieces of baggage do you have?"},
    "bake": {"def": "烘烤", "ipa": "/beɪk/", "trans": "baker (烘焙師), bakery (烘焙坊)", "col": "bake a cake", "ex": "Fresh bread was baking in the oven."},
    "bakery": {"def": "麵包店", "ipa": "/ˈbeɪkəri/", "trans": "bakeries", "col": "neighborhood bakery", "ex": "Go buy some bread from the bakery."},
    "balance": {"def": "平衡、餘額", "ipa": "/ˈbæləns/", "trans": "balanced (平衡的)", "col": "keep one's balance, bank balance", "ex": "She lost her balance and fell."},
    "balcony": {"def": "陽台", "ipa": "/ˈbælkəni/", "trans": "balconies", "col": "stand on the balcony", "ex": "We sat on the balcony to watch the sunset."},
    "bald": {"def": "禿頭的", "ipa": "/bɔːld/", "trans": "baldness", "col": "go bald", "ex": "He's going bald on top."},
    "ball": {"def": "球、舞會", "ipa": "/bɔːl/", "trans": "balls", "col": "play ball", "ex": "Throw the ball to me."},
    "ballet": {"def": "芭蕾舞", "ipa": "/ˈbæleɪ/", "trans": "ballets", "col": "ballet dancer", "ex": "She has been learning ballet since she was five."},
    "balloon": {"def": "氣球", "ipa": "/bəˈluːn/", "trans": "balloons", "col": "hot air balloon", "ex": "The child let go of the balloon."},
    "ballot": {"def": "投票、選票", "ipa": "/ˈbælət/", "trans": "ballots", "col": "secret ballot", "ex": "The issue will be decided by ballot."},
    "bamboo": {"def": "竹子", "ipa": "/ˌbæmˈbuː/", "trans": "bamboos", "col": "bamboo forest", "ex": "Pandas mostly eat bamboo."},
    "ban": {"def": "禁令、禁止", "ipa": "/bæn/", "trans": "banned", "col": "total ban on", "ex": "The government placed a ban on smoking indoors."},
    "banana": {"def": "香蕉", "ipa": "/bəˈnɑːnə/", "trans": "bananas", "col": "ripe banana", "ex": "He eats a banana every morning."},
    "band": {"def": "樂團、條、頻譜", "ipa": "/bænd/", "trans": "bands", "col": "rock band", "ex": "The band played all night long."},
    "bandage": {"def": "繃帶", "ipa": "/ˈbændɪdʒ/", "trans": "bandages", "col": "wrap a bandage", "ex": "The nurse put a bandage on his arm."},
    "bank": {"def": "銀行、岸", "ipa": "/bæŋk/", "trans": "banker (銀行家)", "col": "river bank, savings bank", "ex": "I need to go to the bank to get some money."},
    "banker": {"def": "銀行家", "ipa": "/ˈbæŋkə/", "trans": "bankers", "col": "investment banker", "ex": "He is a successful banker in London."},
    "bankrupt": {"def": "破產的", "ipa": "/ˈbæŋkrʌpt/", "trans": "bankruptcy (名詞)", "col": "go bankrupt", "ex": "The company went bankrupt last year."},
    "banner": {"def": "旗幟、橫幅", "ipa": "/ˈbænə/", "trans": "banners", "col": "protest banner", "ex": "Large banners were hanging above the street."},
    "bar": {"def": "條、棒、酒吧、法院", "ipa": "/bɑː/", "trans": "bars", "col": "chocolate bar, behind bars", "ex": "He went to a bar for a drink."},
    "barbecue/BBQ": {"def": "燒烤", "ipa": "/ˈbɑːbɪkjuː/", "trans": "barbecues", "col": "have a barbecue", "ex": "We had a barbecue in the backyard."},
    "barber": {"def": "理髮師", "ipa": "/ˈbɑːbə/", "trans": "barbershop (理髮店)", "col": "go to the barber", "ex": "The barber cut his hair yesterday."},
    "bare": {"def": "裸露的、赤裸的", "ipa": "/beə/", "trans": "barely (僅僅)", "col": "bare feet, bare hands", "ex": "He walked on the sand with bare feet."},
    "barely": {"def": "僅僅、幾乎不", "ipa": "/ˈbeəli/", "trans": "bare (形容詞)", "col": "barely enough", "ex": "I could barely see through the fog."},
    "bargain": {"def": "交易、特價品", "ipa": "/ˈbɑːɡən/", "trans": "bargained", "col": "a real bargain", "ex": "This shirt was a real bargain at $10."},
    "bark": {"def": "吠叫、樹皮", "ipa": "/bɑːk/", "trans": "barked, barking", "col": "dogs bark", "ex": "The dog barked at the stranger."},
    "barn": {"def": "穀倉", "ipa": "/bɑːn/", "trans": "barns", "col": "red barn", "ex": "They stored the hay in the barn."},
    "barrel": {"def": "木桶、管子", "ipa": "/ˈbærəl/", "trans": "barrels", "col": "wine barrel", "ex": "They stored the beer in a large barrel."},
    "barrier": {"def": "障礙、屏障", "ipa": "/ˈbæriə/", "trans": "barriers", "col": "language barrier", "ex": "Money is the main barrier to my study."},
    "base": {"def": "基地、基礎", "ipa": "/beɪs/", "trans": "baseless (無根據的)", "col": "military base, home base", "ex": "The lamp has a heavy base."},
    "baseball": {"def": "棒球", "ipa": "/ˈbeɪsbɔːl/", "trans": "無", "col": "play baseball", "ex": "Baseball is very popular in Taiwan."},
    "basic": {"def": "基礎的", "ipa": "/ˈbeɪsɪk/", "trans": "basically, basics (基本原則)", "col": "basic needs, basic skills", "ex": "Computer skills are basic for most jobs."},
}

with open("batch_l1_p3.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART3, f, ensure_ascii=False, indent=2)
