import json

# Level 1 Part 30: (Master - Mild)
L1_PART30 = {
    "master": {"def": "主人、大師、精通、征服", "ipa": "/ˈmɑːstə/", "trans": "mastered, mastery, masterpiece", "col": "master's degree, master of arts", "ex": "He is a master of martial arts."},
    "masterpiece": {"def": "傑作、名著", "ipa": "/ˈmɑːstəpiːs/", "trans": "masterpieces", "col": "literary masterpiece", "ex": "The painting is a masterpiece."},
    "masterwork": {"def": "傑作、名作", "ipa": "/ˈmɑːstəwɜːk/", "trans": "masterworks", "col": "cultural masterwork", "ex": "The novel is considered a masterwork."},
    "mastery": {"def": "熟練、支配、優勢", "ipa": "/ˈmɑːstəri/", "trans": "master (動詞)", "col": "mastery of English", "ex": "She has a good mastery of English."},
    "mat": {"def": "墊子、草蓆、墊子狀物", "ipa": "/mæt/", "trans": "mats", "col": "floor mat, door mat", "ex": "Wipe your feet on the mat."},
    "match": {"def": "比賽、對手、火柴、相配", "ipa": "/mætʃ/", "trans": "matched, matcher", "col": "box of matches, close match", "ex": "He is a good match for me."},
    "matching": {"def": "相配的、一致的", "ipa": "/ˈmætʃɪŋ/", "trans": "match (動詞)", "col": "matching colors", "ex": "They are wearing matching outfits."},
    "mate": {"def": "伴侶、夥伴、交配", "ipa": "/meɪt/", "trans": "mated", "col": "soul mate, room mate", "ex": "He is my best mate."},
    "material": {"def": "材料、物質、教材、物質的", "ipa": "/məˈtɪəriəl/", "trans": "materials, materiality", "col": "raw material, construction material", "ex": "The dress is made of soft material."},
    "materialistic": {"def": "唯物主義的、重實利的", "ipa": "/məˌtɪəriəˈlɪstɪk/", "trans": "materialism", "col": "materialistic society", "ex": "He has a very materialistic outlook on life."},
    "maternal": {"def": "母親的、母系的", "ipa": "/məˈtɜːnl/", "trans": "maternally", "col": "maternal instinct, maternal side", "ex": "She has strong maternal feelings."},
    "mathematic/mathematical": {"def": "數學的、精確的", "ipa": "/ˌmæθəˈmætɪkl/", "trans": "mathematically", "col": "mathematical model", "ex": "He is a mathematical genius."},
    "mathematics/math": {"def": "數學", "ipa": "/ˌmæθəˈmætɪks/", "trans": "無 (不可數)", "col": "applied mathematics", "ex": "Math is my favorite subject."},
    "maths": {"def": "數學 (英式)", "ipa": "/mæθs/", "trans": "無", "col": "maths teacher", "ex": "He is very good at maths."},
    "matinee": {"def": "午後場、午後演出", "ipa": "/ˈmætɪneɪ/", "trans": "matinees", "col": "afternoon matinee", "ex": "We went to a matinee performance."},
    "matter": {"def": "物質、事情、有關係、重要", "ipa": "/ˈmætə/", "trans": "mattered", "col": "no matter what, in matter of", "ex": "It doesn't matter."},
    "mattress": {"def": "床墊", "ipa": "/ˈmætrəs/", "trans": "mattresses", "col": "soft mattress", "ex": "The mattress is too soft."},
    "mature": {"def": "成熟的、到期的、成熟", "ipa": "/məˈtʃʊə/", "trans": "matured, maturity", "col": "fully mature", "ex": "He is very mature for his age."},
    "maturity": {"def": "成熟、到期", "ipa": "/məˈtʃʊərəti/", "trans": "mature (形容詞)", "col": "emotional maturity", "ex": "He reached maturity early."},
    "maximum": {"def": "最大限度、最高的", "ipa": "/ˈmæksɪməm/", "trans": "maxima, minimum (最小的)", "col": "maximum speed, maximum temperature", "ex": "The maximum speed is 100 km/h."},
    "may": {"def": "可以、可能、願", "ipa": "/meɪ/", "trans": "might", "col": "may be, may as well", "ex": "May I come in?"},
    "May": {"def": "五月", "ipa": "/meɪ/", "trans": "無", "col": "early May", "ex": "They are going on holiday in May."},
    "maybe": {"def": "也許、可能", "ipa": "/ˈmeɪbi/", "trans": "無", "col": "maybe so", "ex": "Maybe he'll come later."},
    "mayor": {"def": "市長、鎮長", "ipa": "/meə/", "trans": "mayors", "col": "city mayor", "ex": "He was elected mayor of the city."},
    "me": {"def": "我 (I 之受格)", "ipa": "/miː/", "trans": "I, my", "col": "tell me", "ex": "Give it to me."},
    "meadow": {"def": "草地、牧場", "ipa": "/ˈmedəʊ/", "trans": "meadows", "col": "green meadow", "ex": "Cows were grazing in the meadow."},
    "meal": {"def": "一餐、粗粉", "ipa": "/miːl/", "trans": "meals", "col": "square meal, set meal", "ex": "We had a delicious meal."},
    "mean": {"def": "意指、預示、卑劣的、吝嗇的、平均的、平均數", "ipa": "/miːn/", "trans": "meant, meant, meaning", "col": "mean to do, mean business", "ex": "What do you mean?"},
    "meaning": {"def": "意義、含意、含蓄的", "ipa": "/ˈmiːnɪŋ/", "trans": "meanings, meaningful", "col": "double meaning, true meaning", "ex": "The word has several meanings."},
    "meaningful": {"def": "有意義的、意味深長的", "ipa": "/ˈmiːnɪŋfl/", "trans": "meaningfully", "col": "meaningful relationship", "ex": "It was a meaningful discussion."},
    "meantime": {"def": "其間、同時", "ipa": "/ˈmiːntaɪm/", "trans": "meanwhile", "col": "in the meantime", "ex": "In the meantime, let's wait here."},
    "meanwhile": {"def": "同時、在此期間", "ipa": "/ˈmiːnwaɪl/", "trans": "meantime", "col": "meanwhile, back at the ranch", "ex": "Meanwhile, his father is looking for him."},
    "measles": {"def": "麻疹、風疹", "ipa": "/ˈmiːzlz/", "trans": "無 (恆複)", "col": "suffer from measles", "ex": "The child has caught measles."},
    "measurable": {"def": "可測量的、適度的、可察覺的", "ipa": "/ˈmeʒərəbl/", "trans": "measurably", "col": "measurable improvement", "ex": "The results are measurable."},
    "measure": {"def": "測量、措施、標準、量度", "ipa": "/ˈmeʒə/", "trans": "measured, measurement", "col": "take measures, unit of measure", "ex": "We need to take drastic measures."},
    "measurement": {"def": "測量、尺寸", "ipa": "/ˈmeʒəmənt/", "trans": "measurements", "col": "accurate measurement", "ex": "We took measurements of the room."},
    "meat": {"def": "肉、實質內容", "ipa": "/miːt/", "trans": "meaty", "col": "red meat, white meat", "ex": "I don't eat meat."},
    "mechanic": {"def": "技工、機械工", "ipa": "/məˈkænɪk/", "trans": "mechanics", "col": "car mechanic", "ex": "The mechanic is repairing the car."},
    "mechanical": {"def": "機械的、呆板的", "ipa": "/məˈkænɪkl/", "trans": "mechanically", "col": "mechanical failure", "ex": "The car has a mechanical problem."},
    "mechanics": {"def": "機械學、力學、技巧", "ipa": "/məˈkænɪks/", "trans": "無 (恆複/單數)", "col": "quantum mechanics", "ex": "He is an expert in quantum mechanics."},
    "mechanism": {"def": "機制、機械裝置、技巧", "ipa": "/ˈmekənɪzəm/", "trans": "mechanisms", "col": "defense mechanism", "ex": "The human body has a defense mechanism."},
    "medal": {"def": "獎牌、勛章", "ipa": "/ˈmedl/", "trans": "medals, medalist", "col": "gold medal, silver medal", "ex": "He won a gold medal in the Olympic Games."},
    "media": {"def": "媒體、媒介 (medium 之複數)", "ipa": "/ˈmiːdiə/", "trans": "medium (單數)", "col": "mass media, social media", "ex": "The media plays an important role in society."},
    "mediate": {"def": "調解、斡旋", "ipa": "/ˈmiːdieɪt/", "trans": "mediated, mediation, mediator", "col": "mediate between", "ex": "He tried to mediate between the two sides."},
    "mediation": {"def": "調解、斡旋", "ipa": "/ˌmiːdiˈeɪʃn/", "trans": "mediate (動詞)", "col": "through mediation", "ex": "The dispute was settled through mediation."},
    "mediator": {"def": "調解者、斡旋者", "ipa": "/ˈmiːdieɪtə/", "trans": "mediators", "col": "official mediator", "ex": "He acted as a mediator in the dispute."},
    "medical": {"def": "醫藥的、醫療的、體格檢查", "ipa": "/ˈmedɪkl/", "trans": "medically", "col": "medical insurance, medical checkup", "ex": "He is a medical student."},
    "medically": {"def": "/ˈmedɪkli/", "trans": "medical (形容詞)", "col": "medically fit", "ex": "The treatment is medically approved."},
    "medication": {"def": "藥物治療、藥劑", "ipa": "/ˌmedɪˈkeɪʃn/", "trans": "medications", "col": "prescribe medication", "ex": "Are you taking any medication?"},
    "medicine": {"def": "藥、醫學", "ipa": "/ˈmedsn/", "trans": "medicines, medical", "col": "take medicine, western medicine", "ex": "Laughter is the best medicine."},
    "medieval": {"def": "中世紀的", "ipa": "/ˌmediˈiːvl/", "trans": "無", "col": "medieval history", "ex": "He is an expert in medieval history."},
    "meditate": {"def": "冥想、沈思、策劃", "ipa": "/ˈmedɪteɪt/", "trans": "meditated, meditation", "col": "meditate on", "ex": "He meditates for an hour every day."},
    "meditation": {"def": "沉思、冥想、考慮", "ipa": "/ˌmedɪˈteɪʃn/", "trans": "meditations, meditate (動詞)", "col": "deep meditation", "ex": "Meditation can help reduce stress."},
    "medium": {"def": "中間物、媒體、媒介、中間的", "ipa": "/ˈmiːdiəm/", "trans": "media", "col": "medium size, medium height", "ex": "He is of medium height."},
    "meek": {"def": "溫順的、謙卑的", "ipa": "/miːk/", "trans": "meekly", "col": "meek and mild", "ex": "She is as meek as a lamb."},
    "meet": {"def": "遇見、相會、滿足、運動會", "ipa": "/miːt/", "trans": "met, met, meeting", "col": "meet the needs, race meet", "ex": "Nice to meet you."},
    "meeting": {"def": "會議、接見", "ipa": "/ˈmiːtɪŋ/", "trans": "meetings", "col": "annual meeting, staff meeting", "ex": "We had a meeting this morning."},
    "melancholy": {"def": "憂鬱的、悲哀的、憂鬱", "ipa": "/ˈmelənkəli/", "trans": "無", "col": "deep melancholy", "ex": "There is a deep melancholy in his music."},
    "mellow": {"def": "柔和的、成熟的、使圓潤", "ipa": "/ˈmeləʊ/", "trans": "mellowed", "col": "mellow voice", "ex": "The wine has a mellow flavor."},
    "melody": {"def": "旋律、曲調", "ipa": "/ˈmelədi/", "trans": "melodies, melodic", "col": "sweet melody", "ex": "I like the sweet melody of the song."},
    "melon": {"def": "甜瓜、西瓜、圓形物", "ipa": "/ˈmelən/", "trans": "melons", "col": "honeydew melon, water melon", "ex": "I like honeydew melon."},
    "melt": {"def": "融化、熔化", "ipa": "/melt/", "trans": "melted", "col": "melt away", "ex": "The snow began to melt."},
    "member": {"def": "成員、會員", "ipa": "/ˈmembə/", "trans": "members, membership", "col": "family member, club member", "ex": "He is a member of the tennis club."},
    "membership": {"def": "會員資格、會員數", "ipa": "/ˈmembəʃɪp/", "trans": "member (名詞)", "col": "apply for membership", "ex": "He has a life membership of the club."},
    "memo": {"def": "備忘錄", "ipa": "/ˈmeməʊ/", "trans": "memos", "col": "office memo", "ex": "He sent a memo to all staff."},
    "memorable": {"def": "值得紀念的、難忘的", "ipa": "/ˈmemərəbl/", "trans": "memorably", "col": "memorable day", "ex": "It was a memorable trip."},
    "memorial": {"def": "紀念碑、紀念物、紀念的", "ipa": "/məˈmɔːriəl/", "trans": "memorials", "col": "Lincoln Memorial", "ex": "The memorial was built to honor the dead."},
    "memorize/memorise": {"def": "記住、背誦", "ipa": "/ˈmeməraɪz/", "trans": "memorized", "col": "memorize vocabulary", "ex": "I have to memorize the poem."},
    "memory": {"def": "記憶、回憶、記憶體", "ipa": "/ˈmeməri/", "trans": "memories, memorize (動詞)", "col": "in memory of, short memory", "ex": "He has a good memory."},
    "menace": {"def": "威脅、恐嚇", "ipa": "/ˈmenəs/", "trans": "menaced", "col": "threaten menace", "ex": "The gangs are a menace to society."},
    "mend": {"def": "修理、修補、改進", "ipa": "/mend/", "trans": "mended", "col": "on the mend", "ex": "Can you mend my shoes?"},
    "mental": {"def": "心理的、精神的", "ipa": "/ˈmentl/", "trans": "mentally", "col": "mental health, mental hospital", "ex": "He has some mental problems."},
    "mentally": {"def": "/ˈmentəli/", "trans": "mental (形容詞)", "col": "mentally ill", "ex": "He is mentally fit for task."},
    "mention": {"def": "提及、說起", "ipa": "/ˈmenʃn/", "trans": "mentioned", "col": "not to mention, don't mention it", "ex": "Did he mention my name?"},
    "mentor": {"def": "導師、良師益友", "ipa": "/ˈmentɔː/", "trans": "mentors", "col": "spiritual mentor", "ex": "He was a mentor to me."},
    "menu": {"def": "菜單、選單", "ipa": "/ˈmenjuː/", "trans": "menus", "col": "a la carte menu", "ex": "May I see the menu, please?"},
    "merchandise": {"def": "商品、貨物、買賣", "ipa": "/ˈmɜːtʃəndaɪs/", "trans": "merchandising", "col": "cheap merchandise", "ex": "The shop sells quality merchandise."},
    "merchant": {"def": "商人、零售商、商業的", "ipa": "/ˈmɜːtʃənt/", "trans": "merchants", "col": "merchant ship, wine merchant", "ex": "He is a rich merchant."},
    "merciful": {"def": "仁慈的、慈悲的", "ipa": "/ˈmɜːsɪfl/", "trans": "mercifully", "col": "God is merciful.", "ex": "The king was merciful to the prisoners."},
    "mercury": {"def": "水銀、汞、(M-)水星", "ipa": "/ˈmɜːkjəri/", "trans": "無", "col": "mercury thermometer", "ex": "Mercury is a liquid metal."},
    "mercy": {"def": "慈悲、憐憫、恩惠", "ipa": "/ˈmɜːsi/", "trans": "mercies, merciful", "col": "at the mercy of, have mercy on", "ex": "May God have mercy on your soul."},
    "mere": {"def": "僅僅的、純粹的、池塘", "ipa": "/mɪə/", "trans": "merely", "col": "mere child", "ex": "He is a mere child."},
    "merely": {"def": "僅僅、只不過", "ipa": "/ˈmɪəli/", "trans": "mere (形容詞)", "col": "merely a joke", "ex": "He said it merely for a joke."},
    "merge": {"def": "合併、融合", "ipa": "/mɜːdʒ/", "trans": "merged, merger", "col": "merge together", "ex": "The two companies merged last year."},
    "merger": {"def": "合併、併購", "ipa": "/ˈmɜːdʒə/", "trans": "mergers", "col": "takeover and merger", "ex": "The proposed merger was cancelled."},
    "merit": {"def": "優點、功績、值得", "ipa": "/ˈmerɪt/", "trans": "merits, meritorious", "col": "artistic merit", "ex": "I can see the merit of your plan."},
    "mermaid": {"def": "美人魚", "ipa": "/ˈmɜːmeɪd/", "trans": "mermaids", "col": "legendary mermaid", "ex": "She is as beautiful as a mermaid."},
    "merry": {"def": "快樂的、愉快的", "ipa": "/ˈmeri/", "trans": "merrily, merriment", "col": "Merry Christmas", "ex": "We wish you a Merry Christmas."},
    "mess": {"def": "混亂、食堂、搞糟", "ipa": "/mes/", "trans": "messed, messy", "col": "make a mess, in a mess", "ex": "His room is in a mess."},
    "message": {"def": "消息、訊息、啟示", "ipa": "/ˈmesɪdʒ/", "trans": "messages, messenger", "col": "leave a message, take a message", "ex": "I left a message for him."},
    "messenger": {"def": "信使、傳令兵", "ipa": "/ˈmesɪndʒə/", "trans": "messengers", "col": "bicycle messenger", "ex": "A messenger brought the news."},
    "messy": {"def": "混亂的、骯髒的", "ipa": "/ˈmesi/", "trans": "messier, messiest", "col": "messy hair", "ex": "The desks are very messy."},
    "met": {"def": "遇見 (meet 過去式/受詞)", "ipa": "/met/", "trans": "meet (動詞)", "col": "never met", "ex": "I met him yesterday."},
    "metal": {"def": "金屬(的)", "ipa": "/ˈmetl/", "trans": "metals, metallic", "col": "precious metal", "ex": "Iron is a common metal."},
    "metaphor": {"def": "暗喻、隱喻", "ipa": "/ˈmetəfə/", "trans": "metaphors, metaphorical", "col": "extended metaphor", "ex": "He uses a metaphor to explain his point."},
    "meteor": {"def": "流星、大氣現象", "ipa": "/ˈmiːtiə/", "trans": "meteors", "col": "meteor shower", "ex": "I saw a meteor in the sky."},
    "meteorology": {"def": "氣象學", "ipa": "/ˌmiːtiəˈrɒlədʒ/", "trans": "meteorologist", "col": "dynamic meteorology", "ex": "Meteorology is the study of the atmosphere."},
    "meter/metre": {"def": "公尺、計量器、韻律", "ipa": "/ˈmiːtə/", "trans": "meters", "col": "ten meters, gas meter", "ex": "A hundred centimeters equals one meter."},
    "method": {"def": "方法、條理", "ipa": "/ˈmeθəd/", "trans": "methods, methodical", "col": "teaching method, scientific method", "ex": "What is the best method to learn English?"},
    "metronome": {"def": "節拍器", "ipa": "/ˈmetrənəʊm/", "trans": "metronomes", "col": "wind-up metronome", "ex": "He used a metronome to keep time while practicing."},
    "microscope": {"def": "顯微鏡", "ipa": "/ˈmaɪkrəskəʊp/", "trans": "microscopes", "col": "electron microscope", "ex": "We looked at the cells through a microscope."},
    "microwave": {"def": "微波、微波爐", "ipa": "/ˈmaɪkrəweɪv/", "trans": "microwaves", "col": "microwave oven", "ex": "You can cook it in the microwave."},
    "mid/middle": {"def": "中間的、中央地", "ipa": "/mɪd/", "trans": "midst", "col": "mid-day, in mid-air", "ex": "He was born in the mid-1980s."},
    "mid-day/midday": {"def": "中午", "ipa": "/ˌmɪd ˈdeɪ/", "trans": "無", "col": "at midday", "ex": "The sun is hot at midday."},
    "middle": {"def": "中間、中央的", "ipa": "/ˈmɪdl/", "trans": "middling", "col": "in the middle of, middle class", "ex": "He is the boy in the middle."},
    "midnight": {"def": "午夜", "ipa": "/ˈmɪdnaɪt/", "trans": "無", "col": "at midnight, post-midnight", "ex": "It's already midnight."},
    "midst": {"def": "正中心、在那之中", "ipa": "/mɪdst/", "trans": "無", "col": "in the midst of", "ex": "We are in the midst of a crisis."},
    "might": {"def": "力量、威力、可能 (may 過去式)", "ipa": "/maɪt/", "trans": "mighty", "col": "might as well", "ex": "He might come tomorrow."},
    "mighty": {"def": "有力的、強大的、很", "ipa": "/ˈmaɪti/", "trans": "might (名詞)", "col": "mighty ocean", "ex": "He is a mighty warrior."},
    "migraine": {"def": "偏頭痛", "ipa": "/ˈmiːɡreɪn/", "trans": "migraines", "col": "suffer from migraine", "ex": "She has a terrible migraine."},
    "migrate": {"def": "遷移、移居、洄游", "ipa": "/maɪˈɡreɪt/", "trans": "migrated, migration", "col": "birds migrate", "ex": "Many birds migrate south for the winter."},
    "migration": {"def": "遷移、移居、遷徙", "ipa": "/maɪˈɡreɪʃn/", "trans": "migrations, migrate (動詞)", "col": "mass migration", "ex": "The migration of the birds is a natural phenomenon."},
    "mild": {"def": "溫和的、輕微的、淡味的", "ipa": "/maɪld/", "trans": "mildly", "col": "mild weather, mild symptoms", "ex": "The winter here is very mild."},
}

with open("batch_l1_p30.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART30, f, ensure_ascii=False, indent=2)
