import json

# Level 1 Part 51: (Quaver - Raffle)
L1_PART51 = {
    "quaver": {"def": "顫抖、發顫音、震動、顫聲", "ipa": "/ˈkweɪvə/", "trans": "quavered", "col": "quavering voice", "ex": "His voice quavered with emotion."},
    "quay": {"def": "碼頭", "ipa": "/kiː/", "trans": "quays", "col": "ship at the quay", "ex": "The ship is docked at the quay."},
    "queasy": {"def": "噁心的、想嘔吐的、不自在的", "ipa": "/ˈkwiːzi/", "trans": "queasiness", "col": "feel queasy", "ex": "The smell of food made her feel queasy."},
    "queen": {"def": "皇后、女王", "ipa": "/kwiːn/", "trans": "queens", "col": "queen mother, beauty queen", "ex": "She was the queen of the prom."},
    "queer": {"def": "奇怪的、古怪的、可疑的、同性戀者", "ipa": "/kwɪə/", "trans": "queerly", "col": "queer feeling", "ex": "I had a queer feeling that I was being watched."},
    "quell": {"def": "鎮壓、壓制、消除、平息", "ipa": "/kwel/", "trans": "quelled", "col": "quell a riot", "ex": "Police were called in to quell the riot."},
    "quench": {"def": "熄滅、解渴、壓制、淬火", "ipa": "/kwentʃ/", "trans": "quenched", "col": "quench one's thirst", "ex": "He drank a glass of water to quench his thirst."},
    "querulous": {"def": "愛抱怨的、易怒的", "ipa": "/ˈkwerələs/", "trans": "querulously", "col": "querulous tone", "ex": "He had a querulous voice."},
    "query": {"def": "詢問、疑問、向...提問", "ipa": "/ˈkwɪəri/", "trans": "queries", "col": "query the result", "ex": "If you have any query, please let me know."},
    "quest": {"def": "尋找、追求、遠征、探索", "ipa": "/kwest/", "trans": "quests", "col": "in quest of", "ex": "He is in quest of the truth."},
    "question": {"def": "問題、質疑、詢問、質問", "ipa": "/ˈkwestʃən/", "trans": "questions, questionable, questionnaire", "col": "ask a question, out of the question", "ex": "That is a very good question."},
    "questionable": {"def": "可疑的、有問題的", "ipa": "/ˈkwestʃənəbl/", "trans": "question (名詞)", "col": "questionable behavior", "ex": "His motives are highly questionable."},
    "questionnaire": {"def": "問卷、調查表", "ipa": "/ˌkwestʃəˈneə/", "trans": "questionnaires", "col": "fill out a questionnaire", "ex": "Please complete the questionnaire."},
    "queue": {"def": "行列、隊伍、排隊", "ipa": "/kjuː/", "trans": "queued", "col": "jump the queue", "ex": "There was a long queue at the bus stop."},
    "quibble": {"def": "遁詞、謬論、吹毛徹疵、爭論", "ipa": "/ˈkwɪbl/", "trans": "quibbled", "col": "quibble over details", "ex": "Don't quibble over small matters."},
    "quick": {"def": "快的、迅速的、敏銳的、快地", "ipa": "/kwɪk/", "trans": "quickly, quicken", "col": "quick fix, quick witted", "ex": "He is a quick learner."},
    "quicken": {"def": "加速、加快、鼓舞", "ipa": "/ˈkwɪkən/", "trans": "quickened", "col": "quicken the pace", "ex": "The pace of the game started to quicken."},
    "quickly": {"def": "很快地、迅速地", "ipa": "/ˈkwɪkli/", "trans": "quick (形容詞)", "col": "come quickly", "ex": "Come quickly, or we'll be late."},
    "quicksand": {"def": "流沙、危險狀態", "ipa": "/ˈkwɪksænd/", "trans": "quicksands", "col": "trap in quicksand", "ex": "He felt like he was sinking in quicksand."},
    "quiescent": {"def": "靜止的、沉寂的、不活動的", "ipa": "/kwiˈesnt/", "trans": "quiescence", "col": "quiescent state", "ex": "The volcano is now quiescent."},
    "quiet": {"def": "安靜的、平靜的、寧靜、使安靜", "ipa": "/ˈkwaɪət/", "trans": "quietly, quietude", "col": "keep quiet", "ex": "Please be quiet."},
    "quietly": {"def": "安靜地、平靜地、輕聲地", "ipa": "/ˈkwaɪətli/", "trans": "quiet (形容詞)", "col": "speak quietly", "ex": "He closed the door quietly."},
    "quietude": {"def": "寧靜、寂靜、安靜", "ipa": "/ˈkwaɪɪtjuːd/", "trans": "quiet (形容詞)", "col": "peace and quietude", "ex": "She enjoys the quietude of the countryside."},
    "quill": {"def": "羽毛、羽毛筆、刺、用羽毛筆寫", "ipa": "/kwɪl/", "trans": "quills", "col": "quill pen", "ex": "He used a quill to sign the letter."},
    "quilt": {"def": "被子、棉被、縫成被子", "ipa": "/kwɪlt/", "trans": "quilts", "col": "patchwork quilt", "ex": "I like sleeping under a thick quilt."},
    "quintessence": {"def": "精華、典範、第五元素", "ipa": "/kwɪnˈtesns/", "trans": "quintessential", "col": "quintessence of style", "ex": "He is the quintessence of a gentleman."},
    "quintessential": {"def": "精華的、典型的", "ipa": "/ˌkwɪntɪˈsenʃl/", "trans": "quintessence", "col": "quintessential english village", "ex": "It was a quintessential country house."},
    "quip": {"def": "諷刺的話、俏皮話、嘲弄", "ipa": "/kwɪp/", "trans": "quipped", "col": "witty quip", "ex": "He made a witty quip about the weather."},
    "quirk": {"def": "古怪、怪癖、急轉", "ipa": "/kwɜːk/", "trans": "quirky", "col": "quirk of fate", "ex": "Everyone has their little quirks."},
    "quirky": {"def": "古怪的、離奇的", "ipa": "/ˈkwɜːki/", "trans": "quirk (名詞)", "col": "quirky sense of humor", "ex": "He has a quirky personality."},
    "quit": {"def": "停止、離開、辭職、拋棄", "ipa": "/kwɪt/", "trans": "quitted", "col": "quit smoking, quit a job", "ex": "He decided to quit his job."},
    "quite": {"def": "相當、完全、非常", "ipa": "/kwaɪt/", "trans": "無", "col": "quite good, quite right", "ex": "It's quite cold today."},
    "quiver": {"def": "顫抖、發抖、箭囊、抖動", "ipa": "/ˈkwɪvə/", "trans": "quivered", "col": "quiver with fear", "ex": "She quivered with cold."},
    "quixotic": {"def": "唐吉訶德式的、狂想的、不切實際的", "ipa": "/kwɪkˈsɒtɪk/", "trans": "quixotically", "col": "quixotic quest", "ex": "It was a quixotic attempt to change the system."},
    "quiz": {"def": "測驗、詢問、挖苦", "ipa": "/kwɪz/", "trans": "quizzed, quizzical", "col": "pop quiz", "ex": "We had a quiz in geography class."},
    "quizzical": {"def": "古怪的、嘲弄的、困惑的", "ipa": "/ˈkwɪzɪkl/", "trans": "quizzically", "col": "quizzical look", "ex": "He gave her a quizzical look."},
    "quota": {"def": "配額、限額、定額", "ipa": "/ˈkwəʊtə/", "trans": "quotas", "col": "import quota", "ex": "The country has an import quota on cars."},
    "quotation": {"def": "引用、引文、報價", "ipa": "/kwəʊˈteɪʃn/", "trans": "quote (動詞)", "col": "quotation marks", "ex": "Here is a quotation from the Bible."},
    "rabbit": {"def": "兔子、野兔、獵兔", "ipa": "/ˈræbɪt/", "trans": "rabbits", "col": "rabbit hole", "ex": "The rabbit ran into its hole."},
    "rabid": {"def": "患狂犬病的、瘋狂的、激進的", "ipa": "/ˈræbɪd/", "trans": "rabies", "col": "rabid dog, rabid fan", "ex": "He is a rabid fan of the team."},
    "race": {"def": "競賽、種族、賽跑、人種、比賽", "ipa": "/reɪs/", "trans": "raced, racial, racism", "col": "horse race, human race", "ex": "Who won the race?"},
    "racial": {"def": "種族的、人種的", "ipa": "/ˈreɪʃl/", "trans": "race (名詞)", "col": "racial harmony, racial discrimination", "ex": "We must eliminate racial prejudice."},
    "racism": {"def": "種族主義、種族歧視", "ipa": "/ˈreɪsɪzəm/", "trans": "racist", "col": "fight against racism", "ex": "Rasism is still a problem in society."},
    "racist": {"def": "種族主義者、種族歧視的", "ipa": "/ˈreɪsɪst/", "trans": "racism (名詞)", "col": "racist attack", "ex": "He made a racist comment."},
    "rack": {"def": "架子、掛物架、酷刑、折磨", "ipa": "/ræk/", "trans": "racked", "col": "luggage rack, spice rack", "ex": "Put your shoes on the rack."},
    "racket": {"def": "球拍、喧鬧、敲詐、非法勾當", "ipa": "/ˈrækɪt/", "trans": "rackets", "col": "tennis racket, make a racket", "ex": "Stop making such a racket!"},
    "radar": {"def": "雷達、無線電探側", "ipa": "/ˈreɪdɑː/", "trans": "radars", "col": "on the radar", "ex": "The blip showed up on the radar."},
    "radiant": {"def": "輻射的、光芒四射的、表情燦爛的", "ipa": "/ˈreɪdiənt/", "trans": "radiance, radiate", "col": "radiant smile", "ex": "She looked radiant in her wedding dress."},
    "radiate": {"def": "輻射、流露、發光、發熱", "ipa": "/ˈreɪdieɪt/", "trans": "radiated, radiation", "col": "radiate heat", "ex": "The sun radiates heat and light."},
    "radiation": {"def": "輻射、放射線", "ipa": "/ˌreɪdiˈeɪʃn/", "trans": "radiator", "col": "ultraviolet radiation", "ex": "High levels of radiation were detected."},
    "radiator": {"def": "散熱器、暖氣片", "ipa": "/ˈreɪdieɪtə/", "trans": "radiators", "col": "car radiator", "ex": "The radiator is leaking."},
    "radical": {"def": "激進的、基本的、根本的、激進分子", "ipa": "/ˈrædɪkl/", "trans": "radically", "col": "radical change, radical reform", "ex": "They proposed radical changes to the law."},
    "radically": {"def": "基本上、根本上、激進地", "ipa": "/ˈrædɪkli/", "trans": "radical (形容詞)", "col": "radically different", "ex": "The new design is radically different."},
    "radio": {"def": "收音機、無線電、發送無線電報", "ipa": "/ˈreɪdiəʊ/", "trans": "radios", "col": "listen to the radio", "ex": "Turn on the radio."},
    "radioactive": {"def": "放射性的、有輻射的", "ipa": "/ˌreɪdiəʊˈæktɪv/", "trans": "radioactivity", "col": "radioactive waste", "ex": "Cadium is a radioactive element."},
    "radioactivity": {"def": "放射性、輻射能", "ipa": "/ˌreɪdiəʊækˈtɪvəti/", "trans": "radioactive", "col": "measure radioactivity", "ex": "Scientists are monitoring the radioactivity levels."},
    "radish": {"def": "小蘿蔔", "ipa": "/ˈrædɪʃ/", "trans": "radishes", "col": "red radish", "ex": "The salad has fresh radishes in it."},
    "radium": {"def": "鐳", "ipa": "/ˈreɪdiəm/", "trans": "無", "col": "radium treatment", "ex": "Radium is used in cancer treatment."},
    "radius": {"def": "半徑、範圍", "ipa": "/ˈreɪdiəs/", "trans": "radii", "col": "within a radius of", "ex": "The school serves people within a 5-mile radius."},
    "raffle": {"def": "抽彩、摸彩、抽獎", "ipa": "/ˈræfl/", "trans": "raffled", "col": "charity raffle", "ex": "She won a prize in the raffle."},
}

with open("batch_l1_p51.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART51, f, ensure_ascii=False, indent=2)
