import json

# Level 1 Part 41: (Phrase - Pizza)
L1_PART41 = {
    "phrase": {"def": "片語、詞組、措辭、宣稱", "ipa": "/freɪz/", "trans": "phrases", "col": "common phrase, set phrase", "ex": "He used a lot of technical phrases."},
    "physical": {"def": "身體的、物理的、物質的、體檢", "ipa": "/ˈfɪzɪkl/", "trans": "physically", "col": "physical education, physical appearance", "ex": "Exercise is good for physical health."},
    "physically": {"def": "身體上、物理上", "ipa": "/ˈfɪzɪkli/", "trans": "physical (形容詞)", "col": "be physically fit", "ex": "He is physically weak."},
    "physician": {"def": "內科醫生", "ipa": "/fɪˈzɪʃn/", "trans": "physicians, surgeon (外科醫生)", "col": "chief physician", "ex": "Consult your physician before taking this medicine."},
    "physicist": {"def": "物理學家", "ipa": "/ˈfɪzɪsɪst/", "trans": "physicists", "col": "nuclear physicist", "ex": "Einstein was a famous physicist."},
    "physics": {"def": "物理學", "ipa": "/ˈfɪzɪks/", "trans": "physical", "col": "laws of physics", "ex": "Physics is my favorite subject."},
    "physiologist": {"def": "生理學家", "ipa": "/ˌfɪziˈɒlədʒɪst/", "trans": "physiologists", "col": "experimental physiologist", "ex": "The physiologist is studying the effects of space flight."},
    "physiology": {"def": "生理學", "ipa": "/ˌfɪziˈɒlədʒi/", "trans": "physiological", "col": "human physiology", "ex": "He is an expert in physiology."},
    "pianist": {"def": "鋼琴家", "ipa": "/ˈpɪənɪst/", "trans": "pianists", "col": "concert pianist", "ex": "She is a talented pianist."},
    "piano": {"def": "鋼琴", "ipa": "/piˈænəʊ/", "trans": "pianos, pianist", "col": "play the piano", "ex": "He likes playing the piano."},
    "pick": {"def": "挑選、採摘、拾起、十字鎬", "ipa": "/pɪk/", "trans": "picked, pickup", "col": "pick up, pick on someone", "ex": "I picked some flowers for you."},
    "picket": {"def": "糾察隊、樁子、派人監視", "ipa": "/ˈpɪkɪt/", "trans": "picketed", "col": "picket line", "ex": "There was a picket line outside the factory."},
    "pickle": {"def": "泡菜、醃漬物、困境、醃製", "ipa": "/ˈpɪkl/", "trans": "pickled", "col": "in a pickle", "ex": "I like pickles on my burger."},
    "pickpocket": {"def": "扒手", "ipa": "/ˈpɪkpɒkɪt/", "trans": "pickpockets", "col": "watch out for pickpockets", "ex": "Watch out for pickpockets on the bus."},
    "pickup": {"def": "接送、拾起、改善、皮卡車", "ipa": "/ˈpɪkʌp/", "trans": "pickups", "col": "pickup truck, pickup point", "ex": "I'll give you a pickup at the station."},
    "picnic": {"def": "野餐、輕鬆的事、去野餐", "ipa": "/ˈpɪknɪk/", "trans": "picnics, picnicked", "col": "go on a picnic", "ex": "We had a picnic in the park."},
    "pictorial": {"def": "圖示的、繪畫的、畫報", "ipa": "/pɪkˈtɔːriəl/", "trans": "pictorially", "col": "pictorial dictionary", "ex": "They published a pictorial history of the war."},
    "picture": {"def": "圖畫、照片、影片、想像", "ipa": "/ˈpɪktʃə/", "trans": "pictures, picturesque", "col": "take a picture, big picture", "ex": "Can you draw a picture of a cat?"},
    "picturesque": {"def": "風景如畫的、生動的", "ipa": "/ˌpɪktʃəˈresk/", "trans": "picturesquely", "col": "picturesque village", "ex": "The village is very picturesque."},
    "pie": {"def": "派、餡餅", "ipa": "/paɪ/", "trans": "pies", "col": "apple pie, easy as pie", "ex": "She baked an apple pie."},
    "piece": {"def": "碎片、一件作品、硬幣", "ipa": "/piːs/", "trans": "pieces", "col": "a piece of cake, in pieces", "ex": "He ate a large piece of cake."},
    "pier": {"def": "碼頭、橋墩", "ipa": "/pɪə/", "trans": "piers", "col": "concrete pier", "ex": "The ship is tied to the pier."},
    "pierce": {"def": "刺穿、穿透、洞察", "ipa": "/pɪəs/", "trans": "pierced, piercing", "col": "pierce the skin", "ex": "The needle pierced her finger."},
    "piercing": {"def": "刺穿的、刺骨的、敏銳的", "ipa": "/ˈpɪəsɪŋ/", "trans": "pierce (動詞)", "col": "piercing eyes, piercing cold", "ex": "She has piercing blue eyes."},
    "piety": {"def": "虔誠、孝順", "ipa": "/ˈpaɪəti/", "trans": "pious", "col": "filial piety", "ex": "Filial piety is highly valued in Chinese culture."},
    "pig": {"def": "豬、貪婪的人、生豬肉", "ipa": "/pɪɡ/", "trans": "pigs, piglet", "col": "guinea pig, pig out", "ex": "The pigs are in the pen."},
    "pigeon": {"def": "鴿子、簡單目標", "ipa": "/ˈpɪdʒɪn/", "trans": "pigeons", "col": "homing pigeon, carrier pigeon", "ex": "Pigeons are common in city parks."},
    "pigment": {"def": "顏料、色素、染色", "ipa": "/ˈpɪɡmənt/", "trans": "pigments", "col": "skin pigment", "ex": "Plant pigments are used to make dyes."},
    "pile": {"def": "堆、大量、建築物、堆積", "ipa": "/paɪl/", "trans": "piles, piled", "col": "pile up", "ex": "There is a pile of books on the desk."},
    "pilgrim": {"def": "朝聖者、漫遊者", "ipa": "/ˈpɪlɡrɪm/", "trans": "pilgrims, pilgrimage", "col": "religious pilgrim", "ex": "The pilgrims traveled to the holy city."},
    "pilgrimage": {"def": "朝聖之旅", "ipa": "/ˈpɪlɡrɪmɪdʒ/", "trans": "pilgrimages", "col": "make a pilgrimage to", "ex": "They made a pilgrimage to Mecca."},
    "pill": {"def": "藥丸、口服避孕藥、討厭的人", "ipa": "/pɪl/", "trans": "pills", "col": "sleeping pill, take a pill", "ex": "The doctor gave me some pills."},
    "pillar": {"def": "柱子、棟樑、核心人物", "ipa": "/ˈpɪlə/", "trans": "pillars", "col": "pillar of society", "ex": "The temple is supported by stone pillars."},
    "pillow": {"def": "枕頭、靠墊、枕藉", "ipa": "/ˈpɪləʊ/", "trans": "pillows", "col": "pillow case, pillow fight", "ex": "I like to sleep with two pillows."},
    "pilot": {"def": "飛行員、領航員、導游、駕駛、試點", "ipa": "/ˈpaɪlət/", "trans": "pilots, piloted", "col": "fighter pilot, pilot light", "ex": "He is a commercial airlines pilot."},
    "pimple": {"def": "粉刺、丘疹", "ipa": "/ˈpɪmpl/", "trans": "pimples, pimply", "col": "get a pimple", "ex": "She has a pimple on her nose."},
    "pin": {"def": "大頭針、別針、引信、別住、釘住", "ipa": "/pɪn/", "trans": "pins, pinned", "col": "safety pin, rolling pin", "ex": "She fastened the note with a pin."},
    "pinch": {"def": "捏、掐、一撮、緊缺、勒索", "ipa": "/pɪntʃ/", "trans": "pinched", "col": "in a pinch, pinch oneself", "ex": "He gave her a pinch on the arm."},
    "pine": {"def": "松樹、憔悴、思念", "ipa": "/paɪn/", "trans": "pines, pineapple", "col": "pine tree, pine cone", "ex": "The mountains are covered with pines."},
    "pineapple": {"def": "鳳梨", "ipa": "/ˈpaɪnæpl/", "trans": "pineapples", "col": "canned pineapple", "ex": "I like to eat pineapple."},
    "ping-pong": {"def": "桌球、乒乓球", "ipa": "/ˈpɪŋ pɒŋ/", "trans": "table tennis", "col": "play ping-pong", "ex": "He is good at playing ping-pong."},
    "pink": {"def": "粉紅色的、巔峰、石竹花", "ipa": "/pɪŋk/", "trans": "pinks", "col": "in the pink", "ex": "She is wearing a pink dress."},
    "pint": {"def": "品脫", "ipa": "/paɪnt/", "trans": "pints", "col": "pint of milk", "ex": "He drank a pint of beer."},
    "pioneer": {"def": "先驅、拓荒者、開闢、倡導", "ipa": "/ˌpaɪəˈnɪə/", "trans": "pioneered", "col": "pioneer spirit", "ex": "They are pioneers in the field of medicine."},
    "pious": {"def": "虔誠的、盡責的、虛偽的", "ipa": "/ˈpaɪəs/", "trans": "piously, piety", "col": "pious hope, pious man", "ex": "She is a pious woman."},
    "pipe": {"def": "管子、煙斗、笛、導管、以管輸送", "ipa": "/paɪp/", "trans": "pipes, piper, pipeline", "col": "water pipe, smoking pipe", "ex": "The water pipe is leaking."},
    "pipeline": {"def": "管道、輸送管、在處理中", "ipa": "/ˈpaɪplaɪn/", "trans": "pipelines", "col": "in the pipeline", "ex": "New products are in the pipeline."},
    "piracy": {"def": "海盜行為、版權侵害", "ipa": "/ˈpɪrəsi/", "trans": "pirate (名詞)", "col": "software piracy", "ex": "Software piracy is a major problem."},
    "pirate": {"def": "海盜、盜版者、剽竊、盜印", "ipa": "/ˈpaɪrət/", "trans": "pirates, pirated", "col": "pirate ship, pirated software", "ex": "They were attacked by pirates."},
    "piss": {"def": "散尿", "ipa": "/pɪs/", "trans": "pissed", "col": "piss off", "ex": "He had to go for a piss."},
    "pistol": {"def": "手槍", "ipa": "/ˈpɪstl/", "trans": "pistols", "col": "semi-automatic pistol", "ex": "He was carrying a pistol."},
    "pit": {"def": "深坑、地窖、陷阱、果核、使對立", "ipa": "/pɪt/", "trans": "pits, pitted", "col": "pit against", "ex": "The car fell into a deep pit."},
    "pitch": {"def": "瀝青、投、音高、推銷、投擲、紮營", "ipa": "/pɪtʃ/", "trans": "pitched, pitcher", "col": "perfect pitch, sales pitch", "ex": "The pitch of the sound was too high."},
    "pitcher": {"def": "大水罐、投手", "ipa": "/ˈpɪtʃə/", "trans": "pitchers", "col": "starting pitcher", "ex": "He is a famous baseball pitcher."},
    "pity": {"def": "憐憫、同情、遺憾的事、同情", "ipa": "/ˈpɪti/", "trans": "pitied, pitiful", "col": "take pity on, what a pity", "ex": "I feel pity for the homeless."},
    "pizza": {"def": "披薩", "ipa": "/ˈpiːtsə/", "trans": "pizzas", "col": "cheese pizza", "ex": "I'd like a slice of pizza."},
}

with open("batch_l1_p41.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART41, f, ensure_ascii=False, indent=2)
