import json

# Level 2 Part 3: (Beer - Brave)
L2_PART3 = {
    "beer": {"def": "啤酒", "ipa": "/bɪə/", "trans": "beers", "col": "draft beer, bottle of beer", "ex": "He ordered a glass of beer.", "pos": "n."},
    "beetle": {"def": "甲蟲、（像甲蟲般）急行", "ipa": "/ˈbiːtl/", "trans": "beetles", "col": "dung beetle", "ex": "I saw a small green beetle in the garden.", "pos": "n./v."},
    "beforehand": {"def": "預先地、提前地", "ipa": "/bɪˈfɔːhænd/", "trans": "before", "col": "plan beforehand", "ex": "I appreciate you telling me that beforehand.", "pos": "adv."},
    "beg": {"def": "乞討、懇求", "ipa": "/beɡ/", "trans": "beggar, begged", "col": "beg for mercy, beg a favor", "ex": "He begged her for another chance.", "pos": "v."},
    "beggar": {"def": "乞丐、窮人、使淪為乞丐", "ipa": "/ˈbeɡə/", "trans": "beg (動詞)", "col": "homeless beggar", "ex": "The beggar asked for some small change.", "pos": "n./v."},
    "begin": {"def": "開始", "ipa": "/bɪˈɡɪn/", "trans": "began, begun, beginning", "col": "begin with, newly begun", "ex": "Wait for me to begin.", "pos": "v."},
    "beginner": {"def": "初學者", "ipa": "/bɪˈɡɪnə/", "trans": "begin (動詞)", "col": "absolute beginner", "ex": "This course is suitable for beginners.", "pos": "n."},
    "beginning": {"def": "開始、開端、最初的", "ipa": "/bɪˈɡɪnɪŋ/", "trans": "begin (動詞)", "col": "at the beginning of", "ex": "In the beginning, God created the earth.", "pos": "n./adj."},
    "behave": {"def": "行為舉止、表現", "ipa": "/bɪˈheɪv/", "trans": "behavior, behavioral", "col": "behave well", "ex": "You must behave yourself.", "pos": "v."},
    "behavior": {"def": "行為、舉止", "ipa": "/bɪˈheɪvjə/", "trans": "behave (動詞)", "col": "good behavior, human behavior", "ex": "The child was rewarded for his good behavior.", "pos": "n."},
    "behind": {"def": "在...後面、背後地、背後、臀部", "ipa": "/bɪˈhaɪnd/", "trans": "hinder", "col": "behind the scenes, behind schedule", "ex": "The sun went behind a cloud.", "pos": "prep./adv./n."},
    "belief": {"def": "信念、相信、信仰", "ipa": "/bɪˈliːf/", "trans": "believe (動詞)", "col": "belief in God, strong belief", "ex": "Religious beliefs are very personal.", "pos": "n."},
    "believe": {"def": "相信、信仰", "ipa": "/bɪˈliːv/", "trans": "believer, believable", "col": "make-believe, believe in", "ex": "I believe you.", "pos": "v."},
    "bell": {"def": "鈴、鐘、使像鈴般響", "ipa": "/bel/", "trans": "belfry", "col": "door bell, ring a bell", "ex": "I rang the bell, but no one answered.", "pos": "n./v."},
    "belong": {"def": "屬於、為...的一員", "ipa": "/bɪˈlɒŋ/", "trans": "belongings", "col": "belong to", "ex": "This book belongs to me.", "pos": "v."},
    "below": {"def": "在...下面、在下面", "ipa": "/bɪˈləʊ/", "trans": "low", "col": "below average, below zero", "ex": "The temperature is below freezing.", "pos": "prep./adv."},
    "belt": {"def": "腰帶、帶、地帶、繫上皮帶", "ipa": "/belt/", "trans": "seatbelt", "col": "seat belt, green belt", "ex": "You must wear a seat belt in the car.", "pos": "n./v."},
    "bench": {"def": "長凳、長椅、法官席", "ipa": "/bentʃ/", "trans": "benches", "col": "park bench", "ex": "We sat on a park bench.", "pos": "n."},
    "bend": {"def": "彎曲、屈服、彎曲、轉彎", "ipa": "/bend/", "trans": "bent, bender", "col": "bend over, around the bend", "ex": "The road bends to the left.", "pos": "v./n."},
    "beneath": {"def": "在...底下、在此之下", "ipa": "/bɪˈniːθ/", "trans": "under", "col": "beneath the surface", "ex": "The boat sank beneath the waves.", "pos": "prep./adv."},
    "beneficial": {"def": "有益的、有利的", "ipa": "/ˌbenɪˈfɪʃl/", "trans": "benefit (名詞)", "col": "beneficial to health", "ex": "Exercising is beneficial to your health.", "pos": "adj."},
    "benefit": {"def": "利益、好處、保險金、有助於、獲益", "ipa": "/ˈbenɪfɪt/", "trans": "beneficial, beneficiary", "col": "benefit from, for the benefit of", "ex": "I've had the benefit of a good education.", "pos": "n./v."},
    "berry": {"def": "漿果、採漿果", "ipa": "/ˈberi/", "trans": "berries", "col": "strawberry, blueberry", "ex": "The birds are eating the red berries.", "pos": "n./v."},
    "beside": {"def": "在...旁邊", "ipa": "/bɪˈsaɪd/", "trans": "besides (區分)", "col": "beside the point", "ex": "She sat beside me.", "pos": "prep."},
    "besides": {"def": "此外、而且、除...之外", "ipa": "/bɪˈsaɪdz/", "trans": "beside (區分)", "col": "besides that", "ex": "I have no other friends besides you.", "pos": "adv./prep."},
    "best": {"def": "最好的（地）、最多的（地）、最大量、打敗", "ipa": "/best/", "trans": "good, better", "col": "at best, do one's best", "ex": "She is my best friend.", "pos": "adj./adv./n./v."},
    "bet": {"def": "下注、打賭、賭金", "ipa": "/bet/", "trans": "better (分詞)", "col": "bet on, place a bet", "ex": "I bet he'll be late again.", "pos": "v./n."},
    "better": {"def": "更好的（地）、改進、勝過、更好者", "ipa": "/ˈbetə/", "trans": "good, best", "col": "had better, get better", "ex": "I hope you feel better soon.", "pos": "adj./adv./v./n."},
    "between": {"def": "在...之間、之間、中間地", "ipa": "/bɪˈtwiːn/", "trans": "interspace", "col": "between you and me", "ex": "Is there a train between London and Oxford?", "pos": "prep./adv."},
    "beyond": {"def": "在...那一邊、超出...、在那邊、遠處", "ipa": "/bɪˈjɒnd/", "trans": "yonder", "col": "beyond belief, beyond control", "ex": "The town is just beyond those hills.", "pos": "prep./adv."},
    "bicycle/bike": {"def": "腳踏車、騎腳踏車", "ipa": "/ˈbaɪsɪkl/ /baɪk/", "trans": "bicyclist", "col": "ride a bike, motor bike", "ex": "I go to school by bicycle.", "pos": "n./v."},
    "bill": {"def": "帳單、法案、鈔票、鳥嘴、給...開帳單", "ipa": "/bɪl/", "trans": "billing", "col": "pay the bill, dollar bill", "ex": "The waiter brought the bill.", "pos": "n./v."},
    "billion": {"def": "十億、無數", "ipa": "/ˈbɪljən/", "trans": "billions", "col": "billionaire", "ex": "The population of China is over one billion.", "pos": "n."},
    "biology": {"def": "生物學", "ipa": "/baɪˈɒlədʒi/", "trans": "biologist, biological", "col": "marine biology", "ex": "She is a student of biology.", "pos": "n."},
    "bird": {"def": "鳥、禽", "ipa": "/bɜːd/", "trans": "birdie", "col": "early bird, bird's-eye view", "ex": "The bird is singing in the tree.", "pos": "n."},
    "birth": {"def": "出生、分娩、起源", "ipa": "/bɜːθ/", "trans": "birthday, born", "col": "give birth to, birth certificate", "ex": "She gave birth to a healthy baby boy.", "pos": "n."},
    "birthday": {"def": "生日", "ipa": "/ˈbɜːθdeɪ/", "trans": "birth (名詞)", "col": "Happy Birthday", "ex": "When is your birthday?", "pos": "n."},
    "biscuit": {"def": "餅乾", "ipa": "/ˈbɪskɪt/", "trans": "cracker", "col": "chocolate biscuit", "ex": "Would you like a biscuit with your coffee?", "pos": "n."},
    "bit": {"def": "一小塊、一點點", "ipa": "/bɪt/", "trans": "bitty", "col": "a bit, bit by bit", "ex": "Wait a bit.", "pos": "n."},
    "bite": {"def": "咬、叮、咬傷、一小口", "ipa": "/baɪt/", "trans": "bit, bitten", "col": "bite off", "ex": "The dog bit him on the leg.", "pos": "v./n."},
    "bitter": {"def": "苦的、苦澀的", "ipa": "/ˈbɪtə/", "trans": "bitterness, bitterly", "col": "bitter pill, bitter taste", "ex": "This coffee tastes very bitter.", "pos": "adj."},
    "black": {"def": "黑色的、黑暗的、黑種人的、黑色、使變黑", "ipa": "/blæk/", "trans": "blacken, blackness", "col": "black coffee, in the black", "ex": "She was wearing a black dress.", "pos": "adj./n./v."},
    "blackboard": {"def": "黑板", "ipa": "/ˈblækbɔːd/", "trans": "chalkboard", "col": "write on the blackboard", "ex": "The teacher wrote the words on the blackboard.", "pos": "n."},
    "blame": {"def": "責備、責怪、過失、責任", "ipa": "/bleɪm/", "trans": "blameless", "col": "be to blame, blame someone for", "ex": "He blamed me for the accident.", "pos": "v./n."},
    "blank": {"def": "空白的、茫然的、空白處、空格、使模糊", "ipa": "/blæŋk/", "trans": "blankly", "col": "blank space, fill in the blanks", "ex": "Leave the last page blank.", "pos": "adj./n./v."},
    "blanket": {"def": "毛毯、覆蓋層、覆蓋、面面俱到的", "ipa": "/ˈblæŋkɪt/", "trans": "blanketing", "col": "electric blanket", "ex": "It was cold, so I put another blanket on the bed.", "pos": "n./v./adj."},
    "blast": {"def": "爆炸、衝擊波、強風、炸毀、抨擊", "ipa": "/blɑːst/", "trans": "blasting", "col": "blast off, at full blast", "ex": "The explosion was caused by a gas blast.", "pos": "n./v."},
    "bless": {"def": "祝福、保佑、保佑", "ipa": "/bles/", "trans": "blessed, blessing", "col": "God bless you", "ex": "The priest blessed the crowd.", "pos": "v."},
    "blind": {"def": "盲的、盲目的、百葉窗、遮掩、使失明", "ipa": "/blaɪnd/", "trans": "blindness, blindly", "col": "blind date, blind alley", "ex": "She is blind in one eye.", "pos": "adj./n./v."},
    "block": {"def": "大樓、街區、塊、障礙、阻擋、封鎖", "ipa": "/blɒk/", "trans": "blockage", "col": "apartment block, mental block", "ex": "The road was blocked by a fallen tree.", "pos": "n./v."},
    "blood": {"def": "血液、血統", "ipa": "/blʌd/", "trans": "bleed, bloody", "col": "blood pressure, blood type", "ex": "He lost a lot of blood in the accident.", "pos": "n."},
    "bloody": {"def": "流血的、殘酷的", "ipa": "/ˈblʌdi/", "trans": "blood (名詞)", "col": "bloody battle", "ex": "He had a bloody nose.", "pos": "adj."},
    "bloom": {"def": "開花、花朵、全盛期", "ipa": "/bluːm/", "trans": "blooming", "col": "in full bloom", "ex": "The roses are in bloom.", "pos": "n./v."},
    "blossom": {"def": "花、開花、興旺", "ipa": "/ˈblɒsəm/", "trans": "blossomed", "col": "cherry blossom", "ex": "The apple trees are in blossom.", "pos": "n./v."},
    "blow": {"def": "吹、吹響、毆打、打擊、吹氣聲", "ipa": "/bləʊ/", "trans": "blew, blown", "col": "blow out, blow up", "ex": "The wind is blowing hard.", "pos": "v./n."},
    "blue": {"def": "藍色的、憂鬱的、藍色、使變藍", "ipa": "/bluː/", "trans": "blueness", "col": "feeling blue, dark blue", "ex": "She has blue eyes.", "pos": "adj./n./v."},
    "board": {"def": "木板、董事會、伙食、登上、寄宿", "ipa": "/bɔːd/", "trans": "boarding", "col": "on board, notice board", "ex": "He is on the board of directors.", "pos": "n./v."},
    "boast": {"def": "自誇、吹嘘", "ipa": "/bəʊst/", "trans": "boastful", "col": "boast about", "ex": "She is always boasting about her children.", "pos": "v./n."},
    "boat": {"def": "船、小船、划船", "ipa": "/bəʊt/", "trans": "boating", "col": "fishing boat, in the same boat", "ex": "We went for a boat ride.", "pos": "n./v."},
    "body": {"def": "身體、主體、屍體、給...實體", "ipa": "/ˈbɒdi/", "trans": "bodily", "col": "body language, main body", "ex": "Regular exercise is good for the body.", "pos": "n./v."},
    "boil": {"def": "煮費、沸騰、疔、瘡", "ipa": "/bɔɪl/", "trans": "boiling, boiler", "col": "boil over, boiling point", "ex": "Is the water boiling yet?", "pos": "v./n."},
    "bold": {"def": "大膽的、粗體的", "ipa": "/bəʊld/", "trans": "boldness, boldly", "col": "bold move", "ex": "It was a bold decision.", "pos": "adj."},
    "bomb": {"def": "炸彈、爆炸、轟炸", "ipa": "/bɒm/", "trans": "bomber, bombing", "col": "time bomb, hydrogen bomb", "ex": "A bomb exploded in the city center.", "pos": "n./v."},
    "bond": {"def": "連結、債券、契約、使連結", "ipa": "/bɒnd/", "trans": "bonding", "col": "family bond, government bond", "ex": "There is a close bond between the two sisters.", "pos": "n./v."},
    "bone": {"def": "骨頭、移除骨頭", "ipa": "/bəʊn/", "trans": "bony", "col": "broken bone, bone marrow", "ex": "He broke a bone in his leg.", "pos": "n./v."},
    "book": {"def": "書、卷、預訂、登記、帳簿的", "ipa": "/bʊk/", "trans": "booklet, booking", "col": "book a flight, pocket book", "ex": "He is reading a book.", "pos": "n./v./adj."},
    "bookcase": {"def": "書櫃", "ipa": "/ˈbʊkkeɪs/", "trans": "bookshelf", "col": "books in the bookcase", "ex": "He put the books back in the bookcase.", "pos": "n."},
    "border": {"def": "邊界、邊緣、接壤、裝邊", "ipa": "/ˈbɔːdə/", "trans": "bordered", "col": "cross the border", "ex": "They live near the border.", "pos": "n./v."},
    "bored": {"def": "感到無聊的", "ipa": "/bɔːd/", "trans": "bore (動詞), boring", "col": "get bored", "ex": "I'm bored. Let's do something.", "pos": "adj."},
    "boring": {"def": "令人無聊的", "ipa": "/ˈbɔːrɪŋ/", "trans": "bore (動詞), bored", "col": "boring job", "ex": "The movie was very boring.", "pos": "adj."},
    "born": {"def": "出生的、天生的", "ipa": "/bɔːn/", "trans": "birth (名詞)", "col": "be born in", "ex": "I was born in 1990.", "pos": "adj."},
    "borrow": {"def": "借入", "ipa": "/ˈbɒrəʊ/", "trans": "borrower, borrowing", "col": "borrow from", "ex": "Can I borrow your pen?", "pos": "v."},
    "boss": {"def": "老闆、首領、指揮、做主", "ipa": "/bɒs/", "trans": "bossy", "col": "big boss", "ex": "Ask your boss for a raise.", "pos": "n./v."},
    "both": {"def": "兩者（都）、並、不但...而且", "ipa": "/bəʊθ/", "trans": "twain", "col": "both of them", "ex": "Both my parents are teachers.", "pos": "pron./adj./adv."},
    "bother": {"def": "打擾、煩惱、麻煩、煩人的人", "ipa": "/ˈbɒðə/", "trans": "bothersome", "col": "bother with, don't bother", "ex": "I'm sorry to bother you.", "pos": "v./n."},
    "bottle": {"def": "瓶子、裝入瓶中", "ipa": "/ˈbɒtl/", "trans": "bottled", "col": "water bottle, baby bottle", "ex": "He drank a whole bottle of water.", "pos": "n./v."},
    "bottom": {"def": "底部、臀部、底部的、到達底部", "ipa": "/ˈbɒtəm/", "trans": "bottomless", "col": "at the bottom of", "ex": "Sign your name at the bottom of the page.", "pos": "n./adj./v."},
    "bounce": {"def": "彈起、蹦、反彈（力）", "ipa": "/baʊns/", "trans": "bouncy", "col": "bounce back", "ex": "The ball bounced off the wall.", "pos": "v./n."},
    "bound": {"def": "必定的、受約束的、範圍、界限、彈跳", "ipa": "/baʊnd/", "trans": "boundary", "col": "bound to, out of bounds", "ex": "You are bound to succeed.", "pos": "adj./n./v."},
    "bow": {"def": "鞠躬、彎腰、弓、蝴蝶結", "ipa": "/baʊ/ (v.) /bəʊ/ (n.)", "trans": "bowing", "col": "bow tie, take a bow", "ex": "He gave a polite bow.", "pos": "v./n."},
    "bowl": {"def": "碗、球、滾球、打保齡球", "ipa": "/bəʊl/", "trans": "bowls, bowling", "col": "sugar bowl, soup bowl", "ex": "He ate a bowl of soup.", "pos": "n./v."},
    "box": {"def": "箱子、盒子、拳擊、裝箱", "ipa": "/bɒks/", "trans": "boxing, boxer", "col": "post office box, gearbox", "ex": "She put the jewelry in a small box.", "pos": "n./v."},
    "boy": {"def": "男孩", "ipa": "/bɔɪ/", "trans": "boyfriend, boyhood", "col": "old boy", "ex": "He is a good boy.", "pos": "n."},
    "brain": {"def": "大腦、智力、猛擊...的頭部", "ipa": "/breɪn/", "trans": "brainy", "col": "brain drain, human brain", "ex": "The brain is the most complex organ.", "pos": "n./v."},
    "brake": {"def": "煞車、制動器、煞車、減速", "ipa": "/breɪk/", "trans": "braking", "col": "apply the brakes, emergency brake", "ex": "He hit the brakes to avoid the accident.", "pos": "n./v."},
    "branch": {"def": "分枝、分公司、分科、發枝、分岔", "ipa": "/brɑːntʃ/", "trans": "branched", "col": "local branch, olive branch", "ex": "The tree has many branches.", "pos": "n./v."},
    "brand": {"def": "品牌、商標、烙印、打上品牌", "ipa": "/brænd/", "trans": "branding", "col": "brand name, world-famous brand", "ex": "Which brand of tea do you prefer?", "pos": "n./v."},
    "brass": {"def": "黃銅、銅管樂器", "ipa": "/brɑːs/", "trans": "brassy", "col": "brass band", "ex": "The door handle is made of brass.", "pos": "n."},
    "brave": {"def": "勇敢的、華麗的、冒險、勇敢的人", "ipa": "/breɪv/", "trans": "bravery, bravely", "col": "brave the elements", "ex": "He is a brave man.", "pos": "adj./v./n."},
}

with open("batch_l2_p3.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART3, f, ensure_ascii=False, indent=2)
