import json

# Level 1 Part 14: (Evidently - Exercise)
L1_PART14 = {
    "evidently": {"def": "明顯地、顯然", "ipa": "/ˈevɪdəntli/", "trans": "evident (明顯的)", "col": "evidently upset", "ex": "Evidently, they have forgotten our meeting."},
    "evil": {"def": "邪惡的、惡魔", "ipa": "/ˈiːvl/", "trans": "evilly", "col": "evil spirit", "ex": "He is an evil man."},
    "evolution": {"def": "進化、演變", "ipa": "/ˌiːvəˈluːʃn/", "trans": "evolve (進化)", "col": "theory of evolution", "ex": "The evolution of the species took millions of years."},
    "evolve": {"def": "進展、演變、進化", "ipa": "/iˈvɒlv/", "trans": "evolution (名詞)", "col": "evolve from", "ex": "Plants and animals evolve and change over time."},
    "ex": {"def": "前任的", "ipa": "/eks/", "trans": "无", "col": "ex-husband, ex-wife", "ex": "She is still friends with her ex."},
    "exact": {"def": "確切的、嚴格的", "ipa": "/ɪɡˈzækt/", "trans": "exactly", "col": "exact time", "ex": "Tell me the exact time of the meeting."},
    "exactly": {"def": "確切地、正是", "ipa": "/ɪɡˈzæktli/", "trans": "exact (形容詞)", "col": "not exactly", "ex": "That's exactly what I wanted."},
    "exaggerate": {"def": "誇大、言過其實", "ipa": "/ɪɡˈzædʒəreɪt/", "trans": "exaggeration", "col": "exaggerate the facts", "ex": "Don't exaggerate the importance of the incident."},
    "exaggeration": {"def": "誇張", "ipa": "/ɪɡˌzædʒəˈreɪʃn/", "trans": "exaggerate (動詞)", "col": "slight exaggeration", "ex": "It's no exaggeration to say that he is the best."},
    "exam/examination": {"def": "考試、檢查", "ipa": "/ɪɡˈzæm/", "trans": "exams, examine (動詞)", "col": "final exam, entrance exam", "ex": "I have an English exam tomorrow."},
    "examine": {"def": "檢查、審核、考試", "ipa": "/ɪɡˈzæmɪn/", "trans": "examination (名詞)", "col": "examine carefully", "ex": "The doctor examined the patient carefully."},
    "examinee": {"def": "應試者", "ipa": "/ɪɡˌzæmɪˈniː/", "trans": "examinees", "col": "nervous examinee", "ex": "The examinees were busy writing."},
    "examiner": {"def": "主考官、審查員", "ipa": "/ɪɡˈzæmɪnə/", "trans": "examiners", "col": "strict examiner", "ex": "The examiner explained the rules of the test."},
    "example": {"def": "例子、榜樣", "ipa": "/ɪɡˈzɑːmpl/", "trans": "examples", "col": "for example, set an example", "ex": "Let me give you an example."},
    "exasperate": {"def": "激怒、使惱火", "ipa": "/ɪɡˈzæspəreɪt/", "trans": "exasperated, exasperating", "col": "exasperate someone", "ex": "She was exasperated by his constant complaints."},
    "exceed": {"def": "超過、超越", "ipa": "/ɪkˈsiːd/", "trans": "excess (過量), excessive (過度的)", "col": "exceed the speed limit", "ex": "Drivers should not exceed the speed limit."},
    "exceedingly": {"def": "極其地、非常", "ipa": "/ɪkˈsiːdɪŋli/", "trans": "exceed (動詞)", "col": "exceedingly difficult", "ex": "He is exceedingly clever."},
    "excel": {"def": "勝過、卓越", "ipa": "/ɪkˈsel/", "trans": "excellencies", "col": "excel in/at", "ex": "She excels in everything she does."},
    "excellence": {"def": "優美、卓越", "ipa": "/ˈeksələns/", "trans": "excellent (優秀的)", "col": "academic excellence", "ex": "He received an award for excellence."},
    "excellent": {"def": "優秀的、傑出的", "ipa": "/ˈeksələnt/", "trans": "excellently", "col": "excellent achievement", "ex": "That's an excellent idea."},
    "except": {"def": "除了...之外", "ipa": "/ɪkˈsept/", "trans": "exception (例外), exceptional (卓越的)", "col": "except for", "ex": "Everyone is here except him."},
    "exception": {"def": "例外、除外", "ipa": "/ɪkˈsepʃn/", "trans": "except (副詞)", "col": "with the exception of", "ex": "There's an exception to every rule."},
    "exceptional": {"def": "卓越的、例外的", "ipa": "/ɪkˈsepʃənl/", "trans": "exceptionally", "col": "exceptional talent", "ex": "He has an exceptional talent for music."},
    "excess": {"def": "過量、過度、超額", "ipa": "/ɪkˈses/", "trans": "excesses, excessive", "col": "carry excess weight", "ex": "Excess of sugar is bad for health."},
    "excessive": {"def": "過度的、過分的", "ipa": "/ɪkˈsesɪv/", "trans": "excessively", "col": "excessive drinking", "ex": "Excessive noise is harmful."},
    "exchange": {"def": "交換、交易、交流", "ipa": "/ɪksˈtʃeɪndʒ/", "trans": "exchanged", "col": "exchange ideas, stock exchange", "ex": "We exchanged phone numbers."},
    "excite": {"def": "使興奮、激發", "ipa": "/ɪkˈsaɪt/", "trans": "excited, exciting, excitement", "col": "excite curiosity", "ex": "The movie excited the audience."},
    "excited": {"def": "感到興奮的", "ipa": "/ɪkˈsaɪtɪd/", "trans": "excite (動詞)", "col": "be excited about", "ex": "We are excited about the trip."},
    "excitement": {"def": "興奮、刺激", "ipa": "/ɪkˈsaɪtmənt/", "trans": "excite (動詞)", "col": "filled with excitement", "ex": "The children were full of excitement."},
    "exciting": {"def": "令人興奮的", "ipa": "/ɪkˈsaɪtɪŋ/", "trans": "excitingly", "col": "exciting news", "ex": "It was a very exciting game."},
    "exclaim": {"def": "呼喊、大聲驚叫", "ipa": "/ɪkˈskleɪm/", "trans": "exclamation (名詞)", "col": "exclaim with joy", "ex": "He exclaimed with delight."},
    "exclamation": {"def": "驚呼、感歎詞", "ipa": "/ˌekskləˈmeɪʃn/", "trans": "exclaim (動詞)", "col": "exclamation mark", "ex": "His exclamation of surprise was heard by all."},
    "exclude": {"def": "排除、排斥", "ipa": "/ɪkˈskluːd/", "trans": "exclusive (獨佔的/唯一的), exclusion (排除)", "col": "exclude from", "ex": "The price excludes service charges."},
    "exclusive": {"def": "獨有的、排外的、唯一的", "ipa": "/ɪkˈskluːsɪv/", "trans": "exclusively", "col": "exclusive interview", "ex": "The club is exclusive to members."},
    "exclusively": {"def": "獨佔地、排外地", "ipa": "/ɪkˈskluːsɪvli/", "trans": "exclusive (形容詞)", "col": "exclusively for", "ex": "The offer is exclusively for new customers."},
    "excursion": {"def": "遠足、遊覽、離題", "ipa": "/ɪkˈskɜːʃn/", "trans": "excursions", "col": "school excursion", "ex": "They went on an excursion to the mountains."},
    "excuse": {"def": "藉口、原諒、免除", "ipa": "/ɪkˈskjuːs/", "trans": "excused", "col": "excuse me, an excuse for", "ex": "There is no excuse for being late."},
    "execute": {"def": "處死、執行", "ipa": "/ˈeksɪkjuːt/", "trans": "execution", "col": "execute a plan", "ex": "The general executed the order."},
    "executive": {"def": "主管、執行的、總經理", "ipa": "/ɪɡˈzekjətɪv/", "trans": "executives", "col": "executive officer", "ex": "He is a top executive in the company."},
    "exercise": {"def": "運動、練習", "ipa": "/ˈeksəsaɪz/", "trans": "exercised", "col": "physical exercise, doing exercises", "ex": "Exercise is good for your health."},
}

with open("batch_l1_p14.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART14, f, ensure_ascii=False, indent=2)
