import json

# Level 1 Part 43: (Pocket - Portrait)
L1_PART43 = {
    "pocket": {"def": "口袋、小袋、錢財、放進口袋、侵吞", "ipa": "/ˈpɒkɪt/", "trans": "pockets, pocketed", "col": "pocket money, out of pocket", "ex": "He put the keys in his pocket."},
    "poem": {"def": "詩、韻文", "ipa": "/ˈpəʊɪm/", "trans": "poems, poet, poetry", "col": "write a poem", "ex": "She recited a beautiful poem."},
    "poet": {"def": "詩人", "ipa": "/ˈpəʊɪt/", "trans": "poets, poetic", "col": "famous poet", "ex": "Dante was a great Italian poet."},
    "poetic": {"def": "詩的、詩意的", "ipa": "/pəʊˈetɪk/", "trans": "poetically", "col": "poetic justice", "ex": "The description was very poetic."},
    "poetry": {"def": "詩歌、詩意", "ipa": "/ˈpəʊətri/", "trans": "poet, poem", "col": "lyric poetry", "ex": "He enjoys reading poetry."},
    "point": {"def": "點、要點、得分、尖端、指向", "ipa": "/pɔɪnt/", "trans": "points, pointed", "col": "to the point, point out", "ex": "That's a good point."},
    "pointed": {"def": "尖的、尖銳的、針對性的", "ipa": "/ˈpɔɪntɪd/", "trans": "pointedly", "col": "pointed remark", "ex": "He has a pointed chin."},
    "pointless": {"def": "無意義的、徒勞的", "ipa": "/ˈpɔɪntləs/", "trans": "pointlessly", "col": "pointless argument", "ex": "It's pointless to argue with him."},
    "poison": {"def": "毒藥、毒素、毒害、下毒", "ipa": "/ˈpɔɪzn/", "trans": "poisons, poisoned, poisonous", "col": "food poisoning", "ex": "The rat died of poison."},
    "poisonous": {"def": "有毒的、有害的、惡毒的", "ipa": "/ˈpɔɪznəs/", "trans": "poison (名詞)", "col": "poisonous snake", "ex": "The mushroom is poisonous."},
    "poke": {"def": "戳、刺、伸出、撥、懶漢、一戳", "ipa": "/pəʊk/", "trans": "poked", "col": "poke fun at, poke around", "ex": "Don't poke me!"},
    "poker": {"def": "撥火棒、撲克牌戲", "ipa": "/ˈpəʊkə/", "trans": "pokers (恆複)", "col": "poker face", "ex": "He has a perfect poker face."},
    "polar": {"def": "極地的、對立的、磁極的", "ipa": "/ˈpəʊlə/", "trans": "poles, polarity", "col": "polar bear, polar region", "ex": "The polar ice caps are melting."},
    "pole": {"def": "柱、杆、地極、磁極", "ipa": "/pəʊl/", "trans": "poles", "col": "north pole, south pole", "ex": "The flag was flying on a pole."},
    "police": {"def": "警察、警方、治安、監督", "ipa": "/pəˈliːs/", "trans": "policeman, policewoman", "col": "police station, call the police", "ex": "The police are investigating the crime."},
    "policeman": {"def": "警察、警員", "ipa": "/pəˈliːsmən/", "trans": "policemen", "col": "traffic policeman", "ex": "The policeman stopped the car."},
    "policy": {"def": "政策、方針、策略、保險單", "ipa": "/ˈpɒləsi/", "trans": "policies", "col": "foreign policy, insurance policy", "ex": "The company has a no-smoking policy."},
    "polish": {"def": "拋光劑、光澤、修養、擦亮、使完美", "ipa": "/ˈpɒlɪʃ/", "trans": "polished", "col": "nail polish, boot polish", "ex": "He polished his shoes until they shone."},
    "polished": {"def": "擦亮的、優美的、圓滑的", "ipa": "/ˈpɒlɪʃt/", "trans": "polish (動詞)", "col": "polished performance", "ex": "She gave a polished performance on the piano."},
    "polite": {"def": "有禮貌的、客氣的、有教養的", "ipa": "/pəˈlaɪt/", "trans": "politely, politeness", "col": "be polite to", "ex": "It is polite to say thank you."},
    "politely": {"def": "有禮貌地、客氣地", "ipa": "/pəˈlaɪtli/", "trans": "polite (形容詞)", "col": "ask politely", "ex": "He asked politely if he could sit down."},
    "politeness": {"def": "禮貌、客氣、體面", "ipa": "/pəˈlaɪtnəs/", "trans": "polite (形容詞)", "col": "show politeness", "ex": "She is known for her politeness."},
    "political": {"def": "政治的、政府的、政黨的", "ipa": "/pəˈlɪtɪkl/", "trans": "politically, politics", "col": "political party, political leader", "ex": "He is very active in political life."},
    "politician": {"def": "政治家、政客", "ipa": "/ˌpɒləˈtɪʃn/", "trans": "politicians", "col": "career politician", "ex": "The politician gave a speech."},
    "politics": {"def": "政治、政治學、權術", "ipa": "/ˈpɒlətɪks/", "trans": "political", "col": "office politics, enter politics", "ex": "I don't like to talk about politics."},
    "poll": {"def": "民意調查、投票、選舉、頭、進行民調", "ipa": "/pəʊl/", "trans": "polls, polled", "col": "opinion poll, go to the polls", "ex": "The latest poll shows he is leading."},
    "pollen": {"def": "花粉", "ipa": "/ˈpɒlən/", "trans": "pollens", "col": "pollen count", "ex": "Pollen causes hay fever in some people."},
    "pollute": {"def": "污染、弄髒、敗壞", "ipa": "/pəˈluːt/", "trans": "polluted, pollution", "col": "pollute the environment", "ex": "Factories pollute the air."},
    "pollution": {"def": "污染、污染物", "ipa": "/pəˈluːʃn/", "trans": "pollutant", "col": "air pollution, water pollution", "ex": "Pollution is a serious problem in the city."},
    "polo": {"def": "馬球", "ipa": "/ˈpəʊləʊ/", "trans": "polos", "col": "water polo", "ex": "Polo is called the sport of kings."},
    "polygraph": {"def": "測謊器、複寫器", "ipa": "/ˈpɒliɡrɑːf/", "trans": "polygraphs", "col": "take a polygraph test", "ex": "The suspect agreed to a polygraph test."},
    "pond": {"def": "池塘", "ipa": "/pɒnd/", "trans": "ponds", "col": "fish pond", "ex": "The frogs are jumping into the pond."},
    "ponder": {"def": "沉思、衡量、考慮", "ipa": "/ˈpɒndə/", "trans": "pondered", "col": "ponder over", "ex": "He pondered over the question for a long time."},
    "pony": {"def": "矮種馬、小馬", "ipa": "/ˈpəʊni/", "trans": "ponies", "col": "ride a pony", "ex": "The little girl wanted a pony for her birthday."},
    "pool": {"def": "水池、游泳池、撞球、共同資金、合夥、共用", "ipa": "/puːl/", "trans": "pools", "col": "swimming pool, car pool", "ex": "Let's go for a swim in the pool."},
    "poor": {"def": "貧窮的、可憐的、粗劣的、卑鄙的", "ipa": "/pɔː/", "trans": "poorly, poverty", "col": "poor health, poor quality", "ex": "He comes from a poor family."},
    "poorly": {"def": "貧窮地、糟糕地、不健康地", "ipa": "/ˈpɔːli/", "trans": "poor (形容詞)", "col": "be poorly treated", "ex": "He performed poorly in the exam."},
    "pop": {"def": "爆裂聲、流行音樂、爸爸、爆裂、砰然出現", "ipa": "/pɒp/", "trans": "popped", "col": "pop music, pop up", "ex": "A balloon popped loudly."},
    "pope": {"def": "教皇、主教", "ipa": "/pəʊp/", "trans": "popes", "col": "the Pope", "ex": "The Pope visited the country."},
    "popular": {"def": "受歡迎的、流行的、通俗的", "ipa": "/ˈpɒpjələ/", "trans": "popularity, popularize", "col": "popular music, popular culture", "ex": "Football is a popular sport."},
    "popularity": {"def": "普及、流行、受歡迎", "ipa": "/ˌpɒpjuˈlærəti/", "trans": "popular (形容詞)", "col": "gain popularity", "ex": "The singer's popularity is growing."},
    "popularize/popularise": {"def": "推廣、使通俗化、使流行", "ipa": "/ˈpɒpjələraɪz/", "trans": "popularized", "col": "popularize science", "ex": "Television can help popularize classical music."},
    "population": {"def": "人口、居民、群體", "ipa": "/ˌpɒpjuˈleɪʃn/", "trans": "populations", "col": "aging population, over population", "ex": "The population of China is over 1.4 billion."},
    "porcelain": {"def": "瓷器、瓷的", "ipa": "/ˈpɔːsəlɪn/", "trans": "無", "col": "fine porcelain", "ex": "Handel the porcelain with care."},
    "porch": {"def": "門廊、走廊", "ipa": "/pɔːtʃ/", "trans": "porches", "col": "front porch", "ex": "We sat on the porch and drank lemonade."},
    "porcupine": {"def": "豪豬", "ipa": "/ˈpɔːkjupaɪn/", "trans": "porcupines", "col": "sharp porcupine", "ex": "A porcupine's quills protect it from enemies."},
    "pore": {"def": "毛孔、細孔、注視、鑽研", "ipa": "/pɔː/", "trans": "pores", "col": "pore over", "ex": "He pored over the map for hours."},
    "pork": {"def": "豬肉", "ipa": "/pɔːk/", "trans": "無", "col": "roast pork", "ex": "I don't eat pork."},
    "porridge": {"def": "粥、麥片粥", "ipa": "/ˈpɒrɪdʒ/", "trans": "無", "col": "bowl of porridge", "ex": "He had porridge for breakfast."},
    "port": {"def": "港口、出口、口(電腦)、左舷", "ipa": "/pɔːt/", "trans": "ports", "col": "port city, free port", "ex": "The ship arrived at the port."},
    "portable": {"def": "便攜式的、手提的", "ipa": "/ˈpɔːtəbl/", "trans": "portability", "col": "portable computer", "ex": "I have a portable radio."},
    "portal": {"def": "大門、正門、入口網站", "ipa": "/ˈpɔːtl/", "trans": "portals", "col": "web portal", "ex": "The main portal of the cathedral is magnificent."},
    "porter": {"def": "搬運工、守門人", "ipa": "/ˈpɔːtə/", "trans": "porters", "col": "railway porter", "ex": "The porter carried our bags to our room."},
    "portfolio": {"def": "公事包、作品集、投資組合", "ipa": "/pɔːtˈfəʊliəʊ/", "trans": "portfolios", "col": "investment portfolio, model portfolio", "ex": "The designer showed me her portfolio."},
    "portion": {"def": "部分、一份、遺產、分配", "ipa": "/ˈpɔːʃn/", "trans": "portions", "col": "large portion", "ex": "She ate a small portion of the cake."},
    "portly": {"def": "肥胖的、魁梧的、莊嚴的", "ipa": "/ˈpɔːtli/", "trans": "portliness", "col": "portly gentleman", "ex": "A portly gentleman walked into the room."},
    "portrait": {"def": "肖像、畫像、描繪", "ipa": "/ˈpɔːtreɪt/", "trans": "portraits", "col": "family portrait, portrait gallery", "ex": "He painted a portrait of her."},
}

with open("batch_l1_p43.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART43, f, ensure_ascii=False, indent=2)
