import json

# Level 1 Part 54: (Read - Reconnaissance)
L1_PART54 = {
    "read": {"def": "閱讀、朗讀、讀懂、讀物", "ipa": "/riːd/", "trans": "read, readable, reader, reading", "col": "read aloud, read between the lines", "ex": "I like to read before bed."},
    "readable": {"def": "可讀的、易讀的、有趣的", "ipa": "/ˈriːdəbl/", "trans": "readability", "col": "highly readable", "ex": "The handwriting is not very readable."},
    "readily": {"def": "樂意地、容易地、迅速地", "ipa": "/ˈredɪli/", "trans": "ready (形容詞)", "col": "readily available", "ex": "He readily agreed to help."},
    "readiness": {"def": "準備就緒、樂意、敏捷", "ipa": "/ˈredɪnəs/", "trans": "ready (形容詞)", "col": "state of readiness", "ex": "The army is in a state of readiness."},
    "reading": {"def": "閱讀、讀物、讀數、解釋", "ipa": "/ˈriːdɪŋ/", "trans": "read (動詞)", "col": "speed reading, reading room", "ex": "Reading is my favorite hobby."},
    "ready": {"def": "準備好的、樂意的、現成的、準備", "ipa": "/ˈredi/", "trans": "readily, readiness", "col": "get ready, ready made", "ex": "Are you ready to go?"},
    "real": {"def": "真實的、現實的、真正的、現實", "ipa": "/rɪəl/", "trans": "reality, realize, really", "col": "real estate, real life", "ex": "Is this real gold?"},
    "realism": {"def": "現實主義、實在論、現實性", "ipa": "/ˈrɪəlɪzəm/", "trans": "realist, realistic", "col": "social realism", "ex": "The movie has a sense of realism."},
    "realistic": {"def": "現實的、逼真的、實際的", "ipa": "/ˌrɪəˈlɪstɪk/", "trans": "realistically", "col": "realistic goal, realistic expectation", "ex": "We need to be realistic about this."},
    "reality": {"def": "現實、真實、實際存在的事物", "ipa": "/riˈæləti/", "trans": "realities", "col": "virtual reality, in reality", "ex": "Television is different from reality."},
    "realizable": {"def": "可實現的、可變現的", "ipa": "/ˈrɪəlaɪzəbl/", "trans": "realize (動詞)", "col": "realizable asset", "ex": "The goal is not easily realizable."},
    "realization": {"def": "實現、體會、領悟、變現", "ipa": "/ˌrɪəlaɪˈzeɪʃn/", "trans": "realize (動詞)", "col": "sudden realization", "ex": "There was a sudden realization of danger."},
    "realize": {"def": "實現、領悟、了解、變現", "ipa": "/ˈrɪəlaɪz/", "trans": "realized, realization", "col": "realize a dream, realize the potential", "ex": "I didn't realize you were there."},
    "really": {"def": "真正地、實在、事實上", "ipa": "/ˈrɪəli/", "trans": "real (形容詞)", "col": "really good, not really", "ex": "I really like this place."},
    "realm": {"def": "領域、範圍、王國", "ipa": "/relm/", "trans": "realms", "col": "in the realm of, spiritual realm", "ex": "This is beyond the realm of possibility."},
    "reams": {"def": "大量、令(紙張單位)", "ipa": "/riːmz/", "trans": "ream", "col": "reams of paper", "ex": "He wrote reams of poetry."},
    "reap": {"def": "收割、收穫、獲得", "ipa": "/riːp/", "trans": "reaped, reaper", "col": "reap what one sows, reap the benefits", "ex": "You will reap the rewards of your hard work."},
    "rear": {"def": "後面、後方、背部、撫養", "ipa": "/rɪə/", "trans": "reared", "col": "rear window, bring up the rear", "ex": "The garden is at the rear of the house."},
    "rearm": {"def": "重新武裝、重新裝備", "ipa": "/ˌriːˈɑːm/", "trans": "rearmament", "col": "rearm the military", "ex": "The nation began to rearm fast."},
    "rearrange": {"def": "重新安排、重新佈置", "ipa": "/ˌriːəˈreɪndʒ/", "trans": "rearranged, rearrangement", "col": "rearrange furniture", "ex": "Can we rearrange the meeting?"},
    "reason": {"def": "原因、理智、推論、說服", "ipa": "/ˈriːzn/", "trans": "reasonable, reasoned, reasoning", "col": "for some reason, within reason", "ex": "What is the reason for the delay?"},
    "reasonable": {"def": "合理的、通情達理的、尚可的", "ipa": "/ˈriːznəbl/", "trans": "reasonably", "col": "reasonable price, reasonable doubt", "ex": "That sounds like a reasonable request."},
    "reasonably": {"def": "合理地、相當地、通情達理地", "ipa": "/ˈriːznəbli/", "trans": "reasonable (形容詞)", "col": "reasonably priced", "ex": "The hotel was reasonably clean."},
    "reasoning": {"def": "推理、論證、推斷", "ipa": "/ˈriːznɪŋ/", "trans": "reason (名詞/動詞)", "col": "logical reasoning", "ex": "His reasoning is based on facts."},
    "reassure": {"def": "使放心、消除...疑慮", "ipa": "/ˌriːəˈʃʊə/", "trans": "reassured, reassurance", "col": "reassure someone", "ex": "He smiled to reassure her."},
    "rebel": {"def": "反叛者、造反者、反叛", "ipa": "/ˈrebl/", "trans": "rebelled, rebellion, rebellious", "col": "rebel leader", "ex": "She was a rebel in her youth."},
    "rebellion": {"def": "反叛、造反、叛亂", "ipa": "/rɪˈbeljən/", "trans": "rebellions", "col": "armed rebellion", "ex": "The army crushed the rebellion."},
    "rebellious": {"def": "反叛的、難控制的", "ipa": "/rɪˈbeljəs/", "trans": "rebelliously", "col": "rebellious teenager", "ex": "He has always been a rebellious child."},
    "rebirth": {"def": "重生、復興", "ipa": "/ˌriːˈbɜːθ/", "trans": "無", "col": "spiritual rebirth", "ex": "The city is experiencing a rebirth."},
    "rebound": {"def": "彈回、重新振作、回報", "ipa": "/rɪˈbaʊnd/", "trans": "rebounded", "col": "on the rebound", "ex": "The ball rebounded off the wall."},
    "rebuff": {"def": "回絕、沮喪、拒絕", "ipa": "/rɪˈbʌf/", "trans": "rebuffed", "col": "suffer a rebuff", "ex": "She rebuffed all his attempts to help."},
    "rebuke": {"def": "譴責、指責、非難", "ipa": "/rɪˈbjuːk/", "trans": "rebuked", "col": "sharp rebuke", "ex": "He received a stern rebuke for his behavior."},
    "rebut": {"def": "反駁、揭穿、擊退", "ipa": "/rɪˈbʌt/", "trans": "rebutted, rebuttal", "col": "rebut a claim", "ex": "He attempted to rebut the argument."},
    "rebuttal": {"def": "反駁、揭穿", "ipa": "/rɪˈbʌtl/", "trans": "rebutals", "col": "submit a rebuttal", "ex": "She prepared a strong rebuttal to the charges."},
    "recalcitrant": {"def": "反抗的、頑強的、不聽從指揮的", "ipa": "/rɪˈkælsɪtrənt/", "trans": "recalcitrance", "col": "recalcitrant child", "ex": "The recalcitrant prisoner refused to cooperate."},
    "recall": {"def": "回想起、召回、回收、回憶", "ipa": "/rɪˈcɔːl/", "trans": "recalled", "col": "recall notice, beyond recall", "ex": "I can't recall his name."},
    "recant": {"def": "撤回、放棄、聲明廢除", "ipa": "/rɪˈkænt/", "trans": "recanted", "col": "recant a testimony", "ex": "He was forced to recant his beliefs."},
    "recapitulate": {"def": "概括、扼要重述", "ipa": "/ˌriːkəˈpɪtʃuleɪt/", "trans": "recapitulation", "col": "recapitulate the main points", "ex": "Let me briefly recapitulate what has been said."},
    "recede": {"def": "後退、收回、跌落", "ipa": "/rɪˈsiːd/", "trans": "receded", "col": "recede into the distance", "ex": "The flood waters began to recede."},
    "receipt": {"def": "收據、發票、收到、進款", "ipa": "/rɪˈsiːt/", "trans": "receipts", "col": "on receipt of, acknowledge receipt", "ex": "Do you need a receipt?"},
    "receive": {"def": "收到、接受、接待", "ipa": "/rɪˈsiːv/", "trans": "received, receiver, reception", "col": "receive a letter, receive visitors", "ex": "I received a gift yesterday."},
    "receiver": {"def": "接收器、接手、話筒、收件人", "ipa": "/rɪˈsiːvə/", "trans": "receivers", "col": "telephone receiver", "ex": "He picked up the receiver."},
    "recent": {"def": "最近的、近代的", "ipa": "/ˈriːsnt/", "trans": "recently", "col": "recent events, in recent years", "ex": "What are your recent findings?"},
    "recently": {"def": "最近、近來", "ipa": "/ˈriːsntli/", "trans": "recent (形容詞)", "col": "most recently", "ex": "I saw him recently."},
    "receptive": {"def": "善於接受的、能容納的", "ipa": "/rɪˈseptɪv/", "trans": "receptivity", "col": "be receptive to ideas", "ex": "She was receptive to new suggestions."},
    "receptor": {"def": "接受器、感受器", "ipa": "/rɪˈseptə/", "trans": "receptors", "col": "sensory receptor", "ex": "The drug binds to the cell receptor."},
    "recession": {"def": "經濟衰退、後退", "ipa": "/rɪˈseʃn/", "trans": "recessions", "col": "economic recession", "ex": "The country is in a deep recession."},
    "recipe": {"def": "食譜、處方、秘訣", "ipa": "/ˈresəpi/", "trans": "recipes", "col": "recipe for success", "ex": "Do you have a good recipe for bread?"},
    "recipient": {"def": "接受者、容器、領受的", "ipa": "/rɪˈsɪpiənt/", "trans": "recipients", "col": "award recipient", "ex": "He was the recipient of many awards."},
    "reciprocal": {"def": "互惠的、相互的、倒數的、倒數", "ipa": "/rɪˈsɪprəkl/", "trans": "reciprocally, reciprocate", "col": "reciprocal trade", "ex": "They have a reciprocal relationship."},
    "reciprocate": {"def": "回報、互換、往復運動", "ipa": "/rɪˈsɪprəkeɪt/", "trans": "reciprocated, reciprocity", "col": "reciprocate a favor", "ex": "She didn't reciprocate his feelings."},
    "reciprocity": {"def": "互惠、相互性", "ipa": "/ˌresɪˈprɒsəti/", "trans": "reciprocal", "col": "principle of reciprocity", "ex": "Reciprocity is essential in diplomacy."},
    "recital": {"def": "獨奏會、朗誦、背誦", "ipa": "/rɪˈsaɪtl/", "trans": "recitals", "col": "piano recital", "ex": "Are you going to the piano recital?"},
    "recitation": {"def": "朗誦、背誦、陳述", "ipa": "/ˌresɪˈteɪʃn/", "trans": "recite (動詞)", "col": "poetry recitation", "ex": "The student gave a fine recitation."},
    "recite": {"def": "背誦、朗讀、敘述", "ipa": "/rɪˈsaɪt/", "trans": "recited, recital", "col": "recite a poem", "ex": "He can recite the entire play."},
    "reckless": {"def": "魯莽的、不計後果的", "ipa": "/ˈrekləs/", "trans": "recklessly", "col": "reckless driving", "ex": "He was arrested for reckless driving."},
    "reckon": {"def": "計算、估計、猜想、指望", "ipa": "/ˈrekən/", "trans": "reckoned", "col": "reckon on, reckon with", "ex": "I reckon that he'll be late."},
    "reclaim": {"def": "開墾、回收、感化、糾正、開墾", "ipa": "/rɪˈkleɪm/", "trans": "reclaimed, reclamation", "col": "reclaim land from sea", "ex": "They are trying to reclaim the wasteland."},
    "recline": {"def": "斜倚、靠、向後傾斜", "ipa": "/rɪˈklaɪn/", "trans": "reclined, recliner", "col": "recline on a sofa", "ex": "He was reclining on the beach chair."},
    "recognizable": {"def": "可辨認的、可認出的", "ipa": "/ˈrekəɡnaɪzəbl/", "trans": "recognize (動詞)", "col": "easily recognizable", "ex": "His voice was easily recognizable."},
    "recognize": {"def": "認出、承認、識別、認可", "ipa": "/ˈrekəɡnaɪz/", "trans": "recognized, recognition", "col": "recognize a problem", "ex": "I didn't recognize him at first."},
    "recoil": {"def": "縮回、畏縮、報應、彈回", "ipa": "/rɪˈkɔɪl/", "trans": "recoiled", "col": "recoil in horror", "ex": "She recoiled from the sight of blood."},
    "recollect": {"def": "回憶、想起、使集聚", "ipa": "/ˌrekəˈlekt/", "trans": "recollected, recollection", "col": "recollect an event", "ex": "I can't recollect where I put it."},
    "recollection": {"def": "回憶、記憶、往事", "ipa": "/ˌrekəˈlekʃn/", "trans": "recollect (動詞)", "col": "to the best of my recollection", "ex": "I have no recollection of that."},
    "recommend": {"def": "推薦、建議", "ipa": "/ˌrekəˈmend/", "trans": "recommended, recommendation", "col": "highly recommend", "ex": "Can you recommend a good book?"},
    "recommendation": {"def": "推薦、建議、介紹信", "ipa": "/ˌrekəmenˈdeɪʃn/", "trans": "recommend (動詞)", "col": "letter of recommendation", "ex": "I followed your recommendation."},
    "recompense": {"def": "補償、報答、賠償、補償", "ipa": "/ˈrekəmpens/", "trans": "recompensed", "col": "without recompense", "ex": "There is no recompense for your loss."},
    "reconcile": {"def": "使和解、使一致、調停", "ipa": "/ˈrekənsaɪl/", "trans": "reconciled, reconciliation", "col": "reconcile differences", "ex": "They managed to reconcile their differences."},
    "reconciliation": {"def": "和解、一致、調和", "ipa": "/ˌrekənsɪliˈeɪʃn/", "trans": "reconcile (動詞)", "col": "national reconciliation", "ex": "The meeting led to a reconciliation."},
    "recondite": {"def": "深奧的、玄妙的、隱晦的", "ipa": "/ˈrekəndaɪt/", "trans": "無", "col": "recondite subject", "ex": "He has a recondite knowledge of history."},
    "reconnaissance": {"def": "偵察、勘察", "ipa": "/rɪˈkɒnɪsns/", "trans": "reconnoitre", "col": "reconnaissance flight", "ex": "The plane was sent on a reconnaissance mission."},
}

with open("batch_l1_p54.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART54, f, ensure_ascii=False, indent=2)
