import json

# Level 1 Part 65: (Simulate - Slanderous)
L1_PART65 = {
    "simulate": {"def": "模擬、模仿、假裝", "ipa": "/ˈsɪmjuleɪt/", "trans": "simulated, simulation", "col": "simulate flight", "ex": "The computer can simulate different weather conditions."},
    "simulation": {"def": "模擬、模仿、偽裝", "ipa": "/ˌsɪmjuˈleɪʃn/", "trans": "simulate (動詞)", "col": "computer simulation", "ex": "The pilots train using flight simulation."},
    "simultaneous": {"def": "同時發生的、同步的", "ipa": "/ˌsɪmlˈteɪniəs/", "trans": "simultaneously", "col": "simultaneous interpretation", "ex": "There were several simultaneous attacks."},
    "sin": {"def": "罪、過失、犯罪", "ipa": "/sɪn/", "trans": "sinful, sinner", "col": "commit a sin, mortal sin", "ex": "It's a sin to steal."},
    "since": {"def": "自從、因為", "ipa": "/sɪns/", "trans": "無", "col": "ever since, long since", "ex": "I haven't seen him since last year."},
    "sincere": {"def": "誠摯的、真誠的、純潔的", "ipa": "/sɪnˈsɪə/", "trans": "sincerely, sincerity", "col": "sincere apology", "ex": "Please accept my sincere thanks."},
    "s sincerelyly": {"def": "真誠地、誠懇地", "ipa": "/sɪnˈsɪəli/", "trans": "sincere (形容詞)", "col": "Yours sincerely", "ex": "I sincerely hope you recover soon."},
    "sincerity": {"def": "真誠、誠摯、純真", "ipa": "/sɪnˈserəti/", "trans": "sincere (形容詞)", "col": "in all sincerity", "ex": "I don't doubt his sincerity."},
    "sinful": {"def": "有罪的、道德敗壞的", "ipa": "/ˈsɪnfl/", "trans": "sin (名詞)", "col": "sinful thoughts", "ex": "They lead a sinful life."},
    "sing": {"def": "唱、唱歌、鳴", "ipa": "/sɪŋ/", "trans": "sang, sung, singer, singing", "col": "sing a song", "ex": "She loves to sing."},
    "singer": {"def": "歌手、歌唱家", "ipa": "/ˈsɪŋə/", "trans": "sing (動詞)", "col": "pop singer, opera singer", "ex": "He is a famous singer."},
    "singing": {"def": "歌唱、歌聲", "ipa": "/ˈsɪŋɪŋ/", "trans": "sing (動詞)", "col": "singing lesson", "ex": "I could hear the birds singing."},
    "single": {"def": "單一的、單身的、單程的", "ipa": "/ˈsɪŋɡl/", "trans": "singly, singular", "col": "single parent, single ticket", "ex": "She is still single."},
    "singular": {"def": "單數的、非凡的、奇特的", "ipa": "/ˈsɪŋɡjələ/", "trans": "singularity", "col": "singular success", "ex": "The word is in the singular."},
    "sinister": {"def": "陰險的、邪惡的、不吉利的", "ipa": "/ˈsɪnɪstə/", "trans": "sinisterly", "col": "sinister smile", "ex": "There was a sinister look in his eyes."},
    "sink": {"def": "下沉、沉沒、變低", "ipa": "/sɪŋk/", "trans": "sank, sunk, sunken", "col": "sink or swim, kitchen sink", "ex": "The titanic began to sink."},
    "sinner": {"def": "罪人、犯罪者", "ipa": "/ˈsɪnə/", "trans": "sin (名詞)", "col": "repentant sinner", "ex": "He asked God to forgive him, a sinner."},
    "sip": {"def": "啜飲、一小口", "ipa": "/sɪp/", "trans": "sipped", "col": "sip coffee", "ex": "She took a sip of her tea."},
    "siren": {"def": "警報器、汽笛、妖婦", "ipa": "/ˈsaɪərən/", "trans": "sirens", "col": "air raid siren", "ex": "I heard the siren of a police car."},
    "sister": {"def": "姊妹、護士、修女", "ipa": "/ˈsɪstə/", "trans": "sisterhood", "col": "older sister, nursing sister", "ex": "My sister is a teacher."},
    "sit": {"def": "坐、位於、開會", "ipa": "/sɪt/", "trans": "sat, sitting, sitter", "col": "sit down, sit for an exam", "ex": "Please sit down."},
    "site": {"def": "地點、場所、網站", "ipa": "/saɪt/", "trans": "sites", "col": "construction site, website", "ex": "This is the site of the new hospital."},
    "sitting": {"def": "坐著、會議、一屆", "ipa": "/ˈsɪtɪŋ/", "trans": "sit (動詞)", "col": "sitting room", "ex": "He spent most of the day sitting."},
    "situation": {"def": "情況、處境、職位", "ipa": "/ˌsɪtʃuˈeɪʃn/", "trans": "situated", "col": "difficult situation, current situation", "ex": "I'm in a difficult situation."},
    "six": {"def": "六、六個", "ipa": "/sɪks/", "trans": "sixth, sixteen, sixty", "col": "six feet tall", "ex": "I have six books."},
    "sixteen": {"def": "十六", "ipa": "/ˌsɪksˈtiːn/", "trans": "sixteenth", "col": "sixteen years old", "ex": "She is sixteen years old."},
    "sixth": {"def": "第六、六分之一", "ipa": "/sɪksθ/", "trans": "six (名詞)", "col": "sixth floor", "ex": "His office is on the sixth floor."},
    "sixty": {"def": "六十", "ipa": "/ˈsɪksti/", "trans": "sixtieth", "col": "sixty minutes", "ex": "He is sixty years old now."},
    "size": {"def": "大小、尺寸、量", "ipa": "/saɪz/", "trans": "sizable", "col": "life size, medium size", "ex": "What size shoes do you wear?"},
    "skate": {"def": "溜冰鞋、冰鞋、溜冰", "ipa": "/skeɪt/", "trans": "skating, skateboard", "col": "ice skate, roller skate", "ex": "I like to skate in winter."},
    "skating": {"def": "溜冰、滑冰", "ipa": "/ˈskeɪtɪŋ/", "trans": "skate (動詞)", "col": "ice skating, figure skating", "ex": "They are going skating."},
    "skeleton": {"def": "骨骼、架構、綱要", "ipa": "/ˈskelɪtn/", "trans": "skeletal", "col": "skeleton crew, skeleton in the closet", "ex": "The human skeleton consists of 206 bones."},
    "sketch": {"def": "素描、草圖、梗概", "ipa": "/sketʃ/", "trans": "sketchbook, sketchy", "col": "charcoal sketch, character sketch", "ex": "He made a quick sketch of the mountain."},
    "ski": {"def": "滑雪板、滑雪", "ipa": "/skiː/", "trans": "skiing, skier", "col": "water ski, go skiing", "ex": "We are going to ski in the Alps."},
    "skiing": {"def": "滑雪", "ipa": "/ˈskiːɪŋ/", "trans": "ski (動詞)", "col": "downhill skiing", "ex": "Skiing is a popular winter sport."},
    "skill": {"def": "技能、技巧、技術", "ipa": "/skɪl/", "trans": "skilled, skilful", "col": "communication skill, management skill", "ex": "It takes skill to do this job."},
    "skilled": {"def": "熟練的、有技能的", "ipa": "/skɪld/", "trans": "skill (名詞)", "col": "skilled worker", "ex": "She is a skilled surgeon."},
    "skim": {"def": "略讀、撇去、掠過", "ipa": "/skɪm/", "trans": "skimmed", "col": "skim the surface, skim milk", "ex": "I skimmed through the report."},
    "skin": {"def": "皮膚、外皮、毛皮", "ipa": "/skɪn/", "trans": "skinny, skinless", "col": "dry skin, skin deep", "ex": "She has very fair skin."},
    "skinny": {"def": "極瘦的、皮包骨的", "ipa": "/ˈskɪni/", "trans": "skin (名詞)", "col": "skinny jeans", "ex": "He is very tall and skinny."},
    "skip": {"def": "跳過、略過、蹦跳", "ipa": "/skɪp/", "trans": "skipped", "col": "skip breakfast, jump and skip", "ex": "Let's skip the first chapter."},
    "skirt": {"def": "裙子、邊緣、繞過", "ipa": "/skɜːt/", "trans": "skirts", "col": "mini skirt, pleated skirt", "ex": "She wore a blue skirt."},
    "skull": {"def": "頭蓋骨、頭骨", "ipa": "/skʌl/", "trans": "skulls", "col": "fractured skull", "ex": "The archeologist found a human skull."},
    "sky": {"def": "天空、天、氣候", "ipa": "/skaɪ/", "trans": "skies, skyscraper", "col": "blue sky, night sky", "ex": "The sky is clear today."},
    "skyscraper": {"def": "摩天大樓", "ipa": "/ˈskaɪskreɪpə/", "trans": "skyscrapers", "col": "giant skyscraper", "ex": "New York is a city of skyscrapers."},
    "slam": {"def": "砰地關上、猛烈抨擊", "ipa": "/slæm/", "trans": "slammed", "col": "slam the door, slam on the brakes", "ex": "Don't slam the door."},
    "slander": {"def": "誹謗、中傷", "ipa": "/ˈslɑːndə/", "trans": "slanderous", "col": "sue for slander", "ex": "He was accused of slander."},
}

with open("batch_l1_p65.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART65, f, ensure_ascii=False, indent=2)
