import json

# Level 1 Part 31: (Mile - Musician)
L1_PART31 = {
    "mile": {"def": "英哩、很大的距離", "ipa": "/maɪl/", "trans": "miles, mileage", "col": "mileage rate", "ex": "The station is two miles away."},
    "military": {"def": "軍事的、軍隊、軍方", "ipa": "/ˈmɪlətri/", "trans": "militarily", "col": "military service, military base", "ex": "He spent two years in the military."},
    "milk": {"def": "牛奶、擠乳", "ipa": "/mɪlk/", "trans": "milky", "col": "milk shake, skimmed milk", "ex": "I like milk in my tea."},
    "mill": {"def": "磨坊、工廠、磨粉", "ipa": "/mɪl/", "trans": "mills, miller", "col": "steel mill, windmill", "ex": "Grain is ground into flour at a mill."},
    "miller": {"def": "磨坊主", "ipa": "/ˈmɪlə/", "trans": "millers", "col": "village miller", "ex": "The miller works in the windmill."},
    "milligram": {"def": "毫克", "ipa": "/ˈ常规 /", "trans": "milligrams", "col": "ten milligrams", "ex": "The dose is 50 milligrams."},
    "milliliter/millilitre": {"def": "毫升", "ipa": "/ˈmɪlɪliːtə/", "trans": "milliliters", "col": "500 milliliters", "ex": "I bought a 500 milliliter bottle of water."},
    "millimeter/millimetre": {"def": "公釐、毫米", "ipa": "/ˈmɪlɪmiːtə/", "trans": "millimeters", "col": "ten millimeters", "ex": "There are 1,000 millimeters in a meter."},
    "million": {"def": "百萬", "ipa": "/ˈmɪljən/", "trans": "millionaire", "col": "one million people", "ex": "He won a million dollars."},
    "millionaire": {"def": "百萬富翁", "ipa": "/ˌmɪljəˈneə/", "trans": "millionaires", "col": "multi-millionaire", "ex": "He became a millionaire overnight."},
    "mimic": {"def": "模仿、戲弄、模仿者", "ipa": "/ˈmɪmɪk/", "trans": "mimicked", "col": "mimic someone", "ex": "She can mimic her father perfectly."},
    "mince": {"def": "絞碎、切碎、矯揉造作的步態", "ipa": "/mɪns/", "trans": "minced", "col": "mince meat", "ex": "Mince the onions finely."},
    "mind": {"def": "頭腦、理智、介意、注意", "ipa": "/maɪnd/", "trans": "minded", "col": "keep in mind, never mind", "ex": "Do you mind if I open the window?"},
    "mindful": {"def": "留心的、注意的", "ipa": "/ˈmaɪndfl/", "trans": "mindfully", "col": "be mindful of", "ex": "We must be mindful of our environment."},
    "mine": {"def": "我的(東西)、礦山、地雷、挖掘", "ipa": "/maɪn/", "trans": "miner, mineral", "col": "gold mine, coal mine", "ex": "This book is mine."},
    "miner": {"def": "礦工", "ipa": "/ˈmaɪnə/", "trans": "miners", "col": "coal miner", "ex": "My grandfather was a coal miner."},
    "mineral": {"def": "礦物(的)", "ipa": "/ˈmɪnərəl/", "trans": "minerals", "col": "mineral water", "ex": "Plants absorb minerals from the soil."},
    "miniature": {"def": "微型的、小型的、微型畫", "ipa": "/ˈmɪnətʃə/", "trans": "miniatures", "col": "in miniature", "ex": "He has a collection of miniature cars."},
    "minimal": {"def": "最小的、最少的", "ipa": "/ˈmɪnɪməl/", "trans": "minimally", "col": "minimal damage", "ex": "The damage to the car was minimal."},
    "minimize/minimise": {"def": "使縮到最小、蔑視", "ipa": "/ˈmɪnɪmaɪz/", "trans": "minimized", "col": "minimize risk", "ex": "We should try to minimize the risk of accident."},
    "minimum": {"def": "最低限度、最小的", "ipa": "/ˈmɪnɪməm/", "trans": "minima, maximum (最高的)", "col": "minimum wage, minimum age", "ex": "The minimum wage has been increased."},
    "minister": {"def": "部長、大臣、牧師、服務", "ipa": "/ˈmɪnɪstə/", "trans": "ministers, ministry", "col": "prime minister, foreign minister", "ex": "The Prime Minister is going to give a speech."},
    "ministry": {"def": "教育部、內閣、牧師職務", "ipa": "/ˈmɪnɪstri/", "trans": "ministries", "col": "ministry of education", "ex": "He works in the Ministry of Finance."},
    "minor": {"def": "次要的、未成年人、主修(副)、二、小調", "ipa": "/ˈmaɪnə/", "trans": "minors, minority", "col": "minor injuries, minor character", "ex": "It was only a minor accident."},
    "minority": {"def": "少數、少數民族、未成年", "ipa": "/maɪˈnɒrəti/", "trans": "minorities, majority (多數)", "col": "ethnic minority", "ex": "They are in a minority."},
    "mint": {"def": "薄荷、造幣廠、巨額、鑄造", "ipa": "/mɪnt/", "trans": "minted", "col": "in mint condition, peppermint", "ex": "I like mint tea."},
    "minus": {"def": "負的、減、負號、缺點", "ipa": "/ˈmaɪnəs/", "trans": "plus (加的)", "col": "minus degree", "ex": "Five minus two is three."},
    "minute": {"def": "分鐘、片刻、筆錄、極小的(maɪˈnjuːt)", "ipa": "/ˈmɪnɪt/", "trans": "minutes", "col": "wait a minute", "ex": "Wait a minute, please."},
    "miracle": {"def": "奇蹟", "ipa": "/ˈmɪrəkl/", "trans": "miracles, miraculous", "col": "economic miracle", "ex": "It's a miracle that he survived."},
    "miraculous": {"def": "奇蹟般的、不可思議的", "ipa": "/mɪˈrækjələs/", "trans": "miraculously", "col": "miraculous escape", "ex": "He made a miraculous recovery."},
    "mirror": {"def": "鏡子、反映", "ipa": "/ˈmɪrə/", "trans": "mirrors, mirrored", "col": "rear-view mirror", "ex": "She looked at herself in the mirror."},
    "mirth": {"def": "歡樂、歡笑", "ipa": "/mɜːθ/", "trans": "mirthful", "col": "full of mirth", "ex": "The room was full of mirth."},
    "mischief": {"def": "頑皮、惡作劇、損害", "ipa": "/ˈmɪstʃɪf/", "trans": "mischievous (頑皮的)", "col": "get into mischief", "ex": "Those boys are always getting into mischief."},
    "miserable": {"def": "痛苦的、不幸的、卑劣的", "ipa": "/ˈmɪzrəbl/", "trans": "miserably", "col": "feel miserable", "ex": "The weather was miserable."},
    "misery": {"def": "痛苦、不幸、窮困", "ipa": "/ˈmɪzəri/", "trans": "miseries", "col": "life of misery", "ex": "He lived a life of misery."},
    "misfortune": {"def": "不幸、厄運、災禍", "ipa": "/ˌmɪsˈfɔːtʃuːn/", "trans": "misfortunes", "col": "bear misfortune", "ex": "He bore his misfortune with great courage."},
    "mislead": {"def": "誤導、使誤信", "ipa": "/ˌmɪsˈliːd/", "trans": "misled, misleading", "col": "mislead the public", "ex": "He tried to mislead the police."},
    "misleading": {"def": "誤導性的、欺騙的", "ipa": "/ˌmɪsˈliːdɪŋ/", "trans": "mislead (動詞)", "col": "misleading advertisement", "ex": "The advertisement was misleading."},
    "miss": {"def": "錯過、想念、失手、小姐", "ipa": "/mɪs/", "trans": "missed, missing", "col": "miss the bus, miss someone", "ex": "I missed the last bus."},
    "missile": {"def": "飛彈、投射箭", "ipa": "/ˈmɪsaɪl/", "trans": "missiles", "col": "nuclear missile, guiding missile", "ex": "The missile was launched yesterday."},
    "mission": {"def": "任務、使命、代表團", "ipa": "/ˈmɪʃn/", "trans": "missions, missionary", "col": "space mission, diplomatic mission", "ex": "His mission was high risk."},
    "missionary": {"def": "傳教士、傳教的", "ipa": "/ˈmɪʃənri/", "trans": "missionaries", "col": "foreign missionary", "ex": "He worked as a missionary in Africa."},
    "mist": {"def": "薄霧、水汽、朦朧", "ipa": "/mɪst/", "trans": "mists, misty", "col": "misty mountain", "ex": "The hills were covered in mist."},
    "mistake": {"def": "錯誤、誤解", "ipa": "/mɪˈsteɪk/", "trans": "mistook, mistaken", "col": "by mistake, make a mistake", "ex": "I made a big mistake."},
    "mistaken": {"def": "錯誤的、誤解的", "ipa": "/mɪˈsteɪkən/", "trans": "mistake (名詞/動詞)", "col": "be mistaken about", "ex": "I'm afraid you are mistaken."},
    "mister": {"def": "先生", "ipa": "/ˈmɪstə/", "trans": "Mr.", "col": "mister chairman", "ex": "Listen to me, mister!"},
    "mistress": {"def": "女主、情婦、教師", "ipa": "/ˈmɪstrəs/", "trans": "mistresses", "col": "head mistress", "ex": "She is the mistress of the house."},
    "misty": {"def": "有霧的、朦朧的", "ipa": "/ˈmɪsti/", "trans": "mist (名詞)", "col": "misty morning", "ex": "It was a cold, misty morning."},
    "misunderstand": {"def": "誤解", "ipa": "/ˌmɪsʌndəˈstænd/", "trans": "misunderstood, misunderstanding", "col": "misunderstand someone", "ex": "I'm sorry, I misunderstood you."},
    "misunderstanding": {"def": "誤解、誤會、不和", "ipa": "/ˌmɪsʌndəˈstændɪŋ/", "trans": "misunderstandings", "col": "clear up a misunderstanding", "ex": "There has been a slight misunderstanding."},
    "mix": {"def": "混合、攪拌", "ipa": "/mɪks/", "trans": "mixed, mixture", "col": "mix up", "ex": "You should mix the paint before using it."},
    "mixture": {"def": "混合物、混合", "ipa": "/ˈmɪkstʃə/", "trans": "mixtures", "col": "strange mixture", "ex": "The air is a mixture of gases."},
    "moan": {"def": "呻吟、鳴咽、抱怨", "ipa": "/məʊn/", "trans": "moaned", "col": "moan about", "ex": "He moaned with pain."},
    "mob": {"def": "暴民、人群、圍攻", "ipa": "/mɒb/", "trans": "mobbed", "col": "angry mob", "ex": "The angry mob attacked the police."},
    "mobile": {"def": "移動式的、易變的、手機", "ipa": "/ˈməʊbaɪl/", "trans": "mobility", "col": "mobile phone", "ex": "Technology makes us more mobile."},
    "mobility": {"def": "流動性、機動性、機動力", "ipa": "/məʊˈbɪləti/", "trans": "mobilize", "col": "social mobility", "ex": "The car increased people's mobility."},
    "mock": {"def": "嘲笑、模仿、假裝的", "ipa": "/mɒk/", "trans": "mocked", "col": "mock exam, mock at", "ex": "Don't mock me!"},
    "mode": {"def": "模式、方式、風格、眾數", "ipa": "/məʊd/", "trans": "modes", "col": "silent mode, transport mode", "ex": "Please turn your phone to silent mode."},
    "model": {"def": "模型、模特兒、模範、模造", "ipa": "/ˈmɒdl/", "trans": "models, modeled", "col": "fashion model, model car", "ex": "She is a top fashion model."},
    "moderate": {"def": "適度的、穩健的、節制、主持", "ipa": "/ˈmɒdərət/", "trans": "moderately, moderation", "col": "moderate exercise, moderate price", "ex": "I take a moderate amount of exercise."},
    "moderately": {"def": "適度地、溫和地", "ipa": "/ˈmɒdərətli/", "trans": "moderate (形容詞)", "col": "be moderately successful", "ex": "He is a moderately successful writer."},
    "modern": {"def": "現代的、時髦的", "ipa": "/ˈmɒdn/", "trans": "modernity, modernize", "col": "modern art, modern history", "ex": "We live in a modern society."},
    "modernize/modernise": {"def": "現代化", "ipa": "/ˈmɒdənaɪz/", "trans": "modernized, modernization", "col": "modernize the factory", "ex": "The airport needs to be modernized."},
    "modest": {"def": "謙虛的、適度的、端莊的", "ipa": "/ˈ常规 /", "trans": "modestly, modesty", "col": "modest salary, be modest about", "ex": "He is very modest about his success."},
    "modesty": {"def": "謙虛、莊重、適度", "ipa": "/ˈmɒdəsti/", "trans": "modest (形容詞)", "col": "natural modesty", "ex": "He accepted the prize with great modesty."},
    "modification": {"def": "修改、更動、緩和", "ipa": "/ˌmɒdɪfɪˈkeɪʃn/", "trans": "modifications, modify (動詞)", "col": "minor modification", "ex": "They made some modifications to the plan."},
    "modify": {"def": "修改、修正、緩和", "ipa": "/ˈmɒdɪfaɪ/", "trans": "modified", "col": "modify a law", "ex": "We need to modify the design."},
    "moist": {"def": "潮濕的、多淚的", "ipa": "/mɔɪst/", "trans": "moisten, moisture", "col": "moist eyes", "ex": "The soil is moist and fertile."},
    "moisture": {"def": "水分、潮氣、濕氣", "ipa": "/ˈmɔɪstʃə/", "trans": "無 (不可數)", "col": "skin moisture", "ex": "These plants need a lot of moisture."},
    "molecule": {"def": "分子", "ipa": "/ˈmɒlɪkjuːl/", "trans": "molecules, molecular", "col": "water molecule", "ex": "A molecule is the smallest unit of a substance."},
    "monarch": {"def": "君主、國王", "ipa": "/ˈmɒnək/", "trans": "monarchs, monarchy", "col": "ruling monarch", "ex": "Queen Elizabeth II was a long-reigning monarch."},
    "monarchy": {"def": "君主制、君主國", "ipa": "/ˈmɒnəki/", "trans": "monarchies", "col": "constitutional monarchy", "ex": "Britain is a constitutional monarchy."},
    "monastery": {"def": "修道院、寺院", "ipa": "/ˈmɒnəstri/", "trans": "monasteries", "col": "Buddhist monastery", "ex": "He spent ten years in a monastery."},
    "Monday": {"def": "星期一", "ipa": "/ˈmʌndeɪ/", "trans": "無", "col": "on Monday", "ex": "I'll see you on Monday."},
    "monetary": {"def": "貨幣的、金融的", "ipa": "/ˈmʌnɪtri/", "trans": "無", "col": "monetary policy, monetary system", "ex": "The country is facing monetary problems."},
    "money": {"def": "錢、貨幣", "ipa": "/ˈmʌni/", "trans": "monetary", "col": "pocket money, make money", "ex": "He has a lot of money."},
    "monitor": {"def": "顯示器、監聽器、班長、監視", "ipa": "/ˈmɒnɪtə/", "trans": "monitored", "col": "computer monitor, monitor performance", "ex": "The police are monitoring his calls."},
    "monk": {"def": "修道士、僧侶", "ipa": "/mʌŋk/", "trans": "monks", "col": "monk's habit", "ex": "The monk is praying in the temple."},
    "monkey": {"def": "猴子、調皮鬼", "ipa": "/ˈmʌŋki/", "trans": "monkeys", "col": "make a monkey of", "ex": "The monkey is eating a banana."},
    "monopoly": {"def": "壟斷、獨佔、大富翁遊戲", "ipa": "/məˈnɒpəli/", "trans": "monopolies, monopolize", "col": "state monopoly", "ex": "The company has a monopoly on the local market."},
    "monotonous": {"def": "單調的、無聊的", "ipa": "/məˈnɒtənəs/", "trans": "monotony", "col": "monotonous voice", "ex": "His voice was thin and monotonous."},
    "monotony": {"def": "單調、無味、一成不變", "ipa": "/məˈnɒtəni/", "trans": "monotonous (形容詞)", "col": "break the monotony", "ex": "She hates the monotony of her daily job."},
    "monster": {"def": "怪物、巨獸、惡人", "ipa": "/ˈmɒnstə/", "trans": "monsters, monstrous", "col": "sea monster", "ex": "I don't believe in monsters."},
    "monstrous": {"def": "可怕的、畸形的、巨大的", "ipa": "/ˈmɒnstrəs/", "trans": "monstrously", "col": "monstrous crime", "ex": "It was a monstrous lie."},
    "month": {"def": "月", "ipa": "/mʌnθ/", "trans": "months, monthly", "col": "once a month", "ex": "He gets paid once a month."},
    "monthly": {"def": "每月的、每月一次地、月刊", "ipa": "/ˈmʌnθli/", "trans": "month (名詞)", "col": "monthly report", "ex": "It's a monthly magazine."},
    "monument": {"def": "紀念碑、歷史遺跡、不朽之物", "ipa": "/ˈmɒnjumənt/", "trans": "monuments, monumental", "col": "national monument", "ex": "They built a monument to the war heroes."},
    "mood": {"def": "情緒、心境、語氣", "ipa": "/muːd/", "trans": "moods, moody", "col": "in a good mood", "ex": "He is in a bad mood today."},
    "moody": {"def": "喜怒無常的、憂鬱的", "ipa": "/ˈmuːdi/", "trans": "mood (名詞)", "col": "moody teenager", "ex": "She has been very moody lately."},
    "moon": {"def": "月亮、衛星", "ipa": "/muːn/", "trans": "moonlight", "col": "full moon, once in a blue moon", "ex": "The moon is shining brightly."},
    "moonlight": {"def": "月光", "ipa": "/ˈmuːnlaɪt/", "trans": "moonlit", "col": "by moonlight", "ex": "We walked home by moonlight."},
    "mop": {"def": "拖把、洗碗刷、拖地、擦", "ipa": "/mɒp/", "trans": "mopped", "col": "mop up", "ex": "He is mopping the floor."},
    "moral": {"def": "道德的、寓意、品行", "ipa": "/ˈmɒrəl/", "trans": "morally, morality", "col": "moral values, moral support", "ex": "It's a moral question."},
    "morality": {"def": "道德、倫理、品行", "ipa": "/məˈræləti/", "trans": "moralities", "col": "public morality", "ex": "Standards of morality vary from culture to culture."},
    "morally": {"def": "/ˈmɒrəli/", "trans": "moral (形容詞)", "col": "morally wrong", "ex": "He feels morally obligated to help."},
    "more": {"def": "更多(的/地)", "ipa": "/mɔː/", "trans": "many/much", "col": "more and more, what's more", "ex": "I want some more juice."},
    "moreover": {"def": "而且、此外", "ipa": "/mɔːrˈəʊvə/", "trans": "無", "col": "moreover, furthermore", "ex": "The rent is high; moreover, the house is in bad condition."},
    "morning": {"def": "早晨", "ipa": "/ˈmɔːnɪŋ/", "trans": "mornings", "col": "good morning, early morning", "ex": "I get up early in the morning."},
    "mortal": {"def": "凡人的、致命的、終有一死的", "ipa": "/ˈmɔːtl/", "trans": "mortality, immortally", "col": "mortal enemy", "ex": "All men are mortal."},
    "mortality": {"def": "死亡數、必死性", "ipa": "/mɔːˈtæləti/", "trans": "mortal (形容詞)", "col": "infant mortality", "ex": "The mortality rate is very high here."},
    "mosquito": {"def": "蚊子", "ipa": "/məˈskiːtəʊ/", "trans": "mosquitoes", "col": "mosquito bite", "ex": "I was bitten by a mosquito."},
    "moss": {"def": "苔蘚", "ipa": "/mɒs/", "trans": "mossy", "col": "green moss", "ex": "The rock is covered with moss."},
    "most": {"def": "最多(的/地)、最(最高級)", "ipa": "/məʊst/", "trans": "mostly", "col": "most of all, for the most part", "ex": "He is the most famous writer in the country."},
    "mostly": {"def": "主要地、大部分", "ipa": "/ˈməʊstli/", "trans": "most (形容詞)", "col": "mostly true", "ex": "They are mostly students."},
    "motel": {"def": "汽車旅館", "ipa": "/məʊˈtel/", "trans": "motels", "col": "roadside motel", "ex": "They stayed in a motel."},
    "moth": {"def": "蛾、蠹蟲", "ipa": "/mɒθ/", "trans": "moths", "col": "clothes moth", "ex": "A moth is flying around the light."},
    "mother": {"def": "母親、發源、扶養", "ipa": "/ˈmʌðə/", "trans": "mothers, motherhood", "col": "mother tongue, mother nature", "ex": "I love my mother."},
    "motherhood": {"def": "母性、母親身份", "ipa": "/ˈmʌðəhʊd/", "trans": "mother (名詞)", "col": "joys of motherhood", "ex": "She is enjoying motherhood."},
    "motion": {"def": "運動、提議、手勢、動議", "ipa": "/ˈməʊʃn/", "trans": "motions, motionless", "col": "slow motion, perpetual motion", "ex": "The ship is in motion."},
    "motionless": {"def": "不動的、靜止的", "ipa": "/ˈməʊʃnləs/", "trans": "motion (名詞)", "col": "stand motionless", "ex": "He stood motionless for a few minutes."},
    "motivate": {"def": "激勵、促動", "ipa": "/ˈməʊtɪveɪt/", "trans": "motivated, motivation", "col": "highly motivated", "ex": "The teacher knows how to motivate students."},
    "motivation": {"def": "動力、動機、激勵", "ipa": "/ˌməʊtɪˈleɪʃn/", "trans": "motivations", "col": "lack of motivation", "ex": "What is your motivation for learning English?"},
    "motive": {"def": "動機、目的、主旨、發動的", "ipa": "/ˈməʊtɪv/", "trans": "motives", "col": "ulterior motive, political motive", "ex": "The police are looking for a motive."},
    "motor": {"def": "馬達、發動機、汽車", "ipa": "/ˈməʊtə/", "trans": "motors, motorist", "col": "motor home", "ex": "The boat has a motor."},
    "motorcycle/motorbike": {"def": "摩托車", "ipa": "/ˈməʊtəsaɪkl/", "trans": "motorcycles", "col": "ride a motorcycle", "ex": "He goes to work by motorcycle."},
    "motorist": {"def": "開汽車的人、駕駛人", "ipa": "/ˈməʊtərɪst/", "trans": "motorists", "col": "stranded motorist", "ex": "The motorist was fined for speeding."},
    "motto": {"def": "座右銘、格言", "ipa": "/ˈmɒtəʊ/", "trans": "mottoes", "col": "family motto", "ex": "Honesty is the best policy' is my motto."},
    "mountain": {"def": "山", "ipa": "/ˈmaʊntən/", "trans": "mountains, mountainous", "col": "mountain range", "ex": "Mount Everest is the highest mountain in the world."},
    "mountainous": {"def": "多山的、巨大的", "ipa": "/ˈmaʊntənəs/", "trans": "mountain (名詞)", "col": "mountainous region", "ex": "Taiwan is a mountainous island."},
    "mount": {"def": "登上、騎上、發動、山峰(縮寫Mt.)", "ipa": "/maʊnt/", "trans": "mounted", "col": "mount a horse", "ex": "He mounted the platform to speak."},
    "mourn": {"def": "哀悼、憂傷", "ipa": "/mɔːn/", "trans": "mourned, mourning", "col": "mourn for", "ex": "Thousands of people mourned for the victims."},
    "mournful": {"def": "憂傷的、淒涼的", "ipa": "/ˈmɔːnfl/", "trans": "mournfully", "col": "mournful song", "ex": "He sang a mournful song."},
    "mouse": {"def": "老鼠、滑鼠", "ipa": "/maʊs/", "trans": "mice", "col": "computer mouse", "ex": "The cat is chasing a mouse."},
    "mouth": {"def": "嘴、開口", "ipa": "/maʊθ/", "trans": "mouths, mouthful", "col": "mouth-to-mouth", "ex": "Open your mouth."},
    "mouthful": {"def": "滿口、少量、噴一噴", "ipa": "/ˈmaʊθfʊl/", "trans": "mouth (名詞)", "col": "eat a mouthful", "ex": "She took a mouthful of soup."},
    "move": {"def": "移動、動、移動、手段", "ipa": "/muːv/", "trans": "moved, movement, movie", "col": "move on, make a move", "ex": "Please move the chair."},
    "movement": {"def": "運動、移動、樂章", "ipa": "/ˈmuːvmənt/", "trans": "movements", "col": "social movement, eye movement", "ex": "Wait for his next movement."},
    "movie": {"def": "電影", "ipa": "/ˈmuːvi/", "trans": "movies", "col": "watch a movie, go to the movies", "ex": "I like to watch movies."},
    "mow": {"def": "割草、收割", "ipa": "/məʊ/", "trans": "mowed, mown, mower", "col": "mow the grass", "ex": "He is mowing the lawn."},
    "mower": {"def": "割草機、收割機", "ipa": "/ˈməʊə/", "trans": "mowers", "col": "lawn mower", "ex": "The lawn mower is broken."},
    "Mr.": {"def": "先生", "ipa": "/ˈmɪstə/", "trans": "Messrs", "col": "Mr. Brown", "ex": "Mr. Smith is our teacher."},
    "Mrs.": {"def": "夫人、太太", "ipa": "/ˈmɪsɪz/", "trans": "無", "col": "Mrs. White", "ex": "Mrs. Lee is a very kind woman."},
    "Ms.": {"def": "女士(不限婚否)", "ipa": "/mɪz/", "trans": "無", "col": "Ms. Wang", "ex": "Ms. Green is the principal."},
    "much": {"def": "許多的、很大地", "ipa": "/mʌtʃ/", "trans": "more, most", "col": "much more, thank you very much", "ex": "How much does it cost?"},
    "mud": {"def": "泥巴、惡言、誹謗", "ipa": "/mʌd/", "trans": "muddy", "col": "stuck in the mud", "ex": "The road was full of mud."},
    "muddy": {"def": "泥濘的、混濁的、使沾泥", "ipa": "/ˈmʌdi/", "trans": "muddied", "col": "muddy boots", "ex": "Take off your muddy boots."},
    "mug": {"def": "大杯、笨蛋、搶劫", "ipa": "/mʌɡ/", "trans": "mugged, mugger", "col": "beer mug", "ex": "He is drinking beer from a mug."},
    "mule": {"def": "騾子、固執的人", "ipa": "/mjuːl/", "trans": "mules", "col": "stubborn as a mule", "ex": "He is as stubborn as a mule."},
    "multiple": {"def": "多樣的、倍數的、倍數", "ipa": "/ˈmʌltɪpl/", "trans": "multiples", "col": "multiple choice", "ex": "The victim had multiple injuries."},
    "multiply": {"def": "乘、增加、繁殖", "ipa": "/ˈmʌltɪplaɪ/", "trans": "multiplied, multiplication", "col": "multiply by", "ex": "If you multiply five by four, you get twenty."},
    "multitude": {"def": "群眾、多數", "ipa": "/ˈmʌltɪtjuːd/", "trans": "multitudes", "col": "multitude of sins", "ex": "He was surrounded by a multitude of people."},
    "mumble": {"def": "含糊地說、喃喃而言", "ipa": "/ˈmʌmbl/", "trans": "mumbled", "col": "mumble to oneself", "ex": "Don't mumble; speak clearly."},
    "mummy": {"def": "木乃伊、媽咪(英式)", "ipa": "/ˈmʌmi/", "trans": "mummies", "col": "Egyptian mummy", "ex": "There are mummies in the museum."},
    "municipal": {"def": "市政的、地方自治的", "ipa": "/mjuːˈnɪsɪpl/", "trans": "municipality", "col": "municipal government", "ex": "The municipal council will meet tomorrow."},
    "muscle": {"def": "肌肉、力量", "ipa": "/ˈmʌsl/", "trans": "muscles, muscular", "col": "build muscle", "ex": "He has strong muscles."},
    "muscular": {"def": "肌肉發達的、強而有力的", "ipa": "/ˈmʌskjələ/", "trans": "muscle (名詞)", "col": "muscular system", "ex": "He has a very muscular body."},
    "museum": {"def": "博物館", "ipa": "/mjuˈziːəm/", "trans": "museums", "col": "art museum, national museum", "ex": "The museum is free to the public."},
    "mushroom": {"def": "蘑菇、菌菇狀物、迅速發展", "ipa": "/ˈmʌʃrʊm/", "trans": "mushrooms", "col": "wild mushroom", "ex": "I like mushroom soup."},
    "music": {"def": "音樂", "ipa": "/ˈmjuːzɪk/", "trans": "musical, musician", "col": "classical music, pop music", "ex": "I like listening to music."},
    "musical": {"def": "音樂的、悅耳的、音樂劇", "ipa": "/ˈmjuːzɪkl/", "trans": "musically", "col": "musical instrument", "ex": "He can play several musical instruments."},
    "musician": {"def": "音樂家、演奏者", "ipa": "/mjuˈzɪʃn/", "trans": "musicians", "col": "famous musician", "ex": "His father is a famous musician."},
}

with open("batch_l1_p31.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART31, f, ensure_ascii=False, indent=2)
