import json

# Level 1 Part 40: (Permission - Photosphere)
L1_PART40 = {
    "permission": {"def": "准許、許可、許可證", "ipa": "/pəˈmɪʃn/", "trans": "permit (動詞)", "col": "written permission, ask for permission", "ex": "He entered without permission."},
    "permissive": {"def": "准許的、縱容的、寬容的", "ipa": "/pəˈmɪsɪv/", "trans": "permissiveness", "col": "permissive society", "ex": "His parents are very permissive."},
    "permit": {"def": "准許、容許、許可證", "ipa": "/pəˈmɪt/", "trans": "permitted, permission", "col": "work permit, driving permit", "ex": "The weather doesn't permit us to go out."},
    "perpendicular": {"def": "垂直的、成直角的、垂直線", "ipa": "/ˌpɜːpənˈdɪkjələ/", "trans": "perpendicularly", "col": "perpendicular line", "ex": "The wall is perpendicular to the floor."},
    "perpetual": {"def": "永久的、不斷的、長期的", "ipa": "/pəˈpetʃuəl/", "trans": "perpetually", "col": "perpetual motion", "ex": "He lives in perpetual fear."},
    "perpetually": {"def": "永久地、終身地", "ipa": "/pəˈpetʃuəli/", "trans": "perpetual (形容詞)", "col": "perpetually moving", "ex": "The snow on the mountain is perpetually there."},
    "perplex": {"def": "使困惑、使複雜", "ipa": "/pəˈpleks/", "trans": "perplexed, perplexity", "col": "perplex someone", "ex": "The problem perplexed the scientist."},
    "persecute": {"def": "迫害、虐待、騷擾", "ipa": "/ˈpɜːsɪkjuːt/", "trans": "persecuted, persecution", "col": "religious persecution", "ex": "They were persecuted for their beliefs."},
    "persecution": {"def": "迫害、虐待", "ipa": "/ˌpɜːsɪˈkjuːʃn/", "trans": "persecutions", "col": "political persecution", "ex": "She fled to escape persecution."},
    "perseverance": {"def": "毅力、堅持不懈", "ipa": "/ˌpɜːsɪˈvɪərəns/", "trans": "persevere (動詞)", "col": "through perseverance", "ex": "Success requires perseverance."},
    "persevere": {"def": "堅持不懈、不屈不撓", "ipa": "/ˌpɜːsɪˈvɪə/", "trans": "persevered", "col": "persevere in/with", "ex": "Despite the difficulties, she persevered with her study."},
    "persist": {"def": "堅持、持續、固執", "ipa": "/pəˈsɪst/", "trans": "persisted, persistent, persistence", "col": "persist in doing", "ex": "He persisted in his efforts."},
    "persistence": {"def": "堅持、持續、固執", "ipa": "/pəˈsɪstəns/", "trans": "persist (動詞)", "col": "persistence of memory", "ex": "His persistence finally paid off."},
    "persistent": {"def": "堅持的、持續的、固執的", "ipa": "/pəˈsɪstənt/", "trans": "persistently", "col": "persistent cough", "ex": "She has a persistent cough."},
    "person": {"def": "人、本人、角色", "ipa": "/ˈpɜːsn/", "trans": "persons, people, personal", "col": "in person, third person", "ex": "He is a very kind person."},
    "personal": {"def": "個人的、私人的、親自的", "ipa": "/ˈpɜːsənl/", "trans": "personally", "col": "personal computer, personal experience", "ex": "This is my personal opinion."},
    "personality": {"def": "個性、人格、名人", "ipa": "/ˌpɜːsəˈnæləti/", "trans": "personalities", "col": "strong personality, television personality", "ex": "She has a cheerful personality."},
    "personally": {"def": "親自地、就個人而言", "ipa": "/ˈpɜːsənəli/", "trans": "personal (形容詞)", "col": "know someone personally", "ex": "Personally, I think it's a good idea."},
    "personnel": {"def": "全體人員、員工、人事部門", "ipa": "/ˌpɜːsəˈnel/", "trans": "無 (恆複)", "col": "military personnel, personnel department", "ex": "All personnel must wear ID badges."},
    "perspective": {"def": "觀點、遠景、透視法", "ipa": "/pəˈspektɪv/", "trans": "perspectives", "col": "from a global perspective", "ex": "We must look at the problem from a different perspective."},
    "persuade": {"def": "說服、勸說、使相信", "ipa": "/pəˈsweɪd/", "trans": "persuaded, persuasion, persuasive", "col": "persuade someone to do", "ex": "He persuaded me to join the club."},
    "persuasion": {"def": "說服、信念、派別", "ipa": "/pəˈsweɪʒn/", "trans": "persuasive", "col": "gentle persuasion", "ex": "She has great powers of persuasion."},
    "persuasive": {"def": "有說服力的", "ipa": "/pəˈsweɪsɪv/", "trans": "persuasively", "col": "persuasive argument", "ex": "He is a persuasive speaker."},
    "pessimism": {"def": "悲觀(主義)", "ipa": "/ˈpesɪmɪzəm/", "trans": "optimism (樂觀)", "col": "deep pessimism", "ex": "There is a general feeling of pessimism about the economy."},
    "pessimist": {"def": "悲觀主義者", "ipa": "/ˈpesɪmɪst/", "trans": "pessimists, pessimistic", "col": "lifelong pessimist", "ex": "An optimist sees the donut; a pessimist sees the hole."},
    "pessimistic": {"def": "悲觀的", "ipa": "/ˌpesɪˈmɪstɪk/", "trans": "pessimistically", "col": "pessimistic view", "ex": "I'm not pessimistic about the future."},
    "pest": {"def": "害蟲、討厭的人事物", "ipa": "/pest/", "trans": "pests, pesticide", "col": "garden pest", "ex": "Rats are a common pest in the city."},
    "pesticide": {"def": "殺蟲劑", "ipa": "/ˈpestɪsaɪd/", "trans": "pesticides", "col": "use pesticide", "ex": "They used pesticides to kill the insects."},
    "pet": {"def": "寵物、受寵的人、寵愛的", "ipa": "/pet/", "trans": "pets, petted", "col": "teacher's pet, pet store", "ex": "Do you have any pets?"},
    "petal": {"def": "花瓣", "ipa": "/ˈpetl/", "trans": "petals", "col": "rose petal", "ex": "The rose petals are falling."},
    "petition": {"def": "請願(書)、訴狀、請願", "ipa": "/pəˈtɪʃn/", "trans": "petitioner", "col": "sign a petition", "ex": "They signed a petition to save the park."},
    "petrochemical": {"def": "石化製品、石化的", "ipa": "/ˌpetrəʊˈkemɪkl/", "trans": "petrochemicals", "col": "petrochemical industry", "ex": "The company dominates the petrochemical market."},
    "petrol": {"def": "汽油 (英式)", "ipa": "/ˈpetrəl/", "trans": "petroleum", "col": "fill up with petrol", "ex": "The car ran out of petrol."},
    "petroleum": {"def": "石油", "ipa": "/pəˈtrəʊliəm/", "trans": "petrol, gasoline", "col": "crude petroleum", "ex": "Petroleum is a major source of energy."},
    "petticoat": {"def": "女襯裙", "ipa": "/ˈpetɪkəʊt/", "trans": "petticoats", "col": "frilly petticoat", "ex": "She wore a white petticoat under her dress."},
    "petty": {"def": "細微的、微不足道的、氣量小的", "ipa": "/ˈpeti/", "trans": "pettier, pettiest", "col": "petty cash, petty crime", "ex": "It was just a petty argument."},
    "phantom": {"def": "幽靈、幻影、虛構的、幽靈般的", "ipa": "/ˈfæntəm/", "trans": "phantoms", "col": "phantom of the opera", "ex": "He saw a phantom in the dark."},
    "pharmaceutical": {"def": "製藥的、藥學的", "ipa": "/ˌfɑːməˈsuːtɪkl/", "trans": "pharmaceuticals", "col": "pharmaceutical company", "ex": "The pharmaceutical industry is booming."},
    "pharmacist": {"def": "藥劑師", "ipa": "/ˈfɑːməsɪst/", "trans": "pharmacists", "col": "qualified pharmacist", "ex": "Ask the pharmacist for advice."},
    "pharmacy": {"def": "藥局、藥劑學", "ipa": "/ˈfɑːməsi/", "trans": "pharmacies, pharmacist", "col": "local pharmacy", "ex": "I bought this medicine at the pharmacy."},
    "phase": {"def": "階段、相位、分階段進行", "ipa": "/feɪz/", "trans": "phases, phased", "col": "initial phase, final phase", "ex": "The project is in its final phase."},
    "phenomenon": {"def": "現象、傑出的人事物", "ipa": "/fəˈnɒmɪnən/", "trans": "phenomena (複數)", "col": "natural phenomenon", "ex": "Global warming is a global phenomenon."},
    "philosopher": {"def": "哲學家", "ipa": "/fɪˈlɒsəfə/", "trans": "philosophers", "col": "greek philosopher", "ex": "Plato was a famous Greek philosopher."},
    "philosophical": {"def": "哲學的、豁達的", "ipa": "/ˌfɪləˈsɒfɪkl/", "trans": "philosophically", "col": "philosophical thinking", "ex": "He took a philosophical view of his failure."},
    "philosophy": {"def": "哲學、人生觀", "ipa": "/fɪˈlɒsəfi/", "trans": "philosophies, philosopher", "col": "political philosophy", "ex": "I'm interested in eastern philosophy."},
    "phobia": {"def": "恐懼症", "ipa": "/ˈfəʊbiə/", "trans": "phobias", "col": "social phobia, arachnophobia", "ex": "He has a phobia about spiders."},
    "phone": {"def": "電話、受話機、打電話", "ipa": "/fəʊn/", "trans": "phones, telephoned", "col": "cellular phone, smart phone", "ex": "Answer the phone, please."},
    "phonetic": {"def": "語音的、音標的", "ipa": "/fəˈnetɪk/", "trans": "phonetics", "col": "phonetic symbol, phonetic spelling", "ex": "I'm using phonetic symbols to show pronunciation."},
    "phonetics": {"def": "語音學", "ipa": "/fəˈnetɪks/", "trans": "phonetic (形容詞)", "col": "study phonetics", "ex": "Phonetics is the study of speech sounds."},
    "phosphorus": {"def": "磷", "ipa": "/ˈfɒsfərəs/", "trans": "無", "col": "white phosphorus", "ex": "Phosphorus is used in making matches."},
    "photo": {"def": "照片", "ipa": "/ˈfəʊtəʊ/", "trans": "photos, photograph", "col": "take a photo", "ex": "Can I take a photo of you?"},
    "photograph": {"def": "照片、相片、照相", "ipa": "/ˈfəʊtəɡrɑːf/", "trans": "photographed, photographer", "col": "black and white photograph", "ex": "He takes high-quality photographs."},
    "photographer": {"def": "攝影師", "ipa": "/fəˈtɒɡrəfə/", "trans": "photographers", "col": "professional photographer", "ex": "He is a professional photographer for a fashion magazine."},
    "photography": {"def": "攝影、攝影術", "ipa": "/fəˈtɒɡrəfi/", "trans": "photographic", "col": "nature photography", "ex": "Her hobby is photography."},
    "photosphere": {"def": "光球層(太陽)", "ipa": "/ˈfəʊtəsfɪə/", "trans": "photospheres", "col": "solar photosphere", "ex": "The photosphere is the visible surface of the sun."},
}

with open("batch_l1_p40.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART40, f, ensure_ascii=False, indent=2)
