import json

# Level 1 Part 29: (Majesty - Massive)
L1_PART29 = {
    "majesty": {"def": "威嚴、莊嚴、陛下", "ipa": "/ˈmædʒəsti/", "trans": "majesties, majestic", "col": "Her Majesty", "ex": "He bowed before Her Majesty the Queen."},
    "major": {"def": "主要的、主修、成年人、少校", "ipa": "/ˈmeɪdʒə/", "trans": "majors, majority (多數)", "col": "major part, major in", "ex": "Pollution is a major problem."},
    "majority": {"def": "多數、大多數、成年", "ipa": "/məˈdʒɒrəti/", "trans": "majorities, minority (少數)", "col": "vast majority, majority vote", "ex": "The vast majority of people were happy."},
    "make": {"def": "製作、使得、品牌、製造", "ipa": "/meɪk/", "trans": "made, made, maker", "col": "make up, make effort", "ex": "He made a wooden table."},
    "maker": {"def": "製造者、創物主", "ipa": "/ˈmeɪkə/", "trans": "makers", "col": "policy maker, decision maker", "ex": "The decision was made by the policy makers."},
    "make-up/makeup": {"def": "化妝(品)、組成、虛構", "ipa": "/ˈmeɪk ʌp/", "trans": "makeups", "col": "put on makeup", "ex": "She is wearing too much makeup."},
    "malaise": {"def": "不適、心神不安、痼疾", "ipa": "/mæˈleɪz/", "trans": "無", "col": "economic malaise", "ex": "There is a sense of malaise in the country."},
    "malaria": {"def": "瘧疾", "ipa": "/məˈleəriə/", "trans": "無", "col": "suffer from malaria", "ex": "Many people died of malaria."},
    "male": {"def": "男性的、公的、雄性", "ipa": "/meɪl/", "trans": "males, female (女性的)", "col": "male student, male voice", "ex": "The bird is a male."},
    "malice": {"def": "惡意、怨恨", "ipa": "/ˈmælɪs/", "trans": "malicious (惡意的)", "col": "bear malice", "ex": "I bear him no malice."},
    "malicious": {"def": "惡意的、懷恨的", "ipa": "/məˈlɪʃəs/", "trans": "maliciously", "col": "malicious software", "ex": "He was accused of malicious gossip."},
    "mall": {"def": "購物中心、林蔭大道", "ipa": "/mɔːl/", "trans": "malls", "col": "shopping mall", "ex": "We spent the afternoon at the mall."},
    "mammal": {"def": "哺乳動物", "ipa": "/ˈmæml/", "trans": "mammals", "col": "marine mammal", "ex": "The whale is a large mammal."},
    "man": {"def": "男人、人類、執勤", "ipa": "/mæn/", "trans": "men, mankind (人類)", "col": "old man, man to man", "ex": "He is a good man."},
    "manage": {"def": "管理、處理、設法(做到)", "ipa": "/ˈmænɪdʒ/", "trans": "managed, manager, management", "col": "manage to do, manage time", "ex": "How do you manage to do so much?"},
    "management": {"def": "管理、經營、資方", "ipa": "/ˈmænɪdʒmənt/", "trans": "manage (動詞)", "col": "time management, business management", "ex": "The company has good management."},
    "manager": {"def": "經理、管理人、教練", "ipa": "/ˈmænɪdʒə/", "trans": "managers", "col": "general manager, sales manager", "ex": "The manager is talking to a client."},
    "mandate": {"def": "授權、委派、命領、託管地", "ipa": "/ˈmændet/", "trans": "mandates, mandatory", "col": "popular mandate", "ex": "The government has a mandate for change."},
    "mandatory": {"def": "強制的、義務的、託管的", "ipa": "/ˈmændətəri/", "trans": "mandate (名詞)", "col": "mandatory detention", "ex": "School attendance is mandatory."},
    "maneuver/manoeuvre": {"def": "調遣、演習、策略", "ipa": "/məˈnuːvə/", "trans": "maneuvered", "col": "military maneuver", "ex": "He carried out a tactical maneuver."},
    "mango": {"def": "芒果", "ipa": "/ˈmæŋɡəʊ/", "trans": "mangoes", "col": "sweet mango", "ex": "I like to eat mango juice."},
    "manifest": {"def": "顯然的、表露、清單", "ipa": "/ˈmænɪfest/", "trans": "manifested, manifestation", "col": "manifest interest", "ex": "Their dissatisfaction soon manifested itself."},
    "manifestation": {"def": "顯露、跡象、示威運動", "ipa": "/ˌmænɪfeˈsteɪʃn/", "trans": "manifestations, manifest (動詞)", "col": "clinical manifestation", "ex": "The riot was a manifestation of popular discontent."},
    "manipulate": {"def": "操縱、控制、處理", "ipa": "/məˈnɪpjuleɪt/", "trans": "manipulated, manipulation", "col": "manipulate market", "ex": "He tried to manipulate the situation."},
    "manipulation": {"def": "操縱、處理、手法", "ipa": "/məˌnɪpjuˈleɪʃn/", "trans": "manipulations", "col": "data manipulation", "ex": "The manipulation of figures is a serious crime."},
    "mankind": {"def": "人類", "ipa": "/mænˈkaɪnd/", "trans": "無 (不可數)", "col": "the future of mankind", "ex": "War is a crime against mankind."},
    "man-made": {"def": "人造的、人工的", "ipa": "/ˌmæn ˈmeɪd/", "trans": "natural (自然的)", "col": "man-made fibers", "ex": "The lake is man-made."},
    "manner": {"def": "方式、方法、態度、禮貌", "ipa": "/ˈmænə/", "trans": "manners", "col": "in a manner, good/bad manners", "ex": "It's a bad manner to talk with your mouth full."},
    "manners": {"def": "禮貌、風俗", "ipa": "/ˈmænəz/", "trans": "無 (恆複)", "col": "good manners, mind one's manners", "ex": "His manners are impeccable."},
    "manoeuvre": {"def": "調遣、策動、演習", "ipa": "/məˈnuːvə/", "trans": "manoeuvred", "col": "field manoeuvre", "ex": "The aircraft is capable of complex manoeuvres."},
    "mansion": {"def": "豪宅、公館、大廈", "ipa": "/ˈmænʃn/", "trans": "mansions", "col": "luxurious mansion", "ex": "They live in a large mansion."},
    "manual": {"def": "手動的、體力的、手冊", "ipa": "/ˈmænjuəl/", "trans": "manually", "col": "manual labor, instruction manual", "ex": "I read the instruction manual carefully."},
    "manually": {"def": "用手地、手動地", "ipa": "/ˈmænjuəli/", "trans": "manual (形容詞)", "col": "operate manually", "ex": "The machine should be operated manually."},
    "manufacture": {"def": "製造、製品、虛構", "ipa": "/ˌmænjuˈfæktʃə/", "trans": "manufactured, manufacturer", "col": "mass manufacture", "ex": "They manufacture clothes in the factory."},
    "manufacturer": {"def": "製造商、廠商", "ipa": "/ˌmænjuˈfæktʃərə/", "trans": "manufacturers", "col": "car manufacturer", "ex": "He is a leading computer manufacturer."},
    "manure": {"def": "肥料、糞便、施肥", "ipa": "/məˈnjʊə/", "trans": "manured", "col": "organic manure", "ex": "The farmers used manure on the fields."},
    "manuscript": {"def": "手稿、原稿", "ipa": "/ˈmænjuskrɪpt/", "trans": "manuscripts", "col": "original manuscript", "ex": "He sent the manuscript to the publisher."},
    "many": {"def": "許多的", "ipa": "/ˈmeni/", "trans": "more, most", "col": "many times, as many as", "ex": "I have many friends."},
    "map": {"def": "地圖、繪圖", "ipa": "/mæp/", "trans": "maps, mapped", "col": "world map, road map", "ex": "Look at the map."},
    "maple": {"def": "楓樹、楓木", "ipa": "/ˈmeɪpl/", "trans": "maples", "col": "maple leaf, maple syrup", "ex": "The maple leaves turned red in autumn."},
    "mar": {"def": "損毀、妨礙、汙點", "ipa": "/mɑː/", "trans": "marred", "col": "mar the beauty of", "ex": "The joy was marred by news of the accident."},
    "marathon": {"def": "馬拉松、馬拉松式的計畫", "ipa": "/ˈmærəθən/", "trans": "marathons", "col": "run a marathon", "ex": "He is training for a marathon."},
    "marble": {"def": "大理石、彈珠、冷酷的", "ipa": "/ˈmɑːbl/", "trans": "marbles", "col": "marble floor", "ex": "The floor is made of white marble."},
    "march": {"def": "行軍、進軍、前行、三月", "ipa": "/mɑːtʃ/", "trans": "marched", "col": "march on, protest march", "ex": "They marched to the city center."},
    "March": {"def": "三月", "ipa": "/mɑːtʃ/", "trans": "無", "col": "early March", "ex": "He was born in March."},
    "margin": {"def": "邊緣、餘地、差距、利潤", "ipa": "/ˈmɑːdʒɪn/", "trans": "margins, marginal", "col": "profit margin, wide margin", "ex": "He wrote notes in the margin of the book."},
    "marginal": {"def": "邊緣的、微小的、不重要的", "ipa": "/ˈmɑːdʒɪnl/", "trans": "marginally", "col": "marginal effect", "ex": "The change had only a marginal effect."},
    "marginally": {"def": "/ˈmɑːdʒɪnəli/", "trans": "marginal (形容詞)", "col": "increase marginally", "ex": "The price has increased marginally."},
    "marinate": {"def": "醃泡、醃漬", "ipa": "/ˈmærɪneɪt/", "trans": "marinated", "col": "marinate the meat", "ex": "Marinate the chicken for two hours."},
    "marine": {"def": "海洋的、海事的、海軍陸戰隊隊員", "ipa": "/məˈriːn/", "trans": "marines", "col": "marine life, merchant marine", "ex": "I like to study marine biology."},
    "marital": {"def": "婚姻的", "ipa": "/ˈmærɪtl/", "trans": "maritally", "col": "marital status", "ex": "What is your marital status?"},
    "mark": {"def": "痕跡、記號、分數、做記號", "ipa": "/mɑːk/", "trans": "marked, marker", "col": "question mark, trademark", "ex": "The stain left a mark on my shirt."},
    "marked": {"def": "顯著的、有記號的", "ipa": "/mɑːkt/", "trans": "markedly", "col": "marked improvement", "ex": "There has been a marked improvement in his work."},
    "markedly": {"def": "顯著地、醒目地", "ipa": "/ˈmɑːkɪdli/", "trans": "marked (形容詞)", "col": "markedly different", "ex": "The two countries are markedly different."},
    "marker": {"def": "麥克筆、記號員、指標", "ipa": "/ˈmɑːkə/", "trans": "markers", "col": "permanent marker", "ex": "He used a marker to draw a line."},
    "market": {"def": "市場、銷售、市集", "ipa": "/ˈmɑːkɪt/", "trans": "markets, marketable", "col": "flea market, stock market", "ex": "I'm going to the fish market."},
    "marketable": {"def": "可销售的、有市場的", "ipa": "/ˈmɑːkɪtəbl/", "trans": "marketability", "col": "marketable skills", "ex": "He has many marketable skills."},
    "marketing": {"def": "行銷、開發市場", "ipa": "/ˈmɑːkɪtɪŋ/", "trans": "market (名詞)", "col": "marketing manager", "ex": "She works in the marketing department."},
    "maroon": {"def": "栗色(的)、使孤立、荒島餘生", "ipa": "/məˈruːn/", "trans": "maroons", "col": "maroon color", "ex": "They were marooned on a desert island."},
    "marriage": {"def": "婚姻、結婚", "ipa": "/ˈmærɪdʒ/", "trans": "marriages, marry (動詞)", "col": "happy marriage, by marriage", "ex": "It was a very happy marriage."},
    "marrow": {"def": "髓、骨髓、精華", "ipa": "/ˈmærəʊ/", "trans": "marrows", "col": "bone marrow", "ex": "She needs a bone marrow transplant."},
    "marry": {"def": "結婚、娶、嫁", "ipa": "/ˈmæri/", "trans": "married, marriage", "col": "get married, marry young", "ex": "They got married last year."},
    "Mars": {"def": "火星、戰神", "ipa": "/mɑːz/", "trans": "Martian (火星的/人)", "col": "on Mars", "ex": "Is there life on Mars?"},
    "marsh": {"def": "沼澤、溼地", "ipa": "/mɑːʃ/", "trans": "marshes, marshy", "col": "salt marsh", "ex": "The birds live in the marsh."},
    "marshal/marshall": {"def": "元帥、典禮官、整理、編組", "ipa": "/ˈmɑːʃl/", "trans": "marshaled, marshaling", "col": "field marshal", "ex": "The general marshaled his troops."},
    "marshy": {"def": "沼澤的、濕軟的", "ipa": "/ˈmɑːʃi/", "trans": "marsh (名詞)", "col": "marshy ground", "ex": "The ground is marshy near the lake."},
    "martial": {"def": "戰爭的、武術的、尚武的", "ipa": "/ˈmɑːʃl/", "trans": "無", "col": "martial arts", "ex": "He is a master of martial arts."},
    "martyr": {"def": "殉道者、烈士、折磨", "ipa": "/ˈmɑːtə/", "trans": "martyrs, martyrdom", "col": "political martyr", "ex": "He died a martyr to the cause of freedom."},
    "marvel": {"def": "奇蹟、驚異的事、驚嘆", "ipa": "/ˈmɑːvl/", "trans": "marveled, marvelous", "col": "marvel at", "ex": "I marvel at her patience."},
    "marvelous/marvellous": {"def": "驚人的、奇蹟般的、極好的", "ipa": "/ˈmɑːvələs/", "trans": "marvelously", "col": "marvelous news", "ex": "It was a marvelous experience."},
    "masculine": {"def": "男性的、陽剛的", "ipa": "/ˈmæskjəlɪn/", "trans": "masculinity", "col": "masculine gender", "ex": "He has a very masculine voice."},
    "mash": {"def": "糊狀物、搗成泥、亂搞", "ipa": "/mæʃ/", "trans": "mashed", "col": "mashed potatoes", "ex": "I like mashed potatoes."},
    "mask": {"def": "面具、口罩、遮蔽", "ipa": "/mɑːsk/", "trans": "masked", "col": "gas mask, face mask", "ex": "She is wearing a mask."},
    "mass": {"def": "大量、大眾、質量、群眾的、聚集成塊", "ipa": "/mæs/", "trans": "masses, massive", "col": "in mass, mass media", "ex": "The mountains are a heavy mass of snow."},
    "massacre": {"def": "大屠殺、徹底擊敗", "ipa": "/ˈmæsəkə/", "trans": "massacred", "col": "bloody massacre", "ex": "Hundreds of people died in the massacre."},
    "massage": {"def": "按摩", "ipa": "/ˈmæsɑːʒ/", "trans": "massaged", "col": "back massage", "ex": "A massage will help you relax."},
    "massive": {"def": "巨大的、大規模的、厚重的", "ipa": "/ˈmæsɪv/", "trans": "massively", "col": "massive heart attack, massive building", "ex": "The building was an immense, massive structure."},
}

with open("batch_l1_p29.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART29, f, ensure_ascii=False, indent=2)
