import json

# Level 1 Part 24: (Intent - Ivory)
L1_PART24 = {
    "intent": {"def": "意圖、目的、熱切的", "ipa": "/ɪnˈtent/", "trans": "intently", "col": "intent on doing, with the intent of", "ex": "He is intent on winning the game."},
    "intently": {"def": "一心一意地、熱切地", "ipa": "/ɪnˈtentli/", "trans": "intent (名詞/形容詞)", "col": "listen intently", "ex": "She listened intently to every word."},
    "intention": {"def": "意圖、目的、打算", "ipa": "/ɪnˈtenʃn/", "trans": "intentions, intentional", "col": "good intention, have no intention of", "ex": "I have no intention of leaving."},
    "intentional": {"def": "故意的、有意的", "ipa": "/ɪnˈtenʃənl/", "trans": "intentionally", "col": "intentional damage", "ex": "The damage was not intentional."},
    "intentionally": {"def": "/ɪnˈtenʃənəli/", "trans": "intentional (形容詞)", "col": "act intentionally", "ex": "He did it intentionally."},
    "interact": {"def": "互動、相互作用", "ipa": "/ˌɪntərˈækt/", "trans": "interaction", "col": "interact with", "ex": "Children need to interact with others."},
    "interaction": {"def": "互動、相互影響", "ipa": "/ˌɪntərˈækʃn/", "trans": "interactions, interactive", "col": "social interaction", "ex": "Interaction between students is important."},
    "interactive": {"def": "互動的、交互式的", "ipa": "/ˌɪntərˈæktɪv/", "trans": "interactively", "col": "interactive whiteboard", "ex": "This is an interactive educational program."},
    "interest": {"def": "興趣、利息、利益、使感興趣", "ipa": "/ˈɪntrəst/", "trans": "interested, interesting, interestingly", "col": "be interested in, common interest", "ex": "I have an interest in music."},
    "interested": {"def": "感興趣的、有利害關係的", "ipa": "/ˈɪntrəstɪd/", "trans": "interest (名詞/動詞)", "col": "be interested in", "ex": "I am interested in learning English."},
    "interesting": {"def": "有趣的", "ipa": "/ˈɪntrəstɪŋ/", "trans": "interestingly", "col": "interesting story", "ex": "His story was very interesting."},
    "interestingly": {"def": "/ˈɪntrəstɪŋli/", "trans": "interesting (形容詞)", "col": "interestingly enough", "ex": "Interestingly, he never mentioned his family."},
    "interfere": {"def": "干涉、妨礙", "ipa": "/ˌɪntəˈfɪə/", "trans": "interfered, interference", "col": "interfere with", "ex": "Don't interfere with my business."},
    "interference": {"def": "干涉、干擾、中斷", "ipa": "/ˌɪntəˈfɪərəns/", "trans": "interferes", "col": "political interference, radio interference", "ex": "I don't like any interference in my private life."},
    "interior": {"def": "內部、內地的、內心的", "ipa": "/ɪnˈtɪəriə/", "trans": "exteriors (外部的)", "col": "interior design, ministry of interior", "ex": "The interior of the house was dusty."},
    "intermediate": {"def": "中間的、中級的", "ipa": "/ˌɪntəˈmiːdiət/", "trans": "intermediate level", "col": "intermediate stage", "ex": "This is an intermediate level course."},
    "internal": {"def": "內部的、國內的、體內的", "ipa": "/ɪnˈtɜːnl/", "trans": "internally", "col": "internal revenue, internal bleeding", "ex": "Smoking causes internal damage."},
    "international": {"def": "國際的", "ipa": "/ˌɪntəˈnæʃənl/", "trans": "internationally", "col": "international airport", "ex": "This is an international organization."},
    "internationally": {"def": "/ˌɪntəˈnæʃənəli/", "trans": "international (形容詞)", "col": "internationally renowned", "ex": "He is an internationally known scientist."},
    "Internet": {"def": "網際網路", "ipa": "/ˈɪntənet/", "trans": "無", "col": "on the internet, surf the internet", "ex": "I usually buy books on the internet."},
    "interpret": {"def": "解釋、翻譯、詮釋", "ipa": "/ɪnˈtɜːprət/", "trans": "interpreted, interpretation, interpreter", "col": "interpret a dream", "ex": "Can you interpret the sentence for me?"},
    "interpretation": {"def": "解釋、表演、翻釋", "ipa": "/ɪnˌtɜːprɪˈteɪʃn/", "trans": "interpretations, interpret (動詞)", "col": "a novel interpretation", "ex": "Her interpretation of the song was beautiful."},
    "interpreter": {"def": "口譯員、解釋者", "ipa": "/ɪnˈtɜːprətə/", "trans": "interpreters", "col": "trained interpreter", "ex": "He works as an interpreter at the UN."},
    "interrupt": {"def": "打斷、中斷、妨礙", "ipa": "/ˌɪntəˈrʌpt/", "trans": "interrupted, interruption", "col": "interrupt someone", "ex": "Don't interrupt me while I'm talking."},
    "interruption": {"def": "中斷、干擾、暫停", "ipa": "/ˌɪntəˈrʌpʃn/", "trans": "interruptions, interrupt (動詞)", "col": "without interruption", "ex": "We worked for four hours without interruption."},
    "intersection": {"def": "交叉路口、十字路口", "ipa": "/ˈ常规 /", "trans": "intersections", "col": "at the intersection", "ex": "Turn left at the intersection."},
    "interval": {"def": "間隔、距離、中場休息", "ipa": "/ˈɪntəvl/", "trans": "intervals", "col": "at regular intervals", "ex": "There was an interval of ten minutes between the acts."},
    "intervention": {"def": "干預、調停、介入", "ipa": "/ˌɪntəˈvenʃn/", "trans": "intervene (干預)", "col": "military intervention", "ex": "The government's intervention proved to be helpful."},
    "interview": {"def": "面試、訪談、採訪", "ipa": "/ˈɪntəvjuː/", "trans": "interviewer, interviewee", "col": "job interview", "ex": "I have an interview for a job tomorrow."},
    "intimacy": {"def": "親密、親近、隱私", "ipa": "/ˈɪntɪməsi/", "trans": "intimate (親密的)", "col": "sense of intimacy", "ex": "The relationship was one of great intimacy."},
    "intimate": {"def": "親密的、私人的、密友", "ipa": "/ˈɪntɪmət/", "trans": "intimately", "col": "intimate friend", "ex": "He is my most intimate friend."},
    "into": {"def": "進入、成、對...感興趣", "ipa": "/ˈɪntuː/", "trans": "無", "col": "get into, run into", "ex": "She walked into the room."},
    "intonation": {"def": "語調、聲調", "ipa": "/ˌɪntəˈneɪʃn/", "trans": "intonations", "col": "correct intonation", "ex": "His English has a good intonation."},
    "intimidate": {"def": "威脅、恐嚇", "ipa": "/ɪnˈtɪmɪdeɪt/", "trans": "intimidated, intimidation", "col": "intimidate someone into", "ex": "The gangs intimidated the local people."},
    "intolerance": {"def": "不寬容、無法忍受", "ipa": "/ɪnˈtɒlərəns/", "trans": "intolerant (不寬容的)", "col": "religious intolerance", "ex": "We should fight against intolerance."},
    "introduce": {"def": "介紹、引進、採用", "ipa": "/ˌɪntrəˈdjuːs/", "trans": "introduction (名詞)", "col": "introduce someone to", "ex": "Let me introduce my friend to you."},
    "introduction": {"def": "介紹、引進、緒論", "ipa": "/ˌɪntrəˈdʌkʃn/", "trans": "introductions, introduce (動詞)", "col": "letter of introduction", "ex": "The book has a long introduction."},
    "introductory": {"def": "介紹的、導論性的、入門的", "ipa": "/ˌɪntrəˈdʌktəri/", "trans": "introduction", "col": "introductory course", "ex": "This is an introductory course to biology."},
    "invade": {"def": "侵略、入侵、侵犯", "ipa": "/ɪnˈveɪd/", "trans": "invaded, invasion, invader", "col": "invade a country", "ex": "The troops invaded the country yesterday."},
    "invader": {"def": "侵略者", "ipa": "/ɪnˈveɪdə/", "trans": "invaders", "col": "foreign invader", "ex": "The invaders were defeated."},
    "invalid": {"def": "無效的、傷殘者(ˈɪnvəlɪd)", "ipa": "/ɪnˈvælɪd/", "trans": "invalidated", "col": "invalid password", "ex": "Your password is invalid."},
    "invasion": {"def": "入侵、侵略、攻入", "ipa": "/ɪnˈveɪʒn/", "trans": "invasions, invade (動詞)", "col": "military invasion, invasion of privacy", "ex": "The invasion of privacy is a serious issue."},
    "invent": {"def": "發明、虛構", "ipa": "/ɪnˈvent/", "trans": "invention, inventor", "col": "invent a machine", "ex": "Edison invented the light bulb."},
    "invention": {"def": "發明、虛構、發明物", "ipa": "/ɪnˈvenʃn/", "trans": "inventions, invent (動詞)", "col": "latest invention", "ex": "Television is an important invention."},
    "inventive": {"def": "有發明才能的、獨創的", "ipa": "/ɪnˈventɪv/", "trans": "inventiveness", "col": "inventive mind", "ex": "She has a very inventive mind."},
    "inventor": {"def": "發明者", "ipa": "/ɪnˈventə/", "trans": "inventors", "col": "famed inventor", "ex": "Bell was the inventor of the telephone."},
    "invest": {"def": "投資、投入", "ipa": "/ɪnˈvest/", "trans": "investment, investor", "col": "invest in", "ex": "I want to invest some money in the stock market."},
    "investigate": {"def": "調查", "ipa": "/ɪnˈvestɪɡeɪt/", "trans": "investigation (名詞), investigator (調查員)", "col": "investigate a crime", "ex": "The police are investigating the cause of the fire."},
    "investigation": {"def": "調查、研究、偵查", "ipa": "/ɪnˌvestɪˈɡeɪʃn/", "trans": "investigations, investigate (動詞)", "col": "under investigation", "ex": "The incident is under investigation."},
    "investigator": {"def": "調查人員、研究者", "ipa": "/ɪnˈvestɪɡeɪtə/", "trans": "investigators", "col": "police investigator", "ex": "He is a detective investigator."},
    "investment": {"def": "投資、投入", "ipa": "/ɪnˈvestmənt/", "trans": "investments, invest (動詞)", "col": "capital investment, sound investment", "ex": "Tobacco is a bad investment."},
    "investor": {"def": "投資者", "ipa": "/ɪnˈvestə/", "trans": "investors", "col": "foreign investor", "ex": "The project attracted many foreign investors."},
    "invisible": {"def": "隱形的、看不見的", "ipa": "/ɪnˈvɪzəbl/", "trans": "visible (看得見的)", "col": "invisible ink", "ex": "Gas is usually invisible."},
    "invitation": {"def": "邀請、招呼、請帖", "ipa": "/ˌɪnvɪˈteɪʃn/", "trans": "invitations, invite (動詞)", "col": "wedding invitation, accept an invitation", "ex": "Thank you for your invitation."},
    "invite": {"def": "邀請、招致", "ipa": "/ɪnˈvaɪt/", "trans": "invited", "col": "invite to dinner", "ex": "I'll invite him to my party."},
    "inviting": {"def": "誘人的、引人入勝的", "ipa": "/ɪnˈvaɪtɪŋ/", "trans": "invitingly", "col": "inviting smile", "ex": "The bed looked very inviting."},
    "invoke": {"def": "援引、祈求、引發", "ipa": "/ɪnˈvəʊk/", "trans": "invoked", "col": "invoke the law", "ex": "They invoked the emergency powers."},
    "involuntary": {"def": "非自願的、無意識的", "ipa": "/ɪnˈvɒləntri/", "trans": "voluntarily (自願地)", "col": "involuntary muscles", "ex": "A shiver was an involuntary reaction to the cold."},
    "involve": {"def": "涉及、包括、使陷入", "ipa": "/ɪnˈvɒlv/", "trans": "involved, involvement (名詞)", "col": "be involved in", "ex": "The accident involved two cars."},
    "involved": {"def": "有關的、複雜的、捲入的", "ipa": "/ɪnˈvɒlvd/", "trans": "involve (動詞)", "col": "be involved with", "ex": "Don't get involved with him."},
    "involvement": {"def": "涉入、捲入、連累", "ipa": "/ɪnˈvɒlvmənt/", "trans": "involve (動詞)", "col": "emotional involvement", "ex": "I denied any involvement in the scandal."},
    "iron": {"def": "鐵、熨斗、熨", "ipa": "/ˈaɪən/", "trans": "irons, ironic (諷刺的)", "col": "cast iron, iron a shirt", "ex": "I need an iron to iron my shirt."},
    "ironic": {"def": "諷刺的、相反地", "ipa": "/aɪˈrɒnɪk/", "trans": "ironically, irony (名詞)", "col": "ironic remark", "ex": "It's ironic that he is a poor doctor."},
    "irony": {"def": "諷刺、反諷、冷笑", "ipa": "/ˈaɪərəni/", "trans": "ironies", "col": "tragic irony", "ex": "The irony of the situation was evident to all."},
    "irregular": {"def": "不規則的、非正式的、不齊的", "ipa": "/ɪˈreɡjələ/", "trans": "regular (規則的)", "col": "irregular verb", "ex": "These are irregular verbs."},
    "irregularity": {"def": "不規則、不整齊、瑕疵", "ipa": "/ɪˌreɡjəˈlærəti/", "trans": "irregular (形容詞)", "col": "financial irregularity", "ex": "There were some irregularities in the accounts."},
    "irrelevant": {"def": "無關的、不適切的", "ipa": "/ɪˈreləvənt/", "trans": "relevant (相關的)", "col": "irrelevant information", "ex": "His remarks were irrelevant to the topic."},
    "irresponsible": {"def": "不負責任的", "ipa": "/ˌɪrɪˈspɒnsəbl/", "trans": "responsible (有責任的)", "col": "be irresponsible of", "ex": "It was irresponsible of you to leave the window open."},
    "irrigate": {"def": "灌溉、潤濕", "ipa": "/ˈɪrɪɡeɪt/", "trans": "irrigation", "col": "irrigate fields", "ex": "They use water from the river to irrigate the fields."},
    "irrigation": {"def": "灌溉", "ipa": "/ˌɪrɪˈɡeɪʃn/", "trans": "irrigate (動詞)", "col": "irrigation system", "ex": "The government funded the new irrigation project."},
    "irritable": {"def": "易怒的、敏感的", "ipa": "/ˈɪrɪtəbl/", "trans": "irritably", "col": "feel irritable", "ex": "The lack of sleep made him very irritable."},
    "irritate": {"def": "使惱火、刺激(皮膚等)", "ipa": "/ˈɪrɪteɪt/", "trans": "irritated, irritating", "col": "irritate someone", "ex": "Stop making that noise; it irritates me."},
    "irritated": {"def": "感到惱火的、發炎的", "ipa": "/ˈɪrɪteɪtɪd/", "trans": "irritate (動詞)", "col": "get irritated", "ex": "He gets irritated very easily."},
    "irritating": {"def": "令人惱火的、氣人的", "ipa": "/ˈɪrɪteɪtɪŋ/", "trans": "irritatingly", "col": "irritating habit", "ex": "It was a very irritating experience."},
    "island": {"def": "島嶼", "ipa": "/ˈaɪlənd/", "trans": "islander", "col": "tropical island", "ex": "Taiwan is a beautiful island."},
    "isolate": {"def": "使隔離、使孤立", "ipa": "/ˈaɪsəleɪt/", "trans": "isolated, isolation", "col": "isolate from", "ex": "The island was isolated from the mainland."},
    "isolated": {"def": "孤立的、偏僻的、唯一的", "ipa": "/ˈaɪsəleɪtɪd/", "trans": "isolate (動詞)", "col": "isolated village", "ex": "The village is completely isolated in winter."},
    "isolation": {"def": "孤立、隔離", "ipa": "/ˌaɪsəˈleɪʃn/", "trans": "isolations", "col": "in isolation", "ex": "The prisoners were kept in isolation."},
    "issue": {"def": "議題、發行、核發、排放", "ipa": "/ˈɪʃuː/", "trans": "issued", "col": "major issue, current issue", "ex": "Climate change is a global issue."},
    "it": {"def": "它", "ipa": "/ɪt/", "trans": "its, itself", "col": "it doesn't matter", "ex": "I like it."},
    "italic": {"def": "斜體字(的)", "ipa": "/ɪˈtælɪk/", "trans": "italics", "col": "italic font", "ex": "These words are in italic type."},
    "Italy": {"def": "義大利", "ipa": "/ˈɪtəli/", "trans": "Italian (義大利的/人/語)", "col": "Rome, Italy", "ex": "Rome is the capital of Italy."},
    "item": {"def": "項目、品目、一件物品", "ipa": "/ˈaɪtəm/", "trans": "items", "col": "item of clothing", "ex": "What's the next item on the agenda?"},
    "its": {"def": "它的 (it 之所有格)", "ipa": "/ɪts/", "trans": "it", "col": "its own", "ex": "The cat is eating its food."},
    "itself": {"def": "它自己", "ipa": "/ɪtˈself/", "trans": "無", "col": "it itself", "ex": "History repeat itself."},
    "ivory": {"def": "象牙(的)、乳白色", "ipa": "/ˈaɪvəri/", "trans": "無", "col": "ivory coast", "ex": "The keys of the piano are made of ivory."},
}

with open("batch_l1_p24.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART24, f, ensure_ascii=False, indent=2)
