import json

# Level 1 Part 42: (Placard - Plywood)
L1_PART42 = {
    "placard": {"def": "公告、海報、布告、招貼", "ipa": "/ˈplækɑːd/", "trans": "placards", "col": "carry a placard", "ex": "The protesters carried placards with slogans."},
    "place": {"def": "地方、名次、地位、放置、安置", "ipa": "/pleɪs/", "trans": "placed, placement", "col": "take place, in place of", "ex": "Put it in its place."},
    "placement": {"def": "安置、佈置、分配、職位", "ipa": "/ˈpleɪsmənt/", "trans": "placements", "col": "job placement", "ex": "The school offers a job placement service."},
    "plague": {"def": "瘟疫、天災、禍患、折磨、煩擾", "ipa": "/pleɪɡ/", "trans": "plagued", "col": "bubonic plague", "ex": "The country was hit by a plague of locusts."},
    "plain": {"def": "平原、純色的、顯然的、簡樸的", "ipa": "/pleɪn/", "trans": "plainly", "col": "plain clothes, make plain", "ex": "The meaning is quite plain."},
    "plainly": {"def": "明白地、坦率地、樸素地", "ipa": "/ˈplainli/", "trans": "plain (形容詞)", "col": "speak plainly", "ex": "He said plainly that he couldn't come."},
    "plan": {"def": "計畫、方案、平面圖、打算、設計", "ipa": "/plæn/", "trans": "planned, planner, planning", "col": "action plan, make a plan", "ex": "Do you have a plan for the weekend?"},
    "plane": {"def": "飛機、平面、程度、刨平、翱翔", "ipa": "/pleɪn/", "trans": "planes", "col": "fighter plane, paper plane", "ex": "The plane took off on time."},
    "planet": {"def": "行星", "ipa": "/ˈplænɪt/", "trans": "planets, planetary", "col": "red planet, planet earth", "ex": "Mars is known as the Red Planet."},
    "planetary": {"def": "行星的", "ipa": "/ˈplænətri/", "trans": "planet (名詞)", "col": "planetary motion", "ex": "Planetary motion follows specific physical laws."},
    "plank": {"def": "厚板、木板、要點、鋪板", "ipa": "/plæŋk/", "trans": "planks", "col": "wooden plank", "ex": "He walked across the plank."},
    "planner": {"def": "計劃者、設計師、行事曆", "ipa": "/ˈplænə/", "trans": "planners", "col": "wedding planner", "ex": "She is an event planner."},
    "plant": {"def": "植物、工廠、設備、種植、栽植", "ipa": "/plɑːnt/", "trans": "planted, plantation", "col": "power plant, garden plant", "ex": "The plant is growing rapidly."},
    "plantation": {"def": "農場、種植園、人造林", "ipa": "/plɑːnˈteɪʃn/", "trans": "plantations", "col": "rubber plantation", "ex": "Tea is grown on large plantations."},
    "plaque": {"def": "匾、齒垢、銘牌", "ipa": "/plæk/", "trans": "plaques", "col": "memorial plaque, dental plaque", "ex": "A memorial plaque was erected in his honor."},
    "plasma": {"def": "等離子體、血漿", "ipa": "/ˈplæzmə/", "trans": "plasmas", "col": "plasma screen", "ex": "Plasma is the fourth state of matter."},
    "plaster": {"def": "灰泥、石膏、膏藥、塗以灰泥", "ipa": "/ˈplɑːstə/", "trans": "plasters, plastered", "col": "sticking plaster, in plaster", "ex": "The walls are covered with plaster."},
    "plastic": {"def": "塑膠(的)、可塑的、虚偽的", "ipa": "/ˈplæstɪk/", "trans": "plastics", "col": "plastic surgery, plastic bag", "ex": "I use plastic bags sparingly."},
    "plate": {"def": "盤子、金屬板、車牌、鍍金", "ipa": "/pleɪt/", "trans": "plates, plated", "col": "license plate, dinner plate", "ex": "I put the cookies on a plate."},
    "plateau": {"def": "高原、穩定狀態、達到平穩期", "ipa": "/ˈplætəʊ/", "trans": "plateaus", "col": "reach a plateau", "ex": "Tibetan Plateau is the highest in the world."},
    "platform": {"def": "平台、月台、政綱、講台", "ipa": "/ˈplætfɔːm/", "trans": "platforms", "col": "station platform, oil platform", "ex": "Wait for me on the platform."},
    "plating": {"def": "鍍金、金屬板裝甲", "ipa": "/ˈpleɪtɪŋ/", "trans": "plate (名詞/動詞)", "col": "chrome plating", "ex": "The car has silver plating on the handles."},
    "platinum": {"def": "鉑、白金、鉑色的", "ipa": "/ˈˈplætɪnəm/", "trans": "無", "col": "platinum record", "ex": "Platinum is a precious metal."},
    "plattery": {"def": "盤子類、碟類", "ipa": "/ˈplætəri/", "trans": "plate", "col": "collection of plattery", "ex": "She has a fine collection of plattery."},
    "plausible": {"def": "似有道理的、花言巧語的", "ipa": "/ˈplɔːzəbl/", "trans": "plausibly, plausibility", "col": "plausible explanation", "ex": "His story sounds plausible."},
    "play": {"def": "玩耍、比賽、劇本、彈奏、播放", "ipa": "/pleɪ/", "trans": "played, player, playwright", "col": "play football, play a role", "ex": "Children like to play."},
    "player": {"def": "選手、演奏者、播放器", "ipa": "/ˈpleɪə/", "trans": "players", "col": "record player, team player", "ex": "He is a great football player."},
    "playful": {"def": "好玩的、嬉戲的、開玩笑的", "ipa": "/ˈpleɪfl/", "trans": "playfully", "col": "playful kitten", "ex": "The puppy is very playful."},
    "playground": {"def": "操場、遊樂場", "ipa": "/ˈpleɪɡraʊnd/", "trans": "playgrounds", "col": "school playground", "ex": "The kids are playing on the playground."},
    "playhouse": {"def": "劇場、兒童遊戲房", "ipa": "/ˈpleɪhaʊs/", "trans": "playhouses", "col": "summer playhouse", "ex": "They are building a playhouse for the kids."},
    "playmate": {"def": "玩伴", "ipa": "/ˈpleɪmeɪt/", "trans": "playmates", "col": "childhood playmate", "ex": "She was my favorite playmate."},
    "playwright": {"def": "劇作家", "ipa": "/ˈpleɪraɪt/", "trans": "playwrights", "col": "famous playwright", "ex": "Shakespeare was a great playwright."},
    "plea": {"def": "懇求、辯解、託辭、抗辯", "ipa": "/pliː/", "trans": "pleas, plead", "col": "enter a plea, plea bargain", "ex": "He made a plea for mercy."},
    "plead": {"def": "懇求、辯護、認罪、以...為藉口", "ipa": "/pliːd/", "trans": "pleaded", "col": "plead guilty, plead for", "ex": "I plead with you to stay."},
    "pleasant": {"def": "令人愉快的、親切的", "ipa": "/ˈpleznt/", "trans": "pleasantly", "col": "pleasant surprise", "ex": "We had a pleasant evening."},
    "pleasantly": {"def": "愉快地、親切地", "ipa": "/ˈplezntli/", "trans": "pleasant (形容詞)", "col": "be pleasantly surprised", "ex": "They were pleasantly surprised by the results."},
    "please": {"def": "請、使高興、滿意", "ipa": "/pliːz/", "trans": "pleased, pleasing, pleasure", "col": "please yourself", "ex": "Open the door, please."},
    "pleased": {"def": "高興的、滿意的", "ipa": "/pliːzd/", "trans": "please (動詞)", "col": "be pleased with", "ex": "I'm very pleased to meet you."},
    "pleasing": {"def": "令人高興的、愉快的", "ipa": "/ˈpliːzɪŋ/", "trans": "pleasingly", "col": "pleasing results", "ex": "The news was very pleasing."},
    "pleasure": {"def": "快樂、樂事、願望、使高興", "ipa": "/ˈpleʒə/", "trans": "pleasures", "col": "with pleasure, my pleasure", "ex": "It's a pleasure to meet you."},
    "pledge": {"def": "誓言、保證、抵押品、保證、抵押", "ipa": "/pledʒ/", "trans": "pledged", "col": "make a pledge, pledge allegiance", "ex": "They made a pledge to help."},
    "plentiful": {"def": "豐富的、充足的", "ipa": "/ˈplentɪfl/", "trans": "plentifully", "col": "plentiful supply", "ex": "Food is plentiful this year."},
    "plenty": {"def": "豐富、大量、足夠、充足地", "ipa": "/ˈplenti/", "trans": "plentiful", "col": "plenty of", "ex": "We have plenty of time."},
    "pliable": {"def": "柔韌的、易彎的、易受影響的", "ipa": "/ˈplaɪəbl/", "trans": "pliability", "col": "pliable material", "ex": "The plastic is pliable when warm."},
    "plight": {"def": "困境、苦難、誓約", "ipa": "/plaɪt/", "trans": "plights", "col": "hopeless plight", "ex": "I feel sympathy for the plight of the homeless."},
    "plot": {"def": "情節、陰謀、小塊土地、圖表、策劃", "ipa": "/plɒt/", "trans": "plots, plotted", "col": "conspiracy plot, garden plot", "ex": "The plot of the movie is interesting."},
    "plough/plow": {"def": "犁、耕地、開路、耕", "ipa": "/plaʊ/", "trans": "ploughed", "col": "snow plough", "ex": "The farmer is ploughing the field."},
    "pluck": {"def": "勇氣、膽量、拔、採摘、扯", "ipa": "/plʌk/", "trans": "plucked", "col": "pluck up courage", "ex": "She plucked a flower from the garden."},
    "plug": {"def": "插頭、塞子、公開宣傳、塞住、插電", "ipa": "/plʌɡ/", "trans": "plugs, plugged", "col": "spark plug, pull the plug", "ex": "Put the plug in the socket."},
    "plum": {"def": "梅子、李子、深紫色、上好的物", "ipa": "/plʌm/", "trans": "plums", "col": "plum pudding", "ex": "The plum is ripe and sweet."},
    "plumber": {"def": "水管工人", "ipa": "/ˈplʌmə/", "trans": "plumbers", "col": "call a plumber", "ex": "The plumber came to fix the leak."},
    "plume": {"def": "羽毛、羽飾、羽狀物、用羽毛裝飾", "ipa": "/pluːm/", "trans": "plumes", "col": "plume of smoke", "ex": "A plume of smoke rose from the chimney."},
    "plump": {"def": "圓胖的、豐滿的、使豐滿、沈重地墜下", "ipa": "/plʌmp/", "trans": "plumper", "col": "plump cheeks", "ex": "The baby has plump red cheeks."},
    "plunder": {"def": "掠奪物、戰利品、掠奪", "ipa": "/ˈplʌndə/", "trans": "plundered", "col": "plunder and loot", "ex": "The soldiers plundered the city."},
    "plunge": {"def": "跳入、衝進、猛降、投產", "ipa": "/plʌndʒ/", "trans": "plunged", "col": "take the plunge, plunge into", "ex": "He took a plunge into the pool."},
    "plural": {"def": "複數的、多樣的、複數", "ipa": "/ˈplʊərəl/", "trans": "plurals, singular (單數)", "col": "plural form", "ex": "'Cats' is the plural of 'cat'."},
    "plus": {"def": "加、連同、正的、好處、加號", "ipa": "/plʌs/", "trans": "minus (減)", "col": "plus sign", "ex": "Two plus two is four."},
    "plush": {"def": "長毛絨、豪華的", "ipa": "/plʌʃ/", "trans": "plushes", "col": "plush hotel", "ex": "They live in a plush apartment."},
    "plywood": {"def": "膠合板", "ipa": "/ˈplaɪwʊd/", "trans": "無", "col": "sheet of plywood", "ex": "The furniture is made of plywood."},
}

with open("batch_l1_p42.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART42, f, ensure_ascii=False, indent=2)
