import json

# Level 1 Part 38: (Parody - Pattern)
L1_PART38 = {
    "parody": {"def": "滑稽模仿、諷刺性寫作、拙劣的模仿、模仿", "ipa": "/ˈpærədi/", "trans": "parodied", "col": "hilarious parody", "ex": "The show is a clever parody of a talk show."},
    "parole": {"def": "假釋、誓言、假釋期、假釋", "ipa": "/pəˈrəʊl/", "trans": "paroled", "col": "on parole, release on parole", "ex": "He was released on parole after five years."},
    "paroxysm": {"def": "突發、發作、陣發、爆發", "ipa": "/ˈpærksɪzəm/", "trans": "paroxysms", "col": "paroxysm of laughter", "ex": "He was seized with a paroxysm of coughing."},
    "parquet": {"def": "鑲木地板", "ipa": "/ˈpɑːkeɪ/", "trans": "parquetry", "col": "parquet floor", "ex": "The dining room had a beautiful parquet floor."},
    "parrot": {"def": "鸚鵡、模仿、機械地搬用", "ipa": "/ˈpærət/", "trans": "parrots, parroted", "col": "repeat like a parrot", "ex": "He is just parroting what he heard."},
    "parry": {"def": "擋開、避開(攻擊)、迴避(問題)", "ipa": "/ˈpæri/", "trans": "parried", "col": "parry a question", "ex": "She managed to parry the reporter's question."},
    "part": {"def": "部分、零件、角色、分裂、離開", "ipa": "/pɑːt/", "trans": "parts, partially, partner", "col": "take part in, spare part", "ex": "The bike consists of many parts."},
    "partial": {"def": "部分的、偏袒的、熱愛的", "ipa": "/ˈpɑːʃl/", "trans": "partially, partiality", "col": "be partial to, partial view", "ex": "The report is only partial."},
    "partiality": {"def": "偏袒、偏愛、局部", "ipa": "/ˌpɑːʃiˈæləti/", "trans": "partialities, partial (形容詞)", "col": "treat with partiality", "ex": "He showed partiality toward his son."},
    "partially": {"def": "部分地、在一定程度上", "ipa": "/ˈpɑːʃəli/", "trans": "partial (形容詞)", "col": "partially successful", "ex": "The plan was only partially successful."},
    "participant": {"def": "參與者、有份的", "ipa": "/pɑːˈtɪsɪpənt/", "trans": "participants, participate (動詞)", "col": "active participant", "ex": "She is an active participant in the class."},
    "participate": {"def": "參加、參與、分享", "ipa": "/pɑːˈtɪsɪpeɪt/", "trans": "participated, participation", "col": "participate in", "ex": "We encourage everyone to participate."},
    "participation": {"def": "參加、參與、分享", "ipa": "/pɑːˌtɪsɪˈpeɪʃn/", "trans": "participate (動詞)", "col": "active participation", "ex": "Student participation in class is encouraged."},
    "participial": {"def": "分詞的", "ipa": "/ˌpɑːtɪˈsɪpiəl/", "trans": "participle (名詞)", "col": "participial phrase", "ex": "Wait' is a participial form."},
    "participle": {"def": "分詞", "ipa": "/ˈpɑːtɪsɪpl/", "trans": "participles", "col": "present participle, past participle", "ex": "'Gone' is the past participle of 'go'."},
    "particle": {"def": "微粒、粒子、極小物、介詞/助詞", "ipa": "/ˈpɑːtɪkl/", "trans": "particles", "col": "subatomic particle, dust particle", "ex": "Dust particles are floating in the air."},
    "particular": {"def": "特別的、獨特的、講究的、細目", "ipa": "/pəˈtɪkjələ/", "trans": "particularly, particularity", "col": "in particular, be particular about", "ex": "He is very particular about his food."},
    "particularly": {"def": "特別地、尤其", "ipa": "/pəˈtɪkjələli/", "trans": "particular (形容詞)", "col": "particularly important", "ex": "The exam was particularly difficult."},
    "partition": {"def": "隔板、分割、分裂", "ipa": "/pɑːˈtɪʃn/", "trans": "partitions, partitioned", "col": "office partition", "ex": "The wall is just a wood partition."},
    "partly": {"def": "部分地、在一定程度上", "ipa": "/ˈpɑːtli/", "trans": "part (名詞)", "col": "be partly responsible", "ex": "He is partly to blame for the accident."},
    "partner": {"def": "夥伴、合夥人、配偶、合夥", "ipa": "/ˈpɑːtnə/", "trans": "partners, partnership", "col": "business partner", "ex": "He is my business partner."},
    "partnership": {"def": "合夥(關係)、夥伴關係", "ipa": "/ˈpɑːtnəʃɪp/", "trans": "partnerships", "col": "in partnership with", "ex": "The two companies entered into a partnership."},
    "part-time": {"def": "兼職的、部分的", "ipa": "/ˌpɑːt ˈtaɪm/", "trans": "full-time (全職的)", "col": "part-time job", "ex": "He works part-time at the cafe."},
    "party": {"def": "派對、黨派、一方(當事人)", "ipa": "/ˈpɑːti/", "trans": "parties", "col": "birthday party, democratic party", "ex": "We had a party yesterday."},
    "pass": {"def": "通過、經過、遞、及格、過關、護照", "ipa": "/pɑːs/", "trans": "passed, passage, passenger", "col": "pass by, board pass", "ex": "The car passed us at high speed."},
    "passage": {"def": "通道、通過、段落、航行", "ipa": "/ˈpæsɪdʒ/", "trans": "passages", "col": "narrow passage, passage of time", "ex": "The passage leads to the back door."},
    "passenger": {"def": "乘客、旅客、不工作的人(掛名)", "ipa": "/ˈpæsɪndʒə/", "trans": "passengers", "col": "passenger train, passenger seat", "ex": "The plane was full of passengers."},
    "passerby": {"def": "過路人、行人", "ipa": "/ˌpɑːsəˈbaɪ/", "trans": "passersby (複數)", "col": "injured passerby", "ex": "A passerby called the police."},
    "passion": {"def": "熱情、激情、酷愛、基督受難", "ipa": "/ˈpæʃn/", "trans": "passions, passionate", "col": "passion for music", "ex": "He has a great passion for music."},
    "passionate": {"def": "熱情的、激昂的、易怒的", "ipa": "/ˈpæʃənət/", "trans": "passionately", "col": "passionate speech", "ex": "She is a passionate teacher."},
    "passive": {"def": "被動的、消極的、服從的", "ipa": "/ˈpæsɪv/", "trans": "passively, passivity", "col": "passive smoking, passive voice", "ex": "He has a passive personality."},
    "passport": {"def": "護照、通行證、關鍵手段", "ipa": "/ˈpɑːspɔːt/", "trans": "passports", "col": "apply for a passport", "ex": "Don't forget your passport."},
    "password": {"def": "密碼、口令", "ipa": "/ˈpɑːswɜːd/", "trans": "passwords", "col": "forget password, secure password", "ex": "Enter your password to log in."},
    "past": {"def": "過去的、以前的、過往、在...之後", "ipa": "/pɑːst/", "trans": "passed (通過)", "col": "in the past, go past", "ex": "It's ten past nine."},
    "pasta": {"def": "義大利麵食", "ipa": "/ˈpæstə/", "trans": "無", "col": "cook pasta", "ex": "I like pasta with meat sauce."},
    "paste": {"def": "糊劑、漿糊、膏、貼上", "ipa": "/peɪst/", "trans": "pasted", "col": "toothpaste, tooth paste", "ex": "Copy and paste the text."},
    "pastel": {"def": "粉彩(畫/筆)、柔和色調", "ipa": "/ˈpæstl/", "trans": "pastels", "col": "pastel colors", "ex": "She preference pastel shades for her room."},
    "pasteurize/pasteurise": {"def": "以巴氏法消毒", "ipa": "/ˈpɑːstʃəraɪz/", "trans": "pasteurized", "col": "pasteurized milk", "ex": "The milk has been pasteurized."},
    "pastime": {"def": "消遣、娛樂", "ipa": "/ˈpɑːstaɪm/", "trans": "pastimes", "col": "favorite pastime", "ex": "Reading is her favorite pastime."},
    "pastor": {"def": "牧師", "ipa": "/ˈpɑːstə/", "trans": "pastors", "col": "congregational pastor", "ex": "The pastor gives a sermon every Sunday."},
    "pastoral": {"def": "田園式的、鄉村的、牧師的", "ipa": "/ˈpɑːstərəl/", "trans": "pastoralist", "col": "pastoral scene", "ex": "The painting depicts a pastoral landscape."},
    "pastry": {"def": "麵點、點心、酥皮", "ipa": "/ˈpeɪstri/", "trans": "pastries", "col": "flaky pastry", "ex": "She bought some pastries from the bakery."},
    "pasture": {"def": "牧場、草地", "ipa": "/ˈpɑːstʃə/", "trans": "pastures", "col": "green pasture", "ex": "The cows are grazing in the pasture."},
    "pat": {"def": "輕拍、適時的、正好地", "ipa": "/pæt/", "trans": "patted", "col": "pat on the back", "ex": "She gave me a pat on the back."},
    "patch": {"def": "補丁、斑點、小塊土地、修補", "ipa": "/pætʃ/", "trans": "patches, patched", "col": "patch up, nicotine patch", "ex": "He has a patch on his knee."},
    "patchy": {"def": "不勻稱的、零散的", "ipa": "/ˈpætʃi/", "trans": "patch (名詞)", "col": "patchy fog", "ex": "The information is still very patchy."},
    "patent": {"def": "專利、專利的、顯然的、獲得專利", "ipa": "/ˈpeɪtnt/", "trans": "patents, patented", "col": "file a patent", "ex": "He applied for a patent for his invention."},
    "paternal": {"def": "父親的、家長的、父系的", "ipa": "/pəˈtɜːnl/", "trans": "maternal (母親的)", "col": "paternal grandfather", "ex": "He showed paternal concern for his students."},
    "paternity": {"def": "父權、父系", "ipa": "/pəˈtɜːnəti/", "trans": "maternity", "col": "paternity test, paternity leave", "ex": "The court ordered a paternity test."},
    "path": {"def": "小徑、道路、軌跡", "ipa": "/pɑːθ/", "trans": "paths, pathway", "col": "career path, critical path", "ex": "Wait until the path is clear."},
    "pathology": {"def": "病理學、病變", "ipa": "/pəˈθɒlədʒi/", "trans": "pathological, pathologist", "col": "speech pathology", "ex": "He is a specialist in pathology."},
    "pathway": {"def": "路徑、途徑", "ipa": "/ˈpɑːθ weɪ/", "trans": "pathways", "col": "biochemical pathway", "ex": "The drug blocks a specific metabolic pathway."},
    "patience": {"def": "耐心、忍耐、毅力", "ipa": "/ˈpeɪʃns/", "trans": "patient (形容詞)", "col": "lose patience with, out of patience", "ex": "I ran out of patience."},
    "patient": {"def": "有耐心的、忍受的、病人", "ipa": "/ˈpeɪʃnt/", "trans": "patients, patiently", "col": "be patient with, out-patient", "ex": "Please be patient."},
    "patiently": {"def": "耐心地", "ipa": "/ˈpeɪʃntli/", "trans": "patient (形容詞)", "col": "wait patiently", "ex": "The customers waited patiently for the store to open."},
    "patio": {"def": "露台、天井", "ipa": "/ˈpætiəʊ/", "trans": "patios", "col": "patio furniture", "ex": "We had dinner on the patio."},
    "patriarch": {"def": "族長、元老、創始人", "ipa": "/ˈpeɪtriɑːk/", "trans": "patriarchs, patriarchy", "col": "Old Testament patriarch", "ex": "He was the patriarch of a large family."},
    "patriarchy": {"def": "父權制、家長治", "ipa": "/ˈpeɪtriɑːki/", "trans": "patriarchal", "col": "traditional patriarchy", "ex": "The society was a strict patriarchy."},
    "patriotic": {"def": "愛國的", "ipa": "/ˌpætriˈɒtɪk/", "trans": "patriotism", "col": "patriotic song", "ex": "He is a very patriotic person."},
    "patriotism": {"def": "愛國心", "ipa": "/ˈpætriətɪzəm/", "trans": "patriotic (形容詞)", "col": "spirit of patriotism", "ex": "They fought for the country out of patriotism."},
    "patrol": {"def": "巡邏、巡邏隊、巡防", "ipa": "/pəˈtrəʊl/", "trans": "patrolled", "col": "police patrol, on patrol", "ex": "The police are on patrol."},
    "patron": {"def": "資助人、主顧、守護神", "ipa": "/ˈpeɪtrən/", "trans": "patrons, patronage", "col": "patron of the arts", "ex": "He is a regular patron of the library."},
    "patronage": {"def": "資助、光顧、恩賜態度", "ipa": "/ˈpætənɪdʒ/", "trans": "patron (名詞)", "col": "corporate patronage", "ex": "The festival depends on local patronage."},
    "patter": {"def": "輕拍聲、喋喋不休、發出聲", "ipa": "/ˈpætə/", "trans": "pattered", "col": "patter of rain", "ex": "I can hear the patter of rain on the roof."},
    "pattern": {"def": "圖案、模式、樣式、模仿", "ipa": "/ˈpætən/", "trans": "patterns, patterned", "col": "behavior pattern, checked pattern", "ex": "The pattern of the fabric is beautiful."},
}

with open("batch_l1_p38.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART38, f, ensure_ascii=False, indent=2)
