import json

# Level 1 Part 59: (Sea - Segment)
L1_PART59 = {
    "sea": {"def": "海、海洋、大量", "ipa": "/siː/", "trans": "seafood, seagull, seaman", "col": "at sea, by sea", "ex": "The sea is calm today."},
    "seafood": {"def": "海鮮、海產", "ipa": "/ˈsiːfuːd/", "trans": "seafoods", "col": "fresh seafood", "ex": "This restaurant is famous for its seafood."},
    "seagull": {"def": "海鷗", "ipa": "/ˈsiːɡʌl/", "trans": "seagulls", "col": "flock of seagulls", "ex": "Seagulls are crying over the harbor."},
    "seal": {"def": "海豹、封條、印章、封上", "ipa": "/siːl/", "trans": "sealed", "col": "official seal, break the seal", "ex": "The letter was closed with a wax seal."},
    "seam": {"def": "縫、接縫、煤層、縫合", "ipa": "/siːm/", "trans": "seamless", "col": "bursting at the seams", "ex": "The seam of his jacket has come undone."},
    "seaman": {"def": "海員、水手", "ipa": "/ˈsiːmən/", "trans": "seamen", "col": "able seaman", "ex": "He spent most of his life as a seaman."},
    "seamless": {"def": "無縫的、完美的", "ipa": "/ˈsiːmləs/", "trans": "seamlessly", "col": "seamless integration", "ex": "The new system offers a seamless transition."},
    "seaport": {"def": "海港、港都", "ipa": "/ˈsiːpɔːt/", "trans": "seaports", "col": "busy seaport", "ex": "Singapore is one of the world's largest seaports."},
    "search": {"def": "搜尋、檢查、搜查", "ipa": "/sɜːtʃ/", "trans": "searched, searchlight", "col": "in search of, search for", "ex": "I'm searching for my keys."},
    "searchlight": {"def": "探照燈、搜索燈", "ipa": "/ˈsɜːtʃlaɪt/", "trans": "searchlights", "col": "beam of a searchlight", "ex": "The searchlight swept across the night sky."},
    "season": {"def": "季節、時期、季、調味", "ipa": "/ˈsiːzn/", "trans": "seasonal, seasoned", "col": "holiday season, peak season", "ex": "Autumn is my favorite season."},
    "seasonal": {"def": "季節性的", "ipa": "/ˈsiːzənl/", "trans": "season (名詞)", "col": "seasonal job, seasonal fruits", "ex": "The price varies due to seasonal changes."},
    "seat": {"def": "座位、所在地、底座", "ipa": "/siːt/", "trans": "seated", "col": "take a seat, window seat", "ex": "Please take a seat."},
    "seaweed": {"def": "海草、海藻", "ipa": "/ˈsiːwiːd/", "trans": "seaweeds", "col": "dried seaweed", "ex": "The beach was covered in seaweed."},
    "second": {"def": "第二、秒、支持、第二的", "ipa": "/ˈsekənd/", "trans": "secondly, secondary", "col": "second hand, wait a second", "ex": "He came second in the race."},
    "secondary": {"def": "次要的、中等的、第二位的", "ipa": "/ˈsekəndəri/", "trans": "secondary education", "col": "secondary school", "ex": "Safety is of secondary importance."},
    "seconder": {"def": "支持者、贊成者", "ipa": "/ˈsekəndə/", "trans": "second (動詞)", "col": "motion seconder", "ex": "Is there a seconder for this motion?"},
    "secondhand": {"def": "二手地、間接地、二手的", "ipa": "/ˌsekəndˈhænd/", "trans": "second hand", "col": "secondhand shop", "ex": "I bought this car secondhand."},
    "secondly": {"def": "第二、其次", "ipa": "/ˈsekəndli/", "trans": "second (形容詞)", "col": "firstly... secondly...", "ex": "Secondly, we need to consider the cost."},
    "secrecy": {"def": "秘密、保密、隱蔽", "ipa": "/ˈsiːkrəsi/", "trans": "secret (名詞/形容詞)", "col": "in secrecy", "ex": "The meeting was held in strict secrecy."},
    "secret": {"def": "秘密、秘訣、秘密的", "ipa": "/ˈsiːkrət/", "trans": "secretly, secretive, secretary", "col": "keep a secret, top secret", "ex": "I'll tell you a secret."},
    "secretary": {"def": "秘書、大臣、部長", "ipa": "/ˈsekrətri/", "trans": "secretarial", "col": "private secretary, Secretary of State", "ex": "His secretary manages his diary."},
    "secretive": {"def": "守口如瓶的、分泌的", "ipa": "/ˈsiːkrətɪv/", "trans": "secret (名詞)", "col": "secretive behavior", "ex": "He is very secretive about his past."},
    "secretly": {"def": "秘密地、私下地", "ipa": "/ˈsiːkrətli/", "trans": "secret (形容詞)", "col": "meet secretly", "ex": "They were secretly married."},
    "section": {"def": "部分、段落、部門", "ipa": "/ˈsekʃn/", "trans": "sections, sectional", "col": "cross section, sports section", "ex": "The book is divided into five sections."},
    "sector": {"def": "部門、扇形、扇面", "ipa": "/ˈsektə/", "trans": "sectors", "col": "public sector, private sector", "ex": "The manufacturing sector is growing."},
    "secular": {"def": "世俗的、現世的、百年一度的", "ipa": "/ˈsekjələ/", "trans": "secularism", "col": "secular society", "ex": "We live in a secular state."},
    "secure": {"def": "安全的、牢固的、確定、獲得", "ipa": "/sɪˈkjʊə/", "trans": "secured, securely, security", "col": "secure a future, feel secure", "ex": "Is the door secure?"},
    "securely": {"def": "安全地、牢固地、確實地", "ipa": "/sɪˈkjʊəli/", "trans": "secure (形容詞)", "col": "fasten securely", "ex": "The rope was securely tied."},
    "security": {"def": "安全、安全性、保證、證券", "ipa": "/sɪˈkjʊərəti/", "trans": "securities", "col": "national security, job security", "ex": "Security at the airport is very tight."},
    "sedan": {"def": "轎車、轎子", "ipa": "/sɪˈdæn/", "trans": "sedans", "col": "four door sedan", "ex": "They bought a new sedan."},
    "sedentary": {"def": "久坐的、定居的、不遷移的", "ipa": "/ˈsedntri/", "trans": "sedentariness", "col": "sedentary lifestyle", "ex": "He has a sedentary job."},
    "sediment": {"def": "沈澱物、沈積物", "ipa": "/ˈsedɪmənt/", "trans": "sedimentary", "col": "thick sediment", "ex": "A layer of sediment had settled at the bottom."},
    "sedimentary": {"def": "沈澱的、沈積成的", "ipa": "/ˌsedɪˈmentri/", "trans": "sediment (名詞)", "col": "sedimentary rock", "ex": "Sandstone is a type of sedimentary rock."},
    "see": {"def": "看見、領會、拜訪、理解", "ipa": "/siː/", "trans": "saw, seen, seeing, sight", "col": "see through, see off", "ex": "I can see the mountains from here."},
    "seed": {"def": "種子、種、原由、播種", "ipa": "/siːd/", "trans": "seedling, seedy", "col": "sow a seed, sunflower seed", "ex": "Birds eat the seeds of the plant."},
    "seedling": {"def": "幼苗、苗木", "ipa": "/ˈsiːdlɪŋ/", "trans": "seeds", "col": "vegetable seedling", "ex": "The seedlings need more water."},
    "seek": {"def": "尋找、追求、試圖、請求", "ipa": "/siːk/", "trans": "sought, seeker", "col": "seek help, seek advice", "ex": "They are seeking shelter from the rain."},
    "seem": {"def": "似乎、好像", "ipa": "/siːm/", "trans": "seemed, seeming", "col": "seem like", "ex": "It seems like a good idea."},
    "seemingly": {"def": "表面上、看似", "ipa": "/ˈsiːmɪŋli/", "trans": "seem (動詞)", "col": "seemingly endless", "ex": "The task was seemingly impossible."},
    "segment": {"def": "段、部分、切面、分割", "ipa": "/ˈseɡmənt/", "trans": "segmented, segmentation", "col": "market segment", "ex": "She cut the orange into segments."},
}

with open("batch_l1_p59.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART59, f, ensure_ascii=False, indent=2)
