import json

# Level 1 Part 9: (Commit - Council)
L1_PART9 = {
    "commit": {"def": "承諾、犯錯、委託", "ipa": "/kəˈmɪt/", "trans": "committed, commitment", "col": "commit a crime, commit to", "ex": "He committed a serious mistake."},
    "commitment": {"def": "承諾、奉獻", "ipa": "/kəˈmɪtmənt/", "trans": "commit (動詞)", "col": "make a commitment", "ex": "I have a lot of work commitments."},
    "committee": {"def": "委員會", "ipa": "/kəˈmɪti/", "trans": "committees", "col": "standing committee", "ex": "The committee will meet next week."},
    "common": {"def": "常見的、共同的", "ipa": "/ˈkɒmən/", "trans": "commonly", "col": "common sense, in common", "ex": "Jackson is a very common name."},
    "commonly": {"def": "通常地、一般地", "ipa": "/ˈkɒmənli/", "trans": "common (形容詞)", "col": "commonly known as", "ex": "This plant is commonly found in Asia."},
    "communicate": {"def": "溝通、傳達", "ipa": "/kəˈmjuːnɪkeɪt/", "trans": "communication (名詞)", "col": "communicate with each other", "ex": "They communicate by email."},
    "communication": {"def": "溝通、通訊", "ipa": "/kəˌmjuːnɪˈkeɪʃn/", "trans": "communicate (動詞)", "col": "means of communication", "ex": "Radio is a form of communication."},
    "communist": {"def": "共產主義者、共產主義的", "ipa": "/ˈkɒmjənɪst/", "trans": "communism", "col": "communist party", "ex": "He is a member of the communist party."},
    "community": {"def": "社區、社群", "ipa": "/kəˈmjuːnəti/", "trans": "communities", "col": "local community", "ex": "She is well-known in the local community."},
    "companion": {"def": "同伴、伴侶", "ipa": "/kəmˈpæniən/", "trans": "companions", "col": "travel companion", "ex": "He is a faithful companion to me."},
    "company": {"def": "公司、陪伴", "ipa": "/ˈkʌmpəni/", "trans": "companies", "col": "insurance company, keep company", "ex": "Which company do you work for?"},
    "comparable": {"def": "可比擬的", "ipa": "/ˈkɒmpərəbl/", "trans": "compare (動詞)", "col": "be comparable to", "ex": "The two situations are not comparable."},
    "comparative": {"def": "比較的、相對的", "ipa": "/kəmˈpærətɪv/", "trans": "comparatively", "col": "comparative study", "ex": "He is a comparative newcomer to the field."},
    "comparatively": {"def": "比較地、相當地", "ipa": "/kəmˈpærətɪvli/", "trans": "comparative (形容詞)", "col": "comparatively easy", "ex": "The exam was comparatively easy."},
    "compare": {"def": "比較、對比", "ipa": "/kəmˈpeə/", "trans": "comparison (名詞), comparable (形容詞)", "col": "compare A with B", "ex": "Compare your answers with mine."},
    "comparison": {"def": "比較、對照", "ipa": "/kəmˈpærɪsn/", "trans": "compare (動詞)", "col": "in comparison with", "ex": "By comparison, the new system is much better."},
    "compass": {"def": "指南針、圓規", "ipa": "/ˈkʌmpəs/", "trans": "compasses", "col": "magnetic compass", "ex": "He used a compass to find his way."},
    "compassion": {"def": "同情心、憐憫", "ipa": "/kəmˈpæʃn/", "trans": "compassionate (同情心的)", "col": "feel compassion for", "ex": "She had great compassion for the poor."},
    "compassionate": {"def": "有同情心的", "ipa": "/kəmˈpæʃənət/", "trans": "compassion (名詞)", "col": "compassionate leave", "ex": "He is a very compassionate person."},
    "compel": {"def": "強迫、驅使", "ipa": "/kəmˈpel/", "trans": "compelled, compelling", "col": "compel someone to do", "ex": "Hunger compelled him to steal."},
    "compete": {"def": "競爭、比賽", "ipa": "/kəmˈpiːt/", "trans": "competition (名詞), competitor (競爭者)", "col": "compete with/against", "ex": "They are competing for the prize."},
    "competent": {"def": "稱職的、勝任的", "ipa": "/ˈkɒmpɪtənt/", "trans": "competence (能力)", "col": "competent teacher", "ex": "He is a very competent manager."},
    "competition": {"def": "競爭、比賽", "ipa": "/ˌkɒmpəˈtɪʃn/", "trans": "compete (動詞)", "col": "music competition", "ex": "She won the swimming competition."},
    "competitive": {"def": "競爭的、具競爭力的", "ipa": "/kəmˈpetətɪv/", "trans": "competitively", "col": "competitive market", "ex": "He has a very competitive personality."},
    "competitor": {"def": "競爭者、對手", "ipa": "/kəmˈpetɪtə/", "trans": "competitors", "col": "serious competitor", "ex": "Our main competitor is a German company."},
    "complain": {"def": "抱怨、投訴", "ipa": "/kəmˈpleɪn/", "trans": "complaint (名詞)", "col": "complain about", "ex": "He is always complaining about the weather."},
    "complaint": {"def": "抱怨、投訴", "ipa": "/kəmˈpleɪnt/", "trans": "complain (動詞)", "col": "make a complaint", "ex": "The manager ignored my complaint."},
    "complete": {"def": "完全的、完成", "ipa": "/kəmˈpliːt/", "trans": "completely, completion", "col": "a complete success", "ex": "I have completed my homework."},
    "completely": {"def": "完全地", "ipa": "/kəmˈpliːtli/", "trans": "complete (形容詞)", "col": "completely different", "ex": "I completely forgot about the meeting."},
    "completion": {"def": "完成", "ipa": "/kəmˈpliːʃn/", "trans": "complete (動詞)", "col": "near completion", "ex": "The building is nearing completion."},
    "complex": {"def": "複雜的、建築群", "ipa": "/ˈkɒmpleks/", "trans": "complexity (複雜性)", "col": "industrial complex", "ex": "It's a very complex problem."},
    "complexity": {"def": "複雜、複雜性", "ipa": "/kəmˈpleksəti/", "trans": "complex (形容詞)", "col": "added complexity", "ex": "The complexity of the task was surprising."},
    "compliment": {"def": "稱讚、恭維", "ipa": "/ˈkɒmplɪmənt/", "trans": "complimentary", "col": "pay a compliment", "ex": "Thank you for the compliment."},
    "component": {"def": "組件、成分", "ipa": "/kəmˈpəʊnənt/", "trans": "components", "col": "essential component", "ex": "Nitrogen is a component of air."},
    "compose": {"def": "組成、創作、作曲", "ipa": "/kəmˈpəʊz/", "trans": "composition (作品/組成)", "col": "compose a song", "ex": "English is composed of many words."},
    "composer": {"def": "作曲家", "ipa": "/kəmˈpəʊzə/", "trans": "composers", "col": "famous composer", "ex": "Beethoven was a great composer."},
    "composition": {"def": "組成、成分、作品", "ipa": "/ˌkɒmpəˈzɪʃn/", "trans": "composers", "col": "chemical composition", "ex": "What is the composition of this metal?"},
    "comprehensive": {"def": "全面的、廣泛的", "ipa": "/ˌkɒmprɪˈhensɪv/", "trans": "comprehend (理解)", "col": "comprehensive study", "ex": "You need a comprehensive list of all parts."},
    "comprise": {"def": "由此組成、包含", "ipa": "/kəmˈpraɪz/", "trans": "comprised", "col": "comprise of", "ex": "The committee comprises ten members."},
    "compromise": {"def": "妥協、讓步", "ipa": "/ˈkɒmprəmaɪz/", "trans": "compromised", "col": "reach a compromise", "ex": "We finally reached a compromise."},
    "computer": {"def": "電腦", "ipa": "/kəmˈpjuːtə/", "trans": "computers", "col": "personal computer", "ex": "I use a computer for my work."},
    "conceal": {"def": "隱藏、瞞", "ipa": "/kənˈsiːl/", "trans": "concealed", "col": "conceal the truth", "ex": "He tried to conceal his feelings."},
    "concentrate": {"def": "集中、濃縮", "ipa": "/ˈkɒnsntreɪt/", "trans": "concentration (名詞)", "col": "concentrate on", "ex": "I need to concentrate on my study."},
    "concentration": {"def": "集中、專注、濃度", "ipa": "/ˌkɒnsnˈtreɪʃn/", "trans": "concentrate (動詞)", "col": "lose concentration", "ex": "He lost his concentration and made a mistake."},
    "concept": {"def": "概念、觀念", "ipa": "/ˈkɒnsept/", "trans": "conceptual", "col": "new concept", "ex": "This is a very simple concept to understand."},
    "concern": {"def": "關心、憂慮", "ipa": "/kənˈsɜːn/", "trans": "concerned, concerning", "col": "environmental concern", "ex": "Your health is my main concern."},
    "concerned": {"def": "關心的、擔憂的", "ipa": "/kənˈsɜːnd/", "trans": "concern (名詞)", "col": "be concerned about", "ex": "He is concerned about his future."},
    "concert": {"def": "音樂會、演唱會", "ipa": "/ˈkɒnsət/", "trans": "concerts", "col": "live concert", "ex": "We are going to a jazz concert tonight."},
    "conclude": {"def": "下結論、結束", "ipa": "/kənˈkluːd/", "trans": "conclusion (結論)", "col": "conclude that", "ex": "The jury concluded that he was guilty."},
    "conclusion": {"def": "結論、結束", "ipa": "/kənˈkluːʒn/", "trans": "conclude (動詞)", "col": "draw a conclusion", "ex": "I reached the same conclusion as you."},
    "concrete": {"def": "混凝土、具體的", "ipa": "/ˈkɒŋkriːt/", "trans": "無", "col": "reinforced concrete", "ex": "The wall is made of concrete."},
    "condition": {"def": "狀況、條件、環境", "ipa": "/kənˈdɪʃn/", "trans": "conditional (有條件的)", "col": "living conditions, weather conditions", "ex": "The car is in excellent condition."},
    "conductor": {"def": "指揮、導體、列車員", "ipa": "/kənˈdʌktə/", "trans": "conductors", "col": "orchestra conductor", "ex": "The conductor raised his baton."},
    "cone": {"def": "圓錐體、甜筒", "ipa": "/kəʊn/", "trans": "cones", "col": "ice cream cone", "ex": "The mountain peak is a perfect cone."},
    "conference": {"def": "會議、研討會", "ipa": "/ˈkɒnfərəns/", "trans": "conferences", "col": "press conference", "ex": "The international conference was a success."},
    "confess": {"def": "承認、懺悔", "ipa": "/kənˈfes/", "trans": "confession (名詞)", "col": "confess to a crime", "ex": "He confessed that he had stolen the money."},
    "confession": {"def": "坦白、承認", "ipa": "/kənˈfeʃn/", "trans": "confess (動詞)", "col": "make a confession", "ex": "Her confession was published in the newspaper."},
    "confidence": {"def": "信心、自信", "ipa": "/ˈkɒnfɪdəns/", "trans": "confident (有自信的)", "col": "self-confidence", "ex": "He has a lot of confidence in his abilities."},
    "confident": {"def": "有自信的", "ipa": "/ˈkɒnfɪdənt/", "trans": "confidently", "col": "be confident of", "ex": "She is confident that she will pass the exam."},
    "confidential": {"def": "機密的", "ipa": "/ˌkɒnfɪˈdenʃl/", "trans": "confidentially", "col": "confidential information", "ex": "These documents are strictly confidential."},
    "confine": {"def": "限制、監禁", "ipa": "/kənˈfaɪn/", "trans": "confined, confinement", "col": "confine someone to", "ex": "A fever confined him to his bed."},
    "confirm": {"def": "確認、確證", "ipa": "/kənˈfɜːm/", "trans": "confirmation (名詞)", "col": "confirm a booking", "ex": "Can you confirm your arrival time?"},
    "conflict": {"def": "衝突、鬥爭", "ipa": "/ˈkɒnflɪkt/", "trans": "conflicts", "col": "armed conflict, conflict of interest", "ex": "They are trying to avoid a direct conflict."},
    "confront": {"def": "面臨、對質", "ipa": "/kənˈfrʌnt/", "trans": "confrontation (名詞)", "col": "confront the truth", "ex": "We must confront the problem head-on."},
    "confrontation": {"def": "對質、衝突", "ipa": "/ˌkɒnfrʌnˈteɪʃn/", "trans": "confront (動詞)", "col": "violent confrontation", "ex": "The confrontation ended in a fight."},
    "confuse": {"def": "使困惑、混淆", "ipa": "/kənˈfjuːz/", "trans": "confused, confusing, confusion", "col": "confuse A with B", "ex": "People often confuse me with my brother."},
    "confused": {"def": "感到困惑的", "ipa": "/kənˈfjuːzd/", "trans": "confuse (動詞)", "col": "look confused", "ex": "I am a bit confused by your instructions."},
    "confusing": {"def": "令人困惑的", "ipa": "/kənˈfjuːzɪŋ/", "trans": "confusingly", "col": "confusing situation", "ex": "The map was very confusing."},
    "confusion": {"def": "困惑、混亂", "ipa": "/kənˈfjuːʒn/", "trans": "confuse (動詞)", "col": "cause confusion", "ex": "The new rules caused a lot of confusion."},
    "congratulate": {"def": "恭喜", "ipa": "/kənˈɡrætʃuleɪt/", "trans": "congratulation (名詞)", "col": "congratulate someone on", "ex": "I congratulated her on her success."},
    "congratulation": {"def": "祝賀", "ipa": "/kənˌɡrætʃuˈleɪʃn/", "trans": "congratulate (動詞)", "col": "congratulations!", "ex": "Please accept my warmest congratulations."},
    "congress": {"def": "代表大會、國會", "ipa": "/ˈkɒŋɡres/", "trans": "congressional", "col": "National Congress", "ex": "He was elected to Congress last year."},
    "conjunction": {"def": "連接詞、連結", "ipa": "/kənˈdʒʌŋkʃn/", "trans": "conjunctions", "col": "in conjunction with", "ex": "'And' is a common conjunction."},
    "connect": {"def": "連接、聯絡", "ipa": "/kəˈnekt/", "trans": "connection (名詞)", "col": "connect to the internet", "ex": "The printer is connected to the computer."},
    "connection": {"def": "連接、關聯", "ipa": "/kəˈnekʃn/", "trans": "connect (動詞)", "col": "strong connection", "ex": "There's a connection between smoking and cancer."},
    "conquer": {"def": "征服、戰勝", "ipa": "/ˈkɒŋkə/", "trans": "conquered, conqueror", "col": "conquer fear", "ex": "The army conquered the city in two days."},
    "conscience": {"def": "良心", "ipa": "/ˈkɒnʃəns/", "trans": "conscientious (有良心的)", "col": "guilty conscience", "ex": "He has a clear conscience."},
    "conscious": {"def": "意識到的、神志清醒的", "ipa": "/ˈkɒnʃəs/", "trans": "consciousness (名詞)", "col": "be conscious of", "ex": "She was conscious during the entire surgery."},
    "consciousness": {"def": "意識、神志", "ipa": "/ˈkɒnʃəsnəs/", "trans": "conscious (形容詞)", "col": "lose consciousness", "ex": "He lost consciousness after the accident."},
    "consecutive": {"def": "連續的", "ipa": "/kənˈsekjətɪv/", "trans": "consecutively", "col": "consecutive days", "ex": "It has rained for three consecutive days."},
    "consensus": {"def": "共識、輿論", "ipa": "/kənˈsensəs/", "trans": "無", "col": "general consensus", "ex": "They reached a consensus on the matter."},
    "consequence": {"def": "結果、後果", "ipa": "/ˈkɒnsɪkwəns/", "trans": "consequent", "col": "serious consequence", "ex": "Accept the consequences of your actions."},
    "consequent": {"def": "隨之發生的", "ipa": "/ˈkɒnsɪkwənt/", "trans": "consequently", "col": "consequent increase", "ex": "the war and the consequent poverty"},
    "consequently": {"def": "因此", "ipa": "/ˈkɒnsɪkwəntli/", "trans": "consequent (形容詞)", "col": "consequently, therefore", "ex": "She forgot the key; consequently, she was locked out."},
    "conservation": {"def": "保育、保存", "ipa": "/ˌkɒnsəˈveɪʃn/", "trans": "conserve (動詞)", "col": "water conservation", "ex": "Wildlife conservation is very important."},
    "conservative": {"def": "保守的、保守派的人", "ipa": "/kənˈsɜːvətɪv/", "trans": "conservatively", "col": "conservative view", "ex": "He has a very conservative attitude toward change."},
    "conserve": {"def": "保存、節約", "ipa": "/kənˈsɜːv/", "trans": "conservation (名詞)", "col": "conserve energy", "ex": "We should conserve our natural resources."},
    "consider": {"def": "考慮、認為", "ipa": "/kənˈsɪdə/", "trans": "consideration (名詞), considerable (相當大的)", "col": "consider doing", "ex": "Please consider my suggestion."},
    "considerable": {"def": "相當大的、值得考慮的", "ipa": "/kənˈsɪdərəbl/", "trans": "considerably", "col": "considerable amount", "ex": "the project required considerable time and effort."},
    "considerably": {"def": "相當地、大大地", "ipa": "/kənˈsɪdərəbli/", "trans": "considerable (形容詞)", "col": "considerably better", "ex": "The quality of life has improved considerably."},
    "considerate": {"def": "體貼的", "ipa": "/kənˈsɪdərət/", "trans": "consideration (名詞)", "col": "be considerate to", "ex": "It was very considerate of you to bring flowers."},
    "consideration": {"def": "考慮、體貼", "ipa": "/kənˌsɪdəˈreɪʃn/", "trans": "consider (動詞)", "col": "take into consideration", "ex": "You must take all factors into consideration."},
    "consist": {"def": "由...組成、在於", "ipa": "/kənˈsɪst/", "trans": "consistent (一致的)", "col": "consist of", "ex": "The team consists of ten players."},
    "consistent": {"def": "一致的、穩定的", "ipa": "/kənˈsɪstənt/", "trans": "consistently, consistency", "col": "consistent performance", "ex": "He is very consistent in his beliefs."},
    "consonant": {"def": "子音", "ipa": "/ˈkɒnsənənt/", "trans": "consonants", "col": "vowel and consonant", "ex": "'B' is a consonant."},
    "constant": {"def": "常數、不變的、持續的", "ipa": "/ˈkɒnstənt/", "trans": "constantly", "col": "constant noise", "ex": "He is in constant pain."},
    "constantly": {"def": "不斷地、經常地", "ipa": "/ˈkɒnstəntli/", "trans": "constant (形容詞)", "col": "constantly changing", "ex": "The world is constantly changing."},
    "constitute": {"def": "構成、組成", "ipa": "/ˈkɒnstɪtjuːt/", "trans": "constitution (憲法/組成)", "col": "constitute a threat", "ex": "The 12 members constitute the board."},
    "constitution": {"def": "憲法、體質、組成", "ipa": "/ˌkɒnstɪˈtjuːʃn/", "trans": "constitutional (憲法的)", "col": "written constitution", "ex": "Japan has a peace constitution."},
    "construct": {"def": "建造、構造", "ipa": "/kənˈstrʌkt/", "trans": "construction (建築)", "col": "construct a building", "ex": "They are constructing a new bridge."},
    "construction": {"def": "建築、建設", "ipa": "/kənˈstrʌkʃn/", "trans": "construct (動詞)", "col": "under construction", "ex": "The road is under construction."},
    "consult": {"def": "諮詢、商議", "ipa": "/kənˈsʌlt/", "trans": "consultant (顧問)", "col": "consult a doctor", "ex": "You should consult your lawyer."},
    "consultant": {"def": "顧問", "ipa": "/kənˈsʌltənt/", "trans": "consultants", "col": "management consultant", "ex": "He works as a technical consultant."},
    "consume": {"def": "消耗、消費、吃/喝", "ipa": "/kənˈsjuːm/", "trans": "consumer (消費者), consumption (名詞)", "col": "consume energy", "ex": "Our car consumes a lot of fuel."},
    "consumer": {"def": "消費者", "ipa": "/kənˈsjuːmə/", "trans": "consumers", "col": "consumer price index", "ex": "Consumers are demanding better services."},
    "consumption": {"def": "消耗量、消費", "ipa": "/kənˈsʌmpʃn/", "trans": "consume (動詞)", "col": "power consumption", "ex": "The consumption of sugar has increased."},
    "contact": {"def": "接觸、聯絡", "ipa": "/ˈkɒntækt/", "trans": "contacted", "col": "eye contact, keep in contact", "ex": "I am in contact with my old friends."},
    "contain": {"def": "包含、含有、遏制", "ipa": "/kənˈteɪn/", "trans": "container (容器), content (內容)", "col": "contain sugar", "ex": "These fruits contain a lot of juice."},
    "container": {"def": "容器、集裝箱", "ipa": "/kənˈteɪnə/", "trans": "containers", "col": "shipping container", "ex": "Store the food in an airtight container."},
    "contemporary": {"def": "同時代的、現代的", "ipa": "/kənˈtemprəri/", "trans": "contemporaries", "col": "contemporary art", "ex": "She loves contemporary dance."},
    "contempt": {"def": "輕蔑、藐視", "ipa": "/kənˈtempt/", "trans": "contemptuous (輕蔑的)", "col": "show contempt for", "ex": "He has a deep contempt for his rivals."},
    "content": {"def": "內容、目錄、滿意的", "ipa": "/ˈkɒntent/", "trans": "contentment (滿足)", "col": "content of the book, be content with", "ex": "I am content with my current life."},
    "contest": {"def": "競賽、爭奪", "ipa": "/ˈkɒntest/", "trans": "contested, contestant (參賽者)", "col": "beauty contest", "ex": "He entered a speech contest."},
    "contestant": {"def": "參賽者", "ipa": "/kənˈtestənt/", "trans": "contestants", "col": "lucky contestant", "ex": "The contestant answered the final question."},
    "context": {"def": "上下文、背景", "ipa": "/ˈkɒntekst/", "trans": "contexts", "col": "in this context", "ex": "You must understand the word in its context."},
    "continent": {"def": "大陸、洲", "ipa": "/ˈkɒntɪnənt/", "trans": "continents", "col": "seven continents", "ex": "Africa is a large continent."},
    "continual": {"def": "持續的、不間斷的", "ipa": "/kənˈtɪnjuəl/", "trans": "continually", "col": "continual noise", "ex": "They suffered from continual noise problems."},
    "continue": {"def": "繼續", "ipa": "/kənˈtɪnjuː/", "trans": "continued, continuous", "col": "continue to run", "ex": "Let's continue our lesson."},
    "continuous": {"def": "連續的、不斷的", "ipa": "/kənˈtɪnjuəs/", "trans": "continuously", "col": "continuous rain", "ex": "The rain was continuous for three days."},
    "contract": {"def": "合約、縮小", "ipa": "/ˈkɒntrækt/", "trans": "contractor (承包商)", "col": "sign a contract", "ex": "They signed a three-year contract."},
    "contradict": {"def": "矛盾、反駁", "ipa": "/ˌkɒntrəˈdɪkt/", "trans": "contradiction (名詞)", "col": "contradict oneself", "ex": "His account of the event contradicted hers."},
    "contradiction": {"def": "矛盾、反駁", "ipa": "/ˌkɒntrəˈdɪkʃn/", "trans": "contradict (動詞)", "col": "obvious contradiction", "ex": "There is a contradiction between his words and actions."},
    "contrary": {"def": "相反的、對立面", "ipa": "/ˈkɒntrəri/", "trans": "無", "col": "on the contrary, contrary to", "ex": "Contrary to expectations, he failed."},
    "contrast": {"def": "對比、差異", "ipa": "/ˈkɒntrɑːst/", "trans": "contrasted", "col": "in contrast with", "ex": "There's a sharp contrast between the two cities."},
    "contribute": {"def": "貢獻、投稿、助長", "ipa": "/kənˈtrɪbjuːt/", "trans": "contribution (名詞), contributor (貢獻者)", "col": "contribute to", "ex": "Everyone can contribute to local charities."},
    "contribution": {"def": "貢獻、捐款", "ipa": "/ˌkɒntrɪˈbjuːʃn/", "trans": "contribute (動詞)", "col": "make a contribution", "ex": "His contribution to science was enormous."},
    "control": {"def": "控制", "ipa": "/kənˈtrəʊl/", "trans": "controlled, controlling", "col": "remote control, out of control", "ex": "He lost control of the car."},
    "controversial": {"def": "具爭議性的", "ipa": "/ˌkɒntrəˈvɜːʃl/", "trans": "controversy (名詞)", "col": "controversial issue", "ex": "The new policy is highly controversial."},
    "controversy": {"def": "爭議、辯論", "ipa": "/ˈkɒntrəvɜːsi/", "trans": "controversies", "col": "cause controversy", "ex": "The decision provoked a lot of controversy."},
    "convenience": {"def": "方便、便利設施", "ipa": "/kənˈviːniəns/", "trans": "convenient (方便的)", "col": "convenience store", "ex": "I like the convenience of living near a station."},
    "convenient": {"def": "方便的", "ipa": "/kənˈviːniənt/", "trans": "conveniently", "col": "convenient for you", "ex": "Is it convenient for me to call you tonight?"},
    "convention": {"def": "慣例、大會、公約", "ipa": "/kənˈvenʃn/", "trans": "conventional (傳統的)", "col": "international convention", "ex": "The group held its annual convention in Tokyo."},
    "conventional": {"def": "傳統的、常規的", "ipa": "/kənˈvenʃənl/", "trans": "convention (名詞)", "col": "conventional medicine", "ex": "We had a conventional wedding."},
    "conversation": {"def": "交談、談話", "ipa": "/ˌkɒnvəˈseɪʃn/", "trans": "conversations", "col": "have a conversation", "ex": "They were deep in conversation."},
    "convey": {"def": "傳達、運送", "ipa": "/kənˈveɪ/", "trans": "conveyed", "col": "convey a message", "ex": "I can't convey my feelings in words."},
    "convince": {"def": "說服、使相信", "ipa": "/kənˈvɪns/", "trans": "convinced, convincing", "col": "convince someone of", "ex": "I tried to convince him that I was right."},
    "convincing": {"def": "具說服力的", "ipa": "/kənˈvɪnsɪŋ/", "trans": "convince (動詞)", "col": "convincing evidence", "ex": "He gave a very convincing explanation."},
    "cook": {"def": "烹飪、廚師", "ipa": "/kʊk/", "trans": "cooked, cooker (爐灶)", "col": "home-cooked", "ex": "She is a very good cook."},
    "cookie/cooky": {"def": "餅乾", "ipa": "/ˈkʊki/", "trans": "cookies", "col": "chocolate chip cookie", "ex": "I ate a few cookies with my milk."},
    "cool": {"def": "涼爽的、酷的、冷靜的", "ipa": "/kuːl/", "trans": "coolly, coolness", "col": "keep cool", "ex": "The weather is nice and cool today."},
    "cooperate": {"def": "合作", "ipa": "/kəʊˈɒpəreɪt/", "trans": "cooperation (名詞)", "col": "cooperate with", "ex": "The two countries cooperated on the project."},
    "cooperation": {"def": "合作、協作", "ipa": "/kəʊˌɒpəˈreɪʃn/", "trans": "cooperate (動詞)", "col": "international cooperation", "ex": "Thank you for your cooperation."},
    "cooperative": {"def": "合作的、協作的", "ipa": "/kəʊˈɒpərətɪv/", "trans": "cooperatives", "col": "cooperative effort", "ex": "They are a very cooperative team."},
    "coordinate": {"def": "協調、坐標", "ipa": "/kəʊˈɔːdɪneɪt/", "trans": "coordination (名詞)", "col": "coordinate activities", "ex": "We need to coordinate our efforts."},
    "cope": {"def": "應付、處理", "ipa": "/kəʊp/", "trans": "coped", "col": "cope with", "ex": "It's difficult to cope with such pressure."},
    "copper": {"def": "銅、紫銅", "ipa": "/ˈkɒpə/", "trans": "無", "col": "copper wire", "ex": "The pipes are made of copper."},
    "copy": {"def": "複製、副本", "ipa": "/ˈkɒpi/", "trans": "copies", "col": "hard copy, photocopier", "ex": "Make a copy of this important file."},
    "cord": {"def": "細繩、線、絕緣線", "ipa": "/kɔːd/", "trans": "cords", "col": "power cord, vocal cords", "ex": "He tied the box with a strong cord."},
    "core": {"def": "核心、果核", "ipa": "/kɔː/", "trans": "cores", "col": "apple core, core value", "ex": "the core of the problem"},
    "cork": {"def": "軟木塞", "ipa": "/kɔːk/", "trans": "corks", "col": "cork screw", "ex": "He pulled the cork out of the wine bottle."},
    "corn": {"def": "玉米、穀物", "ipa": "/kɔːn/", "trans": "無 (不可數)", "col": "sweet corn, corn field", "ex": "He likes to eat boiled corn."},
    "corner": {"def": "角落、轉角", "ipa": "/ˈkɔːnə/", "trans": "corners", "col": "around the corner", "ex": "I'll meet you at the street corner."},
    "corporate": {"def": "公司的、法人的、共同的", "ipa": "/ˈkɔːpərət/", "trans": "corporation", "col": "corporate identity", "ex": "The company has a strong corporate culture."},
    "corporation": {"def": "法人、大型公司", "ipa": "/ˌkɔːpəˈreɪʃn/", "trans": "corporations", "col": "multinational corporation", "ex": "She works for a large corporation in NY."},
    "correct": {"def": "正確的、糾正", "ipa": "/kəˈrekt/", "trans": "incorrect, correction", "col": "correct answer", "ex": "Is my answer correct?"},
    "correction": {"def": "糾正、修正", "ipa": "/kəˈrekʃn/", "trans": "correct (動詞)", "col": "make corrections", "ex": "I made some corrections to my essay."},
    "correspond": {"def": "符合、一致、通信", "ipa": "/ˌkɒrəˈspɒnd/", "trans": "correspondence (名詞)", "col": "correspond with", "ex": "Her actions do not correspond with her words."},
    "correspondence": {"def": "通信、一致", "ipa": "/ˌkɒrəˈspɒndəns/", "trans": "correspond (動詞)", "col": "private correspondence", "ex": "I have been in correspondence with him."},
    "corridor": {"def": "走廊", "ipa": "/ˈkɒrɪdɔː/", "trans": "corridors", "col": "long corridor", "ex": "My office is down the corridor on the left."},
    "corrupt": {"def": "腐敗的、墮落的", "ipa": "/kəˈrʌpt/", "trans": "corruption (名詞)", "col": "corrupt official", "ex": "Power corrupts and absolute power corrupts absolutely."},
    "corruption": {"def": "腐敗、賄賂", "ipa": "/kəˈrʌpʃn/", "trans": "corrupt (形容詞)", "col": "political corruption", "ex": "The government is fighting against corruption."},
    "cost": {"def": "成本、代價、價值", "ipa": "/kɒst/", "trans": "costly (昂貴的)", "col": "at all costs, living cost", "ex": "The car cost him a lot of money."},
    "costly": {"def": "昂貴的", "ipa": "/ˈkɒstli/", "trans": "cost (名詞/動詞)", "col": "costly mistake", "ex": "The error proved very costly for the company."},
    "costume": {"def": "服裝、戲服、裝束", "ipa": "/ˈkɒstjuːm/", "trans": "costumes", "col": "fancy dress costume", "ex": "The actors are all in period costume."},
    "cottage": {"def": "小屋、村舍", "ipa": "/ˈkɒtɪdʒ/", "trans": "cottages", "col": "country cottage", "ex": "They live in a beautiful little cottage."},
    "cotton": {"def": "棉花、棉布", "ipa": "/ˈkɒtn/", "trans": "無", "col": "cotton shirt", "ex": "This shirt is made of pure cotton."},
    "couch": {"def": "沙發", "ipa": "/kaʊtʃ/", "trans": "couches", "col": "couch potato", "ex": "They are sitting on the couch watching TV."},
    "cough": {"def": "咳嗽", "ipa": "/kɒf/", "trans": "coughed", "col": "cough up, a bad cough", "ex": "I have a bad cough today."},
    "could": {"def": "能 (can 過去式)", "ipa": "/kəd/", "trans": "無", "col": "could you please...", "ex": "Could you help me with this?"},
    "council": {"def": "理事會、議會", "ipa": "/ˈkaʊnsl/", "trans": "councils", "col": "city council", "ex": "The local council is building new parks."},
}

with open("batch_l1_p9.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART9, f, ensure_ascii=False, indent=2)
