import json

# Level 1 Part 19: (Fundamentally - Glide)
L1_PART19 = {
    "fundamentally": {"def": "根本地、從基本來說", "ipa": "/ˌfʌndəˈmentəli/", "trans": "fundamental (形容詞)", "col": "fundamentally different", "ex": "The two systems are fundamentally different."},
    "funeral": {"def": "葬禮、出殯", "ipa": "/ˈfjuːnərəl/", "trans": "funerals", "col": "attend a funeral", "ex": "He attended his friend's funeral."},
    "funny": {"def": "好笑的、奇怪的", "ipa": "/ˈfʌni/", "trans": "funnie, funniest", "col": "funny story", "ex": "That's a very funny joke."},
    "fur": {"def": "毛皮、皮草", "ipa": "/fɜː/", "trans": "furs", "col": "fur coat", "ex": "The rabbit has soft fur."},
    "furious": {"def": "狂怒的、猛烈的", "ipa": "/ˈfjʊəriəs/", "trans": "furiously", "col": "be furious with", "ex": "He was furious with me for being late."},
    "furnace": {"def": "爐子、熔爐", "ipa": "/ˈfɜːnɪs/", "trans": "furnaces", "col": "blast furnace", "ex": "The iron was melted in a furnace."},
    "furnish": {"def": "提供、裝修(傢俱)", "ipa": "/ˈfɜːnɪʃ/", "trans": "furnished", "col": "fully furnished", "ex": "We need to furnish the new apartment."},
    "furniture": {"def": "傢俱", "ipa": "/ˈfɜːnɪtʃə/", "trans": "無 (不可數)", "col": "piece of furniture, office furniture", "ex": "I bought some new furniture for the living room."},
    "further": {"def": "更遠地、進一步的", "ipa": "/ˈfɜːðə/", "trans": "far (遠的)", "col": "further information, until further notice", "ex": "For further information, please call us."},
    "furthermore": {"def": "此外、而且", "ipa": "/ˌfɜːðəˈmɔː/", "trans": "無", "col": "furthermore, moreover", "ex": "Further more, it's very expensive."},
    "fury": {"def": "狂怒、猛烈、暴怒", "ipa": "/ˈfjʊəri/", "trans": "furiously", "col": "shout in fury", "ex": "She was shaking with fury."},
    "fuse": {"def": "保險絲、引信、融合", "ipa": "/fjuːz/", "trans": "fused, fusion", "col": "blow a fuse", "ex": "The lights went out because a fuse had blown."},
    "fusion": {"def": "熔化、融合、聚合", "ipa": "/ˈfjuːʒn/", "trans": "fuse (動詞)", "col": "nuclear fusion", "ex": "The restaurant serves fusion cuisine."},
    "fuss": {"def": "忙亂、小題大作", "ipa": "/fʌs/", "trans": "fussy", "col": "make a fuss about", "ex": "Don't make a fuss about nothing."},
    "fussy": {"def": "愛挑剔的、過份裝飾的", "ipa": "/ˈfʌsi/", "trans": "fussiness", "col": "be fussy about", "ex": "He is very fussy about his food."},
    "future": {"def": "未來", "ipa": "/ˈfjuːtʃə/", "trans": "futures", "col": "in the future, future career", "ex": "What are your plans for the future?"},
    "gain": {"def": "獲得、增加", "ipa": "/ɡeɪn/", "trans": "gained", "col": "gain weight, gain control", "ex": "I gained a lot of experience from the job."},
    "galaxy": {"def": "星系、銀河系、傑出的人才群", "ipa": "/ˈɡæləksi/", "trans": "galaxies", "col": "spiral galaxy", "ex": "There are billions of galaxies in the universe."},
    "gallery": {"def": "美術館、畫廊", "ipa": "/ˈɡæləri/", "trans": "galleries", "col": "art gallery", "ex": "We visited the national art gallery."},
    "gallon": {"def": "加侖", "ipa": "/ˈɡælən/", "trans": "gallons", "col": "gallon of milk", "ex": "The tank holds 50 gallons of gas."},
    "gamble": {"def": "賭博、投機", "ipa": "/ˈɡæmbl/", "trans": "gambled, gambler", "col": "gamble on", "ex": "He lost all his money gambling."},
    "gambler": {"def": "賭徒", "ipa": "/ˈɡæmblə/", "trans": "gamblers", "col": "professional gambler", "ex": "He is a professional gambler."},
    "game": {"def": "遊戲、比賽", "ipa": "/ɡeɪm/", "trans": "games", "col": "video game, play a game", "ex": "Let's play a game."},
    "gang": {"def": "幫派、群", "ipa": "/ɡæŋ/", "trans": "gangs, gangster", "col": "street gang", "ex": "A gang of thieves broke into the bank."},
    "gangster": {"def": "歹徒、幫派份子", "ipa": "/ˈɡæŋstə/", "trans": "gangsters", "col": "notorious gangster", "ex": "He was shot by a rival gangster."},
    "gap": {"def": "間隔、差距、缺口", "ipa": "/ɡæp/", "trans": "gaps", "col": "generation gap", "ex": "There's a wide gap between the two ideas."},
    "garage": {"def": "車庫", "ipa": "/ˈɡærɑːʒ/", "trans": "garages", "col": "park in the garage", "ex": "He put his car in the garage."},
    "garbage": {"def": "垃圾", "ipa": "/ˈɡɑːbɪdʒ/", "trans": "無", "col": "garbage can, garbage collector", "ex": "Don't throw garbage on the street."},
    "garden": {"def": "花園", "ipa": "/ˈɡɑːdn/", "trans": "gardener, gardening", "col": "botanical garden, beer garden", "ex": "My grandmother likes to work in the garden."},
    "gardener": {"def": "園丁", "ipa": "/ˈɡɑːdnə/", "trans": "gardeners", "col": "landscape gardener", "ex": "The gardener is watering the flowers."},
    "gardening": {"def": "園藝", "ipa": "/ˈɡɑːdnɪŋ/", "trans": "garden (名詞)", "col": "enjoy gardening", "ex": "Gardening is a popular hobby."},
    "garlic": {"def": "大蒜", "ipa": "/ˈɡɑːlɪk/", "trans": "無", "col": "clove of garlic", "ex": "I like the smell of garlic."},
    "garment": {"def": "衣服、服裝", "ipa": "/ˈɡɑːmənt/", "trans": "garments", "col": "garment industry", "ex": "She works in the garment industry."},
    "gas": {"def": "氣體、瓦斯、汽油", "ipa": "/ɡæs/", "trans": "gases", "col": "tear gas, natural gas", "ex": "We cook with natural gas."},
    "gasoline/gas": {"def": "汽油", "ipa": "/ˈɡæsəliːn/", "trans": "無", "col": "gasoline station", "ex": "The price of gasoline has gone up."},
    "gasp": {"def": "喘氣、倒抽一口氣", "ipa": "/ɡɑːsp/", "trans": "gasped", "col": "gasp for breath", "ex": "He gasped with surprise."},
    "gate": {"def": "門、閘門", "ipa": "/ɡeɪt/", "trans": "gates", "col": "main gate, departure gate", "ex": "The gate is locked."},
    "gather": {"def": "聚集、集合、採集", "ipa": "/ˈɡæðə/", "trans": "gathered, gathering", "col": "gather around", "ex": "A crowd gathered to watch the game."},
    "gathering": {"def": "集會", "ipa": "/ˈɡæðərɪŋ/", "trans": "gather (動詞)", "col": "family gathering, social gathering", "ex": "There was a large gathering of people."},
    "gauge/gage": {"def": "測量儀器、標準、規格、衡量", "ipa": "/ɡeɪdʒ/", "trans": "gauged", "col": "fuel gauge", "ex": "He used a gauge to measure the pressure."},
    "gave": {"def": "給予 (give 過去式)", "ipa": "/ɡeɪv/", "trans": "give (動詞)", "col": "gave up", "ex": "She gave me a present."},
    "gay": {"def": "同性戀的、快樂的", "ipa": "/ɡeɪ/", "trans": "gays", "col": "gay pride", "ex": "He is a gay rights activist."},
    "gaze": {"def": "注視、凝視", "ipa": "/ɡeɪz/", "trans": "gazed", "col": "gaze at", "ex": "He gazed at the stars for hours."},
    "gear": {"def": "齒輪、裝置、工具、排檔", "ipa": "/ɡɪə/", "trans": "gears", "col": "camping gear, in high gear", "ex": "He shifted into second gear."},
    "gender": {"def": "性別", "ipa": "/ˈdʒendə/", "trans": "genders", "col": "gender equality", "ex": "We should promote gender equality."},
    "gene": {"def": "基因", "ipa": "/dʒiːn/", "trans": "genes, genetic", "col": "dominant gene", "ex": "Blue eyes are a recessive gene."},
    "general": {"def": "一般的、普遍的、將軍", "ipa": "/ˈdʒenrəl/", "trans": "generally", "col": "general idea, in general", "ex": "In general, women live longer than men."},
    "generalize": {"def": "概括、歸納", "ipa": "/ˈdʒenrəlaɪz/", "trans": "generalization", "col": "generalize from", "ex": "It's dangerous to generalize from only one case."},
    "generally": {"def": "/ˈdʒenrəli/", "trans": "general (形容詞)", "col": "generally speaking", "ex": "I generally get up at six."},
    "generate": {"def": "產生、引起、生殖", "ipa": "/ˈdʒenəreɪt/", "trans": "generator (發電機), generation (產生)", "col": "generate power", "ex": "Windmills generate electricity."},
    "generation": {"def": "世代、產生", "ipa": "/ˌdʒenəˈreɪʃn/", "trans": "generations", "col": "future generation, previous generation", "ex": "We should respect the older generation."},
    "generator": {"def": "發電機、產生器", "ipa": "/ˈdʒenəreɪtə/", "trans": "generators", "col": "power generator", "ex": "The emergency generator started automatically."},
    "generosity": {"def": "慷慨、大方", "ipa": "/ˌdʒenəˈrɒsəti/", "trans": "generous (慷慨的)", "col": "act of generosity", "ex": "Thank you for your generosity."},
    "generous": {"def": "慷慨的、大方的", "ipa": "/ˈdʒenərəs/", "trans": "generously", "col": "be generous with", "ex": "He is very generous with his money."},
    "genius": {"def": "天才", "ipa": "/ˈdʒiːniəs/", "trans": "geniuses", "col": "mathematical genius", "ex": "He is a genius at math."},
    "gentle": {"def": "溫柔的、和藹的", "ipa": "/ˈdʒentl/", "trans": "gently", "col": "gentle voice, gentle breeze", "ex": "He is a very gentle person."},
    "gentleman": {"def": "紳士、先生", "ipa": "/ˈdʒentlmən/", "trans": "gentlemen", "col": "ladies and gentlemen", "ex": "He is a perfect gentleman."},
    "gently": {"def": "/ˈdʒentli/", "trans": "gentle (形容詞)", "col": "touch gently", "ex": "She spoke gently to the baby."},
    "genuine": {"def": "真實的、真誠的", "ipa": "/ˈdʒenjuɪn/", "trans": "genuinely", "col": "genuine leather", "ex": "It's made of genuine leather."},
    "geography": {"def": "地理學、地理", "ipa": "/dʒiˈɒɡrəfi/", "trans": "geographer, geographical", "col": "physical geography", "ex": "I like physical geography."},
    "geology": {"def": "地質學、地質", "ipa": "/dʒiˈɒlədʒ/", "trans": "geologist, geological", "col": "marine geology", "ex": "He has a degree in geology."},
    "geometry": {"def": "幾何學", "ipa": "/dʒiˈɒmətri/", "trans": "geometric", "col": "euclidean geometry", "ex": "We are studying geometry this semester."},
    "germ": {"def": "細菌、胚芽", "ipa": "/dʒɜːm/", "trans": "germs", "col": "disease germ", "ex": "Wash your hands to kill germs."},
    "Germany": {"def": "德國", "ipa": "/ˈdʒɜːməni/", "trans": "German (德國的/人/語)", "col": "Berlin, Germany", "ex": "Berlin is the capital of Germany."},
    "gesture": {"def": "手勢、姿勢、示意", "ipa": "/ˈdʒestʃə/", "trans": "gestured", "col": "make a gesture", "ex": "He made a rude gesture at me."},
    "get": {"def": "得到、變得、理解", "ipa": "/ɡet/", "trans": "got, got, getting", "col": "get along, get up", "ex": "I got some money from him."},
    "ghost": {"def": "鬼、幽靈", "ipa": "/ɡəʊst/", "trans": "ghosts, ghostly", "col": "ghost story, holy ghost", "ex": "I don't believe in ghosts."},
    "giant": {"def": "巨人、巨大的", "ipa": "/ˈdʒaɪənt/", "trans": "giants", "col": "giant panda", "ex": "The elephant is a giant animal."},
    "gift": {"def": "禮物、天賦", "ipa": "/ɡɪft/", "trans": "gifted (有天賦的)", "col": "birthday gift", "ex": "This is a gift for you."},
    "gifted": {"def": "有天賦的", "ipa": "/ˈɡɪftɪd/", "trans": "gift (名詞)", "col": "gifted child", "ex": "He is a gifted musician."},
    "gigantic": {"def": "巨大的、龐大的", "ipa": "/dʒaɪˈɡæntɪk/", "trans": "gigantically", "col": "gigantic wave", "ex": "The ship crashed into a gigantic iceberg."},
    "giggle": {"def": "咯咯地笑", "ipa": "/ˈɡɪɡl/", "trans": "giggled", "col": "giggle at", "ex": "The girls giggled during the lesson."},
    "ginger": {"def": "生薑、精力、赤褐色", "ipa": "/ˈdʒɪndʒə/", "trans": "gingery", "col": "ginger ale, ginger bread", "ex": "I like the taste of ginger."},
    "giraffe": {"def": "長頸鹿", "ipa": "/dʒəˈrɑːf/", "trans": "giraffes", "col": "baby giraffe", "ex": "A giraffe was eating leaves from a tree."},
    "girl/young lady": {"def": "女孩", "ipa": "/ɡɜːl/", "trans": "girls", "col": "little girl, baby girl", "ex": "She is a beautiful girl."},
    "give": {"def": "給予、交給", "ipa": "/ɡɪv/", "trans": "gave, given, giver", "col": "give in, give up", "ex": "Give me that book, please."},
    "glacier": {"def": "冰河、冰川", "ipa": "/ˈɡlæsiə/", "trans": "glaciers", "col": "receding glacier", "ex": "The glacier is melting rapidly."},
    "glad": {"def": "高興的", "ipa": "/ɡlæd/", "trans": "gladly", "col": "I'm glad that...", "ex": "I'm glad to see you again."},
    "glamour": {"def": "魅力、誘惑力", "ipa": "/ˈɡlæmə/", "trans": "glamorous (迷人的)", "col": "hollywood glamour", "ex": "She has the glamour of a movie star."},
    "glance": {"def": "瞥見、一瞥", "ipa": "/ɡlɑːns/", "trans": "glanced", "col": "at a glance, glance at", "ex": "He took a glance at the newspaper."},
    "glare": {"def": "怒視、刺眼的光", "ipa": "/ɡleə/", "trans": "glared", "col": "glare at", "ex": "She glared at him in anger."},
    "glass": {"def": "玻璃、玻璃杯、(複)眼鏡", "ipa": "/ɡlɑːs/", "trans": "glasses", "col": "magnifying glass, drinking glass", "ex": "Be careful; the glass is broken."},
    "glasses": {"def": "眼鏡", "ipa": "/ˈɡlɑːsɪz/", "trans": "無 (恆複)", "col": "wear glasses", "ex": "I have to wear glasses for reading."},
    "gleam": {"def": "微光、閃光", "ipa": "/ɡliːm/", "trans": "gleamed", "col": "gleam of hope", "ex": "His eyes gleamed with joy."},
    "glide": {"def": "滑行、下滑", "ipa": "/ɡlaɪd/", "trans": "glided, glider (滑翔機)", "col": "glide across", "ex": "The boat glided smoothly over the water."},
}

with open("batch_l1_p19.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART19, f, ensure_ascii=False, indent=2)
