import json

# Level 1 Part 17: (Film - Flow)
L1_PART17 = {
    "film": {"def": "電影、軟片、膠捲", "ipa": "/fɪlm/", "trans": "filmed", "col": "documentary film, short film", "ex": "I like to watch old black-and-white films."},
    "filter": {"def": "過濾、過濾器", "ipa": "/ˈfɪltə/", "trans": "filtered", "col": "water filter", "ex": "The sun filtered through the trees."},
    "fin/flipper": {"def": "鰭、鰭狀物", "ipa": "/fɪn/", "trans": "fins", "col": "dorsal fin", "ex": "Sharks have large fins on their backs."},
    "final": {"def": "最後的、期末考", "ipa": "/ˈfaɪnl/", "trans": "finally, finalize", "col": "final decision, final exam", "ex": "The final result was a tie."},
    "finally": {"def": "最後、終於", "ipa": "/ˈfaɪnəli/", "trans": "final (形容詞)", "col": "finally found", "ex": "He finally found his lost keys."},
    "finance": {"def": "財務、融資、資金", "ipa": "/ˈfaɪnæns/", "trans": "financial", "col": "public finance, corporate finance", "ex": "He studied finance at university."},
    "financial": {"def": "財務的、金融的", "ipa": "/faɪˈnænʃl/", "trans": "financially", "col": "financial support, financial crisis", "ex": "The company is in serious financial trouble."},
    "financially": {"def": "/faɪˈnænʃəli/", "trans": "financial (形容詞)", "col": "financially independent", "ex": "He is now financially independent."},
    "find": {"def": "發現、尋找", "ipa": "/faɪnd/", "trans": "found, found, finding (名詞)", "col": "find out, find one's way", "ex": "I can't find my keys anywhere."},
    "finding": {"def": "發現、調查結果", "ipa": "/ˈfaɪndɪŋ/", "trans": "findings", "col": "scientific finding", "ex": "The finding was a surprise to many."},
    "fine": {"def": "好的、罰金", "ipa": "/faɪn/", "trans": "fined", "col": "pay a fine", "ex": "I feel fine today."},
    "finger": {"def": "手指", "ipa": "/ˈfɪŋɡə/", "trans": "fingers", "col": "index finger, ring finger", "ex": "I cut my finger yesterday."},
    "finish": {"def": "完成、結束", "ipa": "/ˈfɪnɪʃ/", "trans": "finished", "col": "finish off", "ex": "I have finished my homework."},
    "finite": {"def": "有限的、限定的", "ipa": "/ˈfaɪnaɪt/", "trans": "infinite (無限的)", "col": "finite resources", "ex": "Our natural resources are finite."},
    "fire": {"def": "火、射擊、火災、開除", "ipa": "/ˈfaɪə/", "trans": "fired, firemen", "col": "catch fire, set fire to", "ex": "There was a fire in the building night."},
    "firearm": {"def": "火器、槍枝", "ipa": "/ˈfaɪərɑːm/", "trans": "firearms", "col": "illegal firearm", "ex": "He was arrested for possessing an illegal firearm."},
    "firefighter/fireman": {"def": "消防員", "ipa": "/ˈfaɪəfaɪtə/", "trans": "firefighters", "col": "volunteer firefighter", "ex": "Firefighters arrived quickly to extinguish the fire."},
    "firework": {"def": "/ˈfaɪəwɜːk/", "trans": "fireworks", "col": "firework display", "ex": "We watched the firework display on New Year's Eve."},
    "firm": {"def": "堅實的、公司、硬的", "ipa": "/fɜːm/", "trans": "firmly", "col": "law firm, accounting firm", "ex": "The law firm is located in the city center."},
    "firmly": {"def": "牢固地、堅定地", "ipa": "/ˈfɜːmli/", "trans": "firm (形容詞)", "col": "firmly believe", "ex": "I firmly believe that he is right."},
    "first": {"def": "/fɜːst/", "trans": "firstly", "col": "first of all, at first", "ex": "This is the first time I've been to London."},
    "firstly": {"def": "/ˈfɜːstli/", "trans": "first (副詞)", "col": "firstly, secondly", "ex": "Firstly, I'd like to thank everyone for coming."},
    "fish": {"def": "魚、捕魚", "ipa": "/fɪʃ/", "trans": "fishes, fisherman", "col": "fresh fish, fish and chips", "ex": "The fish is swimming in the water."},
    "fisherman": {"def": "漁夫", "ipa": "/ˈfɪʃəmən/", "trans": "fishermen", "col": "old fisherman", "ex": "The fisherman caught a lot of fish today."},
    "fishing": {"def": "捕魚、釣魚", "ipa": "/ˈfɪʃɪŋ/", "trans": "fish (名詞/動詞)", "col": "go fishing", "ex": "He likes to go fishing on weekends."},
    "fist": {"def": "拳頭", "ipa": "/fɪst/", "trans": "fists", "col": "clench one's fist", "ex": "He clenched his fist in anger."},
    "fit": {"def": "適合的、健康的、使適合", "ipa": "/fɪt/", "trans": "fitted, fitting", "col": "keep fit, a good fit", "ex": "I exercise every day to keep fit."},
    "five": {"def": "/faɪv/", "trans": "fifth", "col": "at five", "ex": "He has five fingers on each hand."},
    "fix": {"def": "修理、固定、困難", "ipa": "/fɪks/", "trans": "fixed", "col": "in a fix", "ex": "Can you fix my bike?"},
    "fixed": {"def": "固定的、不變的", "ipa": "/fɪkst/", "trans": "fix (動詞)", "col": "fixed income", "ex": "The price is fixed and cannot be changed."},
    "flag": {"def": "旗幟", "ipa": "/flæɡ/", "trans": "flags", "col": "national flag", "ex": "The national flag was waving in the breeze."},
    "flame": {"def": "火焰、情熱", "ipa": "/fleɪm/", "trans": "flames, flaming", "col": "burst into flames", "ex": "The house was in flames when we arrived."},
    "flap": {"def": "拍打、拍動", "ipa": "/flæp/", "trans": "flapped", "col": "flap wings", "ex": "The bird flapped its wings and flew away."},
    "flare": {"def": "閃耀、燒開、閃光信號", "ipa": "/fleə/", "trans": "flared", "col": "solar flare", "ex": "The signal flare was seen from the ship."},
    "flash": {"def": "閃光、一瞬間、發閃光", "ipa": "/flæʃ/", "trans": "flashed", "col": "flash of light, in a flash", "ex": "There was a sudden flash of light in the sky."},
    "flashlight/torch": {"def": "手電筒", "ipa": "/ˈflæʃlaɪt/", "trans": "flashlights", "col": "shine a flashlight", "ex": "I used my flashlight to see in the dark cave."},
    "flat": {"def": "平坦的、公寓", "ipa": "/flæt/", "trans": "flats, flatly", "col": "flat tire", "ex": "The land around here is very flat."},
    "flatter": {"def": "奉承、討好", "ipa": "/ˈflætə/", "trans": "flattered, flattery", "col": "flatter someone", "ex": "Don't flatter me; just tell me the truth."},
    "flattery": {"def": "奉承、甜言蜜語", "ipa": "/ˈflætəri/", "trans": "flatter (動詞)", "col": "empty flattery", "ex": "She is sensible to empty flattery."},
    "flavor/flavour": {"def": "風味、調味品", "ipa": "/ˈfleɪvə/", "trans": "flavored", "col": "original flavor", "ex": "This ice cream has a strawberry flavor."},
    "flea": {"def": "跳蚤", "ipa": "/fliː/", "trans": "fleas", "col": "flea market", "ex": "We bought some old books at the flea market."},
    "flee": {"def": "逃走、潰散", "ipa": "/fliː/", "trans": "fled, fled", "col": "flee from", "ex": "They had to flee from their homes due to the war."},
    "fleet": {"def": "艦隊、船隊、快速的", "ipa": "/fliːt/", "trans": "fleets", "col": "fishing fleet", "ex": "A large naval fleet was anchored in the bay."},
    "flesh": {"def": "肉、果肉、人體", "ipa": "/fleʃ/", "trans": "fleshy", "col": "flesh and blood", "ex": "The tiger ate some fresh flesh."},
    "flexibility": {"def": "靈活性、彈性", "ipa": "/ˌfleksəˈbɪləti/", "trans": "flexible (靈活的)", "col": "high flexibility", "ex": "He shows great flexibility in his work."},
    "flexible": {"def": "靈活的、有彈性的", "ipa": "/ˈfleksəbl/", "trans": "flexibly", "col": "flexible time", "ex": "We have very flexible working hours."},
    "flight": {"def": "飛行、班機、逃跑", "ipa": "/flaɪt/", "trans": "flights", "col": "direct flight, domestic flight", "ex": "The flight will take about three hours."},
    "float": {"def": "漂浮", "ipa": "/fləʊt/", "trans": "floated", "col": "float in the air", "ex": "Wood floats on water."},
    "flock": {"def": "群(鳥/羊)、群聚", "ipa": "/flɒk/", "trans": "flocks", "col": "flock of birds", "ex": "A large flock of birds flew over the lake."},
    "flood": {"def": "洪水、淹沒", "ipa": "/flʌd/", "trans": "flooded", "col": "heavy flood", "ex": "The river flooded after the heavy rain."},
    "floor": {"def": "地板、樓層", "ipa": "/flɔː/", "trans": "floors", "col": "on the floor, first floor", "ex": "The kids are playing on the floor."},
    "flour": {"def": "麵粉", "ipa": "/ˈflaʊə/", "trans": "無 (不可數)", "col": "wheat flour", "ex": "I bought a bag of flour to bake bread."},
    "flow": {"def": "流動、流入", "ipa": "/fləʊ/", "trans": "flowed", "col": "flow out", "ex": "The river flows into the sea."},
}

with open("batch_l1_p17.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART17, f, ensure_ascii=False, indent=2)
