import json

# Level 1 Part 36: (Open - Overstep)
L1_PART36 = {
    "open": {"def": "打通、開、打開的、坦率的", "ipa": "/ˈəʊpən/", "trans": "opened, opening, openly", "col": "open mind, in the open", "ex": "Please open the door."},
    "opening": {"def": "開端、空穴、職位空缺、開始的", "ipa": "/ˈəʊpənɪŋ/", "trans": "openings, open (動詞)", "col": "job opening, grand opening", "ex": "The opening ceremony starts at eight."},
    "openly": {"def": "坦率地、公開地", "ipa": "/ˈəʊpənli/", "trans": "open (形容詞)", "col": "speak openly", "ex": "They discussed the issue openly."},
    "opera": {"def": "歌劇", "ipa": "/ˈɒpərə/", "trans": "operas", "col": "soap opera, opera house", "ex": "He likes going to the opera."},
    "operate": {"def": "操作、運轉、動手術", "ipa": "/ˈ常规 /", "trans": "operated, operation, operator", "col": "operate a machine, operate on", "ex": "The doctor decided to operate at once."},
    "operation": {"def": "操作、手術、業務、運作", "ipa": "/ˌɒpəˈreɪʃn/", "trans": "operations", "col": "in operation, surgical operation", "ex": "The factory is in full operation."},
    "operational": {"def": "運作的、手術的、作戰的", "ipa": "/ˌɒpəˈreɪʃənl/", "trans": "operation", "col": "operational costs", "ex": "The system is now fully operational."},
    "operator": {"def": "操作員、接線生、運營商", "ipa": "/ˈɒpəreɪtə/", "trans": "operators", "col": "telephone operator", "ex": "Please ask the operator for the long-distance call."},
    "opinion": {"def": "意見、觀點、評價", "ipa": "/əˈpɪnjən/", "trans": "opinions", "col": "in my opinion, public opinion", "ex": "In my opinion, he is a good teacher."},
    "opium": {"def": "鴉片、麻醉劑", "ipa": "/ˈəʊpiəm/", "trans": "無", "col": "opium war", "ex": "Opium poppy is used to produce opium."},
    "opponent": {"def": "對手、敵手、反對者", "ipa": "/əˈpəʊnənt/", "trans": "opponents", "col": "political opponent", "ex": "He defeated his opponent in the final match."},
    "opportune": {"def": "適時的、適當的、凑巧的", "ipa": "/ˈɒpətjuːn/", "trans": "opportunely", "col": "opportune moment", "ex": "This is an opportune moment for us to leave."},
    "opportunist": {"def": "機會主義者", "ipa": "/ˌɒpəˈtjuːnɪst/", "trans": "opportunists, opportunistic", "col": "ruthless opportunist", "ex": "He was described as a political opportunist."},
    "opportunity": {"def": "機會、時機", "ipa": "/ˌɒpəˈtjuːnəti/", "trans": "opportunities", "col": "equal opportunity, take the opportunity", "ex": "Don't miss the opportunity."},
    "oppose": {"def": "反對、使對抗", "ipa": "/əˈpəʊz/", "trans": "opposed, opposition", "col": "be opposed to", "ex": "They opposed the new plan."},
    "opposite": {"def": "相反的、對面的、對立物", "ipa": "/ˈɒpəzɪt/", "trans": "opposites", "col": "the opposite sex, on the opposite side", "ex": "They live on the opposite side of the street."},
    "opposition": {"def": "反對、對抗、反對黨", "ipa": "/ˌɒpəˈzɪʃn/", "trans": "oppositions", "col": "under opposition", "ex": "There is strong opposition to the tax increase."},
    "oppress": {"def": "壓迫、壓抑、使憂鬱", "ipa": "/əˈpres/", "trans": "oppressed, oppression", "col": "be oppressed by", "ex": "The dictator oppressed his people."},
    "oppression": {"def": "壓迫、沈悶、苦難", "ipa": "/əˈpreʃn/", "trans": "oppressions", "col": "fight against oppression", "ex": "The people suffered under years of oppression."},
    "opt": {"def": "選擇、挑選", "ipa": "/ɒpt/", "trans": "opted", "col": "opt for, opt out", "ex": "She decided to opt for a career in law."},
    "optical": {"def": "光學的、視力的", "ipa": "/ˈɒptɪkl/", "trans": "optically", "col": "optical fiber, optical illusion", "ex": "Microscopes are optical instruments."},
    "optician": {"def": "配鏡師、眼鏡商", "ipa": "/ɒpˈtɪʃn/", "trans": "opticians", "col": "see an optician", "ex": "I need to go to the optician to have my eyes tested."},
    "optimism": {"def": "樂觀(主義)", "ipa": "/ˈɒptɪmɪzəm/", "trans": "pessimism (悲觀)", "col": "blind optimism", "ex": "His optimism is infectious."},
    "optimist": {"def": "樂觀主義者", "ipa": "/ˈ常规 /", "trans": "optimists, optimistic", "col": "congenital optimist", "ex": "I'm an optimist by nature."},
    "optimistic": {"def": "樂觀的", "ipa": "/ˌɒptɪˈmɪstɪk/", "trans": "optimistically", "col": "optimistic outlook", "ex": "I'm optimistic about the future."},
    "optimum": {"def": "最優的、最合適的、最佳狀態", "ipa": "/ˈɒptɪməm/", "trans": "optima, optimal", "col": "optimum temperature", "ex": "The machine is working at its optimum level."},
    "option": {"def": "選擇、期權、選件", "ipa": "/ˈɒpʃn/", "trans": "options, optional", "col": "keep options open, stock option", "ex": "You have several options."},
    "optional": {"def": "可選擇的、非強制的", "ipa": "/ˈɒpʃənl/", "trans": "optionally", "col": "optional extras", "ex": "The course is optional."},
    "or": {"def": "或者、還是", "ipa": "/ɔː/", "trans": "無", "col": "either...or...", "ex": "Tea or coffee?"},
    "oral": {"def": "口頭的、口腔的、口試", "ipa": "/ˈɔːrəl/", "trans": "orally", "col": "oral exam, oral hygiene", "ex": "We have an oral exam tomorrow."},
    "orange": {"def": "橘子、橙色(的)", "ipa": "/ˈɒrɪndʒ/", "trans": "oranges", "col": "orange juice", "ex": "I'd like an orange."},
    "orbit": {"def": "軌道、勢力範圍、繞軌道行", "ipa": "/ˈɔːbɪt/", "trans": "orbited", "col": "in orbit, earth orbit", "ex": "The moon orbits the earth."},
    "orchard": {"def": "果園", "ipa": "/ˈɔːtʃəd/", "trans": "orchards", "col": "apple orchard", "ex": "They have a small apple orchard."},
    "orchestra": {"def": "管弦樂團、管弦樂器", "ipa": "/ˈɔːkɪstrə/", "trans": "orchestras, orchestral", "col": "symphony orchestra", "ex": "He plays the violin in an orchestra."},
    "order": {"def": "命令、順序、訂單、秩序、訂購、整理", "ipa": "/ˈɔːdə/", "trans": "ordered, orderly", "col": "in order to, law and order", "ex": "May I take your order?"},
    "orderly": {"def": "有條理的、守秩序的、勤務員", "ipa": "/ˈɔːdəli/", "trans": "order (名詞/動詞)", "col": "orderly queue", "ex": "The meeting was conducted in an orderly way."},
    "ordinal": {"def": "序數(的)", "ipa": "/ˈɔːdɪnl/", "trans": "ordinals", "col": "ordinal numbers", "ex": "First, second and third are ordinal numbers."},
    "ordinary": {"def": "普通的、平凡的", "ipa": "/ˈɔːdnri/", "trans": "extraordinary (非凡的)", "col": "ordinary life, in the ordinary way", "ex": "He is just an ordinary man."},
    "ore": {"def": "礦石、礦砂", "ipa": "/ɔː/", "trans": "ores", "col": "iron ore", "ex": "The iron ore is sent to the smelter."},
    "organ": {"def": "器官、風琴、機構、喉舌", "ipa": "/ˈɔːɡən/", "trans": "organs, organic, organism", "col": "internal organ, church organ", "ex": "The heart is an important organ."},
    "organic": {"def": "有機的、器官的、整體的", "ipa": "/ɔːˈɡænɪk/", "trans": "organically", "col": "organic food, organic chemistry", "ex": "I prefer organic vegetables."},
    "organism": {"def": "生物、有機體", "ipa": "/ˈɔːɡənɪzəm/", "trans": "organisms", "col": "marine organism", "ex": "A virus is a simple organism."},
    "organization/organisation": {"def": "組織、機構、團體", "ipa": "/ˌɔːɡənaɪˈzeɪʃn/", "trans": "organizations, organize (動詞)", "col": "international organization", "ex": "WHO is an international organization."},
    "organize/organise": {"def": "組織、規劃、籌備", "ipa": "/ˈɔːɡənaɪz/", "trans": "organized, organizer", "col": "organize a trip", "ex": "We are organizing a party."},
    "organizer/organiser": {"def": "組織者、籌備人", "ipa": "/ˈɔːɡənaɪzə/", "trans": "organizers", "col": "event organizer", "ex": "He is the chief organizer of the event."},
    "orient": {"def": "東方、適應、向東", "ipa": "/ˈɔːriənt/", "trans": "oriented, orientation", "col": "the Orient", "ex": "They are oriented toward the south."},
    "oriental": {"def": "東方的、東方人", "ipa": "/ˌɔːriˈentl/", "trans": "orientals", "col": "oriental culture", "ex": "He is an expert in oriental studies."},
    "orientation": {"def": "取向、定位、新人訓練", "ipa": "/ˌɔːrienˈteɪʃn/", "trans": "orientations", "col": "sexual orientation, orientation course", "ex": "The school holds an orientation program for new students."},
    "origin": {"def": "起源、由來、出生", "ipa": "/ˈɒrɪdʒɪn/", "trans": "origins, original", "col": "country of origin, point of origin", "ex": "The origin of the word is unknown."},
    "original": {"def": "原始的、獨創的、原作", "ipa": "/əˈrɪdʒənl/", "trans": "originally, originality", "col": "original idea, original copy", "ex": "This is the original manuscript."},
    "originality": {"def": "創意、獨創性", "ipa": "/əˌrɪdʒəˈnæləti/", "trans": "original (形容詞)", "col": "lack of originality", "ex": "The design shows great originality."},
    "originally": {"def": "/əˈrɪdʒənəli/", "trans": "original (形容詞)", "col": "originally planned", "ex": "I originally come from Taiwan."},
    "originate": {"def": "起源、創始", "ipa": "/əˈrɪdʒɪneɪt/", "trans": "originated", "col": "originate from", "ex": "The custom originated in ancient Greece."},
    "ornament": {"def": "裝飾、點綴、裝飾品(ˈɔːnəmənt)", "ipa": "/ˈɔːnəmənt/", "trans": "ornaments, ornamental", "col": "garden ornament", "ex": "The vase is purely an ornament."},
    "ornamental": {"def": "裝飾的、美觀的", "ipa": "/ˌɔːnəˈmentl/", "trans": "ornament (名詞)", "col": "ornamental plants", "ex": "They grew many ornamental shrubs."},
    "orphan": {"def": "孤兒、孤立的、變孤兒", "ipa": "/ˈɔːfn/", "trans": "orphans, orphanage", "col": "war orphan", "ex": "He became an orphan at the age of ten."},
    "orphanage": {"def": "孤兒院", "ipa": "/ˈɔːfənɪdʒ/", "trans": "orphanages", "col": "local orphanage", "ex": "The child was sent to an orphanage."},
    "orthodontist": {"def": "齒列矯正醫生", "ipa": "/ˌɔːθəˈdɒntɪst/", "trans": "orthodontists", "col": "visit an orthodontist", "ex": "She has to see the orthodontist regularly."},
    "orthodox": {"def": "正統的、公認的、慣常的", "ipa": "/ˈɔːθədɒks/", "trans": "orthodoxy", "col": "orthodox view", "ex": "That's an orthodox religious belief."},
    "osteoporosis": {"def": "骨質疏鬆症", "ipa": "/ˌɒstiəʊpəˈrəʊsɪs/", "trans": "無", "col": "suffer from osteoporosis", "ex": "Senior citizens are at risk for osteoporosis."},
    "ostrich": {"def": "鴕鳥", "ipa": "/ˈɒstrɪtʃ/", "trans": "ostriches", "col": "ostrich policy", "ex": "The ostrich is the largest living bird."},
    "other": {"def": "其他的、另外、其他人/物", "ipa": "/ˈʌðə/", "trans": "otherwise (否則)", "col": "each other, one another", "ex": "I have no other choice."},
    "otherwise": {"def": "否則、在其他方面、否則地", "ipa": "/ˈʌðəwaɪz/", "trans": "無", "col": "unless otherwise specified", "ex": "Do it now; otherwise, you'll forget."},
    "ought": {"def": "應該、應當", "ipa": "/ɔːt/", "trans": "無", "col": "ought to", "ex": "You ought to help your mother."},
    "ounce": {"def": "盎司、一點兒", "ipa": "/aʊns/", "trans": "ounces", "col": "sixteen ounces", "ex": "There are sixteen ounces in a pound."},
    "our": {"def": "我們的", "ipa": "/ˈaʊə/", "trans": "us, ours", "col": "our country", "ex": "Our teacher is very kind."},
    "ours": {"def": "我們的 (所有代名詞)", "ipa": "/ˈaʊəz/", "trans": "us, our", "col": "it's ours", "ex": "The house is ours."},
    "ourselves": {"def": "我們自己 (反身代名詞)", "ipa": "/ˌaʊəˈselvz/", "trans": "無", "col": "by ourselves", "ex": "We did it ourselves."},
    "out": {"def": "在外、出局、徹底地、出於、向外", "ipa": "/aʊt/", "trans": "outer, outside", "col": "out of date, out of control", "ex": "He is out now."},
    "outbreak": {"def": "爆發、突然發生", "ipa": "/ˈaʊtbreɪk/", "trans": "outbreaks", "col": "cholera outbreak, war outbreak", "ex": "The outbreak of war was sudden."},
    "outcome": {"def": "結果、後果", "ipa": "/ˈaʊtkʌm/", "trans": "outcomes", "col": "final outcome", "ex": "What was the outcome of the game?"},
    "outdoor": {"def": "戶外的、野外的", "ipa": "/ˈaʊtdɔː/", "trans": "outdoors", "col": "outdoor activity", "ex": "I like outdoor sports."},
    "outdoors": {"def": "在戶外、露天、戶外", "ipa": "/ˌaʊtˈdɔːz/", "trans": "indoor (室內的)", "col": "sleep outdoors", "ex": "It's nice to spend time outdoors."},
    "outer": {"def": "外部的、外層的", "ipa": "/ˈaʊtə/", "trans": "inner (內部的)", "col": "outer space, outer layer", "ex": "Pluto is one of the outer planets."},
    "outfit": {"def": "全套裝備、全套服裝、機構、配備", "ipa": "/ˈaʊtfɪt/", "trans": "outfits", "col": "hiking outfit", "ex": "She is wearing a new outfit."},
    "outgo": {"def": "支出、超額、走得比...快", "ipa": "/ˈaʊtɡəʊ/", "trans": "outgoes", "col": "income and outgo", "ex": "Our outgo exceeded our income."},
    "outgoing": {"def": "外向的、即將卸任的、往外的", "ipa": "/ˈaʊtɡəʊɪŋ/", "trans": "outgoingness", "col": "outgoing president", "ex": "She has an outgoing personality."},
    "outing": {"def": "遠足、郊遊", "ipa": "/ˈaʊtɪŋ/", "trans": "outings", "col": "school outing", "ex": "They went on a company outing."},
    "outlaw": {"def": "不法之徒、逃犯、宣布為非法", "ipa": "/ˈaʊtlɔː/", "trans": "outlaws, outlawed", "col": "notorious outlaw", "ex": "The government decided to outlaw the organization."},
    "outlet": {"def": "出口、通路、插座、暢貨中心", "ipa": "/ˈaʊtlet/", "trans": "outlets", "col": "retail outlet, emotional outlet", "ex": "Writing is an emotional outlet for her."},
    "outline": {"def": "輪廓、大綱、描繪、概述", "ipa": "/ˈaʊtlaɪn/", "trans": "outlined", "col": "rough outline", "ex": "He drew an outline of the map."},
    "outlook": {"def": "景緻、觀點、前景、監視", "ipa": "/ˈaʊtlʊk/", "trans": "outlooks", "col": "economic outlook", "ex": "The outlook for tomorrow is sunny."},
    "outnumber": {"def": "在數量上超過", "ipa": "/ˌaʊtˈnʌmbə/", "trans": "outnumbered", "col": "be outnumbered by", "ex": "They were heavily outnumbered."},
    "output": {"def": "產量、輸出、產品", "ipa": "/ˈaʊtpʊt/", "trans": "outputs", "col": "industrial output, power output", "ex": "Manufacturing output has risen."},
    "outrage": {"def": "暴行、侮辱、憤慨、激怒", "ipa": "/ˈaʊtreɪdʒ/", "trans": "outraged, outrageous", "col": "moral outrage", "ex": "The news caused moral outrage."},
    "outrageous": {"def": "殘暴的、無恥的、極其無禮的", "ipa": "/aʊtˈreɪdʒəs/", "trans": "outrageously", "col": "outrageous price", "ex": "The price is outrageous."},
    "outrun": {"def": "跑得比...快、超過", "ipa": "/ˌaʊtˈrʌn/", "trans": "outran, outrun", "col": "outrun someone", "ex": "The boy can outrun his father."},
    "outside": {"def": "外部、外面、在外面、外部的", "ipa": "/ˌaʊtˈsaɪd/", "trans": "inside (內部的)", "col": "on the outside, outside of", "ex": "The house is painted white outside."},
    "outsider": {"def": "外人、局外人、門外漢", "ipa": "/ˌaʊtˈsaɪdə/", "trans": "outsiders", "col": "regarded as an outsider", "ex": "He felt like an outsider in the new school."},
    "outskirts": {"def": "郊區、市郊", "ipa": "/ˈaʊtskɜːts/", "trans": "無 (恆複)", "col": "on the outskirts of", "ex": "They live on the outskirts of London."},
    "outstanding": {"def": "傑出的、顯著的、未償付的", "ipa": "/aʊtˈstændɪŋ/", "trans": "outstandingly", "col": "outstanding achievement, outstanding debt", "ex": "Her performative was outstanding."},
    "outward": {"def": "向外的、表面的、向外", "ipa": "/ˈaʊtwəd/", "trans": "outwards", "col": "outward journey, outward appearance", "ex": "The outward journey took six hours."},
    "outwards": {"def": "向外地", "ipa": "/ˈaʊtwədz/", "trans": "inwards (向內地)", "col": "open outwards", "ex": "The door opens outwards."},
    "outweigh": {"def": "在重要性/重量上超過", "ipa": "/ˌaʊtˈweɪ/", "trans": "outweighed", "col": "outweigh the benefits", "ex": "The risks far outweigh the benefits."},
    "outwit": {"def": "以巧計勝過、瞞過", "ipa": "/ˌaʊtˈwɪt/", "trans": "outwitted", "col": "outwit someone", "ex": "She managed to outwit her opponents."},
    "oval": {"def": "橢圓形的、卵形的、橢圓形", "ipa": "/ˈəʊvl/", "trans": "ovals", "col": "oval office", "ex": "The table is oval in shape."},
    "oven": {"def": "爐、灶、烤箱", "ipa": "/ˈʌvn/", "trans": "ovens", "col": "microwave oven", "ex": "Put the chicken in the oven."},
    "over": {"def": "在...之上、越過、超過、結束、多餘", "ipa": "/ˈəʊvə/", "trans": "無", "col": "over there, all over", "ex": "The game is over."},
    "overall": {"def": "整體的、全面的、工裝褲(複)、全面地", "ipa": "/ˌəʊvərˈɔːl/", "trans": "overalls", "col": "overall cost", "ex": "The overall effect is very pleasing."},
    "overboard": {"def": "自船上掉入水中、過分地", "ipa": "/ˈəʊvəbɔːd/", "trans": "無", "col": "fall overboard, go overboard", "ex": "He jumped overboard."},
    "overcome": {"def": "戰勝、克服、使受不了", "ipa": "/ˌəʊvəˈkʌm/", "trans": "overcame, overcome", "col": "overcome difficulties", "ex": "She overcame her fear of flying."},
    "overdo": {"def": "做得過分、誇張、煮得太久", "ipa": "/ˌəʊvəˈduː/", "trans": "overdid, overdone", "col": "overdo it", "ex": "Don't overdo the exercise."},
    "overdose": {"def": "用藥過量", "ipa": "/ˈəʊvədəʊs/", "trans": "overdosed", "col": "fatal overdose", "ex": "He died of a drug overdose."},
    "overdue": {"def": "過期的、延誤的", "ipa": "/ˌəʊvəˈdjuː/", "trans": "due (到期的)", "col": "overdue library book", "ex": "The library books are overdue."},
    "overeat": {"def": "吃得過飽", "ipa": "/ˌəʊvərˈiːt/", "trans": "overate, overeaten", "col": "overeat oneself", "ex": "Don't overeat; it's bad for your health."},
    "overflow": {"def": "溢出、氾濫、充溢", "ipa": "/ˌəʊvəˈfləʊ/", "trans": "overflowed", "col": "overflow with", "ex": "The river overflowed its banks."},
    "overhear": {"def": "無意中聽到、偷聽到", "ipa": "/ˌəʊvəˈhɪə/", "trans": "overheard", "col": "overhear a conversation", "ex": "I overheard them talking in the next room."},
    "overlap": {"def": "重疊、部分一致", "ipa": "/ˌəʊvəˈlæp/", "trans": "overlapped", "col": "overlap with", "ex": "Our interests overlap."},
    "overlook": {"def": "俯瞰、忽視、寬恕、監視", "ipa": "/ˌəʊvəˈlʊk/", "trans": "overlooked", "col": "overlook a mistake", "ex": "The room overlooks the garden."},
    "overnight": {"def": "在夜間、一整夜地、一夜間、突然", "ipa": "/ˌəʊvəˈnaɪt/", "trans": "無", "col": "stay overnight, overnight success", "ex": "We stayed overnight in a hotel."},
    "overpass": {"def": "天橋、陸橋、越過", "ipa": "/ˈəʊvəpɑːs/", "trans": "overpasses", "col": "pedestrian overpass", "ex": "We crossed the road by the overpass."},
    "overpower": {"def": "擊敗、壓倒、使受不了", "ipa": "/ˌəʊvəˈpaʊə/", "trans": "overpowered", "col": "overpowered by smoke", "ex": "He was overpowered by the police."},
    "overrate": {"def": "評估過高、高估", "ipa": "/ˌəʊvəˈreɪt/", "trans": "overrated", "col": "overrated movie", "ex": "I think that movie is overrated."},
    "overrule": {"def": "否決、駁回、統治", "ipa": "/ˌəʊvəˈruːl/", "trans": "overruled", "col": "overrule an objection", "ex": "The judge overruled the objection."},
    "overrun": {"def": "橫掃、氾濫、超過(限度)、蔓延", "ipa": "/ˌəʊvəˈrʌn/", "trans": "overran, overrun", "col": "overrun with weeds", "ex": "The garden was overrun with weeds."},
    "overseas": {"def": "海外的、在國外的、向海外", "ipa": "/ˌəʊvəˈsiːz/", "trans": "abroad", "col": "overseas market, study overseas", "ex": "He works overseas."},
    "overshadow": {"def": "遮蔽、使陰暗、使顯得微不足道", "ipa": "/ˌəʊvəˈʃædəʊ/", "trans": "overshadowed", "col": "overshadow someone", "ex": "Her success was overshadowed by her health problems."},
    "overshoot": {"def": "越過、飛越、打過頭", "ipa": "/ˌəʊvəˈʃuːt/", "trans": "overshot", "col": "overshoot the runway", "ex": "The plane overshot the runway."},
    "oversleep": {"def": "睡過頭", "ipa": "/ˌəʊvəˈsliːp/", "trans": "overslept", "col": "often oversleep", "ex": "I'm sorry I'm late; I overslept."},
    "overstate": {"def": "言過其實、誇大", "ipa": "/ˌəʊvərˈsteɪt/", "trans": "overstated", "col": "overstate the case", "ex": "He overstated the importance of the meeting."},
    "overstep": {"def": "踏出...之外、超越、逾越", "ipa": "/ˌəʊvəˈstep/", "trans": "overstepped", "col": "overstep the line", "ex": "He overstepped his authority."},
}

with open("batch_l1_p36.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART36, f, ensure_ascii=False, indent=2)
