import json

# Level 1 Part 18: (Flower - Fundamental)
L1_PART18 = {
    "flower": {"def": "花、開花", "ipa": "/ˈflaʊə/", "trans": "flowered", "col": "wild flower, in flower", "ex": "The flower smells very sweet."},
    "flu": {"def": "流感", "ipa": "/fluː/", "trans": "無", "col": "catch flu, stomach flu", "ex": "I am in bed with the flu."},
    "fluency": {"def": "流利、流暢", "ipa": "/ˈfluːənsi/", "trans": "fluent (流利的)", "col": "speak with fluency", "ex": "She speaks English with great fluency."},
    "fluent": {"def": "流利的", "ipa": "/ˈfluːənt/", "trans": "fluently", "col": "be fluent in", "ex": "He is fluent in three languages."},
    "fluid": {"def": "流體、液體、流動的", "ipa": "/ˈfluːɪd/", "trans": "fluids", "col": "cleaning fluid, body fluid", "ex": "Water and oil are fluids."},
    "flunk": {"def": "不及格、失敗", "ipa": "/flʌŋk/", "trans": "flunked", "col": "flunk an exam", "ex": "I flunked the math test."},
    "flush": {"def": "臉紅、沖水、發紅", "ipa": "/flʌʃ/", "trans": "flushed", "col": "flush with anger, flush a toilet", "ex": "She flushed with embarrassment."},
    "flute": {"def": "長笛", "ipa": "/fluːt/", "trans": "flutes, flutist", "col": "play the flute", "ex": "She is practicing the flute."},
    "fly": {"def": "飛、蒼蠅", "ipa": "/flaɪ/", "trans": "flew, flown, flight (名詞)", "col": "fly a kite", "ex": "Look at the bird flying in the sky."},
    "foam": {"def": "泡沫", "ipa": "/fəʊm/", "trans": "foamed", "col": "shaving foam", "ex": "The sea was covered with white foam."},
    "focus": {"def": "焦點、聚焦、專注", "ipa": "/ˈfəʊkəs/", "trans": "focused, focusing", "col": "focus on, in focus", "ex": "You must focus on your study."},
    "fog": {"def": "霧", "ipa": "/fɒɡ/", "trans": "foggy (多霧的)", "col": "thick fog", "ex": "The hills were hidden in thick fog."},
    "foggy": {"def": "霧氣濃重的、多霧的", "ipa": "/ˈfɒɡi/", "trans": "fog (名詞)", "col": "foggy morning", "ex": "It's a very foggy morning today."},
    "fold": {"def": "摺疊、合攏", "ipa": "/fəʊld/", "trans": "folded", "col": "fold up", "ex": "He folded the letter and put it in his pocket."},
    "folder": {"def": "資料夾", "ipa": "/ˈfəʊldə/", "trans": "folders", "col": "plastic folder, file folder", "ex": "Put these papers into the blue folder."},
    "folk": {"def": "人、民間的", "ipa": "/fəʊk/", "trans": "folks", "col": "folk song, folk dance", "ex": "I like listening to traditional folk music."},
    "follow": {"def": "跟隨、遵守、按著", "ipa": "/ˈfɒləʊ/", "trans": "followed, following", "col": "follow instructions, follow in one's footsteps", "ex": "Follow me, please."},
    "follower": {"def": "追隨者、信徒", "ipa": "/ˈfɒləʊə/", "trans": "followers", "col": "loyal follower", "ex": "He has many followers on Twitter."},
    "following": {"def": "接著的、下列的", "ipa": "/ˈfɒləʊɪŋ/", "trans": "followed", "col": "the following day, as following", "ex": "The following day was a sunny day."},
    "fond": {"def": "熱愛的、溫情脈脈的", "ipa": "/fɒnd/", "trans": "fondly", "col": "be fond of", "ex": "I am very fond of chocolate."},
    "food": {"def": "食物", "ipa": "/fuːd/", "trans": "foods", "col": "junk food, fast food", "ex": "What's your favorite food?"},
    "fool": {"def": "愚弄、傻瓜", "ipa": "/fuːl/", "trans": "foolish", "col": "play the fool, make a fool of", "ex": "Don't act like a fool."},
    "foolish": {"def": "愚蠢的", "ipa": "/ˈfuːlɪʃ/", "trans": "foolishly", "col": "foolish mistake", "ex": "That was a foolish decision."},
    "foot": {"def": "腳、英尺", "ipa": "/fʊt/", "trans": "feet", "col": "on foot, standard foot", "ex": "I go to school on foot."},
    "football": {"def": "足球、橄欖球", "ipa": "/ˈfʊtbɔːl/", "trans": "footballs", "col": "play football", "ex": "He likes to play football."},
    "for": {"def": "為了、由於、達到", "ipa": "/fɔː/", "trans": "無", "col": "as for, except for", "ex": "I bought this for you."},
    "forbid": {"def": "禁止", "ipa": "/fəˈbɪd/", "trans": "forbade, forbidden", "col": "forbid someone to do", "ex": "Smoking is forbidden in this area."},
    "force": {"def": "力量、強制、暴力", "ipa": "/fɔːs/", "trans": "forced, forceful", "col": "task force, law in force", "ex": "The door was opened by force."},
    "forecast": {"def": "預報、預測", "ipa": "/ˈfɔːkɑːst/", "trans": "forecast, forecast", "col": "weather forecast", "ex": "The weather forecast says it will rain tomorrow."},
    "forehead": {"def": "額頭", "ipa": "/ˈfɒrɪd/", "trans": "foreheads", "col": "high forehead", "ex": "He wiped the sweat from his forehead."},
    "foreign": {"def": "外國的", "ipa": "/ˈfɒrən/", "trans": "foreigner (外國人)", "col": "foreign language, foreign country", "ex": "He can speak two foreign languages."},
    "foreigner": {"def": "外國人", "ipa": "/ˈfɒrənə/", "trans": "foreigners", "col": "resident foreigner", "ex": "The island is popular with foreigners."},
    "foresee": {"def": "預見、預知", "ipa": "/fɔːˈsiː/", "trans": "foreseen", "col": "unforeseen circumstances", "ex": "I can't foresee any problems."},
    "forest": {"def": "森林", "ipa": "/ˈfɒrɪst/", "trans": "forests", "col": "tropical forest, rain forest", "ex": "They are walking in the forest."},
    "forever": {"def": "永遠、長久", "ipa": "/fəˈrevə/", "trans": "無", "col": "last forever", "ex": "I will love you forever."},
    "forfeit": {"def": "喪失、沒收、罰款", "ipa": "/ˈfɔːfɪt/", "trans": "forfeited", "col": "forfeit your right", "ex": "You will forfeit your deposit if you cancel."},
    "forget": {"def": "忘記", "ipa": "/fəˈɡet/", "trans": "forgot, forgotten, forgetful", "col": "forget about it", "ex": "Don't forget to lock the door."},
    "forgetful": {"def": "健忘的", "ipa": "/fəˈɡetfl/", "trans": "forgetfulness", "col": "become forgetful", "ex": "My grandfather is becoming forgetful."},
    "forgive": {"def": "原諒", "ipa": "/fəˈɡɪv/", "trans": "forgave, forgiven, forgiveness", "col": "forgive someone for", "ex": "Please forgive me for my mistake."},
    "forgiveness": {"def": "寬恕、原諒", "ipa": "/fəˈɡɪvnəs/", "trans": "forgive (動詞)", "col": "ask for forgiveness", "ex": "She asked for my forgiveness."},
    "fork": {"def": "叉子、分叉路", "ipa": "/fɔːk/", "trans": "forks", "col": "knife and fork", "ex": "I can't eat with a knife and fork."},
    "form": {"def": "形式、表格、構成", "ipa": "/fɔːm/", "trans": "formed, formation", "col": "application form, in the form of", "ex": "Please fill in this form."},
    "formal": {"def": "正式的、外形的", "ipa": "/ˈfɔːml/", "trans": "formally", "col": "formal dress, formal education", "ex": "We had a formal dinner tonight."},
    "formation": {"def": "形成、構造、編隊", "ipa": "/fɔːˈmeɪʃn/", "trans": "form (名詞/動詞)", "col": "rock formation", "ex": "The planes were flying in formation."},
    "former": {"def": "前者、以前的", "ipa": "/ˈfɔːmə/", "trans": "formerly", "col": "former president", "ex": "He is a former classmate of mine."},
    "formerly": {"def": "以前、從前地", "ipa": "/ˈfɔːməli/", "trans": "former (形容詞)", "col": "formerly known as", "ex": "Thailand was formerly known as Siam."},
    "formidable": {"def": "可怕的、強大的、難對付的", "ipa": "/fəˈmɪdəbl/", "trans": "formidably", "col": "formidable opponent", "ex": "He is a formidable opponent."},
    "formula": {"def": "配方、公式、客套語", "ipa": "/ˈfɔːmjələ/", "trans": "formulas/formulae", "col": "mathematical formula", "ex": "What is the chemical formula for water?"},
    "fort": {"def": "堡壘", "ipa": "/fɔːt/", "trans": "forts", "col": "build a fort", "ex": "The soldiers defended the fort."},
    "forth": {"def": "向前、向外", "ipa": "/fɔːθ/", "trans": "無", "col": "back and forth, and so forth", "ex": "He walked back and forth in the room."},
    "forthcoming": {"def": "即將到來的、現成的", "ipa": "/ˌfɔːθˈkʌmɪŋ/", "trans": "無", "col": "forthcoming events", "ex": "We are looking forward to the forthcoming trip."},
    "forty": {"def": "/ˈfɔːti/", "trans": "fortieth", "col": "at forty", "ex": "My father is forty years old."},
    "fortune": {"def": "運氣、財富", "ipa": "/ˈfɔːtʃuːn/", "trans": "fortunate (幸運的)", "col": "make a fortune, tell fortune", "ex": "She has a large fortune."},
    "fortunate": {"def": "幸運的、吉祥的", "ipa": "/ˈfɔːtʃənət/", "trans": "fortunately", "col": "be fortunate enough", "ex": "I am fortunate to have such a good family."},
    "fortunately": {"def": "/ˈfɔːtʃənətli/", "trans": "fortunate (形容詞)", "col": "fortunately, the rain stopped", "ex": "Fortunately, we found our lost dog."},
    "fortune-teller": {"def": "算命之師", "ipa": "/ˈfɔːtʃuːn telə/", "trans": "fortune-telling", "col": "visit a fortune-teller", "ex": "She went to a fortune-teller to ask about her future."},
    "forward": {"def": "向前的、轉交", "ipa": "/ˈfɔːwəd/", "trans": "forwarded", "col": "look forward to, move forward", "ex": "Step forward, please."},
    "forward/forwards": {"def": "向前", "ipa": "/ˈfɔːwədz/", "trans": "無", "col": "move forwards", "ex": "The car started to move forwards."},
    "fossil": {"def": "化石、古物", "ipa": "/ˈfɒsl/", "trans": "fossils", "col": "fossil fuel", "ex": "Coal is a types of fossil fuel."},
    "foster": {"def": "培養、收養", "ipa": "/ˈfɒstə/", "trans": "fostered", "col": "foster child", "ex": "They foster children who need a home."},
    "foul": {"def": "卑劣的、犯規、骯髒的", "ipa": "/faʊl/", "trans": "fouled", "col": "foul play, foul language", "ex": "The player committed a foul."},
    "found": {"def": "建立、創立 (find 過去式)", "ipa": "/faʊnd/", "trans": "founded, foundation", "col": "found a school", "ex": "The university was founded in 1900."},
    "foundation": {"def": "基礎、基金會", "ipa": "/faʊnˈdeɪʃn/", "trans": "found (動詞)", "col": "solid foundation", "ex": "The foundation of the building is deep."},
    "founder": {"def": "創立者", "ipa": "/ˈfaʊndə/", "trans": "founders", "col": "co-founder", "ex": "He is the founder of this company."},
    "fountain": {"def": "噴泉、噴水池", "ipa": "/ˈfaʊntən/", "trans": "fountains", "col": "fountain pen", "ex": "The children are playing by the fountain."},
    "four": {"def": "/fɔː/", "trans": "fourth", "col": "four o'clock", "ex": "He has four cousins."},
    "fourteen": {"def": "/ˌfɔːˈtiːn/", "trans": "fourteenth", "col": "at fourteen", "ex": "She is fourteen years old."},
    "fowl": {"def": "家禽、禽肉", "ipa": "/faʊl/", "trans": "fowls", "col": "water fowl", "ex": "The farm has many fowls."},
    "fox": {"def": "狐狸", "ipa": "/fɒks/", "trans": "foxes", "col": "sly fox", "ex": "The sly fox escaped the hunters."},
    "fraction": {"def": "碎片、微量、分數", "ipa": "/ˈfrækʃn/", "trans": "fractions", "col": "only a fraction", "ex": "A fraction of the project has been completed."},
    "fracture": {"def": "斷裂、骨折", "ipa": "/ˈfræktʃə/", "trans": "fractured", "col": "compound fracture", "ex": "He suffered a fracture in his left leg."},
    "fragile": {"def": "脆弱的、易碎的", "ipa": "/ˈfrædʒaɪl/", "trans": "fragility", "col": "fragile peace", "ex": "Be careful; the box is fragile."},
    "fragment": {"def": "碎片、斷片", "ipa": "/ˈfræɡmənt/", "trans": "fragments", "col": "glass fragment", "ex": "The explosion broke the window into fragments."},
    "fragrance": {"def": "芳香、香味", "ipa": "/ˈfreɪɡrəns/", "trans": "fragrant (芳香的)", "col": "sweet fragrance", "ex": "The garden was filled with the fragrance of roses."},
    "fragrant": {"def": "芳香的", "ipa": "/ˈfreɪɡrənt/", "trans": "fragrance (名詞)", "col": "fragrant flowers", "ex": "These roses are very fragrant."},
    "frame": {"def": "框架、骨架、構造", "ipa": "/freɪm/", "trans": "frames, framed", "col": "picture frame, window frame", "ex": "The mirror has a golden frame."},
    "framework": {"def": "框架、構架、體制", "ipa": "/ˈfreɪmwɜːk/", "trans": "frameworks", "col": "conceptual framework", "ex": "They established a solid legal framework."},
    "France": {"def": "法國", "ipa": "/frɑːns/", "trans": "French (法國的/人/語)", "col": "Paris, France", "ex": "Paris is the capital of France."},
    "frank": {"def": "坦白的", "ipa": "/fræŋk/", "trans": "frankly", "col": "to be frank", "ex": "To be frank, I don't like the idea."},
    "frankly": {"def": "/ˈfræŋkli/", "trans": "frank (形容詞)", "col": "frankly speaking", "ex": "Frankly speaking, I don't care at all."},
    "frantic": {"def": "狂亂的、發瘋似的", "ipa": "/ˈfræntɪk/", "trans": "frantically", "col": "frantic efforts", "ex": "They made frantic efforts to save the child."},
    "fraud": {"def": "詐騙、騙子", "ipa": "/frɔːd/", "trans": "fraudulent", "col": "credit card fraud", "ex": "He was arrested for credit card fraud."},
    "freak": {"def": "畸形、奇想、怪胎", "ipa": "/friːk/", "trans": "freaky", "col": "fitness freak", "ex": "The weather was strange, a real freak of nature."},
    "free": {"def": "自由的、免費的", "ipa": "/friː/", "trans": "freely, freedom", "col": "free of charge, set free", "ex": "The coffee is free."},
    "freedom": {"def": "自由", "ipa": "/ˈfriːdəm/", "trans": "free (形容詞)", "col": "freedom of speech", "ex": "They were fighting for their freedom."},
    "freely": {"def": "/ˈfriːli/", "trans": "free (形容詞)", "col": "speak freely", "ex": "You can speak freely here."},
    "freeze": {"def": "結冰、冷凍", "ipa": "/friːz/", "trans": "froze, frozen", "col": "freezing point", "ex": "Water freezes at 0 degrees Celsius."},
    "freezer": {"def": "冰箱、冷凍庫", "ipa": "/ˈfriːzə/", "trans": "freezers", "col": "chest freezer", "ex": "Put the meat in the freezer."},
    "freezing": {"def": "冰凍的、寒冷的", "ipa": "/ˈfriːzɪŋ/", "trans": "freeze (動詞)", "col": "freezing cold", "ex": "It's freezing outside; wear a coat."},
    "freight": {"def": "運費、貨運", "ipa": "/freɪt/", "trans": "freighted", "col": "freight charges", "ex": "The goods were sent by air freight."},
    "French": {"def": "法國的、法國人、法文", "ipa": "/frentʃ/", "trans": "無", "col": "speak French, French fries", "ex": "He likes French wine."},
    "frequency": {"def": "頻率、頻繁", "ipa": "/ˈfriːkwənsi/", "trans": "frequencies", "col": "high frequency", "ex": "The frequency of the bus service has increased."},
    "frequent": {"def": "頻繁的", "ipa": "/ˈfriːkwənt/", "trans": "frequently", "col": "frequent visitor", "ex": "Earthquakes are frequent in this area."},
    "frequently": {"def": "/ˈfriːkwəntli/", "trans": "frequent (形容詞)", "col": "frequently asked questions", "ex": "He frequently goes to London on business."},
    "fresh": {"def": "新鮮的", "ipa": "/freʃ/", "trans": "freshly, freshness", "col": "fresh water, fresh fruit", "ex": "I like fresh orange juice."},
    "freshman": {"def": "大一新生、才進步者", "ipa": "/ˈfreʃmən/", "trans": "freshmen", "col": "college freshman", "ex": "He is a freshman at university."},
    "freshness": {"def": "新鮮、活力", "ipa": "/ˈfreʃnəs/", "trans": "fresh (形容詞)", "col": "guarantee freshness", "ex": "Keep the fish in ice to maintain its freshness."},
    "friction": {"def": "摩擦力、衝突", "ipa": "/ˈfrɪkʃn/", "trans": "frictions", "col": "reduce friction", "ex": "We need to reduce the friction between the two teams."},
    "Friday": {"def": "星期五", "ipa": "/ˈfraɪdeɪ/", "trans": "無", "col": "on Friday", "ex": "We have an English lesson on Friday."},
    "fridge/refrigerator": {"def": "冰箱", "ipa": "/frɪdʒ/", "trans": "fridges", "col": "in the fridge", "ex": "The milk is in the fridge."},
    "friend": {"def": "朋友", "ipa": "/frend/", "trans": "friendly, friendship", "col": "make friends, close friend", "ex": "He is my best friend."},
    "friendly": {"def": "友好的", "ipa": "/ˈfrendli/", "trans": "friendliness", "col": "environmentally friendly", "ex": "The people here are very friendly."},
    "friendship": {"def": "友誼", "ipa": "/ˈfrendʃɪp/", "trans": "friendships", "col": "lifelong friendship", "ex": "We value our friendship highly."},
    "fright": {"def": "驚嚇、恐怖", "ipa": "/fraɪt/", "trans": "frighten (使驚嚇), frightening (可怕的)", "col": "stage fright", "ex": "She was shaking with fright."},
    "frighten": {"def": "使驚嚇", "ipa": "/ˈfraɪtn/", "trans": "frightened", "col": "frighten away", "ex": "Darkness frightens the little boy."},
    "frightened": {"def": "感到受驚的", "ipa": "/ˈfraɪtnd/", "trans": "frighten (動詞)", "col": "be frightened of", "ex": "He is frightened of spiders."},
    "frightening": {"def": "可怕的、嚇人的", "ipa": "/ˈfraɪtnɪŋ/", "trans": "frighteningly", "col": "frightening experience", "ex": "It was a frightening situation."},
    "frog": {"def": "青蛙", "ipa": "/frɒɡ/", "trans": "frogs", "col": "bull frog", "ex": "A frog is jumping into the pond."},
    "from": {"def": "來自、從", "ipa": "/frəm/", "trans": "無", "col": "from A to B, come from", "ex": "Where are you from?"},
    "front": {"def": "前面、前面的", "ipa": "/frʌnt/", "trans": "frontier (國境)", "col": "in front of, at the front", "ex": "There is a park in front of the house."},
    "frontier": {"def": "邊境、新領域", "ipa": "/ˈfrʌntɪə/", "trans": "frontiers", "col": "expand frontiers", "ex": "They were stopped at the frontier."},
    "frost": {"def": "霜、冰凍", "ipa": "/frɒst/", "trans": "frosty", "col": "heavy frost", "ex": "The ground was white with frost."},
    "frown": {"def": "皺眉、反對", "ipa": "/fraʊn/", "trans": "frowned", "col": "frown on/at", "ex": "She frowned at him in anger."},
    "fruit": {"def": "水果", "ipa": "/fruːt/", "trans": "fruits, fruitful", "col": "fresh fruit, fruit juice", "ex": "I like to eat fresh fruit."},
    "frustrate": {"def": "使挫敗、使沮喪、破壞", "ipa": "/frʌˈstreɪt/", "trans": "frustrated, frustrating, frustration", "col": "frustrate efforts", "ex": "The bad weather frustrated our plans."},
    "frustrated": {"def": "感到挫敗的、沮喪的", "ipa": "/frʌˈstreɪtɪd/", "trans": "frustrate (動詞)", "col": "feel frustrated", "ex": "I feel frustrated by the lack of progress."},
    "frustrating": {"def": "令人沮喪的", "ipa": "/frʌˈstreɪtɪŋ/", "trans": "frustratingly", "col": "frustrating situation", "ex": "It was a very frustrating experience."},
    "frustration": {"def": "挫敗、沮喪", "ipa": "/frʌˈstreɪʃn/", "trans": "frustrations", "col": "sense of frustration", "ex": "He expressed his frustration with the new rules."},
    "fry": {"def": "煎、炸、炒", "ipa": "/fraɪ/", "trans": "fried", "col": "fried chicken, stir-fry", "ex": "I'll fry some eggs for breakfast."},
    "fuel": {"def": "燃料", "ipa": "/ˈfjuːəl/", "trans": "fuelled", "col": "fossil fuel, biofuel", "ex": "The car needs fuel."},
    "fulfill/fulfil": {"def": "履行、實現", "ipa": "/fʊlˈfɪl/", "trans": "fulfillment", "col": "fulfill a dream", "ex": "I hope to fulfill my potential."},
    "fulfillment/fulfilment": {"def": "履行、完成、滿足感", "ipa": "/fʊlˈfɪlmənt/", "trans": "fulfill (動詞)", "col": "self-fulfillment", "ex": "The work gives her a sense of fulfillment."},
    "full": {"def": "充滿的、完全地", "ipa": "/fʊl/", "trans": "fully, fullness", "col": "full name, full time", "ex": "The room was full of children."},
    "fully": {"def": "/ˈfʊli/", "trans": "full (形容詞)", "col": "fully recovered", "ex": "I fully understand the situation."},
    "fun": {"def": "有趣、娛樂", "ipa": "/fʌn/", "trans": "funny (好笑的)", "col": "make fun of, have fun", "ex": "We had a lot of fun at the party."},
    "function": {"def": "功能、函數、活動", "ipa": "/ˈfʌŋkʃn/", "trans": "functional (功能性的)", "col": "vital function", "ex": "What is the function of this machine?"},
    "functional": {"def": "功能性的、實用的", "ipa": "/ˈfʌŋkʃənl/", "trans": "function (名詞/動詞)", "col": "functional design", "ex": "The furniture is not only beautiful but also functional."},
    "fund": {"def": "基金、儲備、資助", "ipa": "/fʌnd/", "trans": "funds, funded, funding", "col": "investment fund, raise funds", "ex": "The project is funded by the government."},
    "fundamental": {"def": "基本的、根本的、基礎", "ipa": "/ˌfʌndəˈmentl/", "trans": "fundamentally", "col": "fundamental change", "ex": "Economic reform is fundamental to success."},
}

with open("batch_l1_p18.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART18, f, ensure_ascii=False, indent=2)
