import json

# Level 1 Part 34: (Nimble - Nunnery)
L1_PART34 = {
    "nimble": {"def": "敏捷的、靈敏的、機智的", "ipa": "/ˈnɪmbl/", "trans": "nimbly, nimbleness", "col": "nimble fingers", "ex": "He is very nimble on his feet."},
    "nine": {"def": "九", "ipa": "/naɪn/", "trans": "ninth", "col": "nine times", "ex": "He had nine cats."},
    "nineteen": {"def": "十九", "ipa": "/ˌnaɪnˈtiːn/", "trans": "nineteenth", "col": "age nineteen", "ex": "She is nineteen years old."},
    "ninety": {"def": "九十", "ipa": "/ˈnaɪnti/", "trans": "ninetieth", "col": "in his nineties", "ex": "My grandmother is ninety years old."},
    "nipple": {"def": "乳頭、奶嘴", "ipa": "/ˈnɪpl/", "trans": "nipples", "col": "rubber nipple", "ex": "The baby is sucking on the nipple."},
    "nitrogen": {"def": "氮氣", "ipa": "/ˈnaɪtrədʒən/", "trans": "無", "col": "liquid nitrogen", "ex": "Air is 78% nitrogen."},
    "no": {"def": "不、沒有、難以、反對票", "ipa": "/nəʊ/", "trans": "無", "col": "no way, no problem", "ex": "I have no money."},
    "nobility": {"def": "貴族(階級)、高尚、壯麗", "ipa": "/nəʊˈbɪləti/", "trans": "noble (形容詞)", "col": "hereditary nobility", "ex": "He was a member of the nobility."},
    "noble": {"def": "高尚的、貴族的、宏偉的、貴族", "ipa": "/ˈnəʊbl/", "trans": "nobler, noblest, nobly", "col": "noble prize, noble gas", "ex": "It was a noble act."},
    "nobody": {"def": "無人、小人物", "ipa": "/ˈnəʊbədi/", "trans": "nobodies", "col": "nobody knows", "ex": "Nobody knows the answer."},
    "nocturnal": {"def": "夜間生成的、夜行性的", "ipa": "/nɒkˈtɜːnl/", "trans": "nocturnally", "col": "nocturnal animals", "ex": "Bats are nocturnal animals."},
    "nod": {"def": "點頭、打盹、示意", "ipa": "/nɒd/", "trans": "nodded", "col": "nod one's head", "ex": "He nodded in agreement."},
    "node": {"def": "結、節點、中心點", "ipa": "/nəʊd/", "trans": "nodes", "col": "network node", "ex": "Each computer in the network is a node."},
    "noise": {"def": "噪音、聲響、喧嘩", "ipa": "/nɔɪz/", "trans": "noises, noisy", "col": "loud noise, white noise", "ex": "Don't make so much noise."},
    "noisy": {"def": "嘈雜的、喧鬧的", "ipa": "/ˈnɔɪzi/", "trans": "noisier, noisiest, noisily", "col": "noisy neighbors", "ex": "The street is very noisy."},
    "nominate": {"def": "提名、任命", "ipa": "/ˈnɒmɪneɪt/", "trans": "nominated, nomination", "col": "nominate someone for", "ex": "I nominate you as our leader."},
    "nomination": {"def": "提名、任命、提名權", "ipa": "/ˌnɒmɪˈneɪʃn/", "trans": "nominations, nominate (動詞)", "col": "presidential nomination", "ex": "He won the nomination for president."},
    "nominee": {"def": "被提名者", "ipa": "/ˌnɒmɪˈniː/", "trans": "nominees", "col": "award nominee", "ex": "Who are the nominees for Best Actor?"},
    "non": {"def": "不、非 (字首)", "ipa": "/nɒn/", "trans": "無", "col": "non-stop, non-verbal", "ex": "He signed a non-disclosure agreement."},
    "none": {"def": "一點也不、沒一個", "ipa": "/nʌn/", "trans": "無", "col": "none of your business", "ex": "None of the students was late."},
    "nonetheless": {"def": "儘管如此、然而", "ipa": "/ˌnʌnðəˈles/", "trans": "nevertheless", "col": "but nonetheless", "ex": "It was a difficult task; nonetheless, we succeeded."},
    "non-fiction": {"def": "非小說類寫實文學", "ipa": "/ˌnɒn ˈfɪkʃn/", "trans": "fiction (小說)", "col": "read non-fiction", "ex": "I prefer reading non-fiction."},
    "nonsense": {"def": "廢話、荒唐、胡鬧", "ipa": "/ˈnɒnsns/", "trans": "nonsensical", "col": "talk nonsense", "ex": "That's pure nonsense."},
    "non-smoker": {"def": "不抽菸者、禁菸車廂", "ipa": "/ˌnɒn ˈsməʊkə/", "trans": "smoker (抽菸者)", "col": "designated non-smoker area", "ex": "The restaurant is for non-smokers."},
    "non-stop": {"def": "不停的、直達的", "ipa": "/ˌnɒn ˈstɒp/", "trans": "無", "col": "non-stop flight", "ex": "We took a non-stop flight to New York."},
    "noodle": {"def": "麵條、笨人", "ipa": "/ˈnuːdl/", "trans": "noodles", "col": "instant noodles", "ex": "I like to eat noodles for lunch."},
    "noon": {"def": "正午、中午", "ipa": "/nuːn/", "trans": "無", "col": "at noon", "ex": "The sun is hot at noon."},
    "nor": {"def": "也不、也沒有", "ipa": "/nɔː/", "trans": "無", "col": "neither...nor...", "ex": "I don't like tea, nor does my mother."},
    "normal": {"def": "正常的、正規的、標準的、師範的", "ipa": "/ˈnɔːml/", "trans": "normally, normality, nightmare", "col": "normal distribution, return to normal", "ex": "It's normal to feel tired."},
    "normality": {"def": "正常、常態", "ipa": "/nɔːˈmæləti/", "trans": "normal (形容詞)", "col": "sense of normality", "ex": "Life is slowly returning to normality."},
    "normally": {"def": "/ˈ常规 /", "trans": "normal (形容詞)", "col": "behave normally", "ex": "I normally get up at seven."},
    "north": {"def": "北方、北部的", "ipa": "/nɔːθ/", "trans": "northern", "col": "north pole, go north", "ex": "The wind is blowing from the north."},
    "northern": {"def": "北方的、北部的", "ipa": "/ˈnɔːðən/", "trans": "north (名詞)", "col": "northern lights", "ex": "I grew up in a northern town."},
    "northwest": {"def": "西北方", "ipa": "/ˌnɔːθˈwest/", "trans": "northwestern", "col": "towards northwest", "ex": "The storm is moving northwest."},
    "nose": {"def": "鼻子、嗅覺、探聽", "ipa": "/nəʊz/", "trans": "noses, nosey", "col": "runny nose, nose bleed", "ex": "She has a sharp nose."},
    "nostril": {"def": "鼻孔", "ipa": "/ˈnɒstrəl/", "trans": "nostrils", "col": "right/left nostril", "ex": "Dust entered his nostrils."},
    "not": {"def": "不、並非", "ipa": "/nɒt/", "trans": "無", "col": "not at all, not only", "ex": "I am not a student."},
    "notable": {"def": "顯著的、值得注意的、名人", "ipa": "/ˈnəʊtəbl/", "trans": "notably", "col": "notable achievement", "ex": "Her achievement was notable."},
    "notably": {"def": "顯著地、尤其、特別是", "ipa": "/ˈnəʊtəbli/", "trans": "notable (形容詞)", "col": "notably successful", "ex": "The economy has improved, notably in the manufacturing sector."},
    "note": {"def": "筆記、便條、音符、紙幣、注意", "ipa": "/nəʊt/", "trans": "noted, notebook", "col": "take notes, post-it note", "ex": "I took notes during the lecture."},
    "notebook": {"def": "筆記本、筆記型電腦", "ipa": "/ˈnəʊtbʊk/", "trans": "notebooks", "col": "spiral notebook", "ex": "She is writing in her notebook."},
    "noted": {"def": "著名的、顯著的", "ipa": "/ˈnəʊtɪd/", "trans": "note (名詞/動詞)", "col": "well noted, noted for", "ex": "He is a noted scientist."},
    "nothing": {"def": "無、沒什麼、微不足道的人事物", "ipa": "/ˈnʌθɪŋ/", "trans": "無", "col": "nothing else, for nothing", "ex": "There is nothing in the box."},
    "notice": {"def": "注意、通知、公告", "ipa": "/ˈnəʊtɪs/", "trans": "noticed, noticeable", "col": "take notice of, short notice", "ex": "Did you notice his new car?"},
    "noticeable": {"def": "明顯的、值得注意的", "ipa": "/ˈnəʊtɪsəbl/", "trans": "noticeably", "col": "noticeable difference", "ex": "There's a noticeable difference between the two."},
    "noticeably": {"def": "/ˈnəʊtɪsəbli/", "trans": "noticeable (形容詞)", "col": "change noticeably", "ex": "The weather has turned noticeably cooler."},
    "notify": {"def": "通知、報告", "ipa": "/ˈnəʊtɪfaɪ/", "trans": "notified, notification", "col": "notify someone of", "ex": "Please notify us of any changes."},
    "notion": {"def": "概念、意圖、見解、小飾品", "ipa": "/ˈnəʊʃn/", "trans": "notions", "col": "preconceived notion", "ex": "I have no notion of what he means."},
    "notorious": {"def": "惡名昭彰的", "ipa": "/nəʊˈtɔːriəs/", "trans": "notoriously", "col": "notorious criminal", "ex": "He is a notorious liar."},
    "notwithstanding": {"def": "儘管、雖然", "ipa": "/ˌnɒtwɪθˈstændɪŋ/", "trans": "nevertheless", "col": "notwithstanding the difficulties", "ex": "Notwithstanding the bad weather, they went out."},
    "noun": {"def": "名詞", "ipa": "/naʊn/", "trans": "nouns", "col": "proper noun", "ex": "The word 'dog' is a noun."},
    "nourish": {"def": "滋養、養育、懷有(希望等)", "ipa": "/ˈnʌrɪʃ/", "trans": "nourished, nourishment", "col": "nourish hope", "ex": "The food contains everything to nourish the body."},
    "nourishment": {"def": "營養、食物", "ipa": "/ˈnʌrɪʃmənt/", "trans": "nourish (動詞)", "col": "spiritual nourishment", "ex": "Children need plenty of nourishment."},
    "novel": {"def": "小說、新奇的", "ipa": "/ˈnɒvl/", "trans": "novels, novelist, novelty", "col": "historical novel, detective novel", "ex": "He is writing a new novel."},
    "novelist": {"def": "小說家", "ipa": "/ˈnɒvəlɪst/", "trans": "novelists", "col": "prolific novelist", "ex": "Charles Dickens was a famous novelist."},
    "novelty": {"def": "新奇、新穎、新奇物品", "ipa": "/ˈnɒvlti/", "trans": "novelties", "col": "lack of novelty", "ex": "The novelty of the new job soon wore off."},
    "November": {"def": "十一月", "ipa": "/nəʊˈvembə/", "trans": "無", "col": "late November", "ex": "Thanksgiving is in November."},
    "now": {"def": "現在、立刻", "ipa": "/naʊ/", "trans": "nowadays", "col": "now and then, right now", "ex": "I am busy now."},
    "nowadays": {"def": "現今、時下", "ipa": "/ˈnaʊədeɪz/", "trans": "now (名詞)", "col": "young people nowadays", "ex": "Nowadays, everyone has a mobile phone."},
    "nowhere": {"def": "無處、哪裡都沒有", "ipa": "/ˈnəʊ weə/", "trans": "無", "col": "nowhere else", "ex": "I have nowhere to go."},
    "nozzle": {"def": "噴嘴、槍口", "ipa": "/ˈnɒzl/", "trans": "nozzles", "col": "hose nozzle", "ex": "Water sprayed from the nozzle."},
    "nuclear": {"def": "核子的、核心的", "ipa": "/ˈnjuːkliə/", "trans": "nucleus", "col": "nuclear energy, nuclear family", "ex": "The country has nuclear weapons."},
    "nucleus": {"def": "核心、核、原子核", "ipa": "/ˈnjuːkliəs/", "trans": "nuclei", "col": "cell nucleus", "ex": "The nucleus is the center of the atom."},
    "nude": {"def": "裸體的、裸體畫", "ipa": "/njuːd/", "trans": "nudity", "col": "paint a nude", "ex": "The artist is painting a nude."},
    "nudity": {"def": "裸露、裸體", "ipa": "/ˈnjuːdəti/", "trans": "nude (形容詞)", "col": "public nudity", "ex": "Public nudity is illegal here."},
    "nuisance": {"def": "討厭的人事物、妨害行為", "ipa": "/ˈnjuːsns/", "trans": "nuisances", "col": "public nuisance", "ex": "It's a nuisance to have to do it again."},
    "null": {"def": "無效的、零的", "ipa": "/nʌl/", "trans": "nullify", "col": "null and void", "ex": "The contract is now null and void."},
    "numb": {"def": "麻木的、失去感覺的、使麻木", "ipa": "/nʌm/", "trans": "numbed, numbness", "col": "numb with cold", "ex": "My fingers are numb with cold."},
    "number": {"def": "號碼、數字、數量、編號", "ipa": "/ˈnʌmbə/", "trans": "numbers, numbered", "col": "phone number, lucky number", "ex": "My phone number is 123456."},
    "numerous": {"def": "許多的、為數眾多的", "ipa": "/ˈnjuːmərəs/", "trans": "numerously", "col": "numerous complaints", "ex": "I've visited Paris numerous times."},
    "nun": {"def": "尼姑、修女", "ipa": "/nʌn/", "trans": "nunnery", "col": "Catholic nun", "ex": "She decided to become a nun."},
    "nunnery": {"def": "女修道院、尼姑庵", "ipa": "/ˈnʌnəri/", "trans": "nunnery", "col": "enter a nunnery", "ex": "Get thee to a nunnery!"},
}

with open("batch_l1_p34.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART34, f, ensure_ascii=False, indent=2)
