import json

# Level 1 Part 32: (Must - Negotiable)
L1_PART32 = {
    "must": {"def": "必須、肯定、必備的人事物", "ipa": "/mʌst/", "trans": "無", "col": "must-have, must-see", "ex": "I must go now."},
    "mustache/mouseteche": {"def": "鬍鬚、翹鬍子", "ipa": "/məˈstɑːʃ/", "trans": "mustaches", "col": "grow a mustache", "ex": "He is growing a mustache."},
    "mustard": {"def": "芥末、芥末色", "ipa": "/ˈ常规 /", "trans": "無", "col": "honey mustard", "ex": "Do you want mustard on your hot dog?"},
    "mute": {"def": "沈默的、啞巴、弱音器、消音", "ipa": "/mjuːt/", "trans": "muted", "col": "mute button", "ex": "He is mute from birth."},
    "mutter": {"def": "喃喃而言、抱怨、咕嶹", "ipa": "/ˈmʌtə/", "trans": "muttered", "col": "mutter about", "ex": "He muttered something under his breath."},
    "mutton": {"def": "羊肉", "ipa": "/ˈmʌtn/", "trans": "無", "col": "roast mutton", "ex": "They had mutton for dinner."},
    "mutual": {"def": "相互的、彼此的、公有的", "ipa": "/ˈmjuːtʃuəl/", "trans": "mutually", "col": "mutual friend, mutual trust", "ex": "It was a mutual decision."},
    "mutually": {"def": "/ˈmjuːtʃuəli/", "trans": "mutual (形容詞)", "col": "mutually beneficial", "ex": "The two countries reached a mutually beneficial agreement."},
    "my": {"def": "我的", "ipa": "/maɪ/", "trans": "me, mine", "col": "my pleasure, my god", "ex": "This is my book."},
    "myself": {"def": "我自己、我親自", "ipa": "/maɪˈself/", "trans": "無", "col": "help myself", "ex": "I did it myself."},
    "mysterious": {"def": "神秘的、難解的", "ipa": "/mɪˈstɪəriəs/", "trans": "mysteriously", "col": "mysterious figure", "ex": "He is a mysterious person."},
    "mysteriously": {"def": "/mɪˈstɪəriəsli/", "trans": "mysterious (形容詞)", "col": "mysteriously disappear", "ex": "The plane vanished mysteriously."},
    "mystery": {"def": "神秘、奧祕、推理小說", "ipa": "/ˈmɪstri/", "trans": "mysteries, mysterious", "col": "solve a mystery", "ex": "It's a complete mystery to me."},
    "myth": {"def": "神話、虛構的故事/信念", "ipa": "/mɪθ/", "trans": "myths, mythical", "col": "greek myth, urban myth", "ex": "The story is a pure myth."},
    "mythical": {"def": "神話的、虛構的", "ipa": "/ˈmɪθɪkl/", "trans": "myth (名詞)", "col": "mythical creature", "ex": "The dragon is a mythical creature."},
    "mythology": {"def": "神話(學/集)", "ipa": "/mɪˈθɒlədʒi/", "trans": "mythologies", "col": "Greek mythology", "ex": "I'm interested in Greek mythology."},
    "nail": {"def": "指甲、釘子、釘上、捕獲", "ipa": "/neɪl/", "trans": "nails, nailed", "col": "finger nail, hit the nail on the head", "ex": "She is painting her finger nails."},
    "naive/naïve": {"def": "天真的、素樸的、缺乏經驗的", "ipa": "/naɪˈiːv/", "trans": "naivety", "col": "naive belief", "ex": "He is very naive to believe that."},
    "naked": {"def": "裸體的、無遮蔽的、直率的", "ipa": "/ˈneɪkɪd/", "trans": "nakedly", "col": "naked eye, mother naked", "ex": "He escaped from the house half-naked."},
    "name": {"def": "名字、名譽、命名", "ipa": "/neɪm/", "trans": "named, namely (即)", "col": "by name, in the name of", "ex": "What's your name?"},
    "namely": {"def": "即、也就是說", "ipa": "/ˈneɪmli/", "trans": "name (名詞)", "col": "namely, viz.", "ex": "We have three options, namely, stay, leave, or wait."},
    "nap": {"def": "小睡、絨毛", "ipa": "/næp/", "trans": "napped", "col": "take a nap", "ex": "I usually take a nap after lunch."},
    "napkin": {"def": "餐巾、手帕", "ipa": "/ˈnæpkɪn/", "trans": "napkins", "col": "paper napkin", "ex": "Wipe your mouth with a napkin."},
    "narrate": {"def": "敘述、講故事", "ipa": "/nəˈreɪt/", "trans": "narrated, narrative", "col": "narrate a story", "ex": "The old man narrated his adventures to the children."},
    "narrative": {"def": "敘述的、故事的、敘事", "ipa": "/ˈnærətɪv/", "trans": "narratives", "col": "fictional narrative", "ex": "The novel has a non-linear narrative."},
    "narrator": {"def": "解說員、敘述者", "ipa": "/nəˈreɪtə/", "trans": "narrators", "col": "unreliable narrator", "ex": "The narrator of the story is a young girl."},
    "narrow": {"def": "狹窄的、有限的、變狹窄", "ipa": "/ˈnærəʊ/", "trans": "narrower, narrowest, narrowly", "col": "narrow escape, narrow minded", "ex": "The road is very narrow."},
    "narrowly": {"def": "狹窄地、險些", "ipa": "/ˈnærəʊli/", "trans": "narrow (形容詞)", "col": "narrowly avoid", "ex": "He narrowly escaped being hit by a car."},
    "nasal": {"def": "鼻的、鼻音的", "ipa": "/ˈneɪzl/", "trans": "nasally", "col": "nasal cavity, nasal sound", "ex": "He spoke in a nasal voice."},
    "nasty": {"def": "下流的、骯髒的、嚴重的", "ipa": "/ˈnɑːsti/", "trans": "nastier, nastiest", "col": "nasty habit, nasty weather", "ex": "Don't be nasty to your sister."},
    "nation": {"def": "國家、民族", "ipa": "/ˈneɪʃn/", "trans": "nations, national", "col": "united nations, developing nation", "ex": "He is known throughout the nation."},
    "national": {"def": "國家的、全國性的、國民", "ipa": "/ˈnæʃnəl/", "trans": "nationally, nationality", "col": "national anthem, national park", "ex": "Today is a national holiday."},
    "nationality": {"def": "國籍、民族", "ipa": "/ˌnæʃəˈnæləti/", "trans": "nationalities", "col": "dual nationality", "ex": "What is your nationality?"},
    "native": {"def": "本土的、天生的、土著", "ipa": "/ˈneɪtɪv/", "trans": "natives", "col": "native speaker, native land", "ex": "English is not my native language."},
    "natural": {"def": "自然的、天然的、天生的", "ipa": "/ˈnætʃrəl/", "trans": "naturally", "col": "natural beauty, natural resources", "ex": "It's natural to be nervous."},
    "naturally": {"def": "/ˈnætʃrəli/", "trans": "natural (形容詞)", "col": "naturally occurring", "ex": "He is naturally talented."},
    "nature": {"def": "自然、性質、本性", "ipa": "/ˈneɪtʃə/", "trans": "natures, natural", "col": "human nature, by nature", "ex": "Mother Nature is beautiful."},
    "naughty": {"def": "頑皮的、沒禮貌的", "ipa": "/ˈnɔːti/", "trans": "naughtier, naughtiest", "col": "naughty boy", "ex": "Stop being so naughty!"},
    "naval": {"def": "海軍的、軍艦的", "ipa": "/ˈneɪvl/", "trans": "navy (名詞)", "col": "naval base, naval officer", "ex": "He is a retired naval officer."},
    "navigate": {"def": "航行、導航、駕駛", "ipa": "/ˈnævɪɡeɪt/", "trans": "navigated, navigation", "col": "navigate home", "ex": "He uses GPS to navigate."},
    "navigation": {"def": "航行、導航、航空", "ipa": "/ˌnævɪˈɡeɪʃn/", "trans": "navigations", "col": "satellite navigation, navigation system", "ex": "The ship has a modern navigation system."},
    "navigator": {"def": "領航員、導航者", "ipa": "/ˈnævɪɡeɪtə/", "trans": "navigators", "col": "flight navigator", "ex": "The navigator set the course for the ship."},
    "navy": {"def": "海軍、海軍藍", "ipa": "/ˈneɪvi/", "trans": "navies, naval", "col": "royal navy, navy blue", "ex": "He joined the navy after high school."},
    "near": {"def": "近的、靠近之處、靠近", "ipa": "/nɪə/", "trans": "nearer, nearest, nearly", "col": "near future, near by", "ex": "The station is near here."},
    "nearby": {"def": "附近的、在附近", "ipa": "/ˌnɪəˈbaɪ/", "trans": "near (形容詞)", "col": "nearby town", "ex": "He lives in a nearby village."},
    "nearly": {"def": "幾乎、差不多", "ipa": "/ˈnɪəli/", "trans": "near (形容詞)", "col": "nearly finished", "ex": "It's nearly finished."},
    "nearsighted/near-sighted": {"def": "近視的、微視的", "ipa": "/ˌnɪəˈsaɪtɪd/", "trans": "farsighted (遠視的)", "col": "nearsighted person", "ex": "I am nearsighted and need to wear glasses."},
    "neat": {"def": "整潔的、工整的、靈巧的", "ipa": "/niːt/", "trans": "neater, neatest, neatly", "col": "neat handwriting", "ex": "His room is always neat and tidy."},
    "neatly": {"def": "/ˈniːtli/", "trans": "neat (形容詞)", "col": "neatly arranged", "ex": "The books were arranged neatly on the shelf."},
    "necessary": {"def": "必要的、必然的、必需品", "ipa": "/ˈnesəsəri/", "trans": "necessarily, necessity", "col": "if necessary, absolute necessity", "ex": "Sleep is necessary for health."},
    "necessarily": {"def": "必然地、必定", "ipa": "/ˌnesəˈserəli/", "trans": "necessary (形容詞)", "col": "not necessarily", "ex": "The expensive one is not necessarily the best."},
    "necessitate": {"def": "使成為必要、迫使", "ipa": "/nəˈsesɪteɪt/", "trans": "necessitated", "col": "necessitate action", "ex": "The increased crime necessitated new laws."},
    "necessity": {"def": "必要、需要、必需品", "ipa": "/nəˈsesəti/", "trans": "necessities", "col": "absolute necessity", "ex": "Water is a necessity of life."},
    "neck": {"def": "頸部、領子、狹窄部分", "ipa": "/nek/", "trans": "necks, necklace (項圈)", "col": "neck and neck, stiff neck", "ex": "He has a long neck."},
    "necklace": {"def": "項鍊", "ipa": "/ˈnekləs/", "trans": "necklaces", "col": "pearl necklace", "ex": "She is wearing a diamond necklace."},
    "nectar": {"def": "花蜜、甘露", "ipa": "/ˈnektə/", "trans": "nectars", "col": "sweet nectar", "ex": "Bees collect nectar from flowers."},
    "need": {"def": "需要、貧困、必須", "ipa": "/niːd/", "trans": "needed, needy", "col": "in need of, need doing", "ex": "I need your help."},
    "needle": {"def": "針、針葉、縫紉", "ipa": "/ˈniːdl/", "trans": "needles", "col": "sewing needle, knitting needle", "ex": "I need a needle and thread."},
    "needy": {"def": "貧窮的、生活艱苦的", "ipa": "/ˈniːdi/", "trans": "need (名詞)", "col": "needy family", "ex": "The charity provides aid to needy children."},
    "negative": {"def": "負面的、否定的、負電的、底片、否定", "ipa": "/ˈneɡətɪv/", "trans": "negatively", "col": "negative attitude, negative impact", "ex": "The test results were negative."},
    "negotiable": {"def": "可商量的、可轉讓的", "ipa": "/nɪˈɡəʊʃiəbl/", "trans": "negotiate", "col": "non-negotiable", "ex": "The price is negotiable."},
}

with open("batch_l1_p32.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART32, f, ensure_ascii=False, indent=2)
