import json

# Level 1 Part 6: (Boy - Button)
L1_PART6 = {
    "boy": {"def": "男孩", "ipa": "/bɔɪ/", "trans": "boys", "col": "little boy, schoolboy", "ex": "The boy is playing with his toy car."},
    "bracket": {"def": "括號、托架", "ipa": "/ˈbrækɪt/", "trans": "brackets", "col": "in brackets", "ex": "Put your name in brackets at the top."},
    "brain": {"def": "大腦、頭腦", "ipa": "/breɪn/", "trans": "brains", "col": "human brain, brain drain", "ex": "The brain controls the entire body."},
    "brake": {"def": "煞車", "ipa": "/breɪk/", "trans": "braked, braking", "col": "apply the brakes", "ex": "He stepped on the brake to slow down."},
    "branch": {"def": "分枝、分店、部門", "ipa": "/brɑːntʃ/", "trans": "branches", "col": "bank branch, olive branch", "ex": "He climbed up the tree branch."},
    "brand": {"def": "品牌、商標", "ipa": "/brænd/", "trans": "brands", "col": "brand name, brand new", "ex": "Which brand of shoes do you like?"},
    "brass": {"def": "黃銅、銅製樂器", "ipa": "/brɑːs/", "trans": "brassy", "col": "brass band", "ex": "The door handle is made of brass."},
    "brave": {"def": "勇敢的", "ipa": "/breɪv/", "trans": "bravery (勇氣)", "col": "brave man", "ex": "He is very brave to fight for his rights."},
    "bravery": {"def": "勇敢、勇氣", "ipa": "/ˈbreɪvəri/", "trans": "brave (形容詞)", "col": "act of bravery", "ex": "The soldier received a medal for his bravery."},
    "bread": {"def": "麵包", "ipa": "/bred/", "trans": "無 (不可數)", "col": "slice of bread, wholemeal bread", "ex": "I eat bread for breakfast every morning."},
    "break": {"def": "打破、破碎、休息", "ipa": "/breɪk/", "trans": "broke, broken", "col": "have a break, break down", "ex": "Let's take a ten-minute break."},
    "breakfast": {"def": "早餐", "ipa": "/ˈbrekfəst/", "trans": "breakfasts", "col": "eat breakfast", "ex": "What are you having for breakfast?"},
    "breakthrough": {"def": "突破、重大進展", "ipa": "/ˈbreɪkθruː/", "trans": "breakthroughs", "col": "major breakthrough", "ex": "Scientists have made a major breakthrough in cancer research."},
    "breast": {"def": "胸部、乳房", "ipa": "/brest/", "trans": "breasts", "col": "breast milk, chicken breast", "ex": "She fed the baby at her breast."},
    "breath": {"def": "呼吸", "ipa": "/breθ/", "trans": "breathe (動詞)", "col": "out of breath, take a deep breath", "ex": "She took a deep breath before jumping into the water."},
    "breathe": {"def": "呼吸", "ipa": "/briːð/", "trans": "breathing, breath (名詞)", "col": "breathe in/out", "ex": "It's difficult to breathe at high altitudes."},
    "breeze": {"def": "微風", "ipa": "/briːz/", "trans": "breezy", "col": "gentle breeze, sea breeze", "ex": "A cool breeze blew from the sea."},
    "brick": {"def": "磚塊", "ipa": "/brɪk/", "trans": "bricks", "col": "brick wall, red brick", "ex": "The house is made of red bricks."},
    "bride": {"def": "新娘", "ipa": "/braɪd/", "trans": "brides", "col": "bride and groom", "ex": "The bride was wearing a beautiful white dress."},
    "bridegroom/groom": {"def": "新郎", "ipa": "/ˈbraɪdɡruːm/", "trans": "grooms", "col": "happy groom", "ex": "The groom looked nervous during the ceremony."},
    "bridge": {"def": "橋、橋牌", "ipa": "/brɪdʒ/", "trans": "bridges", "col": "suspension bridge, burn bridges", "ex": "They are building a new bridge over the river."},
    "brief": {"def": "簡短的", "ipa": "/briːf/", "trans": "briefly, briefing", "col": "brief summary", "ex": "He gave a brief description of the incident."},
    "briefly": {"def": "簡短地、暫時地", "ipa": "/ˈbriːfli/", "trans": "brief (形容詞)", "col": "explain briefly", "ex": "He spoke briefly about his travel experiences."},
    "bright": {"def": "明亮的、聰明的", "ipa": "/braɪt/", "trans": "brightly, brightness", "col": "bright color, bright student", "ex": "The sun is very bright today."},
    "brilliant": {"def": "燦爛的、卓越的", "ipa": "/ˈbrɪliənt/", "trans": "brilliantly", "col": "brilliant idea, brilliant sunshine", "ex": "He gave a brilliant performance."},
    "bring": {"def": "帶來", "ipa": "/brɪŋ/", "trans": "brought, brought", "col": "bring up, bring about", "ex": "Can you bring me some water?"},
    "Britain": {"def": "英國", "ipa": "/ˈbrɪtn/", "trans": "British (英國的)", "col": "Great Britain", "ex": "London is the capital of Britain."},
    "British": {"def": "英國的、英國人", "ipa": "/ˈbrɪtɪʃ/", "trans": "無", "col": "British English", "ex": "He speaks with a British accent."},
    "broad": {"def": "寬廣的、遼闊的", "ipa": "/brɔːd/", "trans": "broadly, broaden", "col": "broad shoulder, broad smile", "ex": "The river is quite broad at this point."},
    "broadcast": {"def": "廣播、傳播", "ipa": "/ˈbrɔːdkɑːst/", "trans": "broadcast/broadcasted", "col": "news broadcast, live broadcast", "ex": "The news is broadcast every hour."},
    "broke": {"def": "破產的、身無分文的", "ipa": "/brəʊk/", "trans": "break (動詞過去式)", "col": "go broke", "ex": "He spent all his money and went broke."},
    "brother": {"def": "兄弟", "ipa": "/ˈbrʌðə/", "trans": "brothers", "col": "older/younger brother", "ex": "My brother is older than me."},
    "brown": {"def": "褐色的、棕色的", "ipa": "/braʊn/", "trans": "browned, brownish", "col": "brown eyes, brown hair", "ex": "He has dark brown eyes."},
    "browse": {"def": "瀏覽、放牧", "ipa": "/braʊz/", "trans": "browser (瀏覽器)", "col": "browse the web", "ex": "I like to browse through bookstores."},
    "brush": {"def": "刷子、梳子", "ipa": "/brʌʃ/", "trans": "brushes", "col": "hair brush, tooth brush", "ex": "You should brush your teeth twice a day."},
    "bubble": {"def": "氣泡、泡沫", "ipa": "/ˈbʌbl/", "trans": "bubbles", "col": "bubble bath, soap bubbles", "ex": "Children love blowing bubbles."},
    "bucket": {"def": "水桶", "ipa": "/ˈbʌkɪt/", "trans": "buckets", "col": "plastic bucket", "ex": "He filled the bucket with water."},
    "bud": {"def": "芽、苞、花蕾", "ipa": "/bʌd/", "trans": "buds", "col": "in bud", "ex": "The roses are still in bud."},
    "budget": {"def": "預算", "ipa": "/ˈbʌdʒɪt/", "trans": "budgeted, budgetary", "col": "fix a budget, low budget", "ex": "The travel budget is very tight."},
    "buffalo": {"def": "水牛、野牛", "ipa": "/ˈbʌfələʊ/", "trans": "buffalo/buffaloes", "col": "water buffalo", "ex": "A herd of buffalo was grazing in the field."},
    "buffet": {"def": "自助餐", "ipa": "/ˈbʊfeɪ/", "trans": "buffets", "col": "buffet lunch", "ex": "They served a buffet breakfast at the hotel."},
    "bug": {"def": "昆蟲、程式漏洞", "ipa": "/bʌɡ/", "trans": "bugs", "col": "ladybug, computer bug", "ex": "There is a bug on the wall."},
    "build": {"def": "建造、建築", "ipa": "/bɪld/", "trans": "built, building (名詞)", "col": "build up, build a house", "ex": "They are building a new hospital."},
    "builder": {"def": "建築工、建設者", "ipa": "/ˈbɪldə/", "trans": "builders", "col": "professional builder", "ex": "The builder said the house would be ready in May."},
    "building": {"def": "建築物、大樓", "ipa": "/ˈbɪldɪŋ/", "trans": "buildings", "col": "office building, public building", "ex": "That is the tallest building in the city."},
    "bulb": {"def": "燈泡、球莖", "ipa": "/bʌlb/", "trans": "bulbs", "col": "light bulb", "ex": "The light bulb needs to be replaced."},
    "bull": {"def": "公牛", "ipa": "/bʊl/", "trans": "bulls", "col": "bull fight", "ex": "The bull was angry and began to charge."},
    "bullet": {"def": "子彈", "ipa": "/ˈbʊlɪt/", "trans": "bullets", "col": "silver bullet", "ex": "The police found several bullets at the scene."},
    "bulletin": {"def": "公報、公告", "ipa": "/ˈbʊlətɪn/", "trans": "bulletins", "col": "news bulletin, bulletin board", "ex": "I saw the notice on the school bulletin board."},
    "bunch": {"def": "串、束、一群", "ipa": "/bʌntʃ/", "trans": "bunches", "col": "a bunch of flowers, a bunch of grapes", "ex": "He bought a large bunch of bananas."},
    "burden": {"def": "負擔、重擔", "ipa": "/ˈbɜːdn/", "trans": "burdened", "col": "heavy burden, financial burden", "ex": "The tax is a heavy burden on low-income families."},
    "bureau": {"def": "局、司、處", "ipa": "/ˈbjʊərəʊ/", "trans": "bureaus", "col": "travel bureau, Federal Bureau of Investigation", "ex": "He works at the employment bureau."},
    "burn": {"def": "燃燒、燒傷", "ipa": "/bɜːn/", "trans": "burnt/burned", "col": "burn down, sunburn", "ex": "The fire burned all night."},
    "burst": {"def": "爆裂、衝出", "ipa": "/bɜːst/", "trans": "burst, bursting", "col": "burst into tears, burst out laughing", "ex": "The balloon burst with a loud pop."},
    "bury": {"def": "埋葬、隱藏", "ipa": "/ˈberi/", "trans": "buried, burial (葬禮)", "col": "bury a treasure", "ex": "The dog buried a bone in the garden."},
    "bus": {"def": "公車", "ipa": "/bʌs/", "trans": "buses", "col": "bus stop, school bus", "ex": "I go to work by bus."},
    "bush": {"def": "灌木", "ipa": "/bʊʃ/", "trans": "bushes", "col": "rose bush, beat around the bush", "ex": "The child is hiding behind a bush."},
    "business": {"def": "生意、事物、商業", "ipa": "/ˈbɪznəs/", "trans": "businessman (商人)", "col": "business trip, do business", "ex": "None of your business."},
    "businessman": {"def": "商人", "ipa": "/ˈbɪznəsmæn/", "trans": "businessmen", "col": "successful businessman", "ex": "He is a very wealthy businessman."},
    "busy": {"def": "忙碌的", "ipa": "/ˈbɪzi/", "trans": "busily", "col": "be busy with", "ex": "I am too busy to talk to you right now."},
    "but": {"def": "但是、除了", "ipa": "/bʌt/", "trans": "無", "col": "not only... but also", "ex": "She is poor but happy."},
    "butcher": {"def": "屠夫、肉商", "ipa": "/ˈbʊtʃə/", "trans": "butchers", "col": "go to the butcher's", "ex": "The butcher cut the meat for us."},
    "butter": {"def": "奶油", "ipa": "/ˈbʌtə/", "trans": "buttery", "col": "bread and butter", "ex": "Would you like some butter on your bread?"},
    "butterfly": {"def": "蝴蝶", "ipa": "/ˈbʌtəflaɪ/", "trans": "butterflies", "col": "butterfly net", "ex": "A butterfly landed on my hand."},
    "button": {"def": "按鈕、鈕扣", "ipa": "/ˈbʌtn/", "trans": "buttons", "col": "press the button", "ex": "The top button of your shirt is missing."},
}

with open("batch_l1_p6.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART6, f, ensure_ascii=False, indent=2)
