import json

# Level 1 Part 33: (Negotiate - Nightly)
L1_PART33 = {
    "negotiate": {"def": "談判、協商、轉讓、通過", "ipa": "/nɪˈɡəʊʃieɪt/", "trans": "negotiated, negotiation, negotiator", "col": "negotiate with", "ex": "They are negotiating for a peaceful settlement."},
    "negotiation": {"def": "談判、協商、轉讓", "ipa": "/nɪˌɡəʊʃiˈeɪʃn/", "trans": "negotiations, negotiate (動詞)", "col": "under negotiation", "ex": "The details are still under negotiation."},
    "negotiator": {"def": "談判者、協商者", "ipa": "/nɪˈɡəʊʃieɪtə/", "trans": "negotiators", "col": "hostage negotiator", "ex": "He is an experienced negotiator."},
    "neighbor/neighbour": {"def": "鄰居、鄰國、鄰近的", "ipa": "/ˈneɪbə/", "trans": "neighboring, neighborhood", "col": "next-door neighbor", "ex": "He is my neighbor."},
    "neighborhood/neighbourhood": {"def": "鄰近地區、街坊、鄰里", "ipa": "/ˈneɪbəhʊd/", "trans": "neighborhoods", "col": "in the neighborhood", "ex": "I live in a quiet neighborhood."},
    "neighboring/neighbouring": {"def": "鄰近的、接壤的", "ipa": "/ˈneɪbərɪŋ/", "trans": "neighbor (名詞)", "col": "neighboring countries", "ex": "We visited several neighboring towns."},
    "neither": {"def": "兩者都不、也不", "ipa": "/ˈnaɪðə/", "trans": "either (兩者之一)", "col": "neither...nor...", "ex": "Neither of them was there."},
    "neon": {"def": "氖、霓虹燈", "ipa": "/ˈniːɒn/", "trans": "neons", "col": "neon sign, neon light", "ex": "The streets were bright with neon signs."},
    "nephew": {"def": "姪子、外甥", "ipa": "/ˈnefjuː/", "trans": "niece (姪女)", "col": "paternal nephew", "ex": "He is my favorite nephew."},
    "nerve": {"def": "神經、勇氣、膽量", "ipa": "/nɜːv/", "trans": "nerves, nervous", "col": "get on someone's nerves, loss of nerve", "ex": "It takes a lot of nerve to do that."},
    "nervous": {"def": "緊張的、神經的", "ipa": "/ˈnɜːvəs/", "trans": "nervously, nervousness", "col": "nervous system, feel nervous", "ex": "I feel nervous about the exam."},
    "nervousness": {"def": "緊張、神經質", "ipa": "/ˈnɜːvəsnəs/", "trans": "nervous (形容詞)", "col": "show nervousness", "ex": "His nervousness was apparent to all."},
    "nest": {"def": "鳥巢、窩、營巢", "ipa": "/nest/", "trans": "nested", "col": "bird's nest", "ex": "The bird's nest was in the tree."},
    "net": {"def": "網、純利、純的、網住", "ipa": "/net/", "trans": "nets, netted", "col": "fish net, net weight", "ex": "They caught the fish in a net."},
    "network": {"def": "網路、廣播網、人際網", "ipa": "/ˈnetwɜːk/", "trans": "networks", "col": "computer network, social network", "ex": "The computer network is down."},
    "neural": {"def": "神經的", "ipa": "/ˈnjʊərəl/", "trans": "neuro (字根)", "col": "neural network", "ex": "The neural system is complex."},
    "neurobiology": {"def": "神經生物學", "ipa": "/ˌnjʊərəʊbaɪˈɒlədʒi/", "trans": "neurobiologist", "col": "human neurobiology", "ex": "He is studying neurobiology at the university."},
    "neutral": {"def": "中立的、中性的、空檔、中立者", "ipa": "/ˈnjuːtrəl/", "trans": "neutrality", "col": "neutral gear, neutral stance", "ex": "Switzerland is a neutral country."},
    "neutrality": {"def": "中立、中性", "ipa": "/njuːˈtræləti/", "trans": "neutral (形容詞)", "col": "strict neutrality", "ex": "They declared strict neutrality in the war."},
    "never": {"def": "從不、絕不", "ipa": "/ˈnevə/", "trans": "nevermore", "col": "never mind, never again", "ex": "I've never been to Paris."},
    "nevertheless": {"def": "儘管如此、然而、仍然", "ipa": "/ˌnevəðəˈles/", "trans": "none the less", "col": "but nevertheless", "ex": "It was very hot; nevertheless, we worked all day."},
    "new": {"def": "新的、新近地", "ipa": "/njuː/", "trans": "newer, newest, newly, newness", "col": "new year, what's new?", "ex": "I bought a new car."},
    "newborn": {"def": "新生兒、新生的", "ipa": "/ˈnjuːbɔːn/", "trans": "newborns", "col": "newborn baby", "ex": "The mother held her newborn baby."},
    "newcomer": {"def": "新來者", "ipa": "/ˈnjuːkʌmə/", "trans": "newcomers", "col": "relative newcomer", "ex": "He is a newcomer to the neighborhood."},
    "newly": {"def": "新近、重新地", "ipa": "/ˈnjuːli/", "trans": "new (形容詞)", "col": "newly married", "ex": "They are a newly married couple."},
    "newlyweds": {"def": "新婚夫婦", "ipa": "/ˈnjuːliwedz/", "trans": "newlywed", "col": "celebrate newlyweds", "ex": "The newlyweds are on their honeymoon."},
    "news": {"def": "新聞、消息", "ipa": "/njuːz/", "trans": "newspaper", "col": "latest news, break the news", "ex": "Have you heard the news?"},
    "newspaper": {"def": "報紙", "ipa": "/ˈnjuːzpeɪpə/", "trans": "newspapers", "col": "daily newspaper", "ex": "He reads the newspaper every morning."},
    "next": {"def": "下一個、鄰近的、在此之後", "ipa": "/nekst/", "trans": "無", "col": "next time, next to", "ex": "What's the next step?"},
    "nibble": {"def": "細咬、輕咬、小食", "ipa": "/ˈnɪbl/", "trans": "nibbled", "col": "nibble on", "ex": "The fish were nibbling on the bait."},
    "nice": {"def": "好的、親切的、精細的", "ipa": "/naɪs/", "trans": "nicer, nicest, nicely", "col": "nice to meet you", "ex": "It's a nice day."},
    "nicely": {"def": "/ˈnaɪsli/", "trans": "nice (形容詞)", "col": "work nicely", "ex": "The plan worked nicely."},
    "nick": {"def": "刻痕、缺口、在關鍵時刻、刻跡", "ipa": "/nɪk/", "trans": "nicked", "col": "in the nick of time", "ex": "He arrived in the nick of time."},
    "nickel": {"def": "鎳、五分幣", "ipa": "/ˈnɪkl/", "trans": "nickels", "col": "plated with nickel", "ex": "He gave me a nickel."},
    "nickname": {"def": "綽號、別名", "ipa": "/ˈnɪkneɪm/", "trans": "nicknamed", "col": "common nickname", "ex": "His nickname is 'Giant'."},
    "nicotine": {"def": "尼古丁", "ipa": "/ˈnɪkətiːn/", "trans": "無", "col": "nicotine patch", "ex": "Cigarettes contain nicotine."},
    "niece": {"def": "姪女、外甥女", "ipa": "/niːs/", "trans": "nephew (姪子)", "col": "maternal niece", "ex": "She is my youngest niece."},
    "night": {"def": "夜晚", "ipa": "/naɪt/", "trans": "nights, nightly", "col": "at night, good night", "ex": "He works at night."},
    "nightingale": {"def": "夜鶯", "ipa": "/ˈnaɪtɪŋɡeɪl/", "trans": "nightingales", "col": "singing nightingale", "ex": "The nightingale sings at night."},
    "nightly": {"def": "每夜的、每晚地", "ipa": "/ˈnaɪtli/", "trans": "night (名詞)", "col": "nightly news", "ex": "The museum is guarded nightly."},
}

with open("batch_l1_p33.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART33, f, ensure_ascii=False, indent=2)
