import json

# Level 1 Part 15: (Exert - Fan)
L1_PART15 = {
    "exert": {"def": "努力、發揮、運用", "ipa": "/ɪɡˈzɜːt/", "trans": "exertion (名詞)", "col": "exert pressure", "ex": "He exerted all his strength to open the door."},
    "exertion": {"def": "努力、發揮、氣力", "ipa": "/ɪɡˈzɜːʃn/", "trans": "exert (動詞)", "col": "physical exertion", "ex": "He was panting with exertion."},
    "exhaust": {"def": "耗盡、排出、廢氣", "ipa": "/ɪɡˈzɔːst/", "trans": "exhausted, exhausting, exhaustion", "col": "exhaust fumes", "ex": "The supply of water was exhausted."},
    "exhausted": {"def": "精疲力竭的", "ipa": "/ɪɡˈzɔːstɪd/", "trans": "exhaust (動詞)", "col": "be exhausted from", "ex": "I am exhausted by the long walk."},
    "exhausting": {"def": "令人精疲力竭的", "ipa": "/ɪɡˈzɔːstɪŋ/", "trans": "exhaustedly", "col": "exhausting work", "ex": "It was an exhausting journey."},
    "exhaustion": {"def": "力竭、盡絕", "ipa": "/ɪɡˈzɔːstʃən/", "trans": "exhaust (動詞)", "col": "die of exhaustion", "ex": "He collapsed from exhaustion."},
    "exhibit": {"def": "展覽、展出、展品", "ipa": "/ɪɡˈzɪbɪt/", "trans": "exhibition", "col": "on exhibit", "ex": "They are exhibiting their works in the gallery."},
    "exhibition": {"def": "展覽會", "ipa": "/ˌeksɪˈbɪʃn/", "trans": "exhibit (動詞)", "col": "art exhibition", "ex": "The exhibition was a huge success."},
    "exile": {"def": "流亡、放逐", "ipa": "/ˈeksaɪl/", "trans": "exiled", "col": "in exile", "ex": "He spent many years in exile in NY."},
    "exist": {"def": "存在、生存", "ipa": "/ɪɡˈzɪst/", "trans": "existence (名詞), existent (存在的)", "col": "exist on", "ex": "The species no longer exists."},
    "existence": {"def": "存在、生存方式", "ipa": "/ɪɡˈzɪstəns/", "trans": "exist (動詞)", "col": "come into existence", "ex": "He lead a miserable existence."},
    "exit": {"def": "出口、退場", "ipa": "/ˈeksɪt/", "trans": "exits", "col": "emergency exit", "ex": "There's an exit at the end of the hall."},
    "expand": {"def": "擴大、膨脹、展開", "ipa": "/ɪkˈspænd/", "trans": "expansion (名詞)", "col": "expand business", "ex": "The company is trying to expand its market."},
    "expansion": {"def": "擴張、膨脹", "ipa": "/ɪkˈspænʃn/", "trans": "expand (動詞)", "col": "rapid expansion", "ex": "The expansion of the economy led to more jobs."},
    "expect": {"def": "期待、預料", "ipa": "/ɪkˈspekt/", "trans": "expectation (名詞)", "col": "expect a baby", "ex": "I expect him to arrive at six."},
    "expectation": {"def": "期待、預期", "ipa": "/ˌekspekˈteɪʃn/", "trans": "expect (動詞)", "col": "beyond expectation", "ex": "High expectations often lead to disappointment."},
    "expedition": {"def": "探險隊、遠征", "ipa": "/ˌekspəˈdɪʃn/", "trans": "expeditions", "col": "arctic expedition", "ex": "He went on an expedition to the South Pole."},
    "expend": {"def": "消費、花費", "ipa": "/ɪkˈspend/", "trans": "expenditure (支出)", "col": "expend time and effort", "ex": "They expended a lot of energy on the project."},
    "expenditure": {"def": "支出、消耗、開支", "ipa": "/ɪkˈspendɪtʃə/", "trans": "expend (動詞)", "col": "annual expenditure", "ex": "Public expenditure on health is increasing."},
    "expense": {"def": "開支、代價", "ipa": "/ɪkˈspens/", "trans": "expenses, expensive", "col": "at the expense of, travel expenses", "ex": "He went there at his own expense."},
    "expensive": {"def": "昂貴的", "ipa": "/ɪkˈspensɪv/", "trans": "expensively", "col": "expensive car", "ex": "Everything is expensive in this city."},
    "experience": {"def": "經驗、經歷", "ipa": "/ɪkˈspɪəriəns/", "trans": "experienced", "col": "work experience", "ex": "I write from my own experience."},
    "experienced": {"def": "有經驗的、老練的", "ipa": "/ɪkˈspɪəriənst/", "trans": "experience (名詞)", "col": "experienced teacher", "ex": "He is an experienced doctor."},
    "experiment": {"def": "實驗、試驗", "ipa": "/ɪkˈsperɪmənt/", "trans": "experimental (實驗性的)", "col": "scientific experiment", "ex": "They are conducting an experiment with a new drug."},
    "experimental": {"def": "實驗性的", "ipa": "/ɪkˌsperɪˈmentl/", "trans": "experimentally", "col": "experimental evidence", "ex": "The drug is still in the experimental stage."},
    "expert": {"def": "專家、熟練的", "ipa": "/ˈekspɜːt/", "trans": "experts, expertise (專業知識)", "col": "technical expert", "ex": "He is an expert in computer science."},
    "expertise": {"def": "專業知識、專長", "ipa": "/ˌekspɜːˈtiːz/", "trans": "expert", "col": "management expertise", "ex": "He has considerable expertise in the field."},
    "expire": {"def": "期滿、斷氣、失效", "ipa": "/ɪkˈspaɪə/", "trans": "expiration (名詞)", "col": "expire date", "ex": "My passport will expire next month."},
    "explain": {"def": "解釋", "ipa": "/ɪkˈspleɪn/", "trans": "explanation (名詞)", "col": "explain why", "ex": "Can you explain this word to me?"},
    "explanation": {"def": "解釋、釋義", "ipa": "/ˌekspləˈneɪʃn/", "trans": "explain (動詞)", "col": "detailed explanation", "ex": "His explanation was very clear."},
    "explicit": {"def": "明確的、坦率的", "ipa": "/ɪkˈsplɪsɪt/", "trans": "explicitly", "col": "explicit instruction", "ex": "The teacher gave us explicit instructions."},
    "explode": {"def": "爆炸、激增", "ipa": "/ɪkˈspləʊd/", "trans": "explosion (名詞)", "col": "explode with anger", "ex": "The plane exploded in the air."},
    "exploit": {"def": "利用、開發、功績", "ipa": "/ɪkˈsplɔɪt/", "trans": "exploitation (名詞)", "col": "exploit natural resources", "ex": "They are trying to exploit the oil fields."},
    "exploitation": {"def": "剝削、開發", "ipa": "/ˌeksplɔɪˈteɪʃn/", "trans": "exploit (動詞)", "col": "sexual exploitation", "ex": "They are fighting against exploitation of labor."},
    "exploration": {"def": "勘查、探險", "ipa": "/ˌekspləˈreɪʃn/", "trans": "explore (勘查)", "col": "space exploration", "ex": "The government funded the exploration of Mars."},
    "explore": {"def": "探究、探險、考察", "ipa": "/ɪkˈsplɔː/", "trans": "explorer (探險家), exploration (名詞)", "col": "explore the cave", "ex": "Let's explore the old town."},
    "explorer": {"def": "探險家", "ipa": "/ɪkˈsplɔːrə/", "trans": "explorers", "col": "famed explorer", "ex": "Columbus was a famous explorer."},
    "explosion": {"def": "爆炸、激增", "ipa": "/ɪkˈspləʊʒn/", "trans": "explode (動詞)", "col": "population explosion", "ex": "A gas explosion killed two people."},
    "explosive": {"def": "爆炸性的、炸藥", "ipa": "/ɪkˈspləʊsɪv/", "trans": "explosives", "col": "explosive power", "ex": "The situation is very explosive."},
    "export": {"def": "出口、輸出品", "ipa": "/ɪkˈspɔːt/", "trans": "exported, exporter", "col": "export license", "ex": "Taiwan exports many electronic products."},
    "expose": {"def": "暴露、揭露、使接觸", "ipa": "/ɪkˈspəʊz/", "trans": "exposed, exposure", "col": "expose to light", "ex": "They were exposed to extreme danger."},
    "exposure": {"def": "暴露、揭露、曝光", "ipa": "/ɪkˈspəʊʒə/", "trans": "expose (動詞)", "col": "indecent exposure", "ex": "Lengthy exposure to the sun is harmful."},
    "express": {"def": "表達、快遞、明確的", "ipa": "/ɪkˈspres/", "trans": "expression (表達), expressive (表現出的)", "col": "express train, an express delivery", "ex": "I'll send it by express delivery."},
    "expression": {"def": "表露、詞句、神色", "ipa": "/ɪkˈspreʃn/", "trans": "express (動詞)", "col": "facial expression, common expression", "ex": "He had a surprised expression on his face."},
    "expressive": {"def": "富於表情的", "ipa": "/ɪkˈspresɪv/", "trans": "expressively", "col": "expressive face", "ex": "She has very expressive eyes."},
    "extend": {"def": "延長、延展、擴大", "ipa": "/ɪkˈstend/", "trans": "extended, extension", "col": "extend a deadline", "ex": "We decided to extend our stay in Japan."},
    "extension": {"def": "延伸、分機、擴張", "ipa": "/ɪkˈstenʃn/", "trans": "extensions, extend (動詞)", "col": "phone extension", "ex": "You can reach him on extension 202."},
    "extensive": {"def": "廣泛的、廣大的", "ipa": "/ɪkˈstensɪv/", "trans": "extensively", "col": "extensive research", "ex": "The building suffered extensive damage."},
    "extent": {"def": "程度、範圍、廣大", "ipa": "/ɪkˈstent/", "trans": "extents", "col": "to some extent, half extent", "ex": "To what extent do you agree with him?"},
    "exterior": {"def": "外表的、外部的", "ipa": "/ɪkˈstɪəriə/", "trans": "interiors (內部的)", "col": "exterior wall", "ex": "The exterior of the house needs painting."},
    "external": {"def": "外部的、對外的", "ipa": "/ɪkˈstɜːnl/", "trans": "externally", "col": "external power", "ex": "Don't judge a person by his external appearance."},
    "extinct": {"def": "絕種的、熄滅的", "ipa": "/ɪkˈstɪŋkt/", "trans": "extinction", "col": "extinct volcano, extinct species", "ex": "Dinosaurs are extinct."},
    "extra": {"def": "額外的、外加地", "ipa": "/ˈekstrə/", "trans": "extras", "col": "extra work, extra charge", "ex": "I need some extra money."},
    "extract": {"def": "取出、摘錄、提取物", "ipa": "/ɪkˈstrækt/", "trans": "extracted, extraction", "col": "extract from", "ex": "The dentist extracted his bad tooth."},
    "extraordinary": {"def": "特別的、非凡的", "ipa": "/ɪkˈstrɔːdnri/", "trans": "extraordinarily", "col": "extraordinary achievement", "ex": "It was an extraordinary performance."},
    "extreme": {"def": "極端的、末端的", "ipa": "/ɪkˈstriːm/", "trans": "extremely", "col": "extreme sports", "ex": "The weather is very extreme here."},
    "extremely": {"def": "極其地、非常", "ipa": "/ɪkˈstriːmli/", "trans": "extreme (形容詞)", "col": "extremely difficult", "ex": "The situation is extremely dangerous."},
    "eye": {"def": "眼睛、視覺、看", "ipa": "/aɪ/", "trans": "eyes", "col": "eyebrow, eyelash, keep an eye on", "ex": "I have something in my eye."},
    "fable": {"def": "寓言、神話", "ipa": "/ˈfeɪbl/", "trans": "fabled", "col": "Aesop's fables", "ex": "He enjoys reading fables for children."},
    "fabric": {"def": "織物、構造", "ipa": "/ˈfæbrɪk/", "trans": "fabrics", "col": "cotton fabric", "ex": "This is a soft cotton fabric."},
    "fabulous": {"def": "極好的、傳說中的", "ipa": "/ˈfæbjələs/", "trans": "fabulously", "col": "fabulous prize", "ex": "We had a fabulous time at the party."},
    "face": {"def": "臉、面對、表面", "ipa": "/feɪs/", "trans": "facial (臉部的)", "col": "face up to, make a face", "ex": "He has a smiling face."},
    "facial": {"def": "面部的、臉部的", "ipa": "/ˈfeɪʃl/", "trans": "face (名詞)", "col": "facial cream, facial expression", "ex": "I applied some facial cream before sleep."},
    "facility": {"def": "設施、設備、熟練", "ipa": "/fəˈsɪləti/", "trans": "facilities", "col": "medical facility, sports facilities", "ex": "The sports facilities in the town are excellent."},
    "fact": {"def": "事實", "ipa": "/fækt/", "trans": "factual (事實的)", "col": "in fact, as a matter of fact", "ex": "I know it to be a fact."},
    "faction": {"def": "派系、派別", "ipa": "/ˈfækʃn/", "trans": "factions", "col": "opposing faction", "ex": "There are different factions within the party."},
    "factor": {"def": "因素、要素", "ipa": "/ˈfæktə/", "trans": "factors", "col": "key factor, risk factor", "ex": "Laziness was the main factor in his failure."},
    "factory": {"def": "工廠", "ipa": "/ˈfæktri/", "trans": "factories", "col": "car factory, shoe factory", "ex": "He works in a shoe factory."},
    "faculty": {"def": "才能、系、全體教員", "ipa": "/ˈfæklti/", "trans": "faculties", "col": "intellectual faculty", "ex": "He has a great faculty for languages."},
    "fade": {"def": "褪色、衰退、消失", "ipa": "/feɪd/", "trans": "faded", "col": "fade away", "ex": "The sun will fade the curtains."},
    "Fahrenheit": {"def": "華氏(的)", "ipa": "/ˈfærənhaɪt/", "trans": "無", "col": "Fahrenheit scale", "ex": "Water boils at 212 degrees Fahrenheit."},
    "fail": {"def": "失敗、不及格", "ipa": "/feɪl/", "trans": "failure (名詞)", "col": "fail to do", "ex": "I failed the driving test."},
    "failure": {"def": "失敗、失敗者", "ipa": "/ˈfeɪljə/", "trans": "fail (動詞)", "col": "total failure", "ex": "The party was a complete failure."},
    "faint": {"def": "微弱的、昏倒", "ipa": "/feɪnt/", "trans": "fainted", "col": "faint smell, feel faint", "ex": "I heard a faint sound from the next room."},
    "fair": {"def": "公平的、美好的、市集", "ipa": "/feə/", "trans": "fairly, fairness", "col": "fair play, trade fair", "ex": "It's not fair to the others."},
    "fairly": {"def": "相當地、公平地", "ipa": "/ˈfeəli/", "trans": "fair (形容詞)", "col": "fairly good", "ex": "He is fairly good at English."},
    "fairness": {"def": "公平、公正", "ipa": "/ˈfeənəs/", "trans": "fair (形容詞)", "col": "sense of fairness", "ex": "He emphasized the importance of fairness."},
    "fairy": {"def": "仙女、精靈", "ipa": "/ˈfeəri/", "trans": "fairies", "col": "fairy tale", "ex": "Her grandmother told her a fairy tale."},
    "faith": {"def": "信仰、信念、信義", "ipa": "/feɪθ/", "trans": "faithful (忠實的)", "col": "religious faith, lose faith", "ex": "She has strong faith in God."},
    "faithful": {"def": "忠實的、守信的", "ipa": "/ˈfeɪθfl/", "trans": "faithfully, faithfulness", "col": "faithful dog", "ex": "He is a faithful friend to me."},
    "fake": {"def": "偽造、冒牌、贗品", "ipa": "/feɪk/", "trans": "faked", "col": "fake news, fake money", "ex": "It turned out to be a fake diamond."},
    "fall": {"def": "落下、秋天、下降", "ipa": "/fɔːl/", "trans": "fell, fallen", "col": "fall asleep, fall down", "ex": "Take care not to fall."},
    "false": {"def": "錯誤的、虛偽的", "ipa": "/fɔːls/", "trans": "falsely, falsehood", "col": "false teeth, true or false", "ex": "He gave the police a false name."},
    "falter": {"def": "蹣跚、動搖、顫抖", "ipa": "/ˈfɔːltə/", "trans": "faltered", "col": "voice falters", "ex": "She faltered for a moment before deciding."},
    "fame": {"def": "名聲、聲望", "ipa": "/feɪm/", "trans": "famous (著名的)", "col": "rise to fame", "ex": "The book brought him instant fame."},
    "familiar": {"def": "熟悉的、親近的", "ipa": "/fəˈmɪliə/", "trans": "familiarly, familiarity", "col": "be familiar with", "ex": "He is familiar with everything here."},
    "familiarity": {"def": "熟悉、世交、親近", "ipa": "/fəˌmɪliˈærəti/", "trans": "familiar (形容詞)", "col": "lack familiarity", "ex": "I don't have much familiarity with the local customs."},
    "family": {"def": "家庭、家族", "ipa": "/ˈfæməli/", "trans": "families", "col": "royal family, family tree", "ex": "He has a very big family."},
    "famine": {"def": "飢荒、嚴重缺乏", "ipa": "/ˈfæmɪn/", "trans": "famines", "col": "catastrophic famine", "ex": "Thousands of people died during the famine."},
    "famous": {"def": "著名的", "ipa": "/ˈfeɪməs/", "trans": "famously", "col": "famous person", "ex": "He is a very famous writer."},
    "fan": {"def": "風扇、扇子、狂熱愛好者", "ipa": "/fæn/", "trans": "fans", "col": "baseball fan, electric fan", "ex": "He is a big fan of rock music."},
}

with open("batch_l1_p15.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART15, f, ensure_ascii=False, indent=2)
