import json

# Level 1 Part 4: (Basics - Beyond)
L1_PART4 = {
    "basics": {"def": "基本原理、基礎", "ipa": "/ˈbeɪsɪks/", "trans": "basic (形容詞)", "col": "back to basics", "ex": "First, you need to learn the basics of cooking."},
    "basis": {"def": "基礎、準則", "ipa": "/ˈbeɪsɪs/", "trans": "bases (複數)", "col": "on a daily basis", "ex": "The decision was made on a scientific basis."},
    "basket": {"def": "籃子", "ipa": "/ˈbæskɪt/", "trans": "baskets", "col": "laundry basket, picnic basket", "ex": "The basket was full of fresh apples."},
    "basketball": {"def": "籃球", "ipa": "/ˈbæskɪtbɔːl/", "trans": "無", "col": "play basketball", "ex": "Basketball is a very popular sport."},
    "bat": {"def": "球棒、蝙蝠", "ipa": "/bæt/", "trans": "bats", "col": "baseball bat", "ex": "A bat is flying in the dark cave."},
    "bath": {"def": "洗澡、浴缸", "ipa": "/bɑːθ/", "trans": "baths", "col": "take a bath", "ex": "The baby is having a bubble bath."},
    "bathe": {"def": "洗澡、游泳", "ipa": "/beɪð/", "trans": "bathed, bathing", "col": "bathe in the sea", "ex": "She bathed her face in cold water."},
    "bathroom": {"def": "浴室", "ipa": "/ˈbɑːθruːm/", "trans": "bathrooms", "col": "clean the bathroom", "ex": "I need to use the bathroom."},
    "battle": {"def": "戰鬥、戰役", "ipa": "/ˈbætl/", "trans": "battled, battling", "col": "win a battle", "ex": "The soldiers fought a difficult battle."},
    "bay": {"def": "海灣", "ipa": "/beɪ/", "trans": "bays", "col": "at the bay, keep at bay", "ex": "The boat sailed into the bay."},
    "be": {"def": "是", "ipa": "/biː/", "trans": "was/were, been", "col": "be born, be careful", "ex": "I want to be a teacher."},
    "beach": {"def": "海灘", "ipa": "/biːtʃ/", "trans": "beaches", "col": "go to the beach", "ex": "We spent all day at the beach."},
    "beam": {"def": "光線、橫樑", "ipa": "/biːm/", "trans": "beams", "col": "laser beam, beam of light", "ex": "A beam of sunlight entered the room."},
    "bean": {"def": "豆子", "ipa": "/biːn/", "trans": "beans", "col": "coffee bean, green bean", "ex": "Soybeans are a good source of protein."},
    "bear": {"def": "熊、忍受、負擔", "ipa": "/beə/", "trans": "bore, borne/born", "col": "polar bear, bear in mind", "ex": "I can't bear the loud noise."},
    "beard": {"def": "鬍鬚", "ipa": "/bɪəd/", "trans": "beards", "col": "grow a beard", "ex": "He has a thick black beard."},
    "beast": {"def": "野獸", "ipa": "/biːst/", "trans": "beasts", "col": "wild beast, Beauty and the Beast", "ex": "The lion is the king of beasts."},
    "beat": {"def": "打、擊敗、心跳", "ipa": "/biːt/", "trans": "beat, beaten", "col": "heart beat, beat the drum", "ex": "My team beat them 2-0."},
    "beautiful": {"def": "美麗的", "ipa": "/ˈbjuːtɪfl/", "trans": "beautifully, beauty (名詞)", "col": "beautiful sunset", "ex": "She is a beautiful girl."},
    "beauty": {"def": "美、美人", "ipa": "/ˈbjuːti/", "trans": "beauties", "col": "beauty salon, natural beauty", "ex": "She has great inner beauty."},
    "because": {"def": "因為", "ipa": "/bɪˈkɒz/", "trans": "無", "col": "because of", "ex": "I stayed home because it was raining."},
    "become": {"def": "成為、變成", "ipa": "/bɪˈkʌm/", "trans": "became, become", "col": "become a doctor", "ex": "He became very famous."},
    "bed": {"def": "床", "ipa": "/bed/", "trans": "beds", "col": "go to bed, make the bed", "ex": "It's time for bed."},
    "bedroom": {"def": "臥室", "ipa": "/ˈbedruːm/", "trans": "bedrooms", "col": "master bedroom", "ex": "My bedroom is on the second floor."},
    "bee": {"def": "蜜蜂", "ipa": "/biː/", "trans": "bees", "col": "busy as a bee", "ex": "Bees are collecting honey."},
    "beef": {"def": "牛肉", "ipa": "/biːf/", "trans": "無", "col": "roast beef, ground beef", "ex": "I like my beef medium rare."},
    "beer": {"def": "啤酒", "ipa": "/bɪə/", "trans": "beers", "col": "a bottle of beer", "ex": "He ordered a cold beer."},
    "before": {"def": "在...之前", "ipa": "/bɪˈfɔː/", "trans": "無", "col": "before long, the day before", "ex": "Clean your hands before eating."},
    "beg": {"def": "乞求、乞討", "ipa": "/beɡ/", "trans": "begged, begging", "col": "beg for money, beg your pardon", "ex": "He begged for a second chance."},
    "begin": {"def": "開始", "ipa": "/bɪˈɡɪn/", "trans": "began, begun, beginning (名詞)", "col": "begin with", "ex": "The movie begins at 7 o'clock."},
    "beginner": {"def": "初學者", "ipa": "/bɪˈɡɪnə/", "trans": "beginners", "col": "beginner's class", "ex": "This course is ideal for beginners."},
    "beginning": {"def": "開始、開端", "ipa": "/bɪˈɡɪnɪŋ/", "trans": "begin (動詞)", "col": "at the beginning of", "ex": "This is only the beginning."},
    "behalf": {"def": "利益、代表", "ipa": "/bɪˈhɑːf/", "trans": "無", "col": "on behalf of", "ex": "I'm speaking on behalf of my class."},
    "behave": {"def": "舉止、表現", "ipa": "/bɪˈheɪv/", "trans": "behavior (名詞), well-behaved", "col": "behave yourself", "ex": "He behaved like a gentleman."},
    "behavior": {"def": "行為、舉止", "ipa": "/bɪˈheɪvjə/", "trans": "behave (動詞)", "col": "good behavior", "ex": "His behavior was very strange."},
    "behind": {"def": "在...後面", "ipa": "/bɪˈhaɪnd/", "trans": "無", "col": "behind time, leave behind", "ex": "Who is the man behind you?"},
    "being": {"def": "存在、生命", "ipa": "/ˈbiːɪŋ/", "trans": "beings", "col": "human being", "ex": "Everything has a reason for being."},
    "belief": {"def": "信念、相信", "ipa": "/bɪˈliːf/", "trans": "believe (動詞)", "col": "religious belief, common belief", "ex": "He has a strong belief in god."},
    "believe": {"def": "相信", "ipa": "/bɪˈliːv/", "trans": "believable (可信的)", "col": "believe in", "ex": "I believe that you can do it."},
    "bell": {"def": "鐘、鈴", "ipa": "/bel/", "trans": "bells", "col": "jingle bells, ring the bell", "ex": "The school bell rang."},
    "belly": {"def": "肚子", "ipa": "/ˈbeli/", "trans": "bellies", "col": "belly dance, pot belly", "ex": "The cat likes to have its belly rubbed."},
    "belong": {"def": "屬於", "ipa": "/bɪˈlɒŋ/", "trans": "belongings (所有物)", "col": "belong to", "ex": "This pen belongs to me."},
    "below": {"def": "在...下面", "ipa": "/bɪˈləʊ/", "trans": "無", "col": "see below, below average", "ex": "The temperature is below zero."},
    "belt": {"def": "皮帶", "ipa": "/belt/", "trans": "belts", "col": "seat belt, leather belt", "ex": "Fasten your seat belt."},
    "bench": {"def": "長凳", "ipa": "/bentʃ/", "trans": "benches", "col": "park bench", "ex": "We sat on a bench to rest."},
    "bend": {"def": "彎曲", "ipa": "/bend/", "trans": "bent, bent", "col": "bend down", "ex": "The road bends to the left."},
    "beneath": {"def": "在...之下", "ipa": "/bɪˈniːθ/", "trans": "無", "col": "beneath the surface", "ex": "They found treasure beneath the ground."},
    "beneficial": {"def": "有益的", "ipa": "/ˌbenɪˈfɪʃl/", "trans": "benefit (名詞/動詞)", "col": "mutually beneficial", "ex": "Exercise is beneficial to health."},
    "benefit": {"def": "利益、好處", "ipa": "/ˈbenɪfɪt/", "trans": "benefited, beneficial", "col": "fringe benefit", "ex": "I've had the benefit of a good education."},
    "berry": {"def": "莓果", "ipa": "/ˈberi/", "trans": "berries", "col": "wild berry, strawberry", "ex": "Blueberries are very sweet."},
    "beside": {"def": "在...旁邊", "ipa": "/bɪˈsaɪd/", "trans": "無", "col": "sit beside me", "ex": "Put the table beside the bed."},
    "besides": {"def": "此外", "ipa": "/bɪˈsaɪdz/", "trans": "無", "col": "besides that", "ex": "I'm busy; besides, I have no money."},
    "best": {"def": "最好的", "ipa": "/best/", "trans": "good (形容詞)", "col": "best friend, at best", "ex": "He is my best friend."},
    "bet": {"def": "打賭", "ipa": "/bet/", "trans": "bet, bet", "col": "I bet that...", "ex": "I bet he will be late."},
    "better": {"def": "更好的", "ipa": "/ˈbetə/", "trans": "best (最高級)", "col": "get better, had better", "ex": "You'd better see a doctor."},
    "between": {"def": "在...之間", "ipa": "/bɪˈtwiːn/", "trans": "無", "col": "between you and me", "ex": "The city is between the hills."},
    "beyond": {"def": "越過、超出", "ipa": "/bɪˈjɒnd/", "trans": "無", "col": "beyond hope, beyond repair", "ex": "The house is beyond that hill."},
}

with open("batch_l1_p4.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART4, f, ensure_ascii=False, indent=2)
