import json

# Level 1 Part 35: (Nurse - Onward)
L1_PART35 = {
    "nurse": {"def": "護士、保姆、看護、哺乳、養育、心懷", "ipa": "/nɜːs/", "trans": "nurses, nursing, nursery", "col": "trained nurse, nurse a baby", "ex": "She is a nurse in a hospital."},
    "nursery": {"def": "托兒所、苗圃、育兒室", "ipa": "/ˈnɜːsəri/", "trans": "nurseries", "col": "nursery school, day nursery", "ex": "I picked up the kids from the nursery."},
    "nursing": {"def": "護理、看護、養育", "ipa": "/ˈnɜːsɪŋ/", "trans": "nurse (名詞/動詞)", "col": "nursing home, breast nursing", "ex": "She entered the nursing profession."},
    "nurture": {"def": "養育、培育、營養", "ipa": "/ˈnɜːtʃə/", "trans": "nurtured", "col": "nature and nurture", "ex": "She nurtured the young plants."},
    "nut": {"def": "堅果、螺帽、瘋子", "ipa": "/nʌt/", "trans": "nuts, nutty", "col": "peanut, nut cracker", "ex": "I like to eat nuts."},
    "nutrient": {"def": "營養物、滋養的", "ipa": "/ˈnjuːtriənt/", "trans": "nutrients", "col": "essential nutrient", "ex": "Vegetables are rich in nutrients."},
    "nutrition": {"def": "營養、營養學", "ipa": "/njuˈtrɪʃn/", "trans": "nutritious", "col": "poor nutrition", "ex": "Good nutrition is essential for growth."},
    "nutritious": {"def": "有營養的", "ipa": "/njuˈtrɪʃəs/", "trans": "nutrition (名詞)", "col": "nutritious meal", "ex": "I try to eat a nutritious diet."},
    "oak": {"def": "橡樹、橡木", "ipa": "/əʊk/", "trans": "oaks", "col": "oak tree, oak leaf", "ex": "The desk is made of oak."},
    "oar": {"def": "槳、櫓", "ipa": "/ɔː/", "trans": "oars", "col": "pair of oars", "ex": "They used oars to row the boat."},
    "oasis": {"def": "綠洲、宜人之處", "ipa": "/əʊˈeɪsɪs/", "trans": "oases (複數)", "col": "desert oasis", "ex": "We found an oasis in the desert."},
    "oat": {"def": "燕麥", "ipa": "/əʊt/", "trans": "oats", "col": "rolled oats", "ex": "I have oats for breakfast."},
    "oath": {"def": "誓言、發誓", "ipa": "/əʊθ/", "trans": "oaths", "col": "take an oath, on oath", "ex": "He was under oath to tell the truth."},
    "obedience": {"def": "服從、順從", "ipa": "/əˈbiːdiəns/", "trans": "obedient (服從的)", "col": "blind obedience", "ex": "Children should show obedience to their parents."},
    "obedient": {"def": "服從的、順從的", "ipa": "/əˈbiːdiənt/", "trans": "obediently", "col": "obedient child", "ex": "She is an obedient girl."},
    "obey": {"def": "遵守、服從", "ipa": "/əˈbeɪ/", "trans": "obeyed", "col": "obey orders", "ex": "You must obey the law."},
    "object": {"def": "物體、對象、反對(以əbˈdʒekt發音)", "ipa": "/ˈɒbdʒɪkt/", "trans": "objects, objection", "col": "object to doing, target object", "ex": "I object to the new plan."},
    "objection": {"def": "反對、異議、缺點", "ipa": "/əbˈdʒekʃn/", "trans": "objections, object (動詞)", "col": "raise an objection, have no objection to", "ex": "I have no objection to your going."},
    "objective": {"def": "目標、目的、客觀的", "ipa": "/əbˈdʒektɪv/", "trans": "objectives, objectively", "col": "main objective, objective view", "ex": "Our main objective is to win the game."},
    "obligate": {"def": "使負義務、強迫、有義務的", "ipa": "/ˈɒblɪɡeɪt/", "trans": "obligated, obligation", "col": "feel obligated to", "ex": "I feel obligated to help him."},
    "obligation": {"def": "義務、責任、恩惠", "ipa": "/ˌɒblɪˈɡeɪʃn/", "trans": "obligations, obligatory", "col": "moral obligation, under obligation", "ex": "I have an obligation to help my family."},
    "obligatory": {"def": "義務的、必修的、強制的", "ipa": "/əˈblɪɡətəri/", "trans": "obligation (名詞)", "col": "obligatory attendance", "ex": "Attendance at school is obligatory."},
    "oblige": {"def": "強迫、使感激、施恩", "ipa": "/əˈblaɪdʒ/", "trans": "obliged", "col": "be obliged to", "ex": "I was obliged to leave."},
    "oblique": {"def": "傾斜的、間接的、不坦率的", "ipa": "/əˈbliːk/", "trans": "obliquely", "col": "oblique reference", "ex": "He made an oblique reference to the incident."},
    "obscure": {"def": "微暗的、模糊的、隱匿、使變暗", "ipa": "/əbˈskjʊə/", "trans": "obscured, obscurity", "col": "obscure reason", "ex": "The reason remains obscure."},
    "observance": {"def": "遵守、慶祝、儀式", "ipa": "/əbˈzɜːvəns/", "trans": "observances", "col": "religious observance", "ex": "The observance of traditional customs is important."},
    "observation": {"def": "觀察、注視、言論", "ipa": "/ˌɒbzəˈveɪʃn/", "trans": "observations", "col": "under observation", "ex": "They are under police observation."},
    "observatory": {"def": "天文台、氣象台", "ipa": "/əbˈzɜːvətri/", "trans": "observatories", "col": "Royal Observatory", "ex": "We visited the greenwich observatory."},
    "observe": {"def": "觀察、遵守、慶祝、注意到", "ipa": "/əbˈzɜːv/", "trans": "observed, observer, observation", "col": "observe the law", "ex": "Did you observe anything unusual?"},
    "observer": {"def": "觀察家、目擊者、旁聽者", "ipa": "/əbˈzɜːvə/", "trans": "observers", "col": "political observer", "ex": "The observer wrote a detailed report."},
    "obsess": {"def": "使著迷、纏住", "ipa": "/əbˈses/", "trans": "obsessed, obsession", "col": "be obsessed with", "ex": "She is obsessed with cleanliness."},
    "obsession": {"def": "執著、痴迷、擺脫不了的想法", "ipa": "/əbˈseʃn/", "trans": "obsessions, obsessive", "col": "dangerous obsession", "ex": "Money became an obsession with him."},
    "obsessive": {"def": "強迫性的、著迷的、過分的", "ipa": "/əbˈsesɪv/", "trans": "obsessively", "col": "obsessive behavior", "ex": "He has an obsessive interest in history."},
    "obstacle": {"def": "障礙、阻礙物", "ipa": "/ˈɒbstəkl/", "trans": "obstacles", "col": "major obstacle, obstacle course", "ex": "Lack of money is the main obstacle to her success."},
    "obstruct": {"def": "阻隔、阻塞、妨礙", "ipa": "/əbˈstrʌkt/", "trans": "obstructed, obstruction", "col": "obstruct justice", "ex": "Don't obstruct the path."},
    "obstruction": {"def": "阻礙、妨礙、閉塞", "ipa": "/əbˈstrʌkʃn/", "trans": "obstructions", "col": "intentional obstruction", "ex": "The police are removing the obstruction."},
    "obtain": {"def": "得到、獲得、流通", "ipa": "/əbˈteɪn/", "trans": "obtained", "col": "obtain permission", "ex": "I obtained permission to leave."},
    "obvious": {"def": "顯然的、明顯的", "ipa": "/ˈɒbviəs/", "trans": "obviously", "col": "obvious reason", "ex": "It's obvious that he is lying."},
    "obviously": {"def": "/ˈɒbviəsli/", "trans": "obvious (形容詞)", "col": "obviously clear", "ex": "Obviously, he doesn't want to come."},
    "occasion": {"def": "場合、盛典、誘因", "ipa": "/əˈkeɪʒn/", "trans": "occasions, occasional", "col": "special occasion, on occasion", "ex": "We met on several occasions."},
    "occasional": {"def": "偶爾的、特殊場合的", "ipa": "/əˈkeɪʒənl/", "trans": "occasionally", "col": "occasional visitor", "ex": "He pays occasional visits to his aunt."},
    "occasionally": {"def": "/əˈ常规 /", "trans": "occasional (形容詞)", "col": "every now and then", "ex": "We meet for dinner occasionally."},
    "occupation": {"def": "職業、占領、消遣", "ipa": "/ˌɒkjuˈpeɪʃn/", "trans": "occupations, occupy (動詞)", "col": "main occupation, under occupation", "ex": "What is your father's occupation?"},
    "occupant": {"def": "居住者、佔有人", "ipa": "/ˈɒkjupənt/", "trans": "occupants", "col": "former occupant", "ex": "The car had two occupants."},
    "occupy": {"def": "佔領、居住、佔用(時間)", "ipa": "/ˈɒkjupaɪ/", "trans": "occupied", "col": "occupy a position", "ex": "The enemy occupied the city."},
    "occur": {"def": "發生、想到、出現", "ipa": "/əˈkɜː/", "trans": "occurred, occurrence", "col": "occur to someone", "ex": "It didn't occur to me that he was lying."},
    "occurrence": {"def": "發生、事情、發現", "ipa": "/əˈkʌrəns/", "trans": "occurrences, occur (動詞)", "col": "daily occurrence", "ex": "Traffic jams are a common occurrence here."},
    "ocean": {"def": "海洋", "ipa": "/ˈəʊʃn/", "trans": "oceans, oceanic", "col": "pacific ocean, ocean liner", "ex": "The ocean is full of mysteries."},
    "October": {"def": "十月", "ipa": "/ɒkˈtəʊbə/", "trans": "無", "col": "early October", "ex": "He was born in October."},
    "octopus": {"def": "章魚", "ipa": "/ˈɒktəpəs/", "trans": "octopuses", "col": "huge octopus", "ex": "The octopus hide in the rocks."},
    "odd": {"def": "奇特的、奇數的、剩餘的、臨席的", "ipa": "/ɒd/", "trans": "odds", "col": "odd number, odd job", "ex": "That's an odd thing to say."},
    "odds": {"def": "勝算、機會、不和、差異", "ipa": "/ɒdz/", "trans": "無 (恆複)", "col": "against all odds, at odds with", "ex": "The odds were against them."},
    "odor/odour": {"def": "氣味、名聲", "ipa": "/ˈəʊdə/", "trans": "odors", "col": "body odor", "ex": "I can smell the odor of garlic."},
    "of": {"def": "之、屬於、對於", "ipa": "/ɒv/", "trans": "無", "col": "out of, full of", "ex": "A cup of tea, please."},
    "off": {"def": "離開、關掉、中斷的、離開", "ipa": "/ɒf/", "trans": "無", "col": "turn off, take off", "ex": "Turn off the light."},
    "offence": {"def": "罪過、進攻、冒犯", "ipa": "/əˈfens/", "trans": "offences, offend (動詞)", "col": "criminal offence, take offence", "ex": "Stealing is a criminal offence."},
    "offend": {"def": "冒犯、違反、使不適", "ipa": "/əˈfend/", "trans": "offended, offender", "col": "offend someone", "ex": "I'm sorry if I offended you."},
    "offender": {"def": "罪犯、冒犯者", "ipa": "/əˈfendə/", "trans": "offenders", "col": "first offender, sex offender", "ex": "He is a young offender."},
    "offensive": {"def": "冒犯的、攻擊性的、進攻", "ipa": "/əˈfensɪv/", "trans": "offensively", "col": "offensive remark, go on the offensive", "ex": "I found his remarks very offensive."},
    "offer": {"def": "提供、出價、報價", "ipa": "/ˈɒfə/", "trans": "offered, offering", "col": "job offer, make an offer", "ex": "He offered me a job."},
    "office": {"def": "辦公室、公職、職權", "ipa": "/ˈɒfɪs/", "trans": "offices, officer", "col": "head office, in office", "ex": "I work in a small office."},
    "officer": {"def": "官員、警官、軍官", "ipa": "/ˈɒfɪsə/", "trans": "officers", "col": "police officer, army officer", "ex": "The officer asked for my ID."},
    "official": {"def": "官方的、正式的、公務員", "ipa": "/əˈfɪʃl/", "trans": "officially", "col": "official website, government official", "ex": "This is an official announcement."},
    "officially": {"def": "/əˈfɪʃəli/", "trans": "official (形容詞)", "col": "officially announced", "ex": "It has been officially announced."},
    "offset": {"def": "抵銷、補償、偏移量", "ipa": "/ˈɒfset/", "trans": "offsets", "col": "offset the loss", "ex": "The profit will offset the loss."},
    "offspring": {"def": "後代、子孫、產物", "ipa": "/ˈɒfsprɪŋ/", "trans": "無 (單複同形)", "col": "my offspring", "ex": "He has four offspring."},
    "often": {"def": "經常、往往", "ipa": "/ˈɒfn/", "trans": "無", "col": "how often", "ex": "I often go to the movies."},
    "oh": {"def": "噢、唷", "ipa": "/əʊ/", "trans": "無", "col": "oh no, oh my god", "ex": "Oh, I see."},
    "oil": {"def": "油、石油", "ipa": "/ɔɪl/", "trans": "oily", "col": "olive oil, crude oil", "ex": "Oil doesn't mix with water."},
    "oily": {"def": "油膩的、滑頭的", "ipa": "/ˈɔɪli/", "trans": "oil (名詞)", "col": "oily skin", "ex": "The fish is very oily."},
    "ointment": {"def": "軟膏、油膏", "ipa": "/ˈɔɪntmənt/", "trans": "ointments", "col": "apply ointment", "ex": "She is putting some ointment on the burn."},
    "O.K./OK": {"def": "好的、可以、批准", "ipa": "/əʊˈkeɪ/", "trans": "無", "col": "it's OK", "ex": "Is everything OK?"},
    "old": {"def": "老的、舊的", "ipa": "/əʊld/", "trans": "older, oldest, elder", "col": "old friend, old age", "ex": "He is very old."},
    "olive": {"def": "橄欖(樹)、橄欖綠", "ipa": "/ˈɒlɪv/", "trans": "olives", "col": "olive oil, olive branch", "ex": "I like to eat olives."},
    "Olympic": {"def": "奧林匹克的", "ipa": "/əˈlɪmpɪk/", "trans": "Olympics (奧運)", "col": "Olympic Games", "ex": "The next Olympic Games will be in Paris."},
    "omelet/omelette": {"def": "煎蛋捲", "ipa": "/ˈɒmlət/", "trans": "omelets", "col": "cheese omelet", "ex": "I'd like a cheese omelet."},
    "omen": {"def": "預兆、前兆", "ipa": "/ˈəʊmən/", "trans": "omens", "col": "bad omen", "ex": "It's considered a bad omen."},
    "ominous": {"def": "不吉利的、不祥的", "ipa": "/ˈɒmɪnəs/", "trans": "ominously", "col": "ominous silence", "ex": "There was an ominous silence in the house."},
    "omission": {"def": "省略、遗漏、疏忽", "ipa": "/əˈmɪʃn/", "trans": "omissions, omit (動詞)", "col": "error and omission", "ex": "The omission of certain details was unfortunate."},
    "omit": {"def": "省略、遗漏、忘記", "ipa": "/əˈmɪt/", "trans": "omitted", "col": "omit details", "ex": "Don't omit any important details."},
    "on": {"def": "在...之上、關於、進行中、接通", "ipa": "/ɒn/", "trans": "無", "col": "on time, on sale", "ex": "The book is on the table."},
    "once": {"def": "一次、一度、曾經、一旦", "ipa": "/wʌns/", "trans": "無", "col": "once again, at once", "ex": "I've been to Paris once."},
    "one": {"def": "一、一個人/物", "ipa": "/wʌn/", "trans": "oneself", "col": "one by one, no one", "ex": "One and one is two."},
    "oneself": {"def": "自己 (反身代名詞)", "ipa": "/wʌnˈself/", "trans": "無", "col": "by oneself", "ex": "He likes to work by oneself."},
    "onion": {"def": "洋蔥", "ipa": "/ˈʌnjən/", "trans": "onions", "col": "onion ring", "ex": "I don't like onions."},
    "online": {"def": "聯機的、連網的、在線地", "ipa": "/ˌɒnˈlaɪn/", "trans": "offline (離線的)", "col": "online shopping", "ex": "I like to buy books online."},
    "only": {"def": "唯一的、只是、僅僅", "ipa": "/ˈəʊnli/", "trans": "無", "col": "only if, not only", "ex": "He is the only child."},
    "onset": {"def": "開始、發作、突擊", "ipa": "/ˈɒnset/", "trans": "onsets", "col": "onset of winter", "ex": "The onset of the disease is sudden."},
    "onward": {"def": "向前地、向前的", "ipa": "/ˈɒnwəd/", "trans": "onwards", "col": "from now onward", "ex": "We moved onward in the direction of the coast."},
}

with open("batch_l1_p35.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART35, f, ensure_ascii=False, indent=2)
