import json

# Level 1 Part 8: (Ceremony - Commercial)
L1_PART8 = {
    "ceremony": {"def": "典禮、儀式", "ipa": "/ˈserəməni/", "trans": "ceremonies", "col": "opening ceremony", "ex": "The award ceremony was very exciting."},
    "certain": {"def": "確定的、某個", "ipa": "/ˈsɜːtn/", "trans": "certainly, certainty", "col": "be certain of", "ex": "I am certain that he will win."},
    "certainly": {"def": "無疑地、當然", "ipa": "/ˈsɜːtnli/", "trans": "certain (形容詞)", "col": "most certainly", "ex": "I will certainly come to your party."},
    "certainty": {"def": "確定性、肯定的事", "ipa": "/ˈsɜːtnti/", "trans": "certainly", "col": "absolute certainty", "ex": "There is no certainty in the future."},
    "certificate": {"def": "證書、執照", "ipa": "/səˈtɪfɪkət/", "trans": "certificates", "col": "birth certificate, marriage certificate", "ex": "She received a certificate for her achievement."},
    "chain": {"def": "鏈條、連鎖、一連串", "ipa": "/tʃeɪn/", "trans": "chains", "col": "chain store, food chain", "ex": "She is wearing a gold chain."},
    "chair": {"def": "椅子、主席", "ipa": "/tʃeə/", "trans": "chairs", "col": "rocking chair", "ex": "Please sit down on the chair."},
    "chairman/chairwoman/chairperson": {"def": "主席", "ipa": "/ˈtʃeəmən/", "trans": "chairmen", "col": "chairman of the board", "ex": "He was elected chairman of the company."},
    "chalk": {"def": "粉筆", "ipa": "/tʃɔːk/", "trans": "chalks", "col": "white chalk", "ex": "The teacher used some white chalk on the board."},
    "challenge": {"def": "挑戰", "ipa": "/ˈtʃælɪndʒ/", "trans": "challenged, challenging", "col": "face a challenge", "ex": "This job is a real challenge for me."},
    "challenging": {"def": "具挑戰性的", "ipa": "/ˈtʃælɪndʒɪŋ/", "trans": "challenge (名詞/動詞)", "col": "challenging task", "ex": "Mountain climbing is a very challenging sport."},
    "chamber": {"def": "房間、會所、腔", "ipa": "/ˈtʃeɪmbə/", "trans": "chambers", "col": "chamber music, legislative chamber", "ex": "The king sat in his inner chamber."},
    "champion": {"def": "冠軍", "ipa": "/ˈtʃæmpiən/", "trans": "champions, championship", "col": "world champion", "ex": "He is the Olympic swimming champion."},
    "championship": {"def": "冠軍賽、錦標賽", "ipa": "/ˈtʃæmpiənʃɪp/", "trans": "champions", "col": "world championship", "ex": "The team won the championship this year."},
    "chance": {"def": "機會、可能性", "ipa": "/tʃɑːns/", "trans": "chances", "col": "by chance, take a chance", "ex": "Give me one more chance, please."},
    "change": {"def": "改變、更換、零錢", "ipa": "/tʃeɪndʒ/", "trans": "changed, changeable", "col": "make a change, small change", "ex": "I need some change for the bus."},
    "changeable": {"def": "易變的、不定的", "ipa": "/ˈtʃeɪndʒəbl/", "trans": "change (動詞)", "col": "changeable weather", "ex": "The local weather is very changeable."},
    "channel": {"def": "頻道、管道、海峽", "ipa": "/ˈtʃænl/", "trans": "channels", "col": "news channel, English Channel", "ex": "What's on channel 5 tonight?"},
    "chapter": {"def": "章節", "ipa": "/ˈtʃæptə/", "trans": "chapters", "col": "chapter one", "ex": "I've already finished the first chapter."},
    "character": {"def": "性格、特質、角色、字", "ipa": "/ˈkærəktə/", "trans": "characteristic (特徵)", "col": "main character, Chinese characters", "ex": "She has a very strong character."},
    "characteristic": {"def": "特徵、特色", "ipa": "/ˌkærəktəˈrɪstɪk/", "trans": "characteristics", "col": "distinctive characteristic", "ex": "Kindness is her most notable characteristic."},
    "charcoal": {"def": "木炭、炭畫", "ipa": "/ˈtʃɑːkəʊl/", "trans": "無", "col": "charcoal drawing", "ex": "They cooked the meat over charcoal."},
    "charge": {"def": "收費、控告、充電、負責", "ipa": "/tʃɑːdʒ/", "trans": "charged, charging", "col": "in charge of, free of charge", "ex": "How much do you charge for this?"},
    "charity": {"def": "慈善機構、慈悲", "ipa": "/ˈtʃærəti/", "trans": "charities", "col": "raise money for charity", "ex": "They gave all their old clothes to charity."},
    "charm": {"def": "魅力、法寶", "ipa": "/tʃɑːm/", "trans": "charming, charmed", "col": "lucky charm", "ex": "She has a lot of personal charm."},
    "charming": {"def": "迷人的", "ipa": "/ˈtʃɑːmɪŋ/", "trans": "charmingly", "col": "charming village", "ex": "He is a very charming young man."},
    "chart": {"def": "圖表、排行榜", "ipa": "/tʃɑːt/", "trans": "charts", "col": "flow chart, music charts", "ex": "Look at the chart above the text."},
    "chase": {"def": "追逐、追捕", "ipa": "/tʃeɪs/", "trans": "chased, chasing", "col": "chase after someone", "ex": "The police chased the thief down the street."},
    "chat": {"def": "聊天", "ipa": "/tʃæt/", "trans": "chatted, chatting", "col": "have a chat", "ex": "I had a long chat with my friend."},
    "chatter": {"def": "饒舌、喋喋不休", "ipa": "/ˈtʃætə/", "trans": "chattered", "col": "constant chatter", "ex": "She continued to chatter all morning."},
    "cheap": {"def": "便宜的", "ipa": "/tʃiːp/", "trans": "cheaply, cheapness", "col": "dirt cheap", "ex": "This watch is quite cheap but good."},
    "cheaply": {"def": "便宜地", "ipa": "/ˈtʃiːpli/", "trans": "cheap (形容詞)", "col": "produced cheaply", "ex": "The new cars are being made very cheaply."},
    "cheat": {"def": "欺騙、作弊", "ipa": "/tʃiːt/", "trans": "cheated, cheating", "col": "cheat on an exam", "ex": "He was caught cheating on the test."},
    "check": {"def": "檢查、支票", "ipa": "/tʃek/", "trans": "checked, checking", "col": "check in/out, background check", "ex": "Let me check the flight time."},
    "check-in": {"def": "報到、登錄", "ipa": "/ˈtʃek ɪn/", "trans": "無", "col": "at the check-in desk", "ex": "Check-in is at three in the afternoon."},
    "checkout": {"def": "結帳處", "ipa": "/ˈtʃekaʊt/", "trans": "無", "col": "supermarket checkout", "ex": "There is a long queue at the checkout."},
    "cheek": {"def": "臉頰", "ipa": "/tʃiːk/", "trans": "cheeks", "col": "rosy cheeks", "ex": "The baby has rosy red cheeks."},
    "cheer": {"def": "歡呼、激發、加油", "ipa": "/tʃɪə/", "trans": "cheerful, cheery", "col": "cheer up, cheers!", "ex": "The audience cheered for the dancer."},
    "cheerful": {"def": "開朗的、令人愉快的", "ipa": "/ˈtʃɪəfl/", "trans": "cheerfully", "col": "cheerful person", "ex": "He always has a cheerful smile."},
    "cheese": {"def": "起司、乳酪", "ipa": "/tʃiːz/", "trans": "cheesy", "col": "cream cheese", "ex": "I like bread with cheese."},
    "chemical": {"def": "化學的、化學製品", "ipa": "/ˈkemɪkl/", "trans": "chemically", "col": "chemical reaction", "ex": "Don't use harmful chemicals in the garden."},
    "chemist": {"def": "化學家、藥劑師", "ipa": "/ˈkemɪst/", "trans": "chemistry (名詞)", "col": "trained chemist", "ex": "She is a student chemist at university."},
    "chemistry": {"def": "化學、化學作用", "ipa": "/ˈkemɪstri/", "trans": "chemical (形容詞)", "col": "organic chemistry", "ex": "Chemistry was my favorite subject in school."},
    "cherish": {"def": "珍愛、懷念", "ipa": "/ˈtʃerɪʃ/", "trans": "cherished", "col": "cherish the memory", "ex": "I will cherish this gift forever."},
    "cherry": {"def": "櫻桃", "ipa": "/ˈtʃeri/", "trans": "cherries", "col": "cherry blossom", "ex": "I added a cherry on top of the cake."},
    "chess": {"def": "西洋棋", "ipa": "/tʃes/", "trans": "無", "col": "play chess", "ex": "Chess requires a lot of concentration."},
    "chest": {"def": "胸膛、大箱子", "ipa": "/tʃest/", "trans": "chests", "col": "chest pain, treasure chest", "ex": "He felt a sharp pain in his chest."},
    "chew": {"def": "咀嚼", "ipa": "/tʃuː/", "trans": "chewed, chewing", "col": "chew gum", "ex": "You must chew your food well before swallowing."},
    "chick": {"def": "小雞", "ipa": "/tʃɪk/", "trans": "chicks", "col": "baby chick", "ex": "A little chick hatched from the egg."},
    "chicken": {"def": "雞、雞肉、膽小鬼", "ipa": "/ˈtʃɪkɪn/", "trans": "chickens", "col": "roast chicken", "ex": "She doesn't like to eat chicken."},
    "chief": {"def": "首領、主要的", "ipa": "/tʃiːf/", "trans": "chiefly (主要地)", "col": "chief officer, editor-in-chief", "ex": "The chief reason for his failure was laziness."},
    "child": {"def": "兒童", "ipa": "/tʃaɪld/", "trans": "children", "col": "only child", "ex": "Every child has a right to education."},
    "childhood": {"def": "童年", "ipa": "/ˈtʃaɪldhʊd/", "trans": "childhoods", "col": "early childhood", "ex": "He spent his childhood in the countryside."},
    "childish": {"def": "孩子氣的", "ipa": "/ˈtʃaɪldɪʃ/", "trans": "childly", "col": "childish behavior", "ex": "Stop making such childish jokes."},
    "childlike": {"def": "天真的、孩子般的", "ipa": "/ˈtʃaɪldlaɪk/", "trans": "無", "col": "childlike innocence", "ex": "She has a childlike enthusiasm for everything."},
    "chill": {"def": "寒冷、使冷卻", "ipa": "/tʃɪl/", "trans": "chilly", "col": "catch a chill", "ex": "There's a chill in the air today."},
    "chilly": {"def": "寒冷的", "ipa": "/ˈtʃɪli/", "trans": "chill (名詞)", "col": "chilly morning", "ex": "It's a bit chilly outside; wear a jacket."},
    "chimney": {"def": "煙囪", "ipa": "/ˈtʃɪmni/", "trans": "chimneys", "col": "tall chimney", "ex": "Smoke was coming out of the chimney."},
    "chimpanzee": {"def": "黑猩猩", "ipa": "/ˌtʃɪmpænˈziː/", "trans": "chimps", "col": "intelligent chimp", "ex": "Chimpanzees are closely related to humans."},
    "chin": {"def": "下巴", "ipa": "/tʃɪn/", "trans": "chins", "col": "double chin", "ex": "He rested his chin on his hand."},
    "China": {"def": "中國、瓷器", "ipa": "/ˈtʃaɪnə/", "trans": "Chinese (中國的/人)", "col": "Mainland China", "ex": "Beijing is the capital of China."},
    "Chinese": {"def": "中國的、中國人、中文", "ipa": "/ˌtʃaɪˈniːz/", "trans": "無", "col": "speak Chinese", "ex": "He likes Chinese food very much."},
    "chip": {"def": "晶片、薄片、掉下的小片", "ipa": "/tʃɪp/", "trans": "chips", "col": "computer chip, potato chips", "ex": "He put a potato chip into his mouth."},
    "chirp": {"def": "啾啾聲", "ipa": "/tʃɜːp/", "trans": "chirped", "col": "birds chirp", "ex": "Birds were chirping in the trees."},
    "chocolate": {"def": "巧克力", "ipa": "/ˈtʃɒklət/", "trans": "chocolates", "col": "dark chocolate", "ex": "She bought a box of chocolates."},
    "choice": {"def": "選擇", "ipa": "/tʃɔɪs/", "trans": "choose (動詞)", "col": "have no choice", "ex": "It's your choice."},
    "choke": {"def": "窒息、噎住", "ipa": "/tʃəʊk/", "trans": "choked", "col": "choke on food", "ex": "She almost choked on a piece of meat."},
    "choose": {"def": "選擇", "ipa": "/tʃuːz/", "trans": "chose, chosen, choice (名詞)", "col": "choose from", "ex": "You can choose any color you like."},
    "chop": {"def": "剁、砍", "ipa": "/tʃɒp/", "trans": "chopped, chopping", "col": "pork chop, chop wood", "ex": "She chopped the onions finely."},
    "chopstick": {"def": "筷子", "ipa": "/ˈtʃɒpstɪk/", "trans": "chopsticks", "col": "use chopsticks", "ex": "I'm not good at using chopsticks."},
    "chore": {"def": "日常雜務", "ipa": "/tʃɔː/", "trans": "chores", "col": "household chores", "ex": "I have several household chores to do."},
    "chorus": {"def": "合唱、合唱團", "ipa": "/ˈkɔːrəs/", "trans": "choruses", "col": "school chorus", "ex": "The audience joined in the chorus."},
    "Christian": {"def": "基督徒、基督教的", "ipa": "/ˈkrɪstʃən/", "trans": "Christians", "col": "Christian faith", "ex": "She is a devout Christian."},
    "Christmas": {"def": "聖誕節", "ipa": "/ˈkrɪsməs/", "trans": "無", "col": "Christmas Eve, Christmas tree", "ex": "Merry Christmas to you!"},
    "chubby": {"def": "圓胖的", "ipa": "/ˈtʃʌbi/", "trans": "chubbier", "col": "chubby baby", "ex": "He has chubby red cheeks."},
    "church": {"def": "教堂", "ipa": "/tʃɜːtʃ/", "trans": "churches", "col": "go to church", "ex": "There is an old church near our house."},
    "cigar": {"def": "雪茄", "ipa": "/sɪˈɡɑː/", "trans": "cigars", "col": "smoke a cigar", "ex": "He likes smoking an expensive cigar."},
    "cigarette": {"def": "香菸", "ipa": "/ˌsɪɡəˈret/", "trans": "cigarettes", "col": "quit cigarettes", "ex": "Smoking cigarettes is bad for your lungs."},
    "cinema": {"def": "電影院、電影業", "ipa": "/ˈsɪnəmə/", "trans": "cinemas", "col": "at the cinema", "ex": "We went to the cinema last night."},
    "circle": {"def": "圓圈、界線、社交圈", "ipa": "/ˈsɜːkl/", "trans": "circular (圓形的)", "col": "draw a circle, social circle", "ex": "The children sat in a circle."},
    "circular": {"def": "圓形的、循環的", "ipa": "/ˈsɜːkjələ/", "trans": "circulars, circle (名詞)", "col": "circular motion", "ex": "The table was large and circular."},
    "circulate": {"def": "循環、傳播", "ipa": "/ˈsɜːkjəleɪt/", "trans": "circulation (名詞)", "col": "circulate blood", "ex": "Blood circulates around the body."},
    "circulation": {"def": "循環、發行量", "ipa": "/ˌsɜːkjəˈleɪʃn/", "trans": "circulate (動詞)", "col": "daily circulation", "ex": "The coin was in circulation for many years."},
    "circumstance": {"def": "情況、環境", "ipa": "/ˈsɜːkəmstəns/", "trans": "circumstances", "col": "under any circumstances", "ex": "The decision depends on the circumstances."},
    "circus": {"def": "馬戲團", "ipa": "/ˈsɜːkəs/", "trans": "circuses", "col": "traveling circus", "ex": "The circus is in town this week."},
    "citizen": {"def": "公民、市民", "ipa": "/ˈsɪtɪzn/", "trans": "citizenship", "col": "senior citizen", "ex": "He is a law-abiding citizen."},
    "city": {"def": "城市", "ipa": "/ˈsɪti/", "trans": "cities", "col": "big city, city council", "ex": "New York is a very big city."},
    "civil": {"def": "公務的、文明的、民法的", "ipa": "/ˈsɪvl/", "trans": "civilly", "col": "civil rights, civil war", "ex": "Everyone has their civil rights."},
    "civilian": {"def": "平民", "ipa": "/səˈvɪliən/", "trans": "civilians", "col": "innocent civilian", "ex": "Many civilians were killed in the war."},
    "civilization": {"def": "文明", "ipa": "/ˌsɪvəlaɪˈzeɪʃn/", "trans": "civilize (文明化)", "col": "western civilization", "ex": "They studied the ancient Maya civilization."},
    "civilize": {"def": "使開化、教化", "ipa": "/ˈsɪvəlaɪz/", "trans": "civilized, civilization", "col": "civilize someone", "ex": "Education should help to civilize people."},
    "clap": {"def": "鼓掌、輕敲", "ipa": "/klæp/", "trans": "clapped, clapping", "col": "clap one's hands", "ex": "The audience began to clap for the singer."},
    "clarify": {"def": "澄清、闡明", "ipa": "/ˈklærəfaɪ/", "trans": "clarification (名詞)", "col": "clarify a point", "ex": "Could you clarify the last statement?"},
    "clash": {"def": "衝突、碰撞聲", "ipa": "/klæʃ/", "trans": "clashed", "col": "clash of interests", "ex": "The two teams will clash on Sunday."},
    "class": {"def": "班級、階級、等級", "ipa": "/klɑːs/", "trans": "classes", "col": "first class, middle class", "ex": "I have an English class at nine."},
    "classic": {"def": "經典的、熱衷的", "ipa": "/ˈklæsɪk/", "trans": "classics", "col": "classic example", "ex": "This is a classic example of his style."},
    "classical": {"def": "古典的", "ipa": "/ˈklæsɪkl/", "trans": "無", "col": "classical music", "ex": "Do you like classical music?"},
    "classification": {"def": "分類、類別", "ipa": "/ˌklæsɪfɪˈkeɪʃn/", "trans": "classify (動詞)", "col": "system of classification", "ex": "The system of biological classification is complex."},
    "classify": {"def": "將...分類", "ipa": "/ˈklæsɪfaɪ/", "trans": "classified, classification", "col": "classify into", "ex": "These books are classified by subject."},
    "classmate": {"def": "同學", "ipa": "/ˈklɑːsmeɪt/", "trans": "classmates", "col": "new classmate", "ex": "He is my classmate from high school."},
    "classroom": {"def": "教室", "ipa": "/ˈklɑːsruːm/", "trans": "classrooms", "col": "empty classroom", "ex": "They are sitting in the classroom."},
    "clatter": {"def": "喀噠聲、喧鬧", "ipa": "/ˈklætə/", "trans": "clattered", "col": "clatter of dishes", "ex": "The plates fell to the floor with a clatter."},
    "clause": {"def": "子句、條款", "ipa": "/klɔːz/", "trans": "clauses", "col": "relative clause, main clause", "ex": "The contract has a very strict clause."},
    "clay": {"def": "黏土", "ipa": "/kleɪ/", "trans": "clayey", "col": "clay pot", "ex": "The potter made a bowl out of clay."},
    "clean": {"def": "乾淨的、清洗", "ipa": "/kliːn/", "trans": "cleanly, cleanness", "col": "clean up, clean clothes", "ex": "Keep your hands clean."},
    "cleaner": {"def": "清潔工、清潔劑", "ipa": "/ˈkliːnə/", "trans": "cleaners", "col": "vacuum cleaner, dry cleaner", "ex": "The window cleaner is here."},
    "cleanly": {"def": "乾淨地、愛潔地", "ipa": "/ˈklenli/", "trans": "cleanliness (名詞)", "col": "live cleanly", "ex": "He was cleanly dressed for the interview."},
    "cleans/cleanse": {"def": "清洗、淨化", "ipa": "/klenz/", "trans": "cleansed", "col": "cleansing cream", "ex": "Wash your face to cleanse it of dirt."},
    "clear": {"def": "清楚的、透明的、清空", "ipa": "/klɪə/", "trans": "clearly, clearness", "col": "clear sky, make clear", "ex": "The sky is clear and blue today."},
    "clearly": {"def": "清楚地", "ipa": "/ˈklɪəli/", "trans": "clear (形容詞)", "col": "speak clearly", "ex": "He explained the situation very clearly."},
    "clerk": {"def": "店員、辦事員", "ipa": "/klɑːk/", "trans": "clerks", "col": "bank clerk, office clerk", "ex": "The hotel clerk gave us our keys."},
    "clever": {"def": "聰明的", "ipa": "/ˈklevə/", "trans": "cleverly, cleverness", "col": "clever idea", "ex": "He is always a very clever boy."},
    "click": {"def": "點擊、喀噠聲", "ipa": "/klɪk/", "trans": "clicked, clicking", "col": "double click", "ex": "Click the link to open the page."},
    "client": {"def": "客戶、委託人", "ipa": "/ˈklaɪənt/", "trans": "clients", "col": "important client", "ex": "He is meeting a client for lunch."},
    "cliff": {"def": "懸崖", "ipa": "/klɪf/", "trans": "cliffs", "col": "high cliff", "ex": "The hotel stands on top of a cliff."},
    "climate": {"def": "氣候", "ipa": "/ˈklaɪmət/", "trans": "climatic", "col": "tropical climate, climate change", "ex": "Taiwan has a humid subtropical climate."},
    "climb": {"def": "攀登、爬", "ipa": "/klaɪm/", "trans": "climber, climbing", "col": "climb a mountain", "ex": "They are climbing the stairs."},
    "climber": {"def": "登山者", "ipa": "/ˈklaɪmə/", "trans": "climbers", "col": "professional climber", "ex": "The climber reached the peak yesterday."},
    "clinging/cling": {"def": "緊貼、依附", "ipa": "/klɪŋ/", "trans": "clung, clung", "col": "cling to", "ex": "Dew drops clung to the leaves."},
    "clinic": {"def": "診所", "ipa": "/ˈklɪnɪk/", "trans": "clinics", "col": "dental clinic", "ex": "I am going to the dental clinic today."},
    "clip": {"def": "剪輯、夾住、夾子", "ipa": "/klɪp/", "trans": "clips", "col": "paper clip, video clip", "ex": "She used a clip to hold her hair."},
    "clock": {"def": "/klɒk/", "trans": "clocks", "col": "alarm clock, round the clock", "ex": "The clock on the wall says it's 10 p.m."},
    "close": {"def": "親近的、關閉", "ipa": "/kləʊz/", "trans": "closed, closely", "col": "close to, close down", "ex": "Please close the door."},
    "closely": {"def": "緊密地、仔細地", "ipa": "/ˈkləʊsli/", "trans": "close (形容詞)", "col": "watch closely", "ex": "Follow the instructions closely."},
    "closet": {"def": "壁櫥、碗櫃", "ipa": "/ˈklɒzɪt/", "trans": "closets", "col": "walk-in closet", "ex": "My clothes are in the closet."},
    "cloth": {"def": "布料", "ipa": "/klɒθ/", "trans": "clothes (衣服)", "col": "piece of cloth", "ex": "I cleaned the table with a wet cloth."},
    "clothe": {"def": "給...穿衣、覆蓋", "ipa": "/kləʊð/", "trans": "clothed, clothing", "col": "clothe oneself in", "ex": "They have few resources to clothe themselves."},
    "clothes": {"def": "衣服", "ipa": "/kləʊðz/", "trans": "cloth (名詞)", "col": "casual clothes, designer clothes", "ex": "She is wearing her new clothes."},
    "clothing": {"def": "服裝 (總稱)", "ipa": "/ˈkləʊðɪŋ/", "trans": "cloth", "col": "protective clothing", "ex": "Bring warm clothing for the trip."},
    "cloud": {"def": "雲", "ipa": "/klaʊd/", "trans": "cloudy (陰天的)", "col": "white cloud, dark cloud", "ex": "There are white clouds in the sky."},
    "cloudy": {"def": "陰天的、多雲的", "ipa": "/ˈklaʊdi/", "trans": "cloud (名詞)", "col": "cloudy day", "ex": "It's a cloudy day today."},
    "clown": {"def": "小丑", "ipa": "/klaʊn/", "trans": "clowns", "col": "funny clown", "ex": "The clown performed tricks for children."},
    "club": {"def": "俱樂部、棍棒、社團", "ipa": "/klʌb/", "trans": "clubs", "col": "night club, tennis club", "ex": "He is a member of the golf club."},
    "clue": {"def": "線索", "ipa": "/kluː/", "trans": "clues", "col": "give a clue", "ex": "The police are looking for clues."},
    "clumsy": {"def": "笨拙的", "ipa": "/ˈklʌmzi/", "trans": "clumsily", "col": "clumsy mistake", "ex": "He is very clumsy with his hands."},
    "cluster": {"def": "串、簇、群", "ipa": "/ˈklʌstə/", "trans": "clusters", "col": "star cluster", "ex": "A cluster of grapes hung from the vine."},
    "coach": {"def": "教練、長途巴士", "ipa": "/kəʊtʃ/", "trans": "coached, coaching", "col": "football coach, travel by coach", "ex": "The coach gave us some good advice."},
    "coal": {"def": "煤炭", "ipa": "/kəʊl/", "trans": "無", "col": "coal mine", "ex": "Coal is burnt to produce energy."},
    "coarse": {"def": "粗糙的、粗俗的", "ipa": "/kɔːs/", "trans": "coarseness", "col": "coarse sand", "ex": "The shirt was made of coarse cloth."},
    "coast": {"def": "海岸", "ipa": "/kəʊst/", "trans": "coastal (沿海的)", "col": "on the coast", "ex": "The city is on the east coast."},
    "coastal": {"def": "沿海的", "ipa": "/ˈkəʊstl/", "trans": "coast (名詞)", "col": "coastal city", "ex": "They drove along a coastal road."},
    "coat": {"def": "大衣、塗層", "ipa": "/kəʊt/", "trans": "coats", "col": "winter coat, coat of paint", "ex": "Put your coat on; it's cold."},
    "cock": {"def": "公雞、龍頭", "ipa": "/kɒk/", "trans": "cocks", "col": "fighting cock", "ex": "The cock crows at dawn."},
    "cockroach": {"def": "蟑螂", "ipa": "/ˈkɒkrəʊtʃ/", "trans": "cockroaches", "col": "kill a cockroach", "ex": "There's a cockroach in the kitchen."},
    "cocktail": {"def": "雞尾酒", "ipa": "/ˈkɒkteɪl/", "trans": "cocktails", "col": "cocktail party", "ex": "They ordered two fruit cocktails."},
    "cocoa": {"def": "可可、可可粉", "ipa": "/ˈkəʊkəʊ/", "trans": "無", "col": "hot cocoa", "ex": "She drank a cup of hot cocoa."},
    "coconut": {"def": "椰子", "ipa": "/ˈkəʊkənʌt/", "trans": "coconuts", "col": "coconut milk, coconut oil", "ex": "Monkeys can climb up to get coconuts."},
    "code": {"def": "代碼、法典、代號", "ipa": "/kəʊd/", "trans": "coded, coding", "col": "area code, secret code", "ex": "You need a code to enter the door."},
    "coffee": {"def": "咖啡", "ipa": "/ˈkɒfi/", "trans": "無 (不可數)", "col": "black coffee, coffee shop", "ex": "I like to drink coffee in the morning."},
    "coffin": {"def": "棺材", "ipa": "/ˈkɒfɪn/", "trans": "coffins", "col": "wooden coffin", "ex": "Six men carried the coffin."},
    "coin": {"def": "硬幣", "ipa": "/kɔɪn/", "trans": "coins", "col": "flip a coin", "ex": "He put a coin into the vending machine."},
    "cold": {"def": "寒冷的、感冒", "ipa": "/kəʊld/", "trans": "coldly, coldness", "col": "catch a cold, common cold", "ex": "It's freezing cold today."},
    "collapse": {"def": "崩潰、倒塌", "ipa": "/kəˈlæps/", "trans": "collapsed", "col": "building collapse", "ex": "The building collapsed in the earthquake."},
    "collar": {"def": "衣領、項圈", "ipa": "/ˈkɒlə/", "trans": "collars", "col": "blue-collar, white-collar", "ex": "The dog's collar is around its neck."},
    "colleague": {"def": "同事", "ipa": "/ˈkɒliːɡ/", "trans": "colleagues", "col": "business colleague", "ex": "He is one of my close colleagues."},
    "collect": {"def": "收集", "ipa": "/kəˈlekt/", "trans": "collection (名詞), collector (收集者)", "col": "collect stamps", "ex": "She likes to collect old coins."},
    "collection": {"def": "收集品、採收", "ipa": "/kəˈlekʃn/", "trans": "collect (動詞)", "col": "stamp collection", "ex": "He has a large collection of books."},
    "college": {"def": "學院、大學", "ipa": "/ˈkɒlɪdʒ/", "trans": "colleges", "col": "go to college", "ex": "He is a student at the local college."},
    "collision": {"def": "碰撞、衝突", "ipa": "/kəˈlɪʒn/", "trans": "collide (碰撞)", "col": "car collision", "ex": "Two ships were in a collision yesterday."},
    "colonial": {"def": "殖民的", "ipa": "/kəˈləʊniəl/", "trans": "colony (殖民地)", "col": "colonial period", "ex": "Brazil was once a colonial territory."},
    "colony": {"def": "殖民地、群體", "ipa": "/ˈkɒləni/", "trans": "colonies", "col": "british colony, ant colony", "ex": "They established a new colony on the island."},
    "color/colour": {"def": "顏色", "ipa": "/ˈkʌlə/", "trans": "colorful (色彩繽紛的)", "col": "bright color", "ex": "What is your favorite color?"},
    "colorful": {"def": "色彩繽紛的", "ipa": "/ˈkʌləfl/", "trans": "colorfully", "col": "colorful garden", "ex": "The room is very colorful."},
    "column": {"def": "專欄、圓柱、纵列", "ipa": "/ˈkɒləm/", "trans": "columns", "col": "newspaper column, column of smoke", "ex": "The roof is supported by columns."},
    "comb": {"def": "梳子、梳理", "ipa": "/kəʊm/", "trans": "combed, combing", "col": "comb hair", "ex": "He combed his hair before the meeting."},
    "combination": {"def": "結合、密碼", "ipa": "/ˌkɒmbɪˈneɪʃn/", "trans": "combine (動詞)", "col": "color combination", "ex": "Green is a combination of blue and yellow."},
    "combine": {"def": "結合、聯合", "ipa": "/kəmˈbaɪn/", "trans": "combined, combination", "col": "combine forces", "ex": "Let's combine our efforts."},
    "come": {"def": "來、出現", "ipa": "/kʌm/", "trans": "came, come", "col": "come back, come true", "ex": "Please come here."},
    "comedy": {"def": "喜劇", "ipa": "/ˈkɒmədi/", "trans": "comedian (喜劇演員)", "col": "romantic comedy", "ex": "The play is a very funny comedy."},
    "comfort": {"def": "安慰、舒適", "ipa": "/ˈkʌmfət/", "trans": "comfortable", "col": "comfort food, take comfort", "ex": "She found comfort in music."},
    "comfortable": {"def": "舒適的", "ipa": "/ˈkʌmftəbl/", "trans": "comfortably", "col": "feel comfortable", "ex": "This sofa is very comfortable."},
    "comic": {"def": "喜劇的、連環漫畫", "ipa": "/ˈkɒmɪk/", "trans": "comics", "col": "comic strip, comic book", "ex": "He loves reading Japanese comics."},
    "command": {"def": "命令、掌握", "ipa": "/kəˈmɑːnd/", "trans": "commander (指揮官)", "col": "obey a command", "ex": "You must obey the general's command."},
    "commander": {"def": "指揮官", "ipa": "/kəˈmɑːndə/", "trans": "commanders", "col": "supreme commander", "ex": "He is a high-ranking army commander."},
    "comment": {"def": "評論", "ipa": "/ˈkɒment/", "trans": "comments", "col": "no comment, leaves a comment", "ex": "I have no comment on his performance."},
    "commerce": {"def": "商業、貿易", "ipa": "/ˈkɒmɜːs/", "trans": "commercial (商業的)", "col": "chamber of commerce", "ex": "He studied commerce at university."},
    "commercial": {"def": "商業的、電視廣告", "ipa": "/kəˈmɜːʃl/", "trans": "commercially", "col": "commercial bank, commercial break", "ex": "The movie was a commercial success."},
}

with open("batch_l1_p8.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART8, f, ensure_ascii=False, indent=2)
