import json

# Level 1 Part 56: (Refract - Sage)
L1_PART56 = {
    "refract": {"def": "使折射", "ipa": "/rɪˈfrækt/", "trans": "refracted, refraction", "col": "refract light", "ex": "Water refracts light."},
    "refraction": {"def": "折射、折光", "ipa": "/rɪˈfrækʃn/", "trans": "refract (動詞)", "col": "index of refraction", "ex": "The refraction of light makes the stick look bent."},
    "refrain": {"def": "節制、避免、克制、重複句", "ipa": "/rɪˈfreɪn/", "trans": "refrained", "col": "refrain from smoking", "ex": "Please refrain from talking during the movie."},
    "refresh": {"def": "使清新、更新、提神", "ipa": "/rɪˈfreʃ/", "trans": "refreshed, refreshment", "col": "refresh one's memory", "ex": "I took a shower to refresh myself."},
    "refreshment": {"def": "茶點、點心、恢復", "ipa": "/rɪˈfreʃmənt/", "trans": "refresh (動詞)", "col": "light refreshments", "ex": "Light refreshments were served after the meeting."},
    "refrigerate": {"def": "冷凍、使冷卻、冷藏", "ipa": "/rɪˈfrɪdʒəreɪt/", "trans": "refrigerated, refrigerator", "col": "refrigerate after opening", "ex": "You should refrigerate the milk."},
    "refrigerator": {"def": "冰箱、冷藏庫", "ipa": "/rɪˈfrɪdʒəreɪtə/", "trans": "refrigerators", "col": "fridge", "ex": "Put the butter back in the refrigerator."},
    "refuge": {"def": "避難所、庇護、避難", "ipa": "/ˈrefjuːdʒ/", "trans": "refugee", "col": "take refuge", "ex": "They took refuge from the storm in a cave."},
    "refugee": {"def": "難民、流亡者", "ipa": "/ˌrefjuˈdʒiː/", "trans": "refugees", "col": "political refugee", "ex": "Thousands of refugees fled the country."},
    "refund": {"def": "退款、償還、退還", "ipa": "/ˈriːfʌnd/", "trans": "refunded", "col": "full refund", "ex": "I'd like to get a refund on this shirt."},
    "refusal": {"def": "拒絕、優先取捨權", "ipa": "/rɪˈfjuːzl/", "trans": "refuse (動詞)", "col": "blunt refusal", "ex": "His refusal to help was a surprise."},
    "refuse": {"def": "拒絕、謝絕、廢物", "ipa": "/rɪˈfjuːz/", "trans": "refused, refusal", "col": "refuse to answer", "ex": "I refuse to pay that much."},
    "refute": {"def": "反駁、駁斥、推翻", "ipa": "/rɪˈfjuːt/", "trans": "refuted, refutation", "col": "refute a theory", "ex": "He tried to refute the allegations."},
    "regain": {"def": "收回、恢復、復得", "ipa": "/rɪˈɡeɪn/", "trans": "regained", "col": "regain consciousness", "ex": "He finally regained consciousness."},
    "regard": {"def": "認為、考慮、注意、致意", "ipa": "/rɪˈɡɑːd/", "trans": "regarded, regarding, regardless", "col": "as regards, with regard to", "ex": "I regard him as a friend."},
    "regarding": {"def": "關於、至於", "ipa": "/rɪˈɡɑːdɪŋ/", "trans": "regard (動詞)", "col": "information regarding", "ex": "I have some questions regarding the new policy."},
    "regardless": {"def": "不管地、不注意地、不顧慮的", "ipa": "/rɪˈɡɑːdləs/", "trans": "regardless of", "col": "regardless of the cost", "ex": "He will do it regardless of the consequences."},
    "regime": {"def": "政體、政權、制度", "ipa": "/reɪˈʒiːm/", "trans": "regimes", "col": "military regime", "ex": "The old regime was overthrown."},
    "regiment": {"def": "軍團、大量、訓練", "ipa": "/ˈredʒɪmənt/", "trans": "regiments, regimental", "col": "infantry regiment", "ex": "He joined the infantry regiment."},
    "region": {"def": "地區、區域、行政區", "ipa": "/ˈriːdʒən/", "trans": "regional", "col": "remote region, coastal region", "ex": "This region is known for its wine."},
    "regional": {"def": "地區的、地方的", "ipa": "/ˈriːdʒənl/", "trans": "region (名詞)", "col": "regional office", "ex": "There are regional differences in the dialect."},
    "register": {"def": "註冊、登記、紀錄、暫存器", "ipa": "/ˈredʒɪstə/", "trans": "registered, registration, registrar", "col": "cash register, register for a class", "ex": "You need to register at the desk."},
    "registration": {"def": "註冊、登記、掛號", "ipa": "/ˌredʒɪˈstreɪʃn/", "trans": "register (動詞)", "col": "car registration, registration fee", "ex": "Registration closes on Friday."},
    "regret": {"def": "遺憾、後悔、遺憾地", "ipa": "/rɪˈɡret/", "trans": "regretted, regretful, regrettable", "col": "deeply regret", "ex": "I regret not going to university."},
    "regretful": {"def": "後悔的、遺憾的、惋惜的", "ipa": "/rɪˈɡretfl/", "trans": "regretfully", "col": "regretful look", "ex": "He gave a regretful sigh."},
    "regrettable": {"def": "客觀遺憾的、不幸的", "ipa": "/rɪˈɡretəbl/", "trans": "regrettably", "col": "regrettable mistake", "ex": "The loss of life was regrettable."},
    "regular": {"def": "正常的、定期的、均勻的", "ipa": "/ˈreɡjələ/", "trans": "regularly, regularity", "col": "regular exercise, regular customer", "ex": "He is a regular visitor here."},
    "regularity": {"def": "定期、整齊、規律性", "ipa": "/ˌreɡjuˈlærəti/", "trans": "regular (形容詞)", "col": "with regularity", "ex": "The buses run with great regularity."},
    "regularly": {"def": "定期地、有規律地", "ipa": "/ˈreɡjələli/", "trans": "regular (形容詞)", "col": "exercise regularly", "ex": "He goes to the gym regularly."},
    "regulate": {"def": "調節、管制、控制", "ipa": "/ˈreɡjuleɪt/", "trans": "regulated, regulation, regulator", "col": "regulate blood pressure", "ex": "The government regulates the banking industry."},
    "regulation": {"def": "規則、規章、調節", "ipa": "/ˌreɡjuˈleɪʃn/", "trans": "regulations", "col": "safety regulations, government regulation", "ex": "It's against the regulations."},
    "sabotage": {"def": "蓄意破壞、怠工、破壞行動", "ipa": "/ˈsæbətɑːʒ/", "trans": "sabotaged", "col": "industrial sabotage", "ex": "The factory was closed due to sabotage."},
    "sack": {"def": "麻袋、枕頭袋、解僱", "ipa": "/sæk/", "trans": "sacked", "col": "get the sack", "ex": "He was given the sack for being late."},
    "sacred": {"def": "神聖的、莊嚴的", "ipa": "/ˈseɪkrɪd/", "trans": "sacredness", "col": "sacred site, sacred music", "ex": "The cow is a sacred animal in some cultures."},
    "sacrifice": {"def": "犧牲、貢品、祭祀", "ipa": "/ˈsækrɪfaɪs/", "trans": "sacrificed, sacrificial", "col": "make a sacrifice", "ex": "They made many sacrifices for their children."},
    "sad": {"def": "悲哀的、憂愁的、不幸的", "ipa": "/sæd/", "trans": "sadly, sadness, sadden", "col": "sad story, sad news", "ex": "It's a sad state of affairs."},
    "sadden": {"def": "使悲傷、使憂愁", "ipa": "/ˈsædn/", "trans": "saddened", "col": "be saddened by", "ex": "She was saddened by the news of his death."},
    "saddle": {"def": "鞍、車座、馬鞍形物", "ipa": "/ˈsædl/", "trans": "saddles", "col": "in the saddle", "ex": "Put the saddle on the horse."},
    "safe": {"def": "安全的、平安的、可靠的", "ipa": "/seɪf/", "trans": "safely, safety, safeguard", "col": "safe and sound, keep safe", "ex": "Is it safe to go out alone?"},
    "safeguard": {"def": "保衛、預防措施、防護", "ipa": "/ˈseɪfɡɑːd/", "trans": "safeguarded", "col": "legal safeguard", "ex": "We must safeguard the environment."},
    "safely": {"def": "安全地、平安地、確實地", "ipa": "/ˈseɪfli/", "trans": "safe (形容詞)", "col": "arrive safely", "ex": "I hope you get home safely."},
    "safety": {"def": "安全、平安、保險", "ipa": "/ˈseɪfti/", "trans": "safeties", "col": "safety first, safety belt", "ex": "Health and safety are important."},
    "sag": {"def": "下垂、下陥、蕭條", "ipa": "/sæɡ/", "trans": "sagged", "col": "sag in the middle", "ex": "The shelf was sagging under the weight of books."},
    "saga": {"def": "英雄傳、傳說、長篇傳奇", "ipa": "/ˈsɑːɡə/", "trans": "sagas", "col": "family saga", "ex": "His life story is a real saga."},
    "sagacious": {"def": "睿智的、聰明的、有洞察力的", "ipa": "/səˈɡeɪʃəs/", "trans": "sagacity", "col": "sagacious leader", "ex": "She is a sagacious businesswoman."},
    "sagacity": {"def": "睿智、聰明、遠見", "ipa": "/səˈɡæsəti/", "trans": "sagacious", "col": "wisdom and sagacity", "ex": "The old man was known for his sagacity."},
    "sage": {"def": "智者、聖人、鼠尾草、賢明的", "ipa": "/seɪdʒ/", "trans": "sages", "col": "sage advice", "ex": "He gave me some sage advice."},
}

with open("batch_l1_p56.json", "w", encoding="utf-8") as f:
    json.dump(L1_PART56, f, ensure_ascii=False, indent=2)
