import json

# Level 2 Part 8: (Clip - Couple)
L2_PART8 = {
    "clip": {"def": "剪、修剪、夾子、別針、剪下", "ipa": "/klɪp/", "trans": "clipping, clipper", "col": "paper clip, hair clip", "ex": "He used a paper clip to hold the pages together.", "pos": "n./v."},
    "clock": {"def": "鐘、時鐘、記錄...的時間", "ipa": "/klɒk/", "trans": "clockwise", "col": "alarm clock, around the clock", "ex": "The clock on the wall is five minutes fast.", "pos": "n./v."},
    "close": {"def": "靠近的、親密的、關閉、結束、靠近地", "ipa": "/kləʊz/ (v.) /kləʊs/ (adj.)", "trans": "closely, closure", "col": "close to, close friend", "ex": "Please close the door.", "pos": "adj./v./adv."},
    "closet": {"def": "壁櫥、衣櫥、私室、把...關在私室內、私下的", "ipa": "/ˈklɒzɪt/", "trans": "closeted", "col": "walk-in closet, in the closet", "ex": "She hung her coat in the closet.", "pos": "n./v./adj."},
    "cloth": {"def": "布、桌布、衣料", "ipa": "/klɒθ/", "trans": "clothe, clothing", "col": "piece of cloth, table cloth", "ex": "Wipe the table with a damp cloth.", "pos": "n."},
    "clothe": {"def": "穿衣、覆蓋", "ipa": "/kləʊð/", "trans": "clothing, clothes", "col": "clothe oneself", "ex": "The hills were clothed in mist.", "pos": "v."},
    "clothes": {"def": "衣服、服裝", "ipa": "/kləʊðz/", "trans": "clothe (動詞)", "col": "casual clothes, change clothes", "ex": "She is wearing new clothes.", "pos": "n."},
    "clothing": {"def": "（總稱）衣服、服裝", "ipa": "/ˈkləʊðɪŋ/", "trans": "clothe (動詞)", "col": "protective clothing", "ex": "They took warm clothing for the trip.", "pos": "n."},
    "cloud": {"def": "雲、雲狀物、使陰暗、遮蔽", "ipa": "/klaʊd/", "trans": "cloudy", "col": "dark clouds, on cloud nine", "ex": "The sun went behind a cloud.", "pos": "n./v."},
    "cloudy": {"def": "多雲的、陰天的、模糊的", "ipa": "/ˈklaʊdi/", "trans": "cloud (名詞)", "col": "cloudy sky", "ex": "It's a cloudy day today.", "pos": "adj."},
    "club": {"def": "俱樂部、社團、棍棒、用棍棒打、聯合成一體", "ipa": "/klʌb/", "trans": "clubhouse", "col": "night club, chess club", "ex": "He is a member of the local golf club.", "pos": "n./v."},
    "clue": {"def": "線索、提示、為...提供線索", "ipa": "/kluː/", "trans": "cluelss", "col": "clue to, follow a clue", "ex": "The police are looking for clues to the murder.", "pos": "n./v."},
    "clumsy": {"def": "笨拙的、粗陋的", "ipa": "/ˈklʌmzi/", "trans": "clumsily, clumsiness", "col": "clumsy mistake", "ex": "I'm very clumsy; I'm always dropping things.", "pos": "adj."},
    "coach": {"def": "教練、長途巴士、大馬車、訓練、指導", "ipa": "/kəʊtʃ/", "trans": "coaching", "col": "football coach, stagecoach", "ex": "The team has a new coach.", "pos": "n./v."},
    "coal": {"def": "煤、木炭", "ipa": "/kəʊl/", "trans": "coalfield", "col": "coal mine, burn coal", "ex": "The fire was burning with bright red coals.", "pos": "n."},
    "coast": {"def": "海岸、海濱、沿岸航行、滑行", "ipa": "/kəʊst/", "trans": "coastal, coastline", "col": "on the coast, west coast", "ex": "They live on the south coast of England.", "pos": "n./v."},
    "coat": {"def": "大衣、外衣、塗層、覆蓋、塗上", "ipa": "/kəʊt/", "trans": "coating", "col": "winter coat, coat of paint", "ex": "She put on her coat and went out.", "pos": "n./v."},
    "cock": {"def": "公雞、龍頭、首領、豎起、翹起", "ipa": "/kɒk/", "trans": "cockerel", "col": "cock-a-doodle-doo", "ex": "The cock crows at dawn.", "pos": "n./v."},
    "cockroach": {"def": "蟑螂", "ipa": "/ˈkɒkrəʊtʃ/", "trans": "roach", "col": "kill a cockroach", "ex": "I saw a cockroach in the kitchen.", "pos": "n."},
    "cocktail": {"def": "雞尾酒、混合物", "ipa": "/ˈkɒkteɪl/", "trans": "mocktail", "col": "cocktail party", "ex": "They were drinking cocktails by the pool.", "pos": "n."},
    "cocoa": {"def": "可可粉、可可豆", "ipa": "/ˈkəʊkəʊ/", "trans": "chocolate", "col": "hot cocoa", "ex": "I like to drink hot cocoa before bed.", "pos": "n."},
    "coconut": {"def": "椰子", "ipa": "/ˈkəʊkənʌt/", "trans": "copra", "col": "coconut milk, coconut oil", "ex": "The cake was decorated with coconut flakes.", "pos": "n."},
    "coffee": {"def": "咖啡", "ipa": "/ˈkɒfi/", "trans": "caffeine", "col": "black coffee, coffee break", "ex": "I'd like a cup of coffee, please.", "pos": "n."},
    "coin": {"def": "硬幣、古錢、鑄造（貨幣）、創造（新詞）", "ipa": "/kɔɪn/", "trans": "coinage", "col": "toss a coin, gold coin", "ex": "He found a rare coin in the garden.", "pos": "n./v."},
    "cold": {"def": "寒冷的、感冒、寒冷、冷淡地", "ipa": "/kəʊld/", "trans": "coldly, coldness", "col": "catch a cold, common cold", "ex": "It's very cold outside.", "pos": "adj./n./adv."},
    "collapse": {"def": "倒塌、崩潰、虛脫", "ipa": "/kəˈlæps/", "trans": "collapsible", "col": "mental collapse", "ex": "The building collapsed during the earthquake.", "pos": "v./n."},
    "collar": {"def": "衣領、項圈、給...穿上領子、抓住", "ipa": "/ˈkɒlə/", "trans": "collared", "col": "white-collar, blue-collar", "ex": "He loosened his collar.", "pos": "n./v."},
    "collect": {"def": "收集、採集、募集、收款、聚集", "ipa": "/kəˈlekt/", "trans": "collection, collector", "col": "collect stamps, collect data", "ex": "She likes to collect old coins.", "pos": "v."},
    "collection": {"def": "收集物、收藏品", "ipa": "/kəˈlekʃn/", "trans": "collect (動詞)", "col": "stamp collection, private collection", "ex": "He has a large collection of books.", "pos": "n."},
    "college": {"def": "大學、學院", "ipa": "/ˈkɒlɪdʒ/", "trans": "collegiate", "col": "college student, go to college", "ex": "She is a student at the local college.", "pos": "n."},
    "colony": {"def": "殖民地、僑民、集群", "ipa": "/ˈkɒləni/", "trans": "colonial, colonize", "col": "penal colony, ant colony", "ex": "Brazil was once a Portuguese colony.", "pos": "n."},
    "color": {"def": "顏色、色調、給...著色、渲染", "ipa": "/ˈkʌlə/", "trans": "colorful, colorless", "col": "bright color, in color", "ex": "What's your favorite color?", "pos": "n./v."},
    "column": {"def": "圓柱、專欄、列", "ipa": "/ˈkɒləm/", "trans": "columnist", "col": "newspaper column, spinal column", "ex": "The roof is supported by stone columns.", "pos": "n."},
    "comb": {"def": "梳子、梳毛、梳發、搜尋", "ipa": "/kəʊm/", "trans": "combing", "col": "comb one's hair", "ex": "I can't find my comb.", "pos": "n./v."},
    "combination": {"def": "結合、聯合、密碼組合", "ipa": "/ˌkɒmbɪˈneɪʃn/", "trans": "combine (動詞)", "col": "combination lock", "ex": "The colors are a nice combination.", "pos": "n."},
    "combine": {"def": "結合、聯合、兼有、收割機", "ipa": "/kəmˈbaɪn/", "trans": "combination", "col": "combine with", "ex": "We should combine our efforts.", "pos": "v./n."},
    "come": {"def": "來到、發生、到達", "ipa": "/kʌm/", "trans": "came, coming", "col": "come true, come up with", "ex": "Please come here.", "pos": "v."},
    "comedy": {"def": "喜劇、幽默", "ipa": "/ˈkɒmədi/", "trans": "comedian, comedic", "col": "romantic comedy", "ex": "I prefer comedy to drama.", "pos": "n."},
    "comfort": {"def": "舒適、安慰、安慰者、安慰", "ipa": "/ˈkʌmfət/", "trans": "comfortable", "col": "comfort zone, seek comfort", "ex": "The hotel provides every modern comfort.", "pos": "n./v."},
    "comfortable": {"def": "舒適的、安逸的、自在的", "ipa": "/ˈkʌmftəbl/", "trans": "comfort (名詞), comfortably", "col": "comfortable chair, feel comfortable", "ex": "Is your room comfortable?", "pos": "adj."},
    "comic": {"def": "滑稽的、喜劇的、漫畫、喜劇演員", "ipa": "/ˈkɒmɪk/", "trans": "comical, comics", "col": "comic strip, comic book", "ex": "He is a very comic character.", "pos": "adj./n."},
    "command": {"def": "命令、指揮、掌握、命令、俯瞰", "ipa": "/kəˈmɑːnd/", "trans": "commander", "col": "at one's command, chain of command", "ex": "The general gave the command to attack.", "pos": "n./v."},
    "comment": {"def": "評論、意見、發表評論", "ipa": "/ˈkɒment/", "trans": "commentary, commentator", "col": "no comment, comment on", "ex": "I have no comment to make.", "pos": "n./v."},
    "commerce": {"def": "商業、貿易", "ipa": "/ˈkɒmɜːs/", "trans": "commercial", "col": "chamber of commerce", "ex": "The city is a center of commerce.", "pos": "n."},
    "commercial": {"def": "商業的、營利的、廣告", "ipa": "/kəˈmɜːʃl/", "trans": "commerce (名詞), commercially", "col": "commercial break, commercial flight", "ex": "The film was a commercial success.", "pos": "adj./n."},
    "commit": {"def": "犯（罪）、致力於、承諾、撥出", "ipa": "/kəˈmɪt/", "trans": "commitment, committee", "col": "commit a crime, commit suicide", "ex": "He committed a serious error.", "pos": "v."},
    "committee": {"def": "委員會", "ipa": "/kəˈmɪti/", "trans": "committees", "col": "organizing committee, steering committee", "ex": "The committee is meeting today.", "pos": "n."},
    "common": {"def": "普通的、公共的、共同的、平民、共有地", "ipa": "/ˈkɒmən/", "trans": "commonly", "col": "common sense, in common", "ex": "It's a common problem.", "pos": "adj./n./adv."},
    "communicate": {"def": "溝通、傳達、通訊", "ipa": "/kəˈmjuːnɪkeɪt/", "trans": "communication", "col": "communicate with", "ex": "We communicate mainly by email.", "pos": "v."},
    "communication": {"def": "溝通、通訊、訊息", "ipa": "/kəˌmjuːnɪˈkeɪʃn/", "trans": "communicate (動詞)", "col": "mass communication, means of communication", "ex": "Clear communication is essential.", "pos": "n."},
    "community": {"def": "社區、團體、共同體", "ipa": "/kəˈmjuːnəti/", "trans": "communities", "col": "local community, international community", "ex": "She is very active in the local community.", "pos": "n."},
    "companion": {"def": "同伴、伴侶、手冊、陪伴", "ipa": "/kəmˈpæniən/", "trans": "companionship", "col": "traveling companion, close companion", "ex": "He was my constant companion.", "pos": "n./v."},
    "company": {"def": "公司、陪伴、客人、在座的人、陪伴", "ipa": "/ˈkʌmpəni/", "trans": "companies", "col": "keep company, joint-stock company", "ex": "Which company do you work for?", "pos": "n./v."},
    "compare": {"def": "比較、比擬", "ipa": "/kəmˈpeə/", "trans": "comparison, comparative", "col": "compare A with B, beyond compare", "ex": "If you compare the two, you'll see the difference.", "pos": "v./n."},
    "comparison": {"def": "比較、對照、比喻", "ipa": "/kəmˈpærɪsn/", "trans": "compare (動詞)", "col": "in comparison with, make a comparison", "ex": "The comparison is quite useful.", "pos": "n."},
    "compete": {"def": "競爭、對抗、參賽", "ipa": "/kəmˈpiːt/", "trans": "competition, competitor", "col": "compete with, compete for", "ex": "Several companies are competing for the contract.", "pos": "v."},
    "competition": {"def": "競爭、比賽、競爭者", "ipa": "/ˌkɒmpəˈtɪʃn/", "trans": "compete (動詞)", "col": "stiff competition, win a competition", "ex": "There is fierce competition for the job.", "pos": "n."},
    "competitive": {"def": "競爭的、好勝的、有競爭力的", "ipa": "/kəmˈpetətɪv/", "trans": "compete (動詞), competitor", "col": "competitive advantage, highly competitive", "ex": "The market is very competitive.", "pos": "adj."},
    "competitor": {"def": "競爭者、對手", "ipa": "/kəmˈpetɪtə/", "trans": "compete (動詞), competition", "col": "main competitor", "ex": "Their main competitor is a Japanese firm.", "pos": "n."},
    "complain": {"def": "抱怨、投訴、訴說（痛苦）", "ipa": "/kəmˈpleɪn/", "trans": "complaint", "col": "complain about, complain of", "ex": "She complained to the manager about the service.", "pos": "v."},
    "complaint": {"def": "抱怨、控告、疾病、訴怨", "ipa": "/kəmˈpleɪnt/", "trans": "complain (動詞)", "col": "make a complaint, file a complaint", "ex": "I have a complaint to make.", "pos": "n."},
    "complete": {"def": "完整的、完成的、完成、結束、完整地", "ipa": "/kəmˈpliːt/", "trans": "completely, completion", "col": "complete set, mission complete", "ex": "I need to complete this work by Friday.", "pos": "adj./v./adv."},
    "complex": {"def": "複雜的、綜合體的、建築群、情結、使複雜化", "ipa": "/ˈkɒmpleks/", "trans": "complexity", "col": "superiority complex, complex problem", "ex": "The situation is becoming very complex.", "pos": "adj./n./v."},
    "complicate": {"def": "使複雜化", "ipa": "/ˈkɒmplɪkeɪt/", "trans": "complicated, complication", "col": "complicate matters", "ex": "Let's not complicate the issue.", "pos": "v."},
    "complicated": {"def": "複雜的、難懂的", "ipa": "/ˈkɒmplɪkeɪtɪd/", "trans": "complicate (動詞)", "col": "complicated situation", "ex": "The instructions are very complicated.", "pos": "adj."},
    "compliment": {"def": "讚美、稱讚、恭維、稱讚、恭維", "ipa": "/ˈkɒmplɪmənt/", "trans": "complimentary", "col": "pay a compliment", "ex": "Thank you for the compliment.", "pos": "n./v."},
    "compose": {"def": "組成、作曲、寫信、使安定", "ipa": "/kəmˈpəʊz/", "trans": "composition, composer", "col": "compose music", "ex": "Water is composed of hydrogen and oxygen.", "pos": "v."},
    "composer": {"def": "作曲家", "ipa": "/kəmˈpəʊzə/", "trans": "compose (動詞)", "col": "classical composer", "ex": "He is a world-famous composer.", "pos": "n."},
    "composition": {"def": "組成、成分、作品、作文", "ipa": "/ˌkɒmpəˈzɪʃn/", "trans": "compose (動詞)", "col": "chemical composition", "ex": "The composition of the group has changed.", "pos": "n."},
    "compound": {"def": "化合物、混合物、合成的、混合、使惡化", "ipa": "/ˈkɒmpaʊnd/ (n.) /kəmˈpaʊnd/ (v.)", "trans": "compounding", "col": "chemical compound, organic compound", "ex": "Salt is a chemical compound.", "pos": "n./adj./v."},
    "comprehend": {"def": "理解、領會、包含", "ipa": "/ˌkɒmprɪˈhend/", "trans": "comprehension, comprehensible", "col": "fail to comprehend", "ex": "I fail to comprehend how this happened.", "pos": "v."},
    "comprehension": {"def": "理解、包含、理解力", "ipa": "/ˌkɒmprɪˈhenʃn/", "trans": "comprehend (動詞)", "col": "reading comprehension, beyond comprehension", "ex": "His actions were beyond my comprehension.", "pos": "n."},
    "compromise": {"def": "妥協、折衷、妥協、折衷、危及", "ipa": "/ˈkɒmprəmaɪz/", "trans": "compromising", "col": "reach a compromise", "ex": "We had to compromise on the price.", "pos": "n./v."},
    "computer": {"def": "電腦", "ipa": "/kəmˈpjuːtə/", "trans": "computing, computerize", "col": "personal computer, computer software", "ex": "I'm learning how to use a computer.", "pos": "n."},
    "conceal": {"def": "隱藏、遮掩", "ipa": "/kənˈsiːl/", "trans": "concealment", "col": "conceal a secret", "ex": "She could not conceal her disappointment.", "pos": "v."},
    "concentrate": {"def": "集中、濃縮、濃縮物", "ipa": "/ˈkɒnsntreɪt/", "trans": "concentration", "col": "concentrate on", "ex": "I can't concentrate with all this noise.", "pos": "v./n."},
    "concentration": {"def": "集中、專注、濃度", "ipa": "/ˌkɒnsnˈtreɪʃn/", "trans": "concentrate (動詞)", "col": "concentration camp, mental concentration", "ex": "This work requires great concentration.", "pos": "n."},
    "concept": {"def": "概念、觀念", "ipa": "/ˈkɒnsept/", "trans": "conceptual", "col": "basic concept, abstract concept", "ex": "The concept of time is difficult to define.", "pos": "n."},
    "concern": {"def": "關心、擔心、涉及、使擔心、關係、關心的事", "ipa": "/kənˈsɜːn/", "trans": "concerned, concerning", "col": "be concerned about, as far as I'm concerned", "ex": "Environmental issues concern us all.", "pos": "v./n."},
    "concert": {"def": "音樂會、協調、齊心協力", "ipa": "/ˈkɒnsət/", "trans": "concerted", "col": "live concert, pop concert", "ex": "I'm going to a rock concert tonight.", "pos": "n./v."},
    "conclude": {"def": "結論、結束、斷定", "ipa": "/kənˈkluːd/", "trans": "conclusion", "col": "conclude a speech", "ex": "The study concluded that the drug is safe.", "pos": "v."},
    "conclusion": {"def": "結論、結束", "ipa": "/kənˈkluːʒn/", "trans": "conclude (動詞)", "col": "in conclusion, reach a conclusion", "ex": "I've come to the conclusion that she's right.", "pos": "n."},
    "concrete": {"def": "具體的、混凝土、用混凝土澆築、具體地", "ipa": "/ˈkɒŋkriːt/", "trans": "concretion", "col": "concrete evidence, reinforced concrete", "ex": "Can you give me a concrete example?", "pos": "adj./n./v./adv."},
    "condition": {"def": "條件、狀況、疾病、使適應、制約", "ipa": "/kənˈdɪʃn/", "trans": "conditional", "col": "in good condition, working conditions", "ex": "The car is in excellent condition.", "pos": "n./v."},
    "conductor": {"def": "導體、指揮、售票員", "ipa": "/kənˈdʌktə/", "trans": "conduct (動詞)", "col": "orchestra conductor", "ex": "Copper is a good conductor of electricity.", "pos": "n."},
    "conference": {"def": "會議、討論會", "ipa": "/ˈkɒnfərəns/", "trans": "confer", "col": "press conference, international conference", "ex": "He is attending a medical conference.", "pos": "n."},
    "confess": {"def": "承認、供認、懺悔", "ipa": "/kənˈfes/", "trans": "confession", "col": "confess to a crime", "ex": "He confessed that he had stolen the money.", "pos": "v."},
    "confidence": {"def": "信心、信任、秘密", "ipa": "/ˈkɒnfɪdəns/", "trans": "confident, confidential", "col": "have confidence in, self-confidence", "ex": "I have full confidence in her ability.", "pos": "n."},
    "confident": {"def": "有信心的、自信的", "ipa": "/ˈkɒnfɪdənt/", "trans": "confidence (名詞), confidently", "col": "feel confident, confident of victory", "ex": "I'm confident that we will win.", "pos": "adj."},
    "confine": {"def": "限制、監禁、界限、範圍", "ipa": "/kənˈfaɪn/", "trans": "confinement", "col": "confine to, solitary confinement", "ex": "Please confine your remarks to the topic.", "pos": "v./n."},
    "confirm": {"def": "確認、證實、批准", "ipa": "/kənˈfɜːm/", "trans": "confirmation", "col": "confirm a flight, confirm rumors", "ex": "Could you confirm your hotel reservation?", "pos": "v."},
    "conflict": {"def": "衝突、鬥爭、不一致、衝突、爭鬥", "ipa": "/ˈkɒnflɪkt/ (n.) /kənˈflɪkt/ (v.)", "trans": "conflicting", "col": "conflict of interest, social conflict", "ex": "There was a lot of conflict between the two groups.", "pos": "n./v."},
    "confuse": {"def": "使困惑、混淆", "ipa": "/kənˈfjuːz/", "trans": "confusion, confusing", "col": "confuse A with B", "ex": "Stop it, you're confusing me!", "pos": "v."},
    "confusion": {"def": "困惑、混亂", "ipa": "/kənˈfjuːʒn/", "trans": "confuse (動詞)", "col": "in confusion, cause confusion", "ex": "There was some confusion as to who should pay.", "pos": "n."},
    "congratulate": {"def": "誠賀、恭喜", "ipa": "/kənˈɡrætʃuleɪt/", "trans": "congratulation", "col": "congratulate someone on", "ex": "I'd like to congratulate you on your success.", "pos": "v."},
    "congratulation": {"def": "祝賀、恭喜", "ipa": "/kənˌɡrætʃuˈleɪʃn/", "trans": "congratulate (動詞)", "col": "Congratulions!", "ex": "Congratulations on your new job!", "pos": "n."},
    "congress": {"def": "國會、議會、代表大會", "ipa": "/ˈkɒŋɡres/", "trans": "congressional, congressman", "col": "Library of Congress", "ex": "The bill was passed by Congress.", "pos": "n."},
    "connect": {"def": "連接、關聯、連接", "ipa": "/kəˈnekt/", "trans": "connection, connector", "col": "connect with, connect to internet", "ex": "The two buildings are connected by a tunnel.", "pos": "v."},
    "connection": {"def": "連接、關係、親戚、連線", "ipa": "/kəˈnekʃn/", "trans": "connect (動詞)", "col": "internet connection, in connection with", "ex": "There is a connection between the two events.", "pos": "n."},
    "conscious": {"def": "有意識的、自覺的", "ipa": "/ˈkɒnʃəs/", "trans": "consciousness, consciously", "col": "be conscious of, fashion conscious", "ex": "She was conscious that everyone was watching her.", "pos": "adj."},
    "consider": {"def": "考慮、認為、關心", "ipa": "/kənˈsɪdə/", "trans": "consideration, considerable", "col": "consider doing, take into account/consideration", "ex": "Please consider my offer.", "pos": "v."},
}

with open("batch_l2_p8.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART8, f, ensure_ascii=False, indent=2)
