import json

# Level 2 Part 13: (Duty - Exclude)
L2_PART13 = {
    "duty": {"def": "義務、責任、關稅", "ipa": "/ˈdjuːti/", "trans": "duties", "col": "on duty, sense of duty, heavy-duty", "ex": "It's my duty to protect you.", "pos": "n."},
    "DVD": {"def": "數位影碟", "ipa": "/ˌdiː viː ˈdiː/", "trans": "DVDs", "col": "DVD player", "ex": "I bought a new DVD yesterday.", "pos": "n."},
    "dye": {"def": "染料、染色、染色、給...染色", "ipa": "/daɪ/", "trans": "dyed, dyeing", "col": "hair dye", "ex": "She dyed her hair red.", "pos": "n./v."},
    "dynamic": {"def": "動力、動態、動力的、有活力的", "ipa": "/daɪˈnæmɪk/", "trans": "dynamically", "col": "dynamic system, dynamic person", "ex": "He is a very dynamic leader.", "pos": "n./adj."},
    "dynasty": {"def": "王朝、代", "ipa": "/ˈdɪnəsti/", "trans": "dynasties", "col": "Ming Dynasty", "ex": "The Tang Dynasty was a golden age in Chinese history.", "pos": "n."},
    "each": {"def": "每個、各個、每個、各自地", "ipa": "/iːtʃ/", "trans": "every", "col": "each other, each one", "ex": "Each student has a book.", "pos": "adj./pron./adv."},
    "eager": {"def": "渴望的、熱心的", "ipa": "/ˈiːɡə/", "trans": "eagerly, eagerness", "col": "be eager to, eager for", "ex": "The kids were eager to open their presents.", "pos": "adj."},
    "eagle": {"def": "老鷹", "ipa": "/ˈiːɡl/", "trans": "eagles", "col": "bald eagle", "ex": "An eagle was soaring high in the sky.", "pos": "n."},
    "ear": {"def": "耳朵、聽覺、傾聽", "ipa": "/ɪə/", "trans": "earache", "col": "play by ear, give ear to, ear of corn", "ex": "He has a good ear for music.", "pos": "n."},
    "early": {"def": "早的、早期的、提早、早地", "ipa": "/ˈɜːli/", "trans": "earlier", "col": "early bird, early morning", "ex": "I got up early this morning.", "pos": "adj./adv."},
    "earn": {"def": "賺得、贏得、獲得", "ipa": "/ɜːn/", "trans": "earnings, earner", "col": "earn a living, earn money", "ex": "How much does he earn a year?", "pos": "v."},
    "earnest": {"def": "認真的、誠摯的、認真、定金", "ipa": "/ˈɜːnɪst/", "trans": "earnestly", "col": "in earnest, in dead earnest", "ex": "He is an earnest young man.", "pos": "adj./n."},
    "earnings": {"def": "收入、利潤", "ipa": "/ˈɜːnɪŋz/", "trans": "earn (動詞)", "col": "annual earnings", "ex": "The company's earnings have fallen lately.", "pos": "n."},
    "earphone": {"def": "耳機", "ipa": "/ˈɪəfəʊn/", "trans": "earphones", "col": "wear earphones", "ex": "I've lost my earphones.", "pos": "n."},
    "earth": {"def": "地球、陸地、地面、泥土", "ipa": "/ɜːθ/", "trans": "earthly, earthquake", "col": "on earth, earth surface", "ex": "The moon moves around the earth.", "pos": "n."},
    "earthquake": {"def": "地震", "ipa": "/ˈɜːθkweɪk/", "trans": "earthquakes", "col": "suffer an earthquake", "ex": "The city was destroyed by an earthquake.", "pos": "n."},
    "ease": {"def": "安逸、悠閒、放鬆、使安逸、減輕", "ipa": "/iːz/", "trans": "easy, easily", "col": "at ease, with ease", "ex": "He passed the test with ease.", "pos": "n./v."},
    "east": {"def": "東方、東部、東方的、向東地", "ipa": "/iːst/", "trans": "eastern", "col": "Middle East, Far East", "ex": "The sun rises in the east.", "pos": "n./adj./adv."},
    "Easter": {"def": "復活節", "ipa": "/ˈiːstə/", "trans": "Easterly", "col": "Easter Sunday, Easter egg", "ex": "Easter is in March or April.", "pos": "n."},
    "eastern": {"def": "東方的、東部的", "ipa": "/ˈiːstən/", "trans": "east (名詞)", "col": "eastern Europe", "ex": "They live in eastern Taiwan.", "pos": "adj."},
    "easy": {"def": "容易的、舒適的、輕鬆地", "ipa": "/ˈiːzi/", "trans": "easily, easiness", "col": "easy-going, easy street, take it easy", "ex": "The exam was very easy.", "pos": "adj./adv."},
    "eat": {"def": "吃、腐蝕", "ipa": "/iːt/", "trans": "eatable, eaten", "col": "eat out, eat up", "ex": "I'm so hungry I could eat a horse.", "pos": "v."},
    "echo": {"def": "回聲、反響、發出回聲、重複、反射", "ipa": "/ˈekəʊ/", "trans": "echoes, echoing", "col": "echo back", "ex": "The shout echoed through the mountains.", "pos": "n./v."},
    "ecology": {"def": "生態學、生態", "ipa": "/iˈkɒlədʒi/", "trans": "ecological, ecologist", "col": "environmental ecology", "ex": "The oil spill damaged the local ecology.", "pos": "n."},
    "economic": {"def": "經濟的、獲利的", "ipa": "/ˌiːkəˈnɒmɪk/", "trans": "economy, economics", "col": "economic growth, economic crisis", "ex": "The country is facing an economic crisis.", "pos": "adj."},
    "economical": {"def": "節省的、節約的", "ipa": "/ˌiːkəˈnɒmɪkl/", "trans": "economy (名詞), economically", "col": "economical car", "ex": "It's more economical to buy in bulk.", "pos": "adj."},
    "economics": {"def": "經濟學", "ipa": "/ˌiːkəˈnɒmɪks/", "trans": "economic (形容詞)", "col": "major in economics", "ex": "He is studying economics at university.", "pos": "n."},
    "economy": {"def": "經濟、節約、便宜的", "ipa": "/ɪˈkɒnəmi/", "trans": "economic, economist", "col": "market economy, world economy", "ex": "The global economy is slowing down.", "pos": "n./adj."},
    "edge": {"def": "邊緣、刀口、優勢、給...加邊、緩緩移動", "ipa": "/edʒ/", "trans": "edged, edgy", "col": "on edge, cutting edge", "ex": "Don't stand so close to the edge.", "pos": "n./v."},
    "edible": {"def": "可以食用的", "ipa": "/ˈedəbl/", "trans": "eat (動詞)", "col": "edible oil, edible fruit", "ex": "Are these berries edible?", "pos": "adj."},
    "edit": {"def": "編輯、剪輯、校訂", "ipa": "/ˈedɪt/", "trans": "editor, edition", "col": "edit a video", "ex": "He is editing a new dictionary.", "pos": "v."},
    "edition": {"def": "版本、版次", "ipa": "/ɪˈdɪʃn/", "trans": "edit (動詞)", "col": "first edition, limited edition", "ex": "I have the latest edition of the software.", "pos": "n."},
    "editor": {"def": "編輯者、主編", "ipa": "/ˈedɪtə/", "trans": "edit (動詞)", "col": "editor-in-chief", "ex": "He is the sports editor of the newspaper.", "pos": "n."},
    "educate": {"def": "教育、教導", "ipa": "/ˈedjukeɪt/", "trans": "education, educator", "col": "well-educated", "ex": "He was educated at Oxford University.", "pos": "v."},
    "education": {"def": "教育、訓練", "ipa": "/ˌedjuˈkeɪʃn/", "trans": "educate (動詞), educational", "col": "higher education, physical education", "ex": "Education is the key to success.", "pos": "n."},
    "educational": {"def": "教育的、有教育意義的", "ipa": "/ˌedjuˈkeɪʃənl/", "trans": "education (名詞)", "col": "educational TV", "ex": "The trip was an educational experience for the children.", "pos": "adj."},
    "educator": {"def": "教育工作者、教師", "ipa": "/ˈedjukeɪtə/", "trans": "educate (動詞)", "col": "distinguished educator", "ex": "She is a leading educator in the field of science.", "pos": "n."},
    "effect": {"def": "效應、影響、效果、財產、引起、產生", "ipa": "/ɪˈfekt/", "trans": "effective, efficient", "col": "side effect, greenhouse effect, in effect", "ex": "The medicine had no effect on the pain.", "pos": "n./v."},
    "effective": {"def": "有效的、起作用的", "ipa": "/ɪˈfektɪv/", "trans": "effect (名詞), effectively", "col": "effective strategy", "ex": "The new law will become effective next month.", "pos": "adj."},
    "efficiency": {"def": "效率、效能", "ipa": "/ɪˈfɪʃənsi/", "trans": "efficient", "col": "energy efficiency", "ex": "We need to improve our production efficiency.", "pos": "n."},
    "efficient": {"def": "效率高的、有能力的", "ipa": "/ɪˈfɪʃnt/", "trans": "efficiency (名詞), efficiently", "col": "efficient use of time", "ex": "The new system is much more efficient.", "pos": "adj."},
    "effort": {"def": "努力、成就", "ipa": "/ˈefət/", "trans": "effortless", "col": "make an effort, spare no effort", "ex": "Success requires hard work and effort.", "pos": "n."},
    "egg": {"def": "蛋、卵、激勵", "ipa": "/eɡ/", "trans": "eggplant", "col": "boiled egg, Easter egg, egg on", "ex": "I'd like my eggs fried.", "pos": "n./v."},
    "eight": {"def": "八、八個", "ipa": "/eɪt/", "trans": "eighth", "col": "eight o'clock", "ex": "He is eight years old.", "pos": "num./n."},
    "eighteen": {"def": "十八", "ipa": "/ˌeɪˈtiːn/", "trans": "eighteenth", "col": "at eighteen", "ex": "She is eighteen now.", "pos": "num./n."},
    "eighty": {"def": "八十", "ipa": "/ˈeɪti/", "trans": "eightieth", "col": "eighty years", "ex": "My grandmother is eighty.", "pos": "num./n."},
    "either": {"def": "（兩者之中）任一、非此即彼、也（用於否定句）", "ipa": "/ˈaɪðə/ (pron./adj.) /ˈiːðə/ (adv.)", "trans": "neither", "col": "either...or", "ex": "You can have either juice or milk.", "pos": "pron./adj./adv./conj."},
    "elaborate": {"def": "精心製作的、複雜的、詳盡闡述、精心製作", "ipa": "/ɪˈlæbərət/ (adj.) /ɪˈlæbəreɪt/ (v.)", "trans": "elaboration", "col": "elaborate plan", "ex": "He gave an elaborate explanation of the theory.", "pos": "adj./v."},
    "elastic": {"def": "有彈性的、靈活的、橡皮筋", "ipa": "/ɪˈlæstɪk/", "trans": "elasticity", "col": "elastic band", "ex": "This fabric is very elastic.", "pos": "adj./n."},
    "elbow": {"def": "肘、彎頭、用肘推、擠過", "ipa": "/ˈelbəʊ/", "trans": "elbowroom", "col": "at one's elbow", "ex": "He rested his elbows on the table.", "pos": "n./v."},
    "elder": {"def": "年長的、資格老的、長輩、老人", "ipa": "/ˈeldə/", "trans": "elderly", "col": "elder brother", "ex": "My elder sister is a teacher.", "pos": "adj./n."},
    "elderly": {"def": "上了年紀的、年長的人", "ipa": "/ˈeldəli/", "trans": "elder (形容詞)", "col": "elderly woman", "ex": "She takes care of an elderly couple.", "pos": "adj./n."},
    "elect": {"def": "選舉、挑選、當選的", "ipa": "/ɪˈlekt/", "trans": "election, elective", "col": "elect a president", "ex": "He was elected class president.", "pos": "v./adj."},
    "election": {"def": "選舉、當選", "ipa": "/ɪˈlekʃn/", "trans": "elect (動詞)", "col": "general election, presidential election", "ex": "The next election will be held in May.", "pos": "n."},
    "electric": {"def": "電的、用電的、激動人心的", "ipa": "/ɪˈlektrɪk/", "trans": "electricity, electrical", "col": "electric guitar, electric light", "ex": "Do you have an electric toothbrush?", "pos": "adj."},
    "electrical": {"def": "與電有關的、電氣的", "ipa": "/ɪˈlektrɪkl/", "trans": "electricity, electric", "col": "electrical engineering, electrical appliances", "ex": "He is an electrical engineer.", "pos": "adj."},
    "electrician": {"def": "電工", "ipa": "/ɪˌlekˈtrɪʃn/", "trans": "electric (形容詞)", "col": "qualified electrician", "ex": "We need to call an electrician.", "pos": "n."},
    "electricity": {"def": "電、電力", "ipa": "/ɪˌlekˈtrɪsəti/", "trans": "electric (形容詞)", "col": "static electricity, generate electricity", "ex": "The house has no electricity.", "pos": "n."},
    "electronic": {"def": "電子的", "ipa": "/ɪˌlekˈtrɒnɪk/", "trans": "electronics", "col": "electronic music, electronic components", "ex": "I bought an electronic dictionary.", "pos": "adj."},
    "electronics": {"def": "電子學、電子設備", "ipa": "/ɪˌlekˈtrɒnɪks/", "trans": "electronic (形容詞)", "col": "consumer electronics", "ex": "Singapore is a hub for electronics manufacturing.", "pos": "n."},
    "elegant": {"def": "優雅的、高雅的", "ipa": "/ˈelɪɡənt/", "trans": "elegance, elegantly", "col": "elegant dress", "ex": "She was wearing an elegant black dress.", "pos": "adj."},
    "element": {"def": "元素、要素、原理、自然力", "ipa": "/ˈelɪmənt/", "trans": "elementary, elemental", "col": "chemical element, essential element", "ex": "Water is a chemical element.", "pos": "n."},
    "elementary": {"def": "初級的、基本的", "ipa": "/ˌelɪˈmentri/", "trans": "element (名詞)", "col": "elementary school", "ex": "She is an elementary school teacher.", "pos": "adj."},
    "elephant": {"def": "大象", "ipa": "/ˈelɪfənt/", "trans": "elephants", "col": "white elephant", "ex": "An elephant has a long trunk.", "pos": "n."},
    "elevator": {"def": "電梯、升降機", "ipa": "/ˈelɪveɪtə/", "trans": "elevate (動詞)", "col": "take the elevator", "ex": "Let's take the elevator to the 10th floor.", "pos": "n."},
    "eleven": {"def": "十一", "ipa": "/ɪˈlevn/", "trans": "eleventh", "col": "eleven o'clock", "ex": "He is eleven years old.", "pos": "num./n."},
    "eligible": {"def": "有資格的、合格的", "ipa": "/ˈelɪdʒəbl/", "trans": "eligibility", "col": "eligible for", "ex": "Only citizens are eligible to vote.", "pos": "adj."},
    "eliminate": {"def": "消除、排除、淘汰", "ipa": "/ɪˈlɪmɪneɪt/", "trans": "elimination", "col": "eliminate poverty", "ex": "The goal is to eliminate all forms of discrimination.", "pos": "v."},
    "else": {"def": "其他、另外、否則", "ipa": "/els/", "trans": "elsewhere", "col": "or else, someone else", "ex": "Is there anything else you want to say?", "pos": "adv./adj."},
    "elsewhere": {"def": "在別處、向別處", "ipa": "/ˌelsˈweə/", "trans": "else (形容詞)", "col": "look elsewhere", "ex": "The answer must be found elsewhere.", "pos": "adv."},
    "email/e-mail": {"def": "電子郵件、寄電子郵件", "ipa": "/ˈiːmeɪl/", "trans": "emailing", "col": "send an email", "ex": "Give me your email address.", "pos": "n./v."},
    "embarrass": {"def": "使尷尬、使侷促不安", "ipa": "/ɪmˈbærəs/", "trans": "embarrassment, embarrassed", "col": "embarrass someone", "ex": "Don't ask him that, you'll embarrass him.", "pos": "v."},
    "embarrassed": {"def": "感到尷尬的", "ipa": "/ɪmˈbærəst/", "trans": "embarrass (動詞)", "col": "be embarrassed about", "ex": "She was embarrassed about her mistake.", "pos": "adj."},
    "embarrassment": {"def": "尷尬、難堪之事", "ipa": "/ɪmˈbærəsmənt/", "trans": "embarrass (動詞)", "col": "source of embarrassment", "ex": "He suffered the embarrassment of falling down in public.", "pos": "n."},
    "embassy": {"def": "大使館", "ipa": "/ˈembəsi/", "trans": "embassies", "col": "US embassy", "ex": "He works at the British embassy.", "pos": "n."},
    "embody": {"def": "體現、使具體化、包含", "ipa": "/ɪmˈbɒdi/", "trans": "embodiment", "col": "embody an ideal", "ex": "Small businesses embody the spirit of free enterprise.", "pos": "v."},
    "embrace": {"def": "擁抱、包含、接受、擁抱", "ipa": "/ɪmˈbreɪs/", "trans": "embraced", "col": "embrace a challenge", "ex": "They embraced each other warmly.", "pos": "v./n."},
    "emerge": {"def": "出現、浮現、暴露", "ipa": "/ɪˈmɜːdʒ/", "trans": "emergence, emergent", "col": "emerge from", "ex": "The sun emerged from behind the clouds.", "pos": "v."},
    "emergency": {"def": "緊急情況、突發事件", "ipa": "/ɪˈmɜːdʒənsi/", "trans": "emerge (動詞)", "col": "emergency exit, in case of emergency", "ex": "Call 911 in an emergency.", "pos": "n."},
    "emotion": {"def": "情緒、情感、激情", "ipa": "/ɪˈməʊʃn/", "trans": "emotional", "col": "deep emotion, show emotion", "ex": "He couldn't hide his emotions.", "pos": "n."},
    "emotional": {"def": "情緒的、情感的、易激動的", "ipa": "/ɪˈməʊʃənl/", "trans": "emotion (名詞), emotionally", "col": "emotional support", "ex": "He gave an emotional speech at the funeral.", "pos": "adj."},
    "emperor": {"def": "皇帝、君主", "ipa": "/ˈempərə/", "trans": "empress", "col": "Roman emperor", "ex": "Napoleon was the first emperor of France.", "pos": "n."},
    "emphasis": {"def": "強調、重點", "ipa": "/ˈemfəsɪs/", "trans": "emphasize", "col": "place emphasis on", "ex": "The course puts emphasis on practical skills.", "pos": "n."},
    "emphasize": {"def": "強調、著重", "ipa": "/ˈemfəsaɪz/", "trans": "emphasis (名詞)", "col": "emphasize a point", "ex": "He emphasized that the plan was only a draft.", "pos": "v."},
    "empire": {"def": "帝國、大企業", "ipa": "/ˈempaɪə/", "trans": "imperial", "col": "British Empire, Galactic Empire", "ex": "The Roman Empire was very powerful.", "pos": "n."},
    "employ": {"def": "雇用、使用、職業", "ipa": "/ɪmˈplɔɪ/", "trans": "employment, employer, employee", "col": "employ someone as", "ex": "The factory employs over 500 workers.", "pos": "v./n."},
    "employee": {"def": "員工、受雇者", "ipa": "/ɪmˈplɔɪiː/", "trans": "employ (動詞), employer", "col": "full-time employee", "ex": "He is a government employee.", "pos": "n."},
    "employer": {"def": "雇主、老闆", "ipa": "/ɪmˈplɔɪə/", "trans": "employ (動詞), employee", "col": "current employer", "ex": "The company is a major employer in the region.", "pos": "n."},
    "employment": {"def": "雇用、職業、使用", "ipa": "/ɪmˈplɔɪmənt/", "trans": "employ (動詞), unemployment", "col": "full-time employment, find employment", "ex": "She is looking for full-time employment.", "pos": "n."},
    "empty": {"def": "空的、無意義的、倒空、變空、空的、空車", "ipa": "/ˈempti/", "trans": "emptiness", "col": "empty bottle, empty words", "ex": "The glass is empty.", "pos": "adj./v./n."},
    "enable": {"def": "使能夠、使可能", "ipa": "/ɪˈneɪbl/", "trans": "enabled", "col": "enable someone to do", "ex": "The software enables us to process data faster.", "pos": "v."},
    "enclose": {"def": "圍住、封入、附寄", "ipa": "/ɪnˈkləʊz/", "trans": "enclosure", "col": "enclose a letter", "ex": "The garden is enclosed by a high wall.", "pos": "v."},
    "encounter": {"def": "遭遇、遇到、意外相遇、衝突", "ipa": "/ɪnˈkaʊntə/", "trans": "encountered", "col": "encounter difficulties", "ex": "I encountered many problems during the trip.", "pos": "v./n."},
    "encourage": {"def": "鼓勵、助長", "ipa": "/ɪnˈkʌrɪdʒ/", "trans": "encouragement, encouraged", "col": "encourage someone to do", "ex": "My teacher encouraged me to study hard.", "pos": "v."},
    "encouragement": {"def": "鼓勵、激勵", "ipa": "/ɪnˈkʌrɪdʒmənt/", "trans": "encourage (動詞)", "col": "words of encouragement", "ex": "I appreciate your support and encouragement.", "pos": "n."},
    "ending": {"def": "結局、終結、結尾的", "ipa": "/ˈendɪŋ/", "trans": "end (名詞/動詞)", "col": "happy ending", "ex": "The film has a very sad ending.", "pos": "n./adj."},
    "endurance": {"def": "忍耐、持久力", "ipa": "/ɪnˈdjʊərəns/", "trans": "endure (動詞)", "col": "physical endurance", "ex": "The exam was a test of his endurance.", "pos": "n."},
    "endure": {"def": "忍受、持久", "ipa": "/ɪnˈdjʊə/", "trans": "endurance, enduring", "col": "endure pain", "ex": "He endured many hardships in his life.", "pos": "v."},
    "enemy": {"def": "敵人、仇敵、敵人的", "ipa": "/ˈenəmi/", "trans": "enemies", "col": "public enemy, common enemy", "ex": "They are sworn enemies.", "pos": "n./adj."},
    "energetic": {"def": "精力充沛的、積極的", "ipa": "/ˌenəˈdʒetɪk/", "trans": "energy (名詞), energetically", "col": "energetic person", "ex": "She is a very energetic woman.", "pos": "adj."},
    "energy": {"def": "能量、精力、活力", "ipa": "/ˈenədʒi/", "trans": "energetic, energize", "col": "solar energy, kinetic energy, waste energy", "ex": "We should use energy more efficiently.", "pos": "n."},
    "enforce": {"def": "執行、實施、強迫", "ipa": "/ɪnˈfɔːs/", "trans": "enforcement", "col": "enforce a law", "ex": "The police are here to enforce the law.", "pos": "v."},
    "engage": {"def": "從事、參加、訂婚、吸引（注意力）", "ipa": "/ɪnˈɡeɪdʒ/", "trans": "engagement, engaged", "col": "engage in", "ex": "She is engaged in a very interesting project.", "pos": "v."},
    "engaged": {"def": "忙碌的、訂婚了的、使用中的", "ipa": "/ɪnˈɡeɪdʒd/", "trans": "engage (動詞), engagement", "col": "get engaged to", "ex": "They got engaged last month.", "pos": "adj."},
    "engagement": {"def": "諾言、約定、訂婚、交戰", "ipa": "/ɪnˈɡeɪdʒmənt/", "trans": "engage (動詞)", "col": "previous engagement", "ex": "I'm sorry, I have a previous engagement.", "pos": "n."},
    "engine": {"def": "引擎、發動機、火車頭", "ipa": "/ˈendʒɪn/", "trans": "engineer, engineering", "col": "search engine, diesel engine", "ex": "The engine has stopped working.", "pos": "n."},
    "engineer": {"def": "工程師、技師、設計、策劃", "ipa": "/ˌendʒɪˈnɪə/", "trans": "engineering, engine (名詞)", "col": "software engineer, civil engineer", "ex": "He is a civil engineer.", "pos": "n./v."},
    "engineering": {"def": "工程（學）", "ipa": "/ˌendʒɪˈnɪərɪŋ/", "trans": "engineer (名詞)", "col": "genetic engineering, electrical engineering", "ex": "The bridge is a marvel of engineering.", "pos": "n."},
    "enjoyment": {"def": "享受、樂趣", "ipa": "/ɪnˈdʒɔɪmənt/", "trans": "enjoy (動詞)", "col": "source of enjoyment", "ex": "The trip was a source of great enjoyment for us.", "pos": "n."},
    "enlarge": {"def": "擴大、放大、詳述", "ipa": "/ɪnˈlɑːdʒ/", "trans": "enlargement", "col": "enlarge a photo", "ex": "We decided to enlarge our house.", "pos": "v."},
    "enormous": {"def": "巨大的、龐大的", "ipa": "/ɪˈnɔːməs/", "trans": "enormously, enormity", "col": "enormous amount", "ex": "He has an enormous appetite.", "pos": "adj."},
    "enough": {"def": "足夠的、足夠、充足、足以、足夠地", "ipa": "/ɪˈnʌf/", "trans": "sufficiency", "col": "fair enough, sure enough", "ex": "I have enough money to buy the car.", "pos": "adj./adv./n./int."},
    "ensure": {"def": "確保、保證", "ipa": "/ɪnˈʃʊə/", "trans": "ensured", "col": "ensure safety", "ex": "The law is designed to ensure fair competition.", "pos": "v."},
    "enterprise": {"def": "企業、事業、進取心", "ipa": "/ˈentəpraɪz/", "trans": "enterprising", "col": "private enterprise, state-owned enterprise", "ex": "He is full of enterprise and initiative.", "pos": "n."},
    "entertain": {"def": "娛樂、招待、心存（想法）", "ipa": "/ˌentəˈteɪn/", "trans": "entertainment, entertainer", "col": "entertain guests", "ex": "He likes to entertain his friends with stories.", "pos": "v."},
    "entertainer": {"def": "演藝人員、表演者", "ipa": "/ˌentəˈteɪnə/", "trans": "entertain (動詞)", "col": "popular entertainer", "ex": "He is a versatile entertainer.", "pos": "n."},
    "entertainment": {"def": "娛樂、招待、演藝業", "ipa": "/ˌentəˈteɪnmənt/", "trans": "entertain (動詞)", "col": "mass entertainment", "ex": "Movies are a popular form of entertainment.", "pos": "n."},
    "enthusiasm": {"def": "熱情、熱忱", "ipa": "/ɪnˈθjuːziæzəm/", "trans": "enthusiastic, enthusiast", "col": "full of enthusiasm", "ex": "His enthusiasm for the project was infectious.", "pos": "n."},
    "enthusiastic": {"def": "熱情的、熱心的", "ipa": "/ɪnˌθjuːziˈæstɪk/", "trans": "enthusiasm (名詞), enthusiastically", "col": "enthusiastic support", "ex": "She is very enthusiastic about her new job.", "pos": "adj."},
    "entire": {"def": "整個的、全部的", "ipa": "/ɪnˈtaɪə/", "trans": "entirely, entirety", "col": "entire life, entire world", "ex": "The entire building was destroyed by fire.", "pos": "adj."},
    "entirely": {"def": "完全地、全心地", "ipa": "/ɪnˈtaɪəli/", "trans": "entire (形容詞)", "col": "entirely different", "ex": "I agree with you entirely.", "pos": "adv."},
    "entrance": {"def": "入口、進入、入學", "ipa": "/ˈentrəns/", "trans": "entry, enter (動詞)", "col": "main entrance, entrance exam", "ex": "I'll meet you at the main entrance.", "pos": "n."},
    "entry": {"def": "進入、入口、條目、登記", "ipa": "/ˈentri/", "trans": "entrance, enter (動詞)", "col": "no entry, diary entry", "ex": "Entries must be received by Monday.", "pos": "n."},
    "envelope": {"def": "信封、封套", "ipa": "/ˈenvələʊp/", "trans": "envelop (動詞)", "col": "stamped envelope", "ex": "Put the letter in the envelope.", "pos": "n."},
    "envious": {"def": "妒忌的、羨慕的", "ipa": "/ˈenviəs/", "trans": "envy (名詞/動詞)", "col": "be envious of", "ex": "I'm not envious of his success.", "pos": "adj."},
    "environment": {"def": "環境、外界", "ipa": "/ɪnˈvaɪrənmənt/", "trans": "environmental, environmentally", "col": "protect the environment, living environment", "ex": "We should all help to protect the environment.", "pos": "n."},
    "environmental": {"def": "環境的、環保的", "ipa": "/ɪnˌvaɪrənˈmentl/", "trans": "environment (名詞)", "col": "environmental protection, environmental issues", "ex": "Environmental issues are becoming more important.", "pos": "adj."},
    "envy": {"def": "嫉妒、羨慕、嫉妒之源、嫉妒、羨慕", "ipa": "/ˈenvi/", "trans": "envious", "col": "out of envy, green with envy", "ex": "I envy your success.", "pos": "n./v."},
    "episode": {"def": "（影集）一集、一段插曲、一段經歷", "ipa": "/ˈepɪsəʊd/", "trans": "episodes", "col": "TV episode", "ex": "I missed the last episode of the series.", "pos": "n."},
    "equal": {"def": "相等的、平等的、勝任的、對手、相等體、等於、比得上", "ipa": "/ˈiːkwəl/", "trans": "equality, equally", "col": "be equal to, equal rights", "ex": "All men are created equal.", "pos": "adj./n./v."},
    "equality": {"def": "平等、相等", "ipa": "/iˈkwɒləti/", "trans": "equal (形容詞)", "col": "gender equality, social equality", "ex": "We are fighting for racial equality.", "pos": "n."},
    "equally": {"def": "相等地、同樣地", "ipa": "/ˈiːkwəli/", "trans": "equal (形容詞)", "col": "equally important", "ex": "The two sides were equally matched.", "pos": "adv."},
    "equip": {"def": "裝備、配備、使具備能力", "ipa": "/ɪˈkwɪp/", "trans": "equipment", "col": "equip with", "ex": "The hotel is equipped with every modern comfort.", "pos": "v."},
    "equipment": {"def": "設備、器材、裝備", "ipa": "/ɪˈkwɪpmənt/", "trans": "equip (動詞)", "col": "medical equipment, office equipment", "ex": "The climbers took all the necessary equipment.", "pos": "n."},
    "equivalent": {"def": "相等的、等值的、相等物、等價物", "ipa": "/ɪˈkwɪvələnt/", "trans": "equivalence", "col": "equivalent to", "ex": "Is there a French equivalent of this word?", "pos": "adj./n."},
    "era": {"def": "紀元、時代", "ipa": "/ˈɪərə/", "trans": "eras", "col": "Christian era, golden era", "ex": "The computer age has ushered in a new era.", "pos": "n."},
    "erase": {"def": "擦掉、抹去、消除", "ipa": "/ɪˈreɪz/", "trans": "eraser, erasure", "col": "erase memories", "ex": "He used an eraser to erase the mistake.", "pos": "v."},
    "eraser": {"def": "橡皮擦、黑板擦", "ipa": "/ɪˈreɪzə/", "trans": "erase (動詞)", "col": "pencil eraser", "ex": "I need an eraser to correct my drawing.", "pos": "n."},
    "errand": {"def": "差事、跑腿", "ipa": "/ˈerənd/", "trans": "errands", "col": "run an errand", "ex": "He is out running errands.", "pos": "n."},
    "error": {"def": "錯誤、差錯、過失", "ipa": "/ˈerə/", "trans": "erroneous", "col": "human error, trial and error", "ex": "The document is full of errors.", "pos": "n."},
    "escape": {"def": "逃跑、避免、遺忘、逃跑、避難、洩漏", "ipa": "/ɪˈskeɪp/", "trans": "escapement", "col": "narrow escape, fire escape", "ex": "They managed to escape from the prison.", "pos": "v./n."},
    "essay": {"def": "散文、論文、小品文、企圖、嘗試", "ipa": "/ˈeseɪ/", "trans": "essayist", "col": "write an essay", "ex": "He won first prize in the essay contest.", "pos": "n./v."},
    "essence": {"def": "本質、精髓、香精", "ipa": "/ˈesns/", "trans": "essential", "col": "in essence, vanilla essence", "ex": "The essence of his argument is quite simple.", "pos": "n."},
    "essential": {"def": "本質的、必要的、精華的、要素、必需品", "ipa": "/ɪˈsenʃl/", "trans": "essence (名詞), essentially", "col": "essential oils, essential factor", "ex": "Water is essential for life.", "pos": "adj./n."},
    "establish": {"def": "建立、創立、確定、安置", "ipa": "/ɪˈstæblɪʃ/", "trans": "establishment", "col": "establish a relationship, establish a company", "ex": "The university was established in 1900.", "pos": "v."},
    "establishment": {"def": "建立、機構、編制", "ipa": "/ɪˈstæblɪʃmənt/", "trans": "establish (動詞)", "col": "educational establishment", "ex": "The hotel is an old and world-famous establishment.", "pos": "n."},
    "estate": {"def": "房地產、產產、莊園", "ipa": "/ɪˈsteɪt/", "trans": "estates", "col": "real estate, housing estate", "ex": "He left his entire estate to his wife.", "pos": "n."},
    "estimate": {"def": "估計、估價、評價、估計、估價", "ipa": "/ˈestɪmət/ (n.) /ˈestɪmeɪt/ (v.)", "trans": "estimation, estimator", "col": "rough estimate, give an estimate", "ex": "We estimate that the project will take six months.", "pos": "n./v."},
    "etc.": {"def": "等等", "ipa": "/et ˈsetərə/", "trans": "and so on", "col": "apples, oranges, etc.", "ex": "We bought pens, paper, etc.", "pos": "abbr."},
    "eternal": {"def": "永恆的、不休的、永恆的事物", "ipa": "/ɪˈtɜːnl/", "trans": "eternity, eternally", "col": "eternal life", "ex": "He promised her eternal love.", "pos": "adj./n."},
    "ethics": {"def": "倫理、道德、倫理學", "ipa": "/ˈeθɪks/", "trans": "ethical", "col": "business ethics, code of ethics", "ex": "He is a man of high ethics.", "pos": "n."},
    "ethnic": {"def": "種族的、異國風味的", "ipa": "/ˈeθnɪk/", "trans": "ethnicity", "col": "ethnic group, ethnic food", "ex": "The country has many different ethnic groups.", "pos": "adj."},
    "evaluate": {"def": "評估、評價", "ipa": "/ɪˈvæljueɪt/", "trans": "evaluation", "col": "evaluate options", "ex": "We need to evaluate the results of the project.", "pos": "v."},
    "evaluation": {"def": "評估、估價", "ipa": "/ɪˌvæljuˈeɪʃn/", "trans": "evaluate (動詞)", "col": "performance evaluation", "ex": "The teacher gave us a term-end evaluation.", "pos": "n."},
    "eve": {"def": "前夕、傍晚", "ipa": "/iːv/", "trans": "evenings", "col": "Christmas Eve, New Year's Eve", "ex": "I met him on the eve of his departure.", "pos": "n."},
    "even": {"def": "甚至、即使、平坦的、偶數的、弄平、加倍、甚至於", "ipa": "/ˈiːvn/", "trans": "evenly, evenness", "col": "even if, even though, even number", "ex": "He doesn't even know your name.", "pos": "adv./adj./v."},
    "evening": {"def": "傍晚、晚上、晚上的", "ipa": "/ˈiːvnɪŋ/", "trans": "evenings", "col": "good evening", "ex": "What are you doing this evening?", "pos": "n./adj."},
    "event": {"def": "事件、比賽、大變動", "ipa": "/ɪˈvent/", "trans": "eventful, eventually", "col": "sporting event, in the event of", "ex": "The wedding was the social event of the year.", "pos": "n."},
    "eventual": {"def": "最終的、結果的", "ipa": "/ɪˈventʃuəl/", "trans": "eventually", "col": "eventual success", "ex": "His eventual defeat was predictable.", "pos": "adj."},
    "eventually": {"def": "最終、終於", "ipa": "/ɪˈventʃuəli/", "trans": "eventual (形容詞)", "col": "eventually happen", "ex": "She eventually passed her driving test.", "pos": "adv."},
    "ever": {"def": "曾經、永遠、究竟", "ipa": "/ˈevə/", "trans": "forever", "col": "happily ever after, ever since", "ex": "Have you ever been to Paris?", "pos": "adv."},
    "every": {"def": "每個、所有的", "ipa": "/ˈevri/", "trans": "everybody, everyone, everything", "col": "every day, every now and then", "ex": "I exercise every morning.", "pos": "adj."},
    "evidence": {"def": "證據、證詞、明顯、證明、顯示", "ipa": "/ˈevɪdəns/", "trans": "evident", "col": "direct evidence, in evidence", "ex": "There is no evidence to support the claim.", "pos": "n./v."},
    "evident": {"def": "明顯的、明白的", "ipa": "/ˈevɪdənt/", "trans": "evidence (名詞), evidently", "col": "self-evident", "ex": "It's evident that he's lying.", "pos": "adj."},
    "evil": {"def": "邪惡的、有害的、邪惡、罪惡、邪惡地", "ipa": "/ˈiːvl/", "trans": "evilly", "col": "the root of all evil", "ex": "He chose the lesser of two evils.", "pos": "adj./n./adv."},
    "evolution": {"def": "進化、演變、發展", "ipa": "/ˌiːvəˈluːʃn/", "trans": "evolve (動詞)", "col": "theory of evolution", "ex": "The book traces the evolution of the novel.", "pos": "n."},
    "evolve": {"def": "進化、發展、演變", "ipa": "/ɪˈvɒlv/", "trans": "evolution, evolving", "col": "evolve from", "ex": "The company has evolved into a global brand.", "pos": "v."},
    "exact": {"def": "確切的、嚴格的、強求、勒索", "ipa": "/ɪɡˈzækt/", "trans": "exactly", "col": "exact location, to be exact", "ex": "I need to know the exact date.", "pos": "adj./v."},
    "exactly": {"def": "確切地、正是", "ipa": "/ɪɡˈzæktli/", "trans": "exact (形容詞)", "col": "exactly the same", "ex": "That's exactly what I want.", "pos": "adv."},
    "exaggerate": {"def": "誇張、誇大", "ipa": "/ɪɡˈzædʒəreɪt/", "trans": "exaggeration", "col": "exaggerate a point", "ex": "Stop exaggerating! It wasn't that big.", "pos": "v."},
    "exaggeration": {"def": "誇張、極大", "ipa": "/ɪɡˌzædʒəˈreɪʃn/", "trans": "exaggerate (動詞)", "col": "gross exaggeration", "ex": "It's no exaggeration to say that she's a genius.", "pos": "n."},
    "exam/examination": {"def": "考試、檢查", "ipa": "/ɪɡˈzæm/", "trans": "examine (動詞)", "col": "take an exam, pass/fail an exam", "ex": "I have a math exam tomorrow.", "pos": "n."},
    "examine": {"def": "檢查、調查、測試", "ipa": "/ɪɡˈzæmɪn/", "trans": "examiner, examination", "col": "examine a patient", "ex": "The doctor examined the patient carefully.", "pos": "v."},
    "example": {"def": "例子、榜樣、為...做榜樣", "ipa": "/ɪɡˈzɑːmpl/", "trans": "exemplary", "col": "for example, set an example", "ex": "Could you give me an example?", "pos": "n./v."},
    "exceed": {"def": "超過、勝過", "ipa": "/ɪkˈsiːd/", "trans": "exceeded", "col": "exceed the speed limit", "ex": "The cost of the project exceeded our expectations.", "pos": "v."},
    "excellence": {"def": "卓越、優秀", "ipa": "/ˈeksələns/", "trans": "excellent", "col": "center of excellence", "ex": "The school is famous for its academic excellence.", "pos": "n."},
    "excellent": {"def": "卓越的、極好的", "ipa": "/ˈeksələnt/", "trans": "excellence (名詞), excellently", "col": "excellent work", "ex": "She has an excellent memory.", "pos": "adj."},
    "except": {"def": "除了...之外、除...以外、要不是、不計、反對", "ipa": "/ɪkˈsept/", "trans": "exception, exceptional", "col": "except for", "ex": "Everyone was there except John.", "pos": "prep./conj./v."},
    "exception": {"def": "例外、異議", "ipa": "/ɪkˈsepʃn/", "trans": "except (介系詞), exceptional", "col": "with the exception of, make an exception", "ex": "There are always exceptions to the rule.", "pos": "n."},
    "exceptional": {"def": "優越的、例外的、特殊的", "ipa": "/ɪkˈsepʃənl/", "trans": "exception (名詞)", "col": "exceptional talent", "ex": "She is a student of exceptional ability.", "pos": "adj."},
    "excess": {"def": "超過、過剩、過量、超越規定的、額外的", "ipa": "/ɪkˈses/", "trans": "excessive", "col": "in excess of, excess baggage", "ex": "He drank to excess.", "pos": "n./adj."},
    "excessive": {"def": "過度的、極度的", "ipa": "/ɪkˈsesɪv/", "trans": "excess (名詞), excessively", "col": "excessive noise", "ex": "Excessive drinking is harmful to health.", "pos": "adj."},
    "exchange": {"def": "交換、交流、兌換、轉帳、交換、交易所、電話交換機", "ipa": "/ɪksˈtʃeɪndʒ/", "trans": "exchanger", "col": "stock exchange, exchange rate, in exchange for", "ex": "I gave him my book in exchange for his pen.", "pos": "v./n."},
    "exclaim": {"def": "呼喊、驚叫", "ipa": "/ɪksˈkleɪm/", "trans": "exclamation", "col": "exclaim with joy", "ex": "\"What a beautiful day!\" she exclaimed.", "pos": "v."},
    "exclamation": {"def": "感嘆、驚叫聲", "ipa": "/ˌekskləˈmeɪʃn/", "trans": "exclaim (動詞)", "col": "exclamation mark", "ex": "She let out an exclamation of surprise.", "pos": "n."},
    "exclude": {"def": "排除、不包括、驅逐", "ipa": "/ɪkˈskluːd/", "trans": "exclusion, exclusive", "col": "exclude from", "ex": "The price excludes the cost of delivery.", "pos": "v."},
}

with open("batch_l2_p13.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART13, f, ensure_ascii=False, indent=2)
