import json

# Level 2 Part 9: (Considerable - Cycle)
L2_PART9 = {
    "considerable": {"def": "相當大的、值得考慮的", "ipa": "/kənˈsɪdərəbl/", "trans": "considerably", "col": "considerable amount, considerable progress", "ex": "The project took a considerable amount of time.", "pos": "adj."},
    "considerate": {"def": "體貼的、考慮周到的", "ipa": "/kənˈsɪdərət/", "trans": "consideration, considerately", "col": "be considerate of", "ex": "It was very considerate of you to help.", "pos": "adj."},
    "consideration": {"def": "考慮、報酬、體貼", "ipa": "/kənˌsɪdəˈreɪʃn/", "trans": "consider (動詞)", "col": "take into consideration, out of consideration for", "ex": "After careful consideration, I've decided to go.", "pos": "n."},
    "consist": {"def": "組成、一致", "ipa": "/kənˈsɪst/", "trans": "consistent, consistency", "col": "consist of, consist in", "ex": "The team consists of ten members.", "pos": "v."},
    "constant": {"def": "經常的、不變的、常數、恆量", "ipa": "/ˈkɒnstənt/", "trans": "constantly, constancy", "col": "constant fear, constant speed", "ex": "He is in constant trouble with the police.", "pos": "adj./n."},
    "constantly": {"def": "不斷地、經常地", "ipa": "/ˈkɒnstəntli/", "trans": "constant (形容詞)", "col": "constantly changing", "ex": "Technology is constantly improving.", "pos": "adv."},
    "construct": {"def": "建造、構築、構造物", "ipa": "/kənˈstrʌkt/", "trans": "construction, constructive", "col": "construct a building", "ex": "The bridge was constructed in 1990.", "pos": "v./n."},
    "construction": {"def": "建造、施工、構造", "ipa": "/kənˈstrʌkʃn/", "trans": "construct (動詞)", "col": "under construction, construction site", "ex": "The library is currently under construction.", "pos": "n."},
    "consult": {"def": "諮詢、商量、查閱", "ipa": "/kənˈsʌlt/", "trans": "consultant, consultation", "col": "consult a doctor, consult a dictionary", "ex": "You should consult a travel agent.", "pos": "v."},
    "consultant": {"def": "顧問、諮詢者", "ipa": "/kənˈsʌltənt/", "trans": "consult (動詞)", "col": "management consultant", "ex": "She works as a marketing consultant.", "pos": "n."},
    "consume": {"def": "消耗、吃喝、燒毀", "ipa": "/kənˈsjuːm/", "trans": "consumer, consumption", "col": "consume energy", "ex": "The car consumes a lot of gas.", "pos": "v."},
    "consumer": {"def": "消費者", "ipa": "/kənˈsjuːmə/", "trans": "consume (動詞)", "col": "consumer rights, consumer protection", "ex": "Consumer spendings has increased lately.", "pos": "n."},
    "contact": {"def": "接觸、聯繫、聯繫、接觸的", "ipa": "/ˈkɒntækt/", "trans": "contactless", "col": "keep in contact, contact lenses", "ex": "I've lost contact with my old friends.", "pos": "n./v./adj."},
    "contain": {"def": "包含、容納、抑制", "ipa": "/kənˈteɪn/", "trans": "container", "col": "contain information", "ex": "This bottle contains two liters of water.", "pos": "v."},
    "container": {"def": "容器、貨櫃", "ipa": "/kənˈteɪnə/", "trans": "contain (動詞)", "col": "plastic container", "ex": "Store the food in an airtight container.", "pos": "n."},
    "contemporary": {"def": "當代的、同時期的、同代人", "ipa": "/kənˈtemprəri/", "trans": "contemporaneous", "col": "contemporary art, contemporary music", "ex": "He is a contemporary of Shakespeare.", "pos": "adj./n."},
    "content": {"def": "內容、目錄、滿足的、使滿足", "ipa": "/ˈkɒntent/ (n.) /kənˈtent/ (adj./v.)", "trans": "contentment", "col": "table of contents, be content with", "ex": "I am content with my current job.", "pos": "n./adj./v."},
    "contest": {"def": "比賽、爭奪、爭奪、對...提出質疑", "ipa": "/ˈkɒntest/ (n.) /kənˈtest/ (v.)", "trans": "contestant", "col": "beauty contest, singing contest", "ex": "He won first prize in the photography contest.", "pos": "n./v."},
    "continent": {"def": "大陸、洲", "ipa": "/ˈkɒntɪnənt/", "trans": "continental", "col": "the seven continents", "ex": "Asia is the largest continent.", "pos": "n."},
    "continual": {"def": "不斷的、頻繁的", "ipa": "/kənˈtɪnjuəl/", "trans": "continually", "col": "continual noise", "ex": "I'm tired of your continual complaints.", "pos": "adj."},
    "continue": {"def": "繼續、延伸", "ipa": "/kənˈtɪnjuː/", "trans": "continuation, continuous", "col": "continue to do, continue with", "ex": "Please continue with your work.", "pos": "v."},
    "continuous": {"def": "連續的、不斷的", "ipa": "/kənˈtɪnjuəs/", "trans": "continue (動詞), continuously", "col": "continuous improvement", "ex": "There was a continuous stream of traffic.", "pos": "adj."},
    "contract": {"def": "合約、契約、訂合約、縮小、感染（疾病）", "ipa": "/ˈkɒntrækt/ (n.) /kənˈtrækt/ (v.)", "trans": "contractor, contractual", "col": "sign a contract, breach of contract", "ex": "The two companies signed a ten-year contract.", "pos": "n./v."},
    "contrast": {"def": "對比、對照、對比", "ipa": "/ˈkɒntrɑːst/ (n.) /kənˈtrɑːst/ (v.)", "trans": "contrasting", "col": "in contrast to, by contrast", "ex": "The white lettering provides a sharp contrast against the blue background.", "pos": "n./v."},
    "contribute": {"def": "貢獻、投稿、捐助", "ipa": "/kənˈtrɪbjuːt/", "trans": "contribution, contributor", "col": "contribute to", "ex": "He contributed $100 to the charity.", "pos": "v."},
    "contribution": {"def": "貢獻、捐助物", "ipa": "/ˌkɒntrɪˈbjuːʃn/", "trans": "contribute (動詞)", "col": "make a contribution", "ex": "Everyone made a contribution to the fund.", "pos": "n."},
    "control": {"def": "控制、管理、操縱、控制權", "ipa": "/kənˈtrəʊl/", "trans": "controller", "col": "under control, out of control, remote control", "ex": "The fire was soon under control.", "pos": "v./n."},
    "convenience": {"def": "方便、便利設施", "ipa": "/kənˈviːniəns/", "trans": "convenient", "col": "for convenience, convenience store", "ex": "Please call me at your earliest convenience.", "pos": "n."},
    "convenient": {"def": "方便的、近便的", "ipa": "/kənˈviːniənt/", "trans": "convenience (名詞), conveniently", "col": "convenient time", "ex": "When would be a convenient time for us to meet?", "pos": "adj."},
    "convention": {"def": "大會、慣例、公約", "ipa": "/kənˈvenʃn/", "trans": "conventional", "col": "Geneva Convention, social conventions", "ex": "The Democratic Party convention was held in Chicago.", "pos": "n."},
    "conventional": {"def": "傳統的、慣例的、常規的", "ipa": "/kənˈvenʃənl/", "trans": "convention (名詞)", "col": "conventional methods, conventional weapons", "ex": "I'm looking for a conventional job.", "pos": "adj."},
    "conversation": {"def": "會話、談話", "ipa": "/ˌkɒnvəˈseɪʃn/", "trans": "conversational", "col": "phone conversation, have a conversation", "ex": "He had a long conversation with his teacher.", "pos": "n."},
    "convey": {"def": "傳達、運輸", "ipa": "/kənˈveɪ/", "trans": "conveyance, conveyor", "col": "convey a message", "ex": "How can I convey my feelings to her?", "pos": "v."},
    "convince": {"def": "說服、使信服", "ipa": "/kənˈvɪns/", "trans": "convinced, convincing", "col": "convince someone of", "ex": "I tried to convince him to change his mind.", "pos": "v."},
    "cook": {"def": "煮、烹調、廚師", "ipa": "/kʊk/", "trans": "cooker, cooking", "col": "cook for, pastry cook", "ex": "What's for dinner? I'm hungry.", "pos": "v./n."},
    "cookery": {"def": "烹飪術", "ipa": "/ˈkʊkəri/", "trans": "cook (動詞)", "col": "cookery book", "ex": "She is taking a cookery course.", "pos": "n."},
    "cookie": {"def": "餅乾、小甜餅", "ipa": "/ˈkʊki/", "trans": "cookies", "col": "fortune cookie, chocolate chip cookie", "ex": "He loves eating chocolate cookies.", "pos": "n."},
    "cool": {"def": "涼爽的、冷酷的、使變涼、冷靜、涼爽、冷靜地", "ipa": "/kuːl/", "trans": "coolly, coolness", "col": "keep cool, cool down", "ex": "The weather is starting to cool down.", "pos": "adj./v./n./adv."},
    "cooperate": {"def": "合作、協作", "ipa": "/kəʊˈɒpəreɪt/", "trans": "cooperation, cooperative", "col": "cooperate with", "ex": "Companies should cooperate with each other.", "pos": "v."},
    "cooperation": {"def": "合作、協力", "ipa": "/kəʊˌɒpəˈreɪʃn/", "trans": "cooperate (動詞)", "col": "international cooperation", "ex": "We appreciate your cooperation.", "pos": "n."},
    "cooperative": {"def": "合作的、樂意合作的、合作社", "ipa": "/kəʊˈɒpərətɪv/", "trans": "cooperate (動詞)", "col": "cooperative movement", "ex": "The neighbors were very cooperative.", "pos": "adj./n."},
    "cope": {"def": "應付、處理、長袍、斗篷", "ipa": "/kəʊp/", "trans": "coping", "col": "cope with", "ex": "It's difficult to cope with the stress of the job.", "pos": "v./n."},
    "copper": {"def": "銅、警察、銅製品", "ipa": "/ˈkɒpə/", "trans": "coppery", "col": "copper coin, copper wire", "ex": "Copper is a good conductor of heat.", "pos": "n."},
    "copy": {"def": "影印、模仿、副本、影印本、抄襲", "ipa": "/ˈkɒpi/", "trans": "copier, copying", "col": "copy machine, hard copy", "ex": "Can you make a copy of this for me?", "pos": "v./n."},
    "cord": {"def": "繩、索、電線、用繩捆綁", "ipa": "/kɔːd/", "trans": "cordless", "col": "vocal cords, spinal cord", "ex": "He tied the bundle with a cord.", "pos": "n./v."},
    "cork": {"def": "軟木、軟木瓶塞、塞住、抑制", "ipa": "/kɔːk/", "trans": "corkscrew", "col": "bottle cork", "ex": "He pulled the cork out of the bottle.", "pos": "n./v."},
    "corn": {"def": "玉米、穀物、雞眼", "ipa": "/kɔːn/", "trans": "corny", "col": "corn on the cob, sweet corn", "ex": "The farmers are harvesting the corn.", "pos": "n."},
    "corner": {"def": "角落、困境、壟斷、使困於角落、壟斷", "ipa": "/ˈkɔːnə/", "trans": "cornered", "col": "around the corner, street corner", "ex": "The shop is on the corner of the street.", "pos": "n./v."},
    "corporate": {"def": "公司的、法人的、共同的", "ipa": "/ˈkɔːpərət/", "trans": "corporation", "col": "corporate identity, corporate ladder", "ex": "He works in the corporate headquarters.", "pos": "adj."},
    "corporation": {"def": "公司、法人團體、市政當局", "ipa": "/ˌkɔːpəˈreɪʃn/", "trans": "corporate (形容詞)", "col": "multinational corporation, public corporation", "ex": "He is a vice president of a large corporation.", "pos": "n."},
    "correct": {"def": "正確的、恰當的、改正、糾正、正確地", "ipa": "/kəˈrekt/", "trans": "correction, correctly", "col": "correct answer, politically correct", "ex": "That is the correct answer.", "pos": "adj./v./adv."},
    "correction": {"def": "改正、修正、處罰", "ipa": "/kəˈrekʃn/", "trans": "correct (動詞)", "col": "make a correction", "ex": "He made several corrections to the manuscript.", "pos": "n."},
    "correspond": {"def": "符合、一致、通信、相當於", "ipa": "/ˌkɒrəˈspɒnd/", "trans": "correspondence, correspondent", "col": "correspond with, correspond to", "ex": "His actions do not correspond with his words.", "pos": "v."},
    "corridor": {"def": "走廊", "ipa": "/ˈkɒrɪdɔː/", "trans": "corridors", "col": "long corridor", "ex": "Walk down the corridor and it's the third door on the left.", "pos": "n."},
    "cost": {"def": "成本、代價、耗費、使付出代價", "ipa": "/kɒst/", "trans": "costly", "col": "at all costs, living costs", "ex": "How much does it cost?", "pos": "n./v."},
    "costly": {"def": "昂貴的、損失大的", "ipa": "/ˈkɒstli/", "trans": "cost (名詞)", "col": "costly mistake", "ex": "Buying that car was a costly mistake.", "pos": "adj."},
    "costume": {"def": "服裝、戲服、為...設計服裝", "ipa": "/ˈkɒstjuːm/", "trans": "costumer", "col": "swimming costume, historical costume", "ex": "She wore a traditional Chinese costume.", "pos": "n./v."},
    "cottage": {"def": "小屋、村舍", "ipa": "/ˈkɒtɪdʒ/", "trans": "cottages", "col": "country cottage", "ex": "They live in a small cottage in the country.", "pos": "n."},
    "cotton": {"def": "棉花、棉布、棉花的、理解", "ipa": "/ˈkɒtn/", "trans": "cottony", "col": "cotton candy, organic cotton", "ex": "This shirt is made of pure cotton.", "pos": "n./adj./v."},
    "couch": {"def": "沙發、床、躺下、表達", "ipa": "/kaʊtʃ/", "trans": "couch potato", "col": "lie on the couch", "ex": "He lay on the couch watching TV.", "pos": "n./v."},
    "cough": {"def": "咳嗽、咳嗽聲、咳出", "ipa": "/kɒf/", "trans": "coughing", "col": "bad cough, cough up", "ex": "He has a bad cough.", "pos": "v./n."},
    "council": {"def": "會議、委員會、理事會", "ipa": "/ˈkaʊnsl/", "trans": "councillor", "col": "city council, student council", "ex": "The city council is meeting tonight.", "pos": "n."},
    "count": {"def": "計數、計算、認為、伯爵", "ipa": "/kaʊnt/", "trans": "counter, countless", "col": "count on, count down", "ex": "He can count to ten in English.", "pos": "v./n."},
    "counter": {"def": "櫃檯、計數器、相反的、對抗、反駁、相反地", "ipa": "/ˈkaʊntə/", "trans": "counterpart", "col": "over the counter, service counter", "ex": "He put the money on the counter.", "pos": "n./adj./v./adv."},
    "countryside": {"def": "鄉間地帶、鄉下", "ipa": "/ˈkʌntrisaɪd/", "trans": "country (名詞)", "col": "beautiful countryside", "ex": "We went for a walk in the countryside.", "pos": "n."},
    "county": {"def": "郡、縣", "ipa": "/ˈkaʊnti/", "trans": "counties", "col": "county fair", "ex": "Which county did you grow up in?", "pos": "n."},
    "couple": {"def": "兩個、成雙、伴侶、連結、交配", "ipa": "/ˈkʌpl/", "trans": "coupling", "col": "married couple, a couple of", "ex": "They are a very happy couple.", "pos": "n./v."},
    "courage": {"def": "勇氣、膽量", "ipa": "/ˈkʌrɪdʒ/", "trans": "courageous", "col": "moral courage, pluck up courage", "ex": "It takes courage to speak the truth.", "pos": "n."},
    "courageous": {"def": "勇敢的、有膽量的", "ipa": "/kəˈreɪdʒəs/", "trans": "courage (名詞), courageously", "col": "courageous act", "ex": "It was a courageous decision to quit his job.", "pos": "adj."},
    "course": {"def": "課程、過程、路線、一道菜、奔流、追獵", "ipa": "/kɔːs/", "trans": "courses", "col": "of course, training course, main course", "ex": "I'm taking an English course.", "pos": "n./v."},
    "court": {"def": "法院、球場、庭院、奉承、招致", "ipa": "/kɔːt/", "trans": "courtyard", "col": "tennis court, supreme court", "ex": "The case was settled in court.", "pos": "n./v."},
    "courteous": {"def": "有禮貌的、謙恭的", "ipa": "/ˈkɜːtiəs/", "trans": "courtesy, courteously", "col": "courteous service", "ex": "The hotel staff were very courteous.", "pos": "adj."},
    "courtesy": {"def": "禮貌、好意、出自體貼的", "ipa": "/ˈkɜːtəsi/", "trans": "courteous (形容詞)", "col": "courtesy call, by courtesy of", "ex": "It's only common courtesy to say thank you.", "pos": "n./adj."},
    "cousin": {"def": "堂表兄弟姊妹、親戚", "ipa": "/ˈkʌzn/", "trans": "cousins", "col": "first cousin", "ex": "He is my favorite cousin.", "pos": "n."},
    "cover": {"def": "覆蓋、涵蓋、封面、覆蓋物、報導", "ipa": "/ˈkʌvə/", "trans": "coverage, covered", "col": "cover up, under cover", "ex": "Snow covered the ground.", "pos": "v./n."},
    "cow": {"def": "母牛、乳牛、恐嚇", "ipa": "/kaʊ/", "trans": "cowboy", "col": "cash cow", "ex": "The farmer is milking the cows.", "pos": "n./v."},
    "coward": {"def": "膽怯者、懦夫、膽怯的", "ipa": "/ˈkaʊəd/", "trans": "cowardly, cowardice", "col": "don't be a coward", "ex": "You are a coward for not helping him.", "pos": "n./adj."},
    "cowboy": {"def": "牛仔", "ipa": "/ˈkaʊbɔɪ/", "trans": "cowgirl", "col": "cowboy hat", "ex": "The cowboys were herding the cattle.", "pos": "n."},
    "crab": {"def": "螃蟹、捕蟹、抱怨", "ipa": "/kræb/", "trans": "crabby", "col": "crab meat", "ex": "We caught several crabs on the beach.", "pos": "n./v."},
    "crack": {"def": "裂縫、爆裂聲、使裂開、破解、龜裂的", "ipa": "/kræk/", "trans": "cracker", "col": "crack a joke, crack down on", "ex": "There's a crack in the wall.", "pos": "n./v./adj."},
    "cradle": {"def": "搖籃、發源地、搖、撫育", "ipa": "/ˈkreɪdl/", "trans": "cradled", "col": "from the cradle to the grave", "ex": "She rocked the baby in the cradle.", "pos": "n./v."},
    "craft": {"def": "工藝、手藝、小船、精心製作", "ipa": "/krɑːft/", "trans": "crafty, craftsman", "col": "handicraft, aircraft", "ex": "She is skilled in the craft of weaving.", "pos": "n./v."},
    "crash": {"def": "碰撞、墜落、當機、撞擊聲、碰撞、當機、緊急的", "ipa": "/kræʃ/", "trans": "crashed", "col": "car crash, computer crash", "ex": "The plane crashed into the sea.", "pos": "v./n./adj."},
    "crawl": {"def": "爬行、緩慢移動、爬行、腹泳", "ipa": "/krɔːl/", "trans": "crawler", "col": "crawl along", "ex": "The baby is starting to crawl.", "pos": "v./n."},
    "crayon": {"def": "蠟筆、用蠟筆畫", "ipa": "/ˈkreɪən/", "trans": "crayoned", "col": "color with crayons", "ex": "The child is drawing with crayons.", "pos": "n./v."},
    "cream": {"def": "奶油、乳霜、精華、奶油色的、把...搗成糊狀", "ipa": "/kriːm/", "trans": "creamy", "col": "whipped cream, face cream", "ex": "Do you like cream in your coffee?", "pos": "n./adj./v."},
    "create": {"def": "創造、引起", "ipa": "/kriˈeɪt/", "trans": "creation, creative, creator", "col": "create a problem", "ex": "The artist created a beautiful painting.", "pos": "v."},
    "creation": {"def": "創造、創作物", "ipa": "/kriˈeɪʃn/", "trans": "create (動詞)", "col": "artistic creation", "ex": "The gallery has many wonderful creations.", "pos": "n."},
    "creative": {"def": "有創造力的、啟發想像力的", "ipa": "/kriˈeɪtɪv/", "trans": "create (動詞), creativity", "col": "creative thinking, creative writing", "ex": "She is a very creative person.", "pos": "adj."},
    "creativity": {"def": "創造力、才思", "ipa": "/ˌkriːeɪˈtɪvəti/", "trans": "creative (形容詞)", "col": "artistic creativity", "ex": "The course aims to develop your creativity.", "pos": "n."},
    "creator": {"def": "創造者、創作者", "ipa": "/kriˈeɪtə/", "trans": "create (動詞)", "col": "creator of the show", "ex": "He is the creator of several popular apps.", "pos": "n."},
    "creature": {"def": "生物、動物", "ipa": "/ˈkriːtʃə/", "trans": "creatures", "col": "wild creatures, sea creature", "ex": "The ocean is full of strange creatures.", "pos": "n."},
    "credit": {"def": "信用、學分、榮譽、記帳、相信", "ipa": "/ˈkredɪt/", "trans": "creditor", "col": "credit card, buy on credit", "ex": "Do you accept credit cards?", "pos": "n./v."},
    "creep": {"def": "躡手躡腳地走、爬行、毛骨悚然感、討厭鬼", "ipa": "/kriːp/", "trans": "creepy, crept", "col": "creep up on", "ex": "She crept quietly up the stairs.", "pos": "v./n."},
    "crew": {"def": "工作人員、船員、全體人員、當船員", "ipa": "/kruː/", "trans": "crewed", "col": "cabin crew, film crew", "ex": "The ship's crew worked hard.", "pos": "n./v."},
    "cricket": {"def": "板球、蟋蟀", "ipa": "/ˈkrɪkɪt/", "trans": "cricketer", "col": "play cricket", "ex": "Cricket is popular in many countries.", "pos": "n."},
    "crime": {"def": "罪行、犯罪", "ipa": "/kraɪm/", "trans": "criminal", "col": "commit a crime, fight crime", "ex": "He was accused of a serious crime.", "pos": "n."},
    "criminal": {"def": "犯罪的、罪惡的、罪犯", "ipa": "/ˈkrɪmɪnl/", "trans": "crime (名詞)", "col": "criminal record, war criminal", "ex": "The police are searching for the criminal.", "pos": "adj./n."},
    "crisis": {"def": "危機、緊要關頭", "ipa": "/ˈkraɪsɪs/", "trans": "crises", "col": "financial crisis, energy crisis", "ex": "The country is facing a major economic crisis.", "pos": "n."},
    "crisp/crispy": {"def": "脆的、清爽的、薯片、使變脆", "ipa": "/krɪsp/ /ˈkrɪspi/", "trans": "crispness", "col": "crisp apples, potato crisps", "ex": "I like crisp bacon.", "pos": "adj./n./v."},
    "crisscross": {"def": "十字交叉的、交錯、交叉地", "ipa": "/ˈkrɪskrɒs/", "trans": "crisscrossing", "col": "crisscross pattern", "ex": "The streets crisscross the city.", "pos": "adj./v./adv."},
    "critic": {"def": "評論家、批評者", "ipa": "/ˈkrɪtɪk/", "trans": "critical, criticize", "col": "art critic, film critic", "ex": "He is a sharp critic of the government.", "pos": "n."},
    "critical": {"def": "批評的、關鍵的、危急的", "ipa": "/ˈkrɪtɪkl/", "trans": "criticize, criticism", "col": "critical thinking, critical condition", "ex": "Your support is critical to our success.", "pos": "adj."},
    "criticism": {"def": "批評、評論", "ipa": "/ˈkrɪtɪsɪzəm/", "trans": "criticize (動詞)", "col": "literary criticism, receive criticism", "ex": "The film received a lot of criticism.", "pos": "n."},
    "criticize": {"def": "批評、評論", "ipa": "/ˈkrɪtɪsaɪz/", "trans": "criticism, critic", "col": "criticize someone for", "ex": "She criticized him for being lazy.", "pos": "v."},
    "crop": {"def": "作物、收成、收穫、剪短", "ipa": "/krɒp/", "trans": "cropped", "col": "cash crop, bumper crop", "ex": "Farmers are harvesting the crops.", "pos": "n./v."},
    "cross": {"def": "越過、交叉、十字架、雜交、生氣的", "ipa": "/krɒs/", "trans": "crossing, crossbreed", "col": "cross the road, Red Cross", "ex": "Look both ways before you cross the street.", "pos": "v./n./adj."},
    "crossing": {"def": "十字路口、渡口、交叉", "ipa": "/ˈkrɒsɪŋ/", "trans": "cross (動詞)", "col": "pedestrian crossing, level crossing", "ex": "The ship is making its first Atlantic crossing.", "pos": "n."},
    "crouch": {"def": "蹲下、蜷縮", "ipa": "/kraʊtʃ/", "trans": "crouching", "col": "crouch down", "ex": "He crouched behind the bush.", "pos": "v./n."},
    "crow": {"def": "烏鴉、啼叫、啼叫、自誇", "ipa": "/krəʊ/", "trans": "crowing", "col": "crow's feet", "ex": "A crow flew over the field.", "pos": "n./v."},
    "crowd": {"def": "群眾、一夥、擠、擁擠", "ipa": "/kraʊd/", "trans": "crowded", "col": "a large crowd, follow the crowd", "ex": "A large crowd gathered outside the stadium.", "pos": "n./v."},
    "crowded": {"def": "擁擠的", "ipa": "/ˈkraʊdɪd/", "trans": "crowd (名詞)", "col": "crowded street, overcrowded", "ex": "The bus was very crowded.", "pos": "adj."},
    "crown": {"def": "皇冠、王權、頂端、為...戴冠、覆蓋、加冕", "ipa": "/kraʊn/", "trans": "crowned", "col": "royal crown", "ex": "The king wore a golden crown.", "pos": "n./v."},
    "crucial": {"def": "關鍵性的、至關重要的", "ipa": "/ˈkruːʃl/", "trans": "crucially", "col": "crucial factor", "ex": "Education is crucial for the future.", "pos": "adj."},
    "cruel": {"def": "殘忍的、殘酷的", "ipa": "/ˈkruːəl/", "trans": "cruelty, cruelly", "col": "cruel treatment", "ex": "It was a cruel thing to do.", "pos": "adj."},
    "cruelty": {"def": "殘忍、殘酷行為", "ipa": "/ˈkruːəlti/", "trans": "cruel (形容詞)", "col": "animal cruelty", "ex": "We must fight against animal cruelty.", "pos": "n."},
    "cruise": {"def": "郵輪旅遊、巡航、巡航", "ipa": "/kruːz/", "trans": "cruiser", "col": "luxury cruise, cruise ship", "ex": "They went on a Caribbean cruise.", "pos": "n./v."},
    "crumb": {"def": "麵包屑、碎裂、塗麵包屑於", "ipa": "/krʌm/", "trans": "crumby", "col": "bread crumbs", "ex": "She brushed the crumbs off the table.", "pos": "n./v."},
    "crunch": {"def": "嘎吱地咬、咀嚼聲、關鍵時刻、嘎吱響", "ipa": "/krʌntʃ/", "trans": "crunchy", "col": "crunch numbers", "ex": "He crunched on an apple.", "pos": "v./n."},
    "crush": {"def": "壓碎、迷戀、擁擠、壓壞、迷戀、擠入", "ipa": "/krʌʃ/", "trans": "crushing", "col": "schoolboy crush", "ex": "The crowd crushed the fence.", "pos": "v./n."},
    "crust": {"def": "餅皮、地殼、結皮", "ipa": "/krʌst/", "trans": "crusty", "col": "earth's crust, pizza crust", "ex": "I like the crust of the bread.", "pos": "n./v."},
    "crutch": {"def": "拐杖、支撐物", "ipa": "/krʌtʃ/", "trans": "crutches", "col": "walk on crutches", "ex": "He is walking on crutches.", "pos": "n."},
    "cry": {"def": "哭、叫喊、叫聲、大喊", "ipa": "/kraɪ/", "trans": "crying", "col": "cry over spilt milk, battle cry", "ex": "The baby is crying.", "pos": "v./n."},
    "crystal": {"def": "水晶、結晶、水晶製的、透明的", "ipa": "/ˈkrɪstl/", "trans": "crystalline, crystallize", "col": "crystal ball, crystal clear", "ex": "The glass is made of fine crystal.", "pos": "n./adj."},
    "cub": {"def": "幼獸（熊、獅等）、見習記者", "ipa": "/kʌb/", "trans": "cubs", "col": "bear cub, lion cub", "ex": "The lion cub was playing.", "pos": "n."},
    "cube": {"def": "立方體、立方、求...的立方", "ipa": "/kjuːb/", "trans": "cubic", "col": "ice cube, sugar cube", "ex": "Add two ice cubes to my drink.", "pos": "n./v."},
    "cucumber": {"def": "黃瓜", "ipa": "/ˈkjuːkʌmbə/", "trans": "cucumbers", "col": "cool as a cucumber", "ex": "I like cucumber in my salad.", "pos": "n."},
    "cue": {"def": "暗示、線索、撞球桿、給予暗示", "ipa": "/kjuː/", "trans": "cueing", "col": "take one's cue from", "ex": "That's your cue to start.", "pos": "n./v."},
    "cuff": {"def": "袖口、手銬、掌摑、給予拍打", "ipa": "/kʌf/", "trans": "cuffs", "col": "off the cuff, handcuffs", "ex": "He wore shiny gold cufflinks.", "pos": "n./v."},
    "cultivate": {"def": "耕作、培養、建立（友誼）", "ipa": "/ˈkʌltɪveɪt/", "trans": "cultivation, cultivator", "col": "cultivate soil, cultivate skills", "ex": "They've cultivated the land for centuries.", "pos": "v."},
    "culture": {"def": "文化、教養、培養", "ipa": "/ˈkʌltʃə/", "trans": "cultural", "col": "popular culture, local culture", "ex": "Studying history helps us understand our culture.", "pos": "n."},
    "cunning": {"def": "狡猾的、靈巧的、狡詐", "ipa": "/ˈkʌnɪŋ/", "trans": "cunningly", "col": "cunning plan", "ex": "He is as cunning as a fox.", "pos": "adj./n."},
    "cupboard": {"def": "食櫥、碗櫃", "ipa": "/ˈkʌbəd/", "trans": "cupboards", "col": "kitchen cupboard", "ex": "The cups are in the cupboard.", "pos": "n."},
    "cure": {"def": "治療、治癒、治療法、藥物", "ipa": "/kjʊə/", "trans": "curable, curative", "col": "cure for cancer, permanent cure", "ex": "The doctor can cure his illness.", "pos": "v./n."},
    "curiosity": {"def": "好奇心、古玩", "ipa": "/ˌkjʊəriˈɒsəti/", "trans": "curious (形容詞)", "col": "out of curiosity", "ex": "Children are full of curiosity.", "pos": "n."},
    "curious": {"def": "好奇的、古怪的", "ipa": "/ˈkjʊəriəs/", "trans": "curiosity (名詞), curiously", "col": "be curious about", "ex": "I am curious to know what happened.", "pos": "adj."},
    "curl": {"def": "捲曲、捲髮、螺旋、使捲曲", "ipa": "/kɜːl/", "trans": "curly", "col": "curl up", "ex": "She has natural curls in her hair.", "pos": "v./n."},
    "curly": {"def": "捲曲的", "ipa": "/ˈkɜːli/", "trans": "curl (動詞)", "col": "curly hair", "ex": "He has short curly hair.", "pos": "adj."},
    "currency": {"def": "貨幣、流傳", "ipa": "/ˈkʌrənsi/", "trans": "currencies", "col": "foreign currency, local currency", "ex": "Dollar is a strong currency.", "pos": "n."},
    "current": {"def": "現在的、流傳的、水流、氣流、趨勢", "ipa": "/ˈkʌrənt/", "trans": "currently", "col": "current events, ocean current, electric current", "ex": "What's the current temperature?", "pos": "adj./n."},
    "curse": {"def": "詛咒、咒罵、咒語", "ipa": "/kɜːs/", "trans": "cursing", "col": "break the curse", "ex": "She cursed him for his lack of sympathy.", "pos": "v./n."},
    "curtain": {"def": "窗簾、帷幕、遮蔽、給...裝上門簾", "ipa": "/ˈkɜːtn/", "trans": "curtaining", "col": "theater curtain, iron curtain", "ex": "She drew the curtains to shut out the light.", "pos": "n./v."},
    "curve": {"def": "曲線、彎曲處、使彎曲、呈曲線形", "ipa": "/kɜːv/", "trans": "curvy", "col": "learning curve", "ex": "The road has a sharp curve ahead.", "pos": "n./v."},
    "cushion": {"def": "墊子、緩衝、起緩衝作用、緩衝物", "ipa": "/ˈkʊʃn/", "trans": "cushioned", "col": "air cushion", "ex": "I like to sit on a soft cushion.", "pos": "n./v."},
    "custom": {"def": "習俗、海關、定製的", "ipa": "/ˈkʌstəm/", "trans": "customer, customize", "col": "social custom, local custom", "ex": "It's an old local custom.", "pos": "n./adj."},
    "customer": {"def": "顧客", "ipa": "/ˈkʌstəmə/", "trans": "custom (名詞)", "col": "regular customer, customer service", "ex": "The shop is full of customers today.", "pos": "n."},
    "customs": {"def": "海關、關稅", "ipa": "/ˈkʌstəmz/", "trans": "custom (名詞)", "col": "through customs", "ex": "We had to go through customs at the airport.", "pos": "n."},
    "cut": {"def": "切、割、削減、傷口、切下的份量", "ipa": "/kʌt/", "trans": "cutter, cutting", "col": "cut down, shortcut", "ex": "He cut the bread with a knife.", "pos": "v./n."},
    "cute": {"def": "可愛的、聰明的", "ipa": "/kjuːt/", "trans": "cuteness", "col": "very cute", "ex": "What a cute baby!", "pos": "adj."},
    "cycle": {"def": "週期、循環、腳踏車、騎腳踏車、使循環", "ipa": "/ˈsaɪkl/", "trans": "cyclist, cyclic", "col": "life cycle, business cycle", "ex": "The four seasons form a natural cycle.", "pos": "n./v."},
}

with open("batch_l2_p9.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART9, f, ensure_ascii=False, indent=2)
