import json

# Level 6 Part 11: (Archetype - Army)
L6_PART11 = {
    "archetype": {"def": "原型、典型的人 (或物)、(心)原型的人", "ipa": "/ˈɑːkitaɪp/", "trans": "archetypal", "col": "perfect archetype", "ex": "She is the archetype of a modern office worker.", "pos": "n."},
    "archipelago": {"def": "群島、列島 (單數)", "ipa": "/ˌɑːkɪˈpeləɡəʊ/", "trans": "archipelagos/archipelagoes (複數)", "col": "volcanic archipelago", "ex": "Indonesia is the largest archipelago in the world.", "pos": "n."},
    "architect": {"def": "建築師、設計者、締造者、建築師的、建築師般的、締造地 (建築師)", "ipa": "/ˈɑːkɪtekt/", "trans": "architecture, architectural", "col": "landscape architect, chief architect", "ex": "He is a famous landscape architect.", "pos": "n./adj./adv."},
    "architectural": {"def": "建築的、建築學的、符合建築法則的", "ipa": "/ˌɑːkɪˈtektʃərəl/", "trans": "architecture, architect", "col": "architectural style, architectural features", "ex": "The building has many interesting architectural features.", "pos": "adj."},
    "architecture": {"def": "建築學、建築風格、構造、(電腦)體系結構", "ipa": "/ˈɑːkɪtektʃə/", "trans": "architect, architectural", "col": "modern architecture, computer architecture", "ex": "She is studying modern architecture.", "pos": "n."},
    "archives": {"def": "檔案、檔案館、公文、存檔地 (檔案)", "ipa": "/ˈɑːkaɪvz/", "trans": "archivist", "col": "national archives, city archives", "ex": "The documents are stored in the national archives.", "pos": "n./adv."},
    "archivist": {"def": "檔案保管員", "ipa": "/ˈɑːkɪvɪst/", "trans": "archives (名詞/副詞)", "col": "senior archivist", "ex": "The senior archivist helped him with his research.", "pos": "n."},
    "Arctic": {"def": "北極的、極冷的、北極地帶、北極圈地", "ipa": "/ˈɑːktɪk/", "trans": "Antarctic", "col": "Arctic Circle, Arctic ocean", "ex": "The Arctic is melting rapidly due to climate change.", "pos": "adj./n./adv."},
    "ardent": {"def": "熱心的、熱情的、激烈的、燃燒的、熱心地 (熱心)", "ipa": "/ˈɑːdnt/", "trans": "ardently, ardour", "col": "ardent supporter, ardent lover", "ex": "He is an ardent supporter of the local football team.", "pos": "adj./adv."},
    "ardently": {"def": "熱心地、熱情地、激烈地", "ipa": "/ˈɑːdntli/", "trans": "ardent (形容詞/副詞), ardour", "col": "love ardently", "ex": "She loved him ardently.", "pos": "adv."},
    "ardour/ardor": {"def": "熱心、熱情、狂熱", "ipa": "/ˈɑːdə/", "trans": "ardent", "col": "patriotic ardour", "ex": "Their patriotic ardour was visible during the ceremony.", "pos": "n."},
    "arduous": {"def": "艱巨的、努力的、費力的", "ipa": "/ˈɑːdjuəs/", "trans": "challenging", "col": "arduous journey, arduous task", "ex": "The climb up the mountain was long and arduous.", "pos": "adj."},
    "are": {"def": "公畝 (面積單位)", "ipa": "/ɑː/", "trans": "ares", "col": "one are", "ex": "One are is equal to 100 square meters.", "pos": "n."},
    "area": {"def": "面積、區域、範圍、區域的、地方的、區域地 (區域)", "ipa": "/ˈeəriə/", "trans": "areas", "col": "surface area, storage area, urban area", "ex": "The playground is in a quiet area of the park.", "pos": "n./adj./adv."},
    "arena": {"def": "競技場、舞臺、活動場所", "ipa": "/əˈriːnə/", "trans": "arenas", "col": "sports arena, political arena, in the arena", "ex": "The soldiers entered the political arena.", "pos": "n."},
    "argue": {"def": "爭論、論證、說服、爭論的人 (或物)、爭論地 (爭論)", "ipa": "/ˈɑːɡjuː/", "trans": "argument, arguable", "col": "argue with, argue for, argue against", "ex": "They are always arguing about money.", "pos": "v./n./adv."},
    "arguable": {"def": "可論證的、可辨理的、有爭議的", "ipa": "/ˈɑːɡjuəbl/", "trans": "argue (動詞/名詞/副詞), argument", "col": "arguable point", "ex": "It's an arguable point whether the plan will work.", "pos": "adj."},
    "arguably": {"def": "可以這樣說、按理說、有爭議地", "ipa": "/ˈɑːɡjuəbli/", "trans": "arguable (形容詞), argue", "col": "arguably the best", "ex": "He is arguably the best player in the team.", "pos": "adv."},
    "argument": {"def": "爭論、論據、主張、情節、論證的人 (或物)、爭論地 (爭論)", "ipa": "/ˈɑːɡjumənt/", "trans": "argue (動詞/名詞/副詞), arguable", "col": "heated argument, powerful argument, logical argument", "ex": "I don't want to get into an argument with you.", "pos": "n./adv."},
    "argumentative": {"def": "好爭論的、爭辯的", "ipa": "/ˌɑːɡjuˈmentətɪv/", "trans": "argue", "col": "argumentative child", "ex": "He became very argumentative after a few drinks.", "pos": "adj."},
    "aria": {"def": "詠嘆調、曲調", "ipa": "/ˈɑːriə/", "trans": "arias", "col": "famous aria", "ex": "The soprano sang a beautiful aria from the opera.", "pos": "n."},
    "arid": {"def": "乾旱的、貧瘠的、無趣的", "ipa": "/ˈærɪd/", "trans": "aridity", "col": "arid climate, arid region", "ex": "The desert is known for its arid climate.", "pos": "adj."},
    "aridity": {"def": "乾旱、貧瘠、無趣", "ipa": "/əˈrɪdəti/", "trans": "arid (形容詞)", "col": "soil aridity", "ex": "The aridity of the soil made farming difficult.", "pos": "n."},
    "arise": {"def": "出現、生出、起身、起源於、出現的人 (或物)、出現地 (出現)", "ipa": "/əˈraɪz/", "trans": "arising", "col": "arise from, complications arise", "ex": "New problems arise every day.", "pos": "v./n./adv."},
    "aristocracy": {"def": "貴族、上層社會、貴族階層", "ipa": "/ˌærɪˈstɒkrəsi/", "trans": "aristocrat, aristocratic", "col": "landed aristocracy", "ex": "The aristocracy used to hold a lot of power.", "pos": "n."},
    "aristocrat": {"def": "貴族", "ipa": "/ˈærɪstəkræt/", "trans": "aristocracy, aristocratic", "col": "wealthy aristocrat", "ex": "He was born into a family of wealthy aristocrats.", "pos": "n."},
    "aristocratic": {"def": "貴族的、貴族派頭的、高尚的", "ipa": "/ˌærɪstəˈkrætɪk/", "trans": "aristocrat (名詞), aristocracy", "col": "aristocratic family", "ex": "She has very aristocratic features.", "pos": "adj."},
    "arithmetic": {"def": "算術、算法、算術的、算術地 (算術)", "ipa": "/əˈrɪθmətɪk/", "trans": "mathematics", "col": "mental arithmetic, basic arithmetic", "ex": "She is good at mental arithmetic.", "pos": "n./adj./adv."},
    "ark": {"def": "方舟、避難所、(聖經)約櫃", "ipa": "/ɑːk/", "trans": "Noah's Ark", "col": "ark of the covenant", "ex": "Noah built an ark to survive the flood.", "pos": "n."},
    "arm": {"def": "手臂、武器、袖手、武裝、備戰、袖口的、武器的、武裝地 (臂)", "ipa": "/ɑːm/", "trans": "armed, armour", "col": "arm in arm, up in arms, take up arms", "ex": "He broke his left arm.", "pos": "n./v./adj./adv."},
    "armada": {"def": "艦隊、機群、群、海軍力量", "ipa": "/ɑːˈmɑːdə/", "trans": "fleet", "col": "Spanish Armada", "ex": "The Spanish Armada was defeated by the English.", "pos": "n."},
    "armadillo": {"def": "犰狳", "ipa": "/ˌɑːməˈdɪləʊ/", "trans": "armadillos", "col": "nine-banded armadillo", "ex": "An armadillo has a hard shell to protect itself.", "pos": "n."},
    "armament": {"def": "軍備、武器、武裝、武裝力量", "ipa": "/ˈɑːməmənt/", "trans": "arms", "col": "nuclear armament", "ex": "The country is increasing its armament.", "pos": "n."},
    "armchair": {"def": "扶手椅、空論的、不切實際的、扶手椅的、室內的地 (扶手椅)", "ipa": "/ˈɑːmtʃeə/", "trans": "chair", "col": "comfortable armchair, armchair critic", "ex": "He sat in his favorite comfortable armchair.", "pos": "n./adj./adv."},
    "armed": {"def": "武裝的、有扶手的、帶武器的", "ipa": "/ɑːmd/", "trans": "arm (名詞/動詞/形容詞/副詞), armour", "col": "armed forces, armed robbery", "ex": "The soldiers are fully armed.", "pos": "adj."},
    "armistice": {"def": "停戰、休戰", "ipa": "/ˈɑːmɪstɪs/", "trans": "truce", "col": "sign an armistice", "ex": "The two countries signed an armistice to end the fighting.", "pos": "n."},
    "armlet": {"def": "臂環、臂章、支流、狹長海灣", "ipa": "/ˈɑːmlət/", "trans": "armband", "col": "gold armlet", "ex": "She was wearing a beautiful gold armlet.", "pos": "n."},
    "armor/armour": {"def": "裝甲、護甲、盔甲、為...穿甲、裝甲的、強力的、強力地 (裝甲)", "ipa": "/ˈɑːmə/", "trans": "armored", "col": "armoured vehicle, suit of armour", "ex": "The knight was wearing a suit of heavy armour.", "pos": "n./v./adj./adv."},
    "armored/armoured": {"def": "裝甲的、穿盔甲的、受保護的", "ipa": "/ˈɑːməd/", "trans": "armour (名詞/動詞/形容詞/副詞)", "col": "armoured tank, armoured car", "ex": "The money was transported in an armoured car.", "pos": "adj."},
    "armory/armoury": {"def": "軍械庫、兵工廠、紋章", "ipa": "/ˈɑːməri/", "trans": "arsenal", "col": "national armoury", "ex": "The rebels attacked the city's armoury.", "pos": "n."},
    "armpit": {"def": "腋窩、腋下", "ipa": "/ˈɑːmpɪt/", "trans": "axilla", "col": "hairy armpit", "ex": "He had a thermometer under his armpit.", "pos": "n."},
    "arms": {"def": "武器、軍火、紋章、手臂 (複數)、武器地 (武器)", "ipa": "/ɑːmz/", "trans": "arm (名詞/動詞/形容詞/副詞)", "col": "take up arms, arms race, call to arms", "ex": "The illegal trade in arms is a major problem.", "pos": "n./adv."},
    "army": {"def": "軍隊、陸軍、大群、軍事地、武裝地 (軍隊)", "ipa": "/ˈɑːmi/", "trans": "armies", "col": "join the army, regular army, salvation army", "ex": "He decided to join the army after finishing school.", "pos": "n./adv."},
}