import json

# Level 6 Part 50: (Brewhouse - Brigand)
L6_PART50 = {
    "brewhouse": {"def": "釀酒廠、煮製室 (單數)", "ipa": "/ˈbruːhaʊs/", "trans": "brewery", "col": "traditional brewhouse", "ex": "The traditional brewhouse is still in operation today.", "pos": "n."},
    "brewing": {"def": "釀造、醵釀、釀造的人 (或物) (釀)", "ipa": "/ˈbruːɪŋ/", "trans": "brew (動詞/名詞/副詞)", "col": "brewing industry, storm brewing", "ex": "He has a keen interest in the science of brewing.", "pos": "n./adv."},
    "bribe": {"def": "賄賂、收買、賄賂物、收買的人、賄賂地 (賄)", "ipa": "/braɪb/", "trans": "bribery, bribing", "col": "take a bribe, offer a bribe, bribe someone to do something", "ex": "He was accused of trying to bribe a public official.", "pos": "v./n./adv."},
    "briber": {"def": "行賄者", "ipa": "/ˈbraɪbə/", "trans": "bribe (名詞/動詞/副詞)", "col": "active briber", "ex": "The police caught the briber in the act.", "pos": "n."},
    "bribery": {"def": "賄賂、受賄行為", "ipa": "/ˈbraɪbəri/", "trans": "bribe (名詞/動詞/副詞)", "col": "corruption and bribery", "ex": "Bribery is a serious crime that undermines democracy.", "pos": "n."},
    "bribing": {"def": "行賄、收買的人 (或物) (賄)", "ipa": "/ˈbraɪbɪŋ/", "trans": "bribe (名詞/動詞/副詞)", "col": "systematic bribing", "ex": "The company was involved in a systematic bribing scandal.", "pos": "n./adv."},
    "brick": {"def": "磚、磚塊、(口)好心人、用磚圍、磚塊的人物、磚塊地 (磚)", "ipa": "/brɪk/", "trans": "bricks, brickwork", "col": "brick wall, brick by brick, drop a brick (失言), hit a brick wall", "ex": "The house is built of red brick.", "pos": "n./v./adj./adv."},
    "brickbat": {"def": "碎磚、辱罵的人 (或物) (罵)", "ipa": "/ˈbrɪkbæt/", "trans": "insult", "col": "verbal brickbat", "ex": "The politician was pelted with verbal brickbats from the crowd.", "pos": "n./adv."},
    "bricklayer": {"def": "砌磚工", "ipa": "/ˈbrɪkleɪə/", "trans": "mason", "col": "skilled bricklayer", "ex": "The bricklayer is building a garden wall.", "pos": "n."},
    "bricklaying": {"def": "砌磚、砌磚的人 (或物) (砌)", "ipa": "/ˈbrɪkleɪɪŋ/", "trans": "bricklayer", "col": "apprentice bricklaying", "ex": "Bricklaying requires a lot of physical strength and skill.", "pos": "n./adv."},
    "brickwork": {"def": "磚結構、砌磚部分 (單數)", "ipa": "/ˈbrɪkwɜːk/", "trans": "masonry", "col": "decorative brickwork", "ex": "The decorative brickwork on the old church is beautiful.", "pos": "n."},
    "bridal": {"def": "婚禮的、新娘的、婚禮的人物、婚禮地 (婚)", "ipa": "/ˈbraɪdl/", "trans": "bride", "col": "bridal gown, bridal suite, bridal shower", "ex": "She looked beautiful in her white bridal gown.", "pos": "adj./n./adv."},
    "bride": {"def": "新娘、(俚)女人的人物、新娘地 (新娘)", "ipa": "/braɪd/", "trans": "brides, bridal", "col": "blushing bride, bride and groom", "ex": "The bride walked down the aisle with her father.", "pos": "n./adv."},
    "bridegroom": {"def": "新郎 (單數)", "ipa": "/ˈbraɪdɡruːm/", "trans": "groom", "col": "nervous bridegroom", "ex": "The bridegroom was waiting nervously at the altar.", "pos": "n."},
    "bridesmaid": {"def": "伴娘、女儐相 (單數)", "ipa": "/ˈbraɪdzmeɪd/", "trans": "bridesmaids (複數)", "col": "chief bridesmaid", "ex": "She was chosen to be the chief bridesmaid for her sister.", "pos": "n."},
    "bridge": {"def": "橋、橋梁、鼻樑、天橋、架橋、架橋的人物、架橋地 (橋)", "ipa": "/brɪdʒ/", "trans": "bridges, bridging", "col": "suspension bridge, burn one's bridges (背水一戰), bridge the gap, bridge of the nose", "ex": "We walked across the bridge to the other side of the river.", "pos": "n./v./adv."},
    "bridgehead": {"def": "橋頭堡、據點 (單數)", "ipa": "/ˈbrɪdʒhed/", "trans": "foothold", "col": "strategic bridgehead", "ex": "The army established a strategic bridgehead on the enemy's shore.", "pos": "n."},
    "bridging": {"def": "架橋、跨越、跨越的人 (或物) (跨)", "ipa": "/ˈbrɪdʒɪŋ/", "trans": "bridge (名詞/動詞/副詞)", "col": "bridging loan (過渡性貸款)", "ex": "The company needed a bridging loan to cover expenses.", "pos": "n./adv."},
    "bridle": {"def": "馬勒、韁繩、約束、發怒的人、約束地 (勒)", "ipa": "/ˈbraɪdl/", "trans": "bridling", "col": "bridle path (馬道), bridle at (對...感到憤慨)", "ex": "He put the bridle on the horse.", "pos": "n./v./adv."},
    "bridling": {"def": "約束、發怒的人 (或物) (怒)", "ipa": "/ˈbraɪdlɪŋ/", "trans": "bridle (名詞/動詞/副詞)", "col": "bridling anger", "ex": "She was bridling with anger at the insult.", "pos": "n./adv."},
    "brief": {"def": "簡短的、短暫的、摘要、簡報、摘要的人 (或物)、簡短地 (簡)", "ipa": "/briːf/", "trans": "briefly, brevity", "col": "brief summary, brief meeting, in brief (總之), brief encounter", "ex": "He gave a brief summary of the report.", "pos": "adj./n./v./adv."},
    "briefcase": {"def": "公事包 (單數)", "ipa": "/ˈbriːfkeɪs/", "trans": "briefcases (複數)", "col": "leather briefcase", "ex": "He carried his documents in a leather briefcase.", "pos": "n."},
    "briefing": {"def": "簡報、指示、簡報的人物 (報)", "ipa": "/ˈbriːfɪŋ/", "trans": "brief (名詞/動詞/副詞)", "col": "press briefing, daily briefing", "ex": "The general gave a daily briefing to the reporters.", "pos": "n./adv."},
    "briefly": {"def": "簡短地、暫時地、概括地", "ipa": "/ˈbriːfli/", "trans": "brief (形容詞/名詞/動詞/副詞)", "col": "stated briefly", "ex": "She briefly explained the situation to the team.", "pos": "adv."},
    "briefs": {"def": "(複)內褲、短內褲 (複數)", "ipa": "/briːfs/", "trans": "brief", "col": "cotton briefs", "ex": "He bought a new pack of cotton briefs.", "pos": "n."},
    "brier/briar": {"def": "野薔薇、荊棘、野薔薇的人 (或物)、野薔薇地 (薔薇)", "ipa": "/ˈbraɪə/", "trans": "thicket", "col": "brier patch", "ex": "The rabbit disappeared into the brier patch.", "pos": "n./adv."},
    "brig": {"def": "雙桅方帆船、(軍)監禁室、船上的人物、監禁地 (監)", "ipa": "/brɪɡ/", "trans": "brigs", "col": "naval brig", "ex": "The rebellious sailors were locked in the naval brig.", "pos": "n./adv."},
    "brigade": {"def": "旅、隊、編隊、编隊的人、编隊地 (旅)", "ipa": "/brɪˈɡeɪd/", "trans": "brigades", "col": "fire brigade, infantry brigade, cleaning brigade", "ex": "The local fire brigade arrived within minutes.", "pos": "n./v./adv."},
    "brigade-major": {"def": "旅參謀長", "ipa": "/brɪˈɡeɪd ˈmeɪdʒə/", "trans": "officer", "col": "acting brigade-major", "ex": "The brigade-major issued orders to the column.", "pos": "n."},
    "brigadier": {"def": "准將 (單數)", "ipa": "/ˌbrɪɡəˈdɪə/", "trans": "general", "col": "retired brigadier", "ex": "The retired brigadier wrote his memoirs about the war.", "pos": "n."},
    "brigand": {"def": "土匪、強盜 (單數)", "ipa": "/ˈbrɪɡənd/", "trans": "brigands (複數)", "col": "mountain brigand", "ex": "Mountain brigands often attacked travelers on the high pass.", "pos": "n."},
}