import json

# Level 6 Part 31: (Beside - Bevy)
L6_PART31 = {
    "beside": {"def": "在...旁邊、與...相比、在旁邊地 (旁)", "ipa": "/bɪˈsaɪd/", "trans": "next to", "col": "beside oneself (失常), sit beside, beside the point (無關緊要)", "ex": "She sat beside him on the sofa.", "pos": "prep./adv./n."},
    "besides": {"def": "除...之外、此外、而且地 (此外)", "ipa": "/bɪˈsaɪdz/", "trans": "in addition to", "col": "besides that", "ex": "Besides the violin, she plays the cello.", "pos": "prep./adv./n."},
    "besiege": {"def": "圍攻、包圍、煩擾、圍繞的人 (或物)、圍繞地 (圍)", "ipa": "/bɪˈsiːdʒ/", "trans": "besieged", "col": "besiege a city, besieged by fans", "ex": "The army besieged the city for two months.", "pos": "v./n./adv."},
    "besmear": {"def": "塗抹、弄髒、污衊", "ipa": "/bɪˈsmɪə/", "trans": "smear", "col": "besmeared with", "ex": "The wall was besmeared with blood.", "pos": "v."},
    "besmirch": {"def": "弄髒、污衊、毀損(名譽)", "ipa": "/bɪˈsmɜːtʃ/", "trans": "taint", "col": "besmirch reputation", "ex": "I don't want to besmirch his reputation.", "pos": "v."},
    "besought": {"def": "(beseech的過去式及過去分詞)、哀求", "ipa": "/bɪˈsɔːt/", "trans": "beseech", "col": "besought help", "ex": "They besought help from the local government.", "pos": "v."},
    "bespangle": {"def": "點綴、裝飾", "ipa": "/bɪˈspæŋɡl/", "trans": "adorn", "col": "bespangled with stars", "ex": "The sky was bespangled with stars.", "pos": "v."},
    "bespatter": {"def": "濺污、誹謗", "ipa": "/bɪˈspætə/", "trans": "splatter", "col": "bespattered with mud", "ex": "His clothes were bespattered with mud.", "pos": "v."},
    "bespeak": {"def": "顯示、預約、證明", "ipa": "/bɪˈspiːk/", "trans": "indicate", "col": "bespeak talent", "ex": "His manner bespeaks a good education.", "pos": "v."},
    "bespectacled": {"def": "戴眼鏡的", "ipa": "/bɪˈspektəkld/", "trans": "wearing glasses", "col": "bespectacled student", "ex": "A bespectacled student was studying in the library.", "pos": "adj."},
    "bespoke": {"def": "訂製的、(bespeak的過去式)、訂製地 (訂製)", "ipa": "/bɪˈspəʊk/", "trans": "tailor-made", "col": "bespoke suit", "ex": "He wore a bespoke suit to the wedding.", "pos": "adj./v./adv."},
    "bespread": {"def": "舖滿、散布", "ipa": "/bɪˈspred/", "trans": "spread over", "col": "bespread with", "ex": "The table was bespread with food.", "pos": "v."},
    "besprinkle": {"def": "灑、灑水於", "ipa": "/bɪˈsprɪŋkl/", "trans": "sprinkle", "col": "besprinkled with water", "ex": "The flowers were besprinkled with water.", "pos": "v."},
    "best": {"def": "最好的、最高地、最合適地、最好的人、最好的事物、最、打敗 (最好的)", "ipa": "/best/", "trans": "better, worst", "col": "all the best, best seller, at best, make the best of", "ex": "It's the best movie I've ever seen.", "pos": "adj./adv./n./v."},
    "bestial": {"def": "野獸般的、殘忍的、獸性的", "ipa": "/ˈbestiəl/", "trans": "savage", "col": "bestial cruelty", "ex": "He was shocked by the bestial cruelty of the soldiers.", "pos": "adj."},
    "bestiality": {"def": "獸性、殘忍、人獸交", "ipa": "/ˌbestiˈæləti/", "trans": "savagery", "col": "human bestiality", "ex": "The movie explores the theme of human bestiality.", "pos": "n."},
    "bestialize": {"def": "使野獸化、使殘忍", "ipa": "/ˈbestiəlaɪz/", "trans": "brutalize", "col": "bestialize people", "ex": "War can bestialize even the kindest people.", "pos": "v."},
    "bestir": {"def": "使努力、使活躍 (常用於反身)", "ipa": "/bɪˈstɜː/", "trans": "rouse", "col": "bestir oneself", "ex": "You must bestir yourself if you want to finish on time.", "pos": "v."},
    "bestow": {"def": "授予、贈予、使用、安放、授予的人 (或物)、授予地 (授)", "ipa": "/bɪˈstəʊ/", "trans": "bestowal", "col": "bestow on, bestow honor", "ex": "The prize was bestowed on the scientist for his discovery.", "pos": "v./n./adv."},
    "bestowal": {"def": "授予、贈予、遺贈", "ipa": "/bɪˈstəʊəl/", "trans": "bestow (動詞/名詞/副詞)", "col": "bestowal of gifts", "ex": "The ancient custom involved the bestowal of gifts.", "pos": "n."},
    "bestride": {"def": "跨過、騎在...上、跨越地、跨著的人 (或物) (跨)", "ipa": "/bɪˈstraɪd/", "trans": "stride across", "col": "bestride a horse", "ex": "He bestrode the horse with great skill.", "pos": "v./adv./n."},
    "bestseller/best seller": {"def": "暢銷書、銷路最好的人 (或物) (單數)", "ipa": "/ˌbestˈselə/", "trans": "bestsellers (複數)", "col": "national bestseller", "ex": "His new novel is already a national bestseller.", "pos": "n."},
    "best-selling": {"def": "最暢銷的", "ipa": "/ˌbestˈselɪŋ/", "trans": "bestseller", "col": "best-selling novel", "ex": "She is a best-selling author.", "pos": "adj."},
    "bet": {"def": "打賭、賭金、敢斷言、打賭的人 (或物)、打賭地 (賭)", "ipa": "/bet/", "trans": "bets", "col": "make a bet, bet on, you bet (當然/沒錯)", "ex": "I bet you $10 that I can win.", "pos": "v./n./adv."},
    "beta": {"def": "貝塔 (希臘字母第二位)、(電腦)測試版的、(美俚)平庸的人、測試的人 (或物) (測試)", "ipa": "/ˈbiːtə/", "trans": "alphas", "col": "beta version, beta testing, beta ray", "ex": "The software is currently in beta version.", "pos": "n./adj./adv."},
    "betake": {"def": "使前往、使致身於 (常用於反身)", "ipa": "/bɪˈteɪk/", "trans": "go", "col": "betake oneself to", "ex": "She betook herself to the library to study.", "pos": "v."},
    "bethink": {"def": "想起、考慮、(古)記起 (常用於反身)", "ipa": "/bɪˈθɪŋk/", "trans": "remember", "col": "bethink oneself of", "ex": "He bethought himself of an old promise.", "pos": "v."},
    "betide": {"def": "發生、降臨", "ipa": "/bɪˈtaɪd/", "trans": "befall", "col": "woe betide (禍哉...)", "ex": "Woe betide anyone who touches my things!", "pos": "v."},
    "betimes": {"def": "及時地、提早地、(古)有時地 (早)", "ipa": "/bɪˈtaɪmz/", "trans": "early", "col": "rise betimes", "ex": "He used to rise betimes in the morning.", "pos": "adv."},
    "betray": {"def": "背叛、出賣、洩露、辜負、洩露的人物、洩露地 (洩)", "ipa": "/bɪˈtreɪ/", "trans": "betrayal", "col": "betray a secret, betray trust, betray one's country", "ex": "He betrayed his best friend.", "pos": "v./n./adv."},
    "betrayal": {"def": "背叛、出賣、洩露", "ipa": "/bɪˈtreɪəl/", "trans": "betray (動詞/名詞/副詞)", "col": "act of betrayal", "ex": "Her actions were seen as a deep betrayal.", "pos": "n."},
    "betrayer": {"def": "背叛者、出賣者、通敵者", "ipa": "/bɪˈtreɪə/", "trans": "betray (動詞/名詞/副詞), betrayal", "col": "known betrayer", "ex": "He was labeled as a known betrayer of the cause.", "pos": "n."},
    "betroth": {"def": "許配、訂婚、約定地 (約定)", "ipa": "/bɪˈtrəʊð/", "trans": "betrothal", "col": "betrothed to", "ex": "She was betrothed to a wealthy merchant.", "pos": "v./adv."},
    "betrothal": {"def": "訂婚、婚約", "ipa": "/bɪˈtrəʊðəl/", "trans": "betroth (動詞/副詞)", "col": "formal betrothal", "ex": "The formal betrothal took place last week.", "pos": "n."},
    "betrothed": {"def": "已訂婚的、未婚妻、未婚夫", "ipa": "/bɪˈtrəʊðd/", "trans": "betroth (動詞/副詞), betrothal", "col": "his betrothed", "ex": "He introduced us to his betrothed.", "pos": "adj./n."},
    "better": {"def": "較好的、更好地、更好的人 (或物)、改善、打敗、改善地 (更好)", "ipa": "/ˈbetə/", "trans": "best, worse", "col": "better late than never, had better, get the better of, think better of", "ex": "I'm feeling much better today.", "pos": "adj./adv./n./v."},
    "betterment": {"def": "改善、改進、進步", "ipa": "/ˈbetəmənt/", "trans": "better (形容詞/副詞/名詞/動詞)", "col": "social betterment", "ex": "The project aim at the social betterment of the community.", "pos": "n."},
    "between": {"def": "在...之間、位中間的、合力地 (中間)", "ipa": "/bɪˈtwiːn/", "trans": "among", "col": "between you and me (我們之間), in between, between jobs", "ex": "The town is between the mountains and the sea.", "pos": "prep./adv./adj."},
    "betwixt": {"def": "在...之間、中間地 (古用語) (中間)", "ipa": "/bɪˈtwɪkst/", "trans": "between", "col": "betwixt and between (半中間地)", "ex": "She felt betwixt and between after the decision.", "pos": "prep./adv."},
    "bevel": {"def": "斜角、斜邊、使成斜角、傾斜的人物、傾斜地 (斜)", "ipa": "/ˈbevl/", "trans": "beveling", "col": "beveled edge", "ex": "The mirror has a beveled edge.", "pos": "n./v./adv."},
    "beverage": {"def": "飲料、飲用物、飲用地的 (單數)", "ipa": "/ˈbevərɪdʒ/", "trans": "beverages (複數)", "col": "alcoholic beverage, soft beverage", "ex": "Coffee and tea are popular beverages.", "pos": "n./adv."},
    "bevy": {"def": "一群、一批 (多指女性或鳥類) (單數)", "ipa": "/ˈbevi/", "trans": "bevies (複數)", "col": "bevy of beauties, bevy of quails", "ex": "A bevy of beautiful girls entered the room.", "pos": "n."},
}