import json

# Level 6 Part 36: (Bitter - Blade)
L6_PART36 = {
    "bitter": {"def": "苦的、痛苦的、劇烈的、嚴寒的、苦味、痛苦地 (苦)", "ipa": "/ˈbɪtə/", "trans": "bitterly, bitterness", "col": "bitter taste, bitter enemy, bitter cold, to the bitter end", "ex": "The medicine has a bitter taste.", "pos": "adj./n./adv."},
    "bitterly": {"def": "苦澀地、慘痛地、嚴寒地", "ipa": "/ˈbɪtəli/", "trans": "bitter (形容詞/名詞/副詞)", "col": "cry bitterly, bitterly cold", "ex": "She wept bitterly after hearing the news.", "pos": "adv."},
    "bitterness": {"def": "苦味、痛苦、怨恨", "ipa": "/ˈbɪtənəs/", "trans": "bitter (形容詞/名詞/副詞/代名詞)", "col": "full of bitterness", "ex": "His heart is full of bitterness towards his old boss.", "pos": "n."},
    "bitters": {"def": "苦味酒、苦藥 (複數)", "ipa": "/ˈbɪtəz/", "trans": "liquor", "col": "angostura bitters", "ex": "Angostura bitters is often used in cocktails.", "pos": "n."},
    "bittersweet": {"def": "苦樂參半的、苦甜的、苦甜的人 (或物)、苦甜地 (苦甜)", "ipa": "/ˌbɪtəˈswiːt/", "trans": "bittersweets", "col": "bittersweet memories", "ex": "They have many bittersweet memories of their time together.", "pos": "adj./n./adv."},
    "bitty": {"def": "碎片組成的、零碎的、(俚)細小的", "ipa": "/ˈbɪti/", "trans": "fragmentary", "col": "bits and bitty", "ex": "The report was a bit bitty and hard to follow.", "pos": "adj."},
    "bitumen": {"def": "瀝青、柏油", "ipa": "/ˈbɪtʃəmən/", "trans": "asphalt", "col": "crude bitumen", "ex": "Bitumen is used for road surfacing.", "pos": "n."},
    "bivalve": {"def": "雙殼綱、雙殼動物、雙殼的、雙殼的人 (或物)、雙殼地 (雙殼)", "ipa": "/ˈbaɪvælv/", "trans": "mollusk", "col": "bivalve shellfish", "ex": "Clams and oysters are examples of bivalve shellfish.", "pos": "n./adj./adv."},
    "bivouac": {"def": "露營、露宿、露天營地、露營的人 (或物)、露營地 (營)", "ipa": "/ˈbɪvuæk/", "trans": "bivouacs", "col": "mountain bivouac", "ex": "The group set up a bivouac near the summit.", "pos": "n./v./adv."},
    "bi-weekly": {"def": "兩週一次的、一週兩次的、兩週一次地 (兩週)", "ipa": "/baɪˈwiːkli/", "trans": "fortnightly", "col": "bi-weekly meeting", "ex": "The team holds a bi-weekly meeting to discuss progress.", "pos": "adj./adv."},
    "bizarre": {"def": "奇異的、異想天開的、怪異地 (怪)", "ipa": "/bɪˈzɑː/", "trans": "strange", "col": "bizarre behavior, bizarre situation", "ex": "She wore a bizarre outfit to the party.", "pos": "adj./adv."},
    "bizarreness": {"def": "奇特、怪異", "ipa": "/bɪˈzɑːnəs/", "trans": "bizarre (形容詞/副詞)", "col": "sheer bizarreness", "ex": "The sheer bizarreness of the event took everyone by surprise.", "pos": "n."},
    "blab": {"def": "洩漏、胡扯、多嘴的人、多嘴地 (洩)", "ipa": "/blæb/", "trans": "blabber", "col": "blab a secret", "ex": "Don't blab everything I told you!", "pos": "v./n./adv."},
    "blabber": {"def": "胡扯、多嘴、胡扯的人、多嘴地 (多嘴)", "ipa": "/ˈblæbə/", "trans": "blab (動詞/名詞/副詞)", "col": "stop blabbering", "ex": "He keeps blabbering about his new car.", "pos": "v./n./adv."},
    "blabbermouth": {"def": "(俚)多嘴的人、大嘴巴 (單數)", "ipa": "/ˈblæbəmaʊθ/", "trans": "blabbermouths (複數)", "col": "office blabbermouth", "ex": "Everyone knows she is the office blabbermouth.", "pos": "n."},
    "black": {"def": "黑色的、黑暗的、邪惡的、變黑、黑色、黑人、黑地 (黑)", "ipa": "/blæk/", "trans": "blackness, blacken", "col": "black market, black box, black hole, black and white (白紙黑字)", "ex": "He wore a black suit.", "pos": "adj./n./v./adv."},
    "blackberry": {"def": "黑莓 (單數)", "ipa": "/ˈblækbəri/", "trans": "blackberries (複數)", "col": "wild blackberry", "ex": "We gathered wild blackberries in the fields.", "pos": "n."},
    "blackbird": {"def": "黑鶇、黑鳥 (單數)", "ipa": "/ˈblækbɜːd/", "trans": "blackbirds (複數)", "col": "singing blackbird", "ex": "The singing blackbird woke me up this morning.", "pos": "n."},
    "blackboard": {"def": "黑板 (單數)", "ipa": "/ˈblækbɔːd/", "trans": "blackboards (複數)", "col": "write on the blackboard", "ex": "The teacher wrote the homework on the blackboard.", "pos": "n."},
    "blacken": {"def": "變黑、弄黑、誹謗、變黑的人物、變黑地 (黑)", "ipa": "/ˈblækn/", "trans": "black", "col": "blacken one's name", "ex": "The smoke blackened the walls.", "pos": "v./n./adv."},
    "blackhead": {"def": "黑頭粉刺 (單數)", "ipa": "/ˈblækhed/", "trans": "blackheads (複數)", "col": "stubborn blackhead", "ex": "He used a special cream to remove the stubborn blackhead.", "pos": "n."},
    "blacking": {"def": "擦亮劑、弄黑 (黑)", "ipa": "/ˈblækɪŋ/", "trans": "blacken (動詞/名詞/副詞)", "col": "shoe blacking", "ex": "He applied shoe blacking to his boots.", "pos": "n./adv."},
    "blackjack": {"def": "(遊戲)二十一點、橡皮警棍、海盜旗、投射物、警棍地 (二十一點)", "ipa": "/ˈblækdʒæk/", "trans": "blackjacks", "col": "play blackjack, hit with a blackjack", "ex": "He lost $50 playing blackjack.", "pos": "n./v./adv."},
    "blacklist": {"def": "黑名單、把...列入黑名單、名單上的物、列入地 (黑名單)", "ipa": "/ˈblæklɪst/", "trans": "blacklists", "col": "on the blacklist", "ex": "His name was put on the company's blacklist.", "pos": "n./v./adv."},
    "blackmail": {"def": "敲詐、勒索、勒索的人 (或物)、勒索地 (勒索)", "ipa": "/ˈblækmeɪl/", "trans": "blackmailing", "col": "emotional blackmail", "ex": "He was arrested for attempting to blackmail the politician.", "pos": "n./v./adv."},
    "blackmailer": {"def": "敲詐者、勒索者 (單數)", "ipa": "/ˈblækmeɪlə/", "trans": "blackmail (名詞/動詞/副詞)", "col": "greedy blackmailer", "ex": "The greedy blackmailer demanded more money.", "pos": "n."},
    "blackmailing": {"def": "敲詐、勒索、勒索的人 (或物) (勒)", "ipa": "/ˈblækmeɪlɪŋ/", "trans": "blackmail (名詞/動詞/副詞)", "col": "systematic blackmailing", "ex": "He was involved in a systematic blackmailing scheme.", "pos": "n./adv."},
    "blackness": {"def": "黑色、黑暗、邪惡", "ipa": "/ˈblæknəs/", "trans": "black (形容詞/名詞/動詞/副詞)", "col": "pitch blackness", "ex": "The forest was in pitch blackness.", "pos": "n."},
    "blackout": {"def": "停電、封鎖消息、(暈倒前)眼前發黑、停電的人 (或物)、停電地 (停電)", "ipa": "/ˈblækaʊt/", "trans": "blackouts", "col": "sudden blackout, news blackout", "ex": "The whole city suffered a sudden blackout.", "pos": "n./adv."},
    "blacksmith": {"def": "鐵匠 (單數)", "ipa": "/ˈblæksmɪθ/", "trans": "blacksmiths (複數)", "col": "skilled blacksmith", "ex": "The skilled blacksmith forged a new sword.", "pos": "n."},
    "bladder": {"def": "膀胱、氣囊、氣泡、氣囊的人物、氣囊地 (膀胱)", "ipa": "/ˈblædə/", "trans": "bladders", "col": "urinary bladder, swim bladder (魚鰾)", "ex": "He has a problem with his urinary bladder.", "pos": "n./adv."},
    "blade": {"def": "刀鋒、葉片、槳葉、刀身、少年、草葉的人、刀鋒地 (刀)", "ipa": "/bleɪd/", "trans": "blades", "col": "razor blade, blade of grass, rotor blade, shoulder blade", "ex": "The knife has a very sharp blade.", "pos": "n./adj./adv."},
}