import json

# Level 6 Part 30: (Beneficiary - Beset)
L6_PART30 = {
    "beneficiary": {"def": "受益人、受惠者、(教會)領俸者 (單數)", "ipa": "/ˌbenɪˈfɪʃəri/", "trans": "beneficiaries (複數)", "col": "sole beneficiary", "ex": "She was the sole beneficiary of her father's will.", "pos": "n."},
    "benefit": {"def": "利益、好處、保險金、救濟金、有益、獲益、有益的人、有益地 (益)", "ipa": "/ˈbenɪfɪt/", "trans": "benefits", "col": "unemployment benefit, health benefit, mutual benefit, for the benefit of", "ex": "The new law will benefit many families.", "pos": "n./v./adv."},
    "benevolence": {"def": "仁慈、善行、捐贈、慈悲", "ipa": "/bəˈnevələns/", "trans": "kindness", "col": "act of benevolence", "ex": "He was known for his benevolence to the poor.", "pos": "n."},
    "benevolent": {"def": "仁慈的、慈善的、親切的", "ipa": "/bəˈnevələnt/", "trans": "kind", "col": "benevolent organization", "ex": "A benevolent organization provided food for the homeless.", "pos": "adj."},
    "benevolently": {"def": "仁慈地、慈善地、親切地", "ipa": "/bəˈnevələntli/", "trans": "benevolent (形容詞)", "col": "smiled benevolently", "ex": "The old man smiled benevolently at the children.", "pos": "adv."},
    "benighted": {"def": "(詩)陷於黑暗的、愚昧的、趕路中因天黑受阻地 (愚)", "ipa": "/bɪˈnaɪtɪd/", "trans": "ignorant", "col": "benighted age", "ex": "He described the era as a benighted age of ignorance.", "pos": "adj./adv."},
    "benign": {"def": "親切的、慈祥的、(醫)良性的、溫和的", "ipa": "/bɪˈnaɪn/", "trans": "gentle", "col": "benign tumor (良性腫瘤), benign climate", "ex": "The doctor confirmed that the tumor was benign.", "pos": "adj."},
    "benignant": {"def": "仁慈的、和藹的、有益的", "ipa": "/bɪˈnɪɡnənt/", "trans": "kindly", "col": "benignant influence", "ex": "She had a benignant influence on the children.", "pos": "adj."},
    "benignity": {"def": "溫和、仁慈、善意", "ipa": "/bɪˈnɪɡnəti/", "trans": "kindness", "col": "infinite benignity", "ex": "He looked at them with infinite benignity.", "pos": "n."},
    "benignly": {"def": "親切地、慈祥地、良性地", "ipa": "/bɪˈnaɪnli/", "trans": "benign (形容詞)", "col": "regarded benignly", "ex": "The proposal was regarded benignly by the committee.", "pos": "adv."},
    "bent": {"def": "彎曲的、決心的、傾向、愛好、能力、決心地 (傾向)", "ipa": "/bent/", "trans": "inclination", "col": "bent on doing, artistic bent, natural bent", "ex": "He is bent on winning the race at all costs.", "pos": "adj./n./adv."},
    "benumb": {"def": "使麻木、使失去感覺、使昏迷", "ipa": "/bɪˈnʌm/", "trans": "numb", "col": "benumbed by cold", "ex": "His fingers were benumbed by the extreme cold.", "pos": "v."},
    "benzene": {"def": "苯 (化學品)", "ipa": "/ˈbenziːn/", "trans": "chemical", "col": "benzene ring", "ex": "Benzene is a colorless liquid with a sweet odor.", "pos": "n."},
    "bequeath": {"def": "遺贈、留傳", "ipa": "/bɪˈkwiːð/", "trans": "will", "col": "bequeath property to", "ex": "He bequeathed his entire fortune to charity.", "pos": "v."},
    "bequest": {"def": "遺贈、遺產物 (單數)", "ipa": "/bɪˈkwest/", "trans": "bequests (複數)", "col": "leave a bequest", "ex": "She left a large bequest to the local hospital.", "pos": "n."},
    "berate": {"def": "嚴厲指責、斥責", "ipa": "/bɪˈreɪt/", "trans": "scold", "col": "berate for", "ex": "The coach berated the players for their poor performance.", "pos": "v."},
    "bereave": {"def": "使喪失(親人或物)、使淒涼的人 (或物) (喪)", "ipa": "/bɪˈriːv/", "trans": "bereavement", "col": "bereaved family", "ex": "The war bereaved many families of their sons.", "pos": "v./adv."},
    "bereaved": {"def": "丧失親人的、受苦的、喪失親人的人", "ipa": "/bɪˈriːvd/", "trans": "bereave (動詞/副詞), bereavement", "col": "the bereaved family", "ex": "We offer our deepest condolences to the bereaved family.", "pos": "adj./n."},
    "bereavement": {"def": "喪親、喪友、喪失", "ipa": "/bɪˈriːvmənt/", "trans": "bereave (動詞/副詞), bereaved", "col": "sudden bereavement", "ex": "She is still suffering from the sudden bereavement.", "pos": "n."},
    "bereft": {"def": "喪失的、被剝奪的、被遺棄的", "ipa": "/bɪˈreft/", "trans": "deprived of", "col": "bereft of hope, bereft of reason", "ex": "The building was completely bereft of furniture.", "pos": "adj."},
    "beret": {"def": "貝雷帽 (單數)", "ipa": "/ˈbereɪ/", "trans": "berets (複數)", "col": "red beret", "ex": "The soldiers wore red berets.", "pos": "n."},
    "beriberi": {"def": "腳氣病", "ipa": "/ˌberiˈberi/", "trans": "disease", "col": "suffer from beriberi", "ex": "Beriberi is caused by a deficiency of vitamin B1.", "pos": "n."},
    "berry": {"def": "漿果、一粒漿果、採漿果、漿果般的、漿果地 (果)", "ipa": "/ˈberi/", "trans": "berries", "col": "strawberry, blueberry, raspberry, coffee berry", "ex": "We picked wild berries in the woods.", "pos": "n./v./adj./adv."},
    "berserk": {"def": "狂暴的、發狂的、狂暴地 (狂)", "ipa": "/bəˈsɜːk/", "trans": "crazy", "col": "go berserk", "ex": "The crowd went berserk with excitement.", "pos": "adj./adv."},
    "berth": {"def": "鋪位、停泊處、派給鋪位、停泊、停泊的人物、停泊地 (泊)", "ipa": "/bɜːθ/", "trans": "berths", "col": "lower berth, give a wide berth to (迴避)", "ex": "He booked a lower berth on the train.", "pos": "n./v./adv."},
    "beryl": {"def": "綠柱石、綠寶石", "ipa": "/ˈberəl/", "trans": "gem", "col": "pure beryl", "ex": "Emerald is a green variety of beryl.", "pos": "n."},
    "beseech": {"def": "哀求、懇求、懇求的人 (或物)、懇求地 (求)", "ipa": "/bɪˈsiːtʃ/", "trans": "implore", "col": "beseech help", "ex": "I beseech you to reconsider your decision.", "pos": "v./n./adv."},
    "beset": {"def": "困擾、包圍、裝飾、鑲嵌、困擾的人物、困擾地 (擾)", "ipa": "/bɪˈset/", "trans": "plague", "col": "beset with difficulties, beset by problems", "ex": "The project was beset with technical difficulties from the start.", "pos": "v./n./adv."},
}