import json

# Level 6 Part 15: (Attitude - Authorization)
L6_PART15 = {
    "attitude": {"def": "態度、看法、姿勢、姿勢的、態度地 (態度)", "ipa": "/ˈætɪtjuːd/", "trans": "attitudinal", "col": "positive attitude, change of attitude, take an attitude", "ex": "I don't like your attitude.", "pos": "n./adj./adv."},
    "attitudinal": {"def": "態度的、意向的", "ipa": "/ˌætɪˈtjuːdɪnl/", "trans": "attitude", "col": "attitudinal change", "ex": "There is a significant attitudinal change towards the environment.", "pos": "adj."},
    "attorney": {"def": "律師、代理人", "ipa": "/əˈtɜːni/", "trans": "lawyer", "col": "attorney general, district attorney, power of attorney (委託書)", "ex": "He was appointed as the attorney for the defendant.", "pos": "n."},
    "attract": {"def": "吸引、招引、引起", "ipa": "/əˈtrækt/", "trans": "attraction, attractive", "col": "attract attention, attract customers", "ex": "The new theme park will attract many visitors.", "pos": "v."},
    "attraction": {"def": "吸引、吸引力、景點、吸引物", "ipa": "/əˈtrækʃn/", "trans": "attract (動詞), attractive", "col": "tourist attraction, fatal attraction (致命的吸引力)", "ex": "The Eiffel Tower is a major tourist attraction.", "pos": "n."},
    "attractive": {"def": "有吸引力的、動人的、魅力的、吸引地 (吸引)", "ipa": "/əˈtræktɪv/", "trans": "attract (動詞), attraction", "col": "attractive woman, attractive price, attractive offer", "ex": "She is a very attractive woman.", "pos": "adj./adv."},
    "attractively": {"def": "有吸引力地、動人地、魅力地", "ipa": "/əˈtræktɪvli/", "trans": "attractive (形容詞/副詞), attract", "col": "attractively designed", "ex": "The food was attractively presented.", "pos": "adv."},
    "attractiveness": {"def": "吸引力、魅力", "ipa": "/əˈtræktɪvnəs/", "trans": "attractive (形容詞/副詞), attract", "col": "personal attractiveness", "ex": "She has a lot of personal attractiveness.", "pos": "n."},
    "attributable": {"def": "可歸因於...的", "ipa": "/əˈtrɪbjutəbl/", "trans": "attribute", "col": "attributable to", "ex": "The failure was partially attributable to bad luck.", "pos": "adj."},
    "attribute": {"def": "屬性、特性、特徵、歸因於、認為是...作品、屬性的、歸因地 (屬性)", "ipa": "/ˈætɪbjuːt/ (n.) /əˈtrɪbjuːt/ (v.)", "trans": "attribution, attributable", "col": "essential attribute, attribute to", "ex": "Patience is an essential attribute for a teacher.", "pos": "n./v./adj./adv."},
    "attribution": {"def": "歸屬、歸因、特徵", "ipa": "/ˌætrɪˈbjuːʃn/", "trans": "attribute (名詞/動詞/形容詞/副詞)", "col": "proper attribution", "ex": "The painting arrived without a proper attribution.", "pos": "n."},
    "attributive": {"def": "(語)定語、表屬性的、定語的", "ipa": "/əˈtrɪbjətɪv/", "trans": "attribute", "col": "attributive noun", "ex": "In 'gold watch', 'gold' is an attributive noun.", "pos": "adj."},
    "attrition": {"def": "磨損、消耗、人員縮減", "ipa": "/əˈtrɪʃn/", "trans": "waring away", "col": "war of attrition, staff attrition", "ex": "The company is reducing its staff through natural attrition.", "pos": "n."},
    "attune": {"def": "使調和、使適應、調音", "ipa": "/əˈtjuːn/", "trans": "tune", "col": "attune to", "ex": "Small children are very attuned to their parents' emotions.", "pos": "v."},
    "atypical": {"def": "非典型的、異常的、不規則的", "ipa": "/ˌeɪˈtɪpɪkl/", "trans": "unusual", "col": "atypical behavior", "ex": "This is an atypical example of his work.", "pos": "adj."},
    "atypically": {"def": "非典型地、異常地、不規則地", "ipa": "/ˌeɪˈtɪpɪkli/", "trans": "atypical (形容詞)", "col": "behave atypically", "ex": "He reacted atypically to the news.", "pos": "adv."},
    "auburn": {"def": "紅褐色的、赤褐色的、紅褐色", "ipa": "/ˈɔːbən/", "trans": "red-brown", "col": "auburn hair", "ex": "She has beautiful auburn hair.", "pos": "adj./n."},
    "auction": {"def": "拍賣、拍賣、在拍賣中賣、拍賣地 (拍賣)", "ipa": "/ˈɔːkʃn/", "trans": "auctions", "col": "public auction, auction house, sold at auction", "ex": "The painting was sold at auction for $1 million.", "pos": "n./v./adv."},
    "auctioneer": {"def": "拍賣人員、拍賣者、主持拍賣於", "ipa": "/ˌɔːkʃəˈnɪə/", "trans": "auction", "col": "official auctioneer", "ex": "The auctioneer closed the bidding.", "pos": "n./v."},
    "audacious": {"def": "大膽的、魯莽的、傲慢的", "ipa": "/ɔːˈdeɪʃəs/", "trans": "audacity", "col": "audacious plan", "ex": "They have an audacious plan to climb the mountain.", "pos": "adj."},
    "audacity": {"def": "大膽、魯莽、厚顏無恥", "ipa": "/ɔːˈdæsəti/", "trans": "audacious (形容詞)", "col": "have the audacity to", "ex": "He had the audacity to ask for more money.", "pos": "n."},
    "audible": {"def": "聽得見的、聲音的人、聽得見地 (聽得見)", "ipa": "/ˈɔːdəbl/", "trans": "audibly", "col": "barely audible", "ex": "His voice was barely audible above the noise.", "pos": "adj./n./adv."},
    "audibly": {"def": "聽得見地、顯著地", "ipa": "/ˈɔːdəbli/", "trans": "audible (形容詞/名詞/副詞)", "col": "sigh audibly", "ex": "She sighed audibly when she heard the news.", "pos": "adv."},
    "audience": {"def": "觀眾、聽眾、正式會見、正式會見地 (正式會見)", "ipa": "/ˈɔːdiəns/", "trans": "audiences", "col": "target audience, large audience, grant an audience", "ex": "The movie attracted a large audience.", "pos": "n./adv."},
    "audio": {"def": "音頻、聲音的、錄音的、錄音的人物、錄音地 (音頻)", "ipa": "/ˈɔːdiəʊ/", "trans": "visual", "col": "audio system, audio book, audio-visual (視聽)", "ex": "Connect the speakers to the audio output.", "pos": "n./adj./adv."},
    "audit": {"def": "審計、稽核、查帳、查帳地 (查帳)", "ipa": "/ˈɔːdɪt/", "trans": "auditor", "col": "internal audit, national audit, tax audit", "ex": "The company undergoes an annual audit of its accounts.", "pos": "n./v./adv."},
    "audition": {"def": "試鏡、試播、聽力、試鏡地 (試鏡)", "ipa": "/ɔːˈdɪʃn/", "trans": "auditions", "col": "audition for a role", "ex": "She has an audition for the lead role tomorrow.", "pos": "n./v./adv."},
    "auditor": {"def": "審計員、查帳員、旁聽生", "ipa": "/ˈɔːdɪtə/", "trans": "audit (名詞/動詞/副詞)", "col": "internal auditor, external auditor", "ex": "The internal auditor noticed many errors in the accounts.", "pos": "n."},
    "auditorium": {"def": "禮堂、觀眾席 (單數)", "ipa": "/ˌɔːdɪˈtɔːriəm/", "trans": "auditoriums/auditoria (複數)", "col": "school auditorium", "ex": "The ceremony will be held in the school auditorium.", "pos": "n."},
    "auditory": {"def": "聽覺的、聽眾的、聽眾", "ipa": "/ˈɔːdɪtəri/", "trans": "hearing", "col": "auditory nerve", "ex": "The disease can cause damage to the auditory nerve.", "pos": "adj./n."},
    "augment": {"def": "增加、增大、擴張、(音)延長、增加的人物、增加地 (增加)", "ipa": "/ɔːɡˈment/", "trans": "augmentation", "col": "augment income", "ex": "He took a second job to augment his income.", "pos": "v./n./adv."},
    "augmentation": {"def": "增加、擴張、增加物", "ipa": "/ˌɔːɡmenˈteɪʃn/", "trans": "augment (動詞/名詞/副詞)", "col": "staff augmentation", "ex": "We need staff augmentation for the new project.", "pos": "n."},
    "augur": {"def": "預兆、占卜師、預示、預兆的人物、預言地 (預兆)", "ipa": "/ˈɔːɡə/", "trans": "augury", "col": "augur well for (好兆頭)", "ex": "The early results augur well for the future of the company.", "pos": "n./v./adv."},
    "augury": {"def": "預兆、占卜、徵兆", "ipa": "/ˈɔːɡjəri/", "trans": "augur (名詞/動詞/副詞)", "col": "evil augury", "ex": "I take the black cat as an evil augury.", "pos": "n."},
    "August": {"def": "八月", "ipa": "/ˈɔːɡəst/", "trans": "Augusts", "col": "late August", "ex": "August is the eighth month of the year.", "pos": "n."},
    "august": {"def": "威嚴的、莊嚴的、神聖的", "ipa": "/ɔːˈɡʌst/", "trans": "noble", "col": "august presence", "ex": "He is in the august presence of the king.", "pos": "adj."},
    "aunt": {"def": "姑媽、姨媽、舅媽、嬸嬸", "ipa": "/ɑːnt/", "trans": "aunts", "col": "auntie, great-aunt", "ex": "My aunt lives in the countryside.", "pos": "n."},
    "aura": {"def": "氣氛、氣息、靈氣、(醫)預兆 (單數)", "ipa": "/ˈɔːrə/", "trans": "auras/aurae (複數)", "col": "aura of mystery", "ex": "The place has a strange aura of mystery.", "pos": "n."},
    "aural": {"def": "聽覺的、耳的、耳狀的", "ipa": "/ˈɔːrəl/", "trans": "ear", "col": "aural training", "ex": "Musicians need aural training.", "pos": "adj."},
    "aurally": {"def": "聽覺地、耳地", "ipa": "/ˈɔːrəli/", "trans": "aural (形容詞)", "col": "perceived aurally", "ex": "The information was perceived aurally.", "pos": "adv."},
    "auricle": {"def": "耳廓、心耳", "ipa": "/ˈɔːrɪkl/", "trans": "pinna", "col": "atrial auricle", "ex": "The auricle is the visible part of the ear.", "pos": "n."},
    "auricular": {"def": "耳的、聽覺的、密談的", "ipa": "/ɔːˈrɪkjələ/", "trans": "ear", "col": "auricular confession", "ex": "He had an auricular confession to the priest.", "pos": "adj."},
    "aurora": {"def": "極光、曙光 (單數)", "ipa": "/ɔːˈrɔːrə/", "trans": "auroras/aurorae (複數)", "col": "aurora borealis (北極光), aurora australis (南極光)", "ex": "We saw the beautiful aurora borealis in Norway.", "pos": "n."},
    "auspice": {"def": "支持、贊助、預兆、占卜 (單數/常用複數)", "ipa": "/ˈɔːspɪs/", "trans": "auspices (複數)", "col": "under the auspices of (在...贊助下)", "ex": "The event was organized under the auspices of the UNESCO.", "pos": "n."},
    "auspicious": {"def": "吉利的、幸運的、順利的", "ipa": "/ɔːˈspɪʃəs/", "trans": "lucky", "col": "auspicious occasion", "ex": "It was truly an auspicious occasion.", "pos": "adj."},
    "austere": {"def": "嚴厲的、簡樸的、苦行的", "ipa": "/ɔːˈstɪə/", "trans": "austerity", "col": "austere lifestyle", "ex": "He leads a very simple and austere lifestyle.", "pos": "adj."},
    "austerity": {"def": "簡樸、嚴厲、緊急措施、(政)緊縮政策", "ipa": "/ɔːˈsterəti/", "trans": "austere (形容詞)", "col": "austerity measures, period of austerity", "ex": "The government announced new austerity measures.", "pos": "n."},
    "authentic": {"def": "真實的、真正的、可靠的、真正的地 (真正)", "ipa": "/ɔːˈθentɪk/", "trans": "authentically, authenticity", "col": "authentic signature, authentic experience", "ex": "This is an authentic signature of the artist.", "pos": "adj./adv."},
    "authentically": {"def": "真實地、真正地、可靠地", "ipa": "/ɔːˈθentɪkli/", "trans": "authentic (形容詞/副詞), authenticity", "col": "reproduced authentically", "ex": "The historic building was reproduced authentically.", "pos": "adv."},
    "authenticate": {"def": "驗証、証實、使可靠", "ipa": "/ɔːˈθentɪkeɪt/", "trans": "authentication", "col": "authenticate a user", "ex": "You need a password to authenticate the user.", "pos": "v."},
    "authentication": {"def": "驗証、証實、鑑定", "ipa": "/ɔːˌθentɪˈkeɪʃn/", "trans": "authenticate (動詞)", "col": "user authentication, factor authentication", "ex": "Two-factor authentication is recommended for security.", "pos": "n."},
    "authenticity": {"def": "真實性、可靠性", "ipa": "/ˌɔːθenˈtɪsəti/", "trans": "authentic (形容詞/副詞)", "col": "verify authenticity", "ex": "Experts are checking the authenticity of the painting.", "pos": "n."},
    "author": {"def": "作者、作家、創始人、寫作、寫作的人物、寫作地 (作者)", "ipa": "/ˈɔːθə/", "trans": "authority, authorship", "col": "best-selling author, author of the plan", "ex": "Who is the author of this book?", "pos": "n./v./adv."},
    "authoritarian": {"def": "獨裁的、權力主義者、獨裁地 (獨裁)", "ipa": "/ɔːˌθɒrɪˈteəriən/", "trans": "authority", "col": "authoritarian regime", "ex": "The country is ruled by an authoritarian regime.", "pos": "adj./n./adv."},
    "authoritative": {"def": "權威的、命令式的、可靠的", "ipa": "/ɔːˈθɒrətətɪv/", "trans": "authority", "col": "authoritative source", "ex": "This is the most authoritative source on the subject.", "pos": "adj."},
    "authoritatively": {"def": "權威地、命令式地、可靠地", "ipa": "/ɔːˈθɒrətətɪvli/", "trans": "authoritative (形容詞), authority", "col": "speak authoritatively", "ex": "He spoke authoritatively to the crowd.", "pos": "adv."},
    "authority": {"def": "權威、權力、當局、權威人士、權威地 (權威)", "ipa": "/ɔːˈθɒrəti/", "trans": "authoritative", "col": "local authority, have authority over, position of authority", "ex": "Who has authority over this matter?", "pos": "n./adv."},
    "authorization": {"def": "授權、委託、認可", "ipa": "/ˌɔːθəraɪˈzeɪʃn/", "trans": "authorize (動詞)", "col": "official authorization, written authorization", "ex": "You need official authorization to enter the restricted area.", "pos": "n."},
}