import json

# Level 6 Part 43: (Botanic - Bourbon)
L6_PART43 = {
    "botanic/botanical": {"def": "植物的、植物學的、植物學的人、植物學地 (物)", "ipa": "/bəˈtænɪkl/", "trans": "botany", "col": "botanical garden, botanical study", "ex": "The botanical garden has a large collection of rare plants.", "pos": "adj./n./adv."},
    "botanist": {"def": "植物學家", "ipa": "/ˈbɒtənɪst/", "trans": "botany", "col": "field botanist", "ex": "The botanist spent years studying the flora of the island.", "pos": "n."},
    "botany": {"def": "植物學、植物、植物部的人、植物學地 (物)", "ipa": "/ˈbɒtəni/", "trans": "botanies", "col": "molecular botany", "ex": "Botany is the scientific study of plants.", "pos": "n./adv."},
    "botch": {"def": "笨拙地修補、弄糟、拙劣的工作、弄糟的人、弄糟地 (糟)", "ipa": "/bɒtʃ/", "trans": "botches", "col": "botch up (搞砸)", "ex": "I'm afraid I've made a botch of the repair.", "pos": "v./n./adv."},
    "both": {"def": "兩者都、兩個地 (二)", "ipa": "/bəʊθ/", "trans": "two", "col": "both of them, both A and B", "ex": "Both of his parents are teachers.", "pos": "adj./pron./adv."},
    "bother": {"def": "煩擾、打擾、煩心、麻煩、煩擾的人 (或物)、打擾地 (擾)", "ipa": "/ˈbɒðə/", "trans": "bothering", "col": "don't bother, sorry to bother you, without bother", "ex": "I'm sorry to bother you with my problems.", "pos": "v./n./adv."},
    "bothersome": {"def": "令人討厭的、煩人的、麻煩的", "ipa": "/ˈbɒðəsəm/", "trans": "annoying", "col": "bothersome flies", "ex": "The constant noise was very bothersome.", "pos": "adj."},
    "bottle": {"def": "瓶子、一瓶之量、裝入瓶中、(俚)勇氣、瓶子的人、裝瓶地 (瓶)", "ipa": "/ˈbɒtl/", "trans": "bottles, bottling", "col": "water bottle, wine bottle, lose one's bottle (失去勇氣), bottle neck (瓶頸)", "ex": "He drank a whole bottle of water.", "pos": "n./v./adv."},
    "bottleneck": {"def": "瓶頸、障礙、窄路、阻塞的人物、阻塞地 (阻)", "ipa": "/ˈbɒtlnek/", "trans": "bottlenecks", "col": "production bottleneck, traffic bottleneck", "ex": "The traffic bottleneck is caused by roadworks.", "pos": "n./v./adv."},
    "bottler": {"def": "裝瓶商、瓶裝器 (單數)", "ipa": "/ˈbɒtlə/", "trans": "bottling", "col": "local bottler", "ex": "The local bottler produces soft drinks under license.", "pos": "n."},
    "bottling": {"def": "裝瓶、裝瓶的人物 (裝)", "ipa": "/ˈbɒtlɪŋ/", "trans": "bottle (名詞/動詞/副詞)", "col": "bottling plant", "ex": "The company operates a large bottling plant.", "pos": "n./adv."},
    "bottom": {"def": "底部、臀部、末端、底部的、到達底部、在底部地 (底)", "ipa": "/ˈbɒtəm/", "trans": "bottoms", "col": "rock bottom, from the bottom of one's heart, bottom line (底線/盈虧)", "ex": "The keys are at the bottom of the bag.", "pos": "n./adj./v./adv."},
    "bottomless": {"def": "深不可測的、無底的、無限的", "ipa": "/ˈbɒtəmləs/", "trans": "infinite", "col": "bottomless pit", "ex": "The lake was said to be a bottomless pit.", "pos": "adj."},
    "bottom-line/bottom line": {"def": "盈虧表底線、最重要的事實、帳單底的人物、底線地 (底線)", "ipa": "/ˌbɒtəmˈlaɪn/", "trans": "core", "col": "the bottom line is", "ex": "The bottom line is that we need more money.", "pos": "n./adj./adv."},
    "botulism": {"def": "肉毒桿菌中毒 (單數)", "ipa": "/ˈbɒtʃulɪzəm/", "trans": "poisoning", "col": "stale botulism", "ex": "The outbreak was caused by botulism in contaminated canned food.", "pos": "n."},
    "boudoir": {"def": "閨房、私人休息室 (單數)", "ipa": "/ˈbuːdwɑː/", "trans": "boudoirs (複數)", "col": "elegant boudoir", "ex": "The elegant boudoir was decorated in pink silk.", "pos": "n."},
    "bougainvillaea": {"def": "九重葛 (單數)", "ipa": "/ˌbuːɡənˈvɪliə/", "trans": "plant", "col": "trailing bougainvillaea", "ex": "The colorful bougainvillaea covered the garden wall.", "pos": "n."},
    "bough": {"def": "大樹枝、主枝 (單數)", "ipa": "/baʊ/", "trans": "boughs (複數)", "col": "heavy bough", "ex": "The heavy bough snapped under the weight of the snow.", "pos": "n."},
    "bought": {"def": "(buy的過去式及過去分詞)、買了", "ipa": "/bɔːt/", "trans": "buy", "col": "bought some food", "ex": "I bought this book in London.", "pos": "v."},
    "bougie/boujee": {"def": "(俚)中產階級的、愛裝闊的 (單數)", "ipa": "/ˈbuːʒi/", "trans": "middle-class", "col": "so bougie", "ex": "She is so bougie with her designer handbags.", "pos": "n./adj."},
    "bouillabaisse": {"def": "馬賽魚湯、雜燴魚湯 (單數)", "ipa": "/ˌbuːjəˈbeɪs/", "trans": "soup", "col": "authentic bouillabaisse", "ex": "We had authentic bouillabaisse in a restaurant in Marseille.", "pos": "n."},
    "bouillon": {"def": "清湯、肉湯 (單數)", "ipa": "/ˈbuːjɒn/", "trans": "broth", "col": "beef bouillon", "ex": "The chef used beef bouillon as a base for the sauce.", "pos": "n."},
    "boulder": {"def": "大圓石、巨石 (單數)", "ipa": "/ˈbəʊldə/", "trans": "boulders (複數)", "col": "massive boulder", "ex": "A massive boulder blocked the mountain road.", "pos": "n."},
    "boulevard": {"def": "林蔭大道、大馬路 (單數)", "ipa": "/ˈbuːləvɑːd/", "trans": "boulevards (複數)", "col": "Sunset Boulevard", "ex": "We strolled along the tree-lined boulevard.", "pos": "n."},
    "bounce": {"def": "彈起、反彈、活力、吹牛、彈起的人 (或物)、充滿活力地 (彈)", "ipa": "/baʊns/", "trans": "bouncy, bouncing", "col": "check bounce (支票退票), bounce back (恢復), bounce off (徵求意見)", "ex": "The ball bounced high into the air.", "pos": "v./n./adv."},
    "bouncer": {"def": "(酒/夜店)保鏢、(體)彈跳球 (單數)", "ipa": "/ˈbaʊnsə/", "trans": "bouncers (複數)", "col": "club bouncer", "ex": "The club bouncer checked our IDs at the door.", "pos": "n."},
    "bouncy": {"def": "有彈性的、充滿活力的、反彈的人物", "ipa": "/ˈbaʊnsi/", "trans": "bounce (名詞/動詞/副詞)", "col": "bouncy castle (充氣城堡)", "ex": "The children had fun jumping in the bouncy castle.", "pos": "adj./n."},
    "bound": {"def": "受限的、肯定的、範圍、界線、彈跳、束縛的人物、極限地 (界)", "ipa": "/baʊnd/", "trans": "bounds, boundary", "col": "homeward bound, weather bound, out of bounds (禁止進入), bound to (一定會)", "ex": "He is bound by his promise.", "pos": "adj./n./v./adv."},
    "boundary": {"def": "邊界、分界線、範圍、邊界的人 (或物)、範圍地 (界)", "ipa": "/ˈbaʊndri/", "trans": "boundaries", "col": "territorial boundary, set boundaries", "ex": "The fence marks the boundary of our property.", "pos": "n./adv."},
    "boundless": {"def": "無限的、廣大無邊的、極其地 (限)", "ipa": "/ˈbaʊndləs/", "trans": "infinite", "col": "boundless energy", "ex": "He has boundless energy and enthusiasm.", "pos": "adj./adv."},
    "bounds": {"def": "範圍、領域、界限 (常用複數)", "ipa": "/baʊndz/", "trans": "bound", "col": "within bounds", "ex": "His behavior was beyond the bounds of deceny.", "pos": "n."},
    "bounteous": {"def": "豐裕的、大方的、慷慨地 (豐)", "ipa": "/ˈbaʊntiəs/", "trans": "generous", "col": "bounteous harvest", "ex": "They thanked God for the bounteous harvest.", "pos": "adj./adv."},
    "bountiful": {"def": "慷慨的、豐富的、大方的地 (大方)", "ipa": "/ˈbaʊntɪfl/", "trans": "plentiful", "col": "bountiful nature", "ex": "The land is known for its bountiful natural resources.", "pos": "adj./adv."},
    "bountifully": {"def": "慷慨地、豐富地、大方地", "ipa": "/ˈbaʊntɪfli/", "trans": "bountiful (形容詞/副詞)", "col": "provided bountifully", "ex": "They provided for the visitors bountifully.", "pos": "adv."},
    "bounty": {"def": "慷慨、恩惠、獎金、豐富的人、獎金地 (賞)", "ipa": "/ˈbaʊnti/", "trans": "bounties", "col": "bounty hunter (賞金獵人), government bounty", "ex": "The company offered a bounty for information about the suspect.", "pos": "n./adv."},
    "bouquet": {"def": "花束、(酒)芬芳 (單數)", "ipa": "/buˈkeɪ/", "trans": "bouquets (複數)", "col": "bouquet of roses", "ex": "He gave her a large bouquet of red roses.", "pos": "n."},
    "bourbon": {"def": "波旁威士忌、(法)波旁家族 (單數)", "ipa": "/ˈbɜːbən/", "trans": "whiskey", "col": "kentucky bourbon", "ex": "He poured himself a glass of kentucky bourbon.", "pos": "n."},
}