import json

# Level 6 Part 6: (Ancestral - Announce)
L6_PART6 = {
    "ancestral": {"def": "祖先的、祖傳的", "ipa": "/ænˈsestrəl/", "trans": "ancestor (名詞/形容詞/副詞), ancestry", "col": "ancestral home", "ex": "He returned to his ancestral home in Ireland.", "pos": "adj."},
    "ancestry": {"def": "祖先、血統、家世", "ipa": "/ˈænsestri/", "trans": "ancestor (名詞/形容詞/副詞), ancestral", "col": "of royal ancestry", "ex": "She can trace her ancestry back to the 16th century.", "pos": "n."},
    "anchor": {"def": "錨、靠山、新聞主播、拋錨、固定、擔任主播、錨的、固定的、穩固地 (錨)", "ipa": "/ˈæŋkə/", "trans": "anchored", "col": "drop anchor, cast anchor, news anchor", "ex": "The ship dropped anchor in the bay.", "pos": "n./v./adj./adv."},
    "anchorage": {"def": "拋錨地、停泊所、固定物", "ipa": "/ˈæŋkərɪdʒ/", "trans": "anchor (名詞/動詞/形容詞/副詞)", "col": "secure anchorage", "ex": "The bay provides a secure anchorage for ships.", "pos": "n."},
    "ancient": {"def": "古代的、古老的、古人的、長壽的、古代人、老人、長者、古老地 (古老)", "ipa": "/ˈeɪnʃənt/", "trans": "ancients", "col": "ancient Greece, ancient civilization, ancient history", "ex": "Ancient Greece was a major power in the Mediterranean.", "pos": "adj./n./adv."},
    "ancillary": {"def": "輔助的、附屬的、副的、助手、附件", "ipa": "/ænˈsɪləri/", "trans": "auxiliary", "col": "ancillary staff", "ex": "The ancillary staff provides essential support for the hospital.", "pos": "adj./n."},
    "and": {"def": "和、與、而且、以及、和、與、其、及、以及地 (和)", "ipa": "/ənd/", "trans": "as well as", "col": "and so on, and so forth", "ex": "I like tea and coffee.", "pos": "conj./n./adv."},
    "anecdotal": {"def": "軼聞的、多軼事的、不確鑿的", "ipa": "/ˌænɪkˈdəʊtl/", "trans": "anecdote", "col": "anecdotal evidence", "ex": "The report is based on anecdotal evidence rather than hard facts.", "pos": "adj."},
    "anecdote": {"def": "軼事、趣聞", "ipa": "/ˈænɪkdəʊt/", "trans": "anecdotal", "col": "amusing anecdote", "ex": "He told us an amusing anecdote about his cat.", "pos": "n."},
    "anemia/anaemia": {"def": "貧血、無活力", "ipa": "/əˈniːmiə/", "trans": "anemic", "col": "severe anemia", "ex": "Severe anemia can cause fatigue and weakness.", "pos": "n."},
    "anemic/anaemic": {"def": "貧血的、無活力的、患貧血症的", "ipa": "/əˈniːmɪk/", "trans": "anemia (名詞)", "col": "anemic economic growth", "ex": "The country is suffering from anemic economic growth.", "pos": "adj."},
    "anemometer": {"def": "風速計", "ipa": "/ˌænɪˈmɒmɪtə/", "trans": "wind gauge", "col": "cup anemometer", "ex": "The anemometer showed that the wind speed was 50 mph.", "pos": "n."},
    "anesthesia/anaesthesia": {"def": "麻醉、麻木", "ipa": "/ˌænəˈsθiːziə/", "trans": "anesthetic", "col": "local anesthesia", "ex": "The local anesthesia numbed the area around the tooth.", "pos": "n."},
    "anesthetic/anaesthetic": {"def": "麻醉劑、麻醉的", "ipa": "/ˌænəsˈθetɪk/", "trans": "anesthesia", "col": "anesthetic spray", "ex": "The anesthetic spray helped to ease the pain.", "pos": "n./adj."},
    "anesthetist/anaesthetist": {"def": "麻醉師", "ipa": "/əˈniːsθətɪst/", "trans": "anesthesia", "col": "specialist anesthetist", "ex": "The anesthetist monitored the patient's condition throughout the operation.", "pos": "n."},
    "anew": {"def": "重新、再度", "ipa": "/əˈnjuː/", "trans": "afresh", "col": "begin anew", "ex": "He decided to begin his life anew in a different city.", "pos": "adv."},
    "angel": {"def": "天使、守護神、大好人、可愛的人、天使般的、守護神般的、可愛地 (天使)", "ipa": "/ˈeɪndʒl/", "trans": "angelic", "col": "guardian angel, angel of mercy", "ex": "She is an absolute angel for helping me.", "pos": "n./adj./adv."},
    "angelic": {"def": "天使的、天真可愛的、善心的", "ipa": "/ænˈdʒelɪk/", "trans": "angel (名詞/形容詞/副詞)", "col": "angelic face", "ex": "The child has an angelic face.", "pos": "adj."},
    "anger": {"def": "憤怒、激怒、生氣、憤怒地、生氣地 (憤怒)", "ipa": "/ˈæŋɡə/", "trans": "angry", "col": "burst with anger, in anger", "ex": "He struggled to control his anger.", "pos": "n./v./adv."},
    "angle": {"def": "角度、角、觀點、獵取、釣魚、使成角度、傾斜地、彎曲地 (角)", "ipa": "/ˈæŋɡl/", "trans": "angled", "col": "right angle, interesting angle, from another angle", "ex": "What is the angle of the slope?", "pos": "n./v./adv."},
    "angler": {"def": "釣魚者、琵琶魚", "ipa": "/ˈæŋɡlə/", "trans": "angling", "col": "keen angler", "ex": "He is a keen angler who spends every weekend by the river.", "pos": "n."},
    "angle-worm": {"def": "釣餌用之蚯蚓", "ipa": "/ˈæŋɡlwɜːm/", "trans": "earthworm", "col": "hook an angle-worm", "ex": "The child was digging for an angle-worm to use as bait.", "pos": "n."},
    "anglicize": {"def": "使英國化、使現代化、採用英語式的習慣", "ipa": "/ˈæŋɡlɪsaɪz/", "trans": "English", "col": "anglicized name", "ex": "The family anglicized their name when they moved to the US.", "pos": "v."},
    "angling": {"def": "垂釣、釣魚技巧", "ipa": "/ˈæŋɡlɪŋ/", "trans": "angler", "col": "fly angling", "ex": "Angling is a very popular sport in the UK.", "pos": "n."},
    "angry": {"def": "生氣的、憤怒的、狂暴的、紅腫的、生氣地、憤怒地 (生氣)", "ipa": "/ˈæŋɡri/", "trans": "anger, angrily", "col": "get angry, angry mob", "ex": "He was angry with her for being late.", "pos": "adj./adv."},
    "angrily": {"def": "生氣地、憤怒地、狂暴地", "ipa": "/ˈæŋɡrəli/", "trans": "angry (形容詞/副詞), anger", "col": "shout angrily", "ex": "He shouted angrily at the reporter.", "pos": "adv."},
    "anguish": {"def": "極度痛苦、苦惱、使極度痛苦、苦惱、極度痛苦地、苦惱地 (痛苦)", "ipa": "/ˈæŋɡwɪʃ/", "trans": "agonized", "col": "mental anguish, cry of anguish", "ex": "The mother was filled with anguish after her son went missing.", "pos": "n./v./adv."},
    "angular": {"def": "有角的、瘦骨嶙峋的、生硬的", "ipa": "/ˈæŋɡjələ/", "trans": "angularity", "col": "angular features", "ex": "He has very angular features.", "pos": "adj."},
    "aniline": {"def": "苯胺、苯胺的、苯胺藍", "ipa": "/ˈænɪliːn/", "trans": "dyes", "col": "aniline dye", "ex": "Aniline is used in the manufacture of dyes.", "pos": "n./adj."},
    "animal": {"def": "動物、畜生、野獸、動物的、肉體的、野獸般的、野獸地 (動物)", "ipa": "/ˈænɪml/", "trans": "beast", "col": "wild animal, domestic animal, animal rights", "ex": "The lion is a wild animal.", "pos": "n./adj./adv."},
    "animate": {"def": "賦予生命、激勵、使活潑、有生命的、活潑的、賦予生命的人 (或物)、有生命地 (生命)", "ipa": "/ˈænɪmət/ (adj.) /ˈænɪmeɪt/ (v.)", "trans": "animation, animated", "col": "animate object", "ex": "The director managed to animate the characters.", "pos": "v./adj./n./adv."},
    "animated": {"def": "動畫的、活潑的、興奮的、有生命的", "ipa": "/ˈænɪmeɪtɪd/", "trans": "animate (動詞/形容詞/名詞/副詞), animation", "col": "animated cartoon, animated discussion", "ex": "They had an animated discussion about politics.", "pos": "adj."},
    "animation": {"def": "動畫、活潑、生氣、賦予生命", "ipa": "/ˌænɪˈmeɪʃn/", "trans": "animate (動詞/形容詞/名詞/副詞), animated", "col": "computer animation, suspension animation (暫時停職)", "ex": "The movie uses the latest computer animation techniques.", "pos": "n."},
    "animosity": {"def": "仇恨、敵意、怨恨", "ipa": "/ˌænɪˈmɒsəti/", "trans": "hostility", "col": "personal animosity", "ex": "There is no personal animosity between them.", "pos": "n."},
    "animus": {"def": "敵意、惡意、男性意向、(心)阿尼瑪斯", "ipa": "/ˈænɪməs/", "trans": "hostility", "col": "personal animus", "ex": "He has a strong personal animus towards his former boss.", "pos": "n."},
    "ankle": {"def": "腳踝", "ipa": "/ˈæŋkl/", "trans": "ankles", "col": "twisted ankle, sprained ankle", "ex": "She twisted her ankle while playing tennis.", "pos": "n."},
    "anklet": {"def": "腳環、短襪", "ipa": "/ˈæŋklət/", "trans": "ankle", "col": "silver anklet", "ex": "She was wearing a silver anklet on her left foot.", "pos": "n."},
    "annalist": {"def": "編年史作者、記錄者", "ipa": "/ˈænəlɪst/", "trans": "annals", "col": "court annalist", "ex": "The court annalist recorded the king's deeds.", "pos": "n."},
    "annals": {"def": "編年史、記錄、年報", "ipa": "/ˈænlz/", "trans": "annalist", "col": "historical annals", "ex": "The event is recorded in the historical annals of the city.", "pos": "n."},
    "anneal": {"def": "退火、使其變韌、鍛煉、退火、使變韌", "ipa": "/əˈniːl/", "trans": "toughen", "col": "anneal glass", "ex": "The glass is annealed to make it stronger.", "pos": "v./n."},
    "annex": {"def": "併吞、附加、獲得、附件、增建建築物、併吞地、附加地、(法律)附屬地 (併吞)", "ipa": "/əˈneks/ (v.) /ˈæneks/ (n.)", "trans": "annexation", "col": "annex a territory", "ex": "The country decided to annex the small territory.", "pos": "v./n./adv./adj."},
    "annexation": {"def": "併吞、合併、附加物", "ipa": "/ˌænekˈseɪʃn/", "trans": "annex (動詞/名詞/副詞/形容詞)", "col": "territorial annexation", "ex": "The territorial annexation led to an international crisis.", "pos": "n."},
    "annihilate": {"def": "殲滅、消滅、毀滅、廢除", "ipa": "/əˈnaɪəleɪt/", "trans": "annihilation", "col": "annihilate the enemy", "ex": "The whole army was annihilated in the battle.", "pos": "v."},
    "annihilation": {"def": "殲滅、消滅、毀滅", "ipa": "/əˌnaɪəˈleɪʃn/", "trans": "annihilate (動詞)", "col": "total annihilation", "ex": "The nuclear war would result in total annihilation of the human race.", "pos": "n."},
    "anniversary": {"def": "週年紀念日、週年紀念的", "ipa": "/ˌænɪˈvɜːsəri/", "trans": "anniversaries", "col": "wedding anniversary, diamond anniversary", "ex": "We are celebrating our tenth wedding anniversary this year.", "pos": "n./adj."},
    "annotate": {"def": "註解、註釋、作註解", "ipa": "/ˈænəteɪt/", "trans": "annotation", "col": "annotated edition", "ex": "The book is an annotated edition for students.", "pos": "v."},
    "annotation": {"def": "註解、註釋", "ipa": "/ˌænəˈteɪʃn/", "trans": "annotate (動詞)", "col": "detailed annotation", "ex": "The detailed annotations help to explain the text.", "pos": "n."},
    "announce": {"def": "宣佈、宣告、預告、發表演說、宣佈的人 (或物)、宣佈地 (宣佈)", "ipa": "/əˈnaʊns/", "trans": "announcement, announcer", "col": "announce a decision, announce engagement", "ex": "They are going to announce the results tomorrow.", "pos": "v./n./adv."},
}