import json

# Level 2 Part 6: (Cargo - Chain)
L2_PART6 = {
    "cargo": {"def": "貨物", "ipa": "/ˈkɑːɡəʊ/", "trans": "cargoes", "col": "cargo ship, air cargo", "ex": "The ship is carrying a cargo of wood.", "pos": "n."},
    "carpenter": {"def": "木工、木匠、當木匠、修補", "ipa": "/ˈkɑːpəntə/", "trans": "carpentry", "col": "master carpenter", "ex": "He is a skilled carpenter.", "pos": "n./v."},
    "carpet": {"def": "地毯、覆蓋層、鋪地毯、覆蓋", "ipa": "/ˈkɑːpɪt/", "trans": "carpeting", "col": "wall-to-wall carpet, magic carpet", "ex": "The floor was covered with a thick carpet.", "pos": "n./v."},
    "carrot": {"def": "胡蘿蔔", "ipa": "/ˈkærət/", "trans": "carrots", "col": "carrot cake, carrot and stick", "ex": "Rabbits love eating carrots.", "pos": "n."},
    "carry": {"def": "攜帶、傳送、運載", "ipa": "/ˈkæri/", "trans": "carrier, carried", "col": "carry on, carry out", "ex": "He was carrying a heavy suitcase.", "pos": "v."},
    "cart": {"def": "手推車、二輪馬車、用車裝運", "ipa": "/kɑːt/", "trans": "carting", "col": "shopping cart, go-cart", "ex": "He put the groceries in the cart.", "pos": "n./v."},
    "cartoon": {"def": "卡通、漫畫、為...畫漫畫", "ipa": "/kɑːˈtuːn/", "trans": "cartoonist", "col": "animated cartoon", "ex": "The kids are watching cartoons.", "pos": "n./v."},
    "carve": {"def": "雕刻、切開", "ipa": "/kɑːv/", "trans": "carving, carver", "col": "carve out a career", "ex": "He carved a bird out of wood.", "pos": "v."},
    "case": {"def": "案例、案件、箱、情況、裝入箱中", "ipa": "/keɪs/", "trans": "casing", "col": "in case of, police case, briefcase", "ex": "In this case, I agree with you.", "pos": "n./v."},
    "cash": {"def": "現金、兌現", "ipa": "/kæʃ/", "trans": "cashier", "col": "cash on delivery, hard cash", "ex": "Do you have any cash on you?", "pos": "n./v."},
    "cassette": {"def": "卡式磁帶", "ipa": "/kəˈset/", "trans": "cassettes", "col": "cassette player", "ex": "I used to listen to music on cassette.", "pos": "n."},
    "cast": {"def": "投射、演員陣容、鑄造、石膏模型、投放、撇開", "ipa": "/kɑːst/", "trans": "casting", "col": "cast a vote, cast a shadow", "ex": "The moon cast a pale light over the garden.", "pos": "n./v."},
    "castle": {"def": "城堡、（西洋棋）圍城、把...置於城堡中", "ipa": "/ˈkɑːsl/", "trans": "castles", "col": "build castles in the air", "ex": "They visited an old castle in Scotland.", "pos": "n./v."},
    "casual": {"def": "偶然的、漫不經心的、便裝的", "ipa": "/ˈkæʒuəl/", "trans": "casually", "col": "casual clothes, casual acquaintance", "ex": "I prefer wearing casual clothes.", "pos": "adj."},
    "catalog(ue)": {"def": "目錄、目錄簿、為...編目錄", "ipa": "/ˈkætəlɒɡ/", "trans": "cataloging", "col": "library catalog, mail-order catalog", "ex": "I'm looking through the furniture catalog.", "pos": "n./v."},
    "catch": {"def": "捕捉、趕上、感染、陷阱、捕獲物", "ipa": "/kætʃ/", "trans": "caught, catcher", "col": "catch a cold, catch up with", "ex": "Did you catch any fish?", "pos": "v./n."},
    "cause": {"def": "原因、事業、導致、引起", "ipa": "/kɔːz/", "trans": "causal, causation", "col": "cause and effect, common cause", "ex": "What was the cause of the fire?", "pos": "n./v."},
    "cave": {"def": "洞穴、山洞、挖洞、塌陷", "ipa": "/keɪv/", "trans": "cavern", "col": "explore a cave", "ex": "The explorers found a deep cave.", "pos": "n./v."},
    "cease": {"def": "停止、終止", "ipa": "/siːs/", "trans": "ceaseless", "col": "cease fire", "ex": "The rain has finally ceased.", "pos": "v./n."},
    "ceiling": {"def": "天花板、最高限度", "ipa": "/ˈsiːlɪŋ/", "trans": "ceilings", "col": "high ceiling, price ceiling", "ex": "The room has a very high ceiling.", "pos": "n."},
    "celebrate": {"def": "慶祝、讚美", "ipa": "/ˈselɪbreɪt/", "trans": "celebration, celebrity", "col": "celebrate a birthday", "ex": "We are celebrating our wedding anniversary.", "pos": "v."},
    "celebration": {"def": "慶祝活動、慶祝", "ipa": "/ˌselɪˈbreɪʃn/", "trans": "celebrate (動詞)", "col": "victory celebration", "ex": "The city was full of celebration after the win.", "pos": "n."},
    "cell": {"def": "細胞、小室、電池", "ipa": "/sel/", "trans": "cellular", "col": "cancer cell, prison cell", "ex": "The human body is made up of millions of cells.", "pos": "n."},
    "cellar": {"def": "地窖、地下室、把...藏入地窖", "ipa": "/ˈselə/", "trans": "cellars", "col": "wine cellar", "ex": "We store our wine in the cellar.", "pos": "n./v."},
    "cent": {"def": "分（貨幣單位）", "ipa": "/sent/", "trans": "percent", "col": "per cent", "ex": "There are 100 cents in a dollar.", "pos": "n."},
    "center": {"def": "中心、中央、置於中心、集中", "ipa": "/ˈsentə/", "trans": "central, centralize", "col": "shopping center, sports center", "ex": "The town center is very busy.", "pos": "n./v."},
    "central": {"def": "中央的、主要的", "ipa": "/ˈsentrəl/", "trans": "center (名詞), centrally", "col": "central heating, central bank", "ex": "The hotel is in a very central location.", "pos": "adj."},
    "century": {"def": "世紀、百年", "ipa": "/ˈsentʃəri/", "trans": "centuries", "col": "21st century, turn of the century", "ex": "We are living in the 21st century.", "pos": "n."},
    "cereal": {"def": "穀物、麥片、穀類的", "ipa": "/ˈsɪəriəl/", "trans": "cereals", "col": "breakfast cereal", "ex": "I usually have cereal for breakfast.", "pos": "n./adj."},
    "certain": {"def": "確定的、某個、某些、確定的事", "ipa": "/ˈsɜːtn/", "trans": "certainly, certainty", "col": "make certain, for certain", "ex": "I'm certain that he's telling the truth.", "pos": "adj./pron."},
    "certainly": {"def": "無疑地、當然", "ipa": "/ˈsɜːtnli/", "trans": "certain (形容詞)", "col": "certainly not", "ex": "I will certainly be there.", "pos": "adv."},
    "certificate": {"def": "證書、證明、發給證書", "ipa": "/səˈtɪfɪkət/", "trans": "certification", "col": "birth certificate, marriage certificate", "ex": "She received a certificate for her perfect attendance.", "pos": "n./v."},
    "chain": {"def": "鏈條、連鎖店、一連串、束縛、用鏈條鎖住", "ipa": "/tʃeɪn/", "trans": "chained", "col": "chain reaction, supermarket chain", "ex": "The dog was tied to a tree by a heavy chain.", "pos": "n./v."},
    "chair": {"def": "椅子、主席、主持（會議）", "ipa": "/tʃeə/", "trans": "chairman, chairperson", "col": "electric chair, rock chair", "ex": "Please sit down on that chair.", "pos": "n./v."},
    "chalk": {"def": "粉筆、白堊、用粉筆畫", "ipa": "/tʃɔːk/", "trans": "chalky", "col": "piece of chalk", "ex": "The teacher used white chalk to write on the board.", "pos": "n./v."},
    "challenge": {"def": "挑戰、懷疑、向...挑戰、對...質疑", "ipa": "/ˈtʃælɪndʒ/", "trans": "challenger, challenging", "col": "accept a challenge", "ex": "This job will be a real challenge for me.", "pos": "n./v."},
    "chamber": {"def": "室、房間、議院、私人的、室內的", "ipa": "/ˈtʃeɪmbə/", "trans": "chambers", "col": "chamber music, legislative chamber", "ex": "The king was in his private chamber.", "pos": "n./adj."},
    "champion": {"def": "冠軍、擁護者、優秀的、捍衛", "ipa": "/ˈtʃæmpiən/", "trans": "championship", "col": "world champion", "ex": "They are the reigning champions.", "pos": "n./adj./v."},
    "championship": {"def": "冠軍地位、錦標賽", "ipa": "/ˈtʃæmpiənʃɪp/", "trans": "champion (名詞)", "col": "national championship", "ex": "The team won the championship last year.", "pos": "n."},
    "chance": {"def": "機會、可能、偶然的、碰巧、冒險", "ipa": "/tʃɑːns/", "trans": "chancy", "col": "by chance, take a chance", "ex": "Give me one more chance.", "pos": "n./adj./v."},
    "change": {"def": "改變、更換、找錢、變動", "ipa": "/tʃeɪndʒ/", "trans": "changed, changeable", "col": "change one's mind, loose change", "ex": "The weather is starting to change.", "pos": "v./n."},
    "channel": {"def": "頻道、海峽、通道、引導", "ipa": "/ˈtʃænl/", "trans": "channeled", "col": "news channel, English Channel", "ex": "Which channel is the game on?", "pos": "n./v."},
}

with open("batch_l2_p6.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART6, f, ensure_ascii=False, indent=2)
