import json

# Level 5 Part 11: (Tuition - Workshop)
L5_PART11 = {
    "tuition": {"def": "學費、教授、教學", "ipa": "/tjuˈɪʃn/", "trans": "tutor", "col": "pay tuition, tuition fees", "ex": "The university has increased its tuition fees.", "pos": "n."},
    "vinegar": {"def": "醋、尖酸刻薄、脾氣不好、加醋於、變酸", "ipa": "/ˈvɪnɪɡə/", "trans": "vinegary", "col": "balsamic vinegar", "ex": "She added some vinegar to the salad.", "pos": "n./v."},
    "texture": {"def": "質地、口感、結構、手感、形成紋理", "ipa": "/ˈtekstʃə/", "trans": "textures", "col": "smooth texture, rough texture", "ex": "The fabric has a very smooth texture.", "pos": "n./v."},
    "tumor": {"def": "腫瘤、腫塊", "ipa": "/ˈtjuːmə/", "trans": "tumorous", "col": "brain tumor, benign tumor", "ex": "The doctor discovered a benign tumor on her arm.", "pos": "n."},
    "virtual": {"def": "虛擬的、實質上的、事實上的", "ipa": "/ˈvɜːtʃuəl/", "trans": "virtuality, virtually", "col": "virtual reality, virtual assistant", "ex": "The website offers a virtual tour of the museum.", "pos": "adj."},
    "theft": {"def": "偷竊、贓物", "ipa": "/θeft/", "trans": "thief", "col": "identity theft, grand theft", "ex": "He was charged with identity theft.", "pos": "n."},
    "trait": {"def": "特徵、特點、少許", "ipa": "/treɪt/", "trans": "traits", "col": "inherited trait, personality trait", "ex": "Patience is a key personality trait for a teacher.", "pos": "n."},
    "variation": {"def": "變化、變動、變種、變奏曲", "ipa": "/ˌveəriˈeɪʃn/", "trans": "vary, variable", "col": "genetic variation, seasonal variation", "ex": "There is a wide variation in the prices of cars.", "pos": "n."},
    "witty": {"def": "機智的、詼諧的、機捷的", "ipa": "/ˈwɪti/", "trans": "wit, wittily", "col": "witty remark", "ex": "He is known for his witty remarks.", "pos": "adj."},
    "traitor": {"def": "叛徒、賣國賊", "ipa": "/ˈtreɪtə/", "trans": "treason, betray", "col": "labeled a traitor", "ex": "He was labeled a traitor for selling secrets to the enemy.", "pos": "n."},
    "vein": {"def": "靜脈、血管、葉脈、紋理、心緒、風格、使成紋理", "ipa": "/veɪn/", "trans": "veins", "col": "varicose vein, blue vein", "ex": "The nurse found a vein to draw blood.", "pos": "n./v."},
    "workshop": {"def": "工作坊、研習會、車間、加工廠", "ipa": "/ˈwɜːkʃɒp/", "trans": "workshops", "col": "writing workshop, carpentry workshop", "ex": "I attended a writing workshop last weekend.", "pos": "n."},
    "cargo": {"def": "貨物、載重量", "ipa": "/ˈkɑːɡəʊ/", "trans": "cargoes, cargos", "col": "cargo ship, air cargo", "ex": "The ship is carrying a cargo of timber.", "pos": "n."},
    "carnival": {"def": "嘉年華會、狂歡節、馬戲團", "ipa": "/ˈkɑːnɪvl/", "trans": "carnivals", "col": "Rio Carnival", "ex": "We had a lot of fun at the carnival.", "pos": "n."},
    "carp": {"def": "鯉魚、吹毛求疵、挑剔", "ipa": "/kɑːp/", "trans": "carper, carping", "col": "carp at", "ex": "He's always carping at the rules.", "pos": "n./v."},
    "carpenter": {"def": "木工、木匠、做木工活、修理", "ipa": "/ˈkɑːpəntə/", "trans": "carpentry", "col": "skilled carpenter", "ex": "The furniture was made by a skilled carpenter.", "pos": "n./v."},
    "carpentry": {"def": "木工活、木器、木工術", "ipa": "/ˈkɑːpəntri/", "trans": "carpenter (名詞/動詞)", "col": "course in carpentry", "ex": "He took a course in carpentry at the local college.", "pos": "n."},
    "carpet": {"def": "地毯、蓋層、在...上鋪地毯、覆蓋、斥責、地毯狀的", "ipa": "/ˈkɑːpɪt/", "trans": "carpets", "col": "magic carpet, red carpet", "ex": "The floor is covered with a thick red carpet.", "pos": "n./v./adj."},
    "carriage": {"def": "馬車、車廂、運費、姿態", "ipa": "/ˈkærɪdʒ/", "trans": "carriages", "col": "horse-drawn carriage", "ex": "The princess arrived in a horse-drawn carriage.", "pos": "n."},
    "carrier": {"def": "運送者、載體、航空母艦、帶菌者", "ipa": "/ˈkæriə/", "trans": "carry (動詞)", "col": "aircraft carrier, mail carrier", "ex": "The company is a major carrier of international mail.", "pos": "n."},
    "carrot": {"def": "胡蘿蔔、誘餌、好處", "ipa": "/ˈkærət/", "trans": "carrots", "col": "carrot and stick (獎懲並用)", "ex": "She used the promise of a trip to the zoo as a carrot to get the children to do their homework.", "pos": "n."},
    "carry": {"def": "攜帶、運送、傳達、支撐、進位、射程、背、抱、搬運的人 (或物)", "ipa": "/ˈkæri/", "trans": "carrying, carrier", "col": "carry out, carry on, carry over", "ex": "Can you help me carry these bags?", "pos": "v./n."},
    "cart": {"def": "手推車、二輪馬車、用車載、運送、強行帶走、手推車的", "ipa": "/kɑːt/", "trans": "carting, carter", "col": "go-cart, shopping cart", "ex": "Please put the items in the shopping cart.", "pos": "n./v./adj."},
    "cartel": {"def": "企業聯合、卡特爾、換文、挑戰書", "ipa": "/kɑːˈtel/", "trans": "cartels", "col": "drug cartel, oil cartel", "ex": "The oil cartel decided to increase production.", "pos": "n."},
    "carton": {"def": "紙盒、紙箱、靶心、紙製的", "ipa": "/ˈkːtn/", "trans": "cartons", "col": "milk carton, egg carton", "ex": "I'd like a carton of milk, please.", "pos": "n./adj."},
    "cartoon": {"def": "卡通、漫畫、草圖、連環畫、畫漫畫、卡通化的", "ipa": "/kɑːˈtuːn/", "trans": "cartoonist", "col": "animated cartoon", "ex": "The children love watching animated cartoons.", "pos": "n./v./adj."},
    "cartoonist": {"def": "漫畫家、卡通作家", "ipa": "/kɑːˈtuːnɪst/", "trans": "cartoon (名詞/動詞/形容詞)", "col": "political cartoonist", "ex": "He is a famous political cartoonist.", "pos": "n."},
    "cartridge": {"def": "彈藥筒、墨水匣、底片盒", "ipa": "/ˈkːtrɪdʒ/", "trans": "cartridges", "col": "ink cartridge, movie cartridge", "ex": "The printer needs a new ink cartridge.", "pos": "n."},
    "carve": {"def": "雕刻、切開、瓜分、切成片", "ipa": "/kɑːv/", "trans": "carving, carver", "col": "carve a statue, carve out a career", "ex": "He carved a beautiful statue out of wood.", "pos": "v."},
    "carving": {"def": "雕刻品、雕刻術、切肉、雕刻的", "ipa": "/ˈkɑːvɪŋ/", "trans": "carve (動詞), carver", "col": "wood carving", "ex": "She is an expert in traditional wood carving.", "pos": "n./adj."},
    "cascade": {"def": "小瀑布、串聯、噴湧、如瀑布般落下、串聯、傾瀉、瀑布狀的", "ipa": "/kæsˈkeɪd/", "trans": "cascading", "col": "cascade of events", "ex": "The water cascaded down the mountain side.", "pos": "n./v./adj."},
    "case": {"def": "案件、病例、箱子、事實、情形、裝入箱中、事入、包圍", "ipa": "/keɪs/", "trans": "casing", "col": "in case of, lower case, upper case", "ex": "In case of fire, use the emergency exit.", "pos": "n./v."},
    "cash": {"def": "現金、錢、現款、兌現、付現款、現款的", "ipa": "/kæʃ/", "trans": "cashed, cashing", "col": "cash on delivery (COD), cash flow", "ex": "I don't have any cash on me.", "pos": "n./v./adj."},
    "cashier": {"def": "出納員、收銀員、撤職、開除、丟棄", "ipa": "/kæˈʃɪə/", "trans": "cashiers", "col": "supermarket cashier", "ex": "The cashier gave me the wrong change.", "pos": "n./v."},
    "casino": {"def": "賭場、俱樂部", "ipa": "/kəˈsiːnəʊ/", "trans": "casinos", "col": "online casino", "ex": "He lost a lot of money at the casino.", "pos": "n."},
    "cask": {"def": "桶、酒桶、一桶之量、裝入桶中", "ipa": "/kɑːsk/", "trans": "casks", "col": "oak cask", "ex": "The wine is aged in oak casks.", "pos": "n./v."},
    "casket": {"def": "小箱、珠寶盒、棺材、裝入小箱中", "ipa": "/ˈkːskɪt/", "trans": "caskets", "col": "silver casket", "ex": "She kept her jewels in a small silver casket.", "pos": "n./v."},
    "cassette": {"def": "卡式磁碟、暗盒", "ipa": "/kəˈset/", "trans": "cassettes", "col": "audio cassette, video cassette", "ex": "I found some old audio cassettes in the attic.", "pos": "n."},
    "cast": {"def": "演員陣容、鑄件、投、擲、投影、鑄造、脫落、描述、拋出的、鑄造的", "ipa": "/kɑːst/", "trans": "casting", "col": "cast a vote, cast a shadow", "ex": "The trees cast long shadows on the ground.", "pos": "n./v./adj."},
    "caste": {"def": "種姓(制度)、階級", "ipa": "/kɑːst/", "trans": "castes", "col": "caste system", "ex": "The caste system is still prevalent in some parts of the world.", "pos": "n."},
    "castle": {"def": "城堡、豪宅、(西洋棋)礮、置於城堡中、(西洋棋)入堡", "ipa": "/ˈkɑːsl/", "trans": "castling", "col": "sand castle, medieval castle", "ex": "The children built a sand castle on the beach.", "pos": "n./v."},
    "casual": {"def": "偶然的、隨便的、臨時的、漫不經心的、臨時工、便裝、意外地、隨便地", "ipa": "/ˈkæʒuəl/", "trans": "casually, casualty", "col": "casual wear, casual acquaintance", "ex": "He was wearing casual clothes for the party.", "pos": "adj./n./adv."},
    "casually": {"def": "偶然地、隨便地、臨時地", "ipa": "/ˈkæʒuəli/", "trans": "casual (形容詞/名詞/副詞)", "col": "dress casually", "ex": "She was dressed casually in jeans and a T-shirt.", "pos": "adv."},
    "casualty": {"def": "傷亡人員、意外、急診室", "ipa": "/ˈkæʒuəlti/", "trans": "casual (形容詞/名詞/副詞/副詞)", "col": "heavy casualties", "ex": "There were heavy casualties on both sides during the war.", "pos": "n."},
    "cat": {"def": "貓、貓科動物、惡毒的人、毆打、裝入貓袋中", "ipa": "/kæt/", "trans": "cats, catty", "col": "fat cat, copy cat", "ex": "The cat is sleeping on the sofa.", "pos": "n./v."},
    "catalog/catalogue": {"def": "目錄、一連串的事、登記、編入目錄、把...分類", "ipa": "/ˈkætəlɒɡ/", "trans": "cataloging", "col": "library catalog, mail-order catalog", "ex": "I searched for the book in the library catalog.", "pos": "n./v."},
    "catalyst": {"def": "催化劑、啟發因素", "ipa": "/ˈkætəlɪst/", "trans": "catalysis", "col": "act as a catalyst", "ex": "The new law acted as a catalyst for reform.", "pos": "n."},
    "catastrophe": {"def": "大災難、慘敗、結尾", "ipa": "/kəˈtæstrəfi/", "trans": "catastrophic", "col": "environmental catastrophe", "ex": "The earthquake was a major catastrophe for the region.", "pos": "n."},
    "catastrophic": {"def": "災難性的、慘重的", "ipa": "/ˌkætəˈstrɒfɪk/", "trans": "catastrophe (名詞)", "col": "catastrophic failure", "ex": "The company suffered a catastrophic failure in its computer system.", "pos": "adj."},
    "catch": {"def": "捕捉、捕獲量、陷阱、捉、趕上、理解、領會、感染、捕獲地、捉摸不定地", "ipa": "/kætʃ/", "trans": "catching, catchy", "col": "catch up with, catch fire, eye-catching", "ex": "Try to catch the ball.", "pos": "n./v./adv."},
    "catching": {"def": "傳染性的、有魅力的", "ipa": "/ˈkætʃɪŋ/", "trans": "catch (名詞/動詞/副詞), catchy", "col": "catching laughter", "ex": "Her laughter was very catching.", "pos": "adj."},
    "catchy": {"def": "動聽易記的、詭詐的、斷斷續續的", "ipa": "/ˈkætʃi/", "trans": "catch (名詞/動詞/副詞), catching", "col": "catchy tune", "ex": "The song has a very catchy tune.", "pos": "adj."},
    "categorical": {"def": "絕對的、明確的、類別的", "ipa": "/ˌkætəˈɡɒrɪkl/", "trans": "category, categorize", "col": "categorical denial", "ex": "He issued a categorical denial of the allegations.", "pos": "adj."},
    "category": {"def": "類別、範疇", "ipa": "/ˈkætəɡəri/", "trans": "categorize, categorical", "col": "major category", "ex": "The books are divided into several major categories.", "pos": "n."},
    "cater": {"def": "迎合、提供飲食、投合", "ipa": "/ˈkeɪtə/", "trans": "catering, caterer", "col": "cater for, cater to", "ex": "The hotel caters for weddings and parties.", "pos": "v."},
    "caterer": {"def": "酒席承辦者、餐飲服務商", "ipa": "/ˈkeɪtərə/", "trans": "cater (動詞), catering", "col": "official caterer", "ex": "We hired an official caterer for the event.", "pos": "n."},
    "pillar": {"def": "柱子、棟樑、支柱、用柱子支承", "ipa": "/ˈpɪlə/", "trans": "pillars", "col": "pillar of society", "ex": "He is a pillar of the local community.", "pos": "n./v."},
    "mortality": {"def": "死亡率、必死性、人類", "ipa": "/mɔːˈtæləti/", "trans": "mortal", "col": "infant mortality", "ex": "The infant mortality rate is decreasing.", "pos": "n."},
    "moan": {"def": "呻吟、哀嘆、呻吟聲、發出呻吟聲、抱怨、哀悼", "ipa": "/məʊn/", "trans": "moaning", "col": "moan and groan", "ex": "He started to moan with pain.", "pos": "n./v."},
    "opposition": {"def": "反對、對手、在野黨", "ipa": "/ˌɒpəˈzɪʃn/", "trans": "oppose", "col": "strong opposition", "ex": "The plan met with strong opposition from the residents.", "pos": "n."},
    "petition": {"def": "請願、請願書、訴狀、向...請願、祈求", "ipa": "/pəˈtɪʃn/", "trans": "petitioner", "col": "sign a petition", "ex": "The students signed a petition to protest against the fee increase.", "pos": "n./v."},
    "mock": {"def": "嘲笑、模仿、嘲弄、偽造的、模擬的、模擬考試、嘲弄、嘲笑、虛假地、嘲弄地", "ipa": "/mɒk/", "trans": "mockery", "col": "mock exam, mock trial", "ex": "They made a mock trial for the project.", "pos": "n./v./adj./adv."},
    "opt": {"def": "選擇、挑選", "ipa": "/ɒpt/", "trans": "option, optional", "col": "opt for, opt out", "ex": "Most people opt for the cheaper version.", "pos": "v."},
    "petty": {"def": "瑣碎的、小規模的、心胸狹窄的", "ipa": "/ˈpeti/", "trans": "pettiness", "col": "petty crime, petty cash", "ex": "Don't worry about such petty details.", "pos": "adj."},
    "mode": {"def": "模式、方式、風格、時尚", "ipa": "/məʊd/", "trans": "modal", "col": "silent mode, transport mode", "ex": "The phone is in silent mode.", "pos": "n."},
    "optimism": {"def": "樂觀主義、樂觀", "ipa": "/ˈɒptɪmɪzəm/", "trans": "optimist, optimistic", "col": "cautious optimism", "ex": "There is a feeling of cautious optimism about the economy.", "pos": "n."},
    "phase": {"def": "階段、時期、相、實施、分階段進行、調整相位", "ipa": "/feɪz/", "trans": "phased", "col": "phase out, final phase", "ex": "The project is now in its final phase.", "pos": "n./v."},
    "modify": {"def": "修改、更正、修飾", "ipa": "/ˈmɒdɪfaɪ/", "trans": "modification, modifier", "col": "modify a plan", "ex": "We need to modify the original plan.", "pos": "v."},
    "optional": {"def": "可選擇的、非強制的", "ipa": "/ˈɒpʃənl/", "trans": "option, opt", "col": "optional extra", "ex": "The course is optional for all students.", "pos": "adj."},
    "photographic": {"def": "攝影的、細緻的、影像的", "ipa": "/ˌfəʊtəˈɡræfɪk/", "trans": "photography, photograph", "col": "photographic memory", "ex": "He has a photographic memory.", "pos": "adj."},
    "molecule": {"def": "分子、微小顆粒", "ipa": "/ˈmɒlɪkjuːl/", "trans": "molecular", "col": "water molecule", "ex": "A water molecule consists of two hydrogen atoms and one oxygen atom.", "pos": "n."},
    "orchard": {"def": "果園", "ipa": "/ˈɔːtʃəd/", "trans": "orchards", "col": "apple orchard", "ex": "The apple orchard was full of ripe fruit.", "pos": "n."},
    "pickup": {"def": "接送、拾起、整理、皮卡車、傳聲器", "ipa": "/ˈpɪkʌp/", "trans": "pick (動詞)", "col": "airport pickup, pickup truck", "ex": "They arranged an airport pickup for the guests.", "pos": "n."},
}

with open("batch_l5_p11.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART11, f, ensure_ascii=False, indent=2)
