import json

# Level 6 Part 8: (Anthropology - Apathetic)
L6_PART8 = {
    "anthropology": {"def": "人類學", "ipa": "/ˌænθrəˈpɒlədʒi/", "trans": "anthropologist", "col": "cultural anthropology, social anthropology", "ex": "She is interested in cultural anthropology.", "pos": "n."},
    "antibiotic": {"def": "抗生素、抗生的、抗菌的", "ipa": "/ˌæntibaɪˈɒtɪk/", "trans": "antibiotics", "col": "course of antibiotics", "ex": "The doctor prescribed a course of antibiotics for the infection.", "pos": "n./adj."},
    "antibody": {"def": "抗體", "ipa": "/ˈæntibɒdi/", "trans": "antibodies", "col": "antibody test, specific antibody", "ex": "Antibodies help the body to fight off infections.", "pos": "n."},
    "antic": {"def": "滑稽可笑的、古怪的、古怪滑稽的人 (或動作)、古怪滑稽地 (滑稽)", "ipa": "/ˈæntɪk/", "trans": "antics", "col": "clown's antics", "ex": "The monkey's antics amused the children.", "pos": "adj./n./adv."},
    "anticipate": {"def": "預料、預期、先發制人、預先處理", "ipa": "/ænˈtɪsɪpeɪt/", "trans": "anticipation, anticipatory", "col": "anticipate problems, eagerly anticipated", "ex": "We anticipate that sales will rise next year.", "pos": "v."},
    "anticipation": {"def": "預期、期待、先發制人、期望的人 (或事)", "ipa": "/ænˌtɪsɪˈpeɪʃn/", "trans": "anticipate (動詞), anticipatory", "col": "in anticipation of, keen anticipation", "ex": "They held their breath in anticipation of the result.", "pos": "n."},
    "anticipatory": {"def": "預期的、預料之中的、先行的", "ipa": "/ænˈtɪsɪpətəri/", "trans": "anticipation, anticipate", "col": "anticipatory breach", "ex": "The anticipatory excitement was palpable in the room.", "pos": "adj."},
    "anticlimax": {"def": "令人掃興的結局、突降法、落差", "ipa": "/ˌæntiˈklaɪmæks/", "trans": "disappointment", "col": "bit of an anticlimax", "ex": "The end of the movie was a bit of an anticlimax.", "pos": "n."},
    "antidote": {"def": "解毒劑、對策、對抗手段", "ipa": "/ˈæntidəʊt/", "trans": "antidotes", "col": "universal antidote, effective antidote", "ex": "Love is said to be the best antidote for hate.", "pos": "n."},
    "antifreeze": {"def": "防凍劑、抗凍劑", "ipa": "/ˈæntifriːz/", "trans": "coolant", "col": "add antifreeze", "ex": "Remember to add antifreeze to the car radiator in winter.", "pos": "n."},
    "antigen": {"def": "抗原", "ipa": "/ˈæntɪdʒən/", "trans": "antigens", "col": "specific antigen", "ex": "An antigen triggers an immune response in the body.", "pos": "n."},
    "antipathy": {"def": "反感、厭惡、憎惡", "ipa": "/ænˈtɪpəθi/", "trans": "aversion", "col": "strong antipathy", "ex": "He has a strong antipathy towards modern music.", "pos": "n."},
    "antiquarian": {"def": "古文物研究的、古籍的、古文物家、古玩商", "ipa": "/ˌæntɪˈkweəriən/", "trans": "antiquary", "col": "antiquarian bookshop", "ex": "He works in an antiquarian bookshop.", "pos": "adj./n."},
    "antiquated": {"def": "陳舊的、過時的、老式的", "ipa": "/ˈæntɪkweɪtɪd/", "trans": "antique", "col": "antiquated system", "ex": "The company is still using an antiquated filing system.", "pos": "adj."},
    "antique": {"def": "古董、古物、古風、古老的、古董的、使顯古色、古色古香地 (古董)", "ipa": "/ænˈtiːk/", "trans": "antiqueness", "col": "antique furniture, antique shop", "ex": "She collects antique furniture.", "pos": "n./adj./v./adv."},
    "antiquity": {"def": "古代、古老、古羅馬 (或希臘) 之遺物", "ipa": "/ænˈtɪkwəti/", "trans": "antique", "col": "classical antiquity", "ex": "The museum has a large collection of artifacts from classical antiquity.", "pos": "n."},
    "antiseptic": {"def": "防腐劑、消毒劑、防腐的、消毒的、冷淡的、冷淡地 (防腐)", "ipa": "/ˌæntiˈseptɪk/", "trans": "sterile", "col": "antiseptic cream, antiseptic properties", "ex": "This plant has natural antiseptic properties.", "pos": "n./adj./adv."},
    "antisocial": {"def": "反社會的、不善社交的、反常的", "ipa": "/ˌæntiˈsəʊʃl/", "trans": "social", "col": "antisocial behavior, purely antisocial", "ex": "The police are trying to crack down on antisocial behavior.", "pos": "adj."},
    "antithesis": {"def": "對立、對立面、(修)對照、對襯的人 (或物)", "ipa": "/ænˈtɪθəsɪs/", "trans": "opposites", "col": "direct antithesis", "ex": "His behavior is the direct antithesis of his words.", "pos": "n."},
    "antithetic/antithetical": {"def": "正相反的、對立的", "ipa": "/ˌæntɪˈθetɪk/", "trans": "antithesis", "col": "antithetical views", "ex": "Their views on the matter are completely antithetical.", "pos": "adj."},
    "antonym": {"def": "反義詞", "ipa": "/ˈæntənɪm/", "trans": "antonyms", "col": "provide an antonym", "ex": "Cruel is the antonym of kind.", "pos": "n."},
    "anvil": {"def": "鐵砧、(解)砧骨", "ipa": "/ˈænvɪl/", "trans": "anvils", "col": "blacksmith's anvil", "ex": "The blacksmith struck the red-hot iron on the anvil.", "pos": "n."},
    "anxiety": {"def": "焦慮、不安、掛慮、渴望", "ipa": "/æŋˈzaɪəti/", "trans": "anxious, anxiously", "col": "separation anxiety, deep anxiety", "ex": "He was filled with anxiety about the exam result.", "pos": "n."},
    "anxious": {"def": "焦慮的、擔心的、渴望的、焦急地、渴望地 (焦慮)", "ipa": "/ˈæŋkʃəs/", "trans": "anxiety, anxiously", "col": "anxious about, anxious for, anxious wait", "ex": "She was anxious about her mother's health.", "pos": "adj./adv."},
    "anxiously": {"def": "焦慮地、焦急地、渴望地", "ipa": "/ˈæŋkʃəsli/", "trans": "anxious (形容詞/副詞), anxiety", "col": "wait anxiously", "ex": "They waited anxiously for news of the missing child.", "pos": "adv."},
    "any": {"def": "任何的、一些、隨便哪一個、任何一個、一些、隨便哪一回地、一點也 (任何)", "ipa": "/ˈeni/", "trans": "some", "col": "any more, at any rate, in any case", "ex": "Are there any messages for me?", "pos": "adj./pron./adv."},
    "anybody/anyone": {"def": "任何人、隨便哪個人、重要人物、任何地、隨便地 (任何人)", "ipa": "/ˈenibɒdi/", "trans": "someone", "col": "anybody else, anybody at all", "ex": "Is anyone there?", "pos": "pron./n./adv."},
    "anyhow": {"def": "總之、無論如何、隨隨便便地", "ipa": "/ˈenhaʊ/", "trans": "anyway", "col": "do it anyhow", "ex": "It's late, but I'll go anyhow.", "pos": "adv."},
    "anymore": {"def": "不再、再也不、以後 (不再)", "ipa": "/ˌeniˈmɔː/", "trans": "any longer", "col": "don't want any more", "ex": "I don't live there anymore.", "pos": "adv."},
    "anyone": {"def": "任何人、誰 (任何人)", "ipa": "/ˈeniwʌn/", "trans": "anybody", "col": "anyone else, anyone home", "ex": "Anyone can join the club.", "pos": "pron."},
    "anything": {"def": "任何事物、不管什麼、隨便什麼地、任何地 (任何)", "ipa": "/ˈeniθɪŋ/", "trans": "something", "col": "anything else, anything but (絕不)", "ex": "Is there anything you want to say?", "pos": "pron./adv."},
    "anyway": {"def": "總之、無論如何、不管怎樣地 (總之)", "ipa": "/ˈeniweɪ/", "trans": "anyhow", "col": "anyway, it's true", "ex": "I'll do it anyway, even if you object.", "pos": "adv."},
    "anywhere": {"def": "任何地方、處處、隨便哪裡地、到處地 (任何地方)", "ipa": "/ˈeniweə/", "trans": "somewhere", "col": "anywhere else, anywhere near", "ex": "I can't find my keys anywhere.", "pos": "adv./n."},
    "apace": {"def": "快速地、急速地", "ipa": "/əˈpeɪs/", "trans": "quickly", "col": "grow apace", "ex": "Work on the new bridge is progressing apace.", "pos": "adv."},
    "apart": {"def": "分開的、分離的、獨特的、分開地、分離地、除了地 (分開)", "ipa": "/əˈpɑːt/", "trans": "separated", "col": "apart from, fall apart, set apart", "ex": "The two houses are 100 meters apart.", "pos": "adj./adv."},
    "apartment": {"def": "公寓、房間、一組房間", "ipa": "/əˈpɑːtmənt/", "trans": "flat", "col": "luxury apartment, apartment block", "ex": "They live in a small apartment in the city.", "pos": "n."},
    "apathetic": {"def": "冷淡的、無動於衷的、缺乏熱情的", "ipa": "/ˌæpəˈθetɪk/", "trans": "apathy", "col": "apathetic attitude", "ex": "She felt apathetic towards the whole thing.", "pos": "adj."},
}