import json

# Level 6 Part 26: (Beaten - Bedrock)
L6_PART26 = {
    "beaten": {"def": "被打敗的、精疲力竭的、敲平的、(路)踩出來的", "ipa": "/ˈbiːtn/", "trans": "beat (動詞/名詞/副詞)", "col": "off the beaten track (人跡罕至), badly beaten", "ex": "They suffered a badly beaten defeat.", "pos": "adj."},
    "beater": {"def": "打擊者、攪拌器、(獵)趕鳥者", "ipa": "/ˈbiːtə/", "trans": "beat (動詞/名詞/副詞)", "col": "egg beater", "ex": "She used an egg beater to mix the ingredients.", "pos": "n."},
    "beating": {"def": "打、跳動、嚴厲挫敗、敲擊的人物、打擊地 (打)", "ipa": "/ˈbiːtɪŋ/", "trans": "beat (動詞/名詞/副詞)", "col": "take a beating, give a beating", "ex": "His heart gave a loud beating.", "pos": "n./adv."},
    "beatitude": {"def": "至福、神聖、(天主教)宣福 (常作複數)", "ipa": "/biˈætɪtjuːd/", "trans": "bliss", "col": "The Beatitudes (登山寶訓)", "ex": "She lived in a state of beatitude.", "pos": "n."},
    "beauteous": {"def": "美麗的、優美的", "ipa": "/ˈbjuːtiəs/", "trans": "beautiful", "col": "beauteous lady", "ex": "She was a beauteous lady in her youth.", "pos": "adj."},
    "beautician": {"def": "美容師", "ipa": "/bjuːˈtɪʃn/", "trans": "beauty therapist", "col": "qualified beautician", "ex": "She works as a qualified beautician in a salon.", "pos": "n."},
    "beautiful": {"def": "美麗的、優美的、極好的、美地、優美地 (美)", "ipa": "/ˈbjuːtɪfl/", "trans": "beautifully, beauty", "col": "beautiful sunset, beautiful daughter, looks beautiful", "ex": "What a beautiful day!", "pos": "adj./adv."},
    "beautifully": {"def": "美麗地、優美地、出色地", "ipa": "/ˈbjuːtɪfli/", "trans": "beautiful (形容詞/副詞), beauty", "col": "beautifully dressed, beautifully written", "ex": "She was beautifully dressed for the party.", "pos": "adv."},
    "beautify": {"def": "美化、裝飾、變美、美化的人 (或物)、美化地 (美化)", "ipa": "/ˈbjuːtɪfaɪ/", "trans": "beauty", "col": "beautify the environment", "ex": "The city has launched a project to beautify the environment.", "pos": "v./n./adv."},
    "beauty": {"def": "美麗、美人、美的事物、優點、美好的、美的、美地 (美)", "ipa": "/ˈbjuːti/", "trans": "beauties", "col": "beauty salon, sleeping beauty, thing of beauty, black beauty", "ex": "She is a woman of great beauty.", "pos": "n./adj./adv."},
    "beaver": {"def": "海狸、河狸、海狸皮、(口)勤奮工作的人、勤奮工作、工作的人物、勤奮地 (海狸)", "ipa": "/ˈbiːvə/", "trans": "beavers", "col": "eager beaver (工作勤奮的人), beaver away (埋頭苦幹)", "ex": "He has been beavering away at his desk all day.", "pos": "n./v./adv."},
    "becalm": {"def": "使平靜、使(船)因無風而停泊", "ipa": "/bɪˈkɑːm/", "trans": "calm", "col": "becalmed at sea", "ex": "The yacht was becalmed at sea for two days.", "pos": "v."},
    "became": {"def": "(become的過去式)、變成了", "ipa": "/bɪˈkeɪm/", "trans": "become", "col": "became famous", "ex": "He became famous after his first movie.", "pos": "v."},
    "because": {"def": "因為、由於地 (因為)", "ipa": "/bɪˈkɒz/", "trans": "as", "col": "because of, just because", "ex": "I stayed home because I was sick.", "pos": "conj./adv."},
    "beckon": {"def": "招手、示意、吸引、招手的人 (或物)、示意地 (招手)", "ipa": "/ˈbekən/", "trans": "beckons", "col": "beckon someone over", "ex": "She beckoned him over with a wave of her hand.", "pos": "v./n./adv."},
    "become": {"def": "變成、成為、變得、適合、相稱、適合的人物、相稱地 (變)", "ipa": "/bɪˈkʌm/", "trans": "becoming, became", "col": "become a teacher, become ill", "ex": "It's becoming very cold.", "pos": "v./n./adv."},
    "becoming": {"def": "合適的、相稱的、生成、變得地", "ipa": "/bɪˈkʌmɪŋ/", "trans": "become (動詞/名詞/副詞)", "col": "becoming dress", "ex": "That hat is very becoming on you.", "pos": "adj./n./adv."},
    "bed": {"def": "床、河床、苗床、底層、安放、睡在床上、床上的、床狀的、床上地 (床)", "ipa": "/bed/", "trans": "beds", "col": "single bed, double bed, flower bed, river bed, go to bed", "ex": "I'm tired and I'm going to bed.", "pos": "n./v./adj./adv."},
    "bedaub": {"def": "亂塗、塗抹、胡亂裝飾", "ipa": "/bɪˈdɔːb/", "trans": "smear", "col": "bedaub with paint", "ex": "The wall was bedaubed with paint.", "pos": "v."},
    "bedazzle": {"def": "使迷惑、使眼花、使著迷", "ipa": "/bɪˈdæzl/", "trans": "dazzle", "col": "bedazzle by", "ex": "She was bedazzled by the bright lights of the city.", "pos": "v."},
    "bedbug": {"def": "臭蟲", "ipa": "/ˈbedbʌɡ/", "trans": "insect", "col": "bedbug infestation", "ex": "The hotel was closed due to a bedbug infestation.", "pos": "n."},
    "bedding": {"def": "寢具、底部、地層、墊料、墊料的人物、墊料地 (寢)", "ipa": "/ˈbedɪŋ/", "trans": "bed (名詞/動詞/形容詞/副詞)", "col": "clean bedding, animal bedding", "ex": "They provide clean bedding for the guests.", "pos": "n./adv."},
    "bedeck": {"def": "裝飾、修飾", "ipa": "/bɪˈdek/", "trans": "adorn", "col": "bedeck with flowers", "ex": "The room was bedecked with fresh flowers.", "pos": "v."},
    "bedevil": {"def": "折磨、煩擾、使混亂", "ipa": "/bɪˈdevl/", "trans": "torment", "col": "bedevil by problems", "ex": "The project was bedevilled by technical problems.", "pos": "v."},
    "bedew": {"def": "露水般的濕潤、露水滴下 (單數)", "ipa": "/bɪˈdjuː/", "trans": "moisten", "col": "bedewed with tears", "ex": "Her eyes were bedewed with tears.", "pos": "v."},
    "bedfellow": {"def": "同床者、盟友 (常指暫時的)", "ipa": "/ˈbedfeləʊ/", "trans": "partner", "col": "strange bedfellows (奇怪的組合)", "ex": "Politics makes strange bedfellows.", "pos": "n."},
    "bedizen": {"def": "過分裝飾、俗氣地打扮", "ipa": "/bɪˈdaɪzn/", "trans": "deck out", "col": "bedizened queen", "ex": "She arrived bedizened in expensive jewelry.", "pos": "v."},
    "bedlam": {"def": "瘋人院、大混亂、吵鬧的地方", "ipa": "/ˈbedləm/", "trans": "chaos", "col": "sheer bedlam", "ex": "It was sheer bedlam in the store during the sale.", "pos": "n."},
    "bedouin": {"def": "貝都因人、流浪者 (單數)", "ipa": "/ˈbeduɪn/", "trans": "nomad", "col": "bedouin tent", "ex": "The bedouin nomad traveled across the desert.", "pos": "n."},
    "bedraggled": {"def": "破舊的、滿地污泥的、凌亂的", "ipa": "/bɪˈdræɡld/", "trans": "disheveled", "col": "bedraggled bird", "ex": "A bedraggled little bird was sitting in the rain.", "pos": "adj."},
    "bedridden": {"def": "臥床不起的、長年臥床的", "ipa": "/ˈbedrɪdn/", "trans": "confined to bed", "col": "bedridden patient", "ex": "She has been bedridden for three years.", "pos": "adj."},
    "bedrock": {"def": "床岩、根基、基本原則地 (根基)", "ipa": "/ˈbedrɒk/", "trans": "foundation", "col": "hit bedrock (降到底部/觸到核心)", "ex": "Trust is the bedrock of a good relationship.", "pos": "n./adv."},
}