import json

# Level 3 Part 11: (Course - Debt)
L3_PART11 = {
    "course": {"def": "課程、進程、航路、一道菜", "ipa": "/kɔːs/", "trans": "courses", "col": "take a course, of course, in due course", "ex": "He is taking a management course.", "pos": "n."},
    "courtesy": {"def": "禮貌、謙恭、好意", "ipa": "/ˈkɜːtəsi/", "trans": "courteous", "col": "by courtesy of, common courtesy", "ex": "It's common courtesy to say thank you.", "pos": "n."},
    "courtyard": {"def": "庭院、天井", "ipa": "/ˈkɔːt jɑːd/", "trans": "courtyards", "col": "inner courtyard", "ex": "The hotel has a beautiful inner courtyard.", "pos": "n."},
    "cousin": {"def": "堂、表兄弟姊妹", "ipa": "/ˈkʌzn/", "trans": "cousins", "col": "first cousin", "ex": "She is my favorite cousin.", "pos": "n."},
    "cover": {"def": "覆蓋、涵蓋、掩護、蓋子、封面、掩護物", "ipa": "/ˈkʌvə/", "trans": "coverage, covering", "col": "under cover, cover up, front cover", "ex": "Snow covered the ground.", "pos": "v./n."},
    "coverage": {"def": "新聞報導、報導範圍、保險範圍", "ipa": "/ˈkʌvərɪdʒ/", "trans": "cover (動詞)", "col": "media coverage, insurance coverage", "ex": "There was extensive media coverage of the event.", "pos": "n."},
    "cow": {"def": "母牛、乳牛", "ipa": "/kaʊ/", "trans": "cows", "col": "dairy cow, milk a cow", "ex": "Farmers are milking the cows.", "pos": "n."},
    "coward": {"def": "懦夫、膽怯者", "ipa": "/ˈkaʊəd/", "trans": "cowardice, cowardly", "col": "moral coward", "ex": "He is a coward; he won't tell the truth.", "pos": "n."},
    "cowboy": {"def": "牛仔、牧牛人", "ipa": "/ˈkaʊbɔɪ/", "trans": "cowboys", "col": "American cowboy", "ex": "Cowboys worked on cattle ranches.", "pos": "n."},
    "crab": {"def": "螃蟹、蟹肉", "ipa": "/kræb/", "trans": "crabs", "col": "crab meat", "ex": "We had crab for dinner.", "pos": "n."},
    "crack": {"def": "裂縫、爆裂聲、破裂、使爆裂、打擊", "ipa": "/kræk/", "trans": "cracker, cracked", "col": "crack a joke, crack down on", "ex": "The mirror cracked when it fell.", "pos": "n./v."},
    "cradle": {"def": "搖籃、發源地、將...放在搖籃裡、撫育", "ipa": "/ˈkreɪdl/", "trans": "cradled", "col": "from the cradle to the grave", "ex": "She rocked the baby in its cradle.", "pos": "n./v."},
    "craft": {"def": "工藝、技巧、船、飛機、手工製作", "ipa": "/krɑːft/", "trans": "craftsman, crafty", "col": "arts and crafts, spacecraft", "ex": "She is skilled in the craft of weaving.", "pos": "n./v."},
    "cram": {"def": "死記硬背、塞滿、塞進", "ipa": "/kræm/", "trans": "cramming", "col": "cram for an exam", "ex": "He's been cramming for his history exam all week.", "pos": "v."},
    "crane": {"def": "起重機、鶴、伸長脖子、用起重機吊", "ipa": "/kreɪn/", "trans": "cranes", "col": "crane one's neck", "ex": "A giant crane lifted the heavy crates.", "pos": "n./v."},
    "crash": {"def": "碰撞、墜毀、(電腦)當機、毀滅、撞擊聲", "ipa": "/kræʃ/", "trans": "crashing", "col": "car crash, plane crash, computer crash", "ex": "The car crashed into a tree.", "pos": "v./n."},
    "crawl": {"def": "爬行、緩慢移動、緩慢的進行、爬泳", "ipa": "/krɔːl/", "trans": "crawler", "col": "crawl along", "ex": "The baby is learning to crawl.", "pos": "v./n."},
    "crayon": {"def": "蠟筆、用蠟筆畫", "ipa": "/ˈkreɪən/", "trans": "crayons", "col": "box of crayons", "ex": "The child is drawing with a crayon.", "pos": "n./v."},
    "crazy": {"def": "瘋狂的、著迷的、愚蠢的", "ipa": "/ˈkreɪzi/", "trans": "crazily, craziness", "col": "go crazy, crazy about", "ex": "Are you crazy? You can't jump from there!", "pos": "adj."},
    "cream": {"def": "鮮奶油、奶油色的、最精華的部分、奶油色的", "ipa": "/kriːm/", "trans": "creamy", "col": "ice cream, whipped cream, shaving cream", "ex": "I like cream in my coffee.", "pos": "n./adj."},
    "create": {"def": "創造、造成、產出", "ipa": "/kriˈeɪt/", "trans": "creation, creative", "col": "create opportunities", "ex": "The government is trying to create more jobs.", "pos": "v."},
    "creation": {"def": "創造、創作物、天地的萬物", "ipa": "/kriˈeɪʃn/", "trans": "create (動詞), creator", "col": "artistic creation", "ex": "The dress was her own creation.", "pos": "n."},
    "creative": {"def": "有創造力的、創發性的", "ipa": "/kriˈeɪtɪv/", "trans": "create (動詞), creativity", "col": "creative thinking, creative writing", "ex": "She is a very creative person.", "pos": "adj."},
    "creativity": {"def": "創造力、創造性", "ipa": "/ˌkriːeɪˈtɪvəti/", "trans": "creative (形容詞)", "col": "foster creativity", "ex": "The school aims to encourage creativity in its students.", "pos": "n."},
    "creator": {"def": "創造者、創作者、造物主", "ipa": "/kriˈeɪtə/", "trans": "create (動詞)", "col": "content creator", "ex": "Steven Spielberg is the creator of many famous films.", "pos": "n."},
    "creature": {"def": "生物、動物、人", "ipa": "/ˈkriːtʃə/", "trans": "creatures", "col": "strange creature, sea creature", "ex": "The forest is home to many strange creatures.", "pos": "n."},
    "credibility": {"def": "可信性、可靠性", "ipa": "/ˌkredəˈbɪləti/", "trans": "credible", "col": "lose credibility, gain credibility", "ex": "The scandal has damaged his credibility as a politician.", "pos": "n."},
    "credible": {"def": "可信的、可靠的", "ipa": "/ˈkredəbl/", "trans": "credibility (名詞)", "col": "credible explanation, credible witness", "ex": "The story doesn't seem very credible to me.", "pos": "adj."},
    "credit": {"def": "信用、學分、榮譽、賒帳、相信、歸功於", "ipa": "/ˈkredɪt/", "trans": "creditable, creditor", "col": "credit card, on credit, give credit to", "ex": "I don't have enough credit on my phone.", "pos": "n./v."},
    "creed": {"def": "教義、信條、主義", "ipa": "/kriːd/", "trans": "creeds", "col": "political creed", "ex": "People of all creeds live together in this country.", "pos": "n."},
    "creep": {"def": "躡手躡腳地走、爬行、令人毛骨悚然的人", "ipa": "/kriːp/", "trans": "creepy", "col": "creep in, give someone the creeps", "ex": "I saw someone creeping around in the garden.", "pos": "v./n."},
    "crew": {"def": "全體工作人員、隊、組、當船員", "ipa": "/kruː/", "trans": "crews", "col": "cabin crew, film crew, rowing crew", "ex": "The crew of the ship worked hard to stay on course.", "pos": "n./v."},
    "cricket": {"def": "蟋蟀、板球", "ipa": "/ˈkrɪkɪt/", "trans": "cricketer", "col": "play cricket, the sound of crickets", "ex": "Cricket is a very popular sport in England.", "pos": "n."},
    "crime": {"def": "犯罪、罪行", "ipa": "/kraɪm/", "trans": "criminal", "col": "commit a crime, organized crime, fight crime", "ex": "He was accused of a serious crime.", "pos": "n."},
    "criminal": {"def": "犯罪的、刑事的、犯人、罪犯", "ipa": "/ˈkrɪmɪnl/", "trans": "crime (名詞)", "col": "criminal record, criminal law", "ex": "The police are hunting for the criminal.", "pos": "adj./n."},
    "crisis": {"def": "危機、緊要關頭", "ipa": "/ˈkraɪsɪs/", "trans": "crises (複數)", "col": "economic crisis, financial crisis, world crisis", "ex": "The country is facing a major economic crisis.", "pos": "n."},
    "crisp": {"def": "鬆脆的、清爽的、薯片、使脆", "ipa": "/krɪsp/", "trans": "crispy", "col": "crisp air, potato crisp", "ex": "I like crisp apples.", "pos": "adj./n./v."},
    "criterion": {"def": "標準、準則", "ipa": "/kraɪˈtɪəriən/", "trans": "criteria (複數)", "col": "selection criteria, strict criteria", "ex": "What are the criteria for success in this job?", "pos": "n."},
    "critic": {"def": "評論家、批評者", "ipa": "/ˈkrɪtɪk/", "trans": "criticism, criticize", "col": "art critic, film critic, harsh critic", "ex": "He is a sharp critic of the government's policy.", "pos": "n."},
    "critical": {"def": "批評的、關鍵的、病危的", "ipa": "/ˈkrɪtɪkl/", "trans": "critic (名詞), critically", "col": "critical thinking, critical condition", "ex": "The patient is still in critical condition.", "pos": "adj."},
    "criticism": {"def": "批評、評論", "ipa": "/ˈkrɪtɪsɪzəm/", "trans": "critic (名詞), criticize", "col": "constructive criticism, harsh criticism", "ex": "I welcome your criticism of my work.", "pos": "n."},
    "criticize": {"def": "批評、評論、苛求", "ipa": "/ˈkrɪtɪsaɪz/", "trans": "criticism, critic", "col": "criticize someone for doing something", "ex": "It's easy to criticize others, but hard to do the work yourself.", "pos": "v."},
    "crop": {"def": "農作物、產量、收穫、收割、剪短", "ipa": "/krɒp/", "trans": "cropped", "col": "cash crop, crop rotation", "ex": "The farmers are planting crops for the next season.", "pos": "n./v."},
    "cross": {"def": "十字架、交叉、混合物、交叉的、憤怒的、越過、穿過、勾劃出", "ipa": "/krɒs/", "trans": "crossing", "col": "cross the street, Red Cross, keep your fingers crossed", "ex": "Be careful when you cross the road.", "pos": "n./adj./v."},
    "crossing": {"def": "交叉口、渡口、橫越", "ipa": "/ˈkrɒsɪŋ/", "trans": "cross (動詞/名詞)", "col": "pedestrian crossing, level crossing", "ex": "The pedestrian crossing is over there.", "pos": "n."},
    "crouch": {"def": "蹲伏、屈身", "ipa": "/kraʊtʃ/", "trans": "crouched", "col": "crouch down", "ex": "The cat crouched low in the grass.", "pos": "v."},
    "crow": {"def": "鴉、啼叫、大聲慶幸、啼叫", "ipa": "/krəʊ/", "trans": "crows", "col": "as the crow flies", "ex": "A crow was sitting on the fence.", "pos": "n./v."},
    "crowd": {"def": "群眾、人群、擠進、擁擠、聚集", "ipa": "/kraʊd/", "trans": "crowded", "col": "crowd into, stand out from the crowd", "ex": "A large crowd gathered to watch the parade.", "pos": "n./v."},
    "crowded": {"def": "擁擠的、滿出的", "ipa": "/ˈkraʊdɪd/", "trans": "crowd (名詞/動詞)", "col": "crowded street, overcrowded", "ex": "The bus was very crowded.", "pos": "adj."},
    "crown": {"def": "皇冠、王權、頂部、為...加冕、居...之頂、圓滿完成", "ipa": "/kraʊn/", "trans": "crowned", "col": "crown jewel", "ex": "The queen wore a beautiful crown.", "pos": "n./v."},
    "crucial": {"def": "決定性的、至關重要的", "ipa": "/ˈkruːʃl/", "trans": "crucially", "col": "crucial factor, crucial role", "ex": "Her advice was crucial to my success.", "pos": "adj."},
    "crude": {"def": "粗糙的、天然的、粗魯的、原油", "ipa": "/kruːd/", "trans": "crudely", "col": "crude oil", "ex": "The crude oil is refined into gasoline.", "pos": "adj./n."},
    "cruel": {"def": "殘忍的、酷毒的", "ipa": "/ˈkruːəl/", "trans": "cruelty", "col": "cruel treatment", "ex": "It's cruel to keep animals in small cages.", "pos": "adj."},
    "cruelty": {"def": "殘忍、殘酷行徑", "ipa": "/ˈkruːəlti/", "trans": "cruel (形容詞)", "col": "animal cruelty", "ex": "The film depicts the cruelty of war.", "pos": "n."},
    "cruise": {"def": "巡航、乘船遊覽、漫遊、巡航、漫遊", "ipa": "/kruːz/", "trans": "cruiser", "col": "cruise ship, go on a cruise", "ex": "They went on a cruise around the Mediterranean.", "pos": "n./v."},
    "crumb": {"def": "碎屑、麵包屑", "ipa": "/krʌm/", "trans": "crumby", "col": "bread crumbs", "ex": "She brushed the crumbs off the table.", "pos": "n."},
    "crumble": {"def": "粉碎、弄碎、崩潰", "ipa": "/ˈkrʌmbl/", "trans": "crumbly", "col": "crumble away", "ex": "The old building is starting to crumble.", "pos": "v."},
    "crunch": {"def": "嘎吱作響地咬、咀嚼、困境、嘎吱聲", "ipa": "/krʌntʃ/", "trans": "crunchy", "col": "credit crunch", "ex": "He likes to crunch on carrots.", "pos": "v./n."},
    "crush": {"def": "壓碎、粉碎、迷戀、擁擠、壓碎声", "ipa": "/krʌʃ/", "trans": "crushing", "col": "have a crush on, crush rice", "ex": "The grapes are crushed to make wine.", "pos": "v./n."},
    "crust": {"def": "餅皮、外殼、地殼、結成硬殼", "ipa": "/krʌst/", "trans": "crusty", "col": "earth's crust, pizza crust", "ex": "The bread has a thick crust.", "pos": "n./v."},
    "crutch": {"def": "拐杖、支撐物", "ipa": "/krʌtʃ/", "trans": "crutches", "col": "walk on crutches", "ex": "He had to use crutches after he broke his leg.", "pos": "n."},
    "cry": {"def": "哭、喊叫、口號、大聲喊叫、哭泣", "ipa": "/kraɪ/", "trans": "crying", "col": "cry for help, cry out", "ex": "The baby is crying because he is hungry.", "pos": "v./n."},
    "crystal": {"def": "水晶、結晶、透明的、水晶般的", "ipa": "/ˈkrɪstl/", "trans": "crystalline", "col": "crystal clear, quartz crystal", "ex": "The water in the lake is crystal clear.", "pos": "n./adj."},
    "cub": {"def": "幼獸（狐狸、熊、獅子等）、幼童軍", "ipa": "/kʌb/", "trans": "cubs", "col": "lion cub, tiger cub", "ex": "The lioness was playing with her cubs.", "pos": "n."},
    "cube": {"def": "立方體、立方、求...的立方、切成小方塊", "ipa": "/kjuːb/", "trans": "cubic", "col": "ice cube, sugar cube, Rubik's cube", "ex": "Put two ice cubes in my glass, please.", "pos": "n./v."},
    "cubic": {"def": "立方的、立方體的", "ipa": "/ˈkjuːbɪk/", "trans": "cube (名詞)", "col": "cubic meter, cubic centimeter", "ex": "The volume of the box is ten cubic meters.", "pos": "adj."},
    "cucumber": {"def": "黃瓜", "ipa": "/ˈkjuːkʌmbə/", "trans": "cucumbers", "col": "cool as a cucumber", "ex": "He remained as cool as a cucumber during the interview.", "pos": "n."},
    "cue": {"def": "提示、暗示、撞球杆、給予暗示", "ipa": "/kjuː/", "trans": "cues", "col": "on cue, take one's cue from", "ex": "He missed his cue and didn't start speaking on time.", "pos": "n./v."},
    "cultivate": {"def": "耕種、培育、養殖、陶冶、與...交往", "ipa": "/ˈkʌltɪveɪt/", "trans": "cultivation", "col": "cultivate habits, cultivate land", "ex": "The land was cultivated for centuries.", "pos": "v."},
    "cultivation": {"def": "耕種、培育、修養", "ipa": "/ˌkʌltɪˈveɪʃn/", "trans": "cultivate (動詞)", "col": "land cultivation", "ex": "The cultivation of rice requires a lot of water.", "pos": "n."},
    "cultural": {"def": "文化的、教養的", "ipa": "/ˈkʌltʃərəl/", "trans": "culture (名詞), culturally", "col": "cultural heritage, cultural exchange", "ex": "The city has a rich cultural heritage.", "pos": "adj."},
    "culture": {"def": "文化、修養、養殖", "ipa": "/ˈkʌltʃə/", "trans": "cultural", "col": "popular culture, corporate culture, social culture", "ex": "He is interested in ancient cultures.", "pos": "n."},
    "cumulative": {"def": "累積的、漸增的", "ipa": "/ˈkjuːmjələtɪv/", "trans": "accumulate", "col": "cumulative effect", "ex": "The cumulative effect of these changes is significant.", "pos": "adj."},
    "cunning": {"def": "狡猾的、奸詐的、狡黠、奸詐", "ipa": "/ˈkʌnɪŋ/", "trans": "cunningly", "col": "cunning plan", "ex": "The fox is a cunning animal.", "pos": "adj./n."},
    "cup": {"def": "杯子、獎盃、使成杯狀、提供杯子", "ipa": "/kʌp/", "trans": "cups", "col": "a cup of coffee, World Cup, cup one's hands", "ex": "Would you like a cup of tea?", "pos": "n./v."},
    "cupboard": {"def": "櫥櫃、壁櫥", "ipa": "/ˈkʌbəd/", "trans": "cupboards", "col": "kitchen cupboard", "ex": "The plates are in the cupboard.", "pos": "n."},
    "curable": {"def": "可治好的、可醫治的", "ipa": "/ˈkjʊərəbl/", "trans": "cure", "col": "curable disease", "ex": "Most types of cancer are curable if detected early.", "pos": "adj."},
    "curator": {"def": "館長、策展人", "ipa": "/kjʊəˈreɪtə/", "trans": "curatorship", "col": "museum curator", "ex": "The curator showed us around the exhibition.", "pos": "n."},
    "curb": {"def": "制止、束縛、馬路路緣、制止、控制", "ipa": "/kɜːb/", "trans": "curbed", "col": "curb inflation, curb one's temper", "ex": "The government is trying to curb inflation.", "pos": "n./v."},
    "cure": {"def": "治療、治癒、治療法、治癒、矯治", "ipa": "/kjʊə/", "trans": "curable", "col": "cure a disease, permanent cure", "ex": "The doctor managed to cure the patient's illness.", "pos": "v./n."},
    "curiosity": {"def": "好奇心、珍奇物", "ipa": "/ˌkjʊəriˈɒsəti/", "trans": "curious", "col": "satisfy curiosity, burn with curiosity", "ex": "Curiosity killed the cat.", "pos": "n."},
    "curious": {"def": "好奇的、奇異的", "ipa": "/ˈkjʊəriəs/", "trans": "curiosity (名詞), curiously", "col": "curious about", "ex": "I'm curious to know what happens next.", "pos": "adj."},
    "curl": {"def": "捲曲、捲髮、螺旋、捲、彎曲、形成捲曲", "ipa": "/kɜːl/", "trans": "curly", "col": "curl up", "ex": "Her hair curls naturally.", "pos": "n./v."},
    "curly": {"def": "捲曲的", "ipa": "/ˈkɜːli/", "trans": "curl (名詞/動詞)", "col": "curly hair", "ex": "She has long curly hair.", "pos": "adj."},
    "currency": {"def": "貨幣、流傳、通用", "ipa": "/ˈkʌrənsi/", "trans": "currencies", "col": "foreign currency, local currency", "ex": "The US dollar is the standard currency for international trade.", "pos": "n."},
    "current": {"def": "目前的、通用的、水流、氣流、電流", "ipa": "/ˈkʌrənt/", "trans": "currently", "col": "current situation, electric current, current events", "ex": "What are the current trends in fashion?", "pos": "adj./n."},
    "currently": {"def": "目前、現在", "ipa": "/ˈkʌrəntli/", "trans": "current (形容詞)", "col": "currently available", "ex": "She is currently working on a new project.", "pos": "adv."},
    "curriculum": {"def": "課程、全部課程", "ipa": "/kəˈrɪkjələm/", "trans": "curricula (複數)", "col": "school curriculum, core curriculum", "ex": "The school curriculum includes math and science.", "pos": "n."},
    "curry": {"def": "咖哩、用咖哩烹調", "ipa": "/ˈkʌri/", "trans": "curried", "col": "chicken curry, curry favor with", "ex": "She likes to eat spicy curry.", "pos": "n./v."},
    "curse": {"def": "咒罵、詛咒、禍根、咒罵、詛咒", "ipa": "/kɜːs/", "trans": "cursed", "col": "under a curse", "ex": "The old woman put a curse on the family.", "pos": "n./v."},
    "curtain": {"def": "窗簾、幕、遮蔽物", "ipa": "/ˈkɜːtn/", "trans": "curtains", "col": "draw the curtains, behind the scenes (behind the curtain)", "ex": "She drew the curtains to let in some light.", "pos": "n."},
    "curve": {"def": "曲線、彎曲、彎曲、使彎曲", "ipa": "/kɜːv/", "trans": "curvy", "col": "learning curve, sharp curve", "ex": "The road curves sharply to the left.", "pos": "n./v."},
    "cushion": {"def": "墊子、靠墊、緩衝、起緩衝作用、緩解", "ipa": "/ˈkʊʃn/", "trans": "cushioned", "col": "seat cushion, cushion the blow", "ex": "She sat on a soft cushion.", "pos": "n./v."},
    "custody": {"def": "監護、扣留、監管", "ipa": "/ˈkʌstədi/", "trans": "custodian", "col": "child custody, in custody", "ex": "The suspect is in police custody.", "pos": "n."},
    "custom": {"def": "習俗、習慣、顧客、訂做的、海關（常用複數）", "ipa": "/ˈkʌstəm/", "trans": "customary, customer", "col": "local custom, pass through customs", "ex": "It's a local custom to exchange gifts.", "pos": "n./adj."},
    "customary": {"def": "習慣上的、合乎習俗的", "ipa": "/ˈkʌstəməri/", "trans": "custom (名詞)", "col": "customary behavior", "ex": "It's customary to shake hands when you meet someone.", "pos": "adj."},
    "customer": {"def": "顧客、客戶", "ipa": "/ˈkʌstəmə/", "trans": "custom (名詞/形容詞)", "col": "customer service, regular customer", "ex": "The store offers excellent customer service.", "pos": "n."},
    "cut": {"def": "切、割、削減、傷口、切下的部分、削減、切、刻、削減", "ipa": "/kʌt/", "trans": "cutter, cutting", "col": "cut corners, cut in, cut down on", "ex": "He cut his finger with a knife.", "pos": "v./n."},
    "cute": {"def": "可愛的、漂亮、伶俐的", "ipa": "/kjuːt/", "trans": "cutely, cuteness", "col": "cute baby, cute puppy", "ex": "The baby is so cute!", "pos": "adj."},
    "cycle": {"def": "週期、循環、腳踏車、騎腳踏車、使循環", "ipa": "/ˈsaɪkl/", "trans": "cyclist", "col": "life cycle, business cycle, water cycle", "ex": "Success and failure are part of the cycle of life.", "pos": "n./v."},
    "cyclist": {"def": "騎腳踏車的人", "ipa": "/ˈsaɪklɪst/", "trans": "cycle (名詞/動詞)", "col": "professional cyclist", "ex": "There are many cyclists on the road during the weekend.", "pos": "n."},
    "cylinder": {"def": "圓柱體、汽缸", "ipa": "/ˈsɪlɪndə/", "trans": "cylindrical", "col": "gas cylinder", "ex": "The car engine has four cylinders.", "pos": "n."},
    "dairy": {"def": "乳製品、牛奶場、乳製品的", "ipa": "/ˈdeəri/", "trans": "dairying", "col": "dairy products, dairy farm", "ex": "Milk and cheese are dairy products.", "pos": "n./adj."},
    "dam": {"def": "水壩、攔水壩、築壩攔住", "ipa": "/dæm/", "trans": "dams", "col": "beaver dam, hydroelectric dam", "ex": "The dam was built to generate electricity.", "pos": "n./v."},
    "damage": {"def": "損害、損失、賠償金（常用複數）、毀壞、波及", "ipa": "/ˈdæmɪdʒ/", "trans": "damaging", "col": "cause damage, severe damage, fire damage", "ex": "The storm caused a lot of damage to the crops.", "pos": "n./v."},
    "damn": {"def": "譴責、詛咒、咒罵、毫無價值的東西、該死的、極其", "ipa": "/dæm/", "trans": "damned", "col": "I don't give a damn.", "ex": "Damn! I forgot my keys.", "pos": "v./n./adj./adv."},
    "damp": {"def": "潮濕的、使潮濕、潮濕、濕氣", "ipa": "/dæmp/", "trans": "dampen", "col": "damp cloth, cold and damp", "ex": "The walls were damp after the rain.", "pos": "adj./v./n."},
    "dance": {"def": "跳舞、舞蹈、舞會、跳舞、使跳舞", "ipa": "/dɑːns/", "trans": "dancer", "col": "modern dance, folk dance, first dance", "ex": "Would you like to dance with me?", "pos": "n./v."},
    "dancer": {"def": "舞者、舞蹈家", "ipa": "/ˈdɑːnsə/", "trans": "dance (名詞/動詞)", "col": "professional dancer", "ex": "She is a very talented dancer.", "pos": "n."},
    "dancewear": {"def": "舞蹈服裝", "ipa": "/ˈdɑːnsweə/", "trans": "dance (名詞/動詞)", "col": "ballet dancewear", "ex": "She is wearing specialized dancewear for her recital.", "pos": "n."},
    "dancing": {"def": "舞蹈、跳舞的", "ipa": "/ˈdɑːnsɪŋ/", "trans": "dance (名詞/動詞)", "col": "ballroom dancing", "ex": "I enjoy dancing.", "pos": "n./adj."},
    "danger": {"def": "危險、危險的人或物", "ipa": "/ˈdeɪndʒə/", "trans": "dangerous", "col": "in danger, out of danger", "ex": "The bridge is in danger of collapsing.", "pos": "n."},
    "dangerous": {"def": "危險的", "ipa": "/ˈdeɪndʒərəs/", "trans": "danger (名詞), dangerously", "col": "dangerous animals, dangerous road", "ex": "It's dangerous to walk alone at night.", "pos": "adj."},
    "dare": {"def": "敢、挑戰、敢、挑戰、大膽的事", "ipa": "/deə/", "trans": "daring", "col": "dare to do, how dare you", "ex": "How dare you speak to me like that!", "pos": "v./n."},
    "daring": {"def": "大膽的、勇敢的、勇敢、大膽", "ipa": "/ˈdeərɪŋ/", "trans": "dare (動詞/名詞)", "col": "daring rescue", "ex": "She made a daring attempt to climb the mountain.", "pos": "adj./n."},
    "dark": {"def": "黑暗的、深色的、模糊的、黑暗、深色", "ipa": "/dɑːk/", "trans": "darkly, darkness", "col": "after dark, keep in the dark, pitch dark", "ex": "It's getting dark outside.", "pos": "adj./n."},
    "darken": {"def": "變黑、使變黑、變得憂鬱", "ipa": "/ˈdɑːkən/", "trans": "darkness", "col": "darken the room", "ex": "The sky darkened as the storm approached.", "pos": "v."},
    "darkness": {"def": "黑暗、陰鬱", "ipa": "/ˈdɑːknəs/", "trans": "dark (形容詞/名詞)", "col": "in total darkness", "ex": "The room was plunged into darkness.", "pos": "n."},
    "dart": {"def": "飛鏢、猛衝、投擲、急衝、猛衝", "ipa": "/dɑːt/", "trans": "darts", "col": "play darts, make a dart for", "ex": "A rabbit darted across the path.", "pos": "n./v."},
    "dash": {"def": "猛衝、破折號、少許、猛衝、衝擊、使破滅", "ipa": "/dæʃ/", "trans": "dashing", "col": "make a dash for, dash someone's hopes", "ex": "He made a dash for the bus.", "pos": "n./v."},
    "database": {"def": "資料庫", "ipa": "/ˈdeɪtəbeɪs/", "trans": "data", "col": "customer database, searchable database", "ex": "The information is stored in a central database.", "pos": "n."},
    "date": {"def": "日期、約會、椰棗、註明日期、確定年代、約會、過時", "ipa": "/deɪt/", "trans": "dating", "col": "up to date, out of date, blind date", "ex": "What's the date today?", "pos": "n./v."},
    "dating": {"def": "約會、標記日期", "ipa": "/ˈdeɪtɪŋ/", "trans": "date (名詞/動詞)", "col": "online dating", "ex": "They have been dating for six months.", "pos": "n."},
    "daughter": {"def": "女兒", "ipa": "/ˈdɔːtə/", "trans": "daughters", "col": "eldest daughter", "ex": "She is the daughter of a famous writer.", "pos": "n."},
    "dawn": {"def": "黎明、開端、破曉、開始現出、被領悟", "ipa": "/dɔːn/", "trans": "dawning", "col": "at dawn, from dawn to dusk", "ex": "The sun rose at dawn.", "pos": "n./v."},
    "day": {"def": "天、白天、時期", "ipa": "/deɪ/", "trans": "daily", "col": "each day, day and night, these days", "ex": "I work eight hours a day.", "pos": "n."},
    "daybreak": {"def": "黎明、破曉", "ipa": "/ˈdeɪbreɪk/", "trans": "dawn", "col": "at daybreak", "ex": "The travelers set off at daybreak.", "pos": "n."},
    "deadline": {"def": "截止日期、最後時限", "ipa": "/ˈdedlaɪn/", "trans": "deadlines", "col": "meet a deadline, miss a deadline, strictly deadline", "ex": "The deadline for the project is Friday.", "pos": "n."},
    "deadly": {"def": "致命的、枯燥的、極其地", "ipa": "/ˈdedli/", "trans": "dead", "col": "deadly poison, deadly weapon, deadly serious", "ex": "The snake is highly deadly.", "pos": "adj./adv."},
    "deaf": {"def": "聾的、不願聽的", "ipa": "/def/", "trans": "deafness", "col": "stone deaf, turn a deaf ear to", "ex": "He's been deaf since birth.", "pos": "adj."},
    "deafen": {"def": "使聾、淹沒聲音", "ipa": "/ˈdefn/", "trans": "deafening", "col": "deafening noise", "ex": "The noise of the construction was deafening.", "pos": "v."},
    "deal": {"def": "量、交易、買賣、處置、給予、分配", "ipa": "/diːl/", "trans": "dealer, dealing", "col": "big deal, new deal, deal with, a great deal of", "ex": "He is good at dealing with people.", "pos": "n./v."},
    "dealer": {"def": "商入、經銷商、發牌者", "ipa": "/ˈdiːlə/", "trans": "deal (名詞/動詞)", "col": "car dealer, art dealer", "ex": "He is a second-hand car dealer.", "pos": "n."},
    "dean": {"def": "院長、教務長、主任牧師", "ipa": "/diːn/", "trans": "deanship", "col": "dean of students", "ex": "He is the dean of the medical school.", "pos": "n."},
    "dear": {"def": "親愛的、昂貴的、親愛的、好心人、親愛的", "ipa": "/dɪə/", "trans": "dearly", "col": "dear friends, Oh dear!", "ex": "Dear John, how are you?", "pos": "adj./n./int."},
    "debate": {"def": "辯論、爭議、辯論、爭論", "ipa": "/dɪˈbeɪt/", "trans": "debatable", "col": "under debate, presidential debate", "ex": "The matter is still under debate.", "pos": "n./v."},
    "debt": {"def": "債務、恩情", "ipa": "/det/", "trans": "debtor", "col": "in debt, get into debt, pay off a debt", "ex": "The company has a huge debt.", "pos": "n."},
}

with open("batch_l3_p11.json", "w", encoding="utf-8") as f:
    json.dump(L3_PART11, f, ensure_ascii=False, indent=2)
