import json

# Level 6 Part 51: (Bright - Broad)
L6_PART51 = {
    "bright": {"def": "明亮的、聰明的、鮮豔的、快活的、亮色、明亮地 (亮)", "ipa": "/braɪt/", "trans": "brightly, brightness", "col": "bright idea, bright future, look on the bright side, bright and early", "ex": "The sun is very bright today.", "pos": "adj./n./adv."},
    "brighten": {"def": "變亮、使發光、變快活、亮起來的人物、變亮地 (亮)", "ipa": "/ˈbraɪtn/", "trans": "bright", "col": "brighten up", "ex": "The sunshine brightened the room.", "pos": "v./n./adv."},
    "brightly": {"def": "明亮地、鮮豔地、聰明地", "ipa": "/ˈbraɪtli/", "trans": "bright (形容詞/名詞/副詞)", "col": "shining brightly", "ex": "Stars were shining brightly in the sky.", "pos": "adv."},
    "brightness": {"def": "明亮、聰明、鮮豔", "ipa": "/ˈbraɪtnəs/", "trans": "bright (形容詞/名詞/副詞)", "col": "screen brightness", "ex": "He adjusted the brightness of the computer screen.", "pos": "n."},
    "brill": {"def": "(英口)極好的、(魚)菱鮃 (單數)", "ipa": "/brɪl/", "trans": "brilliant", "col": "absolutely brill", "ex": "The movie was absolutely brill!", "pos": "adj./n."},
    "brilliance": {"def": "輝煌、卓越、光輝 (單數)", "ipa": "/ˈbrɪliəns/", "trans": "brilliant", "col": "sheer brilliance", "ex": "Critics praised the sheer brilliance of the performance.", "pos": "n."},
    "brilliancy": {"def": "輝煌、光亮、光彩 (單數)", "ipa": "/ˈbrɪliənsi/", "trans": "brilliance", "col": "exceptional brilliancy", "ex": "The diamond was known for its exceptional brilliancy.", "pos": "n."},
    "brilliant": {"def": "卓越的、燦爛的、輝煌的、才華橫溢的、明亮地 (卓越)", "ipa": "/ˈbrɪliənt/", "trans": "brilliantly, brilliance", "col": "brilliant idea, brilliant sunshine, brilliant career", "ex": "She is a brilliant scientist.", "pos": "adj./adv."},
    "brilliantly": {"def": "輝煌地、卓越地、燦爛地", "ipa": "/ˈbrɪliəntli/", "trans": "brilliant (形容詞/副詞)", "col": "performed brilliantly", "ex": "The team performed brilliantly throughout the tournament.", "pos": "adv."},
    "brim": {"def": "(杯、帽)邊、緣、充滿、溢出、邊緣的人物、充滿地 (邊)", "ipa": "/brɪm/", "trans": "brimming", "col": "brim with (充滿), up to the brim", "ex": "The cup was filled to the brim with coffee.", "pos": "n./v./adv."},
    "brimful": {"def": "盈滿的、充滿的", "ipa": "/ˈbrɪmfl/", "trans": "brim (名詞/動詞/副詞)", "col": "brimful of energy", "ex": "She arrived looking brimful of energy and ideas.", "pos": "adj."},
    "brimming": {"def": "盈滿的、充滿的、充滿的人 (或物) (滿)", "ipa": "/ˈbrɪmɪŋ/", "trans": "brim (名詞/動詞/副詞)", "col": "brimming with confidence", "ex": "His eyes were brimming with tears.", "pos": "adj./adv."},
    "brimstone": {"def": "硫磺、(舊)極端的、硫磺地 (硫磺)", "ipa": "/ˈbrɪmstəʊn/", "trans": "sulfur", "col": "fire and brimstone (地獄之火)", "ex": "The preacher spoke of fire and brimstone.", "pos": "n./adv."},
    "brindled": {"def": "有斑點的、雜色的", "ipa": "/ˈbrɪndld/", "trans": "spotted", "col": "brindled coat", "ex": "The dog had a brindled coat of brown and black.", "pos": "adj."},
    "brine": {"def": "鹽水、海水、醃製、鹽水地 (鹽水)", "ipa": "/braɪn/", "trans": "salty water", "col": "pickled in brine", "ex": "The olives are preserved in brine.", "pos": "n./v./adv."},
    "bring": {"def": "帶來、引起、促使、訴諸、帶來的人 (或物)、引起地 (帶)", "ipa": "/brɪŋ/", "trans": "bringing, brought", "col": "bring up (養育/提及), bring about (導致), bring back, bring around (使恢復意識)", "ex": "Can you bring me a glass of water?", "pos": "v./n./adv."},
    "bringing": {"def": "養育、引起、帶來的人 (或物) (帶)", "ipa": "/ˈbrɪŋɪŋ/", "trans": "bring (動詞/名詞/副詞)", "col": "bringing about change", "ex": "They are focused on bringing about positive change.", "pos": "n./adv."},
    "brink": {"def": "邊緣、(危險)邊界、邊緣的人、在邊緣地 (緣)", "ipa": "/brɪŋk/", "trans": "edge", "col": "on the brink of (在...邊緣)", "ex": "The country is on the brink of war.", "pos": "n./adv."},
    "briny": {"def": "鹽水的、海水的、(口)海洋人物", "ipa": "/ˈbraɪni/", "trans": "brine (名詞/動詞/副詞)", "col": "briny deep (海洋)", "ex": "They sailed across the briny deep.", "pos": "adj./n."},
    "briquette": {"def": "煤磚、煤球 (單數)", "ipa": "/brɪˈket/", "trans": "coal block", "col": "charcoal briquette", "ex": "He put some charcoal briquettes on the barbecue.", "pos": "n."},
    "brisk": {"def": "敏捷的、活潑的、涼爽的、使活躍、敏捷地 (快)", "ipa": "/brɪsk/", "trans": "briskly", "col": "brisk walk, brisk trade, brisk wind", "ex": "We took a brisk walk in the park.", "pos": "adj./v./adv."},
    "briskly": {"def": "敏捷地、活潑地、涼爽地", "ipa": "/ˈbrɪskli/", "trans": "brisk (形容詞/動詞/副詞)", "col": "walked briskly", "ex": "She walked briskly to the office.", "pos": "adv."},
    "briskness": {"def": "敏捷、活潑、涼爽", "ipa": "/ˈbrɪsknəs/", "trans": "brisk (形容詞/動詞/副詞)", "col": "habitual briskness", "ex": "Everything was done with her habitual briskness.", "pos": "n."},
    "brisket": {"def": "胸肉 (通常指牛胸肉) (單數)", "ipa": "/ˈbrɪskɪt/", "trans": "meat", "col": "slow-cooked brisket", "ex": "The menu featured slow-cooked beef brisket.", "pos": "n."},
    "bristle": {"def": "短而硬的毛、(豬)鬃、發怒、毛髮直豎、剛毛的人、發怒地 (剛毛)", "ipa": "/ˈbrɪsl/", "trans": "bristly", "col": "bristle with (充滿/憤慨)", "ex": "The brush hair is made of natural bristles.", "pos": "n./v./adv."},
    "bristly": {"def": "有刺毛的、易怒的", "ipa": "/ˈbrɪstli/", "trans": "bristle (名詞/動詞/副詞)", "col": "bristly chin", "ex": "He rubbed his bristly chin.", "pos": "adj."},
    "british": {"def": "英國的、英國人的、英國英語、英國人的人物、英國英語地 (英)", "ipa": "/ˈbrɪtɪʃ/", "trans": "briton", "col": "British Empire, British Council", "ex": "He has a British accent.", "pos": "adj./n./adv."},
    "brittle": {"def": "脆的、易碎的、冷淡的、脆弱地 (脆)", "ipa": "/ˈbrɪtl/", "trans": "brittleness", "col": "brittle bones, peanut brittle", "ex": "Glass is a brittle material and breaks easily.", "pos": "adj./adv."},
    "brittleness": {"def": "脆性、易碎性", "ipa": "/ˈbrɪtlnəs/", "trans": "brittle (形容詞/副詞)", "col": "degree of brittleness", "ex": "Heat treatment can reduce the brittleness of the metal.", "pos": "n."},
    "broach": {"def": "開始討論(困難話題)、鑽洞、胸針、開始討論地 (開口)", "ipa": "/brəʊtʃ/", "trans": "approach", "col": "broach the subject", "ex": "I didn't know how to broach the subject of money with him.", "pos": "v./n./adv."},
    "broad": {"def": "寬廣的、遼闊的、概括的、口音重的、遼闊的人、概括地 (寬)", "ipa": "/brɔːd/", "trans": "broadly, broaden", "col": "broad smile, broad daylight (大白天), broad outline, broad shoulders", "ex": "The river is very broad at this point.", "pos": "adj./n./adv."},
}