import json

# Level 6 Part 40: (Blue-blooded - Body)
L6_PART40 = {
    "blue-blooded": {"def": "貴族的、出身名門的", "ipa": "/ˌbluːˈblʌdɪd/", "trans": "aristocratic", "col": "blue-blooded family", "ex": "She comes from a blue-blooded aristocratic family.", "pos": "adj."},
    "bluebottle": {"def": "反吐麗蠅、青蠅 (單數)", "ipa": "/ˈbluːbɒtl/", "trans": "bluebottles (複數)", "col": "noisy bluebottle", "ex": "A noisy bluebottle was buzzing around the kitchen.", "pos": "n."},
    "blueprint": {"def": "藍圖、計畫、製成藍圖、計畫的人物、計畫地 (藍圖)", "ipa": "/ˈbluːprɪnt/", "trans": "blueprints", "col": "economic blueprint, building blueprint", "ex": "The architect presented the blueprints for the new library.", "pos": "n./v./adv."},
    "bluer": {"def": "(blue的比較級)、更藍的", "ipa": "/ˈbluːə/", "trans": "blue", "col": "bluer sky", "ex": "The sky is bluer today than it was yesterday.", "pos": "adj."},
    "bluest": {"def": "(blue的最高級)、最藍的", "ipa": "/ˈbluːɪst/", "trans": "blue", "col": "bluest eyes", "ex": "She has the bluest eyes I've ever seen.", "pos": "adj."},
    "bluff": {"def": "虛張聲勢、嚇唬、懸崖、直率的、嚇唬的人 (或物)、直率地 (嚇)", "ipa": "/blʌf/", "trans": "bluffing", "col": "call someone's bluff (戳穿謊言), bluff one's way through", "ex": "He's just bluffing - don't listen to him.", "pos": "v./n./adj./adv."},
    "bluffer": {"def": "虛張聲勢者", "ipa": "/ˈblʌfə/", "trans": "bluff (名詞/動詞/形容詞/副詞)", "col": "big bluffer", "ex": "Everyone knows he's just a big bluffer.", "pos": "n."},
    "bluffing": {"def": "虛張聲勢、嚇唬的人 (或物) (嚇)", "ipa": "/ˈblʌfɪŋ/", "trans": "bluff (名詞/動詞/形容詞/副詞)", "col": "expert at bluffing", "ex": "He is an expert at bluffing people.", "pos": "n./adv."},
    "bluish": {"def": "帶藍色的", "ipa": "/ˈbluːɪʃ/", "trans": "blue", "col": "bluish tinge", "ex": "The mountains have a bluish tinge in the evening.", "pos": "adj."},
    "blunder": {"def": "大錯、失策、犯大錯、跌跌撞撞、犯錯的人、失策地 (錯)", "ipa": "/ˈblʌndə/", "trans": "blunders", "col": "terrible blunder, political blunder", "ex": "He made a terrible blunder in his speech.", "pos": "n./v./adv."},
    "blunderbuss": {"def": "(古)短管鳥槍、笨拙的人 (單數)", "ipa": "/ˈblʌndəbʌs/", "trans": "blunderbusses (複數)", "col": "rusty blunderbuss", "ex": "He owns a rusty old blunderbuss as a collector's item.", "pos": "n."},
    "blundering": {"def": "粗魯的、笨拙的、做錯事的的人 (或物) (錯)", "ipa": "/ˈblʌndərɪŋ/", "trans": "blunder (名詞/動詞/副詞)", "col": "blundering attempt", "ex": "His blundering attempt only made things worse.", "pos": "adj./adv."},
    "blunt": {"def": "鈍的、直率的、使變鈍、變鈍的人 (或物)、直率地 (鈍)", "ipa": "/blʌnt/", "trans": "bluntly, bluntness", "col": "blunt knife, blunt refusal, to be blunt (坦白說)", "ex": "He was quite blunt about his lack of money.", "pos": "adj./v./n./adv."},
    "bluntly": {"def": "直率地、生硬地、鈍地 (鈍)", "ipa": "/ˈblʌntli/", "trans": "blunt (形容詞/動詞/名詞/副詞)", "col": "stated bluntly", "ex": "He told her bluntly that she wasn't wanted.", "pos": "adv."},
    "bluntness": {"def": "直率、生硬、遲鈍", "ipa": "/ˈblʌntnəs/", "trans": "blunt (形容詞/動詞/名詞/副詞)", "col": "characteristic bluntness", "ex": "We were surprised by the bluntness of his speech.", "pos": "n."},
    "blur": {"def": "模糊、模糊不清的事物、使模糊、模糊地 (模糊)", "ipa": "/blɜː/", "trans": "blurred", "col": "motion blur, in a blur", "ex": "Everything happened in a blur.", "pos": "n./v./adv."},
    "blurred": {"def": "模糊的、分不清的", "ipa": "/blɜːd/", "trans": "blur (名詞/動詞/副詞)", "col": "blurred vision", "ex": "His vision was blurred by tears.", "pos": "adj."},
    "blurb": {"def": "(書封)簡介、廣告文字、為...作廣告、廣告的人 (或物) (簡介)", "ipa": "/blɜːb/", "trans": "blurbs", "col": "publisher's blurb", "ex": "The blurb on the back of the book says it's very funny.", "pos": "n./v./adv."},
    "blurt": {"def": "脫口而出、洩漏地 (脫口)", "ipa": "/blɜːt/", "trans": "blurt out", "col": "blurt out the truth", "ex": "She blurted out the truth before she could stop herself.", "pos": "v./adv."},
    "blush": {"def": "臉紅、羞愧、泛紅、臉紅的人 (或物)、泛紅地 (紅)", "ipa": "/blʌʃ/", "trans": "blushing", "col": "blush for shame, blush deep red", "ex": "She blushed deep red when he praised her.", "pos": "n./v./adv."},
    "blushing": {"def": "臉紅的、泛紅的、臉紅的人 (或物) (紅)", "ipa": "/ˈblʌʃɪŋ/", "trans": "blush (名詞/動詞/副詞)", "col": "blushing bride", "ex": "She was a blushing bride on her wedding day.", "pos": "adj./adv."},
    "bluster": {"def": "狂風大作、咆哮、虛張聲勢、恐嚇的人 (或物)、咆哮地 (咆)", "ipa": "/ˈblʌstə/", "trans": "blustering", "col": "bluster through", "ex": "He tried to bluster his way out of the trouble.", "pos": "v./n./adv."},
    "blustering": {"def": "狂風大作的、咆哮的、嚇唬人的的人 (或物) (咆)", "ipa": "/ˈblʌstərɪŋ/", "trans": "bluster (動詞/名詞/副詞)", "col": "blustering winds", "ex": "The blustering winds kept us inside.", "pos": "adj./adv."},
    "boa": {"def": "大蟒蛇、女用羽毛圍巾 (單數)", "ipa": "/ˈbəʊə/", "trans": "boas (複數)", "col": "boa constrictor", "ex": "The boa constrictor squeezed its prey.", "pos": "n."},
    "boar": {"def": "野豬、守公豬、公豬的人物、公豬地 (豬)", "ipa": "/bɔː/", "trans": "boars", "col": "wild boar", "ex": "The wild boar live in the mountain forests.", "pos": "n./adv."},
    "board": {"def": "木板、委員會、膳食、登(機/船)、董事會的、在船上地 (板)", "ipa": "/bɔːd/", "trans": "boarding, boards", "col": "notice board, board meeting, on board, room and board (膳宿)", "ex": "He is a member of the board of directors.", "pos": "n./v./adj./adv."},
    "boarder": {"def": "寄宿生、寄宿者 (單數)", "ipa": "/ˈbɔːdə/", "trans": "boarders (複數)", "col": "school boarder", "ex": "He has been a boarder at the school since he was ten.", "pos": "n."},
    "boarding": {"def": "寄宿的、登機的、寄宿的人 (或物) (宿)", "ipa": "/ˈbɔːdɪŋ/", "trans": "board (名詞/動詞/副詞)", "col": "boarding house, boarding pass, boarding school", "ex": "Please produce your boarding pass at the gate.", "pos": "n./adj./adv."},
    "boardroom": {"def": "董事會會議室 (單數)", "ipa": "/ˈbɔːdruːm/", "trans": "boardrooms (複數)", "col": "company boardroom", "ex": "The crucial decision was made in the company boardroom.", "pos": "n."},
    "boast": {"def": "自誇、誇耀、引以為榮的事、自大的人物、誇耀地 (誇)", "ipa": "/bəʊst/", "trans": "boastful, boasting", "col": "boast about, empty boast", "ex": "He boasted about his expensive new car.", "pos": "v./n./adv."},
    "boaster": {"def": "吹牛者、自誇的人", "ipa": "/ˈbəʊstə/", "trans": "boast (動詞/名詞/副詞)", "col": "notorious boaster", "ex": "He is a notorious boaster who exaggerates everything.", "pos": "n."},
    "boastful": {"def": "自誇的、喜誇耀的", "ipa": "/ˈbəʊstfl/", "trans": "boast (動詞/名詞/副詞)", "col": "boastful behavior", "ex": "He is very boastful about his achievements.", "pos": "adj."},
    "boastfully": {"def": "自誇地、誇耀地", "ipa": "/ˈbəʊstfli/", "trans": "boast (動詞/名詞/副詞), boastful", "col": "spoke boastfully", "ex": "He spoke boastfully of his past successes.", "pos": "adv."},
    "boasting": {"def": "吹牛、誇耀、吹牛的人物 (吹)", "ipa": "/ˈbəʊstɪŋ/", "trans": "boast (動詞/名詞/副詞)", "col": "stop boasting", "ex": "Stop boasting - nobody believes you.", "pos": "n./adv."},
    "boat": {"def": "小船、艇、乘船、船狀的、乘船地 (船)", "ipa": "/bəʊt/", "trans": "boating, boats", "col": "fishing boat, lifeboat, miss the boat (錯失良機), in the same boat (處境相同)", "ex": "We hired a boat for the afternoon.", "pos": "n./v./adv."},
    "boater": {"def": "乘船者、(平頂)硬草帽 (單數)", "ipa": "/ˈbəʊtə/", "trans": "boaters (複數)", "col": "straw boater", "ex": "He wore a straw boater to the summer party.", "pos": "n."},
    "boating": {"def": "划船、泛舟、划船的人 (或物) (划)", "ipa": "/ˈbəʊtɪŋ/", "trans": "boat (名詞/動詞/副詞)", "col": "go boating", "ex": "We went boating on the lake.", "pos": "n./adv."},
    "boatman": {"def": "船夫、划船人", "ipa": "/ˈbəʊtmən/", "trans": "boatman (單數), boatmen (複數)", "col": "experienced boatman", "ex": "The experienced boatman guided us through the rapids.", "pos": "n."},
    "boatswain": {"def": "水手長", "ipa": "/ˈbəʊsn/", "trans": "bosun", "col": "order of the boatswain", "ex": "The boatswain ordered the sailors to scrub the deck.", "pos": "n."},
    "bob": {"def": "輕拍、上下跳動、短髮、切短(髮)、輕拍的人 (或物)、跳動地 (跳)", "ipa": "/bɒb/", "trans": "bobbing", "col": "bob up and down, bobbed hair", "ex": "The cork bobbed up and down in the water.", "pos": "v./n./adv."},
    "bobbin": {"def": "線軸、捲軸 (單數)", "ipa": "/ˈbɒbɪn/", "trans": "bobbins (複數)", "col": "sewing bobbin", "ex": "She wound the thread onto the bobbin.", "pos": "n."},
    "bobbing": {"def": "上下跳動的、擺動的、擺動的人 (或物) (跳)", "ipa": "/ˈbɒbɪŋ/", "trans": "bob (動詞/名詞/副詞)", "col": "bobbing for apples", "ex": "He was bobbing for apples at the Halloween party.", "pos": "adj./adv."},
    "bobsleigh/bobsled": {"def": "雪車、雪橇、乘雪車、雪車的人物、雪車地 (雪車)", "ipa": "/ˈbɒbsleɪ/", "trans": "bobsleighing", "col": "Olympic bobsleigh", "ex": "They competed in the Olympic bobsleigh event.", "pos": "n./v./adv."},
    "bode": {"def": "預言、預示、(古)預兆地 (預示)", "ipa": "/bəʊd/", "trans": "portend", "col": "bode well (吉兆), bode ill (凶兆)", "ex": "The dark clouds bode ill for our picnic.", "pos": "v./adv."},
    "bodice": {"def": "(女裝)緊身胸衣 (單數)", "ipa": "/ˈbɒdɪs/", "trans": "bodices (複數)", "col": "laced bodice", "ex": "The dress has a laced bodice.", "pos": "n."},
    "bodiless": {"def": "無身體的、靈魂的", "ipa": "/ˈbɒdiləs/", "trans": "incorporeal", "col": "bodiless spirit", "ex": "She believed she saw a bodiless spirit.", "pos": "adj."},
    "bodily": {"def": "肉體的、身體的、整體地、親自地", "ipa": "/ˈbɒdɪli/", "trans": "body (名詞/動詞/副詞)", "col": "bodily harm, bodily functions", "ex": "He suffered severe bodily harm in the accident.", "pos": "adj./adv."},
    "body": {"def": "身體、主體、大量、法人團體、變形、具體化、身體的人物、具體地 (身)", "ipa": "/ˈbɒdi/", "trans": "bodies, bodily", "col": "human body, body language, main body, celestial body (天體)", "ex": "She has a very healthy body.", "pos": "n./v./adj./adv."},
}