import json

# Level 6 Part 2: (Acre - Advent)
L6_PART2 = {
    "acre": {"def": "英畝、土地、田地", "ipa": "/ˈeɪkə/", "trans": "acreage", "col": "acre of land", "ex": "He owns several acres of land in the countryside.", "pos": "n."},
    "acreage": {"def": "英畝數、面積", "ipa": "/ˈeɪkərɪdʒ/", "trans": "acre (名詞)", "col": "total acreage", "ex": "The total acreage of the farm is about 500 acres.", "pos": "n."},
    "acrid": {"def": "辛辣的、苦澀的、刺激性的、刻薄的", "ipa": "/ˈækrɪd/", "trans": "acridity", "col": "acrid smoke", "ex": "The acrid smoke from the fire made our eyes water.", "pos": "adj."},
    "acrimonious": {"def": "尖刻的、嚴厲的、刻薄的", "ipa": "/ˌækrɪˈməʊniəs/", "trans": "acrimony", "col": "acrimonious debate", "ex": "The meeting ended in an acrimonious debate.", "pos": "adj."},
    "acrimony": {"def": "尖刻、嚴厲、刻薄", "ipa": "/ˈækrɪməni/", "trans": "acrimonious (形容詞)", "col": "full of acrimony", "ex": "The divorce was handled with great acrimony.", "pos": "n."},
    "acrobat": {"def": "特技演員、雜技演員、隨機應變的人", "ipa": "/ˈækrəbæt/", "trans": "acrobatic", "col": "skilled acrobat", "ex": "I saw a skilled acrobat performing in the circus.", "pos": "n."},
    "acrobatic": {"def": "雜技的、特技的、翻筋斗的", "ipa": "/ˌækrəˈbætɪk/", "trans": "acrobat (名詞)", "col": "acrobatic feat", "ex": "The dancer performed an impressive acrobatic feat.", "pos": "adj."},
    "acronym": {"def": "首字母縮略詞", "ipa": "/ˈækrənɪm/", "trans": "acronymic", "col": "scientific acronym", "ex": "NATO is an acronym for North Atlantic Treaty Organization.", "pos": "n."},
    "across": {"def": "穿過、橫過、在對面、寬、橫過地、交叉地、在對面地 (穿過)", "ipa": "/əˈkrɒs/", "trans": "crossed", "col": "run across, walk across", "ex": "The bridge goes across the river.", "pos": "adv./prep."},
    "act": {"def": "行為、法令、幕、行動、表現、演戲、充當、行動地、有效地", "ipa": "/ækt/", "trans": "action, active, actor", "col": "act of kindness, act as, in the act of", "ex": "It's time to act.", "pos": "n./v./adv."},
    "action": {"def": "行動、作用、官司、情境、在役的、起作用的、戰鬥地", "ipa": "/ˈækʃn/", "trans": "act (名詞/動詞/副詞), active", "col": "take action, course of action", "ex": "We need to take immediate action.", "pos": "n./adj./adv."},
    "actionable": {"def": "可起訴的、可執行的", "ipa": "/ˈækʃənəbl/", "trans": "action, act", "col": "actionable intelligence", "ex": "The report provides actionable intelligence for the government.", "pos": "adj."},
    "activate": {"def": "激活、啟動、使活潑", "ipa": "/ˈæktɪveɪt/", "trans": "activation, active", "col": "activate a card", "ex": "You need to activate your credit card before using it.", "pos": "v."},
    "activation": {"def": "激活、啟動、活化", "ipa": "/ˌæktɪˈveɪʃn/", "trans": "activate (動詞), active", "col": "automatic activation", "ex": "The alarm has an automatic activation system.", "pos": "n."},
    "active": {"def": "積極的、活躍的、主動的、現役的、積極分子、主動語態、活躍地 (積極)", "ipa": "/ˈæktɪv/", "trans": "actively, activity", "col": "active participant, lead an active life", "ex": "She is an active member of the club.", "pos": "adj./n./adv."},
    "actively": {"def": "積極地、活躍地、主動地", "ipa": "/ˈæktɪvli/", "trans": "active (形容詞/名詞/副詞), activity", "col": "actively involved", "ex": "He is actively involved in local politics.", "pos": "adv."},
    "activism": {"def": "行動主義、積極性", "ipa": "/ˈæktɪvɪzəm/", "trans": "activist", "col": "political activism", "ex": "She is known for her political activism.", "pos": "n."},
    "activist": {"def": "活動家、激進分子、行動主義的", "ipa": "/ˈæktɪvɪst/", "trans": "activism (名詞)", "col": "environmental activist", "ex": "He is a prominent environmental activist.", "pos": "n./adj."},
    "activity": {"def": "活動、活力、能動性", "ipa": "/ækˈtɪvəti/", "trans": "active, activate", "col": "outdoor activity, daily activity", "ex": "The center offers a wide range of activities.", "pos": "n."},
    "actor": {"def": "演員、參與者", "ipa": "/ˈæktə/", "trans": "actress", "col": "famous actor", "ex": "He is a famous Hollywood actor.", "pos": "n."},
    "actress": {"def": "女演員", "ipa": "/ˈæktrəs/", "trans": "actor", "col": "award-winning actress", "ex": "She is an award-winning actress.", "pos": "n."},
    "actual": {"def": "實際的、真實的、現行的、現狀、實質、真實地 (實際)", "ipa": "/ˈæktʃuəl/", "trans": "actually, actuality", "col": "actual cost, in actual fact", "ex": "The actual cost was much higher than the estimate.", "pos": "adj./n./adv."},
    "actuality": {"def": "實際、現狀、事實", "ipa": "/ˌæktʃuˈæləti/", "trans": "actual (形容詞/名詞/副詞), actually", "col": "in actuality", "ex": "In actuality, the situation is much worse than reported.", "pos": "n."},
    "actually": {"def": "實際上、竟然、其實", "ipa": "/ˈæktʃuəli/", "trans": "actual (形容詞/名詞/副詞), actuality", "col": "actually happened", "ex": "What actually happened that night?", "pos": "adv."},
    "actuarial": {"def": "精算的、保險統計的", "ipa": "/ˌæktʃuˈeəriəl/", "trans": "actuary", "col": "actuarial science", "ex": "He is studying actuarial science at the university.", "pos": "adj."},
    "actuary": {"def": "保險精算師", "ipa": "/ˈæktʃuəri/", "trans": "actuarial", "col": "qualified actuary", "ex": "She works as a qualified actuary for an insurance company.", "pos": "n."},
    "actuate": {"def": "開動、促使、激勵", "ipa": "/ˈæktʃueɪt/", "trans": "actuation", "col": "actuated by", "ex": "The machine is actuated by a small motor.", "pos": "v."},
    "acuity": {"def": "敏銳、尖銳、劇烈", "ipa": "/əˈkjuːəti/", "trans": "acute", "col": "visual acuity", "ex": "The bird has remarkable visual acuity.", "pos": "n."},
    "acumen": {"def": "敏銳、聰明、才識", "ipa": "/ˈækjəmən/", "trans": "sharpness", "col": "business acumen", "ex": "He is known for his sharp business acumen.", "pos": "n."},
    "acupuncture": {"def": "針灸、針刺療法、施以針灸", "ipa": "/ˈækjupʌŋktʃə/", "trans": "acupuncturist", "col": "traditional acupuncture", "ex": "She tried traditional acupuncture for her back pain.", "pos": "n./v."},
    "acute": {"def": "敏銳的、劇烈的、嚴重的、(醫)急性的、(數)銳角的、細微地 (敏銳)", "ipa": "/əˈkjuːt/", "trans": "acutely, acuity", "col": "acute pain, acute shortage", "ex": "There is an acute shortage of water in the area.", "pos": "adj./adv."},
    "acutely": {"def": "敏銳地、劇烈地、極其、強烈地", "ipa": "/əˈkjuːtli/", "trans": "acute (形容詞/副詞), acuity", "col": "acutely aware", "ex": "He was acutely aware of the danger.", "pos": "adv."},
    "adage": {"def": "格言、諺語", "ipa": "/ˈædɪdʒ/", "trans": "proverb", "col": "ancient adage", "ex": "He often quotes the ancient adage about honesty.", "pos": "n."},
    "adamant": {"def": "堅定不移的、固執的、強硬的、硬石、堅硬無比之物", "ipa": "/ˈædəmənt/", "trans": "adamantly", "col": "remain adamant", "ex": "She remained adamant in her refusal to help.", "pos": "adj./n."},
    "adamantly": {"def": "堅定地、固執地、強硬地", "ipa": "/ˈædəməntli/", "trans": "adamant (形容詞/名詞)", "col": "adamantly opposed", "ex": "He was adamantly opposed to the plan.", "pos": "adv."},
    "adapt": {"def": "適應、改編、修改", "ipa": "/əˈdæpt/", "trans": "adaptation, adaptable", "col": "adapt to environment", "ex": "Animals can adapt to their environment over time.", "pos": "v."},
    "adaptability": {"def": "適應性、順應性", "ipa": "/əˌdæptəˈbɪləti/", "trans": "adaptable, adapt", "col": "high adaptability", "ex": "High adaptability is essential in a fast-changing world.", "pos": "n."},
    "adaptable": {"def": "能適應的、可改編的、適合的", "ipa": "/əˈdæptəbl/", "trans": "adapt (動詞), adaptation", "col": "flexible and adaptable", "ex": "He is a very flexible and adaptable employee.", "pos": "adj."},
    "adaptation": {"def": "適應、改編、改裝、適應之物", "ipa": "/ˌædæpˈteɪʃn/", "trans": "adapt (動詞), adaptable", "col": "film adaptation", "ex": "The movie is a film adaptation of a famous novel.", "pos": "n."},
    "adapter/adaptor": {"def": "適配器、轉接器、改編者", "ipa": "/əˈdæptə/", "trans": "adapt (動詞)", "col": "travel adapter", "ex": "Don't forget to pack a travel adapter.", "pos": "n."},
    "add": {"def": "增加、補充、相加、合計、加數、補充、補充地 (增加)", "ipa": "/æd/", "trans": "addition, additional", "col": "add up to, add on", "ex": "Could you add some sugar to my coffee?", "pos": "v./n./adv."},
    "addict": {"def": "上癮者、入迷的人、使沉溺、使成癮、入迷的", "ipa": "/ˈædɪkt/ (n.) /əˈdɪkt/ (v.)", "trans": "addiction, addicted", "col": "drug addict, workaholic (工作狂)", "ex": "He is a computer game addict.", "pos": "n./v./adj."},
    "addicted": {"def": "上癮的、沉溺的、入迷的", "ipa": "/əˈdɪktɪd/", "trans": "addict (名詞/動詞/形容詞), addiction", "col": "addicted to", "ex": "She is addicted to shopping.", "pos": "adj."},
    "addiction": {"def": "成癮、沉溺、入迷", "ipa": "/əˈdɪkʃn/", "trans": "addict (名詞/動詞/形容詞), addicted", "col": "heroin addiction", "ex": "He is fighting his heroin addiction.", "pos": "n."},
    "addictive": {"def": "使人上癮的、成癮的", "ipa": "/əˈdɪktɪv/", "trans": "addiction, addict", "col": "highly addictive", "ex": "Nicotine is highly addictive.", "pos": "adj."},
    "addition": {"def": "增加、加法、增加物、加法的人 (或事)、額外的、加法的", "ipa": "/əˈdɪʃn/", "trans": "add (動詞/名詞/副詞), additional", "col": "in addition to, addition and subtraction", "ex": "In addition to his salary, he gets a bonus.", "pos": "n./adj."},
    "additional": {"def": "額外的、追加的、另外的", "ipa": "/əˈdɪʃənl/", "trans": "add (動詞/名詞/副詞), additional", "col": "additional cost, additional information", "ex": "There will be an additional cost for delivery.", "pos": "adj."},
    "additionally": {"def": "此外、另外、追加地", "ipa": "/əˈdɪʃənəli/", "trans": "additional (形容詞), addition", "col": "additionally important", "ex": "Additionally, we need to consider the environmental impact.", "pos": "adv."},
    "additive": {"def": "添加劑、添加物、累加的、相加的", "ipa": "/ˈædətɪv/", "trans": "add", "col": "food additive", "ex": "The bread contains no artificial additives.", "pos": "n./adj."},
    "address": {"def": "地址、演說、處理、致辭、稱呼、寫地址、向...發表演說、處理、正式地 (地址)", "ipa": "/əˈdres/", "trans": "addressed", "col": "home address, keynote address, address an issue", "ex": "What is your home address?", "pos": "n./v./adv."},
    "adduce": {"def": "引證、舉出(理由、證據等)", "ipa": "/əˈdjuːs/", "trans": "adducible", "col": "adduce evidence", "ex": "He adduced several reasons for his decision.", "pos": "v."},
    "adept": {"def": "熟練的、內行的、擅長的、能手、專家、熟練地 (熟練)", "ipa": "/əˈdept/ (adj.) /ˈædept/ (n.)", "trans": "adeptly", "col": "adept at", "ex": "She is very adept at solving word puzzles.", "pos": "adj./n./adv."},
    "adeptly": {"def": "熟練地、內行地、擅長地", "ipa": "/əˈdeptli/", "trans": "adept (形容詞/名詞/副詞)", "col": "handle adeptly", "ex": "She handled the difficult situation adeptly.", "pos": "adv."},
    "adequacy": {"def": "適當、足夠、能力", "ipa": "/ˈædəkwəsi/", "trans": "adequate, adequately", "col": "adequacy of resources", "ex": "The adequacy of existing resources is being questioned.", "pos": "n."},
    "adequate": {"def": "足夠的、適當的、勝任的", "ipa": "/ˈædəkwət/", "trans": "accuracy (名詞), adequately", "col": "adequate supply", "ex": "The room is adequate for two people.", "pos": "adj."},
    "adequately": {"def": "足夠地、適當地、勝任地", "ipa": "/ˈædəkwətli/", "trans": "adequate (形容詞), adequacy", "col": "adequately prepared", "ex": "We were not adequately prepared for the storm.", "pos": "adv."},
    "adhere": {"def": "堅持、遵守、黏著、附著", "ipa": "/ədˈhɪə/", "trans": "adherence, adherent", "col": "adhere to rules", "ex": "You must adhere to the rules of the club.", "pos": "v."},
    "adherence": {"def": "堅持、遵守、黏著、忠誠", "ipa": "/ədˈhɪərəns/", "trans": "adhere (動詞), adherent", "col": "strict adherence", "ex": "Strict adherence to the schedule is necessary.", "pos": "n."},
    "adherent": {"def": "信徒、追隨者、黏著的、附著的、堅持的", "ipa": "/ədˈhɪərənt/", "trans": "adherence, adhere", "col": "loyal adherent", "ex": "He is a loyal adherent of the party.", "pos": "n./adj."},
    "adhesion": {"def": "黏著、黏附、支持、贊成", "ipa": "/ədhiːʒn/", "trans": "adhesive", "col": "molecular adhesion", "ex": "The glue provides strong adhesion.", "pos": "n."},
    "adhesive": {"def": "黏著的、附著的、有黏性的、黏合劑、膠帶", "ipa": "/ədˈhiːsɪv/", "trans": "adhesion", "col": "adhesive tape", "ex": "Apply adhesive to both surfaces.", "pos": "adj./n."},
    "adjacent": {"def": "相鄰的、鄰近的、接近的", "ipa": "/əˈdʒeɪsnt/", "trans": "adjacency", "col": "adjacent building", "ex": "The two buildings are adjacent to each other.", "pos": "adj."},
    "adjective": {"def": "形容詞、附屬的、不自立的、形容詞的", "ipa": "/ˈædʒɪktɪv/", "trans": "adjectival", "col": "descriptive adjective", "ex": "Identify the adjectives in the sentence.", "pos": "n./adj."},
    "adjoin": {"def": "毗連、鄰接、靠近", "ipa": "/əˈdʒɔɪn/", "trans": "adjoining", "col": "adjoin the garden", "ex": "His house adjoins the golf course.", "pos": "v."},
    "adjoining": {"def": "毗連的、鄰接的、靠近的", "ipa": "/əˈdʒɔɪnɪŋ/", "trans": "adjoin (動詞)", "col": "adjoining room", "ex": "We stayed in adjoining rooms in the hotel.", "pos": "adj."},
    "adjourn": {"def": "休會、推遲、延期、換地方", "ipa": "/əˈdʒɜːn/", "trans": "adjournment", "col": "adjourn the meeting", "ex": "The meeting was adjourned until next Monday.", "pos": "v."},
    "adjournment": {"def": "休會、延期、休會期", "ipa": "/əˈdʒɜːnmənt/", "trans": "adjourn (動詞)", "col": "brief adjournment", "ex": "The judge called for a brief adjournment.", "pos": "n."},
    "adjudge": {"def": "判決、宣判、裁定、授予", "ipa": "/əˈdʒʌdʒ/", "trans": "adjudicate", "col": "adjudged guilty", "ex": "He was adjudged guilty of the crime.", "pos": "v."},
    "adjudicate": {"def": "判決、裁定、宣告、裁判", "ipa": "/əˈdʒuːdɪkeɪt/", "trans": "adjudication, adjudicator", "col": "adjudicate a dispute", "ex": "The court will adjudicate the dispute.", "pos": "v."},
    "adjunct": {"def": "附件、助手、修飾語、附屬的、臨時的、副的", "ipa": "/ˈædʒʌŋkt/", "trans": "adjunction", "col": "adjunct professor", "ex": "He is an adjunct professor of history.", "pos": "n./adj."},
    "adjust": {"def": "調整、調節、使適應、校準", "ipa": "/əˈdʒʌst/", "trans": "adjustment, adjustable", "col": "adjust the volume, adjust to change", "ex": "You can adjust the height of the chair.", "pos": "v."},
    "adjustable": {"def": "可調整的、可調節的", "ipa": "/əˈdʒʌstəbl/", "trans": "adjust (動詞), adjustment", "col": "adjustable wrench", "ex": "The car has adjustable seats.", "pos": "adj."},
    "adjustment": {"def": "調整、調節、適應、校準", "ipa": "/əˈdʒʌstmənt/", "trans": "adjust (動詞), adjustable", "col": "minor adjustment", "ex": "The watch needs a minor adjustment.", "pos": "n."},
    "adjutant": {"def": "副官、助手、(鳥)禿鸛", "ipa": "/ˈædʒutənt/", "trans": "adjutancy", "col": "military adjutant", "ex": "He served as an adjutant to the general.", "pos": "n."},
    "administer": {"def": "管理、執行、給予、治理", "ipa": "/ədˈmɪnɪstə/", "trans": "administration, administrator", "col": "administer justice, administer medicine", "ex": "The charity is administered by a board of trustees.", "pos": "v."},
    "administration": {"def": "管理、行政、政府、執行", "ipa": "/ədˌmɪnɪˈstreɪʃn/", "trans": "administer (動詞), administrator", "col": "business administration, public administration", "ex": "He works in the administration department.", "pos": "n."},
    "administrative": {"def": "行政的、管理的", "ipa": "/ədˈmɪnɪstrətɪv/", "trans": "administration, administer", "col": "administrative assistant", "ex": "She has strong administrative skills.", "pos": "adj."},
    "administrator": {"def": "管理人、行政官、執行者", "ipa": "/ədˈmɪnɪstreɪtə/", "trans": "administer (動詞), administration", "col": "system administrator", "ex": "He is the system administrator for the company.", "pos": "n."},
    "admirable": {"def": "令人欽佩的、極好的、優秀的", "ipa": "/ˈædmərəbl/", "trans": "admire, admiration", "col": "admirable quality", "ex": "Her courage is truly admirable.", "pos": "adj."},
    "admirably": {"def": "極好地、令人欽佩地、優秀地", "ipa": "/ˈædmərəbli/", "trans": "admirable (形容詞), admire", "col": "behave admirably", "ex": "He behaved admirably during the crisis.", "pos": "adv."},
    "admiral": {"def": "海軍上將、艦隊司令", "ipa": "/ˈædmərəl/", "trans": "admiralty", "col": "rear admiral", "ex": "He was promoted to the rank of admiral.", "pos": "n."},
    "admiralty": {"def": "海軍部、海軍法、海軍法庭", "ipa": "/ˈædmərəlti/", "trans": "admiral", "col": "admiralty law", "ex": "The case was heard in the admiralty court.", "pos": "n."},
    "admiration": {"def": "欽佩、讚賞、羨慕、令人欽佩的人 (或事)", "ipa": "/ˌædməˈreɪʃn/", "trans": "admire (動詞/名詞/副詞), admirable", "col": "full of admiration", "ex": "I have great admiration for her work.", "pos": "n."},
    "admire": {"def": "欽佩、讚賞、羨慕、美觀的人 (或事)、大聲地、出色地、名聲、稱號 (欽佩)", "ipa": "/ədˈmaɪə/", "trans": "admiration, admirable", "col": "admire from afar", "ex": "I really admire your courage.", "pos": "v./n./adv."},
    "admirer": {"def": "仰慕者、讚賞者、追求者", "ipa": "/ədˈmaɪərə/", "trans": "admire (動詞/名詞/副詞)", "col": "secret admirer", "ex": "She has a secret admirer who sends her flowers.", "pos": "n."},
    "admissible": {"def": "可容許的、可採納的、可進入的", "ipa": "/ədˈmɪsəbl/", "trans": "admit, admission", "col": "admissible evidence", "ex": "The judge ruled that the evidence was admissible.", "pos": "adj."},
    "admission": {"def": "入場、承認、錄取、入場費", "ipa": "/ədˈmɪʃn/", "trans": "admit (動詞), admissible", "col": "admission fee, full admission", "ex": "He made a full admission of his guilt.", "pos": "n."},
    "admit": {"def": "承認、准許進入、容納、容許", "ipa": "/ədˈmɪt/", "trans": "admission, admissible", "col": "admit a mistake, admit to hospital", "ex": "He admitted that he had made a mistake.", "pos": "v."},
    "admittance": {"def": "進入權、入場、進入", "ipa": "/ədˈmɪtəns/", "trans": "admit (動詞), admission", "col": "gain admittance", "ex": "No admittance without a permit.", "pos": "n."},
    "admixture": {"def": "混合物、添加物、摻雜", "ipa": "/ædˈmɪkstʃə/", "trans": "mixture", "col": "slight admixture", "ex": "The report was a slight admixture of fact and fiction.", "pos": "n."},
    "admonish": {"def": "告誡、提醒、責備、責令", "ipa": "/ədˈmɒnɪʃ/", "trans": "admonition", "col": "admonish for a mistake", "ex": "He was admonished for his lateness.", "pos": "v."},
    "admonition": {"def": "告誡、提醒、責備", "ipa": "/ˌædməˈnɪʃn/", "trans": "admonish (動詞)", "col": "gentle admonition", "ex": "He received a gentle admonition from his teacher.", "pos": "n."},
    "ado": {"def": "忙亂、紛擾、費力", "ipa": "/əˈduː/", "trans": "fuss", "col": "without more ado (乾脆地), much ado about nothing", "ex": "Without more ado, they started the work.", "pos": "n."},
    "adobe": {"def": "土坏、泥磚、土坏房、土坏色的", "ipa": "/əˈ預測bi/", "trans": "brick", "col": "adobe house", "ex": "The house was built of traditional adobe.", "pos": "n./adj."},
    "adolescence": {"def": "青春期", "ipa": "/ˌædəˈlesns/", "trans": "adolescent", "col": "during adolescence", "ex": "Adolescence is a time of great change.", "pos": "n."},
    "adolescent": {"def": "青少年的、青春期的、不成熟的、青少年", "ipa": "/ˌædəˈlesnt/", "trans": "adolescence (名詞)", "col": "adolescent behavior", "ex": "Many adolescents struggle with self-esteem.", "pos": "adj./n."},
    "adopt": {"def": "採用、收養、批准、採取 (採用)", "ipa": "/əˈdɒpt/", "trans": "adoption, adopted", "col": "adopt a child, adopt a policy", "ex": "They decided to adopt a child.", "pos": "v."},
    "adopted": {"def": "被收養的、採用的、移居的", "ipa": "/əˈdɒptɪd/", "trans": "adopt (動詞), adoption", "col": "adopted son, adopted country", "ex": "He is living in his adopted country.", "pos": "adj."},
    "adoption": {"def": "收養、採用、批准", "ipa": "/əˈdɒpʃn/", "trans": "adopt (動詞), adopted", "col": "child adoption, legal adoption", "ex": "The adoption of the new policy was welcomed.", "pos": "n."},
    "adorable": {"def": "可愛的、討人喜歡的、值得崇拜的", "ipa": "/əˈdɔːrəbl/", "trans": "adore, adoration", "col": "adorable baby", "ex": "What an adorable baby!", "pos": "adj."},
    "adoration": {"def": "崇拜、愛慕、愛慕的人 (或事)", "ipa": "/ˌædəˈreɪʃn/", "trans": "adore (動詞), adorable", "col": "mutual adoration", "ex": "The children looked at their teacher with adoration.", "pos": "n."},
    "adore": {"def": "崇拜、愛慕、極其喜歡", "ipa": "/əˈdɔː/", "trans": "adoration, adorable", "col": "adore someone", "ex": "He adores his children.", "pos": "v."},
    "adroit": {"def": "靈巧的、熟練的、機敏的", "ipa": "/əˈdrɔɪt/", "trans": "adroitly", "col": "adroit handling", "ex": "His adroit handling of the situation was impressive.", "pos": "adj."},
    "adroitly": {"def": "靈巧地、熟練地、機敏地", "ipa": "/əˈdrɔɪtli/", "trans": "adroit (形容詞)", "col": "respond adroitly", "ex": "She responded adroitly to the reporter's questions.", "pos": "adv."},
    "adulate": {"def": "諂媚、奉承", "ipa": "/ˈædjuleɪt/", "trans": "adulation", "col": "adulate a star", "ex": "Fans tend to adulate their favorite movie stars.", "pos": "v."},
    "adulation": {"def": "諂媚、奉承", "ipa": "/ˌædjuˈleɪʃn/", "trans": "adulate (動詞)", "col": "blind adulation", "ex": "He is surrounded by constant adulation.", "pos": "n."},
    "adulterate": {"def": "摻假、通姦的、掺雜的、摻假的人 (或事)、摻假地、通姦地", "ipa": "/əˈdʌltəreɪt/", "trans": "adulteration", "col": "adulterate food", "ex": "The wine had been adulterated with water.", "pos": "v./adj./n./adv."},
    "adulteration": {"def": "摻假、通姦、劣質品", "ipa": "/əˌdʌltəˈreɪʃn/", "trans": "adulterate (動詞/形容詞/名詞/副詞)", "col": "food adulteration", "ex": "Food adulteration is a serious crime.", "pos": "n."},
    "adultery": {"def": "通姦、私通", "ipa": "/əˈdʌltəri/", "trans": "adulterer", "col": "commit adultery", "ex": "He was accused of committing adultery.", "pos": "n."},
    "advance": {"def": "前進、增長、預付款、前進、提前、進步、 پیش的、預先的、前進地、提前地 (前進)", "ipa": "/ədˈvɑːns/", "trans": "advanced, advancement", "col": "in advance, advance notice, scientific advance", "ex": "We need to plan in advance.", "pos": "n./v./adj./adv."},
    "advanced": {"def": "進階的、高級的、先進的、年老的", "ipa": "/ədˈvɑːnst/", "trans": "advance (名詞/動詞/形容詞/副詞), advancement", "col": "advanced technology, advanced study", "ex": "The course is for advanced students only.", "pos": "adj."},
    "advancement": {"def": "前進、進步、升職、預付款", "ipa": "/ədˈvɑːnsmənt/", "trans": "advance (名詞/動詞/形容詞/副詞), advanced", "col": "career advancement", "ex": "The job offers great opportunities for career advancement.", "pos": "n."},
    "advantage": {"def": "優勢、利益、便利、有利於、獲利、有利的、便利的、有利地 (優勢)", "ipa": "/ədˈvɑːntɪdʒ/", "trans": "advantageous, advantageously", "col": "take advantage of, distinct advantage", "ex": "He has a distinct advantage over his rivals.", "pos": "n./v./adj./adv."},
    "advantageous": {"def": "有利的、有益的、方便的", "ipa": "/ˌædvənˈteɪdʒəs/", "trans": "advantage (名詞/動詞/形容詞/副詞), advantageously", "col": "advantageous position", "ex": "The trade deal is advantageous to both countries.", "pos": "adj."},
    "advantageously": {"def": "有利地、有益地、方便地", "ipa": "/ˌædvənˈteɪdʒəsli/", "trans": "advantageous (形容詞), advantage", "col": "placed advantageously", "ex": "The building is placed advantageously on the hill.", "pos": "adv."},
    "advent": {"def": "出現、到來、基督降臨節", "ipa": "/ˈædvent/", "trans": "arrival", "col": "advent of technology", "ex": "The advent of the internet changed the world.", "pos": "n."},
}