import json

# Level 3 Part 6: (Bonus - Calorie)
L3_PART6 = {
    "bonus": {"def": "獎金、紅利、額外津貼", "ipa": "/ˈbəʊnəs/", "trans": "bonuses", "col": "year-end bonus, Christmas bonus", "ex": "He received a generous bonus for his hard work.", "pos": "n."},
    "book": {"def": "書、卷、冊、預訂、登記、登記...", "ipa": "/bʊk/", "trans": "booking, booklet", "col": "book a flight, by the book", "ex": "I'd like to book a table for two.", "pos": "n./v."},
    "bookcase": {"def": "書櫃、書架", "ipa": "/ˈbʊkkeɪs/", "trans": "bookshelf", "col": "modern bookcase", "ex": "The bookcase was filled with classic novels.", "pos": "n."},
    "booklet": {"def": "小冊子", "ipa": "/ˈbʊklət/", "trans": "book (名詞)", "col": "instruction booklet", "ex": "Please read the instruction booklet before using the machine.", "pos": "n."},
    "boom": {"def": "繁榮、激增、發出隆隆聲、繁榮、激增、隆隆聲", "ipa": "/buːm/", "trans": "booming", "col": "baby boom, economic boom", "ex": "The city is experiencing a housing boom.", "pos": "n./v."},
    "boost": {"def": "推進、增加、提高、宣傳、增加、促進", "ipa": "/buːst/", "trans": "booster", "col": "give a boost to, boost confidence", "ex": "The new marketing campaign boosted sales.", "pos": "v./n."},
    "boot": {"def": "靴子、長筒靴、（汽車）行李箱、踢、啟動、解雇", "ipa": "/buːt/", "trans": "booting", "col": "boot up, hiking boots", "ex": "He put on his boots and went outside.", "pos": "n./v."},
    "booth": {"def": "亭、攤、貨攤、隔間", "ipa": "/buːθ/", "trans": "booths", "col": "telephone booth, voting booth", "ex": "He called from a public telephone booth.", "pos": "n."},
    "border": {"def": "邊界、邊境、緣、接界、沿邊、加邊於", "ipa": "/ˈbɔːdə/", "trans": "borderline, bordering", "col": "cross the border, border on", "ex": "Italy shares a border with France.", "pos": "n./v."},
    "bore": {"def": "使厭煩、鑽孔、刺穿、令人厭煩的人事物、孔", "ipa": "/bɔː/", "trans": "boredom, boring", "col": "bore someone to death", "ex": "I don't want to bore you with the details.", "pos": "v./n."},
    "boredom": {"def": "無聊、厭煩", "ipa": "/ˈbɔːdəm/", "trans": "bore (動詞), boring", "col": "die of boredom", "ex": "He took up a hobby to escape boredom.", "pos": "n."},
    "born": {"def": "出生的、天生的", "ipa": "/bɔːn/", "trans": "bear, birth", "col": "born into, a born leader", "ex": "He was born in London in 1990.", "pos": "adj."},
    "borrow": {"def": "借、借入、模仿、借用（詞、主意等）", "ipa": "/ˈbɒrəʊ/", "trans": "borrower, borrowing", "col": "borrow something from", "ex": "Can I borrow your pen?", "pos": "v."},
    "bosom": {"def": "胸懷、胸部、懷抱、心腹的", "ipa": "/ˈbʊzəm/", "trans": "bosoms", "col": "bosom friend", "ex": "She held the child to her bosom.", "pos": "n./adj."},
    "boss": {"def": "老闆、雇主、指揮、下命令於、領頭的", "ipa": "/bɒs/", "trans": "bossy", "col": "boss around", "ex": "My boss is very demanding.", "pos": "n./v./adj."},
    "botany": {"def": "植物學", "ipa": "/ˈbɒtəni/", "trans": "botanical, botanist", "col": "botanical garden", "ex": "He has a great interest in botany.", "pos": "n."},
    "both": {"def": "兩者都、並、雙、兩個、雙方的", "ipa": "/bəʊθ/", "trans": "two", "col": "both...and...", "ex": "Both of them are students.", "pos": "adj./pron./conj."},
    "bother": {"def": "打擾、麻煩、焦慮、困擾、麻煩", "ipa": "/ˈbɒðə/", "trans": "bothersome", "col": "bother students, don't bother", "ex": "I'm sorry to bother you, but I need some help.", "pos": "v./n."},
    "bottle": {"def": "瓶、一瓶、瓶裝、裝入瓶中、抑制（感情等）", "ipa": "/ˈbɒtl/", "trans": "bottling", "col": "wine bottle, bottle up", "ex": "I drank a bottle of mineral water.", "pos": "n./v."},
    "bottom": {"def": "底部、基部、下端、底部的、基礎的", "ipa": "/ˈbɒtəm/", "trans": "bottomless", "col": "bottom line, from the bottom of one's heart", "ex": "The book is at the bottom of the pile.", "pos": "n./adj."},
    "bounce": {"def": "彈跳、反彈、活力、跳動、使彈起、退票", "ipa": "/baʊns/", "trans": "bouncy", "col": "bounce back", "ex": "The ball bounced off the wall.", "pos": "v./n."},
    "bound": {"def": "受約束的、注定的、界限、範圍、跳躍、跳躍、界鄰", "ipa": "/baʊnd/", "trans": "boundary, binding", "col": "be bound to, out of bounds", "ex": "You are bound to fail if you don't work hard.", "pos": "adj./n./v."},
    "boundary": {"def": "邊界、分界線、範圍", "ipa": "/ˈbaʊndri/", "trans": "bound (形容詞/名詞/動詞)", "col": "set a boundary", "ex": "The river forms the boundary between the two countries.", "pos": "n."},
    "bow": {"def": "鞠躬、屈服、弓、蝴蝶結、鞠躬、彎腰、屈從", "ipa": "/baʊ/ (v.) /bəʊ/ (n.)", "trans": "bowed", "col": "bow to, take a bow, bow tie", "ex": "He bowed to the audience.", "pos": "v./n."},
    "bowel": {"def": "腸、內部", "ipa": "/ˈbaʊəl/", "trans": "bowels", "col": "bowel movement", "ex": "He has a bowel problem.", "pos": "n."},
    "bowl": {"def": "碗、缽、打保齡球、快速行進", "ipa": "/bəʊl/", "trans": "bowling", "col": "soup bowl, sugar bowl", "ex": "She ate a bowl of cereal.", "pos": "n./v."},
    "bowling": {"def": "保齡球運動", "ipa": "/ˈbəʊlɪŋ/", "trans": "bowl (動詞)", "col": "go bowling, bowling alley", "ex": "We went bowling last night.", "pos": "n."},
    "box": {"def": "盒子、箱子、包廂、裝入盒中、拳擊", "ipa": "/bɒks/", "trans": "boxing", "col": "post office box, box office", "ex": "Put the toys in the box.", "pos": "n./v."},
    "boxing": {"def": "拳擊", "ipa": "/ˈbɒksɪŋ/", "trans": "box (動詞)", "col": "boxing match, boxing gloves", "ex": "Boxing is a tough sport.", "pos": "n."},
    "boy": {"def": "男孩、兒子、僕人", "ipa": "/bɔɪ/", "trans": "boyhood", "col": "boy scout", "ex": "He's a very clever boy.", "pos": "n."},
    "boycott": {"def": "抵制、拒絕參加、聯合抵制", "ipa": "/ˈbɔɪkɒt/", "trans": "boycotting", "col": "international boycott", "ex": "They are boycotting the product because of its high price.", "pos": "v./n."},
    "boyfriend": {"def": "男朋友", "ipa": "/ˈbɔɪfrend/", "trans": "boyfriends", "col": "former boyfriend", "ex": "She introduced her boyfriend to her parents.", "pos": "n."},
    "brace": {"def": "支架、大括號、一雙、支撐、使防備、緊縛", "ipa": "/breɪs/", "trans": "bracing", "col": "brace yourself", "ex": "He was wearing a knee brace after the injury.", "pos": "n./v."},
    "bracelet": {"def": "手鐲、手鍊", "ipa": "/ˈbreɪslət/", "trans": "bracelets", "col": "gold bracelet", "ex": "She received a gold bracelet for her birthday.", "pos": "n."},
    "bracket": {"def": "括號、組、階層、把...括在一起、放在同一類", "ipa": "/ˈbrækɪt/", "trans": "brackets", "col": "income bracket", "ex": "Please put the reference in brackets.", "pos": "n./v."},
    "brag": {"def": "吹噓、自誇、吹牛", "ipa": "/bræɡ/", "trans": "braggart", "col": "brag about", "ex": "He's always bragging about how much money he makes.", "pos": "v./n."},
    "braille": {"def": "點字、盲文", "ipa": "/breɪl/", "trans": "Braille", "col": "read braille", "ex": "The book is also available in Braille.", "pos": "n."},
    "brain": {"def": "大腦、智商、頭腦、打破...的頭、擊落其頭部", "ipa": "/breɪn/", "trans": "brainy", "col": "brain drain, brain wash", "ex": "Smoking causes damage to the brain.", "pos": "n./v."},
    "brake": {"def": "煞車、阻礙、煞車、制動", "ipa": "/breɪk/", "trans": "braking", "col": "hand brake, electronic brake", "ex": "He slammed on the brakes to avoid the dog.", "pos": "n./v."},
    "branch": {"def": "樹枝、分公司、支流、分岔、分支", "ipa": "/brɑːntʃ/", "trans": "branches", "col": "branch office, tree branch", "ex": "The company is opening a new branch in Tokyo.", "pos": "n./v."},
    "brand": {"def": "品牌、類型、烙印、印商標於、加污名於", "ipa": "/brænd/", "trans": "branded", "col": "brand name, brand new", "ex": "What's your favorite brand of coffee?", "pos": "n./v."},
    "brass": {"def": "黃銅、銅管樂器、高官、黃銅製的", "ipa": "/brɑːs/", "trans": "brassy", "col": "brass band, top brass", "ex": "The door handle is made of brass.", "pos": "n./adj."},
    "brave": {"def": "勇敢的、壯麗的、勇敢的人、冒險、勇敢地面對", "ipa": "/breɪv/", "trans": "bravery, bravely", "col": "brave new world", "ex": "He was a brave soldier.", "pos": "adj./n./v."},
    "bravery": {"def": "勇敢、勇氣、華麗", "ipa": "/ˈbreɪvəri/", "trans": "brave (形容詞)", "col": "act of bravery", "ex": "She was awarded a medal for bravery.", "pos": "n."},
    "breach": {"def": "違反、破壞、缺口、違反、破開", "ipa": "/briːtʃ/", "trans": "breaching", "col": "breach of contract, security breach", "ex": "The company was sued for breach of contract.", "pos": "n./v."},
    "bread": {"def": "麵包、生計、錢", "ipa": "/bred/", "trans": "breadcrumbs", "col": "white bread, bread and butter", "ex": "I'd like a slice of bread.", "pos": "n."},
    "breadth": {"def": "寬度、幅度、胸襟", "ipa": "/bredθ/", "trans": "broad", "col": "breadth of knowledge", "ex": "The breadth of his knowledge is amazing.", "pos": "n."},
    "break": {"def": "打破、弄壞、休息、突破、突破、機會", "ipa": "/breɪk/", "trans": "breakage, broken", "col": "break in, break out, coffee break", "ex": "Handle with care; it's easy to break.", "pos": "v./n."},
    "breakdown": {"def": "故障、崩潰、分析", "ipa": "/ˈbreɪkdaʊn/", "trans": "break down", "col": "nervous breakdown, mechanical breakdown", "ex": "The car had a breakdown on the highway.", "pos": "n."},
    "breakfast": {"def": "早餐、吃早餐", "ipa": "/ˈbrekfəst/", "trans": "breakfasts", "col": "have breakfast", "ex": "I usually have eggs for breakfast.", "pos": "n./v."},
    "breakthrough": {"def": "突破、重大發現", "ipa": "/ˈbreɪkθruː/", "trans": "break through", "col": "scientific breakthrough", "ex": "Scientists have made a major breakthrough in cancer research.", "pos": "n."},
    "breakup": {"def": "解散、崩解、分手", "ipa": "/ˈbreɪkʌp/", "trans": "break up", "col": "marriage breakup", "ex": "He was devastated by the breakup of his marriage.", "pos": "n."},
    "breast": {"def": "胸部、乳房、胸懷、挺拔地面對", "ipa": "/brest/", "trans": "breasts", "col": "breast cancer, chicken breast", "ex": "The baby was nursing at its mother's breast.", "pos": "n./v."},
    "breath": {"def": "呼吸、氣息、微風", "ipa": "/breθ/", "trans": "breathe (動詞)", "col": "bad breath, take a breath, catch one's breath", "ex": "Hold your breath.", "pos": "n."},
    "breathe": {"def": "呼吸、吸入、流露", "ipa": "/briːð/", "trans": "breath (名詞), breathing", "col": "breathe in, breathe out", "ex": "It's difficult to breathe at high altitudes.", "pos": "v."},
    "breed": {"def": "繁殖、飼養、釀成、品種、種類", "ipa": "/briːd/", "trans": "breeding, breeder", "col": "rare breed", "ex": "He breeds horses on his farm.", "pos": "v./n."},
    "breeze": {"def": "微風、輕而易舉的事、輕盈地走、吹微風", "ipa": "/briːz/", "trans": "breezy", "col": "sea breeze, gentle breeze", "ex": "A light breeze was blowing from the sea.", "pos": "n./v."},
    "brew": {"def": "釀造、泡（茶、咖啡）、釀造物", "ipa": "/bruː/", "trans": "brewer, brewery", "col": "brew beer, brew tea", "ex": "The beer is brewed locally.", "pos": "v./n."},
    "bribe": {"def": "賄賂、賄賂、收買", "ipa": "/braɪb/", "trans": "bribery", "col": "accept a bribe", "ex": "He was accused of taking a bribe.", "pos": "n./v."},
    "bribery": {"def": "賄賂、行賄", "ipa": "/ˈbraɪbəri/", "trans": "bribe (名詞/動詞)", "col": "corruption and bribery", "ex": "The politician was convicted of bribery.", "pos": "n."},
    "brick": {"def": "磚塊、好人、用磚圍住、磚紅色的", "ipa": "/brɪk/", "trans": "bricks", "col": "brick wall, red brick", "ex": "The house is made of red brick.", "pos": "n./v./adj."},
    "bride": {"def": "新娘", "ipa": "/braɪd/", "trans": "bridal", "col": "bride and groom", "ex": "The bride looked beautiful in her white dress.", "pos": "n."},
    "bridge": {"def": "橋、橋樑、艦橋、橫跨、架橋於", "ipa": "/brɪdʒ/", "trans": "bridges", "col": "Golden Gate Bridge, bridge the gap", "ex": "We walked across the bridge.", "pos": "n./v."},
    "brief": {"def": "簡短的、短暫的、摘要、簡報、向...做簡報、摘要", "ipa": "/briːf/", "trans": "briefing, briefly", "col": "in brief, brief summary", "ex": "He gave a brief description of the incident.", "pos": "adj./n./v."},
    "briefing": {"def": "簡報、彙報", "ipa": "/ˈbriːfɪŋ/", "trans": "brief (形容詞/名詞/動詞)", "col": "press briefing, daily briefing", "ex": "The soldiers were given a final briefing before the mission.", "pos": "n."},
    "briefly": {"def": "簡短地、短暫地", "ipa": "/ˈbriːfli/", "trans": "brief (形容詞)", "col": "briefly explain", "ex": "She spoke briefly about her travel experiences.", "pos": "adv."},
    "bright": {"def": "明亮的、聰明的、鮮豔的、明亮地", "ipa": "/braɪt/", "trans": "brighten, brightness", "col": "bright idea, look on the bright side", "ex": "The sun is very bright today.", "pos": "adj./adv."},
    "brighten": {"def": "使發亮、使快活、變亮", "ipa": "/ˈbraɪtn/", "trans": "bright (形容詞)", "col": "brighten someone's day", "ex": "The sun soon brightened the room.", "pos": "v."},
    "brilliant": {"def": "卓越的、燦爛的、才華橫溢的", "ipa": "/ˈbrɪliənt/", "trans": "brilliance, brilliantly", "col": "brilliant performance, brilliant student", "ex": "He is a brilliant scientist.", "pos": "adj."},
    "bring": {"def": "帶來、引起、導向", "ipa": "/brɪŋ/", "trans": "brought", "col": "bring about, bring back, bring up", "ex": "Don't forget to bring your umbrella.", "pos": "v."},
    "brisk": {"def": "活潑的、輕快的、寒冷而清新的", "ipa": "/brɪsk/", "trans": "briskly", "col": "brisk walk", "ex": "We took a brisk walk in the park.", "pos": "adj."},
    "bristle": {"def": "短而硬的毛、毛髮直立、憤怒", "ipa": "/ˈbrɪsl/", "trans": "bristly", "col": "stiff bristles", "ex": "The cat's fur bristled with anger.", "pos": "n./v."},
    "British": {"def": "英國的、大不列顛的、英國人", "ipa": "/ˈbrɪtɪʃ/", "trans": "Britain", "col": "British English, British Council", "ex": "He is of British descent.", "pos": "adj./n."},
    "broad": {"def": "寬闊的、廣泛的、宏大的、寬度、廣闊地", "ipa": "/brɔːd/", "trans": "broaden, breadth", "col": "broad daylight, abroad, broaden one's horizons", "ex": "The river is very broad here.", "pos": "adj./n./adv."},
    "broadcast": {"def": "廣播（節目）、播送、廣播、傳播、播送地", "ipa": "/ˈbrɔːdkɑːst/", "trans": "broadcaster, broadcasting", "col": "live broadcast, radio broadcast", "ex": "The news is broadcast every hour.", "pos": "n./v./adv."},
    "broaden": {"def": "變寬、擴大、加寬", "ipa": "/ˈbrɔːdn/", "trans": "broad (形容詞)", "col": "broaden one's horizons", "ex": "Travel broadens the mind.", "pos": "v."},
    "broccoli": {"def": "花椰菜", "ipa": "/ˈbrɒkəli/", "trans": "broccoli", "col": "steamed broccoli", "ex": "She likes to eat broccoli with cheese sauce.", "pos": "n."},
    "brochure": {"def": "手冊、小冊子", "ipa": "/ˈbrəʊʃə/", "trans": "brochures", "col": "travel brochure", "ex": "I've sent for some travel brochures.", "pos": "n."},
    "broke": {"def": "破產的、身無分文的、break的過去式", "ipa": "/brəʊk/", "trans": "break (動詞)", "col": "go broke", "ex": "The company went broke last year.", "pos": "adj./v."},
    "bronze": {"def": "青銅、青銅製品、青銅色、青銅製的、使變青銅色", "ipa": "/brɒnz/", "trans": "bronzed", "col": "bronze medal", "ex": "He won a bronze medal in the Olympics.", "pos": "n./adj./v."},
    "brook": {"def": "小溪、河、忍受、容許", "ipa": "/brʊk/", "trans": "brooks", "col": "babbling brook", "ex": "The water in the brook is crystal clear.", "pos": "n./v."},
    "broom": {"def": "掃帚、金雀花、用掃帚掃", "ipa": "/bruːm/", "trans": "brooms", "col": "new broom", "ex": "A new broom sweeps clean.", "pos": "n./v."},
    "brother": {"def": "兄弟、同胞、教友", "ipa": "/ˈbrʌðə/", "trans": "brotherhood", "col": "elder brother, stepbrother", "ex": "He's like a brother to me.", "pos": "n."},
    "brow": {"def": "額頭、眉毛、山脊", "ipa": "/braʊ/", "trans": "eyebrow", "col": "knit one's brow", "ex": "He wiped the sweat from his brow.", "pos": "n."},
    "brown": {"def": "棕色的、褐色的、棕色、褐色、使成棕色", "ipa": "/braʊn/", "trans": "brownish", "col": "brown sugar, brown bread", "ex": "She has long brown hair.", "pos": "adj./n./v."},
    "browse": {"def": "瀏覽、吃草、嫩枝、草", "ipa": "/braʊz/", "trans": "browser", "col": "browse the web", "ex": "I'm just browsing, thanks.", "pos": "v./n."},
    "browser": {"def": "瀏覽器、吃嫩葉的動物", "ipa": "/ˈbraʊzə/", "trans": "browse (動詞)", "col": "web browser", "ex": "Which browser do you use?", "pos": "n."},
    "bruise": {"def": "瘀青、傷痕、擦傷、碰撞、使瘀傷、在...上留下傷痕", "ipa": "/bruːz/", "trans": "bruised", "col": "nasty bruise", "ex": "He had a large bruise on his arm.", "pos": "n./v."},
    "brush": {"def": "刷子、毛筆、灌木叢、小衝突、刷、擦、拂、掠過", "ipa": "/brʌʃ/", "trans": "brushing", "col": "toothbrush, hairbrush, paint brush", "ex": "Don't forget to brush your teeth.", "pos": "n./v."},
    "brutal": {"def": "殘暴的、野蠻的、冷酷的", "ipa": "/ˈbruːtl/", "trans": "brutality, brutally", "col": "brutal murder", "ex": "The attack was described as brutal and senseless.", "pos": "adj."},
    "bubble": {"def": "氣泡、泡沫、幻想、冒泡、沸騰", "ipa": "/ˈbʌbl/", "trans": "bubbly", "col": "soap bubble, bubble gum, economic bubble", "ex": "The water began to bubble.", "pos": "n./v."},
    "bucket": {"def": "水桶、吊桶、一大桶、用桶提、下大雨", "ipa": "/ˈbʌkɪt/", "trans": "buckets", "col": "bucket list, rain in buckets", "ex": "He filled the bucket with water.", "pos": "n./v."},
    "bud": {"def": "芽、花蕾、初學者、發芽、萌芽", "ipa": "/bʌd/", "trans": "budding", "col": "nip in the bud", "ex": "The roses are in bud.", "pos": "n./v."},
}

with open("batch_l3_p6.json", "w", encoding="utf-8") as f:
    json.dump(L3_PART6, f, ensure_ascii=False, indent=2)
