import json

# Level 3 Part 10: (Construct - Courage)
L3_PART10 = {
    "construct": {"def": "建造、構成、創立、建築物、構想", "ipa": "/kənˈstrʌkt/", "trans": "construction, constructive", "col": "construct a building", "ex": "The bridge was constructed in the nineteenth century.", "pos": "v./n."},
    "construction": {"def": "建造、結構、解釋", "ipa": "/kənˈstrʌkʃn/", "trans": "construct (動詞)", "col": "under construction, construction site", "ex": "The new skyscraper is currently under construction.", "pos": "n."},
    "constructive": {"def": "建設性的、積極的、結構上的", "ipa": "/kənˈstrʌktɪv/", "trans": "construct (動詞), constructively", "col": "constructive criticism", "ex": "She gave me some constructive criticism on my essay.", "pos": "adj."},
    "consult": {"def": "諮詢、向...請教、查閱", "ipa": "/kənˈsʌlt/", "trans": "consultant, consultation", "col": "consult a lawyer, consult a dictionary", "ex": "If the symptoms persist, consult your doctor.", "pos": "v."},
    "consultant": {"def": "顧問、諮詢者、會診醫生", "ipa": "/kənˈsʌltənt/", "trans": "consult (動詞)", "col": "management consultant", "ex": "The company hired a marketing consultant.", "pos": "n."},
    "consultation": {"def": "諮詢、商量、會議", "ipa": "/ˌkɒnslˈteɪʃn/", "trans": "consult (動詞)", "col": "medical consultation", "ex": "The decision was made in consultation with legal experts.", "pos": "n."},
    "consume": {"def": "消耗、消費、吃、喝", "ipa": "/kənˈsjuːm/", "trans": "consumer, consumption", "col": "time consuming", "ex": "The car consumes a lot of fuel.", "pos": "v."},
    "consumer": {"def": "消費者、用戶", "ipa": "/kənˈsjuːmə/", "trans": "consume (動詞)", "col": "consumer goods, consumer rights", "ex": "Consumers are demanding better quality products.", "pos": "n."},
    "consumption": {"def": "消耗、消費、肺結核", "ipa": "/kənˈsʌmpʃn/", "trans": "consume (動詞)", "col": "energy consumption, internal consumption", "ex": "The goal is to reduce energy consumption.", "pos": "n."},
    "contact": {"def": "接觸、聯繫、聯絡、聯繫人、聯繫、聯絡、接觸", "ipa": "/ˈkɒntækt/", "trans": "contacts", "col": "in contact with, eye contact, point of contact", "ex": "Please feel free to contact me if you have any questions.", "pos": "n./v."},
    "contain": {"def": "包含、容納、抑制", "ipa": "/kənˈteɪn/", "trans": "container", "col": "contain information", "ex": "The book contains a list of important dates.", "pos": "v."},
    "container": {"def": "容器、貨櫃", "ipa": "/kənˈteɪnə/", "trans": "contain (動詞)", "col": "sealed container, shipping container", "ex": "The food should be kept in a sealed container.", "pos": "n."},
    "contaminate": {"def": "污染、弄髒、毒害", "ipa": "/kənˈtæmɪneɪt/", "trans": "contamination", "col": "be contaminated with", "ex": "The river has been contaminated with industrial waste.", "pos": "v."},
    "contamination": {"def": "污染、污染物", "ipa": "/kənˌtæmɪˈneɪʃn/", "trans": "contaminate (動詞)", "col": "environmental contamination", "ex": "The health department is investigating the sources of contamination.", "pos": "n."},
    "contemplate": {"def": "沉思、注視、預期", "ipa": "/ˈkɒntəmpleɪt/", "trans": "contemplation", "col": "contemplate marriage", "ex": "He sat there contemplating his future.", "pos": "v."},
    "contemplation": {"def": "沉思、冥想、期望", "ipa": "/ˌkɒntəmˈpleɪʃn/", "trans": "contemplate (動詞)", "col": "deep contemplation", "ex": "She was lost in deep contemplation.", "pos": "n."},
    "contemporary": {"def": "同時代的、現代的、同時代的人", "ipa": "/kənˈtemprəri/", "trans": "contemporaries", "col": "contemporary art, contemporary music", "ex": "The museum exhibits contemporary art.", "pos": "adj./n."},
    "contempt": {"def": "輕視、蔑視、不顧", "ipa": "/kənˈtempt/", "trans": "contemptuous", "col": "show contempt for", "ex": "He showed total contempt for the rules.", "pos": "n."},
    "contend": {"def": "鬥爭、競爭、主張、聲稱", "ipa": "/kənˈtend/", "trans": "contender, contention", "col": "contend against", "ex": "The two countries are contending for regional dominance.", "pos": "v."},
    "contender": {"def": "競爭者、爭奪者", "ipa": "/kənˈtendə/", "trans": "contend (動詞)", "col": "top contender", "ex": "He is a top contender for the world title.", "pos": "n."},
    "content": {"def": "滿足的、滿意的、內容、目錄、使滿足、容量", "ipa": "/ˈkɒntent/ (n.) /kənˈtent/ (adj./v.)", "trans": "contentment", "col": "table of contents, digital content, be content with", "ex": "The content of the letter was surprising.", "pos": "adj./n./v."},
    "contentment": {"def": "滿足、滿意", "ipa": "/kənˈtentmənt/", "trans": "content (形容詞/動詞)", "col": "find contentment", "ex": "He lived a life of peace and contentment.", "pos": "n."},
    "contest": {"def": "競爭、比賽、爭奪、爭取、質疑", "ipa": "/ˈkɒntest/ (n.) /kənˈtest/ (v.)", "trans": "contestant", "col": "beauty contest, song contest", "ex": "She won the beauty contest last year.", "pos": "n./v."},
    "contestant": {"def": "參賽者、競爭者", "ipa": "/kənˈtestənt/", "trans": "contest (動詞/名詞)", "col": "successful contestant", "ex": "There are ten contestants left in the competition.", "pos": "n."},
    "context": {"def": "上下文、背景、環境", "ipa": "/ˈkɒntekst/", "trans": "contextualize", "col": "in context, historical context", "ex": "The sentence must be read in context.", "pos": "n."},
    "continent": {"def": "大陸、洲、克制的", "ipa": "/ˈkɒntɪnənt/", "trans": "continental", "col": "African continent", "ex": "Asia is the largest continent in the world.", "pos": "n./adj."},
    "continental": {"def": "大陸的、洲的、歐洲大陸的", "ipa": "/ˌkɒntɪˈnentl/", "trans": "continent (名詞)", "col": "continental breakfast", "ex": "We had a continental breakfast at the hotel.", "pos": "adj."},
    "continual": {"def": "不斷的、頻繁的", "ipa": "/kənˈtɪnjuəl/", "trans": "continually", "col": "continual change", "ex": "The project was delayed by continual technical problems.", "pos": "adj."},
    "continuation": {"def": "繼續、續篇", "ipa": "/kənˌtɪnjuˈeɪʃn/", "trans": "continue (動詞)", "col": "continuation of the story", "ex": "The film is a continuation of the previous one.", "pos": "n."},
    "continue": {"def": "繼續、連續、延伸", "ipa": "/kənˈtɪnjuː/", "trans": "continuation, continuous", "col": "continue to do, to be continued", "ex": "The rain continued for three days.", "pos": "v."},
    "continuity": {"def": "連續性、連貫性、戲路", "ipa": "/ˌkɒntɪˈnjuːəti/", "trans": "continuous", "col": "lack of continuity", "ex": "The new manager is aiming for better continuity in the team.", "pos": "n."},
    "continuous": {"def": "連續的、不斷的、連續函數的", "ipa": "/kənˈtɪnjuəs/", "trans": "continuity", "col": "continuous improvement", "ex": "The machine was in continuous use for twenty-four hours.", "pos": "adj."},
    "contract": {"def": "合約、契約、感染、簽約、縮小、訂約", "ipa": "/ˈkɒntrækt/ (n.) /kənˈtrækt/ (v.)", "trans": "contraction, contractor", "col": "sign a contract, under contract, breach of contract", "ex": "He has signed a three-year contract with the club.", "pos": "n./v."},
    "contractor": {"def": "承包商、承包者", "ipa": "/kənˈtræktə/", "trans": "contract (動詞/名詞)", "col": "building contractor", "ex": "The work was carried out by a local contractor.", "pos": "n."},
    "contradict": {"def": "反駁、與...矛盾、否定", "ipa": "/ˌkɒntrəˈdɪkt/", "trans": "contradiction, contradictory", "col": "contradict oneself", "ex": "He contradicted everything I said.", "pos": "v."},
    "contradiction": {"def": "矛盾、反駁、否定", "ipa": "/ˌkɒntrəˈdɪkʃn/", "trans": "contradict (動詞)", "col": "direct contradiction", "ex": "There is a direct contradiction between his words and his actions.", "pos": "n."},
    "contradictory": {"def": "矛盾的、對立的", "ipa": "/ˌkɒntrəˈdɪktəri/", "trans": "contradict (動詞)", "col": "contradictory evidence", "ex": "The two reports gave contradictory accounts of the incident.", "pos": "adj."},
    "contrary": {"def": "相反的、對抗的、倔強的、相反的事、反面、相反地", "ipa": "/ˈkɒntrəri/", "trans": "contrast", "col": "on the contrary, contrary to", "ex": "Contrary to my expectations, the movie was very good.", "pos": "adj./n./adv."},
    "contrast": {"def": "對比、對照、差異、與...形成對照、對比", "ipa": "/ˈkɒntrɑːst/ (n.) /kənˈtrɑːst/ (v.)", "trans": "contrasting", "col": "in contrast to, stark contrast", "ex": "The white walls provide a stark contrast to the dark floor.", "pos": "n./v."},
    "contribute": {"def": "貢獻、投稿、助長", "ipa": "/kənˈtrɪbjuːt/", "trans": "contribution, contributor", "col": "contribute to", "ex": "He contributed a lot of money to the charity.", "pos": "v."},
    "contribution": {"def": "貢獻、捐款、投稿", "ipa": "/ˌkɒntrɪˈbjuːʃn/", "trans": "contribute (動詞)", "col": "valuable contribution, make a contribution", "ex": "She made a valuable contribution to the discussion.", "pos": "n."},
    "contributor": {"def": "貢獻者、投稿人、成因", "ipa": "/kənˈtrɪbjətə/", "trans": "contribute (動詞)", "col": "major contributor", "ex": "He is a frequent contributor to the magazine.", "pos": "n."},
    "control": {"def": "控制、管理、操縱裝置、控制、支配、抑制", "ipa": "/kənˈtrəʊl/", "trans": "controller, controlling", "col": "under control, out of control, remote control", "ex": "The fire is now under control.", "pos": "n./v."},
    "controversial": {"def": "有爭議的、引起爭論的", "ipa": "/ˌkɒntrəˈvɜːʃl/", "trans": "controversy", "col": "controversial issue", "ex": "Abortion is a highly controversial issue.", "pos": "adj."},
    "controversy": {"def": "爭議、辯論", "ipa": "/ˈkɒntrəvɜːsi/", "trans": "controversial", "col": "cause controversy", "ex": "The decision caused a lot of controversy.", "pos": "n."},
    "convenience": {"def": "方便、便利、便利設施", "ipa": "/kənˈviːniəns/", "trans": "convenient", "col": "convenience store, for convenience", "ex": "I like the convenience of living near a subway station.", "pos": "n."},
    "convenient": {"def": "方便的、適合的", "ipa": "/kənˈviːniənt/", "trans": "convenience (名詞), conveniently", "col": "convenient time", "ex": "Will tomorrow be a convenient time for us to meet?", "pos": "adj."},
    "convention": {"def": "大會、慣例、協定", "ipa": "/kənˈvenʃn/", "trans": "conventional", "col": "annual convention, social convention", "ex": "He defied social convention by traveling alone.", "pos": "n."},
    "conventional": {"def": "傳統的、慣例的、常規的", "ipa": "/kənˈvenʃənl/", "trans": "convention (名詞), conventionally", "col": "conventional wisdom, conventional weapons", "ex": "She lives a very conventional life.", "pos": "adj."},
    "conversation": {"def": "談話、會話", "ipa": "/ˌkɒnvəˈseɪʃn/", "trans": "conversational", "col": "have a conversation", "ex": "I had a long conversation with him yesterday.", "pos": "n."},
    "conversational": {"def": "對話的、口語的、口才好的", "ipa": "/ˌkɒnvəˈseɪʃənl/", "trans": "conversation (名詞)", "col": "conversational English", "ex": "The book is written in a conversational style.", "pos": "adj."},
    "converse": {"def": "交談、談話、相反的、逆向的、相反的事物、逆命題", "ipa": "/kənˈvɜːs/ (v.) /ˈkɒnvɜːs/ (adj./n.)", "trans": "conversely", "col": "the converse is true", "ex": "He was conversing with his friends in the corner.", "pos": "v./adj./n."},
    "conversion": {"def": "轉換、轉變、宗教信仰的改變", "ipa": "/kənˈvɜːʃn/", "trans": "convert (動詞)", "col": "currency conversion", "ex": "The conversion of the palace into a hotel was a huge project.", "pos": "n."},
    "convert": {"def": "轉換、轉變、改變信仰、皈依者、轉化者", "ipa": "/kənˈvɜːt/ (v.) /ˈkɒnvɜːt/ (n.)", "trans": "conversion", "col": "convert into, convert to", "ex": "The loft was converted into a bedroom.", "pos": "v./n."},
    "convey": {"def": "傳達、運送、轉讓", "ipa": "/kənˈveɪ/", "trans": "conveyance", "col": "convey a message", "ex": "Colors can convey different meanings.", "pos": "v."},
    "convict": {"def": "宣判有罪、證明...有罪、囚犯、受刑人", "ipa": "/kənˈvɪkt/ (v.) /ˈkɒnvɪkt/ (n.)", "trans": "conviction", "col": "convict of", "ex": "He was convicted of murder.", "pos": "v./n."},
    "conviction": {"def": "定罪、信念、說服力", "ipa": "/kənˈvɪkʃn/", "trans": "convict (動詞/名詞)", "col": "strong conviction", "ex": "She has a strong conviction that she is right.", "pos": "n."},
    "convince": {"def": "說服、使信服", "ipa": "/kənˈvɪns/", "trans": "convincing", "col": "convince someone of", "ex": "I managed to convince him that he should come with us.", "pos": "v."},
    "convincing": {"def": "有說服力的、令人信服的", "ipa": "/kənˈvɪnsɪŋ/", "trans": "convince (動詞), convincingly", "col": "convincing argument", "ex": "He gave a very convincing performance.", "pos": "adj."},
    "cook": {"def": "烹調、煮飯、廚師", "ipa": "/kʊk/", "trans": "cookbox, cooking", "col": "cook lunch, head cook", "ex": "She is a very good cook.", "pos": "v./n."},
    "cooker": {"def": "炊具、爐灶、烹調用具", "ipa": "/ˈkʊkə/", "trans": "cook (動詞/名詞)", "col": "gas cooker, pressure cooker", "ex": "The dinner is cooking on the gas cooker.", "pos": "n."},
    "cookie": {"def": "餅乾、小甜點", "ipa": "/ˈkʊki/", "trans": "cookies", "col": "fortune cookie, chocolate chip cookie", "ex": "She is baking cookies in the kitchen.", "pos": "n."},
    "cooking": {"def": "烹飪、飯菜、烹飪的", "ipa": "/ˈkʊkɪŋ/", "trans": "cook (動詞/名詞)", "col": "home cooking", "ex": "I enjoy cooking.", "pos": "n./adj."},
    "cool": {"def": "涼快的、冷靜的、絕妙的、使涼快、變涼、涼快、冷靜", "ipa": "/kuːl/", "trans": "coolly, coolness", "col": "keep cool, play it cool", "ex": "The weather is nice and cool today.", "pos": "adj./v./n."},
    "coolant": {"def": "冷卻劑、潤滑液", "ipa": "/ˈkuːlənt/", "trans": "coolants", "col": "engine coolant", "ex": "The car needs some more coolant.", "pos": "n."},
    "cooperate": {"def": "合作、協作、配合", "ipa": "/kəʊˈɒpəreɪt/", "trans": "cooperation, cooperative", "col": "cooperate with", "ex": "The police are asking the public to cooperate with them.", "pos": "v."},
    "cooperation": {"def": "合作、協作", "ipa": "/kəʊˌɒpəˈreɪʃn/", "trans": "cooperate (動詞)", "col": "international cooperation", "ex": "The project was a success thanks to the cooperation of all the team members.", "pos": "n."},
    "cooperative": {"def": "合作的、樂意配合的、合作社", "ipa": "/kəʊˈɒpərətɪv/", "trans": "cooperate (動詞), cooperatively", "col": "cooperative effort", "ex": "They are a very cooperative team.", "pos": "adj./n."},
    "coordinate": {"def": "協調、調節、座標、座標的、同等的、並列的", "ipa": "/kəʊˈɔːdɪneɪt/ (v.) /kəʊˈɔːdɪnət/ (n./adj.)", "trans": "coordination, coordinator", "col": "coordinate activities", "ex": "The mission was a carefully coordinated effort.", "pos": "v./n./adj."},
    "coordination": {"def": "協調、調節、配合", "ipa": "/kəʊˌɔːdɪˈneɪʃn/", "trans": "coordinate (動詞)", "col": "lack of coordination", "ex": "Good coordination is necessary for this game.", "pos": "n."},
    "coordinator": {"def": "協調者、統籌人", "ipa": "/kəʊˈɔːdɪneɪtə/", "trans": "coordinate (動詞)", "col": "project coordinator", "ex": "He is the project coordinator for the new development.", "pos": "n."},
    "cope": {"def": "應付、對付、妥善處理", "ipa": "/kəʊp/", "trans": "coping", "col": "cope with", "ex": "He is struggling to cope with his workload.", "pos": "v."},
    "copper": {"def": "銅、銅幣、銅色的、紅銅色的", "ipa": "/ˈkɒpə/", "trans": "coppery", "col": "copper wire", "ex": "Copper is a good conductor of electricity.", "pos": "n./adj."},
    "copy": {"def": "複製品、拷貝、複寫、複製、抄襲", "ipa": "/ˈkɒpi/", "trans": "copier", "col": "copy and paste, carbon copy, hard copy", "ex": "Can you make a copy of this document for me?", "pos": "n./v."},
    "copyright": {"def": "版權、著作權、獲得...的版權、版權專有的", "ipa": "/ˈkɒpiraɪt/", "trans": "copyrights", "col": "copyright law, protected by copyright", "ex": "The book is protected by copyright.", "pos": "n./v./adj."},
    "coral": {"def": "珊瑚、珊瑚蟲、珊瑚色的", "ipa": "/ˈkɒrəl/", "trans": "corals", "col": "coral reef", "ex": "The island is surrounded by beautiful coral reefs.", "pos": "n./adj."},
    "cord": {"def": "繩、索、電線、解剖構造中的索狀組織、用繩子縛", "ipa": "/kɔːd/", "trans": "cordless", "col": "vocal cords, spinal cord, power cord", "ex": "He used a piece of cord to tie the boxes together.", "pos": "n./v."},
    "cordial": {"def": "熱忱的、誠懇的、果汁飲料、甜酒", "ipa": "/ˈkɔːdiəl/", "trans": "cordiality", "col": "cordial welcome", "ex": "They received a cordial welcome.", "pos": "adj./n."},
    "cordless": {"def": "無線的", "ipa": "/ˈkɔːdləs/", "trans": "cord (名詞)", "col": "cordless phone, cordless drill", "ex": "She has a cordless phone in her kitchen.", "pos": "adj."},
    "core": {"def": "核心、果核、最重要部分、核心的、去核", "ipa": "/kɔː/", "trans": "coring", "col": "core curriculum, at the core of", "ex": "The core of the problem is lack of communication.", "pos": "n./adj./v."},
    "cork": {"def": "軟木塞、軟木、塞住、抑制", "ipa": "/kɔːk/", "trans": "corks", "col": "cork screw", "ex": "He pulled the cork out of the bottle.", "pos": "n./v."},
    "corn": {"def": "玉米、穀物、雞眼", "ipa": "/kɔːn/", "trans": "corny", "col": "corn flake, sweet corn", "ex": "The field is covered with corn.", "pos": "n."},
    "corner": {"def": "角落、困境、轉角處、將...逼入死角、囤積、壟斷", "ipa": "/ˈkɔːnə/", "trans": "corners", "col": "around the corner, cut corners, street corner", "ex": "His house is on the corner of the street.", "pos": "n./v."},
    "corny": {"def": "陳腔濫調的、沒意思、多雞眼的", "ipa": "/ˈkɔːni/", "trans": "corn (名詞)", "col": "corny joke", "ex": "He keeps telling corny jokes.", "pos": "adj."},
    "corporal": {"def": "下士、身體的、肉體的", "ipa": "/ˈkɔːpərəl/", "trans": "corporals", "col": "corporal punishment", "ex": "Corporal punishment was banned in schools years ago.", "pos": "n./adj."},
    "corporate": {"def": "公司的、法人的、共同的", "ipa": "/ˈkɔːpərət/", "trans": "corporation", "col": "corporate identity, corporate ladder", "ex": "He works for a large corporate organization.", "pos": "adj."},
    "corporation": {"def": "大公司、法人", "ipa": "/ˌkɔːpəˈreɪʃn/", "trans": "corporate (形容詞)", "col": "multinational corporation", "ex": "He works for an international corporation.", "pos": "n."},
    "corps": {"def": "部隊、團、兵種", "ipa": "/kɔː/", "trans": "corps", "col": "Peace Corps, diplomatic corps", "ex": "He joined the medical corps during the war.", "pos": "n."},
    "corpse": {"def": "屍體", "ipa": "/kɔːps/", "trans": "corpses", "col": "human corpse", "ex": "The police found a corpse in the river.", "pos": "n."},
    "correct": {"def": "正確的、恰當的、改正、糾正", "ipa": "/kəˈrekt/", "trans": "correction, correctly", "col": "correct answer, politically correct", "ex": "Are these figures correct?", "pos": "adj./v."},
    "correction": {"def": "糾正、修改、懲罰", "ipa": "/kəˈrekʃn/", "trans": "correct (形容詞/動詞)", "col": "market correction, mark corrections", "ex": "He made some corrections to the manuscript.", "pos": "n."},
    "correspond": {"def": "通信、一致、相當", "ipa": "/ˌkɒrəˈspɒnd/", "trans": "correspondence, correspondent", "col": "correspond with, correspond to", "ex": "His actions do not correspond with his words.", "pos": "v."},
    "correspondence": {"def": "通信、信件、一致、相似", "ipa": "/ˌkɒrəˈspɒndəns/", "trans": "correspond (動詞)", "col": "business correspondence", "ex": "There has been a lot of correspondence between the two companies.", "pos": "n."},
    "correspondent": {"def": "通訊員、記者、通信者", "ipa": "/ˌkɒrəˈspɒndənt/", "trans": "correspond (動詞)", "col": "foreign correspondent, war correspondent", "ex": "He is a foreign correspondent for a major newspaper.", "pos": "n."},
    "corridor": {"def": "走廊、通道", "ipa": "/ˈkɒrɪdɔː/", "trans": "corridors", "col": "down the corridor", "ex": "The office is at the end of the corridor.", "pos": "n."},
    "corrupt": {"def": "腐敗的、貪汙的、敗壞、使腐敗、腐爛", "ipa": "/kəˈrʌpt/", "trans": "corruption", "col": "corrupt official", "ex": "The government is trying to clean up corrupt officials.", "pos": "adj./v."},
    "corruption": {"def": "腐敗、貪汙", "ipa": "/kəˈrʌpʃn/", "trans": "corrupt (形容詞/動詞)", "col": "political corruption", "ex": "There were allegations of corruption within the police force.", "pos": "n."},
    "cosmetic": {"def": "化妝用的、美容的、表面的、化妝品", "ipa": "/kɒzˈmetɪk/", "trans": "cosmetics", "col": "cosmetic surgery", "ex": "She is interested in cosmetics.", "pos": "adj./n."},
    "cosmetics": {"def": "化妝品", "ipa": "/kɒzˈmetɪks/", "trans": "cosmetic (形容詞/名詞)", "col": "natural cosmetics", "ex": "She spends a lot of money on cosmetics.", "pos": "n."},
    "cosmopolitan": {"def": "世界性的、國際化的、四海為家的人", "ipa": "/ˌkɒzməˈpɒlɪtən/", "trans": "cosmopolitans", "col": "cosmopolitan city", "ex": "London is a very cosmopolitan city.", "pos": "adj./n."},
    "cost": {"def": "代價、成本、代價是、花費", "ipa": "/kɒst/", "trans": "costly", "col": "at all costs, living cost, low cost", "ex": "The total cost of the project was $1 million.", "pos": "n./v."},
    "costly": {"def": "昂貴的、損失巨大的", "ipa": "/ˈkɒstli/", "trans": "cost (名詞/動詞)", "col": "costly mistake", "ex": "It was a costly mistake.", "pos": "adj."},
    "costume": {"def": "服裝、戲裝、給...穿上服裝", "ipa": "/ˈkɒstjuːm/", "trans": "costumes", "col": "national costume, costume party", "ex": "She was wearing a traditional Chinese costume.", "pos": "n./v."},
    "cottage": {"def": "小木屋、別墅", "ipa": "/ˈkɒtɪdʒ/", "trans": "cottages", "col": "cottage cheese, holiday cottage", "ex": "They lived in a small cottage in the countryside.", "pos": "n."},
    "cotton": {"def": "棉（花）、棉布", "ipa": "/ˈkɒtn/", "trans": "cottony", "col": "cotton candy, cotton field", "ex": "The dress is made of pure cotton.", "pos": "n."},
    "couch": {"def": "長沙發、診察台、用語言表達", "ipa": "/kaʊtʃ/", "trans": "couches", "col": "couch potato", "ex": "I'm sitting on the couch watching TV.", "pos": "n./v."},
    "cough": {"def": "咳嗽、咳嗽聲、咳出、咳嗽", "ipa": "/kɒf/", "trans": "coughing", "col": "dry cough, cough up", "ex": "He has a bad cough.", "pos": "n./v."},
    "council": {"def": "委員會、政務會、議會", "ipa": "/ˈkaʊnsl/", "trans": "councilor", "col": "local council, city council", "ex": "He was elected to the local council.", "pos": "n."},
    "councilor/councillor": {"def": "議員、委員、顧問", "ipa": "/ˈkaʊnsələ/", "trans": "council (名詞)", "col": "town councillor", "ex": "He is a town councillor.", "pos": "n."},
    "counsel": {"def": "建議、忠告、法律顧問、建議、勸告", "ipa": "/ˈkaʊnsl/", "trans": "counseling, counselor", "col": "legal counsel, take counsel", "ex": "The judge gave him some wise counsel.", "pos": "n./v."},
    "counseling": {"def": "諮詢、心理輔導", "ipa": "/ˈkaʊnsəlɪŋ/", "trans": "counsel (名詞/動詞)", "col": "marriage counseling, grief counseling", "ex": "She is undergoing counseling for depression.", "pos": "n."},
    "counselor/counsellor": {"def": "顧問、心理輔導員、法律顧問", "ipa": "/ˈkaʊnsələ/", "trans": "counsel (名詞/動詞)", "col": "school counselor, guidance counselor", "ex": "He is a school counselor.", "pos": "n."},
    "count": {"def": "數、計算、價值、計數、算數、看作", "ipa": "/kaʊnt/", "trans": "counter, counting", "col": "count on, count down, count out", "ex": "Can you count to ten?", "pos": "n./v."},
    "counter": {"def": "櫃台、計數器、反駁、反對地、逆向地、對抗、反駁", "ipa": "/ˈkaʊntə/", "trans": "counting", "col": "checkout counter, over the counter", "ex": "I'll meet you at the checkout counter.", "pos": "n./adv./adj./v."},
    "counter-clockwise": {"def": "逆時針方向的、逆時針方向地", "ipa": "/ˌkaʊntəˈklɒkwaɪz/", "trans": "clockwise", "col": "turn counter-clockwise", "ex": "Turn the lid counter-clockwise to open it.", "pos": "adj./adv."},
    "counterpart": {"def": "相對應的人、極相似物、副本", "ipa": "/ˈkaʊntəpɑːt/", "trans": "counterparts", "col": "male counterpart", "ex": "The foreign minister met with his French counterpart.", "pos": "n."},
    "countless": {"def": "無數的、數不盡的", "ipa": "/ˈkaʊntləs/", "trans": "count (名詞/動詞)", "col": "countless times", "ex": "He has told me the story countless times.", "pos": "adj."},
    "country": {"def": "國家、鄉下、區域", "ipa": "/ˈkʌntri/", "trans": "countryside, countryman", "col": "developing country, country music, in the country", "ex": "France is a beautiful country.", "pos": "n."},
    "countryside": {"def": "鄉下、農村", "ipa": "/ˈkʌntrisaɪd/", "trans": "country (名詞)", "col": "in the countryside", "ex": "We decided to spend the weekend in the countryside.", "pos": "n."},
    "county": {"def": "郡、線、全體縣民", "ipa": "/ˈkaʊnti/", "trans": "counties", "col": "Orange County", "ex": "The county is famous for its cheese.", "pos": "n."},
    "couple": {"def": "一對、夫婦、連接、結合", "ipa": "/ˈkʌpl/", "trans": "coupling", "col": "a couple of, young couple", "ex": "They are a very happy couple.", "pos": "n./v."},
    "coupon": {"def": "折價券、優惠券", "ipa": "/ˈkuːpɒn/", "trans": "coupons", "col": "discount coupon", "ex": "I have a discount coupon for that restaurant.", "pos": "n."},
    "courage": {"def": "勇氣、膽量、英勇", "ipa": "/ˈkʌrɪdʒ/", "trans": "courageous", "col": "take courage, show courage", "ex": "It takes courage to speak the truth.", "pos": "n."},
}

with open("batch_l3_p10.json", "w", encoding="utf-8") as f:
    json.dump(L3_PART10, f, ensure_ascii=False, indent=2)
