import json

# Level 6 Part 33: (Bibulous - Bilk)
L6_PART33 = {
    "bibulous": {"def": "吸水的、飲酒的、好酒的", "ipa": "/ˈbɪbjələs/", "trans": "absorbent", "col": "bibulous nature", "ex": "The bibulous nature of the sponge makes it ideal for cleaning.", "pos": "adj."},
    "bicameral": {"def": "兩院制的", "ipa": "/ˌbaɪˈkæmərəl/", "trans": "legislature", "col": "bicameral system", "ex": "The US Congress is a bicameral legislature.", "pos": "adj."},
    "bicarbonate": {"def": "重碳酸鹽 (單數)", "ipa": "/ˌbaɪˈkɑːbənət/", "trans": "bicarbonates (複數)", "col": "bicarbonate of soda (蘇打粉)", "ex": "You can use bicarbonate of soda as a cleaning agent.", "pos": "n."},
    "bicentenary": {"def": "兩百週年紀念、兩百週年的 (單數)", "ipa": "/ˌbaɪsenˈtiːnəri/", "trans": "bicentenaries (複數)", "col": "celebrate the bicentenary", "ex": "The city celebrated its bicentenary last year.", "pos": "n./adj."},
    "bicentennial": {"def": "兩百週年紀念、兩百週年一次的、每兩百週年地 (兩百)", "ipa": "/ˌbaɪsenˈteniəl/", "trans": "bicentenary", "col": "bicentennial celebration", "ex": "The country marked its bicentennial with a series of events.", "pos": "n./adj./adv."},
    "bicep": {"def": "二頭肌 (單數/常用複數)", "ipa": "/ˈbaɪsep/", "trans": "biceps (複數)", "col": "flexing biceps", "ex": "He was flexing his biceps in front of the mirror.", "pos": "n."},
    "bicker": {"def": "鬥嘴、爭吵、口角的人、吵鬧地 (吵)", "ipa": "/ˈbɪkə/", "trans": "bickering", "col": "bicker about, constant bicker", "ex": "The couple always bickers about small things.", "pos": "v./n./adv."},
    "bickering": {"def": "吵鬧的、爭吵的人 (或物) (吵)", "ipa": "/ˈbɪkərɪŋ/", "trans": "bicker (動詞/名詞/副詞)", "col": "stop bickering", "ex": "I can't stand the constant bickering between them.", "pos": "adj./n./adv."},
    "bicycle": {"def": "自行車、腳踏車、騎自行車、騎車的人物、騎車地 (車)", "ipa": "/ˈbaɪsɪkl/", "trans": "bicycles", "col": "ride a bicycle, mountain bicycle", "ex": "He goes to work by bicycle.", "pos": "n./v./adv."},
    "bicyclist": {"def": "騎自行車者", "ipa": "/ˈbaɪsɪklɪst/", "trans": "cyclist", "col": "professional bicyclist", "ex": "He is a professional bicyclist competing in the race.", "pos": "n."},
    "bid": {"def": "出價、吩咐、投標、嘗試、出價的人 (或物)、投標地 (投)", "ipa": "/bɪd/", "trans": "bids, bidding, bade, bidden", "col": "make a bid, highest bid, takeover bid, bid for power", "ex": "The highest bid for the painting was $1 million.", "pos": "v./n./adv."},
    "bidden": {"def": "(bid的過去分詞)、吩咐、命令", "ipa": "/ˈbɪdn/", "trans": "bid", "col": "bidden guest (受邀客)", "ex": "He was a bidden guest at the wedding.", "pos": "v."},
    "bidder": {"def": "投標人、出價者 (單數)", "ipa": "/ˈbɪdə/", "trans": "bidders (複數)", "col": "highest bidder", "ex": "The house was sold to the highest bidder.", "pos": "n."},
    "bidding": {"def": "命令、出價、吩咐的人 (或物) (令)", "ipa": "/ˈbɪdɪŋ/", "trans": "bid (名詞/動詞/副詞)", "col": "do someone's bidding, initial bidding", "ex": "He is always ready to do his master's bidding.", "pos": "n./adv."},
    "bide": {"def": "等待、逗留、忍耐地 (待)", "ipa": "/baɪd/", "trans": "wait", "col": "bide one's time (伺機而動)", "ex": "We must bide our time and wait for the right moment.", "pos": "v./adv."},
    "biennial": {"def": "兩年一次的、二年生植物、兩年一次地 (兩年)", "ipa": "/baɪˈeniəl/", "trans": "biennials", "col": "biennial event", "ex": "The festival is a biennial event, held every two years.", "pos": "adj./n./adv."},
    "biennially": {"def": "每兩年地、兩年一次地", "ipa": "/baɪˈeniəli/", "trans": "biennial (形容詞/名詞/副詞)", "col": "held biennially", "ex": "The conference is held biennially.", "pos": "adv."},
    "bier": {"def": "屍架、靈柩臺", "ipa": "/bɪə/", "trans": "stretcher", "col": "laid on the bier", "ex": "The body was laid on a flower-covered bier.", "pos": "n."},
    "bifocals": {"def": "雙光眼鏡 (複數)", "ipa": "/ˌbaɪˈfəʊklz/", "trans": "glasses", "col": "pair of bifocals", "ex": "He needs a pair of bifocals for reading.", "pos": "n."},
    "bifurcate": {"def": "分叉、分成兩支、分叉的人 (或物)、分叉地 (叉)", "ipa": "/ˈbaɪfəkeɪt/", "trans": "split", "col": "bifurcate path", "ex": "The river bifurcates at this point.", "pos": "v./n./adv."},
    "bifurcation": {"def": "分叉、分成兩支、分歧點", "ipa": "/ˌbaɪfəˈkeɪʃn/", "trans": "bifurcate (動詞/名詞/副詞)", "col": "strategic bifurcation", "ex": "The road reached a strategic bifurcation.", "pos": "n."},
    "big": {"def": "大的、重要的、大方的、大、誇大地 (大)", "ipa": "/bɪɡ/", "trans": "bigger, biggest", "col": "big brother, big deal, big business, make it big (成功)", "ex": "My house is not very big.", "pos": "adj./adv./n."},
    "bigamist": {"def": "重婚者", "ipa": "/ˈbɪɡəmɪst/", "trans": "bigamy", "col": "accused bigamist", "ex": "He was arrested as an accused bigamist.", "pos": "n."},
    "bigamy": {"def": "重婚罪", "ipa": "/ˈbɪɡəmi/", "trans": "bigamist", "col": "convicted of bigamy", "ex": "He was convicted of bigamy and sentenced to prison.", "pos": "n."},
    "biggie": {"def": "(俚)大人物、重要人物 (單數)", "ipa": "/ˈbɪɡi/", "trans": "biggies (複數)", "col": "corporate biggie", "ex": "He is a biggie in the corporate world.", "pos": "n."},
    "bighearted": {"def": "慷慨的、大方的、仁慈的", "ipa": "/ˌbɪɡˈhɑːtɪd/", "trans": "generous", "col": "bighearted woman", "ex": "She is a bighearted woman who always helps others.", "pos": "adj."},
    "bigmouth": {"def": "(俚)多嘴的人、吹牛者 (單數)", "ipa": "/ˈbɪɡmaʊθ/", "trans": "bigmouths (複數)", "col": "known bigmouth", "ex": "Don't tell him anything - he's a known bigmouth.", "pos": "n."},
    "bigness": {"def": "巨大、大方、重要", "ipa": "/ˈbɪɡnəs/", "trans": "big (形容詞/副詞/代名詞)", "col": "sheer bigness", "ex": "We were struck by the sheer bigness of the building.", "pos": "n."},
    "bigot": {"def": "盲論者、偏執者", "ipa": "/ˈbɪɡət/", "trans": "prejudice", "col": "religious bigot", "ex": "He is a religious bigot who won't listen to reason.", "pos": "n."},
    "bigoted": {"def": "偏執的、盲從的", "ipa": "/ˈbɪɡətɪd/", "trans": "bigot (名詞)", "col": "bigoted views", "ex": "He has very bigoted views on immigration.", "pos": "adj."},
    "bigotry": {"def": "偏執、盲從、頑固", "ipa": "/ˈbɪɡətri/", "trans": "bigot (名詞), bigoted", "col": "sheer bigotry", "ex": "Their ideas were based on sheer bigotry.", "pos": "n."},
    "bike": {"def": "腳踏車、摩托車、騎腳踏車、騎車的人物、騎車地 (車)", "ipa": "/baɪk/", "trans": "bikes", "col": "mountain bike, motor bike, on your bike! (快走!)", "ex": "He rode his bike to the park.", "pos": "n./v./adv."},
    "bikers": {"def": "騎腳踏車者、騎摩托車者 (複數)", "ipa": "/ˈbaɪkəz/", "trans": "bike", "col": "motorcycle bikers", "ex": "A group of motorcycle bikers passed us.", "pos": "n."},
    "bikini": {"def": "比基尼泳衣 (單數)", "ipa": "/bɪˈkiːni/", "trans": "bikinis (複數)", "col": "string bikini", "ex": "She wore a string bikini on the beach.", "pos": "n."},
    "bilateral": {"def": "雙邊的、雙方的、雙向地 (雙)", "ipa": "/ˌbaɪˈlætərəl/", "trans": "bilaterally", "col": "bilateral agreement, bilateral trade", "ex": "The two countries signed a bilateral trade agreement.", "pos": "adj./adv."},
    "bilaterally": {"def": "雙邊地、雙方地", "ipa": "/ˌbaɪˈlætərəli/", "trans": "bilateral (形容詞/副詞)", "col": "negotiated bilaterally", "ex": "The issue was negotiated bilaterally between the two parties.", "pos": "adv."},
    "bile": {"def": "膽汁、憤怒、脾氣地 (膽)", "ipa": "/baɪl/", "trans": "biliary", "col": "flow of bile, full of bile (滿腔憤怒)", "ex": "The liver produces bile.", "pos": "n./adv."},
    "bilge": {"def": "船底、船底污水、廢話、噴出人物、廢話地 (廢話)", "ipa": "/bɪldʒ/", "trans": "nonsense", "col": "sheer bilge", "ex": "Everything he says is sheer bilge.", "pos": "n./v./adv."},
    "biliary": {"def": "膽汁的、膽管的", "ipa": "/ˈbɪliəri/", "trans": "bile", "col": "biliary tract", "ex": "He was diagnosed with a disorder of the biliary tract.", "pos": "adj."},
    "bilingual": {"def": "雙語的、會兩種語言的人、雙語地 (雙語)", "ipa": "/ˌbaɪˈlɪŋɡwəl/", "trans": "bilingualism", "col": "bilingual dictionary, bilingual school", "ex": "She is bilingual in English and Spanish.", "pos": "adj./n./adv."},
    "bilingualism": {"def": "雙語現象、會用兩種語言的能力", "ipa": "/ˌbaɪˈlɪŋɡwəlɪzəm/", "trans": "bilingual (形容詞/名詞/副詞)", "col": "official bilingualism", "ex": "The country has a policy of official bilingualism.", "pos": "n."},
    "bilious": {"def": "膽汁的、壞脾氣的、令人噁心的", "ipa": "/ˈbɪliəs/", "trans": "bile", "col": "bilious attack, bilious color", "ex": "The walls were painted a bilious yellow.", "pos": "adj."},
    "bilk": {"def": "欺騙、詐取、躲債、詐取地 (詐)", "ipa": "/bɪlk/", "trans": "cheat", "col": "bilk someone out of", "ex": "They tried to bilk the old man out of his savings.", "pos": "v./n./adv."},
}