import json

# Level 4 Part 2: (Amateur - Atomic)
L4_PART2 = {
    "amateur": {"def": "業餘愛好者、業餘的、外行的", "ipa": "/ˈæmətə/", "trans": "amateurish", "col": "amateur photographer", "ex": "He is an amateur photographer.", "pos": "n./adj."},
    "amaze(ment)": {"def": "使驚訝、使大為驚嘆、驚訝、驚奇", "ipa": "/əˈmeɪz(mənt)/", "trans": "amazing, amazed", "col": "to one's amazement", "ex": "She gazed at the view in amazement.", "pos": "v.(n.)"},
    "ambassador": {"def": "大使、使節", "ipa": "/æmˈbæsədə/", "trans": "embassy", "col": "goodwill ambassador", "ex": "He was appointed ambassador to Japan.", "pos": "n."},
    "ambiguous": {"def": "含糊不清的、曖昧的、模稜兩可的", "ipa": "/æmˈbɪɡjuəs/", "trans": "ambiguity", "col": "ambiguous message", "ex": "The message was very ambiguous.", "pos": "adj."},
    "ambition": {"def": "野心、抱負、志向", "ipa": "/æmˈbɪʃn/", "trans": "ambitious", "col": "fulfill an ambition", "ex": "His ambition is to become a famous writer.", "pos": "n."},
    "ambitious": {"def": "野心勃勃的、有抱負的", "ipa": "/æmˈbɪʃəs/", "trans": "ambition (名詞), ambitiously", "col": "ambitious project", "ex": "She is a very ambitious young lawyer.", "pos": "adj."},
    "ambulance": {"def": "救護車", "ipa": "/ˈæmbjələns/", "trans": "ambulances", "col": "call an ambulance", "ex": "The ambulance arrived within five minutes.", "pos": "n."},
    "ambush": {"def": "埋伏、伏擊、埋伏、伏擊", "ipa": "/ˈæmbʃ/", "trans": "ambushed", "col": "fall into an ambush", "ex": "The soldiers were caught in an ambush.", "pos": "n./v."},
    "amend(ment)": {"def": "修訂、修正、改良、修正案", "ipa": "/əˈmend(mənt)/", "trans": "amended", "col": "constitutional amendment", "ex": "They have amended the law.", "pos": "v.(n.)"},
    "amiable": {"def": "親切的、和藹可親的", "ipa": "/ˈeɪmiəbl/", "trans": "amiably", "col": "amiable person", "ex": "He is a very amiable person.", "pos": "adj."},
    "ample": {"def": "充足的、豐富的、寬敞的", "ipa": "/ˈæmpl/", "trans": "amply", "col": "ample evidence", "ex": "There is ample evidence to support the theory.", "pos": "adj."},
    "amplify": {"def": "放大、增強、詳述", "ipa": "/ˈæmplɪfaɪ/", "trans": "amplifier, amplification", "col": "amplify the sound", "ex": "The music was amplified through external speakers.", "pos": "v."},
    "amuse(ment)": {"def": "使開心、逗...笑、娛樂、消遣", "ipa": "/əˈmjuːz(mənt)/", "trans": "amusing, amused", "col": "amusement park", "ex": "The children were amused by the clown.", "pos": "v.(n.)"},
    "analogy": {"def": "比喻、類比、類似", "ipa": "/əˈnælədʒi/", "trans": "analogous", "col": "by analogy with", "ex": "She drew an analogy between the brain and a computer.", "pos": "n."},
    "analysis": {"def": "分析、解析報告", "ipa": "/əˈnæləsɪs/", "trans": "analyze, analyst", "col": "data analysis, SWOT analysis", "ex": "The sample is sent to the lab for analysis.", "pos": "n."},
    "analyst": {"def": "分析家、化驗員", "ipa": "/ˈænəlɪst/", "trans": "analysis (名詞), analyze", "col": "financial analyst, political analyst", "ex": "He is a senior financial analyst.", "pos": "n."},
    "analyze": {"def": "分析、分解", "ipa": "/ˈænəlaɪz/", "trans": "analysis, analyst", "col": "analyze results", "ex": "Scientists are analyzing the data.", "pos": "v."},
    "ancestor": {"def": "祖先、原型", "ipa": "/ˈænsestə/", "trans": "ancestry, ancestral", "col": "common ancestor", "ex": "Our ancestors came from China.", "pos": "n."},
    "anchor": {"def": "錨、主播、依靠、拋錨、使固定、拋錨、固定", "ipa": "/ˈæŋkə/", "trans": "anchored", "col": "news anchor, at anchor", "ex": "The ship dropped anchor in the bay.", "pos": "n./v."},
    "anecdote": {"def": "軼事、趣聞", "ipa": "/ˈænɪkdəʊt/", "trans": "anecdotal", "col": "telling anecdotes", "ex": "He told us many funny anecdotes about his travels.", "pos": "n."},
    "angle": {"def": "角、角度、觀點、垂釣、轉變角度、釣魚", "ipa": "/ˈæŋɡl/", "trans": "angles", "col": "right angle, from another angle", "ex": "The camera was set at a low angle.", "pos": "n./v."},
    "anniversary": {"def": "週年紀念日", "ipa": "/ˌænɪˈvɜːsəri/", "trans": "anniversaries", "col": "wedding anniversary", "ex": "Tomorrow is our tenth wedding anniversary.", "pos": "n."},
    "announce(ment)": {"def": "宣佈、播報、發表", "ipa": "/əˈnaʊns(mənt)/", "trans": "announcer", "col": "make an announcement", "ex": "The company announced a new product launch.", "pos": "v.(n.)"},
    "announcer": {"def": "播音員、發佈者", "ipa": "/əˈnaʊnsə/", "trans": "announce (動詞)", "col": "radio announcer", "ex": "The radio announcer announced the news.", "pos": "n."},
    "annoy(ance)": {"def": "使擾亂、使惱火、煩惱、煩人的事物", "ipa": "/əˈnɔɪ(əns)/", "trans": "annoyed, annoying", "col": "to one's annoyance", "ex": "The noise began to annoy me.", "pos": "v.(n.)"},
    "annual": {"def": "年度的、一年生的、年刊、一年生植物", "ipa": "/ˈænjuəl/", "trans": "annually", "col": "annual report, annual meeting", "ex": "The school holds an annual sports day.", "pos": "adj./n."},
    "anonymous": {"def": "匿名的、無特色的", "ipa": "/əˈnɒnɪməs/", "trans": "anonymity, anonymously", "col": "anonymous tip, anonymous source", "ex": "The donor wishes to remain anonymous.", "pos": "adj."},
    "antenna": {"def": "天線、觸角", "ipa": "/ænˈtenə/", "trans": "antennae (複數)", "col": "TV antenna, radio antenna", "ex": "The car is equipped with a radio antenna.", "pos": "n."},
    "anticipate": {"def": "預期、預料、提前行動", "ipa": "/ænˈtɪsɪpeɪt/", "trans": "anticipation", "col": "anticipate problems", "ex": "We anticipate that sales will increase next year.", "pos": "v."},
    "anticipation": {"def": "預期、期待、期望", "ipa": "/ænˌtɪsɪˈpeɪʃn/", "trans": "anticipate (動詞)", "col": "in anticipation of", "ex": "She was smiling in anticipation of the good news.", "pos": "n."},
    "antique": {"def": "古董的、古風的、古董", "ipa": "/ænˈtiːk/", "trans": "antiques", "col": "antique furniture, antique shop", "ex": "She collects antique clocks.", "pos": "adj./n."},
    "anxiety": {"def": "焦慮、掛念、渴望", "ipa": "/æŋˈzaɪəti/", "trans": "anxious", "col": "suffer from anxiety", "ex": "He suffers from deep anxiety about his future.", "pos": "n."},
    "anxious": {"def": "焦慮的、渴望的", "ipa": "/ˈæŋkʃəs/", "trans": "anxiety (名詞), anxiously", "col": "anxious about, anxious for", "ex": "She is anxious about her exam results.", "pos": "adj."},
    "anyway": {"def": "無論如何、總之、反正", "ipa": "/ˈeniweɪ/", "trans": "anyhow", "col": "thanks anyway", "ex": "It's late, but I'm going to finish the work anyway.", "pos": "adv."},
    "apart": {"def": "分開地、相隔地、除...之外、分離的", "ipa": "/əˈpɑːt/", "trans": "parted", "col": "fall apart, apart from", "ex": "They have been living apart for two years.", "pos": "adv./adj."},
    "apartment": {"def": "公寓、房間", "ipa": "/əˈpɑːtmənt/", "trans": "apartments", "col": "one-bedroom apartment", "ex": "She lives in a small apartment in the city center.", "pos": "n."},
    "apologetic": {"def": "道歉的、認錯的", "ipa": "/əˌpɒləˈdʒetɪk/", "trans": "apologize", "col": "apologetic tone", "ex": "He was very apologetic for being late.", "pos": "adj."},
    "apologize": {"def": "道歉、認錯", "ipa": "/əˈpɒlədʒaɪz/", "trans": "apology, apologetic", "col": "apologize to someone for something", "ex": "I apologize for the delay.", "pos": "v."},
    "apology": {"def": "道歉、辯解", "ipa": "/əˈpɒlədʒi/", "trans": "apologize (動詞), apologetic", "col": "sincere apology, accept an apology", "ex": "Please accept my sincere apologies.", "pos": "n."},
    "apparent": {"def": "明顯的、表面上的", "ipa": "/əˈpærənt/", "trans": "apparently", "col": "apparent success", "ex": "It was apparent that the project was a failure.", "pos": "adj."},
    "apparently": {"def": "顯然地、表面上", "ipa": "/əˈpærəntli/", "trans": "apparent (形容詞)", "col": "apparently true", "ex": "Apparently, the game has been canceled.", "pos": "adv."},
    "appeal": {"def": "上訴、呼籲、吸引力、上訴、呼籲、有吸引力", "ipa": "/əˈpiːl/", "trans": "appealing", "col": "appeal to, lodge an appeal", "ex": "The design has a wide appeal.", "pos": "n./v."},
    "appealing": {"def": "有吸引力的、動人的", "ipa": "/əˈpiːlɪŋ/", "trans": "appeal (名詞/動詞)", "col": "appealing design", "ex": "The idea sounds very appealing to me.", "pos": "adj."},
    "appear": {"def": "出現、顯現、似乎", "ipa": "/əˈpɪə/", "trans": "appearance, apparent", "col": "appear to be", "ex": "He appears to be very happy.", "pos": "v."},
    "appearance": {"def": "外貌、面貌、出現", "ipa": "/əˈpɪərəns/", "trans": "appear (動詞)", "col": "public appearance, personal appearance", "ex": "She has a very youthful appearance.", "pos": "n."},
    "appetite": {"def": "食慾、胃口、嗜好", "ipa": "/ˈæpɪtaɪt/", "trans": "appetizer", "col": "loss of appetite, whet someone's appetite", "ex": "The exercise gave me a good appetite.", "pos": "n."},
    "appetizer": {"def": "開胃菜、開胃飲品", "ipa": "/ˈæpɪtaɪzə/", "trans": "appetite (名詞)", "col": "serve appetizers", "ex": "Would you like some appetizers before dinner?", "pos": "n."},
    "applaud": {"def": "鼓掌、稱讚", "ipa": "/əˈplɔːd/", "trans": "applause", "col": "applaud the performers", "ex": "The audience applauded the performers at the end of the show.", "pos": "v."},
    "applause": {"def": "鼓掌、喝采", "ipa": "/əˈplɔːz/", "trans": "applaud (動詞)", "col": "round of applause", "ex": "The winner received a loud round of applause.", "pos": "n."},
    "appliance": {"def": "家用電器、用品", "ipa": "/əˈplaɪəns/", "trans": "appliances", "col": "household appliance, kitchen appliance", "ex": "The store sells a variety of kitchen appliances.", "pos": "n."},
    "applicable": {"def": "適用的、可應用的", "ipa": "/ˈæplɪkəbl/", "trans": "apply, application", "col": "where applicable", "ex": "Please fill in the form where applicable.", "pos": "adj."},
    "applicant": {"def": "申請人、應徵者", "ipa": "/ˈæplɪkənt/", "trans": "apply (動詞), application", "col": "job applicant", "ex": "There were over fifty applicants for the job.", "pos": "n."},
    "application": {"def": "申請、應用、應用程式、敷藥", "ipa": "/ˌæplɪˈkeɪʃn/", "trans": "apply (動詞), applicant", "col": "job application, mobile application, application form", "ex": "She submitted an application for the position.", "pos": "n."},
    "apply": {"def": "申請、應用、塗抹、適用於", "ipa": "/əˈplaɪ/", "trans": "application, applicant", "col": "apply for a job, apply to", "ex": "He applied for a job as a teacher.", "pos": "v."},
    "appoint(ment)": {"def": "任命、指派、約定、約會", "ipa": "/əˈpɔɪnt(mənt)/", "trans": "appointee", "col": "make an appointment, dental appointment", "ex": "I have an appointment with my lawyer tomorrow.", "pos": "v.(n.)"},
    "appreciate": {"def": "賞識、感激、增值", "ipa": "/əˈpriːʃieɪt/", "trans": "appreciation, appreciative", "col": "appreciate help", "ex": "I really appreciate all your help.", "pos": "v."},
    "appreciation": {"def": "欣賞、感激、評價、增值", "ipa": "/əˌpriːʃiˈeɪʃn/", "trans": "appreciate (動詞), appreciative", "col": "token of appreciation, in appreciation of", "ex": "Please accept this gift in appreciation of your hard work.", "pos": "n."},
    "apprehension": {"def": "憂慮、理解、逮捕", "ipa": "/ˌæprɪˈhenʃn/", "trans": "apprehensive", "col": "deep apprehension", "ex": "He felt a sense of apprehension as he waited for the results.", "pos": "n."},
    "apprentice": {"def": "學徒、新手、使當學徒", "ipa": "/əˈprentɪs/", "trans": "apprenticeship", "col": "apprentice plumber", "ex": "He is an apprentice plumber.", "pos": "n./v."},
    "approach": {"def": "接近、途徑、方法、接近、探討、處理", "ipa": "/əˈprəʊtʃ/", "trans": "approachable", "col": "conservative approach, scientific approach", "ex": "We need to take a different approach to the problem.", "pos": "n./v."},
    "appropriate": {"def": "適當的、撥出(款項)、挪用", "ipa": "/əˈprəʊpriət/ (adj.) /əˈprəʊprieɪt/ (v.)", "trans": "appropriately, appropriation", "col": "appropriate behavior", "ex": "I don't think his behavior was appropriate.", "pos": "adj./v."},
    "approval": {"def": "贊成、同意、認可", "ipa": "/əˈpruːvl/", "trans": "approve (動詞)", "col": "official approval, seek approval", "ex": "The plan has received final approval.", "pos": "n."},
    "approve": {"def": "贊成、同意、認可、通過", "ipa": "/əˈpruːv/", "trans": "approval", "col": "approve of", "ex": "My parents don't approve of my career choice.", "pos": "v."},
    "approximate": {"def": "近似的、大約的、估計、接近", "ipa": "/əˈprɒksɪmət/ (adj.) /əˈprɒksɪmeɪt/ (v.)", "trans": "approximately, approximation", "col": "approximate number", "ex": "Can you give me an approximate number?", "pos": "adj./v."},
    "approximately": {"def": "大約、近似地", "ipa": "/əˈprɒksɪmətli/", "trans": "approximate (形容詞)", "col": "takes approximately", "ex": "It will take approximately ten minutes.", "pos": "adv."},
    "apt": {"def": "恰當的、有...傾向的、易於...的、聰明的", "ipa": "/æpt/", "trans": "aptly", "col": "apt description", "ex": "It was an apt description of the situation.", "pos": "adj."},
    "aquarium": {"def": "水族館、魚缸", "ipa": "/əˈkweəriəm/", "trans": "aquariums", "col": "visit an aquarium", "ex": "The children enjoyed their visit to the aquarium.", "pos": "n."},
    "arch": {"def": "拱門、足弓、拱形的、結成拱形、使成拱形", "ipa": "/ɑːtʃ/", "trans": "arched", "col": "marble arch", "ex": "The bridge is built in the shape of an arch.", "pos": "n./adj./v."},
    "architect": {"def": "建築師、設計者", "ipa": "/ˈɑːkɪtekt/", "trans": "architecture, architectural", "col": "famous architect", "ex": "He is a famous architect who designed many landmark buildings.", "pos": "n."},
    "architecture": {"def": "建築學、建築風格、結構", "ipa": "/ˈɑːkɪtektʃə/", "trans": "architect (名詞)", "col": "modern architecture, Gothic architecture", "ex": "I am interested in ancient architecture.", "pos": "n."},
    "archive": {"def": "檔案館、檔案、把...歸檔、存檔", "ipa": "/ˈɑːkaɪv/", "trans": "archives", "col": "national archives, digital archive", "ex": "The documents are stored in the national archives.", "pos": "n./v."},
    "area": {"def": "地區、區域、面積、學科領域", "ipa": "/ˈeəriə/", "trans": "areal", "col": "residential area, wide area", "ex": "Crime is a major problem in this area.", "pos": "n."},
    "arena": {"def": "競技場、舞台", "ipa": "/əˈriːnə/", "trans": "arenas", "col": "political arena", "ex": "The concert will be held in a large arena.", "pos": "n."},
    "argue(ment)": {"def": "爭論、辯論、論據、理由", "ipa": "/ˈɑːɡjuː(mənt)/", "trans": "arguable", "col": "have an argument, main argument", "ex": "They had a long argument about money.", "pos": "v.(n.)"},
    "arise": {"def": "出現、發生、上升", "ipa": "/əˈraɪz/", "trans": "arisen (過去分詞)", "col": "problems arise", "ex": "Several problems have arisen since the project started.", "pos": "v."},
    "arithmetic": {"def": "算術、算術的", "ipa": "/əˈrɪθmətɪk/", "trans": "arithmetical", "col": "mental arithmetic", "ex": "He is very good at mental arithmetic.", "pos": "n./adj."},
    "arm": {"def": "手臂、袖子、武器、裝備、武裝", "ipa": "/ɑːm/", "trans": "armed, army", "col": "arm in arm, bear arms", "ex": "She held the baby in her arms.", "pos": "n./v."},
    "armor": {"def": "盔甲、裝甲、為...穿盔甲、裝上裝甲", "ipa": "/ˈɑːmə/", "trans": "armored", "col": "body armor, armored vehicle", "ex": "The soldiers wore body armor during the mission.", "pos": "n./v."},
    "arms": {"def": "武器、兵種、戰爭", "ipa": "/ɑːmz/", "trans": "arm (名詞/動詞)", "col": "arms race, nuclear arms", "ex": "The country is trying to reduce its stock of nuclear arms.", "pos": "n."},
    "army": {"def": "軍隊、大群", "ipa": "/ˈɑːmi/", "trans": "armies", "col": "join the army, Salvation Army", "ex": "He decided to join the army after high school.", "pos": "n."},
    "arouse": {"def": "喚醒、引起、激發", "ipa": "/əˈraʊz/", "trans": "arousal", "col": "arouse interest, arouse suspicion", "ex": "His behavior aroused suspicion.", "pos": "v."},
    "arrange(ment)": {"def": "安排、排列、規畫", "ipa": "/əˈreɪndʒ(mənt)/", "trans": "arranger", "col": "make arrangements", "ex": "I need to arrange a meeting with the client.", "pos": "v.(n.)"},
    "arrest": {"def": "逮捕、阻止、吸引(注意)、逮捕、拘留、停止", "ipa": "/əˈrest/", "trans": "arrested", "col": "under arrest, cardiac arrest", "ex": "The suspect was arrested for robbery.", "pos": "v./n."},
    "arrival": {"def": "到達、抵達者、新產品", "ipa": "/əˈraɪvl/", "trans": "arrive (動詞)", "col": "time of arrival, new arrival", "ex": "I am waiting for the arrival of the train.", "pos": "n."},
    "arrive": {"def": "到達、抵達、達成", "ipa": "/əˈraɪv/", "trans": "arrival", "col": "arrive at, arrive in", "ex": "The train arrived on time.", "pos": "v."},
    "arrogance": {"def": "傲慢、自大", "ipa": "/ˈærəɡəns/", "trans": "arrogant", "col": "deep elegance", "ex": "I couldn't believe his arrogance.", "pos": "n."},
    "arrogant": {"def": "傲慢的、自大的", "ipa": "/ˈærəɡənt/", "trans": "arrogance (名詞), arrogantly", "col": "arrogant attitude", "ex": "He is a very arrogant young man.", "pos": "adj."},
    "arrow": {"def": "箭、箭號", "ipa": "/ˈærəʊ/", "trans": "arrows", "col": "bow and arrow", "ex": "Follow the arrows on the ground.", "pos": "n."},
    "art": {"def": "藝術、美術、技藝、技術", "ipa": "/ɑːt/", "trans": "artist, artistic", "col": "work of art, fine arts, modern art", "ex": "I am a fan of modern art.", "pos": "n."},
    "article": {"def": "文章、條款、物品、冠詞", "ipa": "/ˈɑːtɪkl/", "trans": "articles", "col": "newspaper article, leading article", "ex": "Did you read the article in the newspaper?", "pos": "n."},
    "articulate": {"def": "發音清晰的、善於表達的、連結、清晰地說出", "ipa": "/ɑːˈtɪkjələt/ (adj.) /ɑːˈtɪkjuleɪt/ (v.)", "trans": "articulately, articulation", "col": "articulate speech", "ex": "She is a very articulate public speaker.", "pos": "adj./v."},
    "artifact": {"def": "手工藝品、人工製品", "ipa": "/ˈɑːtɪfækt/", "trans": "artifacts", "col": "ancient artifact", "ex": "The museum displays many ancient artifacts.", "pos": "n."},
    "artificial": {"def": "人工的、人造的、虛偽的", "ipa": "/ˌɑːtɪˈfɪʃl/", "trans": "artificially", "col": "artificial intelligence, artificial flavor", "ex": "The product contains no artificial flavors.", "pos": "adj."},
    "artillery": {"def": "大砲、砲兵", "ipa": "/ɑːˈtɪləri/", "trans": "artillerist", "col": "heavy artillery", "ex": "The army used heavy artillery during the battle.", "pos": "n."},
    "artist": {"def": "藝術家、畫家、藝人", "ipa": "/ˈɑːtɪst/", "trans": "artistik", "col": "makeup artist, professional artist", "ex": "She is a very talented artist.", "pos": "n."},
    "artistic": {"def": "藝術的、有藝術鑑賞力的", "ipa": "/ɑːˈtɪstɪk/", "trans": "artist (名詞), artistically", "col": "artistic skills, artistic director", "ex": "The movie has great artistic value.", "pos": "adj."},
    "ascend": {"def": "上升、登高、追溯", "ipa": "/əˈsend/", "trans": "ascent, ascending", "col": "ascend the stairs", "ex": "The aircraft began to ascend.", "pos": "v."},
    "ascent": {"def": "上升、上坡、攀登", "ipa": "/əˈsent/", "trans": "ascend (動詞)", "col": "steep ascent", "ex": "The climb is a steep ascent.", "pos": "n."},
    "ascertain": {"def": "查明、弄清楚", "ipa": "/ˌæsəˈteɪn/", "trans": "ascertainable", "col": "ascertain facts", "ex": "The police are trying to ascertain the cause of the accident.", "pos": "v."},
    "ash": {"def": "灰、灰燼、骨灰", "ipa": "/æʃ/", "trans": "ashy", "col": "volcanic ash, cigarette ash", "ex": "The city was covered in volcanic ash.", "pos": "n."},
    "ashamed": {"def": "羞愧的、慚愧的", "ipa": "/əˈʃeɪmd/", "trans": "shame", "col": "ashamed of", "ex": "I am ashamed of what I did.", "pos": "adj."},
    "aside": {"def": "在旁邊、除...之外、悄悄話、旁白", "ipa": "/əˈsaɪd/", "trans": "asides", "col": "aside from, set aside", "ex": "She stood aside to let me pass.", "pos": "adv./n."},
    "aspect": {"def": "方面、樣子、方位", "ipa": "/ˈæspekt/", "trans": "aspects", "col": "positive aspect, focus on every aspect", "ex": "We need to consider every aspect of the case.", "pos": "n."},
    "aspiration": {"def": "志向、抱負、呼吸", "ipa": "/ˌæspəˈreɪʃn/", "trans": "aspire", "col": "high aspiration", "ex": "She has high aspirations for her future.", "pos": "n."},
    "aspire": {"def": "渴望、嚮往", "ipa": "/əˈspaɪə/", "trans": "aspiration, aspiring", "col": "aspire to", "ex": "He aspires to become a famous writer.", "pos": "v."},
    "assassin": {"def": "刺客、暗殺者", "ipa": "/əˈsæsɪn/", "trans": "assassination, assassinate", "col": "political assassin", "ex": "The assassin was caught by the police.", "pos": "n."},
    "assassinate": {"def": "暗殺、行刺", "ipa": "/əˈsæsɪneɪt/", "trans": "assassination, assassin", "col": "assassinate a leader", "ex": "He was assassinated during a political rally.", "pos": "v."},
    "assassination": {"def": "暗殺", "ipa": "/əˌsæsɪˈneɪʃn/", "trans": "assassinate (動詞)", "col": "political assassination", "ex": "The assassination of the president shocked the nation.", "pos": "n."},
    "assault": {"def": "攻擊、暴力、攻擊、毆打", "ipa": "/əˈsɔːlt/", "trans": "assailant", "col": "sexual assault, physical assault", "ex": "He was charged with sexual assault.", "pos": "n./v."},
    "assemble": {"def": "集合、裝配、聚集", "ipa": "/əˈsembl/", "trans": "assembly, assembler", "col": "assemble components", "ex": "The children assembled in the auditorium.", "pos": "v."},
    "assembly": {"def": "集會、立法機構、裝配、組件", "ipa": "/əˈsembli/", "trans": "assemble (動詞)", "col": "general assembly, assembly line", "ex": "The cars are manufactured on an assembly line.", "pos": "n."},
    "assert": {"def": "斷言、主張、維護", "ipa": "/əˈsɜːt/", "trans": "assertion, assertive", "col": "assert dominance", "ex": "He asserted that he was innocent.", "pos": "v."},
    "assess(ment)": {"def": "評估、估價、徵收、評估額、看法", "ipa": "/əˈses(mənt)/", "trans": "assessor", "col": "needs assessment, environmental assessment", "ex": "The damage was assessed at $1 million.", "pos": "v.(n.)"},
    "asset": {"def": "資產、優點、有用的東西", "ipa": "/ˈæset/", "trans": "assets", "col": "valuable asset, liquid assets", "ex": "His ability to speak multiple languages is a valuable asset.", "pos": "n."},
    "assign(ment)": {"def": "分配、指派、讓與、任務、作業、轉讓", "ipa": "/əˈsaɪn(mənt)/", "trans": "assignable", "col": "assign tasks, homework assignment", "ex": "I was assigned the task of clearing the garden.", "pos": "v.(n.)"},
    "assimilate": {"def": "吸收、同化、消化", "ipa": "/əˈsɪməleɪt/", "trans": "assimilation", "col": "assimilate information", "ex": "It takes time to assimilate new information.", "pos": "v."},
    "assist(ance)": {"def": "幫助、援助、出席、助攻、援助", "ipa": "/əˈsɪst(əns)/", "trans": "assistant", "col": "medical assistance, provide assistance", "ex": "Can you assist me with these boxes?", "pos": "v.(n.)"},
    "assistant": {"def": "助手、助理、助理的、副的", "ipa": "/əˈsɪstənt/", "trans": "assist (動詞/名詞)", "col": "personal assistant, research assistant", "ex": "She works as a personal assistant to the CEO.", "pos": "n./adj."},
    "associate": {"def": "同事、合夥人、準(學士)、聯合的、副的、聯想、交友、聯合", "ipa": "/əˈsəʊʃɪeɪt/ (v.) /əˈsəʊʃɪət/ (n./adj.)", "trans": "association", "col": "associate degree, business associate, associate with", "ex": "I always associate rainy days with sadness.", "pos": "n./adj./v."},
    "association": {"def": "協會、公會、交際、聯想", "ipa": "/əˌsəʊʃiˈeɪʃn/", "trans": "associate (動詞/名詞)", "col": "professional association, housing association", "ex": "He is a member of the local historical association.", "pos": "n."},
    "assume": {"def": "假設、承擔、呈現、裝腔作勢", "ipa": "/əˈsjuːm/", "trans": "assumption, assumed", "col": "assume responsibility, assume control", "ex": "I assume that you are tired after your long journey.", "pos": "v."},
    "assumption": {"def": "假設、擔任、呈現", "ipa": "/əˈsʌmpʃn/", "trans": "assume (動詞)", "col": "basic assumption, underlying assumption", "ex": "The theory is based on a number of basic assumptions.", "pos": "n."},
    "assurance": {"def": "確信、保證、保險 (人壽)", "ipa": "/əˈʃɔːrəns/", "trans": "assure (動詞)", "col": "life assurance", "ex": "He gave me his assurance that the work would be finished on time.", "pos": "n."},
    "assure": {"def": "向...保證、使確信、弄清楚", "ipa": "/əˈʃɔː/", "trans": "assurance", "col": "assure someone of something", "ex": "I assure you that I am telling the truth.", "pos": "v."},
    "asteroid": {"def": "小行星、海星", "ipa": "/ˈæstərɔɪd/", "trans": "astronomy", "col": "asteroid belt", "ex": "The belt is composed primarily of asteroids.", "pos": "n."},
    "asthma": {"def": "氣喘、哮喘", "ipa": "/ˈæsmə/", "trans": "asthmatic", "col": "asthma attack", "ex": "She has been suffering from asthma since childhood.", "pos": "n."},
    "astonish(ment)": {"def": "使大吃一驚、驚訝", "ipa": "/əˈstɒnɪʃ(mənt)/", "trans": "astonishing", "col": "to one's astonishment", "ex": "Her speed astonished everyone.", "pos": "v.(n.)"},
    "astray": {"def": "迷路地、墮落地、誤入歧途的", "ipa": "/əˈstreɪ/", "trans": "stray", "col": "go astray, lead astray", "ex": "The dog was found astray in the woods.", "pos": "adv./adj."},
    "astronaut": {"def": "太空人、宇航員", "ipa": "/ˈæstrənɔːt/", "trans": "astronomy", "col": "American astronaut", "ex": "He dreamed of becoming an astronaut when he was a child.", "pos": "n."},
    "astronomer": {"def": "天文學家", "ipa": "/əˈstrɒnəmə/", "trans": "astronomy (名詞)", "col": "famous astronomer", "ex": "He is a famous astronomer who discovered a new planet.", "pos": "n."},
    "astronomy": {"def": "天文學", "ipa": "/əˈstrɒnəmi/", "trans": "astronomical, astronomer", "col": "study astronomy", "ex": "She has always been interested in astronomy.", "pos": "n."},
    "asylum": {"def": "避難、庇護、精神病院", "ipa": "/əˈsaɪləm/", "trans": "asylums", "col": "political asylum, seek asylum", "ex": "He was granted political asylum in the UK.", "pos": "n."},
    "athletic": {"def": "運動的、強壯的", "ipa": "/æθˈletɪk/", "trans": "athlete, athletics", "col": "athletic skills, athletic field", "ex": "She is a very athletic person.", "pos": "adj."},
    "athletics": {"def": "體育運動、體育競技、田徑運動", "ipa": "/æθˈletɪks/", "trans": "athletic (形容詞)", "col": "university athletics", "ex": "He is interested in athletics.", "pos": "n."},
    "atmosphere": {"def": "大氣層、氣氛、氣壓", "ipa": "/ˈætməsfɪə/", "trans": "atmospheric", "col": "relaxing atmosphere, festive atmosphere", "ex": "The restaurant has a very relaxing atmosphere.", "pos": "n."},
    "atmospheric": {"def": "大氣的、有藝術氣息的", "ipa": "/ˌætməsˈferɪk/", "trans": "atmosphere (名詞)", "col": "atmospheric pressure", "ex": "The atmospheric pressure is dropping.", "pos": "adj."},
    "atom": {"def": "原子、微粒", "ipa": "/ˈætəm/", "trans": "atomic", "col": "hydrogen atom", "ex": "An atom is the smallest unit of matter.", "pos": "n."},
    "atomic": {"def": "原子的、原子能的、微小的", "ipa": "/əˈtɒmɪk/", "trans": "atom (名詞)", "col": "atomic bomb, atomic energy, atomic weight", "ex": "The discovery of atomic energy changed the world.", "pos": "adj."},
}

with open("batch_l4_p2.json", "w", encoding="utf-8") as f:
    json.dump(L4_PART2, f, ensure_ascii=False, indent=2)
