import json

# Level 2 Part 7: (Chapter - Clinic)
L2_PART7 = {
    "chapter": {"def": "章、章節、把...分成章節", "ipa": "/ˈtʃæptə/", "trans": "chapters", "col": "new chapter, Chapter One", "ex": "Please read the first three chapters.", "pos": "n./v."},
    "character": {"def": "性格、特徵、角色、字元、描寫...的特性", "ipa": "/ˈkærəktə/", "trans": "characteristic, characterize", "col": "main character, strong character", "ex": "He is a man of good character.", "pos": "n./v."},
    "charge": {"def": "費用、控告、電荷、收費、控告、充電", "ipa": "/tʃɑːdʒ/", "trans": "charger, chargeable", "col": "in charge of, free of charge, service charge", "ex": "How much do you charge for a haircut?", "pos": "n./v."},
    "charity": {"def": "慈善、施捨、慈善機構", "ipa": "/ˈtʃærəti/", "trans": "charitable", "col": "charity event, for charity", "ex": "The money will be given to charity.", "pos": "n."},
    "chart": {"def": "圖表、航海圖、繪製圖表、記錄", "ipa": "/tʃɑːt/", "trans": "charts", "col": "pie chart, flow chart", "ex": "The sales figures are shown in the chart.", "pos": "n./v."},
    "chase": {"def": "追逐、追趕、追捕", "ipa": "/tʃeɪs/", "trans": "chased", "col": "chase after", "ex": "The cat was chasing a mouse.", "pos": "v./n."},
    "chat": {"def": "閒談、聊天", "ipa": "/tʃæt/", "trans": "chatty, chatter", "col": "have a chat, chat room", "ex": "I had a long chat with my friend yesterday.", "pos": "v./n."},
    "cheap": {"def": "便宜的、低劣的、便宜地", "ipa": "/tʃiːp/", "trans": "cheaply, cheapness", "col": "cheap price, dirt cheap", "ex": "This watch was very cheap.", "pos": "adj./adv."},
    "cheat": {"def": "欺騙、作弊、詐騙、騙子", "ipa": "/tʃiːt/", "trans": "cheater", "col": "cheat on an exam", "ex": "He was caught cheating in the test.", "pos": "v./n."},
    "check": {"def": "檢查、支票、阻止、格紋、檢查、阻止", "ipa": "/tʃek/", "trans": "checker, checkout", "col": "check in, check out, double check", "ex": "Please check your answers carefully.", "pos": "v./n."},
    "cheek": {"def": "臉頰、厚臉皮", "ipa": "/tʃiːk/", "trans": "cheeky", "col": "rosy cheeks", "ex": "She kissed him on the cheek.", "pos": "n."},
    "cheerful": {"def": "愉快的、快樂的", "ipa": "/ˈtʃɪəfl/", "trans": "cheerfully, cheerfulness", "col": "cheerful smile, feeling cheerful", "ex": "She is always very cheerful.", "pos": "adj."},
    "cheese": {"def": "起司、乳酪", "ipa": "/tʃiːz/", "trans": "cheesecake", "col": "blue cheese, cream cheese", "ex": "I'd like some cheese and crackers.", "pos": "n."},
    "chemical": {"def": "化學的、化學製品", "ipa": "/ˈkemɪkl/", "trans": "chemist, chemistry", "col": "chemical reaction, chemical weapon", "ex": "These vegetables are free from chemicals.", "pos": "adj./n."},
    "chemist": {"def": "化學家、藥劑師、藥妝店", "ipa": "/ˈkemɪst/", "trans": "chemistry, chemical", "col": "analytical chemist", "ex": "He is a famous organic chemist.", "pos": "n."},
    "chemistry": {"def": "化學、化學作用、吸引力", "ipa": "/ˈkemɪstri/", "trans": "chemical, chemist", "col": "organic chemistry", "ex": "I enjoyed studying chemistry at school.", "pos": "n."},
    "cherry": {"def": "櫻桃、櫻桃樹、櫻桃色的", "ipa": "/ˈtʃeri/", "trans": "cherries", "col": "cherry blossom, cherry pie", "ex": "The cherries are ripe now.", "pos": "n./adj."},
    "chess": {"def": "西洋棋", "ipa": "/tʃes/", "trans": "chessboard", "col": "play chess", "ex": "Do you know how to play chess?", "pos": "n."},
    "chest": {"def": "胸膛、大箱子、櫥櫃", "ipa": "/tʃest/", "trans": "chestnut", "col": "chest pain, treasure chest", "ex": "He has a very broad chest.", "pos": "n."},
    "chew": {"def": "咀嚼、深思、咀嚼、咀嚼物", "ipa": "/tʃuː/", "trans": "chewy, chewing", "col": "chewing gum", "ex": "You should chew your food well.", "pos": "v./n."},
    "chick": {"def": "小雞、小鳥", "ipa": "/tʃɪk/", "trans": "chicken", "col": "baby chicks", "ex": "The chicks are hatching.", "pos": "n."},
    "chief": {"def": "首領、長官、主要的、首席的、主要地", "ipa": "/tʃiːf/", "trans": "chiefly", "col": "editor-in-chief, chief executive", "ex": "The chief reason for his success is hard work.", "pos": "n./adj./adv."},
    "childhood": {"def": "童年", "ipa": "/ˈtʃaɪldhʊd/", "trans": "child (名詞)", "col": "happy childhood", "ex": "I spent my childhood in the country.", "pos": "n."},
    "chill": {"def": "寒冷、寒戰、使變冷、使受挫、寒冷的", "ipa": "/tʃɪl/", "trans": "chilly", "col": "chill out, catch a chill", "ex": "There was a chill in the air.", "pos": "n./v./adj."},
    "chimney": {"def": "煙囪", "ipa": "/ˈtʃɪmni/", "trans": "chimneys", "col": "smoke from the chimney", "ex": "Smoke was rising from the chimney.", "pos": "n."},
    "chin": {"def": "下巴、聊天、向...聊天", "ipa": "/tʃɪn/", "trans": "chins", "col": "double chin", "ex": "He rubbed his chin thoughtfully.", "pos": "n./v."},
    "china": {"def": "瓷器", "ipa": "/ˈtʃaɪnə/", "trans": "porcelain", "col": "bone china", "ex": "Be careful with that china plate.", "pos": "n."},
    "chip": {"def": "碎片、晶片、炸薯條、削下、切尖", "ipa": "/tʃɪp/", "trans": "chipping, chipper", "col": "computer chip, potato chips", "ex": "This computer uses a high-speed chip.", "pos": "n./v."},
    "chocolate": {"def": "巧克力、巧克力糖、巧克力的", "ipa": "/ˈtʃɒklət/", "trans": "chocolates", "col": "milk chocolate, dark chocolate", "ex": "I love eating chocolate.", "pos": "n./adj."},
    "choice": {"def": "選擇、挑選、精選的", "ipa": "/tʃɔɪs/", "trans": "choose (動詞)", "col": "make a choice, by choice", "ex": "You have no choice but to wait.", "pos": "n./adj."},
    "choir": {"def": "合唱團", "ipa": "/ˈkwaɪə/", "trans": "choral", "col": "church choir", "ex": "He sings in the school choir.", "pos": "n."},
    "choke": {"def": "窒息、阻塞、嗆到、窒息、阻風門", "ipa": "/tʃəʊk/", "trans": "choking", "col": "choke to death", "ex": "The smoke made me choke.", "pos": "v./n."},
    "choose": {"def": "選擇、選定", "ipa": "/tʃuːz/", "trans": "chose, chosen, choice", "col": "choose from, nothing to choose from", "ex": "You must choose between the two.", "pos": "v."},
    "chop": {"def": "切、砍、排骨、切碎", "ipa": "/tʃɒp/", "trans": "chopper, choppy", "col": "pork chop, chop up", "ex": "Chop the carrots into small pieces.", "pos": "v./n."},
    "chorus": {"def": "合唱、合唱隊、副歌、齊聲說、合唱", "ipa": "/ˈkɔːrəs/", "trans": "choral", "col": "dawn chorus, in chorus", "ex": "Everyone joined in the chorus.", "pos": "n./v."},
    "Christian": {"def": "基督徒、基督教的", "ipa": "/ˈkrɪstʃən/", "trans": "Christianity", "col": "Christian name", "ex": "He is a devout Christian.", "pos": "n./adj."},
    "Christmas": {"def": "聖誕節", "ipa": "/ˈkrɪsməs/", "trans": "Noel", "col": "Merry Christmas, Christmas Eve", "ex": "We decorate the tree at Christmas.", "pos": "n."},
    "chubby": {"def": "圓胖的、豐滿的", "ipa": "/ˈtʃʌbi/", "trans": "plump", "col": "chubby cheeks", "ex": "The baby has chubby little legs.", "pos": "adj."},
    "church": {"def": "教堂、教會", "ipa": "/tʃɜːtʃ/", "trans": "churchman", "col": "go to church", "ex": "There is a small church in the village.", "pos": "n."},
    "cigar": {"def": "雪茄", "ipa": "/sɪˈɡɑː/", "trans": "cigarette", "col": "smoke a cigar", "ex": "He likes to smoke a cigar after dinner.", "pos": "n."},
    "cigarette": {"def": "香菸", "ipa": "/ˌsɪɡəˈret/", "trans": "cigar (名詞)", "col": "light a cigarette", "ex": "He is trying to quit smoking cigarettes.", "pos": "n."},
    "cinema": {"def": "電影院、電影業", "ipa": "/ˈsɪnəmə/", "trans": "cinematic", "col": "go to the cinema", "ex": "Let's go to the cinema tonight.", "pos": "n."},
    "circle": {"def": "圓圈、界、社會圈、圈出、環繞", "ipa": "/ˈsɜːkl/", "trans": "circular, circulate", "col": "inner circle, social circle", "ex": "The children sat in a circle.", "pos": "n./v."},
    "circulate": {"def": "循環、傳播、流傳", "ipa": "/ˈsɜːkjəleɪt/", "trans": "circulation", "col": "circulate rumors", "ex": "Blood circulates through the body.", "pos": "v."},
    "circulation": {"def": "循環、流通、發行量", "ipa": "/ˌsɜːkjəˈleɪʃn/", "trans": "circulate (動詞)", "col": "blood circulation, in circulation", "ex": "The newspaper has a large circulation.", "pos": "n."},
    "circumstance": {"def": "環境、情況、境遇", "ipa": "/ˈsɜːkəmstəns/", "trans": "circumstantial", "col": "under the circumstances", "ex": "He was a victim of circumstance.", "pos": "n."},
    "circus": {"def": "馬戲團、圓形廣場", "ipa": "/ˈsɜːkəs/", "trans": "circuses", "col": "traveling circus", "ex": "The kids loved the circus.", "pos": "n."},
    "citizen": {"def": "公民、市民", "ipa": "/ˈsɪtɪzn/", "trans": "citizenship", "col": "senior citizen, good citizen", "ex": "He is a British citizen.", "pos": "n."},
    "civil": {"def": "民事的、國民的、禮貌的", "ipa": "/ˈsɪvl/", "trans": "civilized, civilian", "col": "civil rights, civil war", "ex": "The two countries were at civil war.", "pos": "adj."},
    "civilize": {"def": "使文明、開化、教導", "ipa": "/ˈsɪvəlaɪz/", "trans": "civilization, civilized", "col": "civilizing influence", "ex": "The goal is to civilize the society.", "pos": "v."},
    "claim": {"def": "要求、聲稱、權利、索賠、要求、聲稱", "ipa": "/kleɪm/", "trans": "claimant", "col": "claim responsibility, insurance claim", "ex": "He claimed that he had seen a UFO.", "pos": "v./n."},
    "clap": {"def": "拍手、鼓掌、拍手聲、霹靂聲", "ipa": "/klæp/", "trans": "clapping", "col": "clap one's hands", "ex": "The audience clapped loudly.", "pos": "v./n."},
    "clarify": {"def": "澄清、說明", "ipa": "/ˈklærəfaɪ/", "trans": "clarification, clarity", "col": "clarify a point", "ex": "Could you clarify what you mean?", "pos": "v."},
    "clash": {"def": "衝突、不協調、碰撞聲、衝突、發出撞擊聲", "ipa": "/klæʃ/", "trans": "clashing", "col": "clash of cultures", "ex": "The two armies clashed at dawn.", "pos": "n./v."},
    "classical": {"def": "古典的、傳統的", "ipa": "/ˈklæsɪkl/", "trans": "classic, classify", "col": "classical music, classical education", "ex": "He prefers classical music to pop music.", "pos": "adj."},
    "classify": {"def": "分類、歸類", "ipa": "/ˈklæsɪfaɪ/", "trans": "classification", "col": "classify into", "ex": "Whales are classified as mammals.", "pos": "v."},
    "clatter": {"def": "嘩啦聲、 noisy talk、發出嘩啦聲、喋喋不休", "ipa": "/ˈklætə/", "trans": "clattering", "col": "clatter of dishes", "ex": "The dishes clattered on the floor.", "pos": "n./v."},
    "claw": {"def": "爪、螯、用爪抓、挖", "ipa": "/klɔː/", "trans": "clawed", "col": "cat's claws", "ex": "The crab has powerful claws.", "pos": "n./v."},
    "clay": {"def": "黏土、泥土", "ipa": "/kleɪ/", "trans": "clayey", "col": "clay pot, modeling clay", "ex": "The potter made a bowl out of clay.", "pos": "n."},
    "clerk": {"def": "店員、辦事員、職員", "ipa": "/klɜːk/", "trans": "clerical", "col": "bank clerk, office clerk", "ex": "The clerk was very helpful.", "pos": "n."},
    "clever": {"def": "聰明的、靈巧的", "ipa": "/ˈklevə/", "trans": "cleverly, cleverness", "col": "clever idea", "ex": "She is a very clever girl.", "pos": "adj."},
    "click": {"def": "卡嗒聲、點擊、發出卡嗒聲、點擊", "ipa": "/klɪk/", "trans": "clicking", "col": "double click", "ex": "Click the mouse to open the file.", "pos": "n./v."},
    "client": {"def": "客戶、顧客", "ipa": "/ˈklaɪənt/", "trans": "clientele", "col": "regular client", "ex": "He has a lot of regular clients.", "pos": "n."},
    "cliff": {"def": "懸崖、峭壁", "ipa": "/klɪf/", "trans": "cliffhanger", "col": "chalk cliffs", "ex": "The house stands on the edge of a cliff.", "pos": "n."},
    "climate": {"def": "氣候、風氣", "ipa": "/ˈklaɪmət/", "trans": "climatic", "col": "tropical climate, climate change", "ex": "The island has a warm, dry climate.", "pos": "n."},
    "climb": {"def": "攀登、爬、上昇", "ipa": "/klaɪm/", "trans": "climber, climbing", "col": "climb up, social climber", "ex": "He likes to climb mountains.", "pos": "v./n."},
    "clinic": {"def": "診所、臨床教學", "ipa": "/ˈklɪnɪk/", "trans": "clinical", "col": "dental clinic, health clinic", "ex": "She went to the local health clinic.", "pos": "n."},
}

with open("batch_l2_p7.json", "w", encoding="utf-8") as f:
    json.dump(L2_PART7, f, ensure_ascii=False, indent=2)
