import json

# Level 6 Part 35: (Biotech - Bite)
L6_PART35 = {
    "biotech/biotechnology": {"def": "生物技術", "ipa": "/ˌbaɪəʊtekˈnɒlədʒi/", "trans": "biotechnological", "col": "biotech firm, advancements in biotechnology", "ex": "He works for a leading biotech firm.", "pos": "n."},
    "bipartisan": {"def": "兩黨的、代表兩黨的", "ipa": "/ˌbaɪˈpɑːtɪzæn/", "trans": "bipartisanship", "col": "bipartisan support, bipartisan committee", "ex": "The bill received bipartisan support in Congress.", "pos": "adj."},
    "bipartisanship": {"def": "兩黨合作", "ipa": "/ˌbaɪˈpɑːtɪzænʃɪp/", "trans": "bipartisan (形容詞)", "col": "spirit of bipartisanship", "ex": "The president called for a spirit of bipartisanship.", "pos": "n."},
    "biped": {"def": "兩足動物、兩足的人、兩足地 (兩足)", "ipa": "/ˈbaɪped/", "trans": "bipeds", "col": "bipedal locomotion", "ex": "Human beings are bipeds.", "pos": "n./adv."},
    "bipedal": {"def": "兩足的", "ipa": "/baɪˈpiːdl/", "trans": "biped", "col": "bipedal robot", "ex": "Birds are bipedal animals.", "pos": "adj."},
    "biplane": {"def": "雙翼飛機", "ipa": "/ˈbaɪpleɪn/", "trans": "aircraft", "col": "vintage biplane", "ex": "The vintage biplane took off from the grass strip.", "pos": "n."},
    "birch": {"def": "樺樹、樺木、樺木的、樺木地 (樺)", "ipa": "/bɜːtʃ/", "trans": "tree", "col": "birch tree, silver birch", "ex": "Birch bark was used to make canoes.", "pos": "n./adj./adv."},
    "bird": {"def": "鳥、禽、(俚)女人、(俚)人、像鳥般的、鳥類的人物、鳥類地 (鳥)", "ipa": "/bɜːd/", "trans": "birds", "col": "bird of prey, bird's-eye view, early bird (早起的人), odd bird (古怪的人)", "ex": "A small bird is singing on the branch.", "pos": "n./adj./v./adv."},
    "birdhouse": {"def": "鳥舍、鳥窩", "ipa": "/ˈbɜːdhaʊs/", "trans": "nesting box", "col": "wooden birdhouse", "ex": "He built a wooden birdhouse in his backyard.", "pos": "n."},
    "birdie": {"def": "(口)小鳥、(高爾夫)低於標準桿一桿 (單數)", "ipa": "/ˈbɜːdi/", "trans": "birdies (複數)", "col": "play a birdie", "ex": "He scored a birdie on the ninth hole.", "pos": "n."},
    "birth": {"def": "出生、分娩、起源、出身地 (生)", "ipa": "/bɜːθ/", "trans": "births", "col": "give birth to, birth rate, date of birth, from birth", "ex": "She gave birth to a healthy baby boy.", "pos": "n./adv."},
    "birthday": {"def": "生日、誕生日、生日的、在生日地 (生日)", "ipa": "/ˈbɜːθdeɪ/", "trans": "birthdays", "col": "happy birthday, birthday cake, birthday party", "ex": "Today is my eighteenth birthday.", "pos": "n./adj./adv."},
    "birthing": {"def": "生產、分娩", "ipa": "/ˈbɜːθɪŋ/", "trans": "birth (名詞/副詞)", "col": "birthing room", "ex": "The hospital provides a comfortable birthing room.", "pos": "n."},
    "birthmark": {"def": "胎記", "ipa": "/ˈbɜːθmɑːk/", "trans": "mark", "col": "faint birthmark", "ex": "She has a faint birthmark on her shoulder.", "pos": "n."},
    "birthplace": {"def": "出生地、發源地 (單數)", "ipa": "/ˈbɜːθpleɪs/", "trans": "birthplaces (複數)", "col": "Shakespeare's birthplace", "ex": "Florence is the birthplace of the Renaissance.", "pos": "n."},
    "birthright": {"def": "生來具有的權利、長子繼承權 (單數)", "ipa": "/ˈbɜːθraɪt/", "trans": "birthrights (複數)", "col": "freedom is our birthright", "ex": "Freedom of speech is seen as a universal birthright.", "pos": "n."},
    "biscotti": {"def": "義大利脆餅 (複數)", "ipa": "/bɪˈskɒti/", "trans": "biscuits", "col": "almond biscotti", "ex": "I like to dip almond biscotti in my coffee.", "pos": "n."},
    "biscuit": {"def": "餅乾、(美)小麵包、淡褐色、像餅乾般的、餅乾地 (餅)", "ipa": "/ˈbɪskɪt/", "trans": "biscuits", "col": "chocolate biscuit, dog biscuit", "ex": "Would you like a biscuit with your tea?", "pos": "n./adj./adv."},
    "bisect": {"def": "把...二等分、切斷的人 (或物)、二等份地 (切)", "ipa": "/baɪˈsekt/", "trans": "halve", "col": "bisect the angle", "ex": "The new road will bisect the town center.", "pos": "v./n./adv."},
    "bisection": {"def": "二等分、對切、切斷點", "ipa": "/baɪˈsekʃn/", "trans": "bisect (動詞/名詞/副詞)", "col": "perpendicular bisection", "ex": "The line represents the bisection of the rectangle.", "pos": "n."},
    "bisexual": {"def": "雙性戀的、兩性的、雙性戀的人、雙性戀地 (雙)", "ipa": "/ˌbaɪˈsekʃuəl/", "trans": "bisexuality", "col": "openly bisexual", "ex": "He is openly bisexual.", "pos": "adj./n./adv."},
    "bishop": {"def": "主教、(西洋棋)象、主教的人物、象地 (主教)", "ipa": "/ˈbɪʃəp/", "trans": "bishops", "col": "Anglican bishop, move the bishop", "ex": "The bishop led the church service.", "pos": "n./adv."},
    "bishopric": {"def": "主教轄區、主教職位", "ipa": "/ˈbɪʃəprɪk/", "trans": "diocese", "col": "wealthy bishopric", "ex": "He was appointed to a wealthy bishopric in the south.", "pos": "n."},
    "bismuth": {"def": "鉍 (化學元素)", "ipa": "/ˈbɪzməθ/", "trans": "metal", "col": "bismuth compound", "ex": "Bismuth is a brittle metal with a pinkish tinge.", "pos": "n."},
    "bison": {"def": "北美野牛、歐洲野牛 (單複數同形)", "ipa": "/ˈbaɪsn/", "trans": "buffalo", "col": "herd of bison", "ex": "A huge herd of bison roamed the plains.", "pos": "n."},
    "bisque": {"def": "濃湯、法式濃湯 (單數)", "ipa": "/bɪsk/", "trans": "soup", "col": "lobster bisque", "ex": "The lobster bisque was rich and creamy.", "pos": "n."},
    "bistro": {"def": "小酒館、小餐館 (單數)", "ipa": "/ˈbiːstrəʊ/", "trans": "bistros (複數)", "col": "French bistro", "ex": "We had dinner at a small French bistro.", "pos": "n."},
    "bit": {"def": "小塊、少量、一會兒、馬嚼子、二進位、(bite的過去式及過去分詞)、少許地 (小)", "ipa": "/bɪt/", "trans": "bits", "col": "a bit, bit by bit, wait a bit, quite a bit", "ex": "I'm a bit tired after the walk.", "pos": "n./v./adv."},
    "bitch": {"def": "母狗、(俚)蕩婦、潑婦、抱怨、抱怨的人、抱怨地 (怨)", "ipa": "/bɪtʃ/", "trans": "bitched", "col": "son of a bitch, stop bitching", "ex": "Stop bitching about the weather!", "pos": "n./v./adv."},
    "bitchy": {"def": "(俚)惡毒的、怨氣重的", "ipa": "/ˈbɪtʃi/", "trans": "bitch (名詞/動詞/副詞)", "col": "bitchy comment", "ex": "She made some very bitchy comments about her colleagues.", "pos": "adj."},
    "bite": {"def": "咬、刺、叮、切、咬的一口、咬的人 (或物)、叮地 (咬)", "ipa": "/baɪt/", "trans": "bit, bitten", "col": "bite the bullet (咬牙苦撐), grab a bite (吃點東西), bite off more than one can chew", "ex": "Does the dog bite?", "pos": "v./n./adv."},
}