import json

# Level 6 Part 7: (Announcement - Anthropologist)
L6_PART7 = {
    "announcement": {"def": "公告、宣告、預告", "ipa": "/əˈnaʊnsmənt/", "trans": "announce (動詞/名詞/副詞), announcer", "col": "official announcement, make an announcement", "ex": "The official announcement will be made tomorrow morning.", "pos": "n."},
    "announcer": {"def": "播音員、宣告者", "ipa": "/əˈnaʊnsə/", "trans": "announce (動詞/名詞/副詞), announcement", "col": "radio announcer, news announcer", "ex": "The radio announcer introduced the next program.", "pos": "n."},
    "annoy": {"def": "煩擾、使生氣、騷擾、煩擾的人 (或事)、煩擾地、生氣地 (煩擾)", "ipa": "/əˈnɔɪ/", "trans": "annoyance, annoying", "col": "annoy someone, deeply annoyed", "ex": "His constant complaining began to annoy her.", "pos": "v./n./adv."},
    "annoyance": {"def": "煩擾、惱怒、惱人的事", "ipa": "/əˈnɔɪəns/", "trans": "annoy (動詞/名詞/副詞), annoying", "col": "much to my annoyance, source of annoyance", "ex": "Much to my annoyance, the train was delayed again.", "pos": "n."},
    "annoying": {"def": "惱人的、令人煩惱的、打擾的", "ipa": "/əˈnɔɪɪŋ/", "trans": "annoy (動詞/名詞/副詞), annoyance", "col": "annoying habit", "ex": "He has an annoying habit of interrupting people.", "pos": "adj."},
    "annual": {"def": "每年的、週年的、年度的、年刊、一年生植物、年度地、週年地 (年度)", "ipa": "/ˈænjuəl/", "trans": "annually, annuity", "col": "annual report, annual meeting, annual salary", "ex": "The company publishes its annual report every March.", "pos": "adj./n./adv."},
    "annually": {"def": "每年地、週年地", "ipa": "/ˈænjuəli/", "trans": "annual (形容詞/名詞/副詞), annuity", "col": "held annually", "ex": "The festival is held annually in the summer.", "pos": "adv."},
    "annuity": {"def": "年金、養老金", "ipa": "/əˈnjuːəti/", "trans": "annual", "col": "life annuity", "ex": "He invested his savings in a life annuity.", "pos": "n."},
    "annul": {"def": "廢除、取消、使無效、抹去、廢除地、無效地 (廢除)", "ipa": "/əˈnʌl/", "trans": "annulment", "col": "annul a marriage", "ex": "The court decided to annul the marriage.", "pos": "v./n./adv."},
    "annulment": {"def": "廢除、取消、無效", "ipa": "/əˈnʌlmənt/", "trans": "annul (動詞/名詞/副詞)", "col": "legal annulment", "ex": "She sought a legal annulment of their agreement.", "pos": "n."},
    "annum": {"def": "年", "ipa": "/ˈænəm/", "trans": "year", "col": "per annum (每年)", "ex": "The interest rate is 5% per annum.", "pos": "n."},
    "annunciate": {"def": "宣佈、宣告、播報", "ipa": "/əˈnʌnsieɪt/", "trans": "annunciation", "col": "annunciate words", "ex": "The speaker annunciated his words clearly.", "pos": "v."},
    "anode": {"def": "陽極、正極", "ipa": "/ˈænəʊd/", "trans": "cathode", "col": "anode ray", "ex": "The current flows from the anode to the cathode.", "pos": "n."},
    "anodyne": {"def": "止痛的、緩和的、平淡的、止痛藥、緩和物", "ipa": "/ˈænədaɪn/", "trans": "soothing", "col": "anodyne remark", "ex": "He made some anodyne remarks about the weather.", "pos": "adj./n."},
    "anoint": {"def": "塗油於、神聖化、任命", "ipa": "/əˈnɔɪnt/", "trans": "anointing", "col": "anoint with oil", "ex": "The priest anointed the king with holy oil.", "pos": "v."},
    "anomalous": {"def": "異常的、不規則的、反常的", "ipa": "/əˈnɒmələs/", "trans": "anomaly", "col": "anomalous data", "ex": "The scientists found some anomalous data in their experiment.", "pos": "adj."},
    "anomaly": {"def": "異常、反常、不規則、反常的人 (或事)", "ipa": "/əˈnɒməli/", "trans": "anomalous", "col": "statistical anomaly, gravity anomaly", "ex": "The sudden drop in temperature was a statistical anomaly.", "pos": "n."},
    "anon": {"def": "不久、稍後、即刻、匿名者 (縮寫)", "ipa": "/əˈnɒn/", "trans": "soon", "col": "see you anon", "ex": "I'll see you anon.", "pos": "adv./n."},
    "anonymity": {"def": "匿名、無名、作者不詳", "ipa": "/ˌænəˈnɪməti/", "trans": "anonymous", "col": "protect anonymity", "ex": "The witness was promised anonymity to protect his safety.", "pos": "n."},
    "anonymous": {"def": "匿名的、作者不詳的、無特色的、匿名者 (匿名)", "ipa": "/əˈnɒnɪməs/", "trans": "anonymity, anonymously", "col": "anonymous donor, anonymous letter", "ex": "The letter was sent by an anonymous donor.", "pos": "adj./n./adv."},
    "anonymously": {"def": "匿名地、無名地", "ipa": "/əˈnɒnɪməsli/", "trans": "anonymous (形容詞/名詞/副詞), anonymity", "col": "donated anonymously", "ex": "The money was donated anonymously to the charity.", "pos": "adv."},
    "another": {"def": "另一個、再一個、別的、另外、別的、再一个、另一個人 (或物)、另一個地 (另一個)", "ipa": "/əˈnʌðə/", "trans": "other", "col": "one after another, one another", "ex": "Would you like another cup of tea?", "pos": "adj./pron./n./adv."},
    "answer": {"def": "回答、答案、回報、符合、回答、響應、負責、回答地、響應地 (回答)", "ipa": "/ˈɑːnsə/", "trans": "answering", "col": "answer for, answer back, in answer to", "ex": "Can you answer the question?", "pos": "n./v./adv."},
    "answerable": {"def": "應負責的、可回答的", "ipa": "/ˈɑːnsərəbl/", "trans": "answer (名詞/動詞/副詞)", "col": "answerable to", "ex": "I am not answerable to you for my actions.", "pos": "adj."},
    "ant": {"def": "螞蟻", "ipa": "/ænt/", "trans": "ants", "col": "ant nest", "ex": "An ant is a very small insect.", "pos": "n."},
    "antagonist": {"def": "對手、敵手、拮抗劑、敵對的人 (或事)", "ipa": "/ænˈtæɡənɪst/", "trans": "antagonistic, antagonize", "col": "main antagonist", "ex": "He is the main antagonist in the movie.", "pos": "n."},
    "antagonistic": {"def": "敵對的、對抗的、相反的", "ipa": "/ænˌtæɡəˈnɪstɪk/", "trans": "antagonist (名詞), antagonize", "col": "antagonistic relationship", "ex": "They have had an antagonistic relationship for years.", "pos": "adj."},
    "antagonize": {"def": "使成對手、引起敵意、抵銷", "ipa": "/ænˈtæɡənaɪz/", "trans": "antagonist, antagonistic", "col": "antagonize the boss", "ex": "You don't want to antagonize your new boss.", "pos": "v."},
    "Antarctic": {"def": "南極的、南極地帶的、南極地帶、南極圈", "ipa": "/ænˈtɑːktɪk/", "trans": "Arctic", "col": "Antarctic Circle, Antarctic ocean", "ex": "The Antarctic is the coldest place on Earth.", "pos": "adj./n."},
    "antecede": {"def": "在...之前、居先", "ipa": "/ˌæntɪˈsiːd/", "trans": "precede", "col": "antecede in time", "ex": "The causes must antecede the effect.", "pos": "v."},
    "antecedent": {"def": "先行的、之前的、(語)先行詞、前情、祖先", "ipa": "/ˌæntɪˈsiːdnt/", "trans": "antecede", "col": "historical antecedent, relative antecedent", "ex": "We must look at the historical antecedents to understand the conflict.", "pos": "adj./n."},
    "antechamber": {"def": "前廳、接待室", "ipa": "/ˈæntitʃeɪmbə/", "trans": "ante-room", "col": "magnificent antechamber", "ex": "He waited in the magnificent antechamber.", "pos": "n."},
    "antedate": {"def": "先行、早於、提早日期、前期日期", "ipa": "/ˌæntiˈdeɪt/", "trans": "predate", "col": "antedated check", "ex": "The discovery antedates the previous records by 200 years.", "pos": "v./n."},
    "antediluvian": {"def": "大洪水以前的、古風的、老掉牙的", "ipa": "/ˌæntidɪˈluːviən/", "trans": "ancient", "col": "antediluvian ideas", "ex": "He has some really antediluvian ideas about women.", "pos": "adj."},
    "antenna": {"def": "天線、觸角、直覺 (單數)", "ipa": "/ænˈtenə/", "trans": "antennas/antennae (複數)", "col": "satellite antenna, political antenna", "ex": "The butterfly has two long antennae.", "pos": "n."},
    "antennas/antennae": {"def": "天線、觸角、直覺 (複數)", "ipa": "/ænˈtenə/", "trans": "antenna (單數)", "col": "radio antennas", "ex": "The insects use their antennae to sense their surroundings.", "pos": "n."},
    "anterior": {"def": "前面的、在前的、較早的", "ipa": "/ænˈtɪəriə/", "trans": "front", "col": "anterior part", "ex": "The anterior part of the brain is responsible for complex thinking.", "pos": "adj."},
    "anthem": {"def": "國歌、聖歌、頌歌", "ipa": "/ˈænθəm/", "trans": "anthems", "col": "national anthem", "ex": "Everyone stood up for the national anthem.", "pos": "n."},
    "anthology": {"def": "選集、合集", "ipa": "/ænˈθɒlədʒi/", "trans": "collection", "col": "poetry anthology", "ex": "The book is an anthology of modern Chinese poetry.", "pos": "n."},
    "anthracite": {"def": "無煙煤、硬煤", "ipa": "/ˈænθrəsaɪt/", "trans": "coal", "col": "burn anthracite", "ex": "Anthracite is a high-quality type of coal.", "pos": "n."},
    "anthropoid": {"def": "類人的、類人猿的、類人猿", "ipa": "/ˈænθrəpɔɪd/", "trans": "human-like", "col": "anthropoid ape", "ex": "Chimpanzees are anthropoid apes.", "pos": "adj./n."},
    "anthropologist": {"def": "人類學家", "ipa": "/ˌænθrəˈpɒlədʒɪst/", "trans": "anthropology", "col": "cultural anthropologist", "ex": "He is a famous cultural anthropologist who studied island tribes.", "pos": "n."},
}