import json

# Level 6 Part 18: (Backdoor - Bag)
L6_PART18 = {
    "backdoor": {"def": "後門、秘密途徑、後門的、秘密的、後門地 (後門)", "ipa": "/ˌbækˈdɔː/", "trans": "backdoors", "col": "backdoor entry, backdoor deal", "ex": "They used a backdoor to enter the building.", "pos": "n./adj./adv."},
    "backdrops/backdrop": {"def": "背景、背景幕、事態背景", "ipa": "/ˈbækdrɒp/", "trans": "background", "col": "scenic backdrop, against the backdrop of", "ex": "The mountains provided a beautiful backdrop for the wedding.", "pos": "n."},
    "backer": {"def": "支持者、贊助人", "ipa": "/ˈbækə/", "trans": "back (名詞/動詞/形容詞/副詞/代名詞)", "col": "financial backer", "ex": "The project is still looking for a financial backer.", "pos": "n."},
    "backfire": {"def": "逆火、產生反效果、事與願違、逆火的人 (或物)、逆火地 (逆火)", "ipa": "/ˌbækˈfaɪə/", "trans": "rebound", "col": "backfire on someone", "ex": "Her plan backfired and she lost her job.", "pos": "v./n./adv."},
    "background": {"def": "背景、出身背景、經歷、幕後、背景的、背景地 (背景)", "ipa": "/ˈbækɡraʊnd/", "trans": "backgrounds", "col": "educational background, cultural background, in the background", "ex": "What is your educational background?", "pos": "n./adj./adv."},
    "backhand": {"def": "(網球)反手、反手擊球、反手的、偷偷摸摸的、反手地 (反手)", "ipa": "/ˈbækhænd/", "trans": "backhanded", "col": "strong backhand, backhand stroke, backhand compliment (明褒實貶)", "ex": "She has a very strong backhand.", "pos": "n./adj./adv./v."},
    "backing": {"def": "支持、贊助、襯裡、背景音樂、支持的人 (或物)、支持地 (支持)", "ipa": "/ˈbækɪŋ/", "trans": "support", "col": "financial backing, majority backing", "ex": "The proposal has the backing of the majority.", "pos": "n./adj./adv."},
    "backlash": {"def": "強烈反對、逆向反應、(機)齒隙", "ipa": "/ˈbæklæʃ/", "trans": "reaction", "col": "public backlash", "ex": "The government is facing a public backlash over the new tax.", "pos": "n."},
    "backlog": {"def": "積壓的工作、累計、大木柴、積壓的人 (或物)、積壓地 (積壓)", "ipa": "/ˈbæklɒɡ/", "trans": "accumulation", "col": "backlog of work, backlog of orders", "ex": "We have a huge backlog of work to catch up on.", "pos": "n./v./adv."},
    "backpacker": {"def": "自助旅行者、背包客", "ipa": "/ˈbækpækə/", "trans": "traveler", "col": "budget backpacker", "ex": "He is a budget backpacker traveling across Asia.", "pos": "n."},
    "backpacking": {"def": "背負簡便行李旅行、遠足", "ipa": "/ˈbækpækɪŋ/", "trans": "hiking", "col": "go backpacking", "ex": "They are going backpacking in Europe this summer.", "pos": "n."},
    "backrest": {"def": "靠背", "ipa": "/ˈbækrest/", "trans": "chair back", "col": "adjustable backrest", "ex": "The chair has an adjustable backrest.", "pos": "n."},
    "backside": {"def": "後部、臀部", "ipa": "/ˈbæksaɪd/", "trans": "buttocks", "col": "fall on one's backside", "ex": "He fell on his backside in the snow.", "pos": "n."},
    "backslide": {"def": "倒退、墮落、故態復萌", "ipa": "/ˈbækslaɪd/", "trans": "relapse", "col": "backslide into old habits", "ex": "It's easy to backslide into old habits.", "pos": "v."},
    "backstage": {"def": "後臺的、私下的、在後臺地、私下地 (後臺)", "ipa": "/ˌbækˈsteɪdʒ/", "trans": "behind the scenes", "col": "backstage pass, go backstage", "ex": "We were allowed to go backstage after the show.", "pos": "adj./adv."},
    "backstairs": {"def": "後樓梯的、秘密的、不正當的", "ipa": "/ˈbæksteəz/", "trans": "secret", "col": "backstairs influence", "ex": "The decision was result of backstairs influence.", "pos": "adj."},
    "backstitch": {"def": "回針縫法、回針縫", "ipa": "/ˈbækstɪtʃ/", "trans": "stitch", "col": "neat backstitch", "ex": "Use a neat backstitch to finish the edge.", "pos": "v./n."},
    "backstop": {"def": "擋球網、擋泥板、應急方案、最後防線", "ipa": "/ˈbækstɒp/", "trans": "safeguard", "col": "safety backstop", "ex": "The parent company provides a financial backstop for the subsidiary.", "pos": "n."},
    "backstroke": {"def": "(游泳)仰泳、仰泳的、仰泳地 (仰泳)", "ipa": "/ˈbækstrəʊk/", "trans": "swimming", "col": "swim backstroke", "ex": "She won the gold medal in the 100-meter backstroke.", "pos": "n./adj./adv./v."},
    "backtrack": {"def": "原路折回、退縮、撤回(意見)", "ipa": "/ˈbæktræk/", "trans": "retreat", "col": "backtrack on a promise", "ex": "The government began to backtrack on its promises.", "pos": "v."},
    "backup": {"def": "備份、支持、候補、後備的、備份的、備份的人、備用地 (備份)", "ipa": "/ˈbækʌp/", "trans": "backups", "col": "backup disk, backup plan, regular backup", "ex": "Remember to make a regular backup of your files.", "pos": "n./adj./adv."},
    "backward/backwards": {"def": "向後、倒退地、落後的、退步的、遲鈍的、向後的人、落後地 (向後)", "ipa": "/ˈbækwəd/", "trans": "forward", "col": "step backward, backward country, backward and forward", "ex": "She took a step backward.", "pos": "adj./adv./n."},
    "backwash": {"def": "洗回、(波浪)回流、後果、餘波", "ipa": "/ˈbækwɒʃ/", "trans": "aftermath", "col": "economic backwash", "ex": "The city suffered from the economic backwash of the factory closures.", "pos": "n."},
    "backwater": {"def": "回水、死水、停滯的地方、受阻地 (停滯)", "ipa": "/ˈbækˌwɔːtə/", "trans": "stagnant", "col": "cultural backwater", "ex": "The village was a quiet cultural backwater.", "pos": "n./adv."},
    "backwoods": {"def": "偏僻地區、未開發的森林地區", "ipa": "/ˈbækwʊdz/", "trans": "remote area", "col": "backwoods boy", "ex": "He grew up in the backwoods of Canada.", "pos": "n."},
    "backyard": {"def": "後院、後園、後院的、在後院地 (後院)", "ipa": "/ˌbækˈjɑːd/", "trans": "backyards", "col": "in my backyard (NIMBY)", "ex": "The children were playing in the backyard.", "pos": "n./adj./adv."},
    "bacon": {"def": "培根、燻豬肉、培根的人 (或物)", "ipa": "/ˈbeɪkən/", "trans": "bacons", "col": "save one's bacon (倖免於難), bring home the bacon (養家糊口)", "ex": "He likes eggs and bacon for breakfast.", "pos": "n./adv."},
    "bacterium": {"def": "細菌 (單數)", "ipa": "/bækˈtɪəriəm/", "trans": "bacteria (複數)", "col": "harmful bacterium", "ex": "The disease is caused by a specific type of bacterium.", "pos": "n."},
    "bacteria": {"def": "細菌 (複數)", "ipa": "/bækˈtɪəriə/", "trans": "bacterium (單數)", "col": "beneficial bacteria, bacteria count", "ex": "Many bacteria are actually beneficial to humans.", "pos": "n."},
    "bacterial": {"def": "細菌的、由細菌引起的", "ipa": "/bækˈtɪəriəl/", "trans": "bacteria (名詞)", "col": "bacterial infection", "ex": "The patient has a serious bacterial infection.", "pos": "adj."},
    "bad": {"def": "壞的、不利的、嚴重的、壞事、壞人、差勁地、壞地 (壞)", "ipa": "/bæd/", "trans": "worst", "col": "bad luck, feel bad about, go from bad to worse", "ex": "Smoking is bad for your health.", "pos": "adj./n./adv."},
    "badder/baddest": {"def": "(bad的比較級/最高級)、極壞的、最壞的 (坏)", "ipa": "/ˈbædə/", "trans": "worse/worst", "col": "badder than", "ex": "He is the baddest boy in the school (俚：他最酷).", "pos": "adj./adv."},
    "bade": {"def": "(bid的過去式)、出價、吩咐", "ipa": "/beɪd/", "trans": "bid", "col": "bade farewell (告別)", "ex": "He bade farewell to his friends.", "pos": "v."},
    "badge": {"def": "徽章、標記、象徵、授以徽章、標記的人 (或物)、標記地 (標記)", "ipa": "/bædʒ/", "trans": "badges", "col": "school badge, police badge, merit badge", "ex": "She was wearing a badge on her coat.", "pos": "n./v./adv."},
    "badger": {"def": "獾、騷擾者、糾纏、騷擾者的人 (或物)、騷擾地 (騷擾)", "ipa": "/ˈbædʒə/", "trans": "badgers", "col": "badger someone to do something", "ex": "The children badgered their parents for more sweets.", "pos": "n./v./adv."},
    "badly": {"def": "壞地、拙劣地、極度地", "ipa": "/ˈbædli/", "trans": "bad (形容詞/名詞/副詞)", "col": "badly injured, badly needed", "ex": "He was badly injured in the accident.", "pos": "adv."},
    "badminton": {"def": "羽毛球", "ipa": "/ˈbædmɪntən/", "trans": "badmintons", "col": "play badminton, badminton court", "ex": "Badminton is a very popular sport in Asia.", "pos": "n."},
    "baffle": {"def": "使困惑、挫敗、擋板、屏障、困惑的人 (或物)、困惑地 (困惑)", "ipa": "/ˈbæfl/", "trans": "baffling", "col": "total baffle, baffle everyone", "ex": "The murder case continue to baffle the police.", "pos": "v./n./adv."},
    "bafflement": {"def": "困惑、挫敗、迷惑", "ipa": "/ˈbæflmənt/", "trans": "baffle (動詞/名詞/副詞)", "col": "look of bafflement", "ex": "There was a look of bafflement on her face.", "pos": "n."},
    "baffling": {"def": "令人困惑的、阻礙的", "ipa": "/ˈbæflɪŋ/", "trans": "baffle (動詞/名詞/副詞)", "col": "baffling problem", "ex": "It's a baffling problem that no one can solve.", "pos": "adj."},
    "bag": {"def": "提袋、袋子、獵獲物、把...裝進袋、獵獲、袋裝地 (袋)", "ipa": "/bæɡ/", "trans": "bags", "col": "plastic bag, shopping bag, bag and baggage (全部隨身物品)", "ex": "She carried her shopping in a large plastic bag.", "pos": "n./v./adv."},
}