import json

# Level 6 Part 4: (Affix - Ally)
L6_PART4 = {
    "affix": {"def": "詞綴、附加物、附加、貼上、把...附於", "ipa": "/əˈfɪks/ (v.) /ˈæfɪks/ (n.)", "trans": "affixed", "col": "prefix and suffix, affix a stamp", "ex": "A prefix is a type of affix.", "pos": "n./v."},
    "afflict": {"def": "折磨、使苦惱、使受難", "ipa": "/əˈflɪkt/", "trans": "affliction", "col": "afflicted with", "ex": "The country was afflicted by a severe famine.", "pos": "v."},
    "affliction": {"def": "折磨、痛苦、災難", "ipa": "/əˈflɪkʃn/", "trans": "afflict (動詞)", "col": "great affliction", "ex": "Poverty is a great affliction for many people.", "pos": "n."},
    "affluence": {"def": "富裕、豐富、匯聚", "ipa": "/ˈæfluəns/", "trans": "affluent", "col": "era of affluence", "ex": "The country entered a new era of affluence.", "pos": "n."},
    "affluent": {"def": "富裕的、豐富的、流暢的、支流、富人", "ipa": "/ˈæfluənt/", "trans": "affluence (名詞)", "col": "affluent society", "ex": "He lives in an affluent neighborhood.", "pos": "adj./n."},
    "afford": {"def": "負擔得起、提供、給予", "ipa": "/əˈfɔːd/", "trans": "affordable", "col": "can afford to", "ex": "We can't afford to buy a new car.", "pos": "v."},
    "affordable": {"def": "負擔得起的、便宜的", "ipa": "/əˈfɔːdəbl/", "trans": "afford (動詞)", "col": "affordable housing", "ex": "The city needs more affordable housing.", "pos": "adj."},
    "afforestation": {"def": "造林、綠化", "ipa": "/əˌfɒrɪˈsteɪʃn/", "trans": "forest", "col": "large-scale afforestation", "ex": "The government is promoting large-scale afforestation.", "pos": "n."},
    "affray": {"def": "鬧事、打鬥、驚恐", "ipa": "/əˈfreɪ/", "trans": "brawl", "col": "guilty of affray", "ex": "He was charged with affray after the bar fight.", "pos": "n."},
    "affront": {"def": "侮辱、冒犯、面對、侮辱、冒犯", "ipa": "/əˈfrʌnt/", "trans": "affronted", "col": "personal affront", "ex": "His remarks were a personal affront to me.", "pos": "n./v."},
    "aficionado": {"def": "愛好者、迷", "ipa": "/əˌfɪʃiəˈnɑːdəʊ/", "trans": "fan", "col": "opera aficionado", "ex": "He is a real opera aficionado.", "pos": "n."},
    "afraid": {"def": "害怕的、擔心的、遺憾的", "ipa": "/əˈfreɪd/", "trans": "fear", "col": "afraid of", "ex": "I'm afraid I can't help you.", "pos": "adj."},
    "afresh": {"def": "重新、再度", "ipa": "/əˈfreʃ/", "trans": "fresh", "col": "start afresh", "ex": "He decided to start his life afresh in a new country.", "pos": "adv."},
    "afterglow": {"def": "晚霞、餘暉、美好回憶的回味", "ipa": "/ˈɑːftəɡləʊ/", "trans": "glow", "col": "golden afterglow", "ex": "The mountains were bathed in the golden afterglow of the sunset.", "pos": "n."},
    "aftermath": {"def": "後果、餘波", "ipa": "/ˈɑːftəmæθ/", "trans": "consequence", "col": "in the aftermath of", "ex": "Many people were left homeless in the aftermath of the earthquake.", "pos": "n."},
    "afterthought": {"def": "事後的想法、追加內容", "ipa": "/ˈɑːftəθɔːt/", "trans": "thought", "col": "merely an afterthought", "ex": "The last chapter seemed like merely an afterthought.", "pos": "n."},
    "afterwards/afterward": {"def": "之後、後來、以後", "ipa": "/ˈɑːftəwədz/", "trans": "after", "col": "shortly afterwards", "ex": "We had dinner and went to the cinema afterwards.", "pos": "adv."},
    "again": {"def": "再次、重新、此外、由於、再、又一回、反覆地 (再次)", "ipa": "/əˈɡen/", "trans": "again and again", "col": "once again, time and again", "ex": "Please say that again.", "pos": "adv./n."},
    "against": {"def": "反對、對抗、倚靠、防備、相比、反對、對抗地、不利地 (反對)", "ipa": "/əˈɡenst/", "trans": "opposed", "col": "against the law, lean against", "ex": "Stealing is against the law.", "pos": "prep./adv."},
    "agape": {"def": "張口發呆的、目瞪口呆的、(基督)聖餐、博愛", "ipa": "/əˈɡeɪp/", "trans": "staring", "col": "mouth agape", "ex": "He stood there with his mouth agape in surprise.", "pos": "adj./n."},
    "agate": {"def": "瑪瑙", "ipa": "/ˈæɡət/", "trans": "agates", "col": "blue agate", "ex": "She was wearing a necklace made of blue agate.", "pos": "n."},
    "age": {"def": "年齡、時代、時期、老年、變老、使變老、老化、陳年的、老年的 (年齡)", "ipa": "/eɪdʒ/", "trans": "aging, aged", "col": "middle age, iceberg age, old age", "ex": "What is your age?", "pos": "n./v./adj."},
    "aged": {"def": "年老的、有...歲的、陳年的", "ipa": "/eɪdʒd/", "trans": "age (名詞/動詞/形容詞), aging", "col": "aged 10, aged parents", "ex": "He has two children, aged 10 and 12.", "pos": "adj."},
    "agency": {"def": "代理店、機構、作用、力量", "ipa": "/ˈeɪdʒənsi/", "trans": "agent", "col": "travel agency, advertising agency, news agency", "ex": "I booked the holiday through a travel agency.", "pos": "n."},
    "agenda": {"def": "議程、計畫、意圖", "ipa": "/əˈdʒendə/", "trans": "agendas", "col": "hidden agenda, political agenda, set the agenda", "ex": "The next item on the agenda is the budget.", "pos": "n."},
    "agent": {"def": "代理人、特工、媒介、原動力、代理的、起作用的、代理地 (代理)", "ipa": "/ˈeɪdʒənt/", "trans": "agency, agential", "col": "estate agent, secret agent, cleaning agent", "ex": "He is a secret agent working for the government.", "pos": "n./adj./adv."},
    "agglomerate": {"def": "使成圃、凝聚、成群的、(地質)集塊岩、集塊", "ipa": "/əˈɡlɒməreɪt/", "trans": "agglomeration", "col": "agglomerate particles", "ex": "The small particles began to agglomerate into larger clumps.", "pos": "v./adj./n."},
    "agglutinate": {"def": "黏合、(語)黏著、凝集、黏合的、黏著地", "ipa": "/əˈɡluːtɪneɪt/", "trans": "agglutination", "col": "agglutinate red cells", "ex": "The bacteria cause the red cells to agglutinate.", "pos": "v./adj./adv."},
    "aggrandize": {"def": "擴大、誇張、誇大", "ipa": "/əˈɡrændɪzaɪ/", "trans": "aggrandizement", "col": "self-aggrandize", "ex": "He sought to aggrandize himself at the expense of others.", "pos": "v."},
    "aggravate": {"def": "加重、惡化、激怒、惹惱", "ipa": "/ˈæɡrəveɪt/", "trans": "aggravation", "col": "aggravate a situation", "ex": "Stress can aggravate certain medical conditions.", "pos": "v."},
    "aggravation": {"def": "加重、惡化、惱人的事", "ipa": "/ˌæɡrəˈveɪʃn/", "trans": "aggravate (動詞)", "col": "constant aggravation", "ex": "Dealing with the bureaucracy was a constant aggravation.", "pos": "n."},
    "aggregate": {"def": "合計、總計、集合、合計的、集合的、合計、聚集、合計、總計地 (合計)", "ipa": "/ˈæɡrɪɡət/ (n./adj.) /ˈæɡrɪɡeɪt/ (v.)", "trans": "aggregation", "col": "in the aggregate, aggregate demand", "ex": "The aggregate goal is to improve the quality of life.", "pos": "n./adj./v./adv."},
    "aggression": {"def": "侵略、攻擊、挑釁", "ipa": "/əˈɡreʃn/", "trans": "aggressive, aggressor", "col": "act of aggression, military aggression", "ex": "The invasion was an unprovoked act of aggression.", "pos": "n."},
    "aggressive": {"def": "侵略性的、好鬥的、積極進取的、(醫)劇烈的、侵略地、主動地 (侵略)", "ipa": "/əˈɡresɪv/", "trans": "aggressively, aggression", "col": "aggressive behavior, aggressive marketing", "ex": "The company uses aggressive marketing tactics.", "pos": "adj./adv."},
    "aggressively": {"def": "侵略地、好鬥地、積極進取地", "ipa": "/əˈɡresɪvli/", "trans": "aggressive (形容詞/副詞), aggression", "col": "act aggressively", "ex": "He acted aggressively towards the police.", "pos": "adv."},
    "aggressor": {"def": "侵略者、挑釁者", "ipa": "/əˈɡresə/", "trans": "aggression, aggressive", "col": "identify the aggressor", "ex": "The international community condemned the aggressor.", "pos": "n."},
    "aggrieve": {"def": "使悲痛、使受屈、侵害", "ipa": "/əˈɡriːv/", "trans": "aggrieved", "col": "aggrieved party", "ex": "He felt aggrieved by the decision.", "pos": "v."},
    "aghast": {"def": "驚駭的、嚇呆的", "ipa": "/əˈɡɑːst/", "trans": "shocked", "col": "aghast at", "ex": "She was aghast at the news of the accident.", "pos": "adj."},
    "agile": {"def": "敏捷的、活潑的、機敏的", "ipa": "/ˈædʒaɪl/", "trans": "agility", "col": "agile development, agile mind", "ex": "The cat is very agile and can jump high.", "pos": "adj."},
    "agility": {"def": "敏捷、靈活、機敏", "ipa": "/əˈdʒɪləti/", "trans": "agile (形容詞)", "col": "mental agility", "ex": "He has remarkable mental agility for his age.", "pos": "n."},
    "agitate": {"def": "攪動、使激動、煽動、討論", "ipa": "/ˈædʒɪteɪt/", "trans": "agitation, agitator", "col": "agitate for change", "ex": "They are agitating for better working conditions.", "pos": "v."},
    "agitation": {"def": "激動、不安、煽動、攪動", "ipa": "/ˌædʒɪˈteɪʃn/", "trans": "agitate (動詞)", "col": "political agitation", "ex": "There was a lot of political agitation in the streets.", "pos": "n."},
    "agitator": {"def": "煽動者、攪拌器", "ipa": "/ˈædʒɪteɪtə/", "trans": "agitate (動詞), agitation", "col": "political agitator", "ex": "The police arrested the political agitator.", "pos": "n."},
    "agnostic": {"def": "不可知論者、不可知論的、不確定的", "ipa": "/æɡˈnɒstɪk/", "trans": "agnosticism", "col": "purely agnostic", "ex": "He is an agnostic and doesn't know if God exists.", "pos": "n./adj."},
    "agog": {"def": "興奮的、熱切的、焦急的、渴望地", "ipa": "/əˈɡɒɡ/", "trans": "eager", "col": "all agog", "ex": "We were all agog to hear the news.", "pos": "adj./adv."},
    "agony": {"def": "極大的痛苦、苦惱、臨死的痛苦", "ipa": "/ˈæɡəni/", "trans": "agonize", "col": "in agony, agony aunt", "ex": "He was screaming in agony.", "pos": "n."},
    "agrarian": {"def": "土地的、農民的、農業的、農民、(古)分配土地的人", "ipa": "/əˈɡreəriən/", "trans": "agronomy", "col": "agrarian reform", "ex": "The government is introducing agrarian reform.", "pos": "adj./n."},
    "agree": {"def": "同意、答應、符合、商定、和諧地、一致地 (同意)", "ipa": "/əˈɡriː/", "trans": "agreement, agreeable", "col": "agree with, agree to, agree on", "ex": "I agree with you completely.", "pos": "v./adv."},
    "agreeable": {"def": "令人愉快的、宜人的、同意的、準備好的", "ipa": "/əˈɡriːəbl/", "trans": "agree (動詞/副詞), agreement", "col": "agreeable person, agreeable weather", "ex": "We spent an agreeable afternoon in the park.", "pos": "adj."},
    "agreement": {"def": "同意、協議、契約、一致、和諧地 (同意)", "ipa": "/əˈɡriːmənt/", "trans": "agree (動詞/副詞), agreeable", "col": "sign an agreement, legal agreement, come to an agreement", "ex": "We have signed a legal agreement.", "pos": "n./adv."},
    "agriculture": {"def": "農業、農學、農耕", "ipa": "/ˈæɡrɪkʌltʃə/", "trans": "agricultural", "col": "modern agriculture", "ex": "Agriculture is the main industry in the region.", "pos": "n."},
    "agronomy": {"def": "農學、農藝學、作物學", "ipa": "/əˈɡrɒnəmi/", "trans": "agronomist", "col": "principles of agronomy", "ex": "She is studying agronomy at the agricultural college.", "pos": "n."},
    "ahead": {"def": "在前面、領先、預先、向前的、前進地、領先地 (在前面)", "ipa": "/əˈhed/", "trans": "far ahead", "col": "ahead of time, go ahead, get ahead", "ex": "There is a car ahead of us.", "pos": "adv./adj."},
    "aid": {"def": "幫助、助手、輔助、援助、幫助、救助、幫助地、辅助地 (幫助)", "ipa": "/eɪd/", "trans": "aided", "col": "first aid, financial aid, with the aid of", "ex": "They are providing financial aid for the victims.", "pos": "n./v./adv."},
    "aide": {"def": "助手、副官、助理", "ipa": "/eɪd/", "trans": "aides", "col": "presidential aide", "ex": "He is a close presidential aide.", "pos": "n."},
    "AIDS": {"def": "愛滋病", "ipa": "/eɪdz/", "trans": "HIV", "col": "AIDS virus", "ex": "Scientists are working on a cure for AIDS.", "pos": "n."},
    "ail": {"def": "使生病、使苦惱、生病、憂慮、生病地、苦惱地 (生病)", "ipa": "/eɪl/", "trans": "ailing, ailment", "col": "what ails you", "ex": "What ails you today?", "pos": "v./n./adv."},
    "ailment": {"def": "小病、不安", "ipa": "/ˈeɪlmənt/", "trans": "ail (動詞/名詞/副詞)", "col": "minor ailment", "ex": "She is suffering from a minor ailment.", "pos": "n."},
    "aim": {"def": "目標、對準、意圖、瞄準、對準、力求、旨在、瞄準地、有目的地 (目標)", "ipa": "/eɪm/", "trans": "aimless, aiming", "col": "aim at, take aim, with the aim of", "ex": "My aim is to become a doctor.", "pos": "n./v./adv."},
    "aimless": {"def": "漫無目的的、無目標的", "ipa": "/ˈeɪmləs/", "trans": "aim (名詞/動詞/副詞), aimlessly", "col": "aimless life", "ex": "He led an aimless life after losing his job.", "pos": "adj."},
    "aimlessly": {"def": "漫無目的地、無目標地", "ipa": "/ˈeɪmləsli/", "trans": "aimless (形容詞), aim", "col": "drift aimlessly", "ex": "The boat drifted aimlessly in the sea.", "pos": "adv."},
    "air": {"def": "空氣、天空、樣子、曲調、晾乾、播送、吹捧、空中的、高架的、空中地、虛假地 (空氣)", "ipa": "/eə/", "trans": "airy, aircraft", "col": "by air, on the air, open air", "ex": "I need some fresh air.", "pos": "n./v./adj./adv."},
    "aircraft": {"def": "飛機、飛行器", "ipa": "/ˈeəkrɑːft/", "trans": "airplane", "col": "military aircraft, civil aircraft", "ex": "The aircraft is ready for takeoff.", "pos": "n."},
    "airfield": {"def": "飛機場", "ipa": "/ˈeəfiːld/", "trans": "airport", "col": "military airfield", "ex": "The military airfield is heavily guarded.", "pos": "n."},
    "airing": {"def": "晾、播送、通風、廣泛討論", "ipa": "/ˈeərɪŋ/", "trans": "air (名詞/動詞/形容詞/副詞)", "col": "give a problem an airing", "ex": "The problem needs a thorough airing.", "pos": "n."},
    "airline": {"def": "航空公司、航班、航線的", "ipa": "/ˈeəlaɪn/", "trans": "airlines", "col": "major airline, national airline", "ex": "He works for a major international airline.", "pos": "n./adj."},
    "airliner": {"def": "大型客機、班機", "ipa": "/ˈeəlaɪnə/", "trans": "airplane", "col": "commercial airliner", "ex": "The airliner crashed shortly after takeoff.", "pos": "n."},
    "airmail": {"def": "航空郵件、用掛號寄、航空的", "ipa": "/ˈeəmeɪl/", "trans": "mail", "col": "by airmail", "ex": "I sent the letter by airmail.", "pos": "n./v./adj."},
    "airplane": {"def": "飛機、用飛機運送、飛機的", "ipa": "/ˈeəpleɪn/", "trans": "plane", "col": "jet airplane", "ex": "The airplane is flying at a high altitude.", "pos": "n./v./adj."},
    "airport": {"def": "機場、航空港", "ipa": "/ˈeəpɔːt/", "trans": "airfield", "col": "international airport", "ex": "We arrived at the international airport early.", "pos": "n."},
    "airspace": {"def": "領空、空間、大氣空間", "ipa": "/ˈeəspeɪs/", "trans": "space", "col": "restricted airspace", "ex": "The aircraft entered restricted airspace.", "pos": "n."},
    "airtight": {"def": "不透氣的、密封的、無懈可擊的", "ipa": "/ˈeətaɪt/", "trans": "tight", "col": "airtight container", "ex": "Keep the coffee in an airtight container.", "pos": "adj."},
    "airy": {"def": "通風的、輕快的、虛幻的、空中的", "ipa": "/ˈeəri/", "trans": "air (名詞/動詞/形容詞/副詞)", "col": "airy room", "ex": "The house has a lot of large, airy rooms.", "pos": "adj."},
    "aisle": {"def": "走道、通道、側廊", "ipa": "/aɪl/", "trans": "aisles", "col": "supermarket aisle, walk down the aisle (結婚)", "ex": "The supermarket aisles are very wide.", "pos": "n."},
    "ajar": {"def": "微開的、不和諧的、微開地 (微開)", "ipa": "/əˈdʒɑː/", "trans": "open", "col": "door ajar", "ex": "The door was left slightly ajar.", "pos": "adj./adv."},
    "akin": {"def": "同族的、類似的", "ipa": "/əˈkɪn/", "trans": "related", "col": "akin to", "ex": "Pity is often akin to love.", "pos": "adj."},
    "alarm": {"def": "警報、驚恐、鬧鐘、警報、嚇唬、使不安、警報地、驚恐地 (警報)", "ipa": "/əˈlɑːm/", "trans": "alarmed, alarming", "col": "fire alarm, alarm clock, raise the alarm", "ex": "I set my alarm for 6 o'clock.", "pos": "n./v./adv."},
    "alarmed": {"def": "驚恐的、擔心的、裝有警報器的", "ipa": "/əˈlɑːmd/", "trans": "alarm (名詞/動詞/副詞), alarming", "col": "alarmed by", "ex": "We were alarmed by the news of the explosion.", "pos": "adj."},
    "alarming": {"def": "告急的、使人驚愕的、危急的", "ipa": "/əˈlɑːmɪŋ/", "trans": "alarm (名詞/動詞/副詞), alarmed", "col": "alarming rate", "ex": "The forest is being destroyed at an alarming rate.", "pos": "adj."},
    "alas": {"def": "唉、嗚呼", "ipa": "/əˈlæs/", "trans": "unfortunately", "col": "alas, it is true", "ex": "Alas, she died young.", "pos": "int."},
    "albatross": {"def": "信天翁、沉重負擔", "ipa": "/ˈælbətrɒs/", "trans": "birds", "col": "albatross around one's neck", "ex": "The project became an albatross around his neck.", "pos": "n."},
    "albeit": {"def": "儘管、雖然", "ipa": "/ˌɔːlˈbiːɪt/", "trans": "although", "col": "albeit necessary", "ex": "He finally agreed, albeit reluctantly.", "pos": "conj."},
    "alchemist": {"def": "煉金術士", "ipa": "/ˈælkəmɪst/", "trans": "alchemy", "col": "famous alchemist", "ex": "In the past, many people wanted to become alchemists.", "pos": "n."},
    "alchemy": {"def": "煉金術、魔力", "ipa": "/ˈælkəmi/", "trans": "alchemist", "col": "ancient alchemy", "ex": "Alchemy was a branch of natural philosophy.", "pos": "n."},
    "alcohol": {"def": "酒精、酒", "ipa": "/ˈælkəhɒl/", "trans": "alcoholic, alcoholism", "col": "rubbing alcohol, alcohol abuse", "ex": "He doesn't drink alcohol.", "pos": "n."},
    "alcoholic": {"def": "酒精的、酗酒的、酗酒者、酒鬼、酒精地", "ipa": "/ˌælkəˈhɒlɪk/", "trans": "alcohol (名詞), alcoholism", "col": "alcoholic beverage, recovering alcoholic", "ex": "Beer is an alcoholic beverage.", "pos": "adj./n./adv."},
    "alcoholism": {"def": "酒精中毒、酗酒", "ipa": "/ˈælkəhɒlɪzəm/", "trans": "alcohol, alcoholic", "col": "suffer from alcoholism", "ex": "Alcoholism is a serious disease.", "pos": "n."},
    "alcove": {"def": "凹室、壁櫥、涼亭", "ipa": "/ˈælkəʊv/", "trans": "alcoves", "col": "dining alcove", "ex": "The bed was set in a small alcove.", "pos": "n."},
    "alderman": {"def": "市議員、顯貴、高级市政官", "ipa": "/ˈɔːldəmən/", "trans": "aldermen", "col": "local alderman", "ex": "He is serving as a local alderman.", "pos": "n."},
    "ale": {"def": "麥芽酒、淡啤酒", "ipa": "/eɪl/", "trans": "beer", "col": "ginger ale", "ex": "I'd like a bottle of ginger ale, please.", "pos": "n."},
    "alert": {"def": "警覺的、靈敏的、預先通知的、警報、警戒、使警覺、使意識到、警覺地、靈敏地 (警覺)", "ipa": "/əˈlɜːt/", "trans": "alertness", "col": "stay alert, on the alert, alert a security", "ex": "The soldiers were on high alert.", "pos": "adj./n./v./adv."},
    "alertness": {"def": "警覺、機敏", "ipa": "/əˈlɜːtnəs/", "trans": "alert (形容詞/名詞/動詞/副詞)", "col": "mental alertness", "ex": "The coffee increased his mental alertness.", "pos": "n."},
    "alfalfa": {"def": "紫苜蓿", "ipa": "/ælˈfælfə/", "trans": "lucerne", "col": "alfalfa sprout", "ex": "Alfalfa is a major forage crop.", "pos": "n."},
    "algae": {"def": "藻類、海藻", "ipa": "/ˈældʒiː/", "trans": "algal, alga (單數)", "col": "green algae", "ex": "The pond is covered with green algae.", "pos": "n."},
    "algebra": {"def": "代數學", "ipa": "/ˈældʒɪbrə/", "trans": "algebraic", "col": "linear algebra", "ex": "I am studying linear algebra this semester.", "pos": "n."},
    "alias": {"def": "別名、化名、又名、別名地 (別名)", "ipa": "/ˈeɪliəs/", "trans": "aliased", "col": "known by an alias", "ex": "The criminal used several aliases.", "pos": "n./adv."},
    "alibi": {"def": "不在場證明、託辭、藉口、辯解", "ipa": "/ˈæləbaɪ/", "trans": "alibis", "col": "solid alibi", "ex": "The police confirmed his alibi.", "pos": "n."},
    "alien": {"def": "外星人、外僑、外來者、外國的、異己的、格格不入的、排斥、轉讓、外國地 (外星人)", "ipa": "/ˈeɪliən/", "trans": "alienate, alienation", "col": "alien creature, illegal alien, alien to", "ex": "The movie is about an alien creature from another planet.", "pos": "n./adj./v./adv."},
    "alienate": {"def": "疏遠、離間、轉讓", "ipa": "/ˈeɪliəneɪt/", "trans": "alienation, alien", "col": "alienate friends", "ex": "His behavior alienated many of his friends.", "pos": "v."},
    "alienation": {"def": "疏遠、離間、轉讓、精神錯亂", "ipa": "/ˌeɪliəˈneɪʃn/", "trans": "alienate (動詞), alien", "col": "social alienation", "ex": "The youth showed signs of social alienation.", "pos": "n."},
    "alight": {"def": "燃燒的、點亮的、閃亮的、下來、落下、下來地、落下地、發光地 (落下)", "ipa": "/əˈlaɪt/", "trans": "alighting", "col": "alight from a bus", "ex": "He waited for the passengers to alight from the train.", "pos": "adj./v./adv."},
    "align": {"def": "排整齊、對齊、結盟", "ipa": "/əˈlaɪn/", "trans": "alignment", "col": "align with", "ex": "Please align the text to the left.", "pos": "v."},
    "alignment": {"def": "排成直線、對齊、結盟、調節、陣線", "ipa": "/əˈlaɪnmənt/", "trans": "align (動詞)", "col": "political alignment", "ex": "The wheels need proper alignment.", "pos": "n."},
    "alike": {"def": "相似的、相同的、同樣地、相似地 (相似)", "ipa": "/əˈlaɪk/", "trans": "similar", "col": "look alike", "ex": "The two brothers look very alike.", "pos": "adj./adv."},
    "alimentary": {"def": "營養的、食物的、消化道的", "ipa": "/ˌæliˈmentri/", "trans": "aliment", "col": "alimentary canal (消化道)", "ex": "The alimentary canal is a long tube from mouth to anus.", "pos": "adj."},
    "alimony": {"def": "贍養費", "ipa": "/ˈæləməni/", "trans": "pension", "col": "pay alimony", "ex": "He has been paying alimony to his ex-wife for years.", "pos": "n."},
    "alive": {"def": "活著的、活躍的、活潑的、敏感的、注意到、活著地、活潑地 (活著)", "ipa": "/əˈlaɪv/", "trans": "life", "col": "keep alive, alive and kicking, alive to", "ex": "Is the plant still alive?", "pos": "adj./adv."},
    "alkali": {"def": "鹼、鹼金屬、鹼性的", "ipa": "/ˈælkəlaɪ/", "trans": "alkaline", "col": "caustic alkali", "ex": "Sodium hydroxide is a strong alkali.", "pos": "n./adj."},
    "allay": {"def": "減輕、緩和、使平靜", "ipa": "/əˈleɪ/", "trans": "soothe", "col": "allay fears", "ex": "The government is trying to allay public fears about the economy.", "pos": "v."},
    "allege": {"def": "指控、宣稱、斷言", "ipa": "/əˈledʒ/", "trans": "allegation, allegedly", "col": "allege that", "ex": "The report alleges that the company has been avoiding taxes.", "pos": "v."},
    "allegation": {"def": "指控、陳述、宣稱", "ipa": "/ˌæləˈɡeɪʃn/", "trans": "allege (動詞), allegedly", "col": "serious allegation", "ex": "The police are investigating serious allegations of corruption.", "pos": "n."},
    "allegedly": {"def": "據稱、據說", "ipa": "/əˈledʒɪdli/", "trans": "allege (動詞), allegation", "col": "allegedly committed", "ex": "The crime was allegedly committed last night.", "pos": "adv."},
    "allegiance": {"def": "忠誠、效忠", "ipa": "/əˈliːdʒəns/", "trans": "loyalty", "col": "oath of allegiance", "ex": "The soldiers swore allegiance to the king.", "pos": "n."},
    "allegory": {"def": "寓言、諷喻", "ipa": "/ˈæləɡəri/", "trans": "allegorical", "col": "political allegory", "ex": "The story can be read as a political allegory.", "pos": "n."},
    "allergic": {"def": "過敏的、對...極討厭的", "ipa": "/əˈlɜːdʒɪk/", "trans": "allergy, allergen", "col": "allergic reaction, allergic to", "ex": "She is allergic to peanuts.", "pos": "adj."},
    "allergy": {"def": "過敏、反感", "ipa": "/ˈælədʒi/", "trans": "allergic (形容詞), allergen", "col": "food allergy, seasonal allergy", "ex": "I have an allergy to pollen.", "pos": "n."},
    "alleviate": {"def": "減輕、緩和", "ipa": "/əˈliːvieɪt/", "trans": "alleviation", "col": "alleviate pain", "ex": "The medicine should help to alleviate the pain.", "pos": "v."},
    "alley": {"def": "胡同、弄、小徑、球道", "ipa": "/ˈæli/", "trans": "alleys", "col": "blind alley (死胡同), bowling alley", "ex": "The cat ran down the dark alley.", "pos": "n."},
    "alliance": {"def": "聯盟、同盟、姻親", "ipa": "/əˈlaɪəns/", "trans": "ally", "col": "form an alliance, strategic alliance", "ex": "The two companies formed a strategic alliance.", "pos": "n."},
    "allied": {"def": "同盟的、聯合的、相關的", "ipa": "/ˈælaɪd/", "trans": "ally (名詞/動詞/副詞), alliance", "col": "allied forces", "ex": "The allied forces attacked the enemy positions.", "pos": "adj."},
    "alligator": {"def": "短吻鱷、產於美洲之鱷、鱷魚皮、(機)夾鉗、美洲鱷魚的", "ipa": "/ˈælɪɡeɪtə/", "trans": "alligators", "col": "alligator skin", "ex": "Watch out for alligators in the swamp.", "pos": "n./adj."},
    "alliterate": {"def": "押頭韻、使用頭韻、(語)押頭韻", "ipa": "/əˈlɪtəreɪt/", "trans": "alliteration", "col": "alliterate with", "ex": "The words alliterate with the sound 'S'.", "pos": "v."},
    "alliteration": {"def": "頭韻、(語)押頭韻", "ipa": "/əˌlɪtəˈreɪʃn/", "trans": "alliterate (動詞)", "col": "poetic alliteration", "ex": "The poem uses a lot of alliteration.", "pos": "n."},
    "allocate": {"def": "分配、撥給、分派", "ipa": "/ˈæləkeɪt/", "trans": "allocation", "col": "allocate resources", "ex": "The government will allocate more funds to education.", "pos": "v."},
    "allocation": {"def": "分配、撥給、分配額、配給額", "ipa": "/ˌæləˈkeɪʃn/", "trans": "allocate (動詞)", "col": "resource allocation", "ex": "We need to optimize the resource allocation.", "pos": "n."},
    "allot": {"def": "分配、撥給、分派", "ipa": "/əˈlɒt/", "trans": "allotment", "col": "allot time", "ex": "They allotted a specific time for each speaker.", "pos": "v."},
    "allotment": {"def": "分配、撥給、分配額、配給物", "ipa": "/əˈlɒtmənt/", "trans": "allot (動詞)", "col": "monthly allotment", "ex": "He received his monthly allotment of fuel.", "pos": "n."},
    "allow": {"def": "允許、給予、認可、考慮、准許地 (允許)", "ipa": "/əˈlaʊ/", "trans": "allowance, allowable", "col": "allow for, allow in", "ex": "Please allow me to introduce myself.", "pos": "v./adv."},
    "allowance": {"def": "津貼、補助、零用錢、體諒、容差", "ipa": "/əˈlaʊəns/", "trans": "allow (動詞/副詞), allowable", "col": "make allowance for, baggage allowance", "ex": "He gets a monthly allowance from his parents.", "pos": "n."},
    "alloy": {"def": "合金、雜質、把...成合金、減弱、摻雜、合金的、摻雜地 (合金)", "ipa": "/ˈælɔɪ/", "trans": "alloys", "col": "aluminum alloy", "ex": "Brass is an alloy of copper and zinc.", "pos": "n./v./adj./adv."},
    "allude": {"def": "暗示、間接提到", "ipa": "/əˈluːd/", "trans": "allusion", "col": "allude to", "ex": "He alluded to the problem in his speech.", "pos": "v."},
    "allure": {"def": "誘惑、魅力、吸引力、誘惑、吸引、引誘", "ipa": "/əˈlʊə/", "trans": "alluring", "col": "sexual allure", "ex": "The island has a special allure for tourists.", "pos": "n./v."},
    "alluring": {"def": "誘人的、迷人的、吸引人的", "ipa": "/əˈlʊərɪŋ/", "trans": "allure (名詞/動詞), alluringly", "col": "alluring smile", "ex": "She has an alluring smile.", "pos": "adj."},
    "allusion": {"def": "暗示、間接提到、點故", "ipa": "/əˈluːʒn/", "trans": "allude (動詞)", "col": "literary allusion", "ex": "The poem is full of literary allusions.", "pos": "n."},
    "ally": {"def": "盟友、同盟國、夥伴、結盟、聯合、結盟的、聯合的、盟軍地 (盟友)", "ipa": "/ˈælaɪ/ (n.) /əˈlaɪ/ (v.)", "trans": "alliance, allied", "col": "close ally, strategic ally", "ex": "The two countries have been close allies for years.", "pos": "n./v./adj./adv."},
}