import json

# Level 5 Part 10: (Shed - Testify)
L5_PART10 = {
    "shed": {"def": "流出、散發、蛻皮、棚、小屋、擺脫、流淚、溢出、脫落", "ipa": "/ʃed/", "trans": "shedding", "col": "shed tears, garden shed", "ex": "The sun sheds light and heat.", "pos": "v./n."},
    "specimen": {"def": "樣本、標本、樣品", "ipa": "/ˈspesɪmən/", "trans": "specific", "col": "collect a specimen", "ex": "The scientists are examining the rock specimens.", "pos": "n."},
    "sturdy": {"def": "強壯的、結實的、堅定的", "ipa": "/ˈstɜːdi/", "trans": "sturdily", "col": "sturdy table, sturdy person", "ex": "He is a sturdy young man with a great future.", "pos": "adj."},
    "sheer": {"def": "純粹的、極薄的、陡峭的、急轉、偏離、完全地、陡峭地、透明薄織物", "ipa": "/ʃɪə/", "trans": "sheered", "col": "sheer luck, sheer cliff", "ex": "It was sheer luck that we won.", "pos": "adj./v./adv./n."},
    "spectacular": {"def": "壯觀的、引人入勝的、奇觀、壯麗的演出", "ipa": "/spekˈtækjələ/", "trans": "spectacle", "col": "spectacular view", "ex": "The fireworks display was spectacular.", "pos": "adj./n."},
    "submit": {"def": "提交、遞交、服從、屈服", "ipa": "/səbˈmɪt/", "trans": "submission", "col": "submit an application, submit to authority", "ex": "Please submit your report by Friday.", "pos": "v."},
    "social": {"def": "社會的、社交的、群居的、聯誼會、社交聚會、合群地", "ipa": "/ˈsəʊʃl/", "trans": "society, socialize", "col": "social media, social security, social skills", "ex": "Humans are social animals.", "pos": "adj./n./adv."},
    "viewer": {"def": "觀眾、觀察者、指示器", "ipa": "/ˈvjuːə/", "trans": "view (名詞/動詞/副詞)", "col": "TV viewer", "ex": "The show attracts millions of TV viewers.", "pos": "n."},
    "terrify": {"def": "使恐怖、驚嚇、恐嚇", "ipa": "/ˈterɪfaɪ/", "trans": "terrific, terrible", "col": "terrified of", "ex": "The loud noise terrified the children.", "pos": "v."},
    "trophy": {"def": "獎盃、戰利品、紀念碑", "ipa": "/ˈtrəʊfi/", "trans": "trophies", "col": "winning trophy", "ex": "The winning team was awarded a trophy.", "pos": "n."},
    "viewpoint": {"def": "觀點、看法、視角", "ipa": "/ˈvjuːpɔɪnt/", "trans": "view (名詞/動詞/副詞)", "col": "different viewpoint", "ex": "From a financial viewpoint, the project is a disaster.", "pos": "n."},
    "testify": {"def": "作證、證明、表明", "ipa": "/ˈtestɪfaɪ/", "trans": "testimony", "col": "testify against, testify to", "ex": "He agreed to testify against his former boss.", "pos": "v."},
    "cane": {"def": "手杖、藤條、莖、用藤條編、用杖擊、變弱", "ipa": "/keɪn/", "trans": "canes", "col": "sugar cane, walking cane", "ex": "The old man walks with a cane.", "pos": "n./v."},
    "cannibal": {"def": "食人者、同類相食的動物", "ipa": "/ˈkænɪbl/", "trans": "cannibalism", "col": "cannibal tribe", "ex": "The movie is about a cannibal tribe in the jungle.", "pos": "n."},
    "cannon": {"def": "大砲、火砲、機關砲、砲轟、開砲、突然撞擊", "ipa": "/ˈkænən/", "trans": "cannons", "col": "fire a cannon", "ex": "The castle was attacked with cannons.", "pos": "n./v."},
    "canny": {"def": "謹慎的、精明的、節儉的", "ipa": "/ˈkæni/", "trans": "cannily", "col": "canny investor", "ex": "He is a canny investor who knows when to sell.", "pos": "adj."},
    "canoe": {"def": "獨木舟、皮放、划獨木舟、用獨木舟運送", "ipa": "/kəˈnuː/", "trans": "canoeing, canoeist", "col": "paddling a canoe", "ex": "They went for a trip in a canoe.", "pos": "n./v."},
    "canon": {"def": "標準、準則、教規、正典", "ipa": "/ˈkænən/", "trans": "canonical", "col": "canon law", "ex": "He is an expert in canon law.", "pos": "n."},
    "canopy": {"def": "天篷、遮篷、蒼穹、用天篷遮蓋、覆蓋", "ipa": "/ˈkænəpi/", "trans": "canopies", "col": "forest canopy", "ex": "The trees formed a thick canopy over the path.", "pos": "n./v."},
    "cant": {"def": "偽善的話、行話、斜面、傾斜、傾斜、講偽善的話、流浪者的", "ipa": "/kænt/", "trans": "canted", "col": "political cant", "ex": "His speech was full of political cant.", "pos": "n./v./adj."},
    "canter": {"def": "慢跑、輕捷的步伐、慢跑、使慢跑", "ipa": "/ˈkantə/", "trans": "cantering", "col": "at a canter", "ex": "The horse broke into a slow canter.", "pos": "n./v."},
    "canvas": {"def": "帆布、油畫、油畫布、用帆布覆蓋、強韌的", "ipa": "/ˈkænvəs/", "trans": "canvases", "col": "oil canvas", "ex": "The tent is made of heavy canvas.", "pos": "n./adj."},
    "canvass": {"def": "遊說、拉票、調查、討論", "ipa": "/ˈkænvəs/", "trans": "canvasser", "col": "canvass for votes", "ex": "They are canvassing for the election.", "pos": "v./n."},
    "canyon": {"def": "峽谷", "ipa": "/ˈkænjən/", "trans": "canyons", "col": "Grand Canyon", "ex": "The Grand Canyon is one of the natural wonders of the world.", "pos": "n."},
    "capability": {"def": "能力、才幹、潛力", "ipa": "/ˌkeɪpəˈbɪləti/", "trans": "capable, capably", "col": "beyond one's capability", "ex": "The task is beyond his capability.", "pos": "n."},
    "capable": {"def": "有能力的、能幹的、可以...的", "ipa": "/ˈkeɪpəbl/", "trans": "capability (名詞), capably", "col": "capable of", "ex": "She is capable of doing much better.", "pos": "adj."},
    "capably": {"def": "能幹地、熟練地", "ipa": "/ˈkeɪpəbli/", "trans": "capable (形容詞), capability", "col": "perform capably", "ex": "She performed her duties capably.", "pos": "adv."},
    "capacity": {"def": "容量、能力、身分、地位、極限的", "ipa": "/kəˈpæsəti/", "trans": "capacitate", "col": "full capacity, storage capacity", "ex": "The stadium was filled to its full capacity.", "pos": "n./adj."},
    "cape": {"def": "披肩、斗篷、海角、岬", "ipa": "/keɪp/", "trans": "capes", "col": "Cape of Good Hope", "ex": "The lighthouse stands on the edge of the cape.", "pos": "n."},
    "capital": {"def": "首都、資本、大寫字母、首要的、大寫的、極好的、資本、大寫地", "ipa": "/ˈkæpɪtl/", "trans": "capitalism, capitalize", "col": "capital city, capital punishment, venture capital", "ex": "Taipei is the capital of Taiwan.", "pos": "n./adj./adv."},
    "capitalism": {"def": "資本主義", "ipa": "/ˈkæpɪtəlɪzəm/", "trans": "capitalist", "col": "global capitalism", "ex": "Capitalism is the dominant economic system in the world today.", "pos": "n."},
    "capitalist": {"def": "資本家、資本主義者、資本主義的", "ipa": "/ˈkæpɪtəlɪst/", "trans": "capitalism (名詞)", "col": "capitalist system", "ex": "He is a wealthy capitalist.", "pos": "n./adj."},
    "capitalize": {"def": "使資本化、利用、用大寫字母寫", "ipa": "/ˈkæpɪtəlaɪz/", "trans": "capitalization", "col": "capitalize on an opportunity", "ex": "We should capitalize on this golden opportunity.", "pos": "v."},
    "capitulate": {"def": "投降、屈服", "ipa": "/kəˈpɪtʃuleɪt/", "trans": "capitulation", "col": "capitulate to demands", "ex": "The government refused to capitulate to the demands of the rebels.", "pos": "v."},
    "caprice": {"def": "反覆無常、任性、幻想曲", "ipa": "/kəˈpriːs/", "trans": "capricious", "col": "childish caprice", "ex": "Her decision was based on mere caprice.", "pos": "n."},
    "capricious": {"def": "反覆無常的、任性的、多變的", "ipa": "/kəˈprɪʃəs/", "trans": "caprice (名詞), capriciously", "col": "capricious weather", "ex": "The weather in this area is very capricious.", "pos": "adj."},
    "capsule": {"def": "膠囊、太空艙、小容器、概括的、縮影的、簡縮、封入膠囊", "ipa": "/ˈkæpsjuːl/", "trans": "capsules", "col": "space capsule, time capsule", "ex": "The astronaut returned to Earth in a space capsule.", "pos": "n./adj./v."},
    "captain": {"def": "隊長、船長、上尉、領袖、率領、指揮、隊長的", "ipa": "/ˈkæptɪn/", "trans": "captains", "col": "ship captain, team captain", "ex": "He is the captain of the football team.", "pos": "n./v./adj."},
    "caption": {"def": "標題、說明、字幕、(法律)逮捕、給...加標題、加說明", "ipa": "/ˈkæpʃn/", "trans": "captions", "col": "photo caption", "ex": "The photo had a funny caption.", "pos": "n./v."},
    "captivate": {"def": "迷住、惑、使著迷", "ipa": "/ˈkæptɪveɪt/", "trans": "captivating", "col": "captivate the audience", "ex": "Her performance captivated the entire audience.", "pos": "v."},
    "captive": {"def": "俘虜、獵物、著迷的人、被俘的、著迷的、受控制的", "ipa": "/ˈkæptɪv/", "trans": "captivity, captivate", "col": "hold captive", "ex": "The soldiers were held captive by the enemy.", "pos": "n./adj."},
    "captivity": {"def": "囚禁、束縛", "ipa": "/kæpˈtɪvəti/", "trans": "captive (名詞/形容詞), captivate", "col": "in captivity", "ex": "Wild animals should not be kept in captivity.", "pos": "n."},
    "capture": {"def": "捕獲、佔領、奪取、捕獲物、戰利品、捕捉、引起 (注意、興趣等)、紀錄", "ipa": "/ˈkæptʃə/", "trans": "capturing", "col": "capture the moment, data capture", "ex": "The police managed to capture the thief.", "pos": "n./v."},
    "car": {"def": "汽車、車廂、轎廂、乘坐汽車", "ipa": "/kɑː/", "trans": "cars", "col": "sports car, electric car, used car", "ex": "He bought a new electric car.", "pos": "n./v."},
    "carat": {"def": "克拉", "ipa": "/ˈkærət/", "trans": "carats", "col": "24-carat gold", "ex": "She is wearing a two-carat diamond ring.", "pos": "n."},
    "caravan": {"def": "商隊、旅行車、流動住宅、隨商隊旅行、住旅行車中", "ipa": "/ˈkærəvæn/", "trans": "caravans", "col": "camel caravan", "ex": "A camel caravan was crossing the desert.", "pos": "n./v."},
    "carbon": {"def": "碳、碳紙、複寫本、複寫的、碳發出的", "ipa": "/ˈkɑːbən/", "trans": "carbonic, carbonate", "col": "carbon dioxide, carbon footprint, carbon fiber", "ex": "Carbon dioxide is a greenhouse gas.", "pos": "n./adj."},
    "card": {"def": "卡片、紙牌、地圖、妙計、打牌、記於卡片、卡片狀的", "ipa": "/kɑːd/", "trans": "cards", "col": "credit card, identity card, greeting card", "ex": "He paid with a credit card.", "pos": "n./v./adj."},
    "cardboard": {"def": "硬紙板、瓦楞紙、硬紙板做的、不真實的", "ipa": "/ˈkɑːdbɔːd/", "trans": "boards", "col": "cardboard box", "ex": "The books are packed in a cardboard box.", "pos": "n./adj."},
    "cardinal": {"def": "樞機主教、紅雀、基數、主要的、深紅色的、優越得地", "ipa": "/ˈkːdɪnl/", "trans": "cardinality", "col": "cardinal sin, cardinal number", "ex": "Honesty is a cardinal virtue.", "pos": "n./adj./adv."},
    "care": {"def": "照顧、憂累、小心、保養、照顧、擔心、在意、介意、照顧地", "ipa": "/keə/", "trans": "careful, careless, caring", "col": "take care of, health care, intensive care", "ex": "She takes good care of her children.", "pos": "n./v./adv."},
    "career": {"def": "職業、生涯、歷程、速度、猛衝、職業的、事業的、猛衝、急速行進", "ipa": "/kəˈrɪə/", "trans": "careers", "col": "brilliant career, career path", "ex": "He has had a long and successful career in law.", "pos": "n./adj./v."},
    "carefree": {"def": "無憂無慮的、輕鬆愉快的", "ipa": "/ˈkeəfriː/", "trans": "care (名詞/動詞/副詞)", "col": "carefree lifestyle", "ex": "She enjoyed a carefree childhood.", "pos": "adj."},
    "careful": {"def": "小心的、仔細的、重視的", "ipa": "/ˈkeəfl/", "trans": "carefully, carefulness", "col": "be careful with", "ex": "Be careful with that knife; it's very sharp.", "pos": "adj."},
    "carefully": {"def": "小心地、仔細地、重視地", "ipa": "/ˈkeəfəli/", "trans": "careful (形容詞), carefulness", "col": "handle carefully", "ex": "Please handle the glass carefully.", "pos": "adv."},
    "careless": {"def": "粗心的、疏忽的、無憂無慮的", "ipa": "/ˈkeələs/", "trans": "carelessly, carelessness", "col": "careless mistake", "ex": "It was a careless mistake.", "pos": "adj."},
    "carelessly": {"def": "粗心地、漫不經心地、隨便地", "ipa": "/ˈkeələsli/", "trans": "careless (形容詞), carelessness", "col": "drive carelessly", "ex": "He drives carelessly and has already had several accidents.", "pos": "adv."},
    "carelessness": {"def": "粗心大意、疏忽、自然", "ipa": "/ˈkeələsnəs/", "trans": "careless (形容詞/副詞)", "col": "gross carelessness", "ex": "The accident was caused by gross carelessness.", "pos": "n."},
    "caress": {"def": "愛撫、親吻、撫摸、愛撫、撫摸、疼愛", "ipa": "/kəˈres/", "trans": "caresses", "col": "gentle caress", "ex": "She gave the child a gentle caress.", "pos": "n./v."},
    "caretaker": {"def": "守門人、管理員、看護、臨時代理的", "ipa": "/ˈkeəteɪkə/", "trans": "takes", "col": "building caretaker", "ex": "The building is looked after by a caretaker.", "pos": "n./adj."},
}

with open("batch_l5_p10.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART10, f, ensure_ascii=False, indent=2)
