import json

# Level 6 Part 19: (Baggage - Banal)
L6_PART19 = {
    "baggage": {"def": "行李、累贅、(軍)輜重、行李的人 (或物)、行李地 (行李)", "ipa": "/ˈbæɡɪdʒ/", "trans": "luggage", "col": "excess baggage, emotional baggage, baggage claim", "ex": "You can check your baggage at the counter.", "pos": "n./adj./adv."},
    "baggy": {"def": "袋狀的、寬鬆下垂的、寬大的", "ipa": "/ˈbæɡi/", "trans": "loose", "col": "baggy trousers", "ex": "He likes to wear baggy trousers.", "pos": "adj."},
    "bail": {"def": "保釋、保釋金、把手、桶、(體)橫桿、保釋的人 (或物)、保釋地 (保釋)", "ipa": "/beɪl/", "trans": "bails", "col": "out on bail, release on bail, bail someone out (保釋某人/解圍)", "ex": "He was released on bail of $50,000.", "pos": "n./v./adv."},
    "bailiff": {"def": "法警、執行官、監管員", "ipa": "/ˈbeɪlɪf/", "trans": "officer", "col": "court bailiff", "ex": "The court bailiff served the summons.", "pos": "n."},
    "bait": {"def": "餌、誘餌、誘惑物、引誘、折磨、誘餌的人物、誘餌地 (餌)", "ipa": "/beɪt/", "trans": "baits", "col": "fish bait, take the bait", "ex": "He used a worm as bait for the fish.", "pos": "n./v./adv."},
    "bake": {"def": "烘、烤、焙、烘烤食品、烘烤的人 (或物)、烘烤地 (烘)", "ipa": "/beɪk/", "trans": "baker, baking", "col": "bake a cake, baked potato, freshly baked", "ex": "The bread is freshly baked.", "pos": "v./n./adv."},
    "baker": {"def": "麵包師、烘製者", "ipa": "/ˈbeɪkə/", "trans": "bake (動詞/名詞/副詞), baking", "col": "local baker, baker's dozen (13個)", "ex": "The local baker makes the best cakes.", "pos": "n."},
    "bakery": {"def": "麵包店、烘培場", "ipa": "/ˈbeɪkəri/", "trans": "bake (動詞/名詞/副詞), baking", "col": "village bakery", "ex": "She works in a village bakery.", "pos": "n."},
    "balance": {"def": "平衡、餘額、天平、使平衡、稱重量、平衡的、剩餘的、平衡地 (平衡)", "ipa": "/ˈbæləns/", "trans": "balancing", "col": "keep one's balance, bank balance, balance sheet", "ex": "She struggled to keep her balance on the ice.", "pos": "n./v./adj./adv."},
    "balanced": {"def": "平衡的、和諧的、安定的", "ipa": "/ˈbælənst/", "trans": "balance (動詞/名詞/形容詞/副詞)", "col": "balanced diet", "ex": "Eating a balanced diet is important for your health.", "pos": "adj."},
    "balcony": {"def": "陽台、樓座 (戲院)", "ipa": "/ˈbælkəni/", "trans": "balconies", "col": "private balcony, theatre balcony", "ex": "The apartment has a small private balcony.", "pos": "n."},
    "bald": {"def": "禿頭的、平淡的、露骨的、變禿、枯萎地 (禿)", "ipa": "/bɔːld/", "trans": "baldness", "col": "bald eagle, go bald", "ex": "He's going bald.", "pos": "adj./v./adv."},
    "balderdash": {"def": "胡言亂語、廢話", "ipa": "/ˈbɔːldədæʃ/", "trans": "nonsense", "col": "sheer balderdash", "ex": "What you are saying is sheer balderdash.", "pos": "n."},
    "balding": {"def": "變禿的", "ipa": "/ˈbɔːldɪŋ/", "trans": "bald (形容詞/動詞/副詞)", "col": "balding man", "ex": "The balding man wore a wig.", "pos": "adj."},
    "baldly": {"def": "露骨地、平淡地、禿地", "ipa": "/ˈbɔːldli/", "trans": "bald (形容詞/動詞/副詞)", "col": "stated baldly", "ex": "He stated the facts baldly.", "pos": "adv."},
    "baldness": {"def": "禿頭、露骨、平易", "ipa": "/ˈbɔːldnəs/", "trans": "bald (形容詞/動詞/副詞)", "col": "premature baldness", "ex": "He suffered from premature baldness.", "pos": "n."},
    "bale": {"def": "大包、大捆、災禍、痛苦、打包、打包的人物、打包地 (包)", "ipa": "/beɪl/", "trans": "bales", "col": "bale of hay, bale of cotton", "ex": "He carried a large bale of hay to the barn.", "pos": "n./v./adv."},
    "baleful": {"def": "有害的、惡意的、毀滅性的", "ipa": "/ˈbeɪlfl/", "trans": "evil", "col": "baleful influence, baleful look", "ex": "He gave her a baleful look.", "pos": "adj."},
    "balk/baulk": {"def": "阻礙、挫折、大木、畏縮、阻礙、阻礙的人物、阻礙地 (阻礙)", "ipa": "/bɔːk/", "trans": "balks", "col": "balk at (畏縮)", "ex": "He balked at the idea of working overtime.", "pos": "n./v./adv."},
    "ball": {"def": "球、舞會、蛋、成球狀、球狀的、圓形的、球狀地 (球)", "ipa": "/bɔːl/", "trans": "balls", "col": "football, masked ball, ball gown (舞會禮服)", "ex": "The boy kicked the ball into the goal.", "pos": "n./v./adj./adv."},
    "ballad": {"def": "歌謠、民謠、情歌", "ipa": "/ˈbæləd/", "trans": "ballads", "col": "folk ballad, slow ballad", "ex": "She sang a slow ballad.", "pos": "n."},
    "ballast": {"def": "壓艙物、(路)道碴、稳定性、裝壓艙物於", "ipa": "/ˈbæləst/", "trans": "weight", "col": "ships' ballast", "ex": "Water is often used as ballast in large ships.", "pos": "n./v."},
    "ballerina": {"def": "芭蕾舞女演員", "ipa": "/ˌbæləˈriːnə/", "trans": "dancer", "col": "prima ballerina", "ex": "She dreams of becoming a prima ballerina.", "pos": "n."},
    "ballet": {"def": "芭蕾舞、芭蕾舞團、舞劇", "ipa": "/ˈbæleɪ/", "trans": "ballets", "col": "classical ballet, modern ballet", "ex": "She has been studying classical ballet since she was five.", "pos": "n."},
    "ballistic": {"def": "彈道的、發狂的 (俚語)", "ipa": "/bəˈlɪstɪk/", "trans": "ballistics", "col": "ballistic missile, go ballistic (大發雷霆)", "ex": "He went ballistic when he heard the news.", "pos": "adj."},
    "ballistics": {"def": "彈道學", "ipa": "/bəˈlɪstɪks/", "trans": "ballistic", "col": "forensic ballistics", "ex": "Forensic ballistics help to solve crimes involving firearms.", "pos": "n."},
    "balloon": {"def": "氣球、輕便氣球、像氣球般膨脹、擴張、氣球般的、氣球地 (氣球)", "ipa": "/bəˈluːn/", "trans": "balloons", "col": "hot-air balloon, balloon flight", "ex": "The child let go of the balloon.", "pos": "n./v./adj./adv."},
    "ballot": {"def": "投票、選票、秘密投票、投票、投票的人物、投票地 (投票)", "ipa": "/ˈbælət/", "trans": "ballots", "col": "secret ballot, cast a ballot", "ex": "The election was held by secret ballot.", "pos": "n./v./adv."},
    "ballplayer": {"def": "球類運動員", "ipa": "/ˈbɔːlpleɪə/", "trans": "athlete", "col": "professional ballplayer", "ex": "He is a famous professional ballplayer.", "pos": "n."},
    "ballpoint": {"def": "原子筆 (單數)", "ipa": "/ˈbɔːlpɔɪnt/", "trans": "ballpoints (複數)", "col": "ballpoint pen", "ex": "Can I borrow your ballpoint pen?", "pos": "n."},
    "ballroom": {"def": "舞廳", "ipa": "/ˈbɔːlruːm/", "trans": "dance hall", "col": "grand ballroom", "ex": "The couple danced in the grand ballroom.", "pos": "n."},
    "balm": {"def": "香油、軟膏、慰藉、香膏、慰藉地 (慰藉)", "ipa": "/bɑːm/", "trans": "soothing", "col": "lip balm, healing balm", "ex": "The music was like a balm to her soul.", "pos": "n./adv."},
    "balmy": {"def": "芳香的、溫和的、芬芳的、(英俚)瘋狂的", "ipa": "/ˈbɑːmi/", "trans": "mild", "col": "balmy evening", "ex": "They enjoyed a walk on a balmy evening.", "pos": "adj."},
    "balsa": {"def": "輕木、輕型小船", "ipa": "/ˈbɔːlsə/", "trans": "wood", "col": "balsa wood", "ex": "Balsa wood is very lightweight and easy to carve.", "pos": "n."},
    "balsam": {"def": "香膏、止痛膏、鳳仙花", "ipa": "/ˈbɔːlsəm/", "trans": "balm", "col": "balsam of Peru", "ex": "They used balsam to soothe the wound.", "pos": "n."},
    "baluster": {"def": "欄杆柱、扶手", "ipa": "/ˈbæləstə/", "trans": "spindle", "col": "wooden baluster", "ex": "The staircase has beautifully carved wooden balusters.", "pos": "n."},
    "balustrade": {"def": "欄杆、扶手欄杆", "ipa": "/ˌbæləˈstreɪd/", "trans": "railing", "col": "stone balustrade", "ex": "The stone balustrade surrounds the terrace.", "pos": "n."},
    "bamboo": {"def": "竹、竹子、竹製的、竹製地 (竹)", "ipa": "/ˌbæmˈbuː/", "trans": "bamboos", "col": "bamboo forest, bamboo shoot (竹筍)", "ex": "The furniture is made of bamboo.", "pos": "n./adj./adv."},
    "bamboozle": {"def": "欺騙、迷惑、戲弄", "ipa": "/bæmˈbuːzl/", "trans": "hoax", "col": "bamboozle into", "ex": "He tried to bamboozle the tourists into buying fake watches.", "pos": "v."},
    "ban": {"def": "禁止、禁令、褫奪公權的人 (或物)、禁止地 (禁止)", "ipa": "/bæn/", "trans": "banned", "col": "total ban, smoking ban, ban on", "ex": "The government has imposed a ban on smoking in public places.", "pos": "n./v./adv."},
    "banal": {"def": "平庸的、陳腐的、老掉牙的", "ipa": "/bəˈnɑːl/", "trans": "banality", "col": "banal remark", "ex": "He made some banal remarks about the weather.", "pos": "adj."},
}