import json

# Level 6 Part 3: (Adulterate - Affirm)
L6_PART3 = {
    "adulterate": {"def": "摻假、通姦的、掺雜的、摻假的人 (或事)、摻假地、通姦地", "ipa": "/əˈdʌltəreɪt/", "trans": "adulteration", "col": "adulterate food", "ex": "The wine had been adulterated with water.", "pos": "v./adj./n./adv."},
    "adulteration": {"def": "摻假、通姦、劣質品", "ipa": "/əˌdʌltəˈreɪʃn/", "trans": "adulterate (動詞/形容詞/名詞/副詞)", "col": "food adulteration", "ex": "Food adulteration is a serious crime.", "pos": "n."},
    "adultery": {"def": "通姦、私通", "ipa": "/əˈdʌltəri/", "trans": "adulterer", "col": "commit adultery", "ex": "He was accused of committing adultery.", "pos": "n."},
    "adumbrate": {"def": "預示、畫輪廓、遮蔽", "ipa": "/ˈædəmbreɪt/", "trans": "adumbration", "col": "adumbrate the future", "ex": "The project was only adumbrated in the report.", "pos": "v."},
    "advance": {"def": "前進、增長、預付款、前進、提前、進步、پیش的、預先的、前進地、提前地 (前進)", "ipa": "/ədˈvɑːns/", "trans": "advanced, advancement", "col": "in advance, advance notice, scientific advance", "ex": "We need to plan in advance.", "pos": "n./v./adj./adv."},
    "advanced": {"def": "進階的、高級的、先進的、年老的", "ipa": "/ədˈvɑːnst/", "trans": "advance (名詞/動詞/形容詞/副詞), advancement", "col": "advanced technology, advanced study", "ex": "The course is for advanced students only.", "pos": "adj."},
    "advancement": {"def": "前進、進步、升職、預付款", "ipa": "/ədˈvɑːnsmənt/", "trans": "advance (名詞/動詞/形容詞/副詞), advanced", "col": "career advancement", "ex": "The job offers great opportunities for career advancement.", "pos": "n."},
    "advantage": {"def": "優勢、利益、便利、有利於、獲利、有利的、便利的、有利地 (優勢)", "ipa": "/ədˈvɑːntɪdʒ/", "trans": "advantageous, advantageously", "col": "take advantage of, distinct advantage", "ex": "He has a distinct advantage over his rivals.", "pos": "n./v./adj./adv."},
    "advantageous": {"def": "有利的、有益的、方便的", "ipa": "/ˌædvənˈteɪdʒəs/", "trans": "advantage (名詞/動詞/形容詞/副詞), advantageously", "col": "advantageous position", "ex": "The trade deal is advantageous to both countries.", "pos": "adj."},
    "advantageously": {"def": "有利地、有益地、方便地", "ipa": "/ˌædvənˈteɪdʒəsli/", "trans": "advantageous (形容詞), advantage", "col": "placed advantageously", "ex": "The building is placed advantageously on the hill.", "pos": "adv."},
    "advent": {"def": "出現、到來、基督降臨節", "ipa": "/ˈædvent/", "trans": "arrival", "col": "advent of technology", "ex": "The advent of the internet changed the world.", "pos": "n."},
    "adventitious": {"def": "偶然的、外來的、(生)不定生的", "ipa": "/ˌædvenˈtɪʃəs/", "trans": "adventurously", "col": "adventitious profit", "ex": "The discovery was purely adventitious.", "pos": "adj."},
    "adventure": {"def": "冒險、奇遇、冒險活動、大膽參與、冒險、冒險家的、有冒險精神的", "ipa": "/ədˈventʃə/", "trans": "adventurous, adventurer", "col": "sense of adventure, adventure story", "ex": "Travelling alone in Africa was a real adventure.", "pos": "n./v./adj."},
    "adventurer": {"def": "冒險家、投機者", "ipa": "/ədˈventʃərə/", "trans": "adventure (名詞/動詞/形容詞), adventurous", "col": "great adventurer", "ex": "He is a great adventurer who has climbed many mountains.", "pos": "n."},
    "adventurous": {"def": "愛冒險的、充滿危險的、大膽的", "ipa": "/ədˈventʃərəs/", "trans": "adventure (名詞/動詞/形容詞), adventurer", "col": "adventurous spirit", "ex": "She has an adventurous spirit and loves to travel.", "pos": "adj."},
    "adverb": {"def": "副詞、副詞的", "ipa": "/ˈædvɜːb/", "trans": "adverbial", "col": "manner adverb", "ex": "The word 'quickly' is an adverb.", "pos": "n./adj."},
    "adversary": {"def": "對手、敵手、敵人的、對手的", "ipa": "/ˈædvəsəri/", "trans": "adversarial", "col": "worthy adversary", "ex": "He is a worthy adversary on the tennis court.", "pos": "n./adj."},
    "adverse": {"def": "不利的、相反的、敵對的、有害地 (不利)", "ipa": "/ˈædvɜːs/", "trans": "adversity, adversely", "col": "adverse weather, adverse conditions", "ex": "The flight was cancelled due to adverse weather conditions.", "pos": "adj./adv."},
    "adversely": {"def": "不利地、相反地、敵對地", "ipa": "/ˈædvɜːsli/", "trans": "adverse (形容詞/副詞), adversity", "col": "adversely affected", "ex": "The stock market was adversely affected by the news.", "pos": "adv."},
    "adversity": {"def": "逆境、不幸、災難", "ipa": "/ədˈvɜːsəti/", "trans": "adverse (形容詞/副詞), adversely", "col": "face adversity", "ex": "He showed great courage in the face of adversity.", "pos": "n."},
    "advertise": {"def": "登廣告、宣傳、公佈", "ipa": "/ˈædvətaɪz/", "trans": "advertisement, advertiser", "col": "advertise a job", "ex": "They are advertising a job in the local paper.", "pos": "v."},
    "advertisement/advert/ad": {"def": "廣告、公告、宣傳", "ipa": "/ədˈvɜːtɪsmənt/", "trans": "advertise (動詞), advertiser", "col": "job advertisement, classified ad", "ex": "I saw an advertisement for a new car.", "pos": "n."},
    "advertiser": {"def": "刊登廣告者、廣告商", "ipa": "/ˈædvətaɪzə/", "trans": "advertise (動詞), advertisement", "col": "main advertiser", "ex": "The magazine's main advertisers are car companies.", "pos": "n."},
    "advertising": {"def": "廣告業、廣告、廣告的", "ipa": "/ˈædvətaɪzɪŋ/", "trans": "advertise (動詞), advertisement", "col": "advertising agency", "ex": "She works for a large advertising agency.", "pos": "n./adj."},
    "advice": {"def": "建議、忠告、通知、引導的人 (或事)、建議地 (建議)", "ipa": "/ədˈvaɪs/", "trans": "advise, advisor", "col": "take advice, medical advice, piece of advice", "ex": "Thank you for your advice.", "pos": "n./adv."},
    "advisable": {"def": "明智的、可取的、適當的", "ipa": "/ədˈvaɪzəbl/", "trans": "advice (名詞/副詞), advise", "col": "it is advisable to", "ex": "It is advisable to book in advance.", "pos": "adj."},
    "advise": {"def": "建議、忠告、通知、顧問地 (建議)", "ipa": "/ədˈvaɪz/", "trans": "advice (名詞/副詞), advisor", "col": "advise against, highly advised", "ex": "The doctor advised him to stop smoking.", "pos": "v./adv."},
    "advised": {"def": "深思熟慮的、明智的、受建議的", "ipa": "/ədˈvaɪzd/", "trans": "advise (動詞/副詞), advice", "col": "well-advised", "ex": "You would be well-advised to follow my advice.", "pos": "adj."},
    "adviser/advisor": {"def": "顧問、勸告者、導師", "ipa": "/ədˈvaɪzə/", "trans": "advice (名詞/副詞), advise", "col": "financial adviser", "ex": "He is a financial adviser to a large corporation.", "pos": "n."},
    "advisory": {"def": "諮詢的、顧問的、警告、公告、顧問的、警告地", "ipa": "/ədˈvaɪzəri/", "trans": "advisor", "col": "weather advisory", "ex": "The government issued a travel advisory for the region.", "pos": "adj./n."},
    "advocacy": {"def": "擁護、主張、法律代裡", "ipa": "/ˈædvəkəsi/", "trans": "advocate", "col": "public advocacy", "ex": "The group is known for its advocacy of human rights.", "pos": "n."},
    "advocate": {"def": "擁護者、提倡者、辯護律師、擁護、提倡、辯護、提倡的、擁護的 (提倡)", "ipa": "/ˈædvəkət/ (n.) /ˈædvəkeɪt/ (v.)", "trans": "advocacy", "col": "advocate for change", "ex": "She is a strong advocate for animal rights.", "pos": "n./v./adj."},
    "aerial": {"def": "天線、空氣的、高空的、航空的、天線的、空中的地 (高空)", "ipa": "/ˈeəriəl/", "trans": "air", "col": "aerial view, aerial photography", "ex": "The pilot provided an aerial view of the region.", "pos": "n./adj./adv."},
    "aerobic": {"def": "需氧的、有氧的、(生)需氧生物、(化)需氧的、有氧地 (有氧)", "ipa": "/eəˈrəʊbɪk/", "trans": "aerobics", "col": "aerobic exercise", "ex": "Swimming is a great aerobic exercise.", "pos": "adj./n./adv."},
    "aerobics": {"def": "有氧運動、有氧健身法", "ipa": "/eəˈrəʊbɪks/", "trans": "aerobic (形容詞/名詞/副詞)", "col": "do aerobics", "ex": "She goes to the gym to do aerobics twice a week.", "pos": "n."},
    "aero-dynamics": {"def": "空氣動力學", "ipa": "/ˌeərəʊdaɪˈnæmɪks/", "trans": "dynamic", "col": "laws of aerodynamics", "ex": "The design of the car is based on the laws of aerodynamics.", "pos": "n."},
    "aeronautic/aeronautical": {"def": "航空的、飛行術的、航空學的", "ipa": "/ˌeərəˈnɔːtɪk/", "trans": "aeronautics", "col": "aeronautical engineering", "ex": "He is studying aeronautical engineering.", "pos": "adj."},
    "aeronautics": {"def": "航空學、飛行術", "ipa": "/ˌeərəˈnɔːtɪks/", "trans": "aeronautic", "col": "advance in aeronautics", "ex": "Aeronautics is the science of flight.", "pos": "n."},
    "aeroplane/airplane": {"def": "飛機、用飛機運送、飛機的", "ipa": "/ˈeərəpleɪn/", "trans": "plane", "col": "military aeroplane", "ex": "The aeroplane landed safely on the runway.", "pos": "n./v./adj."},
    "aerosol": {"def": "噴霧劑、氣溶膠、煙霧劑、噴霧的、(化)氣膠的", "ipa": "/ˈeərəsɒl/", "trans": "spray", "col": "aerosol spray", "ex": "The paint comes in an aerosol spray can.", "pos": "n./adj."},
    "aerospace": {"def": "航空航天、宇宙空間、航太業、航太的", "ipa": "/ˈeərəʊspeɪs/", "trans": "space", "col": "aerospace industry", "ex": "The company is a leader in the aerospace industry.", "pos": "n./adj."},
    "aesthetic": {"def": "美學的、有審美感的、審美的、美學、審美觀、審美地 (審美)", "ipa": "/iːsˈθetɪk/", "trans": "aesthetically, aesthetics", "col": "aesthetic value, purely aesthetic", "ex": "The building has great aesthetic value.", "pos": "adj./n./adv."},
    "aesthetically": {"def": "審美地、美學地、有審美感地", "ipa": "/iːsˈθetɪkli/", "trans": "aesthetic (形容詞/名詞/副詞), aesthetics", "col": "aesthetically pleasing", "ex": "The garden is aesthetically pleasing.", "pos": "adv."},
    "aesthetics": {"def": "美學、審美觀、美", "ipa": "/iːsˈθetɪks/", "trans": "aesthetic (形容詞/名詞/副詞), aesthetically", "col": "modern aesthetics", "ex": "Modern aesthetics emphasizes simplicity.", "pos": "n."},
    "affability": {"def": "和藹、親切、和藹可親", "ipa": "/ˌæfəˈbɪləti/", "trans": "affable", "col": "natural affability", "ex": "His natural affability made him very popular.", "pos": "n."},
    "affable": {"def": "和藹可親的、友善的、殷勤的", "ipa": "/ˈæfəbl/", "trans": "affability (名詞)", "col": "affable manner", "ex": "He has a very affable manner.", "pos": "adj."},
    "affably": {"def": "和藹地、親切地、友善地", "ipa": "/ˈæfəbli/", "trans": "affable (形容詞), affability", "col": "greet affably", "ex": "She greeted us affably at the door.", "pos": "adv."},
    "affair": {"def": "事務、私事、風流韻事、事件", "ipa": "/əˈfeə/", "trans": "affairs", "col": "current affairs, love affair, state affair", "ex": "The government is handling the affair with great care.", "pos": "n."},
    "affect": {"def": "影響、感動、假裝、(醫)侵襲、感情、情感、影響地、感染地 (影響)", "ipa": "/əˈfekt/", "trans": "affection, affected", "col": "affect the outcome, deeply affected", "ex": "The weather will affect the outcome of the race.", "pos": "v./n./adv."},
    "affectation": {"def": "做作、假裝、矯揉造作", "ipa": "/ˌæfekˈteɪʃn/", "trans": "affect, affected", "col": "without affectation", "ex": "She spoke with a slight affectation.", "pos": "n."},
    "affected": {"def": "做作的、假裝的、受影響的、(醫)受感染的", "ipa": "/əˈfektɪd/", "trans": "affect (動詞/名詞/副詞), affectation", "col": "affected manner", "ex": "He spoke in a very affected manner.", "pos": "adj."},
    "affection": {"def": "慈愛、喜愛、感情、(醫)影響、(心)情操", "ipa": "/əˈfekʃn/", "trans": "affectionate, affectionately", "col": "deep affection, direct affection", "ex": "She has a deep affection for her parents.", "pos": "n."},
    "affectionate": {"def": "充滿深情的、溫柔親切的、喜愛的", "ipa": "/əˈfekʃənət/", "trans": "affection (名詞), affectionately", "col": "affectionate letter", "ex": "He wrote her an affectionate letter.", "pos": "adj."},
    "affectionately": {"def": "滿懷深情地、溫柔親切地、喜愛地", "ipa": "/əˈfekʃənətli/", "trans": "affectionate (形容詞), affection", "col": "called affectionately", "ex": "He is called 'Uncle' affectionately by the neighborhood children.", "pos": "adv."},
    "affidavit": {"def": "宣誓書", "ipa": "/ˌæfəˈdeɪvɪt/", "trans": "sworn statement", "col": "signed affidavit", "ex": "He submitted a signed affidavit to the court.", "pos": "n."},
    "affiliate": {"def": "使隸屬、接納...為成員、交往、隸屬機關、分會、附生的、屬下的、隸屬地 (隸屬)", "ipa": "/əˈfɪlieɪt/", "trans": "affiliation", "col": "affiliated company, local affiliate", "ex": "The college is affiliated with the university.", "pos": "v./n./adj./adv."},
    "affiliation": {"def": "隸屬關係、入會、聯繫", "ipa": "/əˌfɪliˈeɪʃn/", "trans": "affiliate (動詞/名詞/形容詞/副詞)", "col": "political affiliation", "ex": "What is your political affiliation?", "pos": "n."},
    "affinity": {"def": "吸引力、親密關係、類同、(化)親和力", "ipa": "/əˈfɪnəti/", "trans": "affinities", "col": "natural affinity", "ex": "She has a natural affinity for languages.", "pos": "n."},
    "affirm": {"def": "斷言、申明、證實、確認", "ipa": "/əˈfɜːm/", "trans": "affirmation, affirmative", "col": "affirm beliefs", "ex": "The court affirmed the lower court's decision.", "pos": "v."},
    "affirmation": {"def": "肯定、斷言、證實、批准", "ipa": "/ˌæfəˈmeɪʃn/", "trans": "affirm (動詞), affirmative", "col": "solemn affirmation", "ex": "The witness made a solemn affirmation to tell the truth.", "pos": "n."},
    "affirmative": {"def": "肯定的、同意的、積極的、肯定語、贊成、肯守地、積極地 (肯定)", "ipa": "/əˈfɜːmətɪv/", "trans": "affirmation, affirm", "col": "affirmative answer, affirmative action", "ex": "He gave an affirmative answer to the question.", "pos": "adj./n./adv."},
}