import json

# Level 6 Part 20: (Banality - Barbecue)
L6_PART20 = {
    "banality": {"def": "平庸、陳腐、老掉牙的事", "ipa": "/bəˈnæləti/", "trans": "banal (形容詞)", "col": "sheer banality", "ex": "The banality of modern pop music is shocking.", "pos": "n."},
    "banana": {"def": "香蕉、香蕉的人 (或物)、瘋狂的 (俚語)、瘋狂地 (香蕉)", "ipa": "/bəˈnɑːnə/", "trans": "bananas", "col": "banana peel, go bananas (發瘋), top banana (大老闆)", "ex": "I like to have a banana for breakfast.", "pos": "n./adj./adv."},
    "band": {"def": "樂隊、帶子、繩、人群、用帶子縛、使結合、帶狀的、一夥地 (帶)", "ipa": "/bænd/", "trans": "bands", "col": "wedding band, rubber band, marching band, rock band", "ex": "The band played for three hours.", "pos": "n./v./adj./adv."},
    "bandage": {"def": "繃帶、包紮、用繃帶紮、包紮的人物、包紮地 (繃帶)", "ipa": "/ˈbændɪdʒ/", "trans": "bandages", "col": "apply a bandage, elastic bandage", "ex": "He wrapped a bandage around his injured leg.", "pos": "n./v./adv."},
    "bandanna/bandana": {"def": "多彩大染織手帕、圍巾", "ipa": "/bænˈdænə/", "trans": "handkerchief", "col": "red bandanna", "ex": "He wore a red bandanna around his neck.", "pos": "n."},
    "bandit": {"def": "土匪、強盜、歹徒 (單數)", "ipa": "/ˈbændɪt/", "trans": "bandits (複數)", "col": "armed bandit, one-armed bandit (吃角子老虎機)", "ex": "The traveler was attacked by a bandit.", "pos": "n."},
    "banditry": {"def": "土匪行為、強盜活動", "ipa": "/ˈbændɪtri/", "trans": "bandit", "col": "local banditry", "ex": "The area is known for local banditry.", "pos": "n."},
    "bandoleer/bandolier": {"def": "彈藥帶、肩帶", "ipa": "/ˌbændəˈlɪə/", "trans": "bullet belt", "col": "leather bandoleer", "ex": "The soldier wore a leather bandoleer across his chest.", "pos": "n."},
    "bandstand": {"def": "露天音樂臺", "ipa": "/ˈbændstænd/", "trans": "stage", "col": "park bandstand", "ex": "The band played on the park bandstand.", "pos": "n."},
    "bandwagon": {"def": "樂隊車、大篷車、潮流、浪潮的人 (或物)", "ipa": "/ˈbændwæɡən/", "trans": "trend", "col": "jump on the bandwagon (趕浪潮)", "ex": "Many people jumped on the bandwagon of the new technology.", "pos": "n./adv."},
    "bandy": {"def": "向外彎曲的、向兩側張開的、來回傳球、傳播、來回傳球的人 (或物)、向外彎曲地 (彎)", "ipa": "/ˈbændi/", "trans": "bandied", "col": "bandy legs, bandy words (爭辯)", "ex": "The rumor was bandied about the office.", "pos": "adj./v./n./adv."},
    "bane": {"def": "禍根、災禍、毒藥、毀滅 (單數)", "ipa": "/beɪn/", "trans": "curse", "col": "the bane of one's life", "ex": "Noise is the bane of my life.", "pos": "n."},
    "baneful": {"def": "有害的、致死的、邪惡的", "ipa": "/ˈbeɪnfl/", "trans": "harmful", "col": "baneful effect", "ex": "The baneful effect of smoking is well-known.", "pos": "adj."},
    "bang": {"def": "砰然巨響、砰地敲、猛撞、剪短頭髮、砰地、突然地 (砰)", "ipa": "/bæŋ/", "trans": "bangs", "col": "bang on, with a bang, bang one's head", "ex": "He closed the door with a loud bang.", "pos": "n./v./adv."},
    "bangle": {"def": "手鐲、腳鐲", "ipa": "/ˈbæŋɡl/", "trans": "bracelets", "col": "gold bangle", "ex": "She was wearing several gold bangles.", "pos": "n."},
    "banish": {"def": "驅逐、消除、排除、趕走的人 (或物)、趕走地 (趕走)", "ipa": "/ˈbænɪʃ/", "trans": "banishment", "col": "banish from, banish thoughts", "ex": "The king decided to banish the rebels.", "pos": "v./n./adv."},
    "banishment": {"def": "驅逐、流放、消除", "ipa": "/ˈbænɪʃmənt/", "trans": "banish (動詞/名詞/副詞)", "col": "political banishment", "ex": "He suffered a lot during his political banishment.", "pos": "n."},
    "banister/bannister": {"def": "欄杆、扶手", "ipa": "/ˈbænɪstə/", "trans": "balustrade", "col": "slide down the banister", "ex": "The child likes to slide down the banister.", "pos": "n."},
    "banjo": {"def": "五弦琴、班卓琴、五弦琴的人 (或物)", "ipa": "/ˈbændʒəʊ/", "trans": "banjos", "col": "play the banjo", "ex": "He played a tune on his banjo.", "pos": "n./adv."},
    "bank": {"def": "銀行、堤岸、庫、堆積、存入銀行、傾斜、銀行般的、在岸上地 (銀)", "ipa": "/bæŋk/", "trans": "banking, banker", "col": "river bank, data bank, commercial bank, bank on (依靠)", "ex": "She works in a local bank.", "pos": "n./v./adj./adv."},
    "bankbook": {"def": "銀行存摺", "ipa": "/ˈbæŋkbʊk/", "trans": "passbook", "col": "savings bankbook", "ex": "She checked her savings bankbook last night.", "pos": "n."},
    "banker": {"def": "銀行家、莊家", "ipa": "/ˈbæŋkə/", "trans": "bank (名詞/動詞/形容詞/副詞), banking", "col": "investment banker", "ex": "He is a wealthy investment banker.", "pos": "n."},
    "banking": {"def": "銀行業務、金融、銀行家的人 (或物) (銀行)", "ipa": "/ˈbæŋkɪŋ/", "trans": "bank (名詞/動詞/形容詞/副詞), banker", "col": "investment banking, personal banking", "ex": "He is pursuing a career in banking.", "pos": "n./adv."},
    "banknote/bank note": {"def": "鈔票、紙幣", "ipa": "/ˈbæŋknəʊt/", "trans": "bills", "col": "ten-dollar banknote", "ex": "He pulled a ten-dollar banknote out of his pocket.", "pos": "n."},
    "bankrupt": {"def": "破產的、缺乏的、破產者、使破產、破產地 (破產)", "ipa": "/ˈbæŋkrʌpt/", "trans": "bankruptcy", "col": "go bankrupt, morally bankrupt", "ex": "The company went bankrupt last year.", "pos": "adj./n./v./adv."},
    "bankruptcy": {"def": "破產、倒閉、徹底失敗", "ipa": "/ˈbæŋkrʌptsi/", "trans": "bankrupt (形容詞/名詞/動詞/副詞)", "col": "file for bankruptcy", "ex": "They were forced to file for bankruptcy.", "pos": "n."},
    "banner": {"def": "橫幅、旗幟、大標題、巨大的、卓越的、卓越地 (旗)", "ipa": "/ˈbænə/", "trans": "banners", "col": "banner year, star-spangled banner, banner headline", "ex": "They carried a large banner during the protest.", "pos": "n./adj./adv."},
    "bannock": {"def": "(蘇)燕麥餅、烤餅", "ipa": "/ˈbænək/", "trans": "oatcake", "col": "traditional bannock", "ex": "She made some traditional bannock for breakfast.", "pos": "n."},
    "banns": {"def": "(教會)結婚公告 (複數)", "ipa": "/bænz/", "trans": "marriage notice", "col": "publish the banns", "ex": "The banns were published in the church for three weeks.", "pos": "n."},
    "banquet": {"def": "宴會、盛宴、款待、參加宴會、宴會地 (宴)", "ipa": "/ˈbæŋkwɪt/", "trans": "banquets", "col": "state banquet, wedding banquet", "ex": "They held a grand banquet to celebrate their anniversary.", "pos": "n./v./adv."},
    "banquette": {"def": "靠牆長凳、(窗)臺台、(堡)夾道", "ipa": "/bæŋˈket/", "trans": "bench", "col": "leather banquette", "ex": "We sat on a leather banquette in the restaurant.", "pos": "n."},
    "banshee": {"def": "(愛爾蘭/蘇格蘭民俗)女妖、報喪女妖", "ipa": "/ˈbænʃiː/", "trans": "fairy", "col": "wail like a banshee", "ex": "She was wailing like a banshee.", "pos": "n."},
    "bantam": {"def": "矮腳雞、小而好鬥的人、矮小的", "ipa": "/ˈbæntəm/", "trans": "small", "col": "bantam weight (雛量級)", "ex": "He fought in the bantam weight category.", "pos": "n./adj."},
    "banter": {"def": "開玩笑、打趣、戲弄、戲劇地 (玩笑)", "ipa": "/ˈbæntə/", "trans": "bantering", "col": "lighthearted banter", "ex": "They exchanged some lighthearted banter in the morning.", "pos": "n./v./adv."},
    "bantering": {"def": "打趣的、戲弄的", "ipa": "/ˈbæntərɪŋ/", "trans": "banter (名詞/動詞/副詞)", "col": "bantering tone", "ex": "She spoke in a friendly and bantering tone.", "pos": "adj."},
    "banyan": {"def": "榕樹、孟加拉商人", "ipa": "/ˈbænjən/", "trans": "fig tree", "col": "sacred banyan", "ex": "The ancient banyan tree provided a lot of shade.", "pos": "n."},
    "baptism": {"def": "洗禮、施洗、嚴峻考驗、正式命名、洗禮地 (洗禮)", "ipa": "/ˈbæptɪzəm/", "trans": "christening", "col": "baptism of fire (火的洗禮/初陣), infant baptism", "ex": "The baby was given a baptism at the local church.", "pos": "n./adv."},
    "baptismal": {"def": "洗禮的", "ipa": "/bæpˈtɪzməl/", "trans": "baptism", "col": "baptismal font", "ex": "The priest poured holy water into the baptismal font.", "pos": "adj."},
    "baptize": {"def": "施洗、接受洗禮、命名", "ipa": "/bæpˈtaɪz/", "trans": "baptism", "col": "baptize a child", "ex": "The baby was baptized yesterday.", "pos": "v."},
    "bar": {"def": "酒吧、條、欄、障礙、阻礙、律師界、除外、阻礙、嚴禁、除了、障礙地 (條)", "ipa": "/bɑː/", "trans": "barred", "col": "snack bar, bar code, chocolate bar, behind bars (坐牢), bar graph", "ex": "He went to the bar for a drink.", "pos": "n./prep./v./adv."},
    "barb": {"def": "倒鉤、刺、冷嘲熱諷、裝倒鉤於、尖銳的人、刺人地 (刺)", "ipa": "/bɑːb/", "trans": "barbed", "col": "barbed wire", "ex": "The barb on the hook caught the fish.", "pos": "n./v./adv."},
    "barbarian": {"def": "野蠻人、粗魯的人、野蠻的、粗魯的、野蠻的人 (或物)、野蠻地 (野蠻)", "ipa": "/bɑːˈbeəriən/", "trans": "savage", "col": "barbarian invasion", "ex": "The ancient city was attacked by barbarians.", "pos": "n./adj./adv."},
    "barbaric": {"def": "野蠻的、殘暴的、粗俗的", "ipa": "/bɑːˈbærɪk/", "trans": "barbarian (名詞/形容詞/副詞), barbarous", "col": "barbaric custom", "ex": "They still practice some barbaric customs.", "pos": "adj."},
    "barbarism": {"def": "野蠻狀態、殘暴、粗魯、不規範語", "ipa": "/ˈbɑːbərɪzəm/", "trans": "barbarian (名詞/形容詞/副詞), barbaric", "col": "descent into barbarism", "ex": "The country is quickly descending into barbarism.", "pos": "n."},
    "barbarity": {"def": "殘忍、暴行、野蠻、粗俗", "ipa": "/bɑːˈbærəti/", "trans": "cruelty", "col": "sheer barbarity", "ex": "They were shocked by the sheer barbarity of the crimes.", "pos": "n."},
    "barbarous": {"def": "野蠻的、殘酷的、粗魯的", "ipa": "/ˈbɑːbərəs/", "trans": "barbaric, barbarian", "col": "barbarous treatment", "ex": "The prisoners were subjected to barbarous treatment.", "pos": "adj."},
    "barbecue": {"def": "烤肉、烤肉架、戶外烤肉會、燒烤、燒烤的人 (或物)、燒烤地 (烤肉)", "ipa": "/ˈbɑːbɪkjuː/", "trans": "barbecued", "col": "outdoor barbecue, barbecue sauce", "ex": "We are having a barbecue in our backyard tomorrow.", "pos": "n./v./adv."},
}