import json

# Level 6 Part 25: (Beaching - Beat)
L6_PART25 = {
    "beaching": {"def": "使船上岸、擱淺、擱淺的人 (或物) (灘)", "ipa": "/ˈbiːtʃɪŋ/", "trans": "beach (名詞/動詞/副詞)", "col": "mass beaching (集體擱淺)", "ex": "Scientists are investigating the mass beaching of whales.", "pos": "n./adv."},
    "beacon": {"def": "燈塔、信號浮標、指引、燈塔的人物、指引地 (指引)", "ipa": "/ˈbiːkən/", "trans": "beacons", "col": "beacon of hope, laser beacon", "ex": "The lighthouse served as a beacon for the ships.", "pos": "n./v./adv."},
    "bead": {"def": "珠子、滴、水珠、使成珠狀、裝珠子於、珠子地 (珠)", "ipa": "/biːd/", "trans": "beads", "col": "beads of sweat, string of beads, prayer beads", "ex": "Beads of sweat rolled down his forehead.", "pos": "n./v./adv."},
    "beadle": {"def": "(英)教堂執行吏、小吏 (單數)", "ipa": "/ˈbiːdl/", "trans": "beadles (複數)", "col": "parish beadle", "ex": "The parish beadle maintained order during the service.", "pos": "n."},
    "beading": {"def": "珠狀飾、(木)木條飾、裝飾的人 (或物) (珠)", "ipa": "/ˈbiːdɪŋ/", "trans": "bead (名詞/動詞/副詞)", "col": "decorative beading", "ex": "The dress was adorned with intricate beading.", "pos": "n./adv."},
    "beadwork": {"def": "珠飾品、珠工", "ipa": "/ˈbiːdwɜːk/", "trans": "beadworkings", "col": "native beadwork", "ex": "The museum exhibits some fine native beadwork.", "pos": "n."},
    "beady": {"def": "(眼睛)小而亮的、像珠子般的", "ipa": "/ˈbiːdi/", "trans": "bead", "col": "beady eyes", "ex": "The bird watched me with its beady black eyes.", "pos": "adj."},
    "beagle": {"def": "獵兔犬、比格犬 (單數)", "ipa": "/ˈbiːɡl/", "trans": "beagles (複數)", "col": "loyal beagle", "ex": "He takes his loyal beagle for a walk every morning.", "pos": "n."},
    "beak": {"def": "鳥嘴、喙、(英俚)法官、(俚)鼻子 (單數)", "ipa": "/biːk/", "trans": "beaks (複數)", "col": "hooked beak", "ex": "The eagle has a sharp, hooked beak.", "pos": "n."},
    "beaked": {"def": "有喙的、喙狀的", "ipa": "/biːkt/", "trans": "beak (名詞)", "col": "beaked whale", "ex": "Many types of beaked whales live in these waters.", "pos": "adj."},
    "beaker": {"def": "燒杯、大口杯、大口杯之量 (單數)", "ipa": "/ˈbiːkə/", "trans": "beakers (複數)", "col": "laboratory beaker", "ex": "The chemist poured the liquid into a laboratory beaker.", "pos": "n."},
    "beam": {"def": "光束、橫樑、容光煥發、發射、發光、光束地 (束)", "ipa": "/biːm/", "trans": "beams", "col": "laser beam, balance beam, moon beam, beam with joy", "ex": "A beam of light shone through the window.", "pos": "n./v./adv."},
    "beaming": {"def": "喜氣洋洋的、發光的、滿面笑容地", "ipa": "/ˈbiːmɪŋ/", "trans": "beam (名詞/動詞/副詞)", "col": "beaming smile", "ex": "She has a beaming smile on her face.", "pos": "adj./adv."},
    "bean": {"def": "豆、豆莢、(俚)頭、(俚)毫無價值的人 (或物)、豆狀的、像豆子的、豆狀地 (豆)", "ipa": "/biːn/", "trans": "beans", "col": "soy bean, coffee bean, green bean, (俚) know how many beans make five", "ex": "He grows soy beans on his farm.", "pos": "n./adj./v./adv."},
    "bear": {"def": "熊、空頭、負擔、忍受、生育、帶有、負擔的人物、負擔地 (負)", "ipa": "/beə/", "trans": "bearing, born, borne", "col": "polar bear, teddy bear, bear in mind (記住), bear market (空頭市場)", "ex": "She can't bear the thought of losing him.", "pos": "n./v./adv."},
    "bearable": {"def": "可忍受的、能負擔的", "ipa": "/ˈbeərəbl/", "trans": "bear (名詞/動詞/副詞)", "col": "barely bearable", "ex": "The pain was barely bearable.", "pos": "adj."},
    "beard": {"def": "鬍鬚 (下巴)、山羊鬍、公開反對、長鬍子、鬍鬚的人 (或物)、鬍鬚地 (鬍)", "ipa": "/bɪəd/", "trans": "bearded", "col": "grow a beard, long white beard", "ex": "He has grown a thick beard.", "pos": "n./v./adv."},
    "bearded": {"def": "有鬍鬚的、有芒的", "ipa": "/ˈbɪədɪd/", "trans": "beard (名詞/動詞/副詞)", "col": "bearded dragon, bearded man", "ex": "He is a tall, bearded man.", "pos": "adj."},
    "beardless": {"def": "無鬍鬚的、幼稚的", "ipa": "/ˈbɪədləs/", "trans": "beard (名詞/動詞/副詞)", "col": "beardless youth", "ex": "He looked like a beardless youth.", "pos": "adj."},
    "bearer": {"def": "持票人、背負者、搬運者 (單數)", "ipa": "/ˈbeərə/", "trans": "bearers (複數)", "col": "pallbearer (抬棺人), torch bearer, bearer bond (不記名債券)", "ex": "He is the bearer of good news.", "pos": "n."},
    "bearing": {"def": "舉止、方位、關係、軸承、舉止的人物、舉止地 (舉止)", "ipa": "/ˈbeərəŋ/", "trans": "bear (名詞/動詞/副詞)", "col": "ball bearing, keep one's bearings, of no bearing on", "ex": "She has a very dignified bearing.", "pos": "n./adj./adv."},
    "bearish": {"def": "熊般的、粗魯的、(股)賣空的、看跌的", "ipa": "/ˈbeərɪʃ/", "trans": "bear", "col": "bearish market", "ex": "The stock market analysts are in a bearish mood.", "pos": "adj."},
    "beast": {"def": "野獸、畜牲、殘暴的人、獸性的、野獸般地 (獸)", "ipa": "/biːst/", "trans": "beasts", "col": "wild beast, beast of burden (馱獸)", "ex": "What a wild beast it is!", "pos": "n./adj./adv."},
    "beastliness": {"def": "獸性、殘忍、討厭", "ipa": "/ˈbiːstlinəs/", "trans": "beastly", "col": "sheer beastliness", "ex": "He was shocked by the sheer beastliness of the crime.", "pos": "n."},
    "beastly": {"def": "野獸般的、殘忍的、(口)極討厭的、極其地、非常", "ipa": "/ˈbiːstli/", "trans": "beast (名詞/形容詞/副詞)", "col": "beastly weather", "ex": "It's a beastly cold day.", "pos": "adj./adv."},
    "beat": {"def": "打擊、戰勝、跳動、節拍、攪拌、敲擊的人物、打擊地 (打)", "ipa": "/biːt/", "trans": "beating, beaten", "col": "beat the record, heartbeat, dead beat (筋疲力竭), beat around the bush (繞圈子)", "ex": "My heart was beating fast.", "pos": "v./n./adv."},
}