import json

# Level 3 Part 13 (Final) & Level 4 Part 1
DATA_MIX = {
    # Level 3 Final (Subtract - Voyage/Visible)
    "subtract": {"def": "減去、扣除", "ipa": "/səbˈtrækt/", "trans": "subtraction", "col": "subtract A from B", "ex": "If you subtract 5 from 10, you get 5.", "pos": "v."},
    "suburb": {"def": "郊區、近郊", "ipa": "/ˈsʌbɜːb/", "trans": "suburban", "col": "live in the suburbs", "ex": "They live in a quiet suburb of London.", "pos": "n."},
    "tag": {"def": "標籤、稱呼、給...加標籤", "ipa": "/tæɡ/", "trans": "tags", "col": "price tag, name tag", "ex": "The price tag said $50.", "pos": "n./v."},
    "tailor": {"def": "裁縫師、裁製、使適應", "ipa": "/ˈteɪlə/", "trans": "tailored", "col": "tailor-made", "ex": "The service is tailored to meet your needs.", "pos": "n./v."},
    "terrific": {"def": "極好的、了不起的、恐怖的", "ipa": "/təˈrɪfɪk/", "trans": "terrifically", "col": "terrific news", "ex": "You look terrific in that dress!", "pos": "adj."},
    "territory": {"def": "領土、領域、地盤", "ipa": "/ˈterətri/", "trans": "territorial", "col": "enemy territory, vast territory", "ex": "The army occupied a large territory.", "pos": "n."},
    "trader": {"def": "商人、交易者、商船", "ipa": "/ˈtreɪdə/", "trans": "trade", "col": "stock trader, local trader", "ex": "The salt traders traveled across the desert.", "pos": "n."},
    "trail": {"def": "小徑、蹤跡、拖曳、追蹤", "ipa": "/treɪl/", "trans": "trailing", "col": "walking trail, follow the trail", "ex": "The trail leads through the forest.", "pos": "n./v."},
    "twin": {"def": "雙胞胎之一、成對物之一、雙胞胎的、成對的", "ipa": "/twɪn/", "trans": "twins", "col": "identical twins", "ex": "She has a twin sister.", "pos": "n./adj."},
    "twist": {"def": "捻、扭、轉動、轉向、曲解、旋轉、擰", "ipa": "/twɪst/", "trans": "twisted", "col": "twist and turn", "ex": "She twisted her ankle while running.", "pos": "v./n."},
    "violet": {"def": "紫羅蘭、紫色的", "ipa": "/ˈvaɪələt/", "trans": "purplish", "col": "violet flowers", "ex": "The sky turned a deep violet.", "pos": "n./adj."},
    "visible": {"def": "顯而易見的、看得見的", "ipa": "/ˈvɪzəbl/", "trans": "visibility", "col": "highly visible", "ex": "The stars are clearly visible tonight.", "pos": "adj."},

    # Level 4 Part 1 (Vision - Amateur)
    "vision": {"def": "願景、眼光、視力、影像", "ipa": "/ˈvɪʒn/", "trans": "visual, visionary", "col": "have a vision, 20/20 vision", "ex": "The company has a clear vision for the future.", "pos": "n."},
    "vitamin": {"def": "維他命、維生素", "ipa": "/ˈvɪtəmɪn/", "trans": "vitamins", "col": "vitamin deficiency, take vitamins", "ex": "Oranges are rich in vitamin C.", "pos": "n."},
    "yell": {"def": "大叫、喊叫", "ipa": "/jel/", "trans": "yelling", "col": "yell at someone", "ex": "Don't yell at me!", "pos": "v./n."},
    "absolute": {"def": "絕對的、完全的", "ipa": "/ˈæbsəluːt/", "trans": "absolutely", "col": "absolute truth, absolute power", "ex": "He has absolute confidence in his ability.", "pos": "adj."},
    "absorb": {"def": "吸收、吸引(注意)、併吞", "ipa": "/əbˈzɔːb/", "trans": "absorption", "col": "absorb information, absorb moisture", "ex": "Plants absorb water from the soil.", "pos": "v."},
    "abstract": {"def": "抽象的、深奧的、摘要、提取", "ipa": "/ˈæbstrækt/", "trans": "abstraction", "col": "abstract art, abstract concept", "ex": "Happiness is an abstract concept.", "pos": "adj./n./v."},
    "abundant": {"def": "豐富的、充足的", "ipa": "/əˈbʌndənt/", "trans": "abundance", "col": "abundant resources", "ex": "The area has abundant natural resources.", "pos": "adj."},
    "abuse": {"def": "濫用、虐待、辱罵", "ipa": "/əˈbjuːs/", "trans": "abusive", "col": "child abuse, drug abuse, alcohol abuse", "ex": "The report highlights the abuse of power.", "pos": "n./v."},
    "academic": {"def": "學術的、學院的、學者", "ipa": "/ˌækəˈdemɪk/", "trans": "academy, academically", "col": "academic performance, academic year", "ex": "The school year is divided into two academic terms.", "pos": "adj./n."},
    "accent": {"def": "口音、重音、強調、重讀", "ipa": "/ˈæksent/", "trans": "accentuated", "col": "foreign accent, strong accent", "ex": "He speaks with a strong French accent.", "pos": "n./v."},
    "acceptable": {"def": "可接受的、令人滿意的", "ipa": "/əkˈseptəbl/", "trans": "accept, acceptance", "col": "socially acceptable", "ex": "The conditions are not acceptable to us.", "pos": "adj."},
    "acceptance": {"def": "接受、領受、承認", "ipa": "/əkˈseptəns/", "trans": "accept (動詞)", "col": "social acceptance", "ex": "The proposal found general acceptance.", "pos": "n."},
    "accessible": {"def": "易接近的、可到達的、好懂的", "ipa": "/əkˈsesəbl/", "trans": "access", "col": "easily accessible", "ex": "The library is easily accessible to the public.", "pos": "adj."},
    "accessory": {"def": "配件、零件、附屬的", "ipa": "/əkˈsesəri/", "trans": "accessories", "col": "fashion accessories", "ex": "The car has several accessories, including a DVD player.", "pos": "n./adj."},
    "accidentally": {"def": "偶然地、意外地", "ipa": "/ˌæksɪˈdentəli/", "trans": "accident (名詞)", "col": "accidentally deleted", "ex": "I accidentally broke the glass.", "pos": "adv."},
    "accommodate": {"def": "容納、提供住宿、使適應", "ipa": "/əˈkɒmədeɪt/", "trans": "accommodation", "col": "accommodate needs", "ex": "The hotel can accommodate up to 500 guests.", "pos": "v."},
    "accommodation": {"def": "住宿、調節、和解", "ipa": "/əˌkɒməˈdeɪʃn/", "trans": "accommodate (動詞)", "col": "hotel accommodation", "ex": "The price includes travel and accommodation.", "pos": "n."},
    "accompany": {"def": "陪同、伴隨、伴奏", "ipa": "/əˈkʌmpəni/", "trans": "accompaniment", "col": "be accompanied by", "ex": "He asked her to accompany him to the party.", "pos": "v."},
    "accomplish(ment)": {"def": "完成、實現、成就、才藝", "ipa": "/əˈkʌmplɪʃ(mənt)/", "trans": "accomplished", "col": "sense of accomplishment", "ex": "She has accomplished a lot in her career.", "pos": "v.(n.)"},
    "accord": {"def": "一致、符合、給予、和解、協議", "ipa": "/əˈkɔːd/", "trans": "accordance, accordingly", "col": "in accord with", "ex": "The two countries signed a peace accord.", "pos": "n./v."},
    "accountant": {"def": "會計師", "ipa": "/əˈkaʊntənt/", "trans": "accounting", "col": "certified public accountant", "ex": "He is an accountant for a law firm.", "pos": "n."},
    "accuracy": {"def": "準確性、正確度", "ipa": "/ˈækjərəsi/", "trans": "accurate", "col": "scientific accuracy", "ex": "The instrument measures with high accuracy.", "pos": "n."},
    "accurate": {"def": "準確的、精確的", "ipa": "/ˈækjərət/", "trans": "accuracy (名詞), accurately", "col": "accurate description", "ex": "Are these figures accurate?", "pos": "adj."},
    "accuse": {"def": "指控、控告、譴責", "ipa": "/əˈkjuːz/", "trans": "accusation", "col": "accuse someone of", "ex": "He was accused of murder.", "pos": "v."},
    "accused": {"def": "被控告的、被告", "ipa": "/əˈkjuːzd/", "trans": "accuse (動詞)", "col": "the accused person", "ex": "The accused was found not guilty.", "pos": "adj./n."},
    "accustom": {"def": "使習慣", "ipa": "/əˈkʌstəm/", "trans": "accustomed", "col": "accustom oneself to", "ex": "It took him a while to accustom himself to the heat.", "pos": "v."},
    "accustomed": {"def": "習慣的、通常的", "ipa": "/əˈkʌstəmd/", "trans": "accustom (動詞)", "col": "accustomed to", "ex": "I am not accustomed to getting up so early.", "pos": "adj."},
    "achieve(ment)": {"def": "完成、達到、成就、功績", "ipa": "/əˈtʃiːv(mənt)/", "trans": "achiever", "col": "achieve goals, lifetime achievement", "ex": "It's a major achievement to win the award.", "pos": "v.(n.)"},
    "acid": {"def": "酸、酸的、尖酸刻薄的", "ipa": "/ˈæsɪd/", "trans": "acidic", "col": "acid rain, amino acid", "ex": "Vinegar contains acetic acid.", "pos": "n./adj."},
    "acknowledge(ment)": {"def": "承認、自認、感謝、致謝", "ipa": "/əkˈnɒlɪdʒ(mənt)/", "trans": "acknowledged", "col": "acknowledge receipt", "ex": "He acknowledged that he was wrong.", "pos": "v.(n.)"},
    "acquaintance": {"def": "熟人、認識", "ipa": "/əˈkweɪntəns/", "trans": "acquaint", "col": "make acquaintance with", "ex": "She is just an acquaintance, not a friend.", "pos": "n."},
    "acquire": {"def": "獲得、取得、學到", "ipa": "/əˈkwaɪə/", "trans": "acquisition", "col": "acquire knowledge, acquire skills", "ex": "He acquired a reputation for being honest.", "pos": "v."},
    "acquisition": {"def": "獲得、收購、獲得物", "ipa": "/ˌækwɪˈzɪʃn/", "trans": "acquire (動詞)", "col": "merger and acquisition", "ex": "The company announced the acquisition of a smaller rival.", "pos": "n."},
    "acre": {"def": "英畝", "ipa": "/ˈeɪkə/", "trans": "acres", "col": "thousands of acres", "ex": "They own two hundred acres of land.", "pos": "n."},
    "activate": {"def": "啟動、使活化", "ipa": "/ˈæktɪveɪt/", "trans": "activation", "col": "activate the alarm", "ex": "The alarm is activated by heat.", "pos": "v."},
    "active": {"def": "積極的、活躍的、主動語態的", "ipa": "/ˈæktɪv/", "trans": "activity, action", "col": "take an active role, active life", "ex": "She leads a very active life.", "pos": "adj."},
    "actual": {"def": "實際的、真實的", "ipa": "/ˈæktʃuəl/", "trans": "actually", "col": "actual fact, actual value", "ex": "The actual cost was much higher than the estimate.", "pos": "adj."},
    "actually": {"def": "實際上、事實上、竟然", "ipa": "/ˈæktʃuəli/", "trans": "actual (形容詞)", "col": "actually happened", "ex": "What actually happened?", "pos": "adv."},
    "acute": {"def": "敏銳的、急性的、劇烈的", "ipa": "/əˈkjuːt/", "trans": "acutely", "col": "acute angle, acute pain", "ex": "There is an acute shortage of housing in the city.", "pos": "adj."},
    "adapt": {"def": "使適應、改編", "ipa": "/əˈdæpt/", "trans": "adaptation", "col": "adapt to", "ex": "The film was adapted from a novel.", "pos": "v."},
    "adaptation": {"def": "適應、改編", "ipa": "/ˌædæpˈteɪʃn/", "trans": "adapt (動詞)", "col": "film adaptation", "ex": "The adaptation of the play was a huge hit.", "pos": "n."},
    "addict": {"def": "使入迷、使成癮、有癮的人、入迷者", "ipa": "/ˈædɪkt/ (n.) /əˈdɪkt/ (v.)", "trans": "addiction, addicted", "col": "drug addict, shopaholic", "ex": "He is a computer addict.", "pos": "n./v."},
    "addicted": {"def": "上癮的、沉溺於...的", "ipa": "/əˈdɪktɪd/", "trans": "addict (名詞/動詞), addiction", "col": "addicted to", "ex": "She is addicted to chocolate.", "pos": "adj."},
    "addiction": {"def": "成癮、沉溺", "ipa": "/əˈdɪkʃn/", "trans": "addict (名詞/動詞), addicted", "col": "drug addiction", "ex": "He is trying to overcome his gambling addiction.", "pos": "n."},
    "addition": {"def": "加、加法、增添的人或物", "ipa": "/əˈdɪʃn/", "trans": "additional, add (動詞)", "col": "in addition to", "ex": "The baby is a new addition to the family.", "pos": "n."},
    "additional": {"def": "附加的、額外的", "ipa": "/əˈdɪʃənl/", "trans": "addition (名詞), additionally", "col": "additional information", "ex": "If you need additional information, please let us know.", "pos": "adj."},
    "adequate": {"def": "足夠的、適當的", "ipa": "/ˈædɪkwət/", "trans": "adequacy", "col": "adequate supplies", "ex": "The food was adequate for our needs.", "pos": "adj."},
    "adjust(ment)": {"def": "調整、適應、調節", "ipa": "/əˈdʒʌst(mənt)/", "trans": "adjustable", "col": "make an adjustment", "ex": "He adjusted his tie before the interview.", "pos": "v.(n.)"},
    "administrate": {"def": "管理、實施、經營", "ipa": "/ədˈmɪnɪstreɪt/", "trans": "administration, administrator", "col": "administrate justice", "ex": "The company was administrated by a board of directors.", "pos": "v."},
    "administration": {"def": "行政、管理、行政機關", "ipa": "/ədˌmɪnɪˈstreɪʃn/", "trans": "administrate (動詞), administrative", "col": "business administration", "ex": "She works in the school administration.", "pos": "n."},
    "administrative": {"def": "行政的、管理的", "ipa": "/ədˈmɪnɪstrətɪv/", "trans": "administration (名詞)", "col": "administrative staff", "ex": "He handles all the administrative work.", "pos": "adj."},
    "administrator": {"def": "管理人、行政官", "ipa": "/ədˈmɪnɪstreɪtə/", "trans": "administrate (動詞)", "col": "system administrator", "ex": "She is the administrator of the company.", "pos": "n."},
    "admirable": {"def": "值得讚揚的、極好的", "ipa": "/ˈædmərəbl/", "trans": "admire", "col": "admirable qualities", "ex": "She has many admirable qualities.", "pos": "adj."},
    "admiration": {"def": "欽佩、讚賞", "ipa": "/ˌædməˈreɪʃn/", "trans": "admire (動詞)", "col": "fill with admiration", "ex": "I have great admiration for her courage.", "pos": "n."},
    "admission": {"def": "承認、准許進入、入場費", "ipa": "/ədˈmɪʃn/", "trans": "admit (動詞)", "col": "admission fee, school admission", "ex": "The admission price is $10.", "pos": "n."},
    "admit": {"def": "承認、准許進入、容納", "ipa": "/ədˈmɪt/", "trans": "admission", "col": "admit defeat, admit to", "ex": "He admitted that he had made a mistake.", "pos": "v."},
    "adolescence": {"def": "青春期", "ipa": "/ˌædəˈlesns/", "trans": "adolescent", "col": "period of adolescence", "ex": "Adolescence is a time of great change.", "pos": "n."},
    "adolescent": {"def": "青少年的、未成熟的、青少年", "ipa": "/ˌædəˈlesnt/", "trans": "adolescence", "col": "adolescent behavior", "ex": "She is a typical adolescent.", "pos": "adj./n."},
    "adopt": {"def": "採取、採納、收養", "ipa": "/əˈdɒpt/", "trans": "adoption", "col": "adopt a child, adopt a policy", "ex": "They decided to adopt a child.", "pos": "v."},
    "adoption": {"def": "採納、收養", "ipa": "/əˈdɒpʃn/", "trans": "adopt (動詞)", "col": "legal adoption", "ex": "The adoption of new technology has improved productivity.", "pos": "n."},
    "adored": {"def": "崇拜的、喜愛的", "ipa": "/əˈdɔːd/", "trans": "adore", "col": "adored by", "ex": "She was adored by her grandchildren.", "pos": "adj."},
    "advance": {"def": "前進、進展、預付、提前、進步、前進、預付的、提前的", "ipa": "/ədˈvɑːns/", "trans": "advanced, advancement", "col": "in advance, advance notice", "ex": "The technology has advanced significantly in recent years.", "pos": "v./n./adj."},
    "advanced": {"def": "高級的、先進的、晚期的", "ipa": "/ədˈvɑːnst/", "trans": "advance (名詞/動詞)", "col": "advanced level, advanced technology", "ex": "She is taking an advanced course in mathematics.", "pos": "adj."},
    "advantage": {"def": "優點、利益、優勢、有利於、獲利", "ipa": "/ədˈvɑːntɪdʒ/", "trans": "advantageous", "col": "take advantage of", "ex": "Living in the city has many advantages.", "pos": "n./v."},
    "adventure": {"def": "冒險、奇遇、冒險", "ipa": "/ədˈventʃə/", "trans": "adventurous, adventurer", "col": "outdoor adventure", "ex": "Travelling alone was a great adventure.", "pos": "n./v."},
    "adventurer": {"def": "冒險家", "ipa": "/ədˈventʃərə/", "trans": "adventure (名詞/動詞)", "col": "famous adventurer", "ex": "He is a famous adventurer.", "pos": "n."},
    "adventurous": {"def": "愛冒險的、充滿危險的", "ipa": "/ədˈventʃərəs/", "trans": "adventure (名詞/動詞)", "col": "adventurous spirit", "ex": "She has an adventurous spirit.", "pos": "adj."},
    "advertise(ment)": {"def": "登廣告、做廣告、公告、廣告、啟事", "ipa": "/ˈædvətaɪz(mənt)/", "trans": "advertiser, advertising", "col": "advertise a product, online advertisement", "ex": "The company is advertising for a new manager.", "pos": "v.(n.)"},
    "advertiser": {"def": "廣告客戶、刊登廣告者", "ipa": "/ˈædvətaɪzə/", "trans": "advertise (動詞)", "col": "local advertiser", "ex": "The hospital is a major advertiser in the local newspaper.", "pos": "n."},
    "advertising": {"def": "廣告業、做廣告、廣告的", "ipa": "/ˈædvətaɪzɪŋ/", "trans": "advertise (動詞)", "col": "advertising agency, false advertising", "ex": "She works in advertising.", "pos": "n./adj."},
    "advisable": {"def": "明智的、可取的", "ipa": "/ədˈvaɪzəbl/", "trans": "advise", "col": "highly advisable", "ex": "It's advisable to book your tickets in advance.", "pos": "adj."},
    "advise/advice": {"def": "建議、忠告、通知、忠告、建議", "ipa": "/ədˈvaɪz/ (v.) /ədˈvaɪs/ (n.)", "trans": "adviser, advisory", "col": "take advice, give advice, piece of advice", "ex": "I would advise you to wait.", "pos": "v./n."},
    "adviser/advisor": {"def": "顧問、勸告者、導師", "ipa": "/ədˈvaɪzə/", "trans": "advise (動詞)", "col": "financial adviser, legal adviser", "ex": "She is a financial adviser.", "pos": "n."},
    "advocate": {"def": "提倡者、辯護者、擁護、提倡", "ipa": "/ˈædvəkət/ (n.) /ˈædvəkeɪt/ (v.)", "trans": "advocacy", "col": "advocate for", "ex": "He is a strong advocate of free speech.", "pos": "n./v."},
    "aesthetic": {"def": "美學的、審美的、美感", "ipa": "/iːsˈθetɪk/", "trans": "aesthetically", "col": "aesthetic appeal", "ex": "The building has a great aesthetic appeal.", "pos": "adj./n."},
    "affection": {"def": "感情、疼愛、嗜好", "ipa": "/əˈfekʃn/", "trans": "affectionate", "col": "deep affection", "ex": "I have a deep affection for my hometown.", "pos": "n."},
    "affectionate": {"def": "親切的、充滿深情的", "ipa": "/əˈfekʃənət/", "trans": "affection (名詞), affectionately", "col": "affectionate smile", "ex": "She is a very affectionate child.", "pos": "adj."},
    "affirm": {"def": "斷言、申明、肯定", "ipa": "/əˈfɜːm/", "trans": "affirmation, affirmative", "col": "affirm conviction", "ex": "The decision was affirmed by the court.", "pos": "v."},
    "afford": {"def": "買得起、負擔得起、提供", "ipa": "/əˈfɔːd/", "trans": "affordable", "col": "can afford to", "ex": "I can't afford to buy a new car.", "pos": "v."},
    "afterwards": {"def": "之後、後來", "ipa": "/ˈɑːftəwədz/", "trans": "afterward", "col": "soon afterwards", "ex": "We had dinner, and went to the theater afterwards.", "pos": "adv."},
    "agency": {"def": "代理店、代辦處、機構", "ipa": "/ˈeɪdʒənsi/", "trans": "agent", "col": "travel agency, advertising agency, government agency", "ex": "She works for a travel agency.", "pos": "n."},
    "agenda": {"def": "議事日程、待辦事項", "ipa": "/əˈdʒendə/", "trans": "agendas", "col": "hidden agenda, top of the agenda", "ex": "Education is at the top of the government's agenda.", "pos": "n."},
    "agent": {"def": "代理人、代理商、特務、原動力", "ipa": "/ˈeɪdʒənt/", "trans": "agency", "col": "real estate agent, travel agent, secret agent", "ex": "He is a real estate agent.", "pos": "n."},
    "aggression": {"def": "侵略、攻擊、挑釁", "ipa": "/əˈɡreʃn/", "trans": "aggressive, aggressor", "col": "act of aggression", "ex": "The invasion was an act of unprovoked aggression.", "pos": "n."},
    "aggressive": {"def": "侵略的、好鬥的、有進取心的", "ipa": "/əˈɡresɪv/", "trans": "aggression (名詞), aggressively", "col": "aggressive behavior", "ex": "His behavior was very aggressive.", "pos": "adj."},
    "agriculture": {"def": "農業、農耕", "ipa": "/ˈæɡrɪkʌltʃə/", "trans": "agricultural", "col": "organic agriculture", "ex": "Agriculture is the main industry in this area.", "pos": "n."},
    "agricultural": {"def": "農業的", "ipa": "/ˌæɡrɪˈkʌltʃərəl/", "trans": "agriculture (名詞)", "col": "agricultural products", "ex": "The country exports agricultural products.", "pos": "adj."},
    "AI": {"def": "人工智慧", "ipa": "/ˌeɪ ˈaɪ/", "trans": "artificial intelligence", "col": "generative AI", "ex": "AI is changing the way we work.", "pos": "n."},
    "airway": {"def": "通風口、氣道、國內航線", "ipa": "/ˈeəweɪ/", "trans": "airways", "col": "blocked airway", "ex": "The patient's airway was blocked.", "pos": "n."},
    "aisle": {"def": "通道、走道", "ipa": "/aɪl/", "trans": "aisles", "col": "aisle seat", "ex": "I prefer an aisle seat on the plane.", "pos": "n."},
    "alarm": {"def": "警報器、驚慌、鬧鐘、使驚慌、向...報警", "ipa": "/əˈlɑːm/", "trans": "alarming", "col": "smoke alarm, fire alarm, burglar alarm", "ex": "The alarm went off at 6 a.m.", "pos": "n./v."},
    "alcohol": {"def": "酒精、乙醇、酒", "ipa": "/ˈælkəhɒl/", "trans": "alcoholic", "col": "rubbing alcohol, alcohol abuse", "ex": "I don't drink alcohol.", "pos": "n."},
    "alcoholic": {"def": "含酒精的、嗜酒的、酒鬼、酒精愛好者", "ipa": "/ˌælkəˈhɒlɪk/", "trans": "alcohol (名詞)", "col": "alcoholic beverage", "ex": "He is an alcoholic.", "pos": "adj./n."},
    "alert": {"def": "警報、警惕、警覺的、留心的、使驚覺、使警惕", "ipa": "/əˈlɜːt/", "trans": "alertness", "col": "be on the alert, red alert", "ex": "The city is on high alert after the warning.", "pos": "n./adj./v."},
    "algebra": {"def": "代數學", "ipa": "/ˈældʒɪbrə/", "trans": "algebraic", "col": "linear algebra", "ex": "I found algebra very difficult in school.", "pos": "n."},
    "alien": {"def": "外星人的、外國的、怪異的、外星人、外國人", "ipa": "/ˈeɪliən/", "trans": "aliens", "col": "alien species", "ex": "Do you believe in aliens?", "pos": "adj./n."},
    "allergic": {"def": "過敏的", "ipa": "/əˈlɜːdʒɪk/", "trans": "allergy", "col": "be allergic to", "ex": "I am allergic to cats.", "pos": "adj."},
    "allergy": {"def": "過敏、反感", "ipa": "/ˈælədʒi/", "trans": "allergic", "col": "food allergy, nut allergy", "ex": "She has a nut allergy.", "pos": "n."},
    "alliance": {"def": "同盟、聯盟、姻親關係", "ipa": "/əˈlaɪəns/", "trans": "allied", "col": "strategic alliance", "ex": "The two companies formed a strategic alliance.", "pos": "n."},
    "allocate": {"def": "分配、撥給", "ipa": "/ˈæləkeɪt/", "trans": "allocation", "col": "allocate resources", "ex": "The government has allocated $10 million for the project.", "pos": "v."},
    "allot": {"def": "分配、撥給、派定", "ipa": "/əˈlɒt/", "trans": "allotment", "col": "allot time", "ex": "The time allotted for the task was not enough.", "pos": "v."},
    "allowance": {"def": "津貼、補貼、零用錢、限額", "ipa": "/əˈlaʊəns/", "trans": "allow (動詞)", "col": "monthly allowance, baggage allowance", "ex": "What is the baggage allowance for this flight?", "pos": "n."},
    "ally": {"def": "同盟國、夥伴、結盟、聯合", "ipa": "/ˈælaɪ/ (n.) /əˈlaɪ/ (v.)", "trans": "allies", "col": "trusted ally", "ex": "The two countries were allies during the war.", "pos": "n./v."},
    "alter": {"def": "改變、更改、改製(衣服)", "ipa": "/ˈɔːltə/", "trans": "alteration", "col": "alter the course", "ex": "The plans have been slightly altered.", "pos": "v."},
    "alternate": {"def": "交替的、輪流的、使交替、輪流", "ipa": "/ˈɔːltəneɪt/ (v.) /ɔːlˈtɜːnət/ (adj.)", "trans": "alternatively, alternative", "col": "alternate days", "ex": "Day and night alternate.", "pos": "v./adj."},
    "alternative": {"def": "替代的、非傳統的、選擇、替代方案", "ipa": "/ɔːlˈtɜːnətɪv/", "trans": "alternatively", "col": "alternative energy, have no alternative", "ex": "We have no alternative but to wait.", "pos": "adj./n."},
    "altitude": {"def": "高度、海拔、高處", "ipa": "/ˈæltɪtjuːd/", "trans": "altitudes", "col": "high altitude", "ex": "The plane was flying at an altitude of 30,000 feet.", "pos": "n."},
    "ambassador": {"def": "大使、使節", "ipa": "/æmˈbæsədə/", "trans": "embassy", "col": "goodwill ambassador", "ex": "He was appointed ambassador to Japan.", "pos": "n."},
    "ambiguous": {"def": "含糊不清的、曖昧的、模稜兩可的", "ipa": "/æmˈbɪɡjuəs/", "trans": "ambiguity", "col": "ambiguous message", "ex": "The message was very ambiguous.", "pos": "adj."},
    "ambition": {"def": "野心、抱負、志向", "ipa": "/æmˈbɪʃn/", "trans": "ambitious", "col": "fulfill an ambition", "ex": "His ambition is to become a famous writer.", "pos": "n."},
    "ambitious": {"def": "野心勃勃的、有抱負的", "ipa": "/æmˈbɪʃəs/", "trans": "ambition (名詞), ambitiously", "col": "ambitious project", "ex": "She is a very ambitious young lawyer.", "pos": "adj."},
    "ambulance": {"def": "救護車", "ipa": "/ˈæmbjələns/", "trans": "ambulances", "col": "call an ambulance", "ex": "The ambulance arrived within five minutes.", "pos": "n."},
    "ambush": {"def": "埋伏、伏擊、埋伏、伏擊", "ipa": "/ˈæmbʃ/", "trans": "ambushed", "col": "fall into an ambush", "ex": "The soldiers were caught in an ambush.", "pos": "n./v."},
    "amend(ment)": {"def": "修訂、修正、改良、修正案", "ipa": "/əˈmend(mənt)/", "trans": "amended", "col": "constitutional amendment", "ex": "They have amended the law.", "pos": "v.(n.)"},
    "amateur": {"def": "業餘愛好者、業餘的、外行的", "ipa": "/ˈæmətə/", "trans": "amateurish", "col": "amateur photographer", "ex": "He is an amateur photographer.", "pos": "n./adj."},
}

with open("batch_l3l4_mix_p1.json", "w", encoding="utf-8") as f:
    json.dump(DATA_MIX, f, ensure_ascii=False, indent=2)
