import json

# Level 6 Part 46: (Braggart - Brass)
L6_PART46 = {
    "braggart": {"def": "大言不慚者、吹牛的人、吹牛的、大言不慚地 (吹)", "ipa": "/ˈbræɡət/", "trans": "brag (動詞/名詞/副詞)", "col": "arrogant braggart", "ex": "He is such an arrogant braggart about his sports achievements.", "pos": "n./adj./adv."},
    "bragging": {"def": "吹牛、自誇、自誇的人 (或物) (吹)", "ipa": "/ˈbræɡɪŋ/", "trans": "brag (動詞/名詞/副詞)", "col": "bragging rights (自誇的權利)", "ex": "He was bragging about how much money he'd made.", "pos": "n./adv."},
    "braid": {"def": "辮子、穗子、編織、裝飾、編織的人 (或物)、編織地 (編)", "ipa": "/breɪd/", "trans": "braiding, braided", "col": "gold braid, braid hair", "ex": "She wore her hair in a long braid.", "pos": "n./v./adv."},
    "braided": {"def": "編織的、有穗的的人 (或物) (編)", "ipa": "/ˈbreɪdɪd/", "trans": "braid (名詞/動詞/副詞)", "col": "braided rug", "ex": "She has beautifully braided hair.", "pos": "adj./adv."},
    "braiding": {"def": "辮帶、編織物、編織的人 (或物) (編)", "ipa": "/ˈbreɪdɪŋ/", "trans": "braid (名詞/動詞/副詞)", "col": "intricate braiding", "ex": "The intricate braiding on the jacket was done by hand.", "pos": "n./adv."},
    "braille": {"def": "布萊葉點字法、盲文 (單數)", "ipa": "/breɪl/", "trans": "coding", "col": "read braille", "ex": "The elevator buttons are marked in braille.", "pos": "n."},
    "brain": {"def": "大腦、智力、腦子、打破腦袋、智囊、大腦的人 (或物)、智力地 (腦)", "ipa": "/breɪn/", "trans": "brains, brainy", "col": "brain drain (人才流失), brain storm (腦力激盪), brain trust (智囊團), pick someone's brains (請教)", "ex": "The brain is the control center of the body.", "pos": "n./v./adv."},
    "brainchild": {"def": "腦力勞動的成果、創意、發明", "ipa": "/ˈbreɪntʃaɪld/", "trans": "invention", "col": "his brainchild", "ex": "The project was the brainchild of a young engineer.", "pos": "n."},
    "brainless": {"def": "無腦的、愚蠢的、無智力地 (無腦)", "ipa": "/ˈbreɪnləs/", "trans": "stupid", "col": "brainless idot", "ex": "What a brainless thing to do!", "pos": "adj./adv."},
    "brainpower": {"def": "心智能力、腦力 (單數)", "ipa": "/ˈbreɪnpaʊə/", "trans": "intelligence", "col": "intellectual brainpower", "ex": "Solving these puzzles requires a lot of brainpower.", "pos": "n."},
    "brainstorm": {"def": "腦力激盪、集思廣益、靈光一閃、腦力激盪的人、突然地 (激盪)", "ipa": "/ˈbreɪnstɔːm/", "trans": "brainstorming", "col": "brainstorm ideas", "ex": "We need to brainstorm some ideas for the marketing campaign.", "pos": "v./n./adv."},
    "brainstorming": {"def": "集思廣益、腦力激盪的人 (或物) (激)", "ipa": "/ˈbreɪnstɔːmɪŋ/", "trans": "brainstorm (名詞/動詞/副詞)", "col": "brainstorming session", "ex": "We had a very productive brainstorming session this morning.", "pos": "n./adv."},
    "brainteaser": {"def": "燒腦益智題、謎題 (單數)", "ipa": "/ˈbreɪntiːzə/", "trans": "puzzle", "col": "clever brainteaser", "ex": "This math puzzle is a real brainteaser.", "pos": "n."},
    "brainwash": {"def": "洗腦、洗腦的人 (或物)、洗腦地 (洗腦)", "ipa": "/ˈbreɪnwɒʃ/", "trans": "brainwashing", "col": "prevent brainwash", "ex": "They were brainwashed into believing the propaganda.", "pos": "v./n./adv."},
    "brainwashing": {"def": "洗腦行為、思想改造的人 (或物) (洗)", "ipa": "/ˈbreɪnwɒʃɪŋ/", "trans": "brainwash (名詞/動詞/副詞)", "col": "political brainwashing", "ex": "The regime used political brainwashing to control the population.", "pos": "n./adv."},
    "brainwave": {"def": "(醫)腦波、靈光一閃 (單數)", "ipa": "/ˈbreɪnweɪv/", "trans": "brainwaves (複數)", "col": "have a brainwave", "ex": "I've just had a brainwave for the solving problem.", "pos": "n."},
    "brainwork": {"def": "腦力勞動、心智工作", "ipa": "/ˈbreɪnwɜːk/", "trans": "mental work", "col": "heavy brainwork", "ex": "Writing a novel involves a lot of heavy brainwork.", "pos": "n."},
    "brainy": {"def": "聰明的、有頭腦的", "ipa": "/ˈbreɪni/", "trans": "brain (名詞/動詞/副詞)", "col": "brainy student", "ex": "She's the brainy one in the family.", "pos": "adj."},
    "braise": {"def": "燉、燜、燉肉的人 (或物)、燉肉地 (燉)", "ipa": "/breɪz/", "trans": "braised", "col": "braised beef", "ex": "The recipe explains how to braise beef in red wine.", "pos": "v./n./adv."},
    "brake": {"def": "煞車、制動器、抑制、煞住、煞車的人、制動地 (煞)", "ipa": "/breɪk/", "trans": "brakes", "col": "apply the brakes, emergency brake, disc brake", "ex": "He hit the brakes just in time to avoid the crash.", "pos": "n./v./adv."},
    "bramble": {"def": "荊棘、黑莓叢 (單數)", "ipa": "/ˈbræmbl/", "trans": "brambles (複數)", "col": "thicket of brambles", "ex": "The sheep got stuck in a thicket of brambles.", "pos": "n."},
    "bran": {"def": "糠、麩皮、糠狀的人 (或物)、糠狀地 (糠)", "ipa": "/bræn/", "trans": "fiber", "col": "bran flakes, wheat bran", "ex": "Bran is a good source of fiber.", "pos": "n./adv."},
    "branch": {"def": "樹枝、分部、分支、分支、延伸、分支的人、分支地 (枝)", "ipa": "/brɑːntʃ/", "trans": "branches, branching", "col": "bank branch, local branch, executive branch, branch out (拓展業務)", "ex": "The bird perches on a low branch.", "pos": "n./v./adv."},
    "branched": {"def": "分支的、有枝的的人 (或物) (枝)", "ipa": "/brɑːntʃt/", "trans": "branch (名詞/動詞/副詞)", "col": "branched path", "ex": "The river has many branched tributaries.", "pos": "adj./adv."},
    "branching": {"def": "分叉、分支、分支的人 (或物) (分)", "ipa": "/ˈbrɑːntʃɪŋ/", "trans": "branch (名詞/動詞/副詞)", "col": "branching out", "ex": "The tree has complex branching patterns.", "pos": "n./adv."},
    "brand": {"def": "品牌、商標、火印、打火印、烙印、烙印的人、烙印地 (牌)", "ipa": "/brænd/", "trans": "branding, branded", "col": "well-known brand, leading brand, store brand, brand name", "ex": "Which brand of toothpaste do you usually use?", "pos": "n./v./adv."},
    "branded": {"def": "有品牌的、被烙印的的人 (或物) (品)", "ipa": "/ˈbrændɪd/", "trans": "brand (名詞/動詞/副詞)", "col": "branded goods", "ex": "I prefer to buy branded goods for their quality.", "pos": "adj./adv."},
    "brand-new": {"def": "全新的、嶄新的", "ipa": "/ˌbrænd ˈnjuː/", "trans": "mint", "col": "brand-new car", "ex": "He just bought a brand-new car.", "pos": "adj."},
    "brandish": {"def": "揮舞、炫耀地 (揮)", "ipa": "/ˈbrændɪʃ/", "trans": "flourish", "col": "brandish a sword", "ex": "The angry man brandished a stick at us.", "pos": "v./adv."},
    "brandy": {"def": "白蘭地、白蘭地地 (白蘭地)", "ipa": "/ˈbrændi/", "trans": "liquor", "col": "glass of brandy", "ex": "He drank a glass of brandy before going to bed.", "pos": "n./adv."},
    "brash": {"def": "莽撞的、傲慢的、性急的人、傲慢地 (莽)", "ipa": "/bræʃ/", "trans": "brashness", "col": "brash attitude", "ex": "He's far too brash and confident.", "pos": "adj./n./adv."},
    "brashness": {"def": "莽撞、傲慢、性急", "ipa": "/ˈbræʃnəs/", "trans": "brash (形容詞/名詞/副詞)", "col": "typical brashness", "ex": "His typical brashness got him into trouble again.", "pos": "n."},
    "brass": {"def": "黃銅、銅管樂器、(口)高官、黃銅的、像黃銅般的、黃銅地 (銅)", "ipa": "/brɑːs/", "trans": "brassy", "col": "brass band, top brass (高層), bold as brass", "ex": "The door handle is made of solid brass.", "pos": "n./adj./adv."},
}