import json

# Level 6 Part 41: (Bodyguard - Boom)
L6_PART41 = {
    "bodyguard": {"def": "保鏢、護衛隊 (單數)", "ipa": "/ˈbɒdiɡɑːd/", "trans": "bodyguards (複數)", "col": "personal bodyguard", "ex": "The president travels with a team of personal bodyguards.", "pos": "n."},
    "bodywork": {"def": "(車)車身", "ipa": "/ˈbɒdiwɜːk/", "trans": "chassis", "col": "shiny bodywork", "ex": "The shiny bodywork of the car was damaged in the accident.", "pos": "n."},
    "bog": {"def": "沼澤、泥塘、困住、使不陷、泥濘地 (沼)", "ipa": "/bɒɡ/", "trans": "boggy", "col": "peat bog, bog down (陷入泥淖)", "ex": "The car got bogged down in the mud.", "pos": "n./v./adv."},
    "bogeyman/boogeyman": {"def": "恐怖的人、妖怪 (單數)", "ipa": "/ˈbəʊɡimæn/", "trans": "monster", "col": "scary bogeyman", "ex": "Children are often afraid of the scary bogeyman.", "pos": "n."},
    "boggle": {"def": "吃驚、猶豫、畏縮、吃驚的人、猶豫地 (吃驚)", "ipa": "/ˈbɒɡl/", "trans": "boggles", "col": "mind-boggling (驚人的)", "ex": "The scale of the project boggles the mind.", "pos": "v./n./adv."},
    "boggy": {"def": "沼澤的、泥濘的、鬆軟地 (沼澤)", "ipa": "/ˈbɒɡi/", "trans": "bog (名詞/動詞/副詞)", "col": "boggy ground", "ex": "We walked carefully over the boggy ground.", "pos": "adj./adv."},
    "bogus": {"def": "偽造的、假的、假冒的人、偽造地 (偽)", "ipa": "/ˈbəʊɡəs/", "trans": "fake", "col": "bogus documents, bogus insurance claim", "ex": "He was arrested for using bogus insurance documents.", "pos": "adj./n./adv."},
    "bohemian": {"def": "波希米亞的、放蕩不羈的、波希米亞人、放蕩不羈地 (波希米亞)", "ipa": "/bəʊˈhiːmiən/", "trans": "nonconformist", "col": "bohemian lifestyle", "ex": "They lived a very bohemian lifestyle in Paris.", "pos": "adj./n./adv."},
    "boil": {"def": "沸騰、煮開、沸點、癤子、沸騰的人 (或物)、沸騰地 (沸)", "ipa": "/bɔɪl/", "trans": "boiling, boiler", "col": "boiling water, bring to the boil, on the boil", "ex": "Is the water boiling yet?", "pos": "v./n./adv."},
    "boiler": {"def": "鍋爐、熱水器", "ipa": "/ˈbɔɪlə/", "trans": "boil (名詞/動詞/副詞)", "col": "central heating boiler", "ex": "The central heating boiler needs to be repaired.", "pos": "n."},
    "boiling": {"def": "沸騰的、極熱的、沸騰的人 (或物) (沸)", "ipa": "/ˈbɔɪlɪŋ/", "trans": "boil (名詞/動詞/副詞)", "col": "boiling point, boiling hot", "ex": "It's boiling hot in here!", "pos": "adj./adv."},
    "boisterous": {"def": "喧鬧的、狂暴的、活潑的", "ipa": "/ˈbɔɪstərəs/", "trans": "rowdy", "col": "boisterous energy", "ex": "The children were very boisterous after the party.", "pos": "adj."},
    "boisterously": {"def": "喧鬧地、狂暴地、活潑地", "ipa": "/ˈbɔɪstərəli/", "trans": "boisterous (形容詞)", "col": "greeted boisterously", "ex": "They greeted each other boisterously.", "pos": "adv."},
    "boisterousness": {"def": "喧鬧、狂暴、活潑", "ipa": "/ˈbɔɪstərəsnəs/", "trans": "boisterous (形容詞/副詞)", "col": "childish boisterousness", "ex": "He was annoyed by their childish boisterousness.", "pos": "n."},
    "bold": {"def": "大膽的、勇敢的、黑體的、厚顏無恥的、大膽地 (大膽)", "ipa": "/bəʊld/", "trans": "boldly, boldness", "col": "bold move, bold typeface, as bold as brass (厚著臉皮)", "ex": "It was a bold move to start his own business.", "pos": "adj./adv."},
    "bold-faced/boldface": {"def": "厚顏無恥的、黑體的、黑體的人、黑體地 (黑體)", "ipa": "/ˌbəʊldˈfeɪst/", "trans": "boldfaced", "col": "bold-faced type", "ex": "The keywords are printed in bold-faced type.", "pos": "adj./n./adv."},
    "boldly": {"def": "大膽地、勇敢地、醒目地 (膽)", "ipa": "/ˈbəʊldli/", "trans": "bold (形容詞/副詞)", "col": "stated boldly", "ex": "She boldly stated her opinion in the meeting.", "pos": "adv."},
    "boldness": {"def": "大膽、勇敢、醒目", "ipa": "/ˈbəʊldnəs/", "trans": "bold (形容詞/副詞)", "col": "remarkable boldness", "ex": "The artist used colors with remarkable boldness.", "pos": "n."},
    "bolero": {"def": "波麗露舞、短上衣 (單數)", "ipa": "/bəˈleərəʊ/", "trans": "boleros (複數)", "col": "Ravel's Bolero", "ex": "She wore a black velvet bolero over her dress.", "pos": "n."},
    "boll": {"def": "(棉花、亞麻)圓莢 (單數)", "ipa": "/bəʊl/", "trans": "bolls (複數)", "col": "cotton boll", "ex": "The cotton boll bursts open when it is ripe.", "pos": "n."},
    "bollard": {"def": "繫船柱、護柱 (單數)", "ipa": "/ˈbɒlɑːd/", "trans": "bollards (複數)", "col": "mooring bollard", "ex": "The ship's rope was tied to the mooring bollard.", "pos": "n."},
    "bollix": {"def": "(俚)弄糟、搞亂、廢話的人、廢話地 (糟)", "ipa": "/ˈbɒlɪks/", "trans": "mess up", "col": "bollix up (搞砸)", "ex": "Don't bollix up the whole plan!", "pos": "v./n./adv."},
    "boloney/baloney": {"def": "(俚)胡說、廢話的人、廢話地 (廢話)", "ipa": "/bəˈləʊni/", "trans": "nonsense", "col": "it's all boloney", "ex": "Everything he said about his past was just boloney.", "pos": "n./adv."},
    "bolster": {"def": "長枕、墊枕、支持、增強、支持的人、支持地 (支)", "ipa": "/ˈbəʊlstə/", "trans": "support", "col": "bolster arguments, bolster confidence", "ex": "The good news bolstered our spirits.", "pos": "n./v./adv."},
    "bolt": {"def": "螺栓、急逃、閃電、門閂、上閂、衝出、門閂的人、衝出地 (栓)", "ipa": "/bəʊlt/", "trans": "bolts", "col": "nut and bolt, bolt of lightning, bolt for the door, bolt down (狼吞虎嚥)", "ex": "He tightened the nut and bolt.", "pos": "n./v./adv."},
    "bomb": {"def": "炸彈、大失敗、轟炸、突然失敗、爆炸的人、爆炸地 (炸)", "ipa": "/bɒm/", "trans": "bomber, bombing", "col": "atomic bomb, time bomb, go like a bomb (飛速前進), bomb disposal", "ex": "The bomb exploded in the middle of the street.", "pos": "n./v./adv."},
    "bombard": {"def": "轟炸、砲擊、(以問題)連番質問的人、轟炸地 (轟)", "ipa": "/bɒmˈbɑːd/", "trans": "bombardment", "col": "bombard with questions", "ex": "The minister was bombarded with questions from reporters.", "pos": "v./n./adv."},
    "bombardment": {"def": "轟炸、砲擊、連番質問", "ipa": "/bɒmˈbɑːdmənt/", "trans": "bombard (動詞/名詞/副詞)", "col": "heavy bombardment", "ex": "The city suffered heavy bombardment during the night.", "pos": "n."},
    "bombase": {"def": "爆炸、(舊)棉花填料的人物、填充地 (填)", "ipa": "/ˈbɒmbeɪs/", "trans": "padding", "col": "bombase style", "ex": "The old garment was filled with traditional bombase.", "pos": "n./adv."},
    "bombast": {"def": "大話、誇大、誇大的言詞 (單數)", "ipa": "/ˈbɒmbæst/", "trans": "rhubarb", "col": "empty bombast", "ex": "His speech was full of empty bombast.", "pos": "n."},
    "bombastic": {"def": "誇大的、誇張的", "ipa": "/bɒmˈbæstɪk/", "trans": "pompous", "col": "bombastic speech", "ex": "The candidate gave a bombastic speech that ignored the issues.", "pos": "adj."},
    "bombed": {"def": "(俚)喝醉的、被炸毀的、醉醺醺的人物", "ipa": "/bɒmd/", "trans": "drunk", "col": "get bombed", "ex": "They got completely bombed at the party.", "pos": "adj./n."},
    "bomber": {"def": "轟炸機、爆炸手", "ipa": "/ˈbɒmə/", "trans": "bomb (名詞/動詞/副詞)", "col": "suicide bomber, bomber jacket", "ex": "The bomber was shot down over enemy territory.", "pos": "n."},
    "bombing": {"def": "轟炸、下炸彈、轟炸的人 (或物) (炸)", "ipa": "/ˈbɒmɪŋ/", "trans": "bomb (名詞/動詞/副詞)", "col": "terrorist bombing", "ex": "The terrorist bombing caused many casualties.", "pos": "n./adv."},
    "bombshell": {"def": "炸彈、出人意料的消息、炸彈的人 (或物) (驚)", "ipa": "/ˈbɒmʃel/", "trans": "surprise", "col": "blonde bombshell (性感金髮女郎), drop a bombshell", "ex": "The announcement was a total bombshell.", "pos": "n./adv."},
    "bon/good": {"def": "好的、(法)好地 (好)", "ipa": "/bɒn/", "trans": "well", "col": "bon appétit, bon voyage", "ex": "Bon voyage! I hope you have a great trip.", "pos": "adj./adv."},
    "bonanza": {"def": "興旺、富礦脈、幸運的事物的人物、興旺地 (旺)", "ipa": "/bəˈnænzə/", "trans": "windfall", "col": "bonus bonanza", "ex": "The high oil prices were a bonanza for the oil companies.", "pos": "n./adv."},
    "bond": {"def": "結合、債券、契約、化合鍵、使結合、契約的人物、在契約內地 (約)", "ipa": "/bɒnd/", "trans": "bonds", "col": "government bond, strong bond, in bond (關棧保稅), bail bond", "ex": "There is a strong bond between the two sisters.", "pos": "n./v./adv."},
    "bondage": {"def": "奴役、束縛、奴隸身分 (單數)", "ipa": "/ˈbɒndɪdʒ/", "trans": "slavery", "col": "released from bondage", "ex": "The slaves were finally released from bondage.", "pos": "n."},
    "bonded": {"def": "結合的、有擔保的、保稅的 (單數)", "ipa": "/ˈbɒndɪd/", "trans": "bond (名詞/動詞/副詞)", "col": "bonded warehouse (保稅倉庫)", "ex": "The goods are stored in a bonded warehouse.", "pos": "n./adj."},
    "bone": {"def": "骨頭、骨骼、挑掉骨頭、骨製的人 (或物)、骨頭地 (骨)", "ipa": "/bəʊn/", "trans": "bony", "col": "bone marrow, bone idle (懶透了), to the bone (深入地), a bone of contention (爭端)", "ex": "He broke a bone in his arm.", "pos": "n./v./adv."},
    "boneless": {"def": "無骨的、無骨氣的", "ipa": "/ˈbəʊnləs/", "trans": "bone (名詞/動詞/副詞)", "col": "boneless chicken", "ex": "I bought some boneless chicken for the stew.", "pos": "adj."},
    "boner": {"def": "(俚)大錯、(俚)勃起、犯大錯的人 (或物) (錯)", "ipa": "/ˈbəʊnə/", "trans": "mistake", "col": "make a boner", "ex": "He made a real boner in the presentation.", "pos": "n./adv."},
    "bonfire": {"def": "營火、大火堆", "ipa": "/ˈbɒnfaɪə/", "trans": "fire", "col": "light a bonfire", "ex": "They lit a huge bonfire on the beach.", "pos": "n."},
    "bonnet": {"def": "女用童帽、(英)引擎蓋、裝上遮罩的人 (或物) (帽)", "ipa": "/ˈbɒnɪt/", "trans": "hood", "col": "open the bonnet", "ex": "The driver opened the bonnet to check the engine.", "pos": "n./adv."},
    "bonny": {"def": "漂亮的、健美的、吸引的人物、漂亮地 (漂亮)", "ipa": "/ˈbɒni/", "trans": "beautiful", "col": "bonny baby", "ex": "What a bonny baby!", "pos": "adj./n./adv."},
    "bonus": {"def": "額外給予的東西、紅利、獎金、額外的人物、紅利地 (紅利)", "ipa": "/ˈbəʊnəs/", "trans": "bonuses", "col": "annual bonus, Christmas bonus, sign-on bonus", "ex": "Employees receive an annual bonus based on performance.", "pos": "n./adv."},
    "bony": {"def": "多骨的、瘦骨嶙峋的、骨骼的人物", "ipa": "/ˈbəʊni/", "trans": "bone (名詞/動詞/副詞)", "col": "bony hands", "ex": "He has long, bony hands.", "pos": "adj./n."},
    "boo": {"def": "(感嘆詞)嘘！、表示反對、倒彩、發嘘聲、發嘘聲的人物、嘘聲地 (嘘)", "ipa": "/buː/", "trans": "boos", "col": "boo off the stage", "ex": "The crowd booed the unpopular player off the stage.", "pos": "int./n./v./adv."},
    "boob": {"def": "(口)大錯、(俚)乳房、(俚)笨蛋、犯大錯的人 (或物)、大錯地 (大錯)", "ipa": "/buːb/", "trans": "boobs", "col": "make a boob", "ex": "He made a real boob in the test score calculation.", "pos": "n./v./adv."},
    "booby": {"def": "笨蛋、傻瓜、鰹鳥的人 (或物)、笨瓜地 (笨)", "ipa": "/ˈbuːbi/", "trans": "boobies", "col": "booby prize (安慰獎), booby trap (詭雷)", "ex": "The soldiers were warned about booby traps.", "pos": "n./adv."},
    "boogie": {"def": "(流)搖擺舞、跳搖擺舞、搖擺的人物、搖擺地 (搖擺)", "ipa": "/ˈbuːɡi/", "trans": "boogied", "col": "boogie woogie", "ex": "Let's boogie!", "pos": "n./v./adv."},
    "book": {"def": "書、手冊、登記、預訂、書商、書狀的人、預訂地 (書)", "ipa": "/bʊk/", "trans": "books, booking", "col": "notebook, guidebook, in someone's good books (受器重), throw the book at (嚴懲)", "ex": "I'm reading a very interesting book.", "pos": "n./v./adj./adv."},
    "bookcase": {"def": "書櫃、書架 (單數)", "ipa": "/ˈbʊkkeɪs/", "trans": "bookcases (複數)", "col": "wooden bookcase", "ex": "The wooden bookcase is filled with old novels.", "pos": "n."},
    "bookie": {"def": "(口)賭博經紀人、外圍商 (單數)", "ipa": "/ˈbʊki/", "trans": "bookies (複數)", "col": "local bookie", "ex": "He placed a bet with the local bookie.", "pos": "n."},
    "booking": {"def": "預約、登記、下注、預訂的人 (或物) (預)", "ipa": "/ˈbʊkɪŋ/", "trans": "book (名詞/動詞/副詞)", "col": "advanced booking, booking office", "ex": "It's best to make an advanced booking for the restaurant.", "pos": "n./adv."},
    "bookish": {"def": "博學的、書生氣的、沈溺於書本的", "ipa": "/ˈbʊkɪʃ/", "trans": "book (名詞/動詞/副詞)", "col": "bookish child", "ex": "He was a quiet, bookish child who preferred reading to sports.", "pos": "adj."},
    "bookkeeper": {"def": "簿記員", "ipa": "/ˈbʊkkiːpə/", "trans": "bookkeeping", "col": "certified bookkeeper", "ex": "She works as a certified bookkeeper for a small auditing firm.", "pos": "n."},
    "bookkeeping": {"def": "簿記", "ipa": "/ˈbʊkkiːpɪŋ/", "trans": "bookkeeper", "col": "manual bookkeeping", "ex": "Manual bookkeeping is time-consuming compared to software.", "pos": "n."},
    "booklet": {"def": "小冊子 (單數)", "ipa": "/ˈbʊklət/", "trans": "booklets (複數)", "col": "instruction booklet", "ex": "Read the instruction booklet before you start.", "pos": "n."},
    "bookmaker": {"def": "賭博業者、書籍製作者 (單數)", "ipa": "/ˈbʊkmeɪkə/", "trans": "bookie", "col": "professional bookmaker", "ex": "The bookmaker took bets on the horse race.", "pos": "n."},
    "bookmark": {"def": "書籤、(網)我的最愛、夾書籤於、存入最愛的人 (或物) (籤)", "ipa": "/ˈbʊkmɑːk/", "trans": "bookmarks", "col": "useful bookmark", "ex": "She put a colorful bookmark in the book.", "pos": "n./v./adv."},
    "bookshelf": {"def": "書架 (單數)", "ipa": "/ˈbʊkʃelf/", "trans": "bookshelves (複數)", "col": "crowded bookshelf", "ex": "The original bookshelves were crowded with antique books.", "pos": "n."},
    "bookstore/book shop": {"def": "書店 (單數)", "ipa": "/ˈbʊkstɔː/", "trans": "bookshops (複數)", "col": "local bookstore, independent book shop", "ex": "I bought this novel at a local bookstore.", "pos": "n."},
    "bookworm": {"def": "書呆子、蛀書蟲 (單數)", "ipa": "/ˈbʊkwɜːm/", "trans": "bookworms (複數)", "col": "total bookworm", "ex": "My daughter is a total bookworm who reads every night.", "pos": "n."},
    "boom": {"def": "繁榮、暴漲、轟鳴、帆桁、發轟鳴、突然繁榮的人 (或物)、繁榮地 (旺)", "ipa": "/buːm/", "trans": "booming", "col": "economic boom, sonic boom, baby boom", "ex": "The tech industry is experiencing a massive boom.", "pos": "n./v./adv."},
}