import json

# Level 6 Part 28: (Beggarman - Belligerent)
L6_PART28 = {
    "beggarman": {"def": "男乞丐", "ipa": "/ˈbeɡəmən/", "trans": "beggar", "col": "homeless beggarman", "ex": "The old beggarman sits on the street corner every day.", "pos": "n."},
    "beggary": {"def": "行乞、赤貧、精窮", "ipa": "/ˈbeɡəri/", "trans": "poverty", "col": "reduced to beggary", "ex": "The family was reduced to beggary after the fire.", "pos": "n."},
    "begging": {"def": "乞討、乞求、乞討的人 (或物) (乞)", "ipa": "/ˈbeɡɪŋ/", "trans": "beg (動詞/名詞/副詞)", "col": "go begging (乏人問津)", "ex": "There are several good jobs going begging.", "pos": "n./adv."},
    "begin": {"def": "開始、著手、起始地 (開始)", "ipa": "/bɪˈɡɪn/", "trans": "beginning, began, begun", "col": "begin at the beginning, begin with", "ex": "When does the concert begin?", "pos": "v./adv."},
    "beginner": {"def": "初學者、新手", "ipa": "/bɪˈɡɪnə/", "trans": "begin (動詞/副詞), beginning", "col": "complete beginner", "ex": "The course is suitable for complete beginners.", "pos": "n."},
    "beginning": {"def": "開始、起始、起點、開端的人物、開端地 (開端)", "ipa": "/bɪˈɡɪnɪŋ/", "trans": "begin (動詞/副詞), beginner", "col": "at the beginning, small beginning, in the beginning", "ex": "Every beginning is difficult.", "pos": "n./adj./adv."},
    "begone": {"def": "走開、滾開、(詩)消失", "ipa": "/bɪˈɡɒn/", "trans": "go away", "col": "begone, dull care!", "ex": "I told him to begone and never come back.", "pos": "v./int."},
    "begonia": {"def": "秋海棠 (單數)", "ipa": "/bɪˈɡəʊniə/", "trans": "begonias (複數)", "col": "flowering begonia", "ex": "The window box was full of red begonias.", "pos": "n."},
    "begot": {"def": "(beget的過去式)、引起", "ipa": "/bɪˈɡɒt/", "trans": "beget", "col": "begot violence", "ex": "Violence begot more violence.", "pos": "v."},
    "begotten": {"def": "(beget的過去分詞)、引起的", "ipa": "/bɪˈɡɒtn/", "trans": "beget", "col": "first-begotten (長子)", "ex": "He is the first-begotten son of the family.", "pos": "v."},
    "begrudge": {"def": "嫉妒、吝惜、勉強給予", "ipa": "/bɪˈɡrʌdʒ/", "trans": "envy", "col": "begrudge someone something", "ex": "I don't begrudge him his success.", "pos": "v."},
    "beguile": {"def": "欺騙、使著迷、消磨(時間)", "ipa": "/bɪˈɡaɪl/", "trans": "charm", "col": "beguile with", "ex": "He beguiled the audience with his stories.", "pos": "v."},
    "beguiling": {"def": "迷人的、欺騙的", "ipa": "/bɪˈɡaɪlɪŋ/", "trans": "beguile (動詞)", "col": "beguiling smile", "ex": "She has a very beguiling smile.", "pos": "adj."},
    "begun": {"def": "(begin的過去分詞)、開始", "ipa": "/bɪˈɡʌn/", "trans": "begin", "col": "already begun", "ex": "The movie has already begun.", "pos": "v."},
    "behalf": {"def": "代表、利益、方面、代表的人物、代表地 (代表)", "ipa": "/bɪˈhɑːf/", "trans": "behalves", "col": "on behalf of, in behalf of", "ex": "I'm writing to you on behalf of my client.", "pos": "n./adv."},
    "behave": {"def": "行為舉止、表現、守規矩、表現的人 (或物)、表現地 (表現)", "ipa": "/bɪˈheɪv/", "trans": "behavior", "col": "behave yourself, behave badly", "ex": "The children behaved very well today.", "pos": "v./n./adv."},
    "behavior/behaviour": {"def": "行為、舉止、表現、習性、表現的人 (或物) (表現)", "ipa": "/bɪˈheɪvjə/", "trans": "behave (動詞/名詞/副詞), behavioral", "col": "social behavior, human behavior, patterns of behavior", "ex": "His behavior was unacceptable.", "pos": "n./adv."},
    "behavioral/behavioural": {"def": "行為的、行為學的", "ipa": "/bɪˈheɪvjərəl/", "trans": "behavior (名詞/副詞)", "col": "behavioral problems", "ex": "The student has some behavioral problems.", "pos": "adj."},
    "beheaded": {"def": "斬首的、砍頭的 (behead的過去分詞)", "ipa": "/bɪˈhedɪd/", "trans": "decapitated", "col": "beheaded king", "ex": "The king was beheaded during the revolution.", "pos": "v./adj."},
    "beheld": {"def": "(behold的過去式及過去分詞)、看到", "ipa": "/bɪˈheld/", "trans": "behold", "col": "beheld the sight", "ex": "They beheld a magnificent sunrise.", "pos": "v."},
    "behemoth": {"def": "巨獸、龐然大物", "ipa": "/bɪˈhiːmɒθ/", "trans": "giant", "col": "corporate behemoth", "ex": "The company has become a corporate behemoth.", "pos": "n."},
    "behest": {"def": "命令、叮囑、吩咐 (單數)", "ipa": "/bɪˈhest/", "trans": "command", "col": "at the behest of", "ex": "The changes were made at the behest of the director.", "pos": "n."},
    "behind": {"def": "在...後面、落後、背後、臀部、落後的、延遲的、在背後地 (後)", "ipa": "/bɪˈhaɪnd/", "trans": "back", "col": "left behind, fall behind, behind the scenes", "ex": "The keys are behind the sofa.", "pos": "prep./adv./adj./n."},
    "behold": {"def": "看、注視、瞧、注視的人 (或物)、注視地 (看)", "ipa": "/bɪˈhəʊld/", "trans": "beholden", "col": "behold, the man!", "ex": "Behold the beauty of the mountain!", "pos": "v./n./adv."},
    "beholden": {"def": "受惠的、感激的、欠情的", "ipa": "/bɪˈhəʊldən/", "trans": "indebted", "col": "beholden to", "ex": "I don't want to be beholden to anyone.", "pos": "adj."},
    "behoove/behove": {"def": "有必要、理應、適合 (單數)", "ipa": "/bɪˈhuːv/", "trans": "it is necessary", "col": "it behooves us to", "ex": "It behooves us to consider all the options.", "pos": "v."},
    "beige": {"def": "米色、米色的", "ipa": "/beɪʒ/", "trans": "cream", "col": "beige carpet", "ex": "The walls were painted a light beige.", "pos": "n./adj."},
    "being": {"def": "存在、生命、生物、人的本質、存在的、目前的、目前地 (在)", "ipa": "/ˈbiːɪŋ/", "trans": "existence", "col": "human being, for the time being (目前), well-being (福利)", "ex": "He is a very kind human being.", "pos": "n./adj./adv."},
    "belabor/belabour": {"def": "痛打、過分說明、喋喋不休地說", "ipa": "/bɪˈleɪbə/", "trans": "overwork", "col": "belabor the point", "ex": "There is no need to belabor the point.", "pos": "v."},
    "belated": {"def": "遲到的、誤期的、太遲地 (遲)", "ipa": "/bɪˈleɪtɪd/", "trans": "delayed", "col": "belated happy birthday", "ex": "I sent her a belated birthday card.", "pos": "adj./adv."},
    "belatedly": {"def": "遲延地、過遲地", "ipa": "/bɪˈleɪtɪdli/", "trans": "belated (形容詞/副詞)", "col": "realized belatedly", "ex": "She realized her mistake belatedly.", "pos": "adv."},
    "belch": {"def": "打嗝、噴出、嗝、噴射、噴射的人 (或物)、打嗝地 (嗝)", "ipa": "/beltʃ/", "trans": "burp", "col": "belch smoke", "ex": "The chimney belched black smoke into the air.", "pos": "v./n./adv."},
    "beleaguer": {"def": "圍攻、困擾、煩擾", "ipa": "/bɪˈliːɡə/", "trans": "besiege", "col": "beleaguered city", "ex": "The beleaguered city was finally captured.", "pos": "v."},
    "belfry": {"def": "鐘樓、鐘塔 (單數)", "ipa": "/ˈbelfri/", "trans": "belfries (複數)", "col": "bats in the belfry (癡狂)", "ex": "The birds nested in the belfry.", "pos": "n."},
    "belie": {"def": "掩飾、證明...為假、矛盾", "ipa": "/bɪˈlaɪ/", "trans": "contradict", "col": "belie one's words", "ex": "His actions belie his words.", "pos": "v."},
    "belief": {"def": "信念、相信、信仰、看法、信念的人物、信念地 (信念)", "ipa": "/bɪˈliːf/", "trans": "believe (動詞/名詞/副詞), believable", "col": "religious belief, general belief, in the belief that", "ex": "It's my belief that things will get better.", "pos": "n./adv."},
    "believable": {"def": "可信的、可靠的", "ipa": "/bɪˈliːvəbl/", "trans": "believe (動詞/名詞/副詞), belief", "col": "hardly believable", "ex": "The story was hardly believable.", "pos": "adj."},
    "believe": {"def": "相信、認為、信任、信仰、相信的人 (或物)、信仰地 (信)", "ipa": "/bɪˈliːv/", "trans": "belief, believable", "col": "believe in, hard to believe, make-believe (虛構)", "ex": "I believe that you are right.", "pos": "v./n./adv."},
    "believer": {"def": "信徒、相信者", "ipa": "/bɪˈliːvə/", "trans": "believe (動詞/名詞/副詞), belief", "col": "true believer", "ex": "He is a true believer in the power of education.", "pos": "n."},
    "belittle": {"def": "輕視、蔑視、把...看得很小", "ipa": "/bɪˈlɪtl/", "trans": "disparage", "col": "belittle efforts", "ex": "You should not belittle your brother's efforts.", "pos": "v."},
    "bell": {"def": "鐘、鈴、鐘聲、鈴聲、鈴狀物、發出鐘聲、像鐘般的、鐘聲地 (鐘)", "ipa": "/bel/", "trans": "bells", "col": "doorbell, alarm bell, bell pepper (青椒), ring a bell (耳熟)", "ex": "The church bell rang at noon.", "pos": "n./v./adj./adv."},
    "bellboy": {"def": "旅館服務生、行李員", "ipa": "/ˈbelbɔɪ/", "trans": "bellhop", "col": "friendly bellboy", "ex": "The bellboy took our luggage to the room.", "pos": "n."},
    "belle": {"def": "美女、名媛、受歡迎的女性 (單數)", "ipa": "/bel/", "trans": "beauty", "col": "belle of the ball", "ex": "She was the belle of the ball.", "pos": "n."},
    "bellhop": {"def": "旅館服務生、行李員", "ipa": "/ˈbelhɒp/", "trans": "bellboy", "col": "hotel bellhop", "ex": "The hotel bellhop opened the door for us.", "pos": "n."},
    "bellicose": {"def": "好戰的、好鬥的", "ipa": "/ˈbelɪkəʊs/", "trans": "warlike", "col": "bellicose mood", "ex": "He was in a bellicose mood after the argument.", "pos": "adj."},
    "belligerence": {"def": "交戰、好鬥、好戰性", "ipa": "/bəˈlɪdʒərəns/", "trans": "hostility", "col": "unprovoked belligerence", "ex": "We were surprised by his unprovoked belligerence.", "pos": "n."},
    "belligerent": {"def": "交戰中的、好戰的、交戰國、交戰者、交戰地 (戰)", "ipa": "/bəˈlɪdʒərənt/", "trans": "warring", "col": "belligerent nations", "ex": "The TWO belligerent nations finally agreed to a ceasefire.", "pos": "adj./n./adv."},
}