import json

# Level 5 Part 4: (Complexity - Diminish)
L5_PART4 = {
    "complexity": {"def": "複雜性、複雜的事物", "ipa": "/kəmˈpleksəti/", "trans": "complex", "col": "growing complexity", "ex": "The complexity of the problem surprised us.", "pos": "n."},
    "contractor": {"def": "承包商、立契約者", "ipa": "/kənˈtræktə/", "trans": "contract", "col": "building contractor, independent contractor", "ex": "The building contractor will finish the work by next month.", "pos": "n."},
    "decent": {"def": "正直的、體面的、寬厚的、像樣的、過得去的", "ipa": "/ˈdiːsnt/", "trans": "decency, decently", "col": "decent job, decent life", "ex": "Everyone deserves a decent place to live.", "pos": "adj."},
    "compliance": {"def": "承諾、答應、服從、順從、柔順", "ipa": "/kəmˈplaɪəns/", "trans": "compliant", "col": "in compliance with", "ex": "The company is in compliance with safety regulations.", "pos": "n."},
    "contradict": {"def": "駁斥、否定、同...矛盾", "ipa": "/ˌkɒntrəˈdɪkt/", "trans": "contradiction", "col": "contradict yourself", "ex": "His actions contradict his words.", "pos": "v."},
    "diminish": {"def": "減少、減小、貶低", "ipa": "/dɪˈmɪnɪʃ/", "trans": "diminished", "col": "diminish power", "ex": "The supply of natural resources is diminishing.", "pos": "v."},
    "extensive": {"def": "廣遠的、廣泛的、廣大的、大量的", "ipa": "/ɪkˈstensɪv/", "trans": "extend, extension", "col": "extensive knowledge, extensive damage", "ex": "The storm caused extensive damage to the crops.", "pos": "adj."},
    "dimension": {"def": "尺寸、尺度、維、特點、方面、給...加上尺寸、量尺寸", "ipa": "/daɪˈmenʃn/", "trans": "dimensional", "col": "three-dimensional (3D), new dimension", "ex": "The computer adds a new dimension to our lives.", "pos": "n./v."},
    "entitle": {"def": "給...權利、給...資格、給...題名、通報、給...尊稱", "ipa": "/ɪnˈtaɪtl/", "trans": "entitlement", "col": "be entitled to", "ex": "Members are entitled to a discount.", "pos": "v."},
    "exterior": {"def": "外部的、外面的、外來的、外部、外觀", "ipa": "/ɪkˈstɪəriə/", "trans": "externally", "col": "exterior design", "ex": "The exterior of the house is painted white.", "pos": "adj./n."},
    "bead": {"def": "有孔小珠、珠子、水滴、汗珠、用小珠裝飾、形成珠狀、起泡", "ipa": "/biːd/", "trans": "beaded", "col": "bead of sweat", "ex": "Beads of sweat rolled down his face.", "pos": "n./v."},
    "beam": {"def": "樑、桁、光束、射線、微笑、播送、高興、照射", "ipa": "/biːm/", "trans": "beaming", "col": "laser beam, beaming smile", "ex": "A ray of sunlight beamed through the window.", "pos": "n./v."},
    "bear": {"def": "熊、笨拙的人、持有者、忍受、承擔、生育、帶有", "ipa": "/beə/", "trans": "bearable", "col": "bear in mind, bear witness", "ex": "I can't bear the thought of losing you.", "pos": "n./v."},
    "bearable": {"def": "可忍受的、值得做的", "ipa": "/ˈbeərəbl/", "trans": "bear (動詞), unbearably", "col": "barely bearable", "ex": "The pain was barely bearable.", "pos": "adj."},
    "bearing": {"def": "關係、意義、方位、舉止、軸承、出生、生育", "ipa": "/ˈbeərɪŋ/", "trans": "bear (名詞/動詞/形容詞)", "col": "have a bearing on, get one's bearings", "ex": "His opinion has no bearing on the case.", "pos": "n."},
    "beast": {"def": "獸、畜牲、殘酷的人、討厭的人(或物)", "ipa": "/biːst/", "trans": "beastly", "col": "wild beast, beast of burden", "ex": "Victory changed him into a beast.", "pos": "n."},
    "beat": {"def": "擊、敲、擊敗、心跳、攪拌、疲累的、垂頭喪氣的、(心)跳、打、攪拌、勝過", "ipa": "/biːt/", "trans": "beatable, beating", "col": "heart beat, dead beat", "ex": "He beat the drum loudly.", "pos": "n./adj./v."},
    "beautify": {"def": "美化、修飾", "ipa": "/ˈbjuːtɪfaɪ/", "trans": "beauty, beautiful", "col": "beautify the city", "ex": "The park was beautified with colorful flowers.", "pos": "v."},
    "beckon": {"def": "召喚、示意、召引、誘惑", "ipa": "/ˈbekən/", "trans": "beckoning", "col": "beckon (to) someone", "ex": "The captain beckoned to the crew.", "pos": "v."},
    "becoming": {"def": "合適的、適宜的、相稱的", "ipa": "/bɪˈkʌmɪŋ/", "trans": "become (動詞), becomingly", "col": "becoming dress", "ex": "The blue dress is very becoming on her.", "pos": "adj."},
    "bed": {"def": "床、河床、基礎、底座、安置、嵌入、陪...睡覺", "ipa": "/bed/", "trans": "bedding", "col": "flower bed, double bed", "ex": "The children are already in bed.", "pos": "n./v."},
    "bedding": {"def": "鋪蓋、寢具、底層、基礎", "ipa": "/ˈbedɪŋ/", "trans": "bed (名詞/動詞)", "col": "clean bedding", "ex": "They took enough bedding for the camping trip.", "pos": "n."},
    "beef": {"def": "牛肉、體力、壯漢、抱怨、抱怨、訴苦、增援、加強", "ipa": "/biːf/", "trans": "beefy", "col": "beef up", "ex": "They need to beef up security at the airport.", "pos": "n./v."},
    "beep": {"def": "嗶嗶聲、嗶嗶響", "ipa": "/biːp/", "trans": "beeper", "col": "electronic beep", "ex": "The machine made a short beep.", "pos": "n./v."},
    "beeper": {"def": "呼叫器、傳呼機", "ipa": "/ˈbiːpə/", "trans": "beep (名詞/動詞)", "col": "personal beeper", "ex": "He still carries a beeper.", "pos": "n."},
    "beetle": {"def": "甲蟲、木槌、笨重的人、急忙地跑、懸垂、用木槌打、亂撞的", "ipa": "/ˈbiːtl/", "trans": "beetled", "col": "stag beetle", "ex": "A beetle crawled across the floor.", "pos": "n./v./adj."},
    "befall": {"def": "降臨於、發生於", "ipa": "/bɪˈfɔːl/", "trans": "befalling", "col": "disaster befall", "ex": "Whatever befalls, I will be with you.", "pos": "v."},
    "befitting": {"def": "適當的、合適的、相稱的", "ipa": "/bɪˈfɪtɪŋ/", "trans": "befit", "col": "befitting an occasion", "ex": "The guest was treated in a manner befitting his rank.", "pos": "adj."},
    "beforehand": {"def": "事先、提前、預先、領先的、預先準備的", "ipa": "/bɪˈfɔːhænd/", "trans": "before", "col": "prepare beforehand", "ex": "We had prepared everything beforehand.", "pos": "adv./adj."},
    "beg": {"def": "乞求、請求、乞討、請求", "ipa": "/beɡ/", "trans": "beggar", "col": "beg for, beg to do", "ex": "He begged for mercy.", "pos": "v."},
    "beggar": {"def": "乞丐、可憐蟲、使貧窮、使乾枯", "ipa": "/ˈbeɡə/", "trans": "begging", "col": "lucky beggar", "ex": "The old beggar was asking for food.", "pos": "n./v."},
    "begin": {"def": "開始、著手、創始", "ipa": "/bɪˈɡɪn/", "trans": "beginning, beginner", "col": "begin working, begin to do", "ex": "When did you begin learning English?", "pos": "v."},
    "beginner": {"def": "初學者、新手", "ipa": "/bɪˈɡɪnə/", "trans": "begin (動詞), beginning", "col": "rank beginner", "ex": "The course is suitable for beginners.", "pos": "n."},
    "beginning": {"def": "開始、開端、來源、初期的、開始的", "ipa": "/bɪˈɡɪnɪŋ/", "trans": "begin (動詞), beginner", "col": "at the beginning of, in the beginning", "ex": "In the beginning, God created the heaven and the earth.", "pos": "n./adj."},
    "behalf": {"def": "代表、利益、方面", "ipa": "/bɪˈhɑːf/", "trans": "behalf of", "col": "on behalf of", "ex": "He spoke on behalf of the committee.", "pos": "n."},
    "behave": {"def": "表現、舉止、端正、守規矩", "ipa": "/bɪˈheɪv/", "trans": "behavior", "col": "behave well, behave badly", "ex": "The children behaved very well during the ceremony.", "pos": "v."},
    "behavior/behaviour": {"def": "行為、舉止、習性、性能", "ipa": "/bɪˈheɪvjə/", "trans": "behave (動詞), behavioral", "col": "social behavior, human behavior", "ex": "The study focuses on social behavior.", "pos": "n."},
    "behind": {"def": "在後面、落後、支持、秘密地、屁股、臀部", "ipa": "/bɪˈhaɪnd/", "trans": "behindhand", "col": "left behind, behind schedule", "ex": "The project is falling behind schedule.", "pos": "prep./adv./n."},
    "behold": {"def": "注視、看、凝視、看(命令句)", "ipa": "/bɪˈhəʊld/", "trans": "beholder", "col": "lo and behold!", "ex": "Behold the glory of God.", "pos": "v./int."},
    "being": {"def": "存在、生命、生物、人", "ipa": "/ˈbiːɪŋ/", "trans": "be", "col": "human being, well-being", "ex": "He is a multi-talented human being.", "pos": "n."},
    "belie": {"def": "掩飾、與...不符、證明...為假", "ipa": "/bɪˈlaɪ/", "trans": "belied", "col": "belie expectations", "ex": "Her calm face belied her inner panic.", "pos": "v."},
    "belief": {"def": "信念、信條、相信、信賴", "ipa": "/bɪˈliːf/", "trans": "believe", "col": "religious belief, general belief", "ex": "The report confirms the general belief that the tax is unpopular.", "pos": "n."},
    "believable": {"def": "可信的、真實的", "ipa": "/bɪˈliːvəbl/", "trans": "believe, unbelievable", "col": "hardly believable", "ex": "The story was hardly believable.", "pos": "adj."},
    "believe": {"def": "相信、信任、認為", "ipa": "/bɪˈliːv/", "trans": "belief, believable", "col": "believe in, unbelievable", "ex": "I believe you.", "pos": "v."},
    "belligerent": {"def": "交戰中的、好戰的、交戰國", "ipa": "/bəˈlɪdʒərənt/", "trans": "belligerence", "col": "belligerent nation", "ex": "The two belligerent nations finally signed a peace treaty.", "pos": "adj./n."},
    "bellow": {"def": "吼叫、怒吼、咆哮、怒吼、大聲喊叫、大口吹氣", "ipa": "/ˈbeləʊ/", "trans": "bellowing", "col": "bellow with pain", "ex": "The bull suddenly started to bellow.", "pos": "n./v."},
    "belong": {"def": "應在...處、屬於、合適", "ipa": "/bɪˈlɒŋ/", "trans": "belongings", "col": "belong to", "ex": "Does this book belong to you?", "pos": "v."},
    "belongings": {"def": "財物、動產、親戚", "ipa": "/bɪˈlɒŋɪŋz/", "trans": "belong (動詞)", "col": "personal belongings", "ex": "She packed her personal belongings in a small bag.", "pos": "n."},
    "beloved": {"def": "心愛的、摯愛的人、親愛的", "ipa": "/bɪˈlʌvɪd/", "trans": "love", "col": "dearly beloved", "ex": "She is his beloved daughter.", "pos": "adj./n."},
    "bench": {"def": "板凳、長椅、法官席、工作台、法官、替補隊員席、給...以凳子、在工作中、法官的", "ipa": "/bentʃ/", "trans": "bencher", "col": "bench press, on the bench (法官執勤)", "ex": "An old man was sitting on a wooden bench.", "pos": "n./v./adj."},
    "benchmark": {"def": "基準、標竿、測量、評測、基準的", "ipa": "/ˈbentʃmɑːk/", "trans": "benchmarking", "col": "set a benchmark", "ex": "The study provides a benchmark for future research.", "pos": "n./v./adj."},
    "bend": {"def": "彎曲、偏向、屈服、彎、彎道、繩結、使彎曲、屈服、俯身 (彎)", "ipa": "/bend/", "trans": "bent", "col": "bend over, bend the rules", "ex": "He had to bend down to pick up the coin.", "pos": "n./v."},
    "beneath": {"def": "在下方、在底下、卑下地、在下方、在下層", "ipa": "/bɪˈniːθ/", "trans": "below", "col": "beneath the surface, beneath one's dignity", "ex": "The boat sank beneath the surface of the water.", "pos": "prep./adv."},
    "benediction": {"def": "祝福、祈禱、感謝禱告", "ipa": "/ˌbenɪˈdɪkʃn/", "trans": "blessing", "col": "final benediction", "ex": "The priest gave the final benediction.", "pos": "n."},
    "benefactor": {"def": "捐助者、恩人", "ipa": "/ˈbenɪfæktə/", "trans": "benefaction", "col": "unknown benefactor", "ex": "The school was built by an unknown benefactor.", "pos": "n."},
    "beneficial": {"def": "有益的、有利的、獲產權的", "ipa": "/ˌbenɪˈfɪʃl/", "trans": "benefit", "col": "beneficial to health", "ex": "A good sleep is beneficial to your health.", "pos": "adj."},
    "beneficiary": {"def": "受益人、受俸者", "ipa": "/ˌbenɪˈfɪʃieri/", "trans": "benefit", "col": "primary beneficiary", "ex": "She is the primary beneficiary of her father's will.", "pos": "n."},
    "benefit": {"def": "利益、津貼、義演、福利、有益於、獲益、受惠", "ipa": "/ˈbenɪfɪt/", "trans": "beneficial, beneficiary", "col": "mutual benefit, medical benefit, benefit from", "ex": "The project is for the mutual benefit of both countries.", "pos": "n./v."},
    "benevolence": {"def": "仁慈、善心、義款", "ipa": "/bəˈnevələns/", "trans": "benevolent", "col": "universal benevolence", "ex": "He is well known for his benevolence.", "pos": "n."},
    "benevolent": {"def": "仁慈的、親切的、慈善的", "ipa": "/bəˈnevələnt/", "trans": "benevolence (名詞)", "col": "benevolent institution", "ex": "The organization is a benevolent institution.", "pos": "adj."},
    "benign": {"def": "良性的、仁慈的、氣候溫和的", "ipa": "/bɪˈnaɪn/", "trans": "benignly", "col": "benign tumor", "ex": "Tests revealed that the tumor is benign.", "pos": "adj."},
    "bent": {"def": "彎曲的、決心的、嗜好的、彎曲、傾向、愛好、傾向地", "ipa": "/bent/", "trans": "bend (名詞/動詞)", "col": "bent on, artistic bent", "ex": "He is bent on becoming a famous actor.", "pos": "adj./n./adv."},
    "bequeath": {"def": "遺贈、留下、傳下", "ipa": "/bɪˈkwiːð/", "trans": "bequest", "col": "bequeath to", "ex": "He bequeathed his fortune to the university.", "pos": "v."},
    "bequest": {"def": "遺產、遺贈、繼承物", "ipa": "/bɪˈkwest/", "trans": "bequeath (動詞)", "col": "charitable bequest", "ex": "The museum received a large bequest from an artist.", "pos": "n."},
    "berate": {"def": "嚴責、斥責", "ipa": "/bɪˈreɪt/", "trans": "berated", "col": "berate for", "ex": "The coach berated the players for their poor performance.", "pos": "v."},
    "bereave": {"def": "剝奪、使喪失親友", "ipa": "/bɪˈriːv/", "trans": "bereavement, bereaved", "col": "bereaved family", "ex": "The war bereaved many families of their sons.", "pos": "v."},
    "bereavement": {"def": "喪失、喪友、喪子、(喪親的)痛苦", "ipa": "/bɪˈriːvmənt/", "trans": "bereave (動詞)", "col": "recent bereavement", "ex": "They are still suffering from a recent bereavement.", "pos": "n."},
    "berry": {"def": "漿果、一粒果實、乾果、採漿果", "ipa": "/ˈberi/", "trans": "berries", "col": "wild berry, strawberry", "ex": "The birds are eating the red berries.", "pos": "n./v."},
    "berserk": {"def": "狂暴的、瘋狂的、狂暴者、狂怒地", "ipa": "/bəˈsɜːk/", "trans": "berserker", "col": "go berserk", "ex": "He went berserk when he heard the news.", "pos": "adj./n./adv."},
    "berth": {"def": "鋪位、臥鋪、錨位、職位、停泊、提供鋪位、停泊", "ipa": "/bɜːθ/", "trans": "berths", "col": "give a wide berth", "ex": "We should give that problem a wide berth.", "pos": "n./v."},
    "beseech": {"def": "哀求、懇求", "ipa": "/bɪˈsiːtʃ/", "trans": "beseeching", "col": "beseech someone to do", "ex": "I beseech you to help me.", "pos": "v."},
    "beset": {"def": "包圍、困擾、鑲、飾", "ipa": "/bɪˈset/", "trans": "besetting", "col": "beset with difficulties", "ex": "The project is beset with difficulties.", "pos": "v."},
    "beside": {"def": "在旁邊、除...之外、與...相比、在...旁邊", "ipa": "/bɪˈsaɪd/", "trans": "besides", "col": "beside the point, beside oneself", "ex": "She sat down beside him.", "pos": "prep./adv."},
    "besides": {"def": "此外、而且、除...之外、此外、而且、在...旁邊、除了", "ipa": "/bɪˈsaɪdz/", "trans": "beside", "col": "besides, additionally", "ex": "Besides, we don't have enough money for the trip.", "pos": "adv./prep."},
    "besiege": {"def": "圍攻、包圍、煩擾", "ipa": "/bɪˈsiːdʒ/", "trans": "besieged", "col": "besiege with questions", "ex": "The politician was besieged with questions by the reporters.", "pos": "v."},
    "best": {"def": "最好的、最高水準的、最出色的人、最好地、最高水準地、打敗、優於、最好的人", "ipa": "/best/", "trans": "better, good", "col": "best friend, at best, make the best of", "ex": "She is my best friend.", "pos": "adj./n./adv./v."},
    "bestow": {"def": "授予、贈與、利用、貯存", "ipa": "/bɪˈstəʊ/", "trans": "bestowal", "col": "bestow on, bestow upon", "ex": "The honor was bestowed on him for his contribution to science.", "pos": "v."},
    "betray": {"def": "背叛、出賣、洩漏、背棄、暴露", "ipa": "/bɪˈtreɪ/", "trans": "betrayal, betrayer", "col": "betray a secret, betray trust", "ex": "He betrayed his country by selling secrets to the enemy.", "pos": "v."},
    "betrayal": {"def": "背叛、出賣、洩漏", "ipa": "/bɪˈtreɪəl/", "trans": "betray (動詞)", "col": "personal betrayal", "ex": "The news of his betrayal came as a shock to everyone.", "pos": "n."},
    "beverage": {"def": "飲料", "ipa": "/ˈbevərɪdʒ/", "trans": "drink", "col": "alcoholic beverage, non-alcoholic beverage", "ex": "Beer is a popular alcoholic beverage.", "pos": "n."},
    "beware": {"def": "當心、注意、提防", "ipa": "/bɪˈweə/", "trans": "bewaring", "col": "beware of", "ex": "Beware of pickpockets.", "pos": "v."},
    "bewilder": {"def": "使迷惑、使難住", "ipa": "/bɪˈwɪldə/", "trans": "bewilderment", "col": "bewildered look", "ex": "The sudden change of plans bewildered the students.", "pos": "v."},
    "bewilderment": {"def": "迷惑、混亂、不知所措", "ipa": "/bɪˈwɪldəmənt/", "trans": "bewilder (動詞)", "col": "in bewilderment", "ex": "He stared at them in bewilderment.", "pos": "n."},
    "bias": {"def": "偏見、偏袒、斜紋、使存偏見、偏見、偏心的、斜的、斜向地", "ipa": "/ˈbaɪəs/", "trans": "biased", "col": "racial bias, gender bias", "ex": "The study is free from racial bias.", "pos": "n./v./adj./adv."},
    "bibliography": {"def": "參考書目、文獻學", "ipa": "/ˌbɪbliˈɒɡrəfi/", "trans": "bibliographer", "col": "annotated bibliography", "ex": "The report includes an extensive bibliography.", "pos": "n."},
    "bicentennial": {"def": "二百週年的、二百週年紀念", "ipa": "/ˌbaɪsenˈteniəl/", "trans": "centennial", "col": "bicentennial celebration", "ex": "The city celebrated its bicentennial last year.", "pos": "adj./n."},
    "bid": {"def": "出價、努力、企圖、命令、吩咐、投標、吩咐、出(價)", "ipa": "/bɪd/", "trans": "bidding, bidder", "col": "make a bid, bid for", "ex": "He made a bid for the painting at the auction.", "pos": "n./v."},
}

with open("batch_l5_p4.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART4, f, ensure_ascii=False, indent=2)
