import json

# Level 6 Part 29: (Bellow - Beneficial)
L6_PART29 = {
    "bellow": {"def": "吼叫、怒吼、大聲喊、(風等)呼嘯、吼叫的人 (或物)、吼叫地 (吼)", "ipa": "/ˈbeləʊ/", "trans": "roar", "col": "bellow with laughter, bellow with pain", "ex": "He bellowed with pain when his toe was stubbed.", "pos": "v./n./adv."},
    "bellows": {"def": "風箱、口琴、(俚)肺 (單數/常用複數)", "ipa": "/ˈbeləʊz/", "trans": "air pump", "col": "pair of bellows", "ex": "The blacksmith used a pair of bellows to blow the fire.", "pos": "n."},
    "belly": {"def": "肚子、腹部、胃、膨脹、腹狀的、腹部的人物、腹部地 (腹)", "ipa": "/ˈbeli/", "trans": "bellies", "col": "pot belly, belly dance, belly ache", "ex": "He lay on his belly in the sun.", "pos": "n./v./adj./adv."},
    "bellyache": {"def": "腹痛、胃痛、(俚)抱怨、牢騷", "ipa": "/ˈbelieɪk/", "trans": "stomach ache", "col": "stop bellyaching", "ex": "Stop bellyaching about the food!", "pos": "n./v."},
    "bellyful": {"def": "滿腹、過量、厭煩、受夠了的人 (或物) (受夠)", "ipa": "/ˈbelifʊl/", "trans": "enough", "col": "have a bellyful of (受夠了)", "ex": "I've had a bellyful of your lies.", "pos": "n./adv."},
    "belong": {"def": "屬於、歸屬、合適 (單數)", "ipa": "/bɪˈlɒŋ/", "trans": "belonging", "col": "belong to, belong in (應該在)", "ex": "Where do these books belong?", "pos": "v."},
    "belongings": {"def": "財產、所有物、親屬 (複數)", "ipa": "/bɪˈlɒŋɪŋz/", "trans": "possessions", "col": "personal belongings", "ex": "Please take your personal belongings with you.", "pos": "n."},
    "beloved": {"def": "心愛的、心愛的人、在愛地 (愛)", "ipa": "/bɪˈlʌvɪd/", "trans": "dearest", "col": "beloved wife, dearly beloved", "ex": "He lost his beloved wife last year.", "pos": "adj./n./adv."},
    "below": {"def": "在...下面、在下方、落後於、在下面地 (下)", "ipa": "/bɪˈləʊ/", "trans": "under", "col": "see below, below zero, below average", "ex": "The valley expanded below us.", "pos": "prep./adv./adj./n."},
    "belt": {"def": "皮帶、腰帶、地帶、猛擊、用帶束、猛擊、帶狀的、帶地 (帶)", "ipa": "/belt/", "trans": "belts", "col": "seat belt, black belt, conveyor belt, asteroid belt", "ex": "He tightened his belt.", "pos": "n./v./adj./adv."},
    "beluga": {"def": "白鯨、鰉魚", "ipa": "/bəˈluːɡə/", "trans": "white whale", "col": "beluga whale", "ex": "The beluga whale is known for its white color.", "pos": "n."},
    "bemoan": {"def": "哀嘆、為...慟哭、抱怨", "ipa": "/bɪˈməʊn/", "trans": "lament", "col": "bemoan one's fate", "ex": "He sat there bemoaning his fate.", "pos": "v."},
    "bemuse": {"def": "使困惑、使發呆、使著迷", "ipa": "/bɪˈmjuːz/", "trans": "confuse", "col": "bemused look", "ex": "There was a bemused look on her face.", "pos": "v."},
    "bemusedly": {"def": "困惑地、發呆地", "ipa": "/bɪˈmjuːzədli/", "trans": "bemused (形容詞/動詞)", "col": "shook head bemusedly", "ex": "He shook his head bemusedly.", "pos": "adv."},
    "bench": {"def": "長凳、工作臺、法官席、板凳、坐在凳上、長凳的人物、在凳上地 (凳)", "ipa": "/bentʃ/", "trans": "benches", "col": "park bench, work bench, back bench (後座議員), bench press (臥推)", "ex": "He was sitting on a park bench.", "pos": "n./v./adv."},
    "benchmark": {"def": "基準、基準點、基準的人物、基準地 (基準)", "ipa": "/ˈbentʃmɑːk/", "trans": "standard", "col": "industry benchmark", "ex": "The new product sets an industrial benchmark for quality.", "pos": "n./v./adv."},
    "bend": {"def": "彎曲、屈服、使彎曲、轉向、彎曲、轉向、彎曲地 (彎)", "ipa": "/bend/", "trans": "bending, bent", "col": "bend over, bend the rules, bend to one's will, round the bend (發瘋)", "ex": "The river makes a sharp bend here.", "pos": "v./n./adv."},
    "bending": {"def": "彎曲的、屈服的、轉向的人 (或物) (彎)", "ipa": "/ˈbendɪŋ/", "trans": "bend (動詞/名詞/副詞)", "col": "bending moment (彎矩)", "ex": "The steel rod was bending under the weight.", "pos": "adj./adv."},
    "beneath": {"def": "在...下面、在下方、不值得、在下面地 (下)", "ipa": "/bɪˈniːθ/", "trans": "below", "col": "beneath notice, beneath one's dignity", "ex": "They sat beneath a large oak tree.", "pos": "prep./adv./adj./n."},
    "benediction": {"def": "祝福、賜福、(天主教)聖體降福 (單數)", "ipa": "/ˌbenɪˈdɪkʃn/", "trans": "blessing", "col": "final benediction", "ex": "The priest gave the final benediction.", "pos": "n."},
    "benefaction": {"def": "善行、捐助、捐贈物", "ipa": "/ˌbenɪˈfækʃn/", "trans": "donation", "col": "charitable benefaction", "ex": "The library was built with a large charitable benefaction.", "pos": "n."},
    "benefactor": {"def": "恩人、捐助者、施主 (單數)", "ipa": "/ˈbenɪfæktə/", "trans": "benefactors (複數)", "col": "anonymous benefactor", "ex": "An anonymous benefactor donated $1 million to the school.", "pos": "n."},
    "benefactress": {"def": "女恩人、女施主", "ipa": "/ˈbenɪfæktrəs/", "trans": "benefactor", "col": "wealthy benefactress", "ex": "The museum was founded by a wealthy benefactress.", "pos": "n."},
    "benefice": {"def": "(教會)俸祿、領俸祿的職位", "ipa": "/ˈbenɪfɪs/", "trans": "living", "col": "church benefice", "ex": "The priest was appointed to a local church benefice.", "pos": "n."},
    "beneficence": {"def": "善行、仁慈、慈善", "ipa": "/bəˈnefɪsns/", "trans": "charity", "col": "public beneficence", "ex": "The hospital is a monument to the public beneficence.", "pos": "n."},
    "beneficent": {"def": "仁慈的、慈善的、行善的", "ipa": "/bəˈnefɪsnt/", "trans": "kind", "col": "beneficent rule", "ex": "The country prospered under his beneficent rule.", "pos": "adj."},
    "beneficial": {"def": "有益的、有利的、(法)受益的、有益地 (有益)", "ipa": "/ˌbenɪˈfɪʃl/", "trans": "beneficially, benefit", "col": "mutually beneficial, beneficial effect", "ex": "Regular exercise is beneficial to your health.", "pos": "adj./adv."},
}