import json

# Level 3 Part 2: (Adjust - Any)
L3_PART2 = {
    "adjust": {"def": "調整、適應、校正", "ipa": "/əˈdʒʌst/", "trans": "adjustment, adjustable", "col": "adjust to, adjust focus", "ex": "It took him a while to adjust to his new job.", "pos": "v."},
    "adjustment": {"def": "調整、調節、適應", "ipa": "/əˈdʒʌstmənt/", "trans": "adjust (動詞)", "col": "make an adjustment", "ex": "The company made some adjustments to its prices.", "pos": "n."},
    "administer": {"def": "管理、治理、執行", "ipa": "/ədˈmɪnɪstə/", "trans": "administration, administrator", "col": "administer a drug", "ex": "The fund is administered by the government.", "pos": "v."},
    "administration": {"def": "行政、管理、政府（機關）", "ipa": "/ədˌmɪnɪˈstreɪʃn/", "trans": "administer (動詞), administrative", "col": "business administration", "ex": "The new administration is committed to change.", "pos": "n."},
    "administrative": {"def": "行政的、管理的", "ipa": "/ədˈmɪnɪstrətɪv/", "trans": "administration (名詞)", "col": "administrative staff", "ex": "She has an administrative role in the company.", "pos": "adj."},
    "administrator": {"def": "管理人、行政官", "ipa": "/ədˈmɪnɪstreɪtə/", "trans": "administer (動詞)", "col": "system administrator", "ex": "He is the administrator of a large hospital.", "pos": "n."},
    "admirable": {"def": "令人欽佩的、極好的", "ipa": "/ˈædmərəbl/", "trans": "admire (動詞), admirably", "col": "admirable quality", "ex": "Her courage is truly admirable.", "pos": "adj."},
    "admiral": {"def": "海軍上將、艦隊司令", "ipa": "/ˈædmərəl/", "trans": "admirals", "col": "vice admiral", "ex": "The admiral ordered the fleet to attack.", "pos": "n."},
    "admire": {"def": "欽佩、欣賞、讚賞", "ipa": "/ədˈmaɪə/", "trans": "admiration, admirer", "col": "admire someone for", "ex": "I really admire your work ethic.", "pos": "v."},
    "admission": {"def": "進入權、門票、承認、坦白", "ipa": "/ədˈmɪʃn/", "trans": "admit (動詞)", "col": "admission fee, gain admission", "ex": "The jury took his silence as an admission of guilt.", "pos": "n."},
    "admit": {"def": "承認、准許進入", "ipa": "/ədˈmɪt/", "trans": "admission, admittedly", "col": "admit defeat, admit to", "ex": "He admitted that he had made a mistake.", "pos": "v."},
    "adolescence": {"def": "青春期", "ipa": "/ˌædəˈlesns/", "trans": "adolescent", "col": "troubled adolescence", "ex": "He had a difficult adolescence.", "pos": "n."},
    "adolescent": {"def": "青春期的、青少年", "ipa": "/ˌædəˈlesnt/", "trans": "adolescence (名詞)", "col": "adolescent problems", "ex": "Adolescents often rebel against their parents.", "pos": "adj./n."},
    "adopt": {"def": "採取、採納、收養", "ipa": "/əˈdɒpt/", "trans": "adoption, adopted", "col": "adopt a child, adopt a plan", "ex": "They decided to adopt a baby boy.", "pos": "v."},
    "adoption": {"def": "採納、收養", "ipa": "/əˈdɒpʃn/", "trans": "adopt (動詞)", "col": "legal adoption", "ex": "The adoption of the new technology was a success.", "pos": "n."},
    "adore": {"def": "崇拜、熱愛", "ipa": "/əˈdɔː/", "trans": "adorable", "col": "adore doing", "ex": "I simply adore Italian food.", "pos": "v."},
    "adult": {"def": "成年的、成熟的、成年人", "ipa": "/ˈædʌlt/", "trans": "adulthood", "col": "young adult", "ex": "He's an adult now and can make his own decisions.", "pos": "adj./n."},
    "advance": {"def": "前進、進步、進展、預付、前進、提前的、預先的", "ipa": "/ədˈvɑːns/", "trans": "advanced, advancement", "col": "in advance, technological advance", "ex": "Modern medicine has made great advances.", "pos": "v./n./adj."},
    "advanced": {"def": "高級的、先進的", "ipa": "/ədˈvɑːnst/", "trans": "advance (名詞/動詞)", "col": "advanced level", "ex": "The company uses advanced technology.", "pos": "adj."},
    "advantage": {"def": "優勢、利益、佔優勢、有利於", "ipa": "/ədˈvɑːntɪdʒ/", "trans": "advantageous", "col": "take advantage of", "ex": "Learning a second language is a big advantage.", "pos": "n./v."},
    "adventure": {"def": "冒險、冒險活動、冒險、投機", "ipa": "/ədˈventʃə/", "trans": "adventurous, adventurer", "col": "outdoor adventure", "ex": "They had many adventures during their trip.", "pos": "n./v."},
    "adventurous": {"def": "冒險的、創新的", "ipa": "/ədˈventʃərəs/", "trans": "adventure (名詞)", "col": "adventurous spirit", "ex": "He is an adventurous traveler.", "pos": "adj."},
    "adverb": {"def": "副詞", "ipa": "/ˈædvɜːb/", "trans": "adverbial", "col": "adverb of manner", "ex": "'Quickly' is an adverb.", "pos": "n."},
    "adverse": {"def": "不利的、相反的、有害的", "ipa": "/ˈædvɜːs/", "trans": "adversely, adversity", "col": "adverse weather conditions", "ex": "The drug has some adverse side effects.", "pos": "adj."},
    "adversity": {"def": "逆境、不幸", "ipa": "/ədˈvɜːsəti/", "trans": "adverse (形容詞)", "col": "overcome adversity", "ex": "He showed great courage in the face of adversity.", "pos": "n."},
    "advertise": {"def": "做廣告、慶祝、宣揚", "ipa": "/ˈædvətaɪz/", "trans": "advertisement, advertiser", "col": "advertise for", "ex": "The company is advertising for new staff.", "pos": "v."},
    "advertisement/ad": {"def": "廣告、公告", "ipa": "/ədˈvɜːtɪsmənt/", "trans": "advertise (動詞)", "col": "classified advertisement", "ex": "I saw an advertisement for the job in the paper.", "pos": "n."},
    "advertiser": {"def": "廣告商", "ipa": "/ˈædvətaɪzə/", "trans": "advertise (動詞)", "col": "leading advertiser", "ex": "The magazine attracts many national advertisers.", "pos": "n."},
    "advertising": {"def": "廣告（業）、廣告費", "ipa": "/ˈædvətaɪzɪŋ/", "trans": "advertise (動詞)", "col": "advertising agency", "ex": "She works in advertising.", "pos": "n."},
    "advice": {"def": "建議、勸告", "ipa": "/ədˈvaɪs/", "trans": "advise (動詞)", "col": "take advice, give advice", "ex": "Can I give you some advice?", "pos": "n."},
    "advise": {"def": "勸告、建議、通知", "ipa": "/ədˈvaɪz/", "trans": "advice (名詞), advisor", "col": "advise someone against", "ex": "I would advise you to wait.", "pos": "v."},
    "adviser/advisor": {"def": "顧問、指導老師", "ipa": "/ədˈvaɪzə/", "trans": "advise (動詞)", "col": "financial adviser", "ex": "He is a senior government adviser.", "pos": "n."},
    "advocacy": {"def": "擁護、主張、訴護", "ipa": "/ˈædvəkəsi/", "trans": "advocate", "col": "patient advocacy", "ex": "Her advocacy for women's rights is well-known.", "pos": "n."},
    "advocate": {"def": "擁護者、提倡者、主張、擁護", "ipa": "/ˈædvəkət/ (n.) /ˈædvəkeɪt/ (v.)", "trans": "advocacy", "col": "advocate of free speech", "ex": "He is an advocate of non-violence.", "pos": "n./v."},
    "aerobic": {"def": "有氧的、需氧的、有氧運動", "ipa": "/eəˈrəʊbɪk/", "trans": "aerobics", "col": "aerobic exercise", "ex": "Cycling is a good aerobic exercise.", "pos": "adj./n."},
    "aerobics": {"def": "有氧健身操", "ipa": "/eəˈrəʊbɪks/", "trans": "aerobic (形容詞)", "col": "do aerobics", "ex": "I do aerobics twice a week.", "pos": "n."},
    "aesthetic": {"def": "美學的、審美的、美感、審美觀", "ipa": "/iːsˈθetɪk/", "trans": "aesthetics", "col": "aesthetic appeal", "ex": "The building has great aesthetic value.", "pos": "adj./n."},
    "affair": {"def": "事務、事件、私事", "ipa": "/əˈfeə/", "trans": "affairs", "col": "current affairs, foreign affairs", "ex": "The whole affair was a complete disaster.", "pos": "n."},
    "affect": {"def": "影響、感動、假裝", "ipa": "/əˈfekt/", "trans": "affection, affected", "col": "affect decision", "ex": "Smoking affects your health.", "pos": "v."},
    "affection": {"def": "慈愛、喜愛、感情", "ipa": "/əˈfekʃn/", "trans": "affect (動詞), affectionate", "col": "gain someone's affection", "ex": "I have great affection for my hometown.", "pos": "n."},
    "affectionate": {"def": "慈愛的、親切的", "ipa": "/əˈfekʃənət/", "trans": "affection (名詞), affectionately", "col": "affectionate letter", "ex": "He is a very affectionate child.", "pos": "adj."},
    "affiliate": {"def": "子公司、分會、使附屬於、接納", "ipa": "/əˈfɪlieɪt/", "trans": "affiliation", "col": "affiliate with", "ex": "The company is affiliated with a larger corporation.", "pos": "n./v."},
    "affirm": {"def": "斷言、申明、證實", "ipa": "/əˈfɜːm/", "trans": "affirmation", "col": "affirm his belief", "ex": "He affirmed his commitment to the project.", "pos": "v."},
    "afford": {"def": "買得起、負擔得起、提供", "ipa": "/əˈfɔːd/", "trans": "affordable", "col": "can afford to", "ex": "I can't afford to buy a new car.", "pos": "v."},
    "affordable": {"def": "負擔得起的、便宜的", "ipa": "/əˈfɔːdəbl/", "trans": "afford (動詞)", "col": "affordable housing", "ex": "The goal is to provide affordable healthcare.", "pos": "adj."},
    "afraid": {"def": "害怕的、憂慮的", "ipa": "/əˈfreɪd/", "trans": "fear", "col": "be afraid of", "ex": "Don't be afraid of the dog.", "pos": "adj."},
    "after": {"def": "在...之後、追趕、在後、後來、以後的", "ipa": "/ˈɑːftə/", "trans": "before", "col": "after all, look after, take after", "ex": "Let's meet after school.", "pos": "prep./adv./adj."},
    "aftermath": {"def": "（災難等的）後果、餘波", "ipa": "/ˈɑːftəmæθ/", "trans": "after", "col": "in the aftermath of", "ex": "The country is still struggling in the aftermath of the war.", "pos": "n."},
    "afternoon": {"def": "下午、午後、下午的", "ipa": "/ˌɑːftəˈnuːn/", "trans": "afternoons", "col": "this afternoon", "ex": "I'm busy this afternoon.", "pos": "n./adj."},
    "afterward(s)": {"def": "後來、以後", "ipa": "/ˈɑːftəwəd/", "trans": "following", "col": "shortly afterwards", "ex": "We had dinner and went to the movie afterwards.", "pos": "adv."},
    "again": {"def": "再次、重新、此外", "ipa": "/əˈɡen/", "trans": "repeatedly", "col": "again and again, once again", "ex": "Try it again.", "pos": "adv."},
    "against": {"def": "反對、倚靠、針對、緊貼", "ipa": "/əˈɡenst/", "trans": "anti", "col": "against the law, against the wall", "ex": "He is against the plan.", "pos": "prep."},
    "age": {"def": "年齡、時代、使變老、變老", "ipa": "/eɪdʒ/", "trans": "aged, aging", "col": "at the age of, middle age", "ex": "What's your age?", "pos": "n./v."},
    "agency": {"def": "代理机构、代理、特工、作用", "ipa": "/ˈeɪdʒənsi/", "trans": "agent", "col": "travel agency, CIA", "ex": "I found a job through a recruitment agency.", "pos": "n."},
    "agenda": {"def": "議事日程、待辦事項", "ipa": "/əˈdʒendə/", "trans": "agendas", "col": "on the agenda", "ex": "The next item on the agenda is the budget.", "pos": "n."},
    "agent": {"def": "代理人、經理人、原動力", "ipa": "/ˈeɪdʒənt/", "trans": "agency", "col": "secret agent, real estate agent", "ex": "He is an agent for a famous actor.", "pos": "n."},
    "aggression": {"def": "侵略、挑釁、攻擊性", "ipa": "/əˈɡreʃn/", "trans": "aggressive, aggressor", "col": "unprovoked aggression", "ex": "The country was accused of aggression against its neighbor.", "pos": "n."},
    "aggressive": {"def": "侵略性的、好鬥的、有進取心的", "ipa": "/əˈɡresɪv/", "trans": "aggression (名詞), aggressively", "col": "aggressive behavior", "ex": "He has an aggressive management style.", "pos": "adj."},
    "agile": {"def": "敏捷的、靈活的", "ipa": "/ˈædʒaɪl/", "trans": "agility", "col": "agile mind", "ex": "Cats are very agile animals.", "pos": "adj."},
    "agility": {"def": "敏捷、靈活力", "ipa": "/əˈdʒɪləti/", "trans": "agile (形容詞)", "col": "mental agility", "ex": "He showed great agility on the football field.", "pos": "n."},
    "aging": {"def": "老化的、陳舊的、老化、 aging", "ipa": "/ˈeɪdʒɪŋ/", "trans": "age (名詞/動詞)", "col": "aging population", "ex": "The company is facing the problem of an aging workforce.", "pos": "adj./n."},
    "ago": {"def": "以前、之前", "ipa": "/əˈɡəʊ/", "trans": "back", "col": "a long time ago", "ex": "I met him two years ago.", "pos": "adv."},
    "agony": {"def": "痛苦、苦惱", "ipa": "/ˈæɡəni/", "trans": "agonizing", "col": "in agony", "ex": "He was screaming in agony.", "pos": "n."},
    "agree": {"def": "同意、商定、符合", "ipa": "/əˈɡriː/", "trans": "agreement", "col": "agree with, agree on", "ex": "I agree with your opinion.", "pos": "v."},
    "agreeable": {"def": "令人愉快的、宜人的、同意的", "ipa": "/əˈɡriːəbl/", "trans": "agree (動詞), agreeably", "col": "agreeable personality", "ex": "We spent an agreeable afternoon at the park.", "pos": "adj."},
    "agreement": {"def": "同意、協議、合同、協和", "ipa": "/əˈɡriːmənt/", "trans": "agree (動詞)", "col": "sign an agreement, in agreement", "ex": "The two countries signed a trade agreement.", "pos": "n."},
    "agriculture": {"def": "農業、農學", "ipa": "/ˈæɡrɪkʌltʃə/", "trans": "agricultural", "col": "modern agriculture", "ex": "Agriculture is the main industry in the region.", "pos": "n."},
    "ahead": {"def": "在前面、提早、領先地", "ipa": "/əˈhed/", "trans": "forward", "col": "ahead of time, go ahead", "ex": "The road ahead is blocked.", "pos": "adv./adj."},
    "aid": {"def": "援助、輔助、援助物、幫助、援助", "ipa": "/eɪd/", "trans": "aider, aiding", "col": "first aid, financial aid", "ex": "Food aid was sent to the region.", "pos": "n./v."},
    "aide": {"def": "助手、副官", "ipa": "/eɪd/", "trans": "aides", "col": "presidential aide", "ex": "He is a close aide to the prime minister.", "pos": "n."},
    "AIDS": {"def": "愛滋病", "ipa": "/eɪdz/", "trans": "HIV", "col": "suffer from AIDS", "ex": "Doctors are searching for a cure for AIDS.", "pos": "n."},
    "aim": {"def": "目標、目的、瞄準、對準、瞄準、打算", "ipa": "/eɪm/", "trans": "aimless", "col": "aim high, take aim", "ex": "What is the aim of this project?", "pos": "n./v."},
    "air": {"def": "空氣、天空、樣子、公諸於世、晾、播出", "ipa": "/eə/", "trans": "airy, airline", "col": "on the air, by air, air force", "ex": "I need some fresh air.", "pos": "n./v."},
    "aircraft": {"def": "飛機、飛行器", "ipa": "/ˈeəkrɑːft/", "trans": "aircraft carrier", "col": "military aircraft", "ex": "The aircraft landed safely.", "pos": "n."},
    "airfare": {"def": "飛機票價", "ipa": "/ˈeəfeə/", "trans": "airfares", "col": "cheap airfare", "ex": "The airfare to London is very expensive.", "pos": "n."},
    "airline": {"def": "航空公司、航線", "ipa": "/ˈeəlaɪn/", "trans": "airliner", "col": "national airline", "ex": "Which airline are you flying with?", "pos": "n."},
    "airliner": {"def": "定期班機、大型客機", "ipa": "/ˈeəlaɪnə/", "trans": "airline (名詞)", "col": "commercial airliner", "ex": "The airliner was forced to make an emergency landing.", "pos": "n."},
    "airport": {"def": "機場、航空港", "ipa": "/ˈeəpɔːt/", "trans": "airports", "col": "at the airport", "ex": "I'll meet you at the airport.", "pos": "n."},
    "airtight": {"def": "密封的、無懈可擊的", "ipa": "/ˈeətaɪt/", "trans": "air", "col": "airtight container", "ex": "Keep the food in an airtight container.", "pos": "adj."},
    "airway": {"def": "呼吸道、航線", "ipa": "/ˈeəweɪ/", "trans": "airways", "col": "block the airway", "ex": "British Airways is a famous airline.", "pos": "n."},
    "aisle": {"def": "走道、翼廊", "ipa": "/aɪl/", "trans": "aisles", "col": "aisle seat", "ex": "Would you like a window seat or an aisle seat?", "pos": "n."},
    "alarm": {"def": "警報（器）、恐慌、使恐慌、裝警報器、報警", "ipa": "/əˈlɑːm/", "trans": "alarmed, alarming", "col": "alarm clock, set off an alarm, fire alarm", "ex": "The fire alarm went off at midnight.", "pos": "n./v."},
    "albeit": {"def": "雖然、儘管", "ipa": "/ˌɔːlˈbiːɪt/", "trans": "although", "col": "albeit small", "ex": "He accepted the job, albeit with some hesitation.", "pos": "conj."},
    "album": {"def": "相簿、唱片、專輯", "ipa": "/ˈælbəm/", "trans": "albums", "col": "photo album, music album", "ex": "I put the photos in an album.", "pos": "n."},
    "alcohol": {"def": "酒精、酒", "ipa": "/ˈælkəhɒl/", "trans": "alcoholic", "col": "alcohol abuse", "ex": "The drink contains 5% alcohol.", "pos": "n."},
    "alcoholic": {"def": "含酒精的、酗酒的、酗酒者", "ipa": "/ˌælkəˈhɒlɪk/", "trans": "alcohol (名詞)", "col": "alcoholic beverage", "ex": "Beer is an alcoholic drink.", "pos": "adj./n."},
    "alert": {"def": "警覺的、留心的、警報、警報狀態、向...報警、使提防", "ipa": "/əˈlɜːt/", "trans": "alertness", "col": "stay alert, red alert", "ex": "The police are on alert for any trouble.", "pos": "adj./n./v."},
    "algebra": {"def": "代數", "ipa": "/ˈældʒɪbrə/", "trans": "algebraic", "col": "linear algebra", "ex": "Algebra was my favorite subject in school.", "pos": "n."},
    "alien": {"def": "外國的、異己的、外星人、外國人", "ipa": "/ˈeɪliən/", "trans": "alienate", "col": "illegal alien", "ex": "The culture was completely alien to him.", "pos": "adj./n."},
    "alienate": {"def": "使疏遠、轉讓", "ipa": "/ˈeɪliəneɪt/", "trans": "alienation", "col": "alienate someone from", "ex": "His critical remarks alienated his friends.", "pos": "v."},
    "alike": {"def": "相似地、同樣地、相似的", "ipa": "/əˈlaɪk/", "trans": "like", "col": "look alike", "ex": "The two brothers look very much alike.", "pos": "adv./adj."},
    "alive": {"def": "活著的、活躍的", "ipa": "/əˈlaɪv/", "trans": "life, live", "col": "keep alive, dead or alive", "ex": "The tradition is still very much alive today.", "pos": "adj."},
    "all": {"def": "所有的、全部的、一切、全部、完全地", "ipa": "/ɔːl/", "trans": "altogether", "col": "all over, at all, all right", "ex": "All students must be on time.", "pos": "adj./pron./adv./n."},
    "allay": {"def": "減輕、使平息", "ipa": "/əˈleɪ/", "trans": "alleviate", "col": "allay fears", "ex": "The government is trying to allay public fears about the economy.", "pos": "v."},
    "allegation": {"def": "指控、斷言", "ipa": "/ˌæləˈɡeɪʃn/", "trans": "allege (動詞)", "col": "deny allegations", "ex": "The allegations against the judge proved to be false.", "pos": "n."},
    "allege": {"def": "斷言、宣稱", "ipa": "/əˈledʒ/", "trans": "allegation", "col": "it is alleged that", "ex": "He is alleged to have stolen the money.", "pos": "v."},
    "allergic": {"def": "過敏的、反感的", "ipa": "/əˈlɜːdʒɪk/", "trans": "allergy", "col": "allergic to", "ex": "I am allergic to cat fur.", "pos": "adj."},
    "allergy": {"def": "過敏、反感", "ipa": "/ˈælədʒi/", "trans": "allergic (形容詞)", "col": "food allergy", "ex": "Many people have an allergy to peanuts.", "pos": "n."},
    "alliance": {"def": "同盟、聯盟", "ipa": "/əˈlaɪəns/", "trans": "allied, ally", "col": "strategic alliance", "ex": "The two countries formed a military alliance.", "pos": "n."},
    "alligator": {"def": "短吻鱷", "ipa": "/ˈælɪɡeɪtə/", "trans": "crocodile", "col": "American alligator", "ex": "Alligators live in swamps and rivers.", "pos": "n."},
    "allocate": {"def": "分配、撥給", "ipa": "/ˈæləkeɪt/", "trans": "allocation", "col": "allocate resources", "ex": "The government has allocated more money for education.", "pos": "v."},
    "allow": {"def": "准許、允許、承認", "ipa": "/əˈlaʊ/", "trans": "allowance", "col": "allow for, allow someone to do", "ex": "Smoking is not allowed in the building.", "pos": "v."},
    "allowance": {"def": "津貼、零用錢、限額", "ipa": "/əˈlaʊəns/", "trans": "allow (動詞)", "col": "baggage allowance, pocket money", "ex": "She gets a weekly allowance from her parents.", "pos": "n."},
}

with open("batch_l3_p2.json", "w", encoding="utf-8") as f:
    json.dump(L3_PART2, f, ensure_ascii=False, indent=2)
