import json

# Level 6 Part 21: (Barbed - Barrel)
L6_PART21 = {
    "barbed": {"def": "有刺的、有倒鉤的、諷刺的", "ipa": "/bɑːbd/", "trans": "barb (名詞/動詞/副詞)", "col": "barbed wire, barbed remark", "ex": "The fence was topped with barbed wire.", "pos": "adj."},
    "barbel": {"def": "觸鬚 (魚的)、(魚)觸鬚", "ipa": "/ˈbɑːbl/", "trans": "barbels", "col": "long barbel", "ex": "The catfish has long barbels around its mouth.", "pos": "n."},
    "barbell": {"def": "槓鈴", "ipa": "/ˈbɑːbel/", "trans": "weights", "col": "lift a barbell", "ex": "He lifted the heavy barbell with both hands.", "pos": "n."},
    "barber": {"def": "理髮師、理髮店、理髮、理髮的人 (或物)、理髮地 (理髮)", "ipa": "/ˈbɑːbə/", "trans": "barbers", "col": "local barber, barber shop, lady barber", "ex": "He is going to the local barber for a haircut.", "pos": "n./v./adv."},
    "barber-shop": {"def": "理髮店", "ipa": "/ˈbɑːbəʃɒp/", "trans": "hair salon", "col": "old-fashioned barber-shop", "ex": "He prefers the old-fashioned barber-shop in the village.", "pos": "n."},
    "barbiturate": {"def": "巴比妥鹽、鎮靜劑", "ipa": "/bɑːˈbɪtʃərət/", "trans": "sedative", "col": "overdose on barbiturates", "ex": "The drug is a type of barbiturate.", "pos": "n."},
    "barcode": {"def": "條碼", "ipa": "/ˈbɑːkəʊd/", "trans": "barcodes", "col": "scan the barcode", "ex": "The cashier scanned the barcode on the package.", "pos": "n."},
    "bard": {"def": "吟遊詩人、詩人、敘事詩、(古)吟遊詩人的人物、吟遊地 (詩人)", "ipa": "/bɑːd/", "trans": "bards", "col": "the Bard (莎士比亞), Gaelic bard", "ex": "Shakespeare is often referred to as 'the Bard'.", "pos": "n./adv."},
    "bare": {"def": "裸的、僅僅的、露出的、使赤裸、披露、裸的人、僅僅地 (裸)", "ipa": "/beə/", "trans": "barely, bareness", "col": "bare hands, bare feet, bare bones (基本要素), bare essentials", "ex": "The room was empty and the walls were bare.", "pos": "adj./v./n./adv."},
    "bareback": {"def": "無鞍的、(美俚)不戴安全套的、無鞍地 (無鞍)", "ipa": "/ˈbeəbæk/", "trans": "riding", "col": "ride bareback", "ex": "He learned to ride a horse bareback.", "pos": "adj./adv."},
    "faced/barefaced": {"def": "公然的、厚顏無恥的、露骨的", "ipa": "/ˌbeəˈfeɪst/", "trans": "shameless", "col": "barefaced lie", "ex": "That was a barefaced lie!", "pos": "adj."},
    "barefoot/barefooted": {"def": "赤腳的、赤腳地 (赤腳)", "ipa": "/ˈbeəfʊt/", "trans": "without shoes", "col": "walk barefoot", "ex": "The children were playing barefoot on the beach.", "pos": "adj./adv."},
    "bareheaded": {"def": "不戴帽的、不戴帽地 (不戴帽)", "ipa": "/ˌbeəˈhedɪd/", "trans": "without a hat", "col": "stood bareheaded", "ex": "He stood bareheaded in the rain.", "pos": "adj./adv."},
    "barely": {"def": "僅僅、幾乎不、貧乏地", "ipa": "/ˈbeəli/", "trans": "bare (形容詞/動詞/名詞/副詞)", "col": "barely enough, barely legal", "ex": "I could barely hear what she was saying.", "pos": "adv."},
    "bareness": {"def": "裸露、赤裸、貧乏", "ipa": "/ˈbeənəs/", "trans": "bare (形容詞/動詞/名詞/副詞)", "col": "sheer bareness", "ex": "He was struck by the bareness of the room.", "pos": "n."},
    "bargain": {"def": "討價還價、成交、便宜貨、契約、交易的人物、便宜地 (交易)", "ipa": "/ˈbɑːɡən/", "trans": "bargaining", "col": "hard bargain, real bargain, bargain price, drive a hard bargain", "ex": "The house was a real bargain at that price.", "pos": "n./v./adv."},
    "bargaining": {"def": "討價還價、商議、交易的人 (或物) (交易)", "ipa": "/ˈbɑːɡənɪŋ/", "trans": "bargain (名詞/動詞/副詞)", "col": "collective bargaining", "ex": "Union leaders are involved in collective bargaining with the management.", "pos": "n./adv."},
    "barge": {"def": "駁船、平底船、衝撞、闖入、船隻的、衝撞的、衝撞地 (衝撞)", "ipa": "/bɑːdʒ/", "trans": "barges", "col": "canal barge, barge in (闖入), barge into", "ex": "The canal narrows, making it difficult for a large barge to pass.", "pos": "n./v./adj./adv."},
    "baritone": {"def": "男中音、中音號、男中音的", "ipa": "/ˈbærɪtəʊn/", "trans": "voice type", "col": "baritone singer", "ex": "He has a rich baritone voice.", "pos": "n./adj."},
    "barium": {"def": "鋇", "ipa": "/ˈbeəriəm/", "trans": "chemical element", "col": "barium meal (鋇餐)", "ex": "The patient had to drink a barium meal for the X-ray.", "pos": "n."},
    "bark": {"def": "吠叫、樹皮、小船、吠、剝皮、咆哮的人物、咆哮地 (吠)", "ipa": "/bɑːk/", "trans": "barks", "col": "bark like a dog, bark up the wrong tree (搞錯方向), bite is worse than one's bark", "ex": "The dog began to bark at the stranger.", "pos": "n./v./adv."},
    "barker": {"def": "吠叫者、招徠顧客的人 (或物)", "ipa": "/ˈbɑːkə/", "trans": "bark (名詞/動詞/副詞)", "col": "fairground barker", "ex": "The fairground barker was shouting to attract customers.", "pos": "n."},
    "barley": {"def": "大麥", "ipa": "/ˈbɑːli/", "trans": "grain", "col": "barley grain, barley water", "ex": "Barley is a major crop in this region.", "pos": "n."},
    "barn": {"def": "穀倉、馬廄、簡陋大房、存放於穀倉、穀倉地 (穀倉)", "ipa": "/bɑːn/", "trans": "barns", "col": "dairy barn, hay barn", "ex": "The farmer stored the hay in the barn.", "pos": "n./v./adv."},
    "barnacle": {"def": "藤壺、難纏的人", "ipa": "/ˈbɑːnəkl/", "trans": "crustacean", "col": "encrusted with barnacles", "ex": "The ship's hull was encrusted with barnacles.", "pos": "n."},
    "barnstorm": {"def": "巡迴演出、在鄉村拉票", "ipa": "/ˈbɑːnstɔːm/", "trans": "campaign", "col": "barnstorm around", "ex": "The candidate will barnstorm across the state next week.", "pos": "v."},
    "barnyard": {"def": "穀倉旁的空地、畜舍地、粗俗的人、粗俗地 (粗俗)", "ipa": "/ˈbɑːnjɑːd/", "trans": "barnyards", "col": "barnyard fowl", "ex": "The children were playing in the barnyard.", "pos": "n./adj./adv."},
    "barometer": {"def": "氣壓計、晴雨表、變化的人物 (或事)", "ipa": "/bəˈrɒmɪtə/", "trans": "indicator", "col": "mercury barometer, economic barometer", "ex": "The barometer is falling, so it might rain.", "pos": "n."},
    "barometric": {"def": "氣壓的、氣壓計的", "ipa": "/ˌbærəˈmetrɪk/", "trans": "barometer", "col": "barometric pressure", "ex": "The pilot monitored the barometric pressure throughout the flight.", "pos": "adj."},
    "baron": {"def": "男爵、巨頭、大亨、男爵的、顯貴的人物、顯貴地 (男爵)", "ipa": "/ˈbærən/", "trans": "baroness", "col": "press baron, oil baron", "ex": "He is an oil baron with vast wealth.", "pos": "n./adj./adv."},
    "baroness": {"def": "男爵夫人、女男爵", "ipa": "/ˈbærənəs/", "trans": "baron", "col": "titled baroness", "ex": "The baroness attended the ceremony.", "pos": "n."},
    "baronial": {"def": "男爵的、莊嚴的、宏偉的", "ipa": "/bəˈrəʊniəl/", "trans": "noble", "col": "baronial hall", "ex": "We dined in the grand baronial hall.", "pos": "adj."},
    "baroque": {"def": "巴洛克風格的、變形的、過分裝飾的、巴洛克風格、過分裝飾地 (巴洛克)", "ipa": "/bəˈrɒk/", "trans": "ornate", "col": "baroque music, baroque architecture", "ex": "The church has many baroque features.", "pos": "adj./n./adv."},
    "barque/bark": {"def": "三桅帆船、小船", "ipa": "/bɑːk/", "trans": "ship", "col": "sailing barque", "ex": "The sailing barque was a magnificent sight.", "pos": "n."},
    "barrack": {"def": "營房、大而簡陋的房子、兵舍地、起鬨的人、起鬨地 (營房)", "ipa": "/ˈbærək/", "trans": "barracks", "col": "army barracks, barrack for (喝采/起鬨)", "ex": "The soldiers returned to their barracks.", "pos": "n./v./adv."},
    "barrage": {"def": "火力網、堰、大批出現、以密集火力攻擊、大批的人物、密集地 (密集)", "ipa": "/ˈbærɑːʒ/", "trans": "barrages", "col": "barrage of questions, artillery barrage", "ex": "The candidate was faced with a barrage of questions.", "pos": "n./v./adv."},
    "barrel": {"def": "木桶、槍管、大量、裝入桶內、高速飛行、桶裝的、桶裝地 (木桶)", "ipa": "/ˈbærəl/", "trans": "barrels", "col": "beer barrel, barrel of oil, lock, stock, and barrel (全部)", "ex": "They stored the wine in large wooden barrels.", "pos": "n./v./adj./adv."},
}