import json

# Level 5 Part 1: (Agricultural - Aisle)
L5_PART1 = {
    "agricultural": {"def": "農業的、農藝的", "ipa": "/ˌæɡrɪˈkʌltʃərəl/", "trans": "agriculture", "col": "agricultural policy, agricultural society", "ex": "The country is still largely an agricultural society.", "pos": "adj."},
    "agriculture": {"def": "農業、農藝、農學", "ipa": "/ˈæɡrɪkʌltʃə/", "trans": "agricultural", "col": "modern agriculture, organic agriculture", "ex": "Agriculture is the main industry in this region.", "pos": "n."},
    "aisle": {"def": "走道、通道、側廊", "ipa": "/aɪl/", "trans": "aisles", "col": "supermarket aisle, walk down the aisle (結婚)", "ex": "He was standing in the supermarket aisle.", "pos": "n."},
    "alarm": {"def": "警報、驚恐、鬧鐘、使驚恐、向...報警", "ipa": "/əˈlɑːm/", "trans": "alarming", "col": "fire alarm, sound the alarm", "ex": "The fire alarm went off in the middle of the night.", "pos": "n./v."},
    "alarming": {"def": "令人擔憂的、告急的", "ipa": "/əˈlɑːmɪŋ/", "trans": "alarm (名詞/動詞)", "col": "alarming rate", "ex": "The number of infections is rising at an alarming rate.", "pos": "adj."},
    "alcohol": {"def": "酒精、含酒精飲料", "ipa": "/ˈælkəhɒl/", "trans": "alcoholic", "col": "alcohol abuse, ethyl alcohol", "ex": "He doesn't drink alcohol.", "pos": "n."},
    "alcoholic": {"def": "酒精的、含酒精的、嗜酒者、酒鬼", "ipa": "/ˌælkəˈhɒlɪk/", "trans": "alcohol (名詞)", "col": "alcoholic beverage, recovering alcoholic", "ex": "Beer is an alcoholic beverage.", "pos": "adj./n."},
    "alert": {"def": "警覺的、留心的、機敏的、警報、警戒狀態、向...報警、使警覺", "ipa": "/əˈlɜːt/", "trans": "alertness", "col": "be alert to, red alert, weather alert", "ex": "We must be alert to the danger.", "pos": "adj./n./v."},
    "alley": {"def": "小巷、弄、徑、長廊", "ipa": "/ˈæli/", "trans": "alleys", "col": "blind alley, bowling alley", "ex": "The two men disappeared into a dark alley.", "pos": "n."},
    "alliance": {"def": "聯盟、同盟、聯姻", "ipa": "/əˈlaɪəns/", "trans": "ally", "col": "military alliance, form an alliance", "ex": "The two companies formed a strategic alliance.", "pos": "n."},
    "alligator": {"def": "短吻鱷、鱷魚皮、像短吻鱷的", "ipa": "/ˈælɪɡeɪtə/", "trans": "alligators", "col": "alligator clip", "ex": "Alligators are found in the southeastern United States.", "pos": "n."},
    "allocate": {"def": "分配、撥給、容納", "ipa": "/ˈæləkeɪt/", "trans": "allocation", "col": "allocate resources, allocate funds", "ex": "The government has allocated funds for the project.", "pos": "v."},
    "allocation": {"def": "配給、分配、撥給的款項", "ipa": "/ˌæləˈkeɪʃn/", "trans": "allocate (動詞)", "col": "resource allocation", "ex": "The efficient allocation of resources is essential.", "pos": "n."},
    "allot": {"def": "分配、撥給、分攤", "ipa": "/əˈlɒt/", "trans": "allotment", "col": "allot time", "ex": "How much time has been allotted for the task?", "pos": "v."},
    "allotment": {"def": "分配、配給物、撥給款項", "ipa": "/əˈlɒtmənt/", "trans": "allot (動詞)", "col": "financial allotment", "ex": "The annual allotment for the project is fifty thousand dollars.", "pos": "n."},
    "allowance": {"def": "津貼、零用錢、準備、考慮、定額", "ipa": "/əˈlaʊəns/", "trans": "allow", "col": "daily allowance, baggage allowance, make allowance for", "ex": "His father gives him a monthly allowance.", "pos": "n."},
    "alloy": {"def": "合金、雜質、使成合金、損害、夾雜", "ipa": "/ˈælɔɪ/ (n.) /əˈlɔɪ/ (v.)", "trans": "alloys", "col": "aluminum alloy", "ex": "Brass is an alloy of copper and zinc.", "pos": "n./v."},
    "allude": {"def": "暗指、影射、間接提到", "ipa": "/əˈluːd/", "trans": "allusion", "col": "allude to", "ex": "He alluded to the problem in his speech.", "pos": "v."},
    "allusion": {"def": "典故、暗指、影射", "ipa": "/əˈluːʒn/", "trans": "allude (動詞)", "col": "literary allusion", "ex": "The poem is full of literary allusions.", "pos": "n."},
    "ally": {"def": "盟友、同盟國、支持者、結盟、聯合", "ipa": "/ˈælaɪ/ (n.) /əˈlaɪ/ (v.)", "trans": "allied, alliance", "col": "close ally", "ex": "Britain is a close ally of the United States.", "pos": "n./v."},
    "almanac": {"def": "年鑑、曆書", "ipa": "/ˈɔːlmənæk/", "trans": "almanacs", "col": "nautical almanac", "ex": "I checked the farmers' almanac for the weather forecast.", "pos": "n."},
    "almighty": {"def": "萬能的、全能的、極大的、萬能的上帝", "ipa": "/ɔːlˈmaɪti/", "trans": "might", "col": "Almighty God", "ex": "We believe in the Almighty God.", "pos": "adj./n."},
    "almond": {"def": "杏仁、杏樹、杏仁色", "ipa": "/ˈɑːmənd/", "trans": "almons", "col": "almond milk", "ex": "She likes to eat roasted almonds.", "pos": "n."},
    "aloof": {"def": "遠離的、冷淡的、疏遠地、遠離開地", "ipa": "/əˈluːf/", "trans": "aloofness", "col": "keep aloof from", "ex": "He kept aloof from the other students.", "pos": "adj./adv."},
    "aloud": {"def": "大聲地、出聲地", "ipa": "/əˈlaʊd/", "trans": "loud", "col": "read aloud", "ex": "Please read the text aloud.", "pos": "adv."},
    "alphabet": {"def": "字母表、初步、入門", "ipa": "/ˈælfəbet/", "trans": "alphabetical", "col": "English alphabet, phonetic alphabet", "ex": "There are twenty-six letters in the English alphabet.", "pos": "n."},
    "alphabetical": {"def": "按字母順序的", "ipa": "/ˌælfəˈbetɪkl/", "trans": "alphabet (名詞), alphabetically", "col": "alphabetical order", "ex": "The names are listed in alphabetical order.", "pos": "adj."},
    "alphabetize": {"def": "按字母順序排列", "ipa": "/ˈælfəbətaɪz/", "trans": "alphabet (名詞), alphabetical", "col": "alphabetize the records", "ex": "Please alphabetize the records by author's name.", "pos": "v."},
    "altar": {"def": "祭壇、祭台", "ipa": "/ˈɔːltə/", "trans": "altars", "col": "high altar, sacrificial altar", "ex": "The priest stood in front of the altar.", "pos": "n."},
    "alter": {"def": "改變、更改、閹割", "ipa": "/ˈɔːltə/", "trans": "alteration", "col": "alter the plan", "ex": "We had to alter our plans due to the bad weather.", "pos": "v."},
    "alteration": {"def": "改變、更改、修改過的衣服", "ipa": "/ˌɔːltəˈreɪʃn/", "trans": "alter (動詞)", "col": "major alteration", "ex": "The house has undergone some major alterations.", "pos": "n."},
    "alternate": {"def": "輪流、交替、輪流的、交替的、代理人、替代者、使輪流、使交替", "ipa": "/ˈɔːltəneɪt/ (v./n.) /ɔːlˈtɜːnət/ (adj.)", "trans": "alternation, alternative", "col": "alternate days, alternate energy", "ex": "Wet days alternate with dry days.", "pos": "v./adj./n."},
    "alternation": {"def": "交替、輪流", "ipa": "/ˌɔːltəˈneɪʃn/", "trans": "alternate (動詞)", "col": "alternation of generations", "ex": "The seasons follow an alternation of periods of heat and cold.", "pos": "n."},
    "alternative": {"def": "替代的、兩者擇一的、非主流的、替代方案、選擇、兩者擇一", "ipa": "/ɔːlˈtɜːnətɪv/", "trans": "alternate (動詞), alternatively", "col": "alternative energy, viable alternative, have no alternative", "ex": "Solar power is an alternative energy source.", "pos": "adj./n."},
    "altitude": {"def": "高度、海拔、高處", "ipa": "/ˈæltɪtjuːd/", "trans": "altitudes", "col": "high altitude, at an altitude of", "ex": "The plane was flying at a high altitude.", "pos": "n."},
    "aluminum/aluminium": {"def": "鋁、鋁製的", "ipa": "/əˈluːmɪnəm/ /ˌæljəˈmɪniəm/", "trans": "alloys", "col": "aluminum foil", "ex": "The cans are made of aluminum.", "pos": "n./adj."},
    "alumni": {"def": "校友(複數)", "ipa": "/əˈlʌmnaɪ/", "trans": "alumnus (單數)", "col": "alumni association", "ex": "He is an active member of the alumni association.", "pos": "n."},
    "amateur": {"def": "業餘愛好者、外行、素人、業餘的、外行的、不熟練的", "ipa": "/ˈæmətə/", "trans": "amateurism", "col": "amateur athlete, amateur photography", "ex": "The competition is open to amateurs only.", "pos": "n./adj."},
    "amaze": {"def": "使驚奇、使驚嘆", "ipa": "/əˈmeɪz/", "trans": "amazing, amazement", "col": "amaze everyone", "ex": "The magician amazed everyone with his tricks.", "pos": "v."},
    "amazement": {"def": "驚奇、驚嘆", "ipa": "/əˈmeɪzmənt/", "trans": "amaze (動詞)", "col": "in amazement", "ex": "She stared at him in amazement.", "pos": "n."},
    "ambassador": {"def": "大使、特使", "ipa": "/æmˈbæsədə/", "trans": "ambassadorial", "col": "goodwill ambassador", "ex": "He was appointed as the ambassador to China.", "pos": "n."},
    "ambiguity": {"def": "模稜兩可、含糊、歧義", "ipa": "/ˌæmbɪˈɡjuːəti/", "trans": "ambiguous", "col": "ethical ambiguity", "ex": "The statement was full of ambiguity.", "pos": "n."},
    "ambiguous": {"def": "模稜兩可的、含糊不清的", "ipa": "/æmˈbɪɡjuəs/", "trans": "ambiguity (名詞)", "col": "ambiguous answer", "ex": "His answer was very ambiguous.", "pos": "adj."},
    "ambition": {"def": "野心、抱負、雄心", "ipa": "/æmˈbɪʃn/", "trans": "ambitious", "col": "burning ambition", "ex": "His ambition is to become a famous actor.", "pos": "n."},
    "ambitious": {"def": "野心勃勃的、有抱負的、艱巨的", "ipa": "/æmˈbɪʃəs/", "trans": "ambition (名詞)", "col": "ambitious project", "ex": "She is a very ambitious young woman.", "pos": "adj."},
    "ambulance": {"def": "救護車", "ipa": "/ˈæmbjələns/", "trans": "ambulances", "col": "call an ambulance", "ex": "The ambulance arrived within minutes.", "pos": "n."},
    "ambush": {"def": "伏击、埋伏、伏擊、埋伏", "ipa": "/ˈæmbʊʃ/", "trans": "ambushes", "col": "wait in ambush", "ex": "The soldiers were caught in an ambush.", "pos": "n./v."},
    "amend": {"def": "修正、修訂、賠償、改進、改善", "ipa": "/əˈmend/", "trans": "amendment", "col": "amend the law", "ex": "The committee decided to amend the rule.", "pos": "v."},
    "amendment": {"def": "修正案、修訂、改善", "ipa": "/əˈmendmənt/", "trans": "amend (動詞)", "col": "constitutional amendment", "ex": "The amendment was passed by a majority vote.", "pos": "n."},
    "amenity": {"def": "生活福利設施、便利、和藹、禮貌", "ipa": "/əˈmiːnəti/", "trans": "amenities", "col": "basic amenity, modern amenity", "ex": "The hotel has all the modern amenities.", "pos": "n."},
    "amiable": {"def": "親切的、友好的", "ipa": "/ˈeɪmiəbl/", "trans": "amiably", "col": "amiable personality", "ex": "He has a very amiable personality.", "pos": "adj."},
    "amicable": {"def": "友好的、溫和的", "ipa": "/ˈæmɪkəbl/", "trans": "amicably", "col": "amicable settlement", "ex": "They reached an amicable settlement.", "pos": "adj."},
    "amid/amidst": {"def": "在...中", "ipa": "/əˈmɪd/", "trans": "amidships", "col": "amid the chaos", "ex": "The child was found safe amid the ruins.", "pos": "prep."},
    "ammonia": {"def": "氨、氨水", "ipa": "/əˈməʊniə/", "trans": "ammonium", "col": "ammonia solution", "ex": "Ammonia is a colorless gas with a strong smell.", "pos": "n."},
    "amnesty": {"def": "大赦、特赦、免除、給予大赦", "ipa": "/ˈæmnəsti/", "trans": "amnesties", "col": "general amnesty", "ex": "The president granted a general amnesty to political prisoners.", "pos": "n./v."},
    "amount": {"def": "總額、量、實質、總計、等於、折合", "ipa": "/əˈmaʊnt/", "trans": "amounts", "col": "large amount, small amount, amount to", "ex": "He spent a large amount of money on the car.", "pos": "n./v."},
    "ample": {"def": "寬裕的、足夠的、豐富的", "ipa": "/ˈæmpl/", "trans": "amply", "col": "ample evidence", "ex": "There is ample evidence to support his theory.", "pos": "adj."},
    "amplify": {"def": "放大、擴大、詳述", "ipa": "/ˈæmplɪfaɪ/", "trans": "amplification, amplifier", "col": "amplify the sound", "ex": "The microphone is used to amplify the singer's voice.", "pos": "v."},
    "amplifier": {"def": "放大器、擴聲器", "ipa": "/ˈæmplɪfaɪə/", "trans": "amplify (動詞)", "col": "guitar amplifier", "ex": "He plugged his guitar into the amplifier.", "pos": "n."},
    "amputate": {"def": "截肢、切斷", "ipa": "/ˈæmpjuteɪt/", "trans": "amputation", "col": "amputate a leg", "ex": "The doctors had to amputate his leg.", "pos": "v."},
    "amuse": {"def": "使發笑、使開心、消遣", "ipa": "/əˈmjuːz/", "trans": "amusement, amusing", "col": "amuse someone with", "ex": "The children were amused by the clown.", "pos": "v."},
    "amusement": {"def": "樂趣、消遣、娛樂設施", "ipa": "/əˈmjuːzmənt/", "trans": "amuse (動詞), amusing", "col": "amusement park, for amusement", "ex": "We went to the amusement park for the day.", "pos": "n."},
    "analog/analogue": {"def": "類比的、模擬的、類似物", "ipa": "/ˈænəlɒɡ/", "trans": "analogue", "col": "analog clock", "ex": "The computer uses an analog system.", "pos": "adj./n."},
    "analogy": {"def": "類比、類推、相似之處", "ipa": "/əˈnælədʒi/", "trans": "analogous", "col": "draw an analogy", "ex": "He drew an analogy between the brain and a computer.", "pos": "n."},
    "analysis": {"def": "分析、解析", "ipa": "/əˈnæləsɪs/", "trans": "analyses (複數), analyze", "col": "chemical analysis, statistical analysis", "ex": "A detailed analysis of the data was performed.", "pos": "n."},
    "analyze/analyse": {"def": "分析、解析", "ipa": "/ˈænəlaɪz/", "trans": "analysis (名詞)", "col": "analyze data", "ex": "We need to analyze the problem carefully.", "pos": "v."},
    "analyst": {"def": "分析家、解析者", "ipa": "/ˈænəlɪst/", "trans": "analysis, analyze", "col": "financial analyst, system analyst", "ex": "He works as a financial analyst.", "pos": "n."},
    "ancestor": {"def": "祖先、祖代", "ipa": "/ˈænsestə/", "trans": "ancestral, ancestry", "col": "common ancestor", "ex": "The chimpanzee is a close relative of our ancestors.", "pos": "n."},
    "ancestral": {"def": "祖先的、祖傳的", "ipa": "/ænˈsestrəl/", "trans": "ancestor (名詞)", "col": "ancestral home", "ex": "They visited their ancestral home in China.", "pos": "adj."},
    "ancestry": {"def": "世系、家族、血統", "ipa": "/ˈænsestri/", "trans": "ancestor (名詞)", "col": "Chinese ancestry", "ex": "He is of Chinese ancestry.", "pos": "n."},
    "anchor": {"def": "錨、依靠、新聞主播、拋錨、使固定、主持節目", "ipa": "/ˈæŋkə/", "trans": "anchorman, anchorage", "col": "cast anchor, anchor a program", "ex": "The ship cast anchor in the bay.", "pos": "n./v."},
    "ancient": {"def": "古代的、古老的、老人", "ipa": "/ˈeɪnʃənt/", "trans": "ancients", "col": "ancient civilization, ancient Greece", "ex": "Rome is an ancient city.", "pos": "adj./n."},
    "anecdote": {"def": "軼事、奇聞", "ipa": "/ˈænɪkdəʊt/", "trans": "anecdotal", "col": "tell an anecdote", "ex": "She told several amusing anecdotes about her trip.", "pos": "n."},
    "anemia/anaemia": {"def": "貧血", "ipa": "/əˈniːmiə/", "trans": "anemic", "col": "suffer from anemia", "ex": "She suffers from iron-deficiency anemia.", "pos": "n."},
    "anemic/anaemic": {"def": "貧血的、無力量的", "ipa": "/əˈniːmɪk/", "trans": "anemia (名詞)", "col": "anemic look", "ex": "He has an anemic look.", "pos": "adj."},
    "anesthesia/anaesthesia": {"def": "麻醉", "ipa": "/ˌænəsˈθiːziə/", "trans": "anesthetic", "col": "under anesthesia", "ex": "The surgery was performed under general anesthesia.", "pos": "n."},
    "anesthetic/anaesthetic": {"def": "麻醉劑、麻醉的", "ipa": "/ˌænəsˈθetɪk/", "trans": "anesthesia (名詞)", "col": "local anesthetic", "ex": "The dentist gave me a local anesthetic.", "pos": "n./adj."},
    "angel": {"def": "天使、善良的人", "ipa": "/ˈeɪndʒl/", "trans": "angelic", "col": "guardian angel", "ex": "She is a guardian angel to me.", "pos": "n."},
    "angelic": {"def": "天使般的、美妙的、善良的", "ipa": "/ænˈdʒelɪk/", "trans": "angel (名詞)", "col": "angelic face", "ex": "The baby has an angelic face.", "pos": "adj."},
    "anger": {"def": "生氣、憤怒、使發怒、激怒", "ipa": "/ˈæŋɡə/", "trans": "angry", "col": "in anger, voice full of anger", "ex": "He shook his fist in anger.", "pos": "n./v."},
    "angle": {"def": "角、角度、觀點、角落、釣魚、謀取、傾向", "ipa": "/ˈæŋɡl/", "trans": "angler, angling", "col": "right angle, wide angle, from a different angle", "ex": "We should look at the problem from a different angle.", "pos": "n./v."},
    "angry": {"def": "生氣的、發怒的", "ipa": "/ˈæŋɡri/", "trans": "anger (名詞), angrily", "col": "angry with, angry at", "ex": "He is angry with me for being late.", "pos": "adj."},
    "anguish": {"def": "極度痛苦、苦惱、使感到極度痛苦", "ipa": "/ˈæŋɡwɪʃ/", "trans": "anguished", "col": "mental anguish", "ex": "They suffered mental anguish over the loss of their child.", "pos": "n./v."},
    "animal": {"def": "動物、畜牲、獸性的、野蠻的", "ipa": "/ˈænɪml/", "trans": "animality, animalize", "col": "wild animal, domestic animal, animal rights", "ex": "Lions are wild animals.", "pos": "n./adj."},
    "animate": {"def": "使有生命、賦予活力、動畫化、有生命的、活潑的", "ipa": "/ˈænɪmeɪt/ (v.) /ˈænɪmət/ (adj.)", "trans": "animation, animated", "col": "animated cartoon", "ex": "The movie was animated by a team of artists.", "pos": "v./adj."},
    "animated": {"def": "動畫的、活潑的、有生命的", "ipa": "/ˈænɪmeɪtɪd/", "trans": "animate (名詞/形容詞), animation", "col": "animated movie, animated discussion", "ex": "The movie is an animated adventure.", "pos": "adj."},
    "animation": {"def": "動畫、活潑、生氣", "ipa": "/ˌænɪˈmeɪʃn/", "trans": "animate (名詞/形容詞/動詞)", "col": "computer animation", "ex": "The movie features excellent computer animation.", "pos": "n."},
    "animosity": {"def": "敵意、仇恨、憎惡", "ipa": "/ˌænɪˈmɒsəti/", "trans": "animosities", "col": "personal animosity", "ex": "There is no personal animosity between the two men.", "pos": "n."},
    "ankle": {"def": "腳踝", "ipa": "/ˈæŋkl/", "trans": "ankles", "col": "sprained ankle", "ex": "She sprained her ankle while playing tennis.", "pos": "n."},
    "annals": {"def": "編年史、歷史記載報紀錄", "ipa": "/ˈænlz/", "trans": "annalist", "col": "academic annals", "ex": "The event is recorded in the annals of history.", "pos": "n."},
    "annex": {"def": "併吞、附加、合併、附屬建築、附件", "ipa": "/əˈneks/ (v.) /ˈæneks/ (n.)", "trans": "annexation", "col": "annex territory", "ex": "The territory was annexed by the neighboring country.", "pos": "v./n."},
    "annihilation": {"def": "殲滅、毀滅、消滅", "ipa": "/əˌnaɪəˈleɪʃn/", "trans": "annihilate", "col": "total annihilation", "ex": "The threat of nuclear annihilation hangs over the world.", "pos": "n."},
    "anniversary": {"def": "週年紀念日、中年的、週年的", "ipa": "/ˌænɪˈvɜːsəri/", "trans": "anniversaries", "col": "wedding anniversary", "ex": "They celebrated their tenth wedding anniversary yesterday.", "pos": "n./adj."},
    "announce": {"def": "宣布、發布、預告、播報", "ipa": "/əˈnaʊns/", "trans": "announcement, announcer", "col": "announce the news", "ex": "The company announced its decision this morning.", "pos": "v."},
    "announcement": {"def": "宣布、公告、啟事、婚約發表", "ipa": "/əˈnaʊnsmənt/", "trans": "announce (動詞)", "col": "public announcement, official announcement", "ex": "The government made an official announcement.", "pos": "n."},
    "announcer": {"def": "播音員、報幕員", "ipa": "/əˈnaʊnsə/", "trans": "announce (動詞)", "col": "radio announcer, television announcer", "ex": "He works as a radio announcer.", "pos": "n."},
    "annoy": {"def": "使煩惱、打擾、干擾", "ipa": "/əˈnɔɪ/", "trans": "annoyance, annoying", "col": "annoy someone with", "ex": "His constant complaining began to annoy me.", "pos": "v."},
    "annoyance": {"def": "煩惱、打擾、令人氣惱的事", "ipa": "/əˈnɔɪəns/", "trans": "annoy (動詞), annoying", "col": "much to one's annoyance", "ex": "Much to my annoyance, the train was delayed.", "pos": "n."},
    "annoying": {"def": "討厭的、惱人的", "ipa": "/əˈnɔɪɪŋ/", "trans": "annoy (動詞), annoyance", "col": "annoying habit", "ex": "He has an annoying habit of interrupting others.", "pos": "adj."},
    "annual": {"def": "年度的、每年的、一年生的、年刊、一年生植物、每年地", "ipa": "/ˈænjuəl/", "trans": "annually", "col": "annual report, annual event", "ex": "The company produces an annual report.", "pos": "adj./n./adv."},
    "annually": {"def": "一年一次地、每年地", "ipa": "/ˈænjuəli/", "trans": "annual (形容詞)", "col": "held annually", "ex": "The convention is held annually.", "pos": "adv."},
    "anonymous": {"def": "匿名的、無特徵的", "ipa": "/əˈnɒnɪməs/", "trans": "anonymity, anonymously", "col": "anonymous tip, anonymous source", "ex": "The police received an anonymous tip.", "pos": "adj."},
}

with open("batch_l5_p1.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART1, f, ensure_ascii=False, indent=2)
