import json

# Level 6 Part 34: (Bill - Biota)
L6_PART34 = {
    "bill": {"def": "帳單、議案、鈔票、鳥嘴、廣告、開帳單、宣布、帳單的人、帳單地 (單)", "ipa": "/bɪl/", "trans": "bills", "col": "pay a bill, dollar bill, electricity bill, pass a bill", "ex": "Please send me the bill.", "pos": "n./v./adv."},
    "billboard": {"def": "廣告牌、佈告板", "ipa": "/ˈbɪlbɔːd/", "trans": "hoarding", "col": "giant billboard", "ex": "There are many giant billboards along the highway.", "pos": "n."},
    "billet": {"def": "營房、職位、便條、木柴、安插...在營房、派職位的人 (或物) (營)", "ipa": "/ˈbɪlɪt/", "trans": "billets", "col": "soldiers' billet", "ex": "The soldiers were given billets in the local houses.", "pos": "n./v./adv."},
    "billiard": {"def": "撞球的、撞球地 (撞球)", "ipa": "/ˈbɪliəd/", "trans": "billiards", "col": "billiard table, billiard hall", "ex": "He likes to play on the billiard table in the evening.", "pos": "adj./adv."},
    "billiards": {"def": "撞球 (運動)", "ipa": "/ˈbɪliədz/", "trans": "billiard", "col": "play billiards", "ex": "Billiards is a popular indoor game.", "pos": "n."},
    "billion": {"def": "十億、萬億 (英制)、十億的人 (或物)、十億地 (十億)", "ipa": "/ˈbɪliən/", "trans": "billions", "col": "billions of stars, billionaire (億萬富翁)", "ex": "The world population has reached 8 billion.", "pos": "n./adj./adv."},
    "billionaire": {"def": "億萬富翁", "ipa": "/ˌbɪliəˈneə/", "trans": "wealthy person", "col": "self-made billionaire", "ex": "He is a self-made billionaire with several companies.", "pos": "n."},
    "billow": {"def": "巨浪、波濤、(煙、雲)湧動、翻騰、湧動的人 (或物)、翻騰地 (湧)", "ipa": "/ˈbɪləʊ/", "trans": "billowing", "col": "billowing smoke, billow out (鼓起)", "ex": "Smoke billowed from the burning building.", "pos": "n./v./adv."},
    "billy": {"def": "(澳洲)野外燒水壺、(美俚)警察短棍、男山羊 (單數)", "ipa": "/ˈbɪli/", "trans": "billies (複數)", "col": "billy goat, billy club", "ex": "The farmer kept a large billy goat.", "pos": "n."},
    "binary": {"def": "二進位的、二元的、雙體、雙星、二進位的人 (或物)、二進位地 (二)", "ipa": "/ˈbaɪnəri/", "trans": "binaries", "col": "binary code, binary system, binary star", "ex": "Computers use binary code to process information.", "pos": "adj./n./adv."},
    "bind": {"def": "捆綁、束縛、裝訂、必然、捆綁的人 (或物)、捆綁地 (捆)", "ipa": "/baɪnd/", "trans": "binding, bound", "col": "in a bind (陷入困境), bind together, bind by law", "ex": "They used a rope to bind the wood together.", "pos": "v./n./adv."},
    "binder": {"def": "活頁夾、裝訂機、粘合劑 (單數)", "ipa": "/ˈbaɪndə/", "trans": "binders (複數)", "col": "ring binder", "ex": "I need a ring binder for my school notes.", "pos": "n."},
    "binding": {"def": "裝訂、捆綁物、有約束力的、必不可少的、裝訂的人 (或物) (訂)", "ipa": "/ˈbaɪndɪŋ/", "trans": "bind (動詞/名詞/副詞)", "col": "binding agreement, book binding", "ex": "The agreement is legally binding on both parties.", "pos": "n./adj./adv."},
    "binge": {"def": "狂歡、縱樂、狂飲、大吃大喝的人、狂歡地 (狂歡)", "ipa": "/bɪndʒ/", "trans": "binges", "col": "binge eating, binge watching, go on a binge", "ex": "They went on a shopping binge last weekend.", "pos": "n./v./adv."},
    "bingo": {"def": "賓果 (遊戲)、(感嘆詞)中了！、成功地 (賓果)", "ipa": "/ˈbɪŋɡəʊ/", "trans": "game", "col": "play bingo, bingo hall", "ex": "Bingo! I've found it!", "pos": "n./int./adv."},
    "binocular": {"def": "雙目的、雙筒的、雙筒鏡的人物、雙筒地 (雙)", "ipa": "/baɪˈnɒkjələ/", "trans": "binoculars", "col": "binocular vision", "ex": "Human beings have binocular vision.", "pos": "adj./adv."},
    "binoculars": {"def": "雙筒望遠鏡 (複數)", "ipa": "/bɪˈnɒkjələz/", "trans": "binocular", "col": "pair of binoculars", "ex": "He looked through his binoculars at the birds.", "pos": "n."},
    "binomial": {"def": "(數)二項式、(生)雙名法、二項的、二項的人物、二項地 (二)", "ipa": "/baɪˈnəʊmiəl/", "trans": "polynomial", "col": "binomial theorem, binomial nomenclature", "ex": "Scientific names use binomial nomenclature.", "pos": "n./adj./adv."},
    "bio-": {"def": "(字根)生物、生命", "ipa": "/ˈbaɪəʊ/", "trans": "life", "col": "biology, biography, biosensor", "ex": "'Biology' comes from the Greek roots 'bio' and 'logy'.", "pos": "pref."},
    "biochemical": {"def": "生物化學的、生化的人、生化地 (生化)", "ipa": "/ˌbaɪəʊˈkemɪkl/", "trans": "biochemistry", "col": "biochemical reaction", "ex": "These are the biochemical reactions that occur in the body.", "pos": "adj./n./adv."},
    "biochemistry": {"def": "生物化學", "ipa": "/ˌbaɪəʊˈkemɪstri/", "trans": "biochemist", "col": "department of biochemistry", "ex": "She is studying biochemistry at the university.", "pos": "n."},
    "biodegradable": {"def": "生物可降解的", "ipa": "/ˌbaɪəʊdɪˈɡreɪdəbl/", "trans": "green", "col": "biodegradable plastic", "ex": "We should use biodegradable products to protect the environment.", "pos": "adj."},
    "biodiversity": {"def": "生物多樣性", "ipa": "/ˌbaɪəʊdaɪˈvɜːsəti/", "trans": "biological diversity", "col": "preserve biodiversity", "ex": "The park is home to a rich biodiversity of species.", "pos": "n."},
    "biofeedback": {"def": "生物回饋", "ipa": "/ˌbaɪəʊˈfiːdbæk/", "trans": "therapy", "col": "biofeedback technique", "ex": "The clinic uses biofeedback to help patients manage stress.", "pos": "n."},
    "biographer": {"def": "傳記作者", "ipa": "/baɪˈɒɡrəfə/", "trans": "biography", "col": "official biographer", "ex": "The official biographer spent years researching the president's life.", "pos": "n."},
    "biographic/biographical": {"def": "傳記的、傳記體的", "ipa": "/ˌbaɪəˈɡræfɪkl/", "trans": "biography", "col": "biographical details", "ex": "The book provides interesting biographical details of the artist.", "pos": "adj."},
    "biography": {"def": "傳記、傳記文學", "ipa": "/baɪˈɒɡrəfi/", "trans": "biographies", "col": "unauthorized biography", "ex": "I've just finished reading a biography of Einstein.", "pos": "n."},
    "biological": {"def": "生物學的、生物的、血親的、生物的人、生物地 (生)", "ipa": "/ˌbaɪəˈlɒdʒɪkl/", "trans": "biologically, biology", "col": "biological weapon, biological clock, biological parents", "ex": "She is searching for her biological parents.", "pos": "adj./n./adv."},
    "biologist": {"def": "生物學家", "ipa": "/baɪˈɒlədʒɪst/", "trans": "biology", "col": "marine biologist", "ex": "The marine biologist studies sea creatures.", "pos": "n."},
    "biology": {"def": "生物學、生態、生物部的人、生物地 (生)", "ipa": "/baɪˈɒlədʒi/", "trans": "biologies", "col": "molecular biology, evolutionary biology", "ex": "Biology is the study of living organisms.", "pos": "n./adv."},
    "biomedical": {"def": "生物醫學的", "ipa": "/ˌbaɪəʊˈmedɪkl/", "trans": "medicine", "col": "biomedical research", "ex": "Biomedical research is essential for developing new drugs.", "pos": "adj."},
    "bionic": {"def": "仿生學的、(口)有超人力量的", "ipa": "/baɪˈɒnɪk/", "trans": "bionics", "col": "bionic arm", "ex": "He received a bionic arm after the accident.", "pos": "adj."},
    "biophysics": {"def": "生物物理學", "ipa": "/ˌbaɪəʊˈfɪzɪks/", "trans": "biophysicist", "col": "institute of biophysics", "ex": "Biophysics combines biology and physics.", "pos": "n."},
    "biopsy": {"def": "切片檢查、活組織檢查 (單數)", "ipa": "/ˈbaɪɒpsi/", "trans": "biopsies (複數)", "col": "perform a biopsy", "ex": "The doctor ordered a biopsy to check for cancer.", "pos": "n."},
    "biorhythm": {"def": "生物節律、生理時鐘", "ipa": "/ˈbaɪəʊrɪðəm/", "trans": "biological rhythm", "col": "natural biorhythm", "ex": "Jet lag can disrupt your natural biorhythm.", "pos": "n."},
    "biosphere": {"def": "生物圈", "ipa": "/ˈbaɪəsfiə/", "trans": "ecosystem", "col": "Earth's biosphere", "ex": "The biosphere includes all living things on Earth.", "pos": "n."},
    "biota": {"def": "生物群、生態群 (單數)", "ipa": "/baɪˈəʊtə/", "trans": "biotas (複數)", "col": "local biota", "ex": "The local biota has been affected by pollution.", "pos": "n."},
}