import json

# Level 6 Part 24: (Bath - Beach)
L6_PART24 = {
    "bath": {"def": "洗澡、浴缸、浴室、洗澡的人 (或物)、洗澡地 (浴)", "ipa": "/bɑːθ/", "trans": "baths", "col": "take a bath, bubble bath, bird bath", "ex": "I'm going to take a hot bath.", "pos": "n./v./adv."},
    "bathe": {"def": "洗澡、沐浴、游泳、浸泡、洗澡的人 (或物)、洗澡地 (洗)", "ipa": "/beɪð/", "trans": "bathing", "col": "go for a bathe, sunbathe (日光浴), bathen in", "ex": "She bathed her eyes with cold water.", "pos": "v./n./adv."},
    "bather": {"def": "洗澡者、游泳者", "ipa": "/ˈbeɪðə/", "trans": "bathe (動詞/名詞/副詞)", "col": "sun bather", "ex": "The beach was full of sun bathers.", "pos": "n."},
    "bathing": {"def": "沐浴、游泳、洗澡的人 (或物) (洗)", "ipa": "/ˈbeɪðɪŋ/", "trans": "bathe (動詞/名詞/副詞)", "col": "bathing suit (泳衣), bathing cap", "ex": "Don't forget to pack your bathing suit.", "pos": "n./adv."},
    "bathrobe": {"def": "浴袍", "ipa": "/ˈbɑːθrəʊb/", "trans": "dressing gown", "col": "fluffy bathrobe", "ex": "She put on her fluffy bathrobe after the shower.", "pos": "n."},
    "bathroom": {"def": "浴室、洗手間 (單數)", "ipa": "/ˈbɑːθruːm/", "trans": "bathrooms (複數)", "col": "master bathroom, down the bathroom", "ex": "Where's the bathroom, please?", "pos": "n."},
    "bathtub/bath tub": {"def": "浴缸", "ipa": "/ˈbɑːθtʌb/", "trans": "bath", "col": "full bathtub", "ex": "He likes to relax in a full bathtub.", "pos": "n."},
    "baton": {"def": "指揮棒、接力棒、警棍、權杖的人物、權杖地 (棒)", "ipa": "/ˈbætɒn/", "trans": "batons", "col": "conductor's baton, relay baton, police baton", "ex": "The conductor raised his baton.", "pos": "n./adv."},
    "battalion": {"def": "營、大軍、大批的人 (或物)、大批的人 (或物) 的人物、大批地 (營)", "ipa": "/bəˈtæliən/", "trans": "battalions", "col": "infantry battalion, battalion commander", "ex": "The infantry battalion moved to the front line.", "pos": "n./adv."},
    "batten": {"def": "板條、板帶、用板條固定、吃肥、繁榮的人物、繁榮地 (板)", "ipa": "/ˈbætən/", "trans": "battens", "col": "batten down the hatches (嚴陣以待)", "ex": "We need to batten down the hatches before the storm arrives.", "pos": "n./v./adv."},
    "batter": {"def": "擊球手、糊狀物、猛擊、打爛、猛擊的人 (或物)、猛擊地 (擊)", "ipa": "/ˈbætə/", "trans": "battered", "col": "pancake batter, battering ram", "ex": "The waves battered the shore during the storm.", "pos": "n./v./adv."},
    "battered": {"def": "破舊的、受虐的、打爛的", "ipa": "/ˈbætəd/", "trans": "batter (名詞/動詞/副詞)", "col": "battered car, battered woman", "ex": "He drove an old, battered car.", "pos": "adj."},
    "battering": {"def": "猛擊、連擊、猛擊的人 (或物) (擊)", "ipa": "/ˈbætərɪŋ/", "trans": "batter (名詞/動詞/副詞)", "col": "take a battering (遭到重創)", "ex": "The economy has taken a serious battering.", "pos": "n./adv."},
    "battery": {"def": "(電)電池、(軍)砲兵連、一組、系列、毆打、電池的人物、電池地 (電)", "ipa": "/ˈbætri/", "trans": "batteries", "col": "rechargeable battery, solar battery, series of battery", "ex": "The battery in my phone is dead.", "pos": "n./adv."},
    "battle": {"def": "戰鬥、戰役、鬥爭、爭鬥、博鬥、博鬥的人 (或物)、博鬥地 (戰)", "ipa": "/ˈbætl/", "trans": "battling, battlefield", "col": "battle field, battle cry, win the battle, lose the battle", "ex": "The soldiers prepared for the upcoming battle.", "pos": "n./v./adv."},
    "battlefield/battle field": {"def": "戰場 (單數)", "ipa": "/ˈbætlfiːld/", "trans": "battlefields (複數)", "col": "ancient battlefield", "ex": "Many historical artifacts were found on the ancient battlefield.", "pos": "n."},
    "battlement": {"def": "城疊、雉堞 (單數/常用複數)", "ipa": "/ˈbætlmənt/", "trans": "battlements", "col": "castle battlements", "ex": "The archers stood behind the castle battlements.", "pos": "n."},
    "battleship": {"def": "戰列艦、主力艦", "ipa": "/ˈbætlʃɪp/", "trans": "warship", "col": "massive battleship", "ex": "The battleship was a symbol of naval power.", "pos": "n."},
    "battling": {"def": "戰鬥的、奮鬥的、鬥爭的人 (或物) (戰)", "ipa": "/ˈbætlɪŋ/", "trans": "battle (名詞/動詞/副詞)", "col": "battling against", "ex": "The patient is battling against cancer.", "pos": "adj./adv."},
    "batty": {"def": "(俚)瘋癲的、古怪的、有蝙蝠的", "ipa": "/ˈbæti/", "trans": "crazy", "col": "go batty", "ex": "The noise is driving me batty.", "pos": "adj."},
    "bauble": {"def": "廉價小玩意、飾品 (單數)", "ipa": "/ˈbɔːbl/", "trans": "baubles (複數)", "col": "Christmas bauble", "ex": "The Christmas tree was decorated with colorful baubles.", "pos": "n."},
    "baud": {"def": "波特 (通訊速率單位)", "ipa": "/bɔːd/", "trans": "bps", "col": "bits per baud", "ex": "The transmission speed is 9600 baud.", "pos": "n."},
    "bawdy": {"def": "下流的、猥褻的、強烈的人、強烈地 (強)", "ipa": "/ˈbɔːdi/", "trans": "bawdiness", "col": "bawdy song", "ex": "They sang some bawdy songs after dinner.", "pos": "adj./n./adv."},
    "bawdiness": {"def": "下流、猥褻", "ipa": "/ˈbɔːdinəs/", "trans": "bawdy (形容詞/名詞/副詞)", "col": "sheer bawdiness", "ex": "The play was criticized for its sheer bawdiness.", "pos": "n."},
    "bawl": {"def": "咆哮、大聲嚷、放聲痛哭、咆哮的人 (或物)、咆哮地 (咆)", "ipa": "/bɔːl/", "trans": "cry", "col": "bawl out (責罵), bawl like a baby", "ex": "The mother bawled at the children to come home.", "pos": "v./n./adv."},
    "bay": {"def": "海灣、犬吠、隔間、月桂樹、紅褐色的、吠叫的人 (或物)、在海灣地 (灣)", "ipa": "/beɪ/", "trans": "bays", "col": "bay window, keep at bay (不使逼近), bay for blood", "ex": "The ship anchored in the quiet bay.", "pos": "n./v./adj./adv."},
    "bayonet": {"def": "刺刀、裝刺刀於、用刺刀刺、刺刀地 (刺)", "ipa": "/ˈbeɪənət/", "trans": "bayonets", "col": "fixed bayonet", "ex": "The soldiers charged with fixed bayonets.", "pos": "n./v./adv."},
    "bazaar": {"def": "市集、義賣場", "ipa": "/bəˈzɑː/", "trans": "market", "col": "charity bazaar", "ex": "The church is holding a charity bazaar this weekend.", "pos": "n."},
    "be": {"def": "是、在、存在、發生、在的人 (或物)、(法)是 (是)", "ipa": "/biː/", "trans": "am, is, are, was, were", "col": "to be or not to be, let it be", "ex": "She wants to be a doctor.", "pos": "v./n./adv."},
    "beach": {"def": "海灘、湖濱、使船上岸、擱淺、在岸上的人物、在岸上地 (灘)", "ipa": "/biːtʃ/", "trans": "beaches", "col": "sandy beach, public beach, go to the beach", "ex": "We spent the whole day on the sandy beach.", "pos": "n./v./adv."},
}