import json

# Level 6 Part 37: (Blame - Bleak)
L6_PART37 = {
    "blame": {"def": "責備、責怪、責任、怪罪、應負責任的人物、責備地 (責)", "ipa": "/bleɪm/", "trans": "blaming", "col": "take the blame, blame someone for, shift the blame", "ex": "Don't blame me for your mistakes.", "pos": "v./n./adv."},
    "blameable": {"def": "該責備的、有過失的", "ipa": "/ˈbleɪməbl/", "trans": "blame (名詞/動詞/副詞)", "col": "hardly blameable", "ex": "The driver was hardly blameable for the accident.", "pos": "adj."},
    "blameful": {"def": "該受責備的、有罪的", "ipa": "/ˈbleɪmfl/", "trans": "blame (名詞/動詞/副詞)", "col": "blameful conduct", "ex": "His blameful conduct led to his dismissal.", "pos": "adj."},
    "blameless": {"def": "無可指責的、清白的", "ipa": "/ˈbleɪmləs/", "trans": "innocent", "col": "blameless life", "ex": "She has led a blameless life.", "pos": "adj."},
    "blamelessly": {"def": "無可指責地、清白地", "ipa": "/ˈbleɪmləsli/", "trans": "blameless (形容詞)", "col": "behaved blamelessly", "ex": "The officer behaved blamelessly during the crisis.", "pos": "adv."},
    "blameworthiness": {"def": "應受責備、有過失", "ipa": "/ˈbleɪmwɜːðinəs/", "trans": "blameworthy", "col": "degree of blameworthiness", "ex": "The jury assessed the degree of blameworthiness.", "pos": "n."},
    "blameworthy": {"def": "應受責備的、該罵的", "ipa": "/ˈbleɪmwɜːði/", "trans": "blame (名詞/動詞/副詞)", "col": "blameworthy action", "ex": "His actions were highly blameworthy.", "pos": "adj."},
    "blaming": {"def": "責備的、怪罪的人 (或物) (責)", "ipa": "/ˈbleɪmɪŋ/", "trans": "blame (名詞/動詞/副詞)", "col": "stop blaming", "ex": "There's no point in blaming each other.", "pos": "adj./n./adv."},
    "blanch": {"def": "使變白、(因恐懼等)臉色蒼白、燙(蔬菜)、變白的人 (或物)、變白地 (白)", "ipa": "/blɑːntʃ/", "trans": "whiten", "col": "blanch with fear, blanch almonds", "ex": "She blanched with fear at the sight of the spider.", "pos": "v./n./adv."},
    "bland": {"def": "平淡的、溫和的、乏味的、平淡地 (平)", "ipa": "/blænd/", "trans": "blandly", "col": "bland diet, bland food, bland smile", "ex": "The soup is a bit bland - it needs more salt.", "pos": "adj./adv."},
    "blandly": {"def": "溫和地、平淡地、委婉地", "ipa": "/ˈblændli/", "trans": "bland (形容詞/副詞)", "col": "smiled blandly", "ex": "He smiled blandly and refused to comment.", "pos": "adv."},
    "blandness": {"def": "平淡、溫和、乏味", "ipa": "/ˈblændnəs/", "trans": "bland (形容詞/副詞)", "col": "general blandness", "ex": "Critics complained about the general blandness of the music.", "pos": "n."},
    "blank": {"def": "空白的、茫然的、空白處、沒填寫、茫然地 (空)", "ipa": "/blæŋk/", "trans": "blanks", "col": "blank space, go blank (大腦空白), blank check, blank stare", "ex": "Fill in the blank space with your name.", "pos": "adj./n./v./adv."},
    "blanket": {"def": "毯子、覆蓋層、全體的、覆蓋、覆蓋地的 (毯)", "ipa": "/ˈblæŋkɪt/", "trans": "blanketing", "col": "electric blanket, blanket ban (全面禁止), blanket of snow", "ex": "A thick blanket of snow covered the ground.", "pos": "n./adj./v./adv."},
    "blankly": {"def": "茫然地、無表情地", "ipa": "/ˈblæŋkli/", "trans": "blank (形容詞/名詞/動詞/副詞)", "col": "stared blankly", "ex": "She stared blankly at the exam paper.", "pos": "adv."},
    "blankness": {"def": "空白、茫然、無表情", "ipa": "/ˈblæŋknəs/", "trans": "blank (形容詞/名詞/動詞/副詞)", "col": "total blankness", "ex": "There was a total blankness in his expression.", "pos": "n."},
    "blare": {"def": "大聲鳴響、(光)閃燿、高分貝、鳴響的人 (或物)、鳴響地 (響)", "ipa": "/bleə/", "trans": "blaring", "col": "blare out, trumpet blare", "ex": "Music blared out from the loudspeakers.", "pos": "v./n./adv."},
    "blaring": {"def": "刺耳的、閃燿的、大聲的人 (或物) (響)", "ipa": "/ˈbleərɪŋ/", "trans": "blare (動詞/名詞/副詞)", "col": "blaring music", "ex": "I couldn't sleep because of the blaring music.", "pos": "adj./adv."},
    "blaspheme": {"def": "褻瀆、咒罵", "ipa": "/blæsˈfiːm/", "trans": "curse", "col": "blaspheme God", "ex": "He was accused of blaspheming the holy name.", "pos": "v."},
    "blasphemer": {"def": "褻瀆者、咒罵者", "ipa": "/blæsˈfiːmə/", "trans": "blaspheme (動詞)", "col": "convicted blasphemer", "ex": "The convicted blasphemer was forced to leave the community.", "pos": "n."},
    "blasphemous": {"def": "褻瀆的、不敬的", "ipa": "/ˈblæsfəməs/", "trans": "blasphemy", "col": "blasphemous language", "ex": "His views were considered blasphemous by the church.", "pos": "adj."},
    "blasphemy": {"def": "褻瀆、神明不敬的言行 (單數)", "ipa": "/ˈblæsfəmi/", "trans": "blasphemies (複數)", "col": "accused of blasphemy", "ex": "Blasphemy was a serious crime in the past.", "pos": "n."},
    "blast": {"def": "爆炸、爆風、一陣強風、炸毀、抨擊、強風地 (炸)", "ipa": "/blɑːst/", "trans": "blasted, blasting", "col": "blast wave, sand blast, full blast (全力運轉), blast off (發射)", "ex": "The explosion sent a blast wave through the street.", "pos": "n./v./adv."},
    "blasted": {"def": "被炸後的、(口)該死的、討厭的", "ipa": "/ˈblɑːstɪd/", "trans": "blast (名詞/動詞/副詞)", "col": "blasted nuisance", "ex": "That blasted dog is barking again!", "pos": "adj."},
    "blaster": {"def": "爆破手、噴沙器、(科幻)雷射槍的人 (或物) (槍)", "ipa": "/ˈblɑːstə/", "trans": "weapon", "col": "laser blaster", "ex": "The soldiers were equipped with laser blasters.", "pos": "n./adv."},
    "blasting": {"def": "爆破、枯萎、爆炸的人 (或物) (炸)", "ipa": "/ˈblɑːstɪŋ/", "trans": "blast (名詞/動詞/副詞)", "col": "blasting operations", "ex": "The company is carrying out blasting operations in the quarry.", "pos": "n./adv."},
    "blatancy": {"def": "喧鬧、顯目、露骨", "ipa": "/ˈbleɪtənsi/", "trans": "blatant", "col": "sheer blatancy", "ex": "The sheer blatancy of the lie was shocking.", "pos": "n."},
    "blatant": {"def": "喧鬧的、顯目的、露骨的、公然地 (顯)", "ipa": "/ˈbleɪtənt/", "trans": "obvious", "col": "blatant lie, blatant disregard", "ex": "It was a blatant attempt to influence the jury.", "pos": "adj./adv."},
    "blatantly": {"def": "大聲地、公然地、顯眼地", "ipa": "/ˈbleɪtəntli/", "trans": "blatant (形容詞/副詞)", "col": "blatantly obvious", "ex": "He is blatantly lying about his credentials.", "pos": "adv."},
    "blaze": {"def": "火焰、閃燿、路標、燃燒、閃耀、在火焰中人物、閃耀地 (火)", "ipa": "/bleɪz/", "trans": "blazing", "col": "blaze a trail (開闢道路), in a blaze of glory", "ex": "The dry wood caught fire and began to blaze.", "pos": "n./v./adv."},
    "blazing": {"def": "燃燒的、閃燿的、火熱的的人 (或物) (火)", "ipa": "/ˈbleɪzɪŋ/", "trans": "blaze (名詞/動詞/副詞)", "col": "blazing sun, blazing temper", "ex": "The house was destroyed by the blazing fire.", "pos": "adj./adv."},
    "blazon": {"def": "飾以紋章、宣布、紋章的人、宣布地 (宣布)", "ipa": "/ˈbleɪzn/", "trans": "display", "col": "blazoned with", "ex": "The shield was blazoned with the royal crest.", "pos": "v./n./adv."},
    "bleach": {"def": "漂白劑、漂白、變白、變白的人物、漂白地 (白)", "ipa": "/bliːtʃ/", "trans": "bleaching", "col": "hair bleach, pool bleach", "ex": "She used bleach to get the stains out of her shirt.", "pos": "n./v./adv."},
    "bleaching": {"def": "漂白、變白、變白的人 (或物) (白)", "ipa": "/ˈbliːtʃɪŋ/", "trans": "bleach (名詞/動詞/副詞)", "col": "coral bleaching (珊瑚白化)", "ex": "Coral bleaching is a major environmental problem.", "pos": "n./adv."},
    "bleak": {"def": "荒涼的、淒涼的、冷淡的、淒涼地 (荒涼)", "ipa": "/bliːk/", "trans": "bleakly", "col": "bleak future, bleak landscape", "ex": "The future looks bleak for the company.", "pos": "adj./adv."},
}