import json

# Level 6 Part 5: (Almanac - Ancestor)
L6_PART5 = {
    "almanac": {"def": "年鑑、曆書、氣象預報", "ipa": "/ˈɔːlmənæk/", "trans": "almanacs", "col": "nautical almanac", "ex": "I checked the almanac for the phases of the moon.", "pos": "n."},
    "almighty": {"def": "全能的、巨大的、極大的、上帝、全能者", "ipa": "/ɔːlˈmaɪti/", "trans": "might", "col": "Almighty God", "ex": "The soldiers prayed to Almighty God for protection.", "pos": "adj./n."},
    "almond": {"def": "杏仁、扁桃、杏仁色的", "ipa": "/ˈɑːmənd/", "trans": "almonds", "col": "roasted almonds", "ex": "Can I have some roasted almonds, please?", "pos": "n./adj."},
    "almost": {"def": "幾乎、差不多、幾乎的、差不多的 (幾乎)", "ipa": "/ˈɔːlməʊst/", "trans": "nearly", "col": "almost finished, almost identical, almost every", "ex": "Dinner is almost ready.", "pos": "adv./adj."},
    "alms": {"def": "施捨物、救濟金", "ipa": "/ɑːmz/", "trans": "charity", "col": "give alms to the poor", "ex": "The monk asked for alms in the street.", "pos": "n."},
    "aloft": {"def": "在高處、在空中的、在高處的、在空中的地 (在高處)", "ipa": "/əˈlɒft/", "trans": "high", "col": "held aloft", "ex": "The winners held their trophies aloft.", "pos": "adv./adj."},
    "alone": {"def": "孤獨的、單獨的、獨自的、孤獨地、單獨地 (單獨)", "ipa": "/əˈləʊn/", "trans": "lonely", "col": "leave alone, let alone, stand alone", "ex": "I like to spend some time alone.", "pos": "adj./adv."},
    "along": {"def": "沿著、順著、向前、帶領地、一起地、向前方地 (沿著)", "ipa": "/əˈlɒŋ/", "trans": "long", "col": "along with, all along, go along with", "ex": "We walked along the beach.", "pos": "prep./adv."},
    "alongside": {"def": "在旁邊、橫靠著、與...在一起地、並排地 (在旁邊)", "ipa": "/əˌlɒŋˈsaɪd/", "trans": "beside", "col": "work alongside, alongside with", "ex": "A police car pulled up alongside.", "pos": "adv./prep."},
    "aloof": {"def": "冷淡的、疏遠的、冷淡地、疏遠地 (冷淡)", "ipa": "/əˈluːf/", "trans": "aloofness", "col": "stand aloof, remain aloof", "ex": "She stayed aloof from the others.", "pos": "adj./adv."},
    "aloud": {"def": "大聲地、高聲地", "ipa": "/əˈlaʊd/", "trans": "loud", "col": "read aloud, think aloud", "ex": "Please read the text aloud.", "pos": "adv."},
    "alphabet": {"def": "字母表、初步、基本原理", "ipa": "/ˈælfəbet/", "trans": "alphabetical", "col": "phonetic alphabet, Latin alphabet", "ex": "Learning the alphabet is the first step in reading.", "pos": "n."},
    "alphabetical": {"def": "字母的、依字母順序的、初步的", "ipa": "/ˌælfəˈbetɪkl/", "trans": "alphabet (名詞), alphabetically", "col": "alphabetical order", "ex": "The books are arranged in alphabetical order.", "pos": "adj."},
    "already": {"def": "已經、早已、居然、已經的 (已經)", "ipa": "/ɔːlˈredi/", "trans": "ready", "col": "already done, has already happened", "ex": "I've already eaten.", "pos": "adv./adj."},
    "alright": {"def": "好吧、沒問題的、正確的、正確地、好吧 (好吧)", "ipa": "/ɔːlˈraɪt/", "trans": "okay", "col": "it's alright, feel alright", "ex": "Is everything alright?", "pos": "adj./adv./int."},
    "also": {"def": "也、同樣、而且、也、同樣地、而且地 (也)", "ipa": "/ˈɔːlsəʊ/", "trans": "too", "col": "but also, as well as", "ex": "He is also a talented musician.", "pos": "adv./conj."},
    "altar": {"def": "祭壇、聖壇", "ipa": "/ˈɔːltə/", "trans": "shrine", "col": "high altar", "ex": "The priest knelt before the high altar.", "pos": "n."},
    "alter": {"def": "改變、更改、變更、改造", "ipa": "/ˈɔːltə/", "trans": "alteration, alternative", "col": "alter plans, alter a dress", "ex": "We had to alter our travel plans.", "pos": "v."},
    "alteration": {"def": "改變、變更、改造、修補", "ipa": "/ˌɔːltəˈreɪʃn/", "trans": "alter (動詞)", "col": "minor alteration", "ex": "We need to make some minor alterations to the design.", "pos": "n."},
    "altercation": {"def": "爭吵、爭端、紛爭", "ipa": "/ˌɔːltəˈkeɪʃn/", "trans": "dispute", "col": "heated altercation", "ex": "They had a heated altercation over money.", "pos": "n."},
    "alternate": {"def": "交替的、輪流的、間隔的、代替者、候補、交替、輪流、代理的 (交替)", "ipa": "/ˈɔːltəneɪt/ (v.) /ɔːlˈtɜːnət/ (adj./n.)", "trans": "alternation, alternative", "col": "alternate days, alternate current (AC)", "ex": "The rain alternated with sunshine.", "pos": "v./adj./n./adv."},
    "alternation": {"def": "交替、輪流、間隔", "ipa": "/ˌɔːltəˈneɪʃn/", "trans": "alternate (名詞/動詞/形容詞/副詞)", "col": "season alternation", "ex": "The alternation of day and night is caused by the earth's rotation.", "pos": "n."},
    "alternative": {"def": "供選擇的、替代的、另類的、選擇、替代方案、二者擇一、替代地 (替代)", "ipa": "/ɔːlˈtɜːnətɪv/", "trans": "alternatively, alternate", "col": "alternative energy, alternative medicine", "ex": "Is there an alternative to this plan?", "pos": "adj./n./adv."},
    "alternatively": {"def": "二者擇一地、或者", "ipa": "/ɔːlˈtɜːnətɪvli/", "trans": "alternative (形容詞/名詞/副詞), alternate", "col": "alternatively suggested", "ex": "Alternatively, we could go by train.", "pos": "adv."},
    "although": {"def": "雖然、儘管、即使", "ipa": "/ɔːlˈðəʊ/", "trans": "though", "col": "although true", "ex": "Although it was raining, they went out.", "pos": "conj."},
    "altitude": {"def": "高度、海拔、高處", "ipa": "/ˈæltɪtjuːd/", "trans": "height", "col": "high altitude", "ex": "The plane is flying at a high altitude.", "pos": "n."},
    "alto": {"def": "男高音、女低音、女低音的、中音的", "ipa": "/ˈæltəʊ/", "trans": "altos", "col": "alto saxophone", "ex": "She sings alto in the choir.", "pos": "n./adj."},
    "altogether": {"def": "總共、完全、總之、全面、全然、總共地 (總共)", "ipa": "/ˌɔːltəˈɡeðə/", "trans": "completely", "col": "altogether different, in the altogether (裸體)", "ex": "That's altogether another matter.", "pos": "adv./n."},
    "altruism": {"def": "利他主義、無私", "ipa": "/ˈæltruɪzəm/", "trans": "altruistic", "col": "spirit of altruism", "ex": "He is motivated by pure altruism.", "pos": "n."},
    "altruistic": {"def": "利他的、無私的", "ipa": "/ˌæltruˈɪstɪk/", "trans": "altruism (名詞)", "col": "altruistic behavior", "ex": "They made an altruistic decision to help the poor.", "pos": "adj."},
    "aluminum": {"def": "鋁、鋁製的", "ipa": "/əˈluːmɪnəm/", "trans": "aluminium", "col": "aluminum foil, aluminum can", "ex": "The frame is made of lightweight aluminum.", "pos": "n./adj."},
    "alumnus": {"def": "校友、畢業生 (單數)", "ipa": "/əˈlʌmnəs/", "trans": "alumni (複數)", "col": "university alumnus", "ex": "He is an alumnus of Harvard University.", "pos": "n."},
    "alumni": {"def": "校友、畢業生 (複數)", "ipa": "/əˈlʌmnaɪ/", "trans": "alumnus (單數)", "col": "alumni association", "ex": "The school has a very active alumni association.", "pos": "n."},
    "always": {"def": "總是、永遠、一直、永遠地 (總是)", "ipa": "/ˈɔːlweɪz/", "trans": "ever", "col": "as always, for always", "ex": "She is always late.", "pos": "adv./n."},
    "am/is/are": {"def": "是、在、表示、存在的人 (或物)、正在、現在地 (是)", "ipa": "/æm/ /ɪz/ /ɑː/", "trans": "be", "col": "be able to, be born, be aware of", "ex": "I am a student.", "pos": "v./n./adv."},
    "amalgamate": {"def": "合併、混合、汞齊化", "ipa": "/əˈmælɡəmeɪt/", "trans": "amalgamation", "col": "amalgamate companies", "ex": "The two companies decided to amalgamate.", "pos": "v."},
    "amalgamation": {"def": "合併、混合、混合物", "ipa": "/əˌmælɡəˈmeɪʃn/", "trans": "amalgamate (動詞)", "col": "business amalgamation", "ex": "The amalgamation of the two departments was successful.", "pos": "n."},
    "amass": {"def": "積聚、積累、堆積", "ipa": "/əˈmæs/", "trans": "accumulate", "col": "amass wealth, amass evidence", "ex": "He managed to amass a large fortune.", "pos": "v."},
    "amateur": {"def": "業餘愛好者、外行、業餘的、非職業的、外行的、愛好者的、愛好者地 (業餘)", "ipa": "/ˈæmətə/", "trans": "amateurish", "col": "amateur photographer, purely amateur", "ex": "He is an amateur photographer.", "pos": "n./adj./adv."},
    "amateurish": {"def": "業餘的、外行的、拙劣的", "ipa": "/ˌæməˈtɜːrɪʃ/", "trans": "amateur (名詞/形容詞/副詞)", "col": "amateurish performance", "ex": "The play was a bit amateurish.", "pos": "adj."},
    "amaze": {"def": "使大為驚奇、使驚愕、使人大感意外、驚奇、驚愕、驚奇地、意外地 (驚奇)", "ipa": "/əˈmeɪz/", "trans": "amazement, amazing", "col": "amaze everyone, truly amazed", "ex": "She amazed everyone with her talent.", "pos": "v./n./adv."},
    "amazed": {"def": "大為驚奇的、吃驚的", "ipa": "/əˈmeɪzd/", "trans": "amaze (動詞/名詞/副詞), amazement", "col": "amazed by", "ex": "We were amazed by his progress.", "pos": "adj."},
    "amazement": {"def": "大為驚奇、驚愕、吃驚", "ipa": "/əˈmeɪzmənt/", "trans": "amaze (動詞/名詞/副詞), amazing", "col": "stare in amazement", "ex": "She stared at him in amazement.", "pos": "n."},
    "amazing": {"def": "令人驚奇的、了不起的、驚人的", "ipa": "/əˈmeɪzɪŋ/", "trans": "amaze (動詞/名詞/副詞), amazement", "col": "amazing discovery", "ex": "That's an amazing discovery.", "pos": "adj."},
    "ambassador": {"def": "大使、特使、使者", "ipa": "/æmˈbæsədə/", "trans": "embassy", "col": "ambassador to, goodwill ambassador", "ex": "He was appointed as the ambassador to China.", "pos": "n."},
    "amber": {"def": "琥珀色、琥珀、琥珀製的、琥珀色的", "ipa": "/ˈæmbə/", "trans": "yellow", "col": "amber light, amber necklace", "ex": "The fly was trapped in amber.", "pos": "n./adj."},
    "ambience/ambiance": {"def": "氣氛、周圍環境", "ipa": "/ˈæmbiəns/", "trans": "ambient", "col": "pleasant ambience", "ex": "The restaurant has a very pleasant ambience.", "pos": "n."},
    "ambient": {"def": "周圍的、環境的、周圍、環境、周圍地、環境地 (周圍)", "ipa": "/ˈæmbiənt/", "trans": "ambience", "col": "ambient light, ambient noise", "ex": "The ambient light was very soft.", "pos": "adj./n./adv."},
    "ambiguity": {"def": "模稜兩可、含糊、含糊的詞 (或事)", "ipa": "/ˌæmbɪˈɡjuːəti/", "trans": "ambiguous", "col": "room for ambiguity", "ex": "There is no room for ambiguity in the contract.", "pos": "n."},
    "ambiguous": {"def": "模稜兩可的、含糊不清的、不明確的", "ipa": "/æmˈbɪɡjuəs/", "trans": "ambiguity (名詞)", "col": "ambiguous answer", "ex": "His answer was very ambiguous.", "pos": "adj."},
    "ambition": {"def": "野心、雄心、抱負、志向、雄心勃勃的人 (或事)、大聲地、有力地、名聲、稱號 (野心)", "ipa": "/æmˈbɪʃn/", "trans": "ambitious, ambitiously", "col": "burning ambition, political ambition", "ex": "His ambition is to become the prime minister.", "pos": "n./adv."},
    "ambitious": {"def": "有野心的、雄心勃勃的、艱巨的", "ipa": "/æmˈbɪʃəs/", "trans": "ambition (名詞/副詞), ambitiously", "col": "ambitious plan", "ex": "They have an ambitious plan for the future.", "pos": "adj."},
    "ambitiously": {"def": "有野心地、雄心勃勃地、艱巨地", "ipa": "/æmˈbɪʃəsli/", "trans": "ambitious (形容詞), ambition", "col": "planned ambitiously", "ex": "They planned the project ambitiously.", "pos": "adv."},
    "ambivalence": {"def": "矛盾、猶豫不決、猶豫", "ipa": "/æmˈbɪvələns/", "trans": "ambivalent", "col": "feeling of ambivalence", "ex": "She felt a certain ambivalence towards her job.", "pos": "n."},
    "ambivalent": {"def": "矛盾的、猶豫不決的、含糊不清的", "ipa": "/æmˈbɪvələnt/", "trans": "ambivalence (名詞)", "col": "ambivalent attitude", "ex": "He has an ambivalent attitude towards modern art.", "pos": "adj."},
    "amble": {"def": "緩行、漫步、從容步行", "ipa": "/ˈæmbl/", "trans": "stroll", "col": "gentle amble", "ex": "We took a gentle amble through the woods.", "pos": "v./n."},
    "ambulance": {"def": "救護車", "ipa": "/ˈæmbjələns/", "trans": "ambulances", "col": "call an ambulance", "ex": "Call an ambulance immediately!", "pos": "n."},
    "ambulatory": {"def": "步行的、流動的、能走路的、迴廊", "ipa": "/ˈæmbjələtəri/", "trans": "ambulate", "col": "ambulatory care", "ex": "The patient is now ambulatory.", "pos": "adj./n."},
    "ambush": {"def": "埋伏、伏擊、埋伏的人 (或事)、伏擊、埋伏、潛伏地、悄悄地 (埋伏)", "ipa": "/ˈæmbʊʃ/", "trans": "ambushed", "col": "set an ambush, in ambush", "ex": "They were caught in an ambush.", "pos": "n./v./adv."},
    "ameliorate": {"def": "改善、改良、變好", "ipa": "/əˈmiːliəreɪt/", "trans": "amelioration", "col": "ameliorate conditions", "ex": "The new law is designed to ameliorate the living conditions of the poor.", "pos": "v."},
    "amenable": {"def": "順從的、願接受的、經得起檢驗的", "ipa": "/əˈmiːnəbl/", "trans": "compliant", "col": "amenable to advice", "ex": "She is very amenable to advice.", "pos": "adj."},
    "amend": {"def": "修改、修訂、改進、補償", "ipa": "/əˈmend/", "trans": "amendment", "col": "amend a law, make amends (補償)", "ex": "The committee decided to amend the rules.", "pos": "v."},
    "amendment": {"def": "修改、修訂、修正案、改進", "ipa": "/əˈmendmənt/", "trans": "amend (動詞)", "col": "constitutional amendment", "ex": "The first amendment to the constitution protects free speech.", "pos": "n."},
    "amenity": {"def": "設施、宜人之處、禮儀、和藹", "ipa": "/əˈmiːnəti/", "trans": "amenities", "col": "public amenity, basic amenities", "ex": "The town offers many public amenities.", "pos": "n."},
    "amiable": {"def": "和藹可親的、友好的、親切的", "ipa": "/ˈeɪmiəbl/", "trans": "amiably", "col": "amiable person", "ex": "She is a very amiable and helpful person.", "pos": "adj."},
    "amiably": {"def": "和藹地、友好地、親切地", "ipa": "/ˈeɪmiəbli/", "trans": "amiable (形容詞)", "col": "chat amiably", "ex": "They chatted amiably over coffee.", "pos": "adv."},
    "amicable": {"def": "友好的、和諧的、平息的", "ipa": "/ˈæmɪkəbl/", "trans": "amicably", "col": "amicable settlement", "ex": "They reached an amicable settlement of the dispute.", "pos": "adj."},
    "amicably": {"def": "友好地、和諧地、平息地", "ipa": "/ˈæmɪkəbli/", "trans": "amicable (形容詞)", "col": "settle amicably", "ex": "The case was settled amicably out of court.", "pos": "adv."},
    "amid/amidst": {"def": "其中、在...中間、被...環繞", "ipa": "/əˈmɪd/", "trans": "among", "col": "amid chaos, amidst rumors", "ex": "The building stands amid the chaos of the city.", "pos": "prep."},
    "amiss": {"def": "錯誤的、有缺陷的、不當的、錯誤地、有缺陷地、不當地 (錯誤)", "ipa": "/əˈmɪs/", "trans": "wrong", "col": "something is amiss, take it amiss (誤解)", "ex": "I felt that something was amiss.", "pos": "adj./adv."},
    "ammonia": {"def": "氨、氨水", "ipa": "/əˈməʊniə/", "trans": "ammonium", "col": "smell of ammonia", "ex": "Ammonia has a very strong and sharp smell.", "pos": "n."},
    "ammunition": {"def": "彈藥、軍火、(辯論中的)把柄", "ipa": "/ˌæmjuˈnɪʃn/", "trans": "ammo", "col": "live ammunition", "ex": "They were running low on ammunition.", "pos": "n."},
    "amnesia": {"def": "健忘症、記憶缺失", "ipa": "/æmˈniːziə/", "trans": "memory loss", "col": "temporary amnesia", "ex": "He suffered from temporary amnesia after the accident.", "pos": "n."},
    "amnesty": {"def": "特赦、赦免、赦免權、赦免、給予特赦", "ipa": "/ˈæmnəsti/", "trans": "pardon", "col": "general amnesty, Amnesty International (國際特赦組織)", "ex": "The government granted an amnesty to all political prisoners.", "pos": "n./v."},
    "among/amongst": {"def": "其中、在...中間、為...所共有、在...之間地、其中地 (其中)", "ipa": "/əˈmʌŋ/", "trans": "amid", "col": "among others, from among, share among", "ex": "She is among the best students in the class.", "pos": "prep./adv."},
    "amoral": {"def": "與道德無關的、是非不分的", "ipa": "/ˌeɪˈmɒrəl/", "trans": "immoral (不道德的)", "col": "amoral attitude", "ex": "Children are often seen as being amoral.", "pos": "adj."},
    "amorous": {"def": "多情的、愛情的、好色的", "ipa": "/ˈæmərəs/", "trans": "loving", "col": "amorous letter", "ex": "He sent her an amorous letter.", "pos": "adj."},
    "amorphous": {"def": "無定形的、雜亂的、非結晶的", "ipa": "/əˈmɔːfəs/", "trans": "shapeless", "col": "amorphous shape", "ex": "The cloud had an amorphous shape.", "pos": "adj."},
    "amount": {"def": "總額、量、數量、總計、等於、相當、總計、數量、相等地 (總計)", "ipa": "/əˈmaʊnt/", "trans": "amounted", "col": "small amount, large amount, amount to", "ex": "What is the total amount of the bill?", "pos": "n./v./adv."},
    "ampere": {"def": "安培", "ipa": "/ˈæmpeə/", "trans": "amp", "col": "ampere meter", "ex": "Ampere is the unit of electric current.", "pos": "n."},
    "amphibious": {"def": "兩棲的、水陸兩用的、具有雙重性格的", "ipa": "/æmˈfɪbiəs/", "trans": "amphibian", "col": "amphibious vehicle", "ex": "Frogs are amphibious animals.", "pos": "adj."},
    "amphitheatre/amphitheater": {"def": "圓形劇場、競技場、梯形教室", "ipa": "/ˈæmfɪθɪətə/", "trans": "arena", "col": "Roman amphitheatre", "ex": "The ruins of the Roman amphitheatre are still visible.", "pos": "n."},
    "ample": {"def": "寬敞的、豐富的、充足的", "ipa": "/ˈæmpl/", "trans": "amply", "col": "ample time, ample evidence", "ex": "We have ample time to catch the train.", "pos": "adj."},
    "amplification": {"def": "擴大、放大、增強、詳述", "ipa": "/ˌæmplɪfɪˈkeɪʃn/", "trans": "amplify (動詞), amplifier", "col": "sound amplification", "ex": "The speech needed no further amplification.", "pos": "n."},
    "amplifier": {"def": "放大器、擴音器", "ipa": "/ˈæmplɪfaɪə/", "trans": "amplify (動詞), amplification", "col": "guitar amplifier", "ex": "Connect the microphone to the amplifier.", "pos": "n."},
    "amplify": {"def": "擴大、放大、詳述", "ipa": "/ˈæmplɪfaɪ/", "trans": "amplification, amplifier", "col": "amplify the signal", "ex": "The music was amplified through large speakers.", "pos": "v."},
    "amply": {"def": "充足地、豐富地、詳細地", "ipa": "/ˈæmpli/", "trans": "ample (形容詞)", "col": "amply rewarded", "ex": "His hard work was amply rewarded.", "pos": "adv."},
    "amputate": {"def": "截肢、切除", "ipa": "/ˈæmpjuteɪt/", "trans": "amputation", "col": "amputate a leg", "ex": "The surgeon had to amputate his left leg.", "pos": "v."},
    "amputation": {"def": "截肢、切除", "ipa": "/ˌæmpjuˈteɪʃn/", "trans": "amputate (動詞)", "col": "necessary amputation", "ex": "He is recovering from the amputation.", "pos": "n."},
    "amulet": {"def": "護身符、避邪物", "ipa": "/ˈæmjulət/", "trans": "charm", "col": "lucky amulet", "ex": "He wears a lucky amulet around his neck.", "pos": "n."},
    "amuse": {"def": "逗樂、使發笑、消遣、逗笑的人 (或事)、大聲地、出色地、名聲、稱號 (逗樂)", "ipa": "/əˈmjuːz/", "trans": "amusement, amusing", "col": "amuse oneself, highly amused", "ex": "The joke didn't amuse him at all.", "pos": "v./n./adv."},
    "amusement": {"def": "娛樂、消遣、逗樂、樂趣", "ipa": "/əˈmjuːzmənt/", "trans": "amuse (動詞/名詞/副詞), amusing", "col": "amusement park, sense of amusement", "ex": "To my amusement, he forgot his own name.", "pos": "n."},
    "amusing": {"def": "有趣的、好笑的、逗樂的", "ipa": "/əˈmjuːzɪŋ/", "trans": "amuse (動詞/名詞/副詞), amusement", "col": "amusing story", "ex": "He told us an amusing story about his dog.", "pos": "adj."},
    "anachronism": {"def": "落伍的人 (或事)、時代錯誤、不合時代的人 (或事)", "ipa": "/əˈnækrənɪzəm/", "trans": "outdated", "col": "historical anachronism", "ex": "The use of a computer in the 19th-century setting was an anachronism.", "pos": "n."},
    "anaemia/anemia": {"def": "貧血、貧血症、無活力", "ipa": "/əˈniːmiə/", "trans": "anaemic", "col": "suffer from anaemia", "ex": "She is receiving treatment for anaemia.", "pos": "n."},
    "anaerobic": {"def": "厭氧的、(生)無氧生物、厭氧地", "ipa": "/ˌæneəˈrəʊbɪk/", "trans": "anaerobics", "col": "anaerobic exercise", "ex": "Weightlifting is a form of anaerobic exercise.", "pos": "adj./n./adv."},
    "anaesthesia/anesthesia": {"def": "麻醉、麻木", "ipa": "/ˌænəˈsθiːziə/", "trans": "anaesthetic", "col": "under anaesthesia", "ex": "The patient was under general anaesthesia during the surgery.", "pos": "n."},
    "anaesthetic/anesthetic": {"def": "麻醉劑、麻藥、麻醉的、麻木的、麻醉劑的", "ipa": "/ˌænəsˈθetɪk/", "trans": "anaesthesia", "col": "local anaesthetic, general anaesthetic", "ex": "The dentist gave me a local anaesthetic.", "pos": "n./adj."},
    "anagram": {"def": "迴文、易位構詞、變位詞", "ipa": "/ˈænəɡræm/", "trans": "anagrams", "col": "simple anagram", "ex": "The word 'silent' is an anagram of 'listen'.", "pos": "n."},
    "analgesic": {"def": "止痛劑、鎮痛劑、止痛的、無痛的", "ipa": "/ˌænəlˈdʒiːsɪk/", "trans": "painkiller", "col": "strong analgesic", "ex": "Aspiring is a common analgesic.", "pos": "n./adj."},
    "analogize": {"def": "類推、類比、解釋", "ipa": "/əˈnælədʒaɪz/", "trans": "analogy", "col": "analogize with", "ex": "He tried to analogize the current situation with the past events.", "pos": "v."},
    "analogy": {"def": "類比、類推、類似、(生物)同功", "ipa": "/əˈnælədʒi/", "trans": "analogous", "col": "draw an analogy, by analogy with", "ex": "He drew an analogy between the brain and a computer.", "pos": "n."},
    "analyse/analyze": {"def": "分析、分解、研究、心理分析", "ipa": "/ˈænəlaɪz/", "trans": "analysis, analyst", "col": "analyze results, analyze data", "ex": "The chemist will analyze the sample.", "pos": "v."},
    "analysis": {"def": "分析、解析、分解、心理分析、分析家的、分析的、分析地 (分析)", "ipa": "/əˈnæləsɪs/", "trans": "analyse (動詞), analytical", "col": "data analysis, in final analysis", "ex": "A detailed analysis of the situation is necessary.", "pos": "n./adj./adv."},
    "analyst": {"def": "分析師、分解者、心理分析者", "ipa": "/ˈænələst/", "trans": "analyse (動詞), analysis", "col": "financial analyst, political analyst", "ex": "He works as a financial analyst for a bank.", "pos": "n."},
    "analytical/analytic": {"def": "分析的、解析的、善於分析的", "ipa": "/ˌænəˈlɪtɪkl/", "trans": "analysis, analyse", "col": "analytical mind, analytical skills", "ex": "She has a very analytical mind.", "pos": "adj."},
    "anarchy": {"def": "混亂、無政府狀態、無政府", "ipa": "/ˈænəki/", "trans": "anarchist", "col": "state of anarchy", "ex": "The country was in a state of anarchy after the war.", "pos": "n."},
    "anatomy": {"def": "解剖學、骨骼、分析、構造", "ipa": "/əˈnætəmi/", "trans": "anatomical", "col": "human anatomy", "ex": "He is studying human anatomy at the medical school.", "pos": "n."},
    "ancestor": {"def": "祖先、祖宗、原型、先驅者、祖傳的、老式的、先祖地 (祖先)", "ipa": "/ˈænsestə/", "trans": "ancestry, ancestral", "col": "distant ancestor, common ancestor", "ex": "His ancestors came from Ireland.", "pos": "n./adj./adv."},
}