import json

# Level 5 Part 5: (Entity - Illusion)
L5_PART5 = {
    "entity": {"def": "實體、存在、本質", "ipa": "/ˈentəti/", "trans": "entities", "col": "legal entity, separate entity", "ex": "The two companies are separate legal entities.", "pos": "n."},
    "external": {"def": "外部的、外面的、外國的、外部、外觀", "ipa": "/ɪkˈstɜːnl/", "trans": "externally", "col": "external factor, external drive", "ex": "The project was affected by several external factors.", "pos": "adj./n."},
    "diplomatic": {"def": "外交的、有外交手腕的、老練的", "ipa": "/ˌdɪpləˈmætɪk/", "trans": "diplomat, diplomacy", "col": "diplomatic relations, diplomatic immunity", "ex": "The two countries have broken off diplomatic relations.", "pos": "adj."},
    "entrepreneur": {"def": "企業家、主辦人", "ipa": "/ˌɒntrəprəˈnɜː/", "trans": "entrepreneurship", "col": "successful entrepreneur", "ex": "He is a successful entrepreneur in the tech industry.", "pos": "n."},
    "extinct": {"def": "滅絕的、絕種的、熄滅的", "ipa": "/ɪkˈstɪŋkt/", "trans": "extinction", "col": "extinct species, extinct volcano", "ex": "Dinosaurs became extinct millions of years ago.", "pos": "adj."},
    "gathering": {"def": "聚會、集會、採集、收穫", "ipa": "/ˈɡæðərɪŋ/", "trans": "gather (動詞)", "col": "social gathering, family gathering", "ex": "There was a large social gathering at the hotel.", "pos": "n."},
    "idiot": {"def": "白痴、笨蛋、傻瓜", "ipa": "/ˈɪdiət/", "trans": "idiotic", "col": "complete idiot", "ex": "I felt like a complete idiot when I realized my mistake.", "pos": "n."},
    "interior": {"def": "內部的、內地的、內政的、內部、內地、內景", "ipa": "/ɪnˈtɪəriə/", "trans": "internally", "col": "interior design, Department of the Interior", "ex": "The interior of the building is beautifully decorated.", "pos": "adj./n."},
    "generate": {"def": "產生、發生、引起、導致", "ipa": "/ˈdʒenəreɪt/", "trans": "generator, generation", "col": "generate power, generate income", "ex": "The company hopes to generate more income this year.", "pos": "v."},
    "illusion": {"def": "錯覺、幻覺、虛假的外觀、幻想", "ipa": "/ɪlˈuːʒn/", "trans": "illusory", "col": "optical illusion, under the illusion", "ex": "She was under the illusion that he loved her.", "pos": "n."},
    "bide": {"def": "等待、停留、居住、忍受", "ipa": "/baɪd/", "trans": "biding", "col": "bide one's time", "ex": "He is biding his time until the right opportunity arises.", "pos": "v."},
    "big": {"def": "大的、重要的、大方的、大量地、大大地、誇大地、大亨、重要人物", "ipa": "/bɪɡ/", "trans": "bigger, biggest", "col": "big deal, big name", "ex": "He has a big house in the country.", "pos": "adj./adv./n."},
    "bigamy": {"def": "重婚(罪)", "ipa": "/ˈbɪɡəmi/", "trans": "bigamist", "col": "commit bigamy", "ex": "He was charged with bigamy.", "pos": "n."},
    "bill": {"def": "帳單、議案、鈔票、鳥嘴、廣告、開帳單、宣布", "ipa": "/bɪl/", "trans": "billing", "col": "pay the bill, dollar bill, tax bill", "ex": "I asked the waiter for the bill.", "pos": "n./v."},
    "bimonthly": {"def": "兩月一次地、每月兩次地、兩月一次的、每月兩次的、雙月刊", "ipa": "/baɪˈmʌnθli/", "trans": "monthly", "col": "bimonthly magazine", "ex": "The magazine is published bimonthly.", "pos": "adv./adj./n."},
    "bind": {"def": "捆、綁、限制、使黏合、凝聚、束縛、困境、煩惱", "ipa": "/baɪnd/", "trans": "binding, binder", "col": "bind together, in a bind", "ex": "The contract binds the two parties to the agreement.", "pos": "v./n."},
    "binder": {"def": "裝訂機、活頁夾、黏合劑、捆縛者", "ipa": "/ˈbaɪndə/", "trans": "bind (動詞)", "col": "three-ring binder", "ex": "Put the documents in a three-ring binder.", "pos": "n."},
    "binding": {"def": "裝訂、捆綁、鑲邊、有約束力的、捆綁的、裝訂的", "ipa": "/ˈbaɪndɪŋ/", "trans": "bind (動詞)", "col": "legally binding", "ex": "The contract is legally binding.", "pos": "n./adj."},
    "binge": {"def": "狂鬧、狂歡、放縱、放縱、狂飲、大吃大喝", "ipa": "/bɪndʒ/", "trans": "bingeing", "col": "binge eating, binge watching", "ex": "He went on a drinking binge after he lost his job.", "pos": "n./v."},
    "biography": {"def": "傳記", "ipa": "/baɪˈɒɡrəfi/", "trans": "biographical, biographer", "col": "official biography", "ex": "She is writing an official biography of the president.", "pos": "n."},
    "biologist": {"def": "生物學家", "ipa": "/baɪˈɒlədʒɪst/", "trans": "biology", "col": "marine biologist", "ex": "He is a marine biologist at the research institute.", "pos": "n."},
    "biology": {"def": "生物學、生物、生態學", "ipa": "/baɪˈɒlədʒi/", "trans": "biologist, biological", "col": "molecular biology, marine biology", "ex": "She is studying molecular biology at the university.", "pos": "n."},
    "bipartisan": {"def": "兩黨的、代表兩黨的", "ipa": "/ˌbaɪpɑːtɪˈzæn/", "trans": "partisan", "col": "bipartisan support", "ex": "The bill has bipartisan support in the congress.", "pos": "adj."},
    "bird": {"def": "鳥、禽、傢伙、少女、捕鳥、觀察鳥", "ipa": "/bɜːd/", "trans": "birds, birdie", "col": "early bird, rare bird", "ex": "The early bird catches the worm.", "pos": "n./v."},
    "birth": {"def": "出生、出身、起源、產生、給予...生命、產生", "ipa": "/bɜːθ/", "trans": "births", "col": "give birth to, date of birth, birth control", "ex": "She gave birth to a healthy baby boy.", "pos": "n./v."},
    "biscuit": {"def": "餅乾、淡褐色、軟餅、海綿狀的", "ipa": "/ˈbɪskɪt/", "trans": "biscuits", "col": "chocolate biscuit", "ex": "Would you like a chocolate biscuit?", "pos": "n./adj."},
    "bishop": {"def": "主教、(西洋棋)象", "ipa": "/ˈbɪʃəp/", "trans": "bishops", "col": "Catholic bishop", "ex": "He was appointed as the Catholic bishop of the city.", "pos": "n."},
    "bit": {"def": "小片、小量、硬幣、比特(位元)、一點兒、有些、控制、套上馬嚼子", "ipa": "/bɪt/", "trans": "bits, bitty", "col": "a bit of, bit by bit", "ex": "I'm a bit tired today.", "pos": "n./adv./v."},
    "bitch": {"def": "母狗、潑婦、令人討厭的女人、抱怨、訴苦、發牢騷、糟糕地", "ipa": "/bɪtʃ/", "trans": "bitchy", "col": "son of a bitch", "ex": "Don't be such a bitch.", "pos": "n./v./adv."},
    "bite": {"def": "咬、一口之量、刺痛、餌、咬、叮、螯、上鉤、發生效應", "ipa": "/baɪt/", "trans": "biting, biter", "col": "bite off, bite one's tongue", "ex": "The dog bit him on the leg.", "pos": "n./v."},
    "bitter": {"def": "苦的、痛苦的、嚴寒的、刻毒的、極其地、非常、苦味、苦啤酒、使變苦、使痛苦", "ipa": "/ˈbɪtə/", "trans": "bitterness, bitterly", "col": "bitter taste, bitter enemy, bitter cold", "ex": "The medicine has a bitter taste.", "pos": "adj./adv./n./v."},
    "bitterly": {"def": "苦澀地、悲痛地、慘烈地、刻骨地", "ipa": "/ˈbɪtəli/", "trans": "bitter (形容詞/副詞/名詞/動詞)", "col": "bitterly cold, weep bitterly", "ex": "She wept bitterly after hearing the news.", "pos": "adv."},
    "bitterness": {"def": "苦味、悲痛、辛辣", "ipa": "/ˈbɪtənəs/", "trans": "bitter (形容詞/副詞/名詞/動詞)", "col": "deep bitterness", "ex": "There was a lot of deep bitterness between the two families.", "pos": "n."},
    "bizarre": {"def": "古怪的、奇異的、異乎尋常的", "ipa": "/bɪˈzɑː/", "trans": "bizarrely", "col": "bizarre behavior", "ex": "He was wearing a bizarre costume.", "pos": "adj."},
    "black": {"def": "黑色的、黑暗的、邪惡的、憂鬱的、黑色、黑人、黑顏料、使變黑、抵制(某廠商)", "ipa": "/blæk/", "trans": "blackness, blacken", "col": "black and white, in the black (獲利)", "ex": "She is wearing a black dress.", "pos": "adj./n./v."},
    "blackboard": {"def": "黑板", "ipa": "/ˈblækbɔːd/", "trans": "chalkboard", "col": "write on the blackboard", "ex": "The teacher wrote the homework on the blackboard.", "pos": "n."},
    "blackmail": {"def": "敲詐、勒索、勒索之款、勒索、敲詐", "ipa": "/ˈblækmeɪl/", "trans": "blackmailer", "col": "emotional blackmail", "ex": "He was charged with blackmail.", "pos": "n./v."},
    "blackout": {"def": "停電、燈火管制、暈倒、新聞封鎖、停放(電力)", "ipa": "/ˈblækaʊt/", "trans": "blackouts", "col": "sudden blackout", "ex": "The city suffered a sudden blackout last night.", "pos": "n."},
    "blade": {"def": "葉片、刀片、劍、槳葉", "ipa": "/bleɪd/", "trans": "blades", "col": "razor blade, rotor blade", "ex": "The lawnmower has a sharp blade.", "pos": "n."},
    "blame": {"def": "責備、過錯、責任、歸咎、責怪、把...歸因於", "ipa": "/bleɪm/", "trans": "blameless", "col": "blame someone for, take the blame", "ex": "Don't blame me for your mistakes.", "pos": "n./v."},
    "blanch": {"def": "使變白、漂白、蒼白、川燙、變白、畏縮", "ipa": "/blɑːntʃ/", "trans": "blanched", "col": "blanch almonds", "ex": "Her face blanched with fear.", "pos": "v."},
    "bland": {"def": "淡而無味的、溫和的、乏味的", "ipa": "/blænd/", "trans": "blandly", "col": "bland diet", "ex": "The food was very bland.", "pos": "adj."},
    "blank": {"def": "空白的、沒表情的、未寫過的、空虛、空白、(彈藥)空包彈、使模糊、使無效、抹去", "ipa": "/blæŋk/", "trans": "blankly", "col": "fill in the blanks, blank stare", "ex": "Please fill in the blanks in the form.", "pos": "adj./n./v."},
    "blanket": {"def": "毯子、面、層、覆蓋層、覆蓋、掩蓋、總括的、全體的", "ipa": "/ˈblæŋkɪt/", "trans": "blankets", "col": "blanket of snow, electric blanket", "ex": "The ground was covered with a thick blanket of snow.", "pos": "n./v./adj."},
    "blare": {"def": "響而刺耳的聲音、閃耀的光、大聲發出的、高聲鳴喇叭、閃耀", "ipa": "/bleə/", "trans": "blaring", "col": "blare out", "ex": "The music blared out from the radio.", "pos": "n./v."},
    "blast": {"def": "一陣強風、爆炸、衝擊波、巨響、大聲播、炸、爆破、毀滅", "ipa": "/blɑːst/", "trans": "blasting", "col": "blast furnace, sand blast", "ex": "The explosion was caused by a powerful blast.", "pos": "n./v."},
    "blatant": {"def": "公然的、明目張膽的、喧鬧的", "ipa": "/ˈbleɪtənt/", "trans": "blatantly", "col": "blatant lie", "ex": "That was a blatant lie.", "pos": "adj."},
    "blaze": {"def": "烈火、火焰、光輝、爆發、燃燒、照耀、宣布、在樹上刻痕、燦爛地燃燒", "ipa": "/bleɪz/", "trans": "blazing", "col": "blaze a trail", "ex": "The fire blazed all night.", "pos": "n./v."},
    "bleach": {"def": "漂白劑、漂白、變白、漂白、變白", "ipa": "/bliːtʃ/", "trans": "bleached", "col": "liquid bleach", "ex": "She used bleach to whiten the sheets.", "pos": "n./v."},
    "bleak": {"def": "蒼白的、陰沉的、荒涼的、暗淡的", "ipa": "/bliːk/", "trans": "bleakness", "col": "bleak future", "ex": "The future looks bleak for the company.", "pos": "adj."},
    "bleed": {"def": "流血、出血、滲出、(錢財等)榨取、洩放(空氣等)", "ipa": "/bliːd/", "trans": "bleeding", "col": "bleed to death", "ex": "His nose started to bleed.", "pos": "v."},
    "blemish": {"def": "瑕疵、缺點、污點、使受損、玷污", "ipa": "/ˈblemɪʃ/", "trans": "blemished", "col": "skin blemish", "ex": "She has a small blemish on her face.", "pos": "n./v."},
    "blend": {"def": "混合、摻和、混合物、搭配、調和、使混合、使調和 (混合)", "ipa": "/blend/", "trans": "blender", "col": "blend in, unique blend of", "ex": "The coffee is a unique blend of three different beans.", "pos": "n./v."},
    "blender": {"def": "攪拌機、果汁機、混合者", "ipa": "/ˈblendə/", "trans": "blend (名詞/動詞)", "col": "electric blender", "ex": "Put the ingredients in the blender.", "pos": "n."},
    "bless": {"def": "為...祈福、祝福、保佑、賦予", "ipa": "/bles/", "trans": "blessing, blessed", "col": "God bless you!", "ex": "May God bless you and your family.", "pos": "v."},
    "blessed": {"def": "受祝福的、神聖的、幸運的", "ipa": "/ˈblesɪd/", "trans": "bless (動詞), blessing", "col": "blessed with", "ex": "He is blessed with a wonderful family.", "pos": "adj."},
    "blessing": {"def": "祝福、賜福、幸事、祈禱", "ipa": "/ˈblesɪŋ/", "trans": "bless (動詞), blessed", "col": "mixed blessing", "ex": "The new law is a mixed blessing for the residents.", "pos": "n."},
    "blind": {"def": "瞎的、盲目的、盲點、百葉窗、隱藏處、使失明、使盲目、使模糊、盲目地、看不見地", "ipa": "/blaɪnd/", "trans": "blindness, blindly", "col": "blind date, blind spot, color blind", "ex": "He has been blind since birth.", "pos": "adj./n./v./adv."},
    "blindfold": {"def": "眼罩、蒙住眼睛、盲目的、魯莽的、盲目地、不加考慮地", "ipa": "/ˈblaɪndfəʊld/", "trans": "blindfolded", "col": "be blindfolded", "ex": "The prisoners were blindfolded and led away.", "pos": "n./v./adj./adv."},
    "blink": {"def": "閃爍、眨眼、一瞬間、眨眼、閃爍、閃亮", "ipa": "/blɪŋk/", "trans": "blinking", "col": "blink of an eye", "ex": "She blinked in the bright sunlight.", "pos": "n./v."},
    "bliss": {"def": "極樂、欣喜、至福、使欣喜", "ipa": "/blɪs/", "trans": "blissful", "col": "domestic bliss", "ex": "Ignorance is bliss.", "pos": "n./v."},
    "blissful": {"def": "極樂的、欣喜的", "ipa": "/ˈblɪsfl/", "trans": "bliss (名詞/動詞), blissfully", "col": "blissful ignorance", "ex": "They lived in blissful ignorance of the trouble ahead.", "pos": "adj."},
    "blister": {"def": "水泡、大水泡、氣泡、使起水泡、使起氣泡、猛烈抨擊、起水泡", "ipa": "/ˈblɪstə/", "trans": "blistering", "col": "get a blister", "ex": "I got a blister on my heel from the new shoes.", "pos": "n./v."},
    "blizzard": {"def": "暴風雪、大風雪、大批、大量", "ipa": "/ˈblɪzəd/", "trans": "blizzards", "col": "severe blizzard", "ex": "The city was hit by a severe blizzard last night.", "pos": "n."},
    "bloat": {"def": "膨脹、腫脹、使漲大、使驕傲、(魚類)燻製、腫脹、充血", "ipa": "/bləʊt/", "trans": "bloated", "col": "bloated stomach", "ex": "Salt can make you bloat.", "pos": "v./n."},
    "block": {"def": "塊、大樓、街區、障礙、阻塞、阻塞、阻止、封鎖、大塊的、阻塞地", "ipa": "/blɒk/", "trans": "blocked, blockage", "col": "block of flats, writer's block, road block", "ex": "The road was blocked by a fallen tree.", "pos": "n./v./adj./adv."},
    "blockade": {"def": "封鎖、障礙物、對...進行封鎖、限制", "ipa": "/blɒˈkeɪd/", "trans": "blockades", "col": "naval blockade, lift a blockade", "ex": "The government imposed a naval blockade on the country.", "pos": "n./v."},
    "blockage": {"def": "阻塞、封鎖、障礙物", "ipa": "/ˈblɒkɪdʒ/", "trans": "block (名詞/動詞/形容詞/副詞)", "col": "nasal blockage", "ex": "The medicine helps to relieve nasal blockage.", "pos": "n."},
    "blond/blonde": {"def": "金髮的、金髮女郎、金色的", "ipa": "/blɒnd/", "trans": "blonder", "col": "blond hair", "ex": "She has blond hair and blue eyes.", "pos": "adj./n."},
    "blood": {"def": "血、血統、生命、親屬、放血、使習於戰鬥", "ipa": "/blʌd/", "trans": "bloody, bloodless", "col": "blood pressure, blood type, blood vessel", "ex": "His blood pressure is a bit high.", "pos": "n./v."},
    "bloodshed": {"def": "流血、殺戮", "ipa": "/ˈblʌdʃed/", "trans": "bloody", "col": "prevent bloodshed", "ex": "The two sides are trying to reach a peace agreement to prevent further bloodshed.", "pos": "n."},
    "bloom": {"def": "花、開花期、青春、細粉、開花、茂盛、繁榮、使開花", "ipa": "/bluːm/", "trans": "blooming", "col": "in full bloom", "ex": "The roses are in full bloom.", "pos": "n./v."},
    "blossom": {"def": "花、開花期、初期、開花、繁榮、發展", "ipa": "/ˈblɒsəm/", "trans": "blossoming", "col": "cherry blossom", "ex": "The cherry blossoms are beautiful in the spring.", "pos": "n./v."},
    "blot": {"def": "墨水漬、污點、汙點、吸乾(墨水)、玷污、變髒", "ipa": "/blɒt/", "trans": "blotted", "col": "blot out", "ex": "Don't blot the page with ink.", "pos": "n./v."},
    "blouse": {"def": "女襯衫、寬鬆的上衣、使寬鬆地垂下", "ipa": "/blaʊz/", "trans": "blouses", "col": "silk blouse", "ex": "She is wearing a white silk blouse.", "pos": "n./v."},
    "blow": {"def": "吹、打擊、爆裂、開花、大吹、風、吹、吹氣、打擊、過度、揮霍", "ipa": "/bləʊ/", "trans": "blowing", "col": "blow out, blow up, blow one's mind", "ex": "The wind was blowing hard.", "pos": "n./v."},
    "blue": {"def": "藍色的、憂鬱的、淫穢的、藍色、青色、制服、使變藍、使憂鬱、藍色地", "ipa": "/bluː/", "trans": "blueness", "col": "out of the blue, blue-collar", "ex": "She has blue eyes.", "pos": "adj./n./v./adv."},
    "blueprint": {"def": "藍圖、設計圖、詳細計畫、製成藍圖、擬訂畫", "ipa": "/ˈbluːprɪnt/", "trans": "blueprinting", "col": "genetic blueprint", "ex": "The architect showed us the blueprint of the new house.", "pos": "n./v."},
    "bluff": {"def": "虛張聲勢、唬人、陡岸、峭壁、虛張聲勢地嚇唬、欺騙、直率的、坦率的、陡峭的", "ipa": "/blʌf/", "trans": "bluffs", "col": "call one's bluff", "ex": "He is just bluffing; he doesn't have any evidence.", "pos": "n./v./adj."},
    "blunder": {"def": "大錯、失策、犯大錯、跌跌撞撞地走、洩漏、搞錯", "ipa": "/ˈblʌndə/", "trans": "blundering", "col": "costly blunder", "ex": "He made a costly blunder in the deal.", "pos": "n./v."},
    "blunt": {"def": "鈍的、直率的、木訥的、使變鈍、使遲鈍、減弱、鈍地、直率地、鈍的東西、雪茄", "ipa": "/blʌnt/", "trans": "bluntly, bluntness", "col": "blunt knife, blunt answer", "ex": "The knife is blunt; it needs sharpening.", "pos": "adj./v./adv./n."},
    "blur": {"def": "模糊、汙點、朦朧、使模糊、玷污、汙損、變模糊", "ipa": "/blɜː/", "trans": "blurry", "col": "blur the lines", "ex": "Speed blurs the scenery.", "pos": "n./v."},
    "blush": {"def": "臉紅、羞愧、泛出紅色、一瞥、臉紅、羞愧、變紅", "ipa": "/blʌʃ/", "trans": "blushing", "col": "blush for, at first blush", "ex": "She blushed with embarrassment.", "pos": "n./v."},
    "board": {"def": "板、甲板、董事會、提供膳宿、乘(船、飛機等)、跨入、登上、在船上 (板)", "ipa": "/bɔːd/", "trans": "boarding", "col": "board of directors, keyboard, on board", "ex": "He is a member of the board of directors.", "pos": "n./v."},
    "boast": {"def": "自誇、誇耀、擁有(值得自豪的人、物)、自誇、吹嘘", "ipa": "/bəʊst/", "trans": "boastful", "col": "boast about, boast that", "ex": "He likes to boast about his achievements.", "pos": "n./v."},
    "boat": {"def": "小船、艇、餐具、乘船、划船、用船運送", "ipa": "/bəʊt/", "trans": "boating", "col": "rowing boat, life boat", "ex": "They went for a boat trip on the lake.", "pos": "n./v."},
    "body": {"def": "身體、屍體、主體、群體、賦與肉體、體現、實質地、身體地", "ipa": "/ˈbɒdi/", "trans": "bodily", "col": "body language, body guard", "ex": "Regular exercise is good for your body.", "pos": "n./v./adv."},
    "bodyguard": {"def": "保鏢、護衛隊", "ipa": "/ˈbɒdiɡɑːd/", "trans": "bodyguards", "col": "private bodyguard", "ex": "The celebrity is always accompanied by several bodyguards.", "pos": "n."},
    "bogus": {"def": "偽造的、假的", "ipa": "/ˈbəʊɡəs/", "trans": "fake", "col": "bogus claim", "ex": "The company was making bogus claims about its products.", "pos": "adj."},
    "boil": {"def": "沸騰、痛處、憤怒、沸點、煮、燒開、沸騰、激動", "ipa": "/bɔɪl/", "trans": "boiled, boiling", "col": "boiling water, boil down to", "ex": "Wait until the water boils before adding the pasta.", "pos": "n./v."},
    "bold": {"def": "大膽的、果斷的、粗體的、顯眼的、大膽地、果斷地、粗體、大膽的行動", "ipa": "/bəʊld/", "trans": "boldness, boldly", "col": "bold decision, bold move", "ex": "Taking the challenge was a bold move.", "pos": "adj./adv./n."},
    "bolster": {"def": "長枕、墊枕、支持、增強、支撐、用墊枕墊", "ipa": "/ˈbəʊlstə/", "trans": "bolstered", "col": "bolster confidence", "ex": "The news bolstered their confidence.", "pos": "n./v."},
    "bolt": {"def": "螺栓、閃電、門閂、急逃、閂上、狼吞虎嚥、突然逃跑、衝、門閂地、突然地", "ipa": "/bəʊlt/", "trans": "bolts", "col": "thunder bolt, nut and bolt", "ex": "She bolted the door before going to bed.", "pos": "n./v./adv."},
    "bomb": {"def": "炸彈、大失敗、投彈、大敗、轟炸、引起轟動", "ipa": "/bɒm/", "trans": "bomber, bombing", "col": "time bomb, atomic bomb", "ex": "The building was destroyed by a powerful bomb.", "pos": "n./v."},
    "bombard": {"def": "轟炸、砲擊、攻擊、(以質子等)撞擊", "ipa": "/bɒmˈbɑːd/", "trans": "bombardment", "col": "bombard with questions", "ex": "The reporters bombarded the politician with questions.", "pos": "v."},
    "bombardment": {"def": "砲擊、轟炸、衝擊", "ipa": "/bɒmˈbɑːdmənt/", "trans": "bombard (動詞)", "col": "heavy bombardment", "ex": "The city was under heavy bombardment all night.", "pos": "n."},
    "bond": {"def": "聯結、證券、束縛、債券、連結、使受債券約束、結合", "ipa": "/bɒnd/", "trans": "bonding", "col": "government bond, strong bond", "ex": "There is a strong bond between the twin brothers.", "pos": "n./v."},
}

with open("batch_l5_p5.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART5, f, ensure_ascii=False, indent=2)
