import json

# Level 6 Part 49: (Breastplate - Brew)
L6_PART49 = {
    "breastplate": {"def": "護胸甲、胸甲 (單數)", "ipa": "/ˈbrestpleɪt/", "trans": "armor", "col": "shining breastplate", "ex": "The knight wore a shining steel breastplate.", "pos": "n."},
    "breaststroke": {"def": "蛙式、蛙泳 (單數)", "ipa": "/ˈbreststrəʊk/", "trans": "swimming", "col": "swim breaststroke", "ex": "He won the 100 meters breaststroke final.", "pos": "n."},
    "breastwork": {"def": "胸牆、掩體 (單數)", "ipa": "/ˈbrestwɜːk/", "trans": "fortification", "col": "defensive breastwork", "ex": "The soldiers built a defensive breastwork of sandbags.", "pos": "n."},
    "breath": {"def": "呼吸、氣息、微風、呼吸的人、氣息地 (氣)", "ipa": "/breθ/", "trans": "breathes, breathing", "col": "take a breath, out of breath, catch one's breath, breath of fresh air (新鮮空氣/耳目一新的事物)", "ex": "She took a deep breath before jumping into the water.", "pos": "n./adv."},
    "breathable": {"def": "可呼吸的、透氣的", "ipa": "/ˈbriːðəbl/", "trans": "breath (名詞/動詞/副詞)", "col": "breathable fabric", "ex": "This jacket is made of a breathable fabric.", "pos": "adj."},
    "breathalyse": {"def": "(英)對...作呼氣酒精測試", "ipa": "/ˈbreθəlaɪz/", "trans": "breathalyser", "col": "breathalyse drivers", "ex": "The police have been breathalysing drivers all evening.", "pos": "v."},
    "breathalyser": {"def": "(英)酒精測試計 (單數)", "ipa": "/ˈbreθəlaɪzə/", "trans": "breathalyse", "col": "positive breathalyser test", "ex": "He failed a breathalyser test and was arrested.", "pos": "n."},
    "breathe": {"def": "呼吸、呼氣、流露、低訴、呼吸的人、呼氣地 (吸)", "ipa": "/briːð/", "trans": "breathing, breathed", "col": "breathe in (吸入), breathe out (呼出), breathe deeply, breathe down someone's neck", "ex": "Try to breathe deeply and relax.", "pos": "v./n./adv."},
    "breather": {"def": "呼吸的人、休息、休憩的人物 (休)", "ipa": "/ˈbriːðə/", "trans": "rest", "col": "take a breather", "ex": "Let's take a quick breather before we finish the job.", "pos": "n./adv."},
    "breathing": {"def": "呼吸、氣息、呼吸的人 (或物) (吸)", "ipa": "/ˈbriːðɪŋ/", "trans": "breathe (動詞/名詞/副詞)", "col": "breathing exercises, breathing apparatus", "ex": "The doctor checked his patient's breathing.", "pos": "n./adv."},
    "breathless": {"def": "喘不過氣的、氣喘吁吁的、屏息的", "ipa": "/ˈbreθləs/", "trans": "out of breath", "col": "breathless with excitement", "ex": "He arrived breathless with the news.", "pos": "adj."},
    "breathlessly": {"def": "屏息地、氣喘吁吁地", "ipa": "/ˈbreθləsli/", "trans": "breathless (形容詞/副詞)", "col": "waiting breathlessly", "ex": "They were waiting breathlessly for the results.", "pos": "adv."},
    "breathlessness": {"def": "氣喘、呼吸困難", "ipa": "/ˈbreθləsnəs/", "trans": "breathless (形容詞/副詞)", "col": "chronic breathlessness", "ex": "Chronic breathlessness can be a symptom of heart disease.", "pos": "n."},
    "breathtaking": {"def": "驚人的、美得驚人的、屏息的人 (或物)", "ipa": "/ˈbreθteɪkɪŋ/", "trans": "stunning", "col": "breathtaking view", "ex": "The view from the top of the mountain was breathtaking.", "pos": "adj./n."},
    "breathtakingly": {"def": "驚人地、美得令人屏息地", "ipa": "/ˈbreθteɪkɪŋli/", "trans": "breathtaking (形容詞/副詞)", "col": "breathtakingly beautiful", "ex": "The scenery was breathtakingly beautiful.", "pos": "adv."},
    "breathy": {"def": "帶氣聲的、呼吸沈重的", "ipa": "/ˈbreθi/", "trans": "breath (名詞/動詞/副詞)", "col": "breathy voice", "ex": "She spoke in a low, breathy voice.", "pos": "adj."},
    "bred": {"def": "(breed的過去式及過去分詞)、培植的", "ipa": "/bred/", "trans": "breed", "col": "pure bred, island bred", "ex": "The plants were bred to resist disease.", "pos": "v./adj."},
    "breech": {"def": "臀部、身後、(槍)後膛、穿褲子的人物、褲子地 (臀)", "ipa": "/briːtʃ/", "trans": "breeches", "col": "breech birth (臀位產), breech loader", "ex": "The ammunition is loaded through the breech of the gun.", "pos": "n./v./adv."},
    "breeches": {"def": "(複)褲、馬褲 (複數)", "ipa": "/ˈbrɪtʃɪz/", "trans": "breech", "col": "riding breeches", "ex": "He was wearing traditional riding breeches.", "pos": "n."},
    "breed": {"def": "品種、種類、繁殖、培植、養育、種類的人 (或物)、繁殖地 (種)", "ipa": "/briːd/", "trans": "breeding, bred", "col": "rare breed, cross breed, ill bred, born and bred", "ex": "Dogs are often bred for their intelligence.", "pos": "n./v./adv."},
    "breeder": {"def": "飼養員、育種者、繁殖者 (單數)", "ipa": "/ˈbriːdə/", "trans": "breed (名詞/動詞/副詞)", "col": "dog breeder, plant breeder", "ex": "He is a famous breeder of racing horses.", "pos": "n."},
    "breeding": {"def": "繁殖、飼養、教養、繁殖的人 (或物) (種)", "ipa": "/ˈbriːdɪŋ/", "trans": "breed (名詞/動詞/副詞)", "col": "breeding ground, good breeding", "ex": "It's a perfect breeding ground for mosquitoes.", "pos": "n./adv."},
    "breeze": {"def": "微風、(口)輕而易舉的事、輕盈地走、微風的人物、微風地 (風)", "ipa": "/briːz/", "trans": "breezy", "col": "light breeze, sea breeze, breezy day, sail through (輕易通過)", "ex": "A light breeze was blowing from the sea.", "pos": "n./v./adv."},
    "breezily": {"def": "輕快地、通風地", "ipa": "/ˈbriːzɪli/", "trans": "breezy (形容詞/副詞)", "col": "spoke breezily", "ex": "He chatted breezily about his holiday plans.", "pos": "adv."},
    "breeziness": {"def": "輕快、通風、微風", "ipa": "/ˈbriːzɪnəs/", "trans": "breezy (形容詞/副詞)", "col": "cheerful breeziness", "ex": "I like the cheerful breeziness of his personality.", "pos": "n."},
    "breezy": {"def": "有微風的、輕快的、活潑的的人 (或物)", "ipa": "/ˈbriːzi/", "trans": "breeze (名詞/動詞/副詞)", "col": "breezy morning", "ex": "It's a lovely breezy morning.", "pos": "adj./adv."},
    "brethren": {"def": "(古)同胞們、教友們 (複數)", "ipa": "/ˈbreðrən/", "trans": "brothers", "col": "dear brethren", "ex": "The priest addressed the dear brethren in the congregation.", "pos": "n."},
    "breve": {"def": "(音)二全音符、(標)音短符號、二全音的人、短音地 (短音)", "ipa": "/briːv/", "trans": "note", "col": "musical breve", "ex": "The musical breve is twice the length of a semibreve.", "pos": "n./adv."},
    "brevity": {"def": "短暫、簡潔、簡練 (單數)", "ipa": "/ˈbrevəti/", "trans": "shortness", "col": "brevity is soul of wit (簡練是智慧的靈魂)", "ex": "He is known for the brevity of his speeches.", "pos": "n."},
    "brew": {"def": "釀造、泡(茶)、調製、醞釀、混合物、釀造的人 (或物)、釀造地 (釀)", "ipa": "/bruː/", "trans": "brewing, brewery", "col": "home brew, brew a pot of tea, trouble is brewing", "ex": "He is brewing a new batch of beer in his basement.", "pos": "v./n./adv."},
}