import json

# Level 6 Part 27: (Bedroom - Beggarly)
L6_PART27 = {
    "bedroom": {"def": "臥室、寢室、臥室的、臥室地 (臥)", "ipa": "/ˈbedruːm/", "trans": "bedrooms", "col": "master bedroom, spare bedroom", "ex": "The house has three large bedrooms.", "pos": "n./adj./adv."},
    "bedside": {"def": "床旁、床邊、床邊的、在床上的地 (床邊)", "ipa": "/ˈbedsaɪd/", "trans": "bedsides", "col": "bedside table, bedside manner (醫生的臨床態度)", "ex": "He kept a lamp on his bedside table.", "pos": "n./adj./adv."},
    "bedspread": {"def": "床罩", "ipa": "/ˈbedspred/", "trans": "coverlet", "col": "quilted bedspread", "ex": "She put a colorful quilted bedspread on the bed.", "pos": "n."},
    "bedstead": {"def": "床架", "ipa": "/ˈbedsted/", "trans": "bed frame", "col": "iron bedstead", "ex": "The old iron bedstead was very heavy.", "pos": "n."},
    "bedtime": {"def": "就寢時間、就寢時間的、在就寢時地 (就寢)", "ipa": "/ˈbedtaɪm/", "trans": "bedtimes", "col": "regular bedtime, bedtime story", "ex": "It's long past your bedtime.", "pos": "n./adj./adv."},
    "bee": {"def": "蜜蜂、忙碌的人、聚會的人、像蜜蜂般的、蜂群的人物 (蜂)", "ipa": "/biː/", "trans": "bees", "col": "busy as a bee, spelling bee (拼字比賽), honey bee", "ex": "The bee buzzed around the flowers.", "pos": "n./adj./v./adv."},
    "beech": {"def": "山毛櫸、山毛櫸木、山毛櫸的、山毛櫸地 (山毛櫸)", "ipa": "/biːtʃ/", "trans": "tree", "col": "beech tree, copper beech", "ex": "The park is filled with ancient beech trees.", "pos": "n./adj./adv."},
    "beef": {"def": "牛肉、肌肉、糾紛、訴苦、牛肉的、強壯的人物、抱怨地 (牛)", "ipa": "/biːf/", "trans": "beefs/beeves", "col": "roast beef, beef cattle, have a beef with (有嫌隙), beef up (加強)", "ex": "I like roast beef with potatoes.", "pos": "n./adj./v./adv."},
    "beefsteak": {"def": "牛排", "ipa": "/ˈbiːfsteɪk/", "trans": "steak", "col": "tender beefsteak", "ex": "He ordered a large tender beefsteak.", "pos": "n."},
    "beefy": {"def": "強壯的、結實的、牛肉般的", "ipa": "/ˈbiːfi/", "trans": "beef (名詞/形容詞/動詞/副詞)", "col": "beefy man", "ex": "He is a beefy man with broad shoulders.", "pos": "adj."},
    "beehive": {"def": "蜂窩、忙碌的場所、像蜂窩般地 (蜂窩)", "ipa": "/ˈbiːhaɪv/", "trans": "beehives", "col": "active beehive", "ex": "The office was like an active beehive in the morning.", "pos": "n./adv."},
    "beekeeper": {"def": "養蜂人", "ipa": "/ˈbiːkiːpə/", "trans": "beekeeping", "col": "local beekeeper", "ex": "The local beekeeper produces delicious organic honey.", "pos": "n."},
    "beekeeping": {"def": "養蜂、養蜂業", "ipa": "/ˈbiːkiːpɪŋ/", "trans": "beekeeper", "col": "hobby beekeeping", "ex": "He started beekeeping as a hobby.", "pos": "n."},
    "beeline": {"def": "直線、快捷路徑、走直線、直接的人物、直接地 (線)", "ipa": "/ˈbiːlaɪn/", "trans": "shortcut", "col": "make a beeline for (直奔)", "ex": "He made a beeline for the bar as soon as he arrived.", "pos": "n./v./adv."},
    "been": {"def": "(be的過去分詞)、在、是", "ipa": "/biːn/", "trans": "be", "col": "have been to", "ex": "I have been to London twice.", "pos": "v."},
    "beep": {"def": "嗶嗶聲、按喇叭、發出嗶聲、發嗶聲的人物、發嗶聲地 (嗶)", "ipa": "/biːp/", "trans": "beeper", "col": "loud beep", "ex": "The microwave gave a loud beep when it was finished.", "pos": "n./v./adv."},
    "beeper": {"def": "呼叫器、傳呼機", "ipa": "/ˈbiːpə/", "trans": "pager", "col": "carry a beeper", "ex": "The doctor carries a beeper for emergencies.", "pos": "n."},
    "beer": {"def": "啤酒、啤酒的一杯 (單數)", "ipa": "/bɪə/", "trans": "beers (複數)", "col": "draft beer, ginger beer, small beer (微不足道的小事)", "ex": "He likes a glass of beer with his meal.", "pos": "n."},
    "beery": {"def": "像啤酒的、滿身酒臭的", "ipa": "/ˈbɪəri/", "trans": "beer", "col": "beery breath", "ex": "He had very beery breath.", "pos": "adj."},
    "beeswax": {"def": "蜂蠟", "ipa": "/ˈbiːzwæks/", "trans": "wax", "col": "pure beeswax", "ex": "The candles are made of pure beeswax.", "pos": "n."},
    "beet": {"def": "甜菜、甜菜根", "ipa": "/biːt/", "trans": "beets", "col": "sugar beet", "ex": "Sugar can be made from sugar beet.", "pos": "n."},
    "beetle": {"def": "甲蟲、木槌、急忙、懸在...上、凸出的、凸出的物、凸出地 (甲)", "ipa": "/ˈbiːtl/", "trans": "beetles", "col": "stag beetle, beetle away (急趕)", "ex": "A small black beetle crawled across the path.", "pos": "n./v./adj./adv."},
    "befall": {"def": "降臨、發生、不幸地發生 (降)", "ipa": "/bɪˈfɔːl/", "trans": "happen to", "col": "befall someone", "ex": "A great disaster befell the city.", "pos": "v./adv."},
    "befit": {"def": "適合、適宜、合身地 (適合)", "ipa": "/bɪˈfɪt/", "trans": "matching", "col": "befit royalty", "ex": "The ceremony was conducted with the dignity that befits royalty.", "pos": "v./adv."},
    "befitting": {"def": "適合的、適當的", "ipa": "/bɪˈfɪtɪŋ/", "trans": "befit (動詞/副詞)", "col": "befitting occasion", "ex": "He dressed in a manner befitting the occasion.", "pos": "adj."},
    "before": {"def": "在其前、之前、以往、在...的前面、在面前的人物、在...之前地 (前)", "ipa": "/bɪˈfɔː/", "trans": "previously", "col": "before long, ever before, day before yesterday", "ex": "Think carefully before you make a decision.", "pos": "prep./conj./adv./n."},
    "beforehand": {"def": "事先、預先地", "ipa": "/bɪˈfɔːhænd/", "trans": "in advance", "col": "planned beforehand", "ex": "I wish you had told me beforehand.", "pos": "adv."},
    "befoul": {"def": "弄髒、污衊", "ipa": "/bɪˈfaʊl/", "trans": "dirty", "col": "befoul the air", "ex": "The factory smoke befouls the local air.", "pos": "v."},
    "befriend": {"def": "待如友、幫助、交朋友的人物、友好地 (友)", "ipa": "/bɪˈfrend/", "trans": "make friends with", "col": "befriend a stranger", "ex": "She befriended the new student.", "pos": "v./adv."},
    "befuddle": {"def": "使昏迷、使困惑、使迷惑", "ipa": "/bɪˈfʌdl/", "trans": "confuse", "col": "befuddled by", "ex": "The complicated instructions only served to befuddle me.", "pos": "v."},
    "beg": {"def": "乞求、乞討、請求、乞丐的人物、卑微地 (乞)", "ipa": "/beɡ/", "trans": "begging, beggar", "col": "beg for money, beg a favor, I beg your pardon", "ex": "He sat on the corner to beg for money.", "pos": "v./n./adv."},
    "beget": {"def": "招致、引起、為...之父", "ipa": "/bɪˈɡet/", "trans": "produce", "col": "beget violence", "ex": "Violence begets violence.", "pos": "v."},
    "beggar": {"def": "乞丐、窮人、小傢伙、使貧窮、乞討的人物、卑躬屈膝地 (丐)", "ipa": "/ˈbeɡə/", "trans": "beggars", "col": "lucky beggar, beggar description (難以形容)", "ex": "The beauty of the sunset beggars description.", "pos": "n./v./adv."},
    "beggarly": {"def": "赤貧的、微薄的、可憐的、赤貧地 (赤貧)", "ipa": "/ˈbeɡəli/", "trans": "beggar (名詞/動詞/副詞)", "col": "beggarly amount", "ex": "He worked all day for a beggarly sum of money.", "pos": "adj./adv."},
}