import json

# Level 6 Part 38: (Bleakly - Blissful)
L6_PART38 = {
    "bleakly": {"def": "荒涼地、淒涼地", "ipa": "/ˈbliːkli/", "trans": "bleak (形容詞/副詞)", "col": "looked bleakly", "ex": "He looked bleakly at the empty room.", "pos": "adv."},
    "bleakness": {"def": "荒涼、淒涼、寒冷", "ipa": "/ˈbliːknəs/", "trans": "bleak (形容詞/副詞)", "col": "sheer bleakness", "ex": "They were depressed by the sheer bleakness of the desert.", "pos": "n."},
    "bleat": {"def": "咩咩叫、胡扯、咩咩聲、抱怨、咩咩叫的人 (或物)、抱怨地 (咩)", "ipa": "/bliːt/", "trans": "bleating", "col": "soft bleat, stop bleating (停止發牢騷)", "ex": "The lamb gave a soft bleat.", "pos": "v./n./adv."},
    "bleck": {"def": "黑、污垢地 (黑)", "ipa": "/blek/", "trans": "dirt", "col": "bleck on", "ex": "The wall was covered with bleck.", "pos": "n./adv."},
    "bleed": {"def": "流血、滲出、搾取、漏氣、流血的人 (或物)、滲出地 (血)", "ipa": "/bliːd/", "trans": "bleeding, bled", "col": "bleed to death, heart bleeds for, bleed dry (搾乾)", "ex": "My nose started to bleed.", "pos": "v./n./adv."},
    "bleeder": {"def": "(口)受罪的人、(俚)討厭的人、放血器", "ipa": "/ˈbliːdə/", "trans": "bleed (動詞/名詞/副詞)", "col": "poor bleeder", "ex": "The poor bleeder didn't stand a chance.", "pos": "n."},
    "bleeding": {"def": "流血、慘痛的、(俚)該死的、流血的人 (或物) (血)", "ipa": "/ˈbliːdɪŋ/", "trans": "bleed (動詞/名詞/副詞)", "col": "internal bleeding, heavy bleeding", "ex": "He was rushed to hospital with internal bleeding.", "pos": "n./adj./adv."},
    "blemish": {"def": "汙點、瑕疵、損害、傷疤、有瑕疵的人 (或物)、有瑕疵地 (汙點)", "ipa": "/ˈblemɪʃ/", "trans": "blemishes", "col": "skin blemish, without blemish", "ex": "Her skin is without blemish.", "pos": "n./v./adv."},
    "blench": {"def": "退縮、畏縮、變白", "ipa": "/blentʃ/", "trans": "flinch", "col": "blench at", "ex": "He didn't blench at the sight of the surgery.", "pos": "v."},
    "blend": {"def": "混合、混和、調和、混合物、混合的人 (或物)、調和地 (混)", "ipa": "/blend/", "trans": "blender, blending", "col": "blend in (融入), perfect blend, coffee blend", "ex": "The new building doesn't blend in with the older ones.", "pos": "v./n./adv."},
    "blender": {"def": "攪拌機、果汁機 (單數)", "ipa": "/ˈblendə/", "trans": "blenders (複數)", "col": "electric blender", "ex": "She put the fruit in the electric blender.", "pos": "n."},
    "blending": {"def": "混合、調和、混合的人物 (混)", "ipa": "/ˈblendɪŋ/", "trans": "blend (動詞/名詞/副詞)", "col": "smooth blending", "ex": "The smooth blending of flavors was impressive.", "pos": "n./adv."},
    "blenny": {"def": "䲁魚、粘魚 (單數)", "ipa": "/ˈbleni/", "trans": "blennies (複數)", "col": "rock blenny", "ex": "The rock blenny hides among the stones.", "pos": "n."},
    "bless": {"def": "保佑、祝福、賜福、賦予、祝福的人 (或物)、賜福地 (福)", "ipa": "/bles/", "trans": "blessing, blessed", "col": "God bless you, bless you (打噴嚏時), bless with", "ex": "May God bless you.", "pos": "v./n./adv."},
    "blessed": {"def": "神聖的、受祝福的、(口)極大的", "ipa": "/ˈblesɪd/", "trans": "bless (動詞/名詞/副詞), blessing", "col": "blessed event (小孩出生), the Blessed Virgin", "ex": "We are blessed with good health.", "pos": "adj."},
    "blessedly": {"def": "神聖地、幸運地、極其地", "ipa": "/ˈblesɪdli/", "trans": "blessed (形容詞/名詞/副詞)", "col": "blessedly quiet", "ex": "The house was blessedly quiet for once.", "pos": "adv."},
    "blessedness": {"def": "神聖、幸福、至福", "ipa": "/ˈblesɪdnəs/", "trans": "bless (動詞/名詞/副詞), blessing", "col": "eternal blessedness", "ex": "He is seeking eternal blessedness.", "pos": "n."},
    "blessing": {"def": "祝福、賜福、同意、幸事、祝福的人 (或物) (福)", "ipa": "/ˈblesɪŋ/", "trans": "bless (動詞/名詞/副詞), blessed", "col": "mixed blessing (憂喜參半), disguised blessing (塞翁失馬), count one's blessings", "ex": "The rain was a blessing for the farmers.", "pos": "n./adv."},
    "blest": {"def": "(古)受祝福的、(bless的過去式及過去分詞)", "ipa": "/blest/", "trans": "blessed", "col": "most blest", "ex": "I am most blest to have such friends.", "pos": "adj./v."},
    "blew": {"def": "(blow的過去式)、吹過了", "ipa": "/bluː/", "trans": "blow", "col": "blew a whistle", "ex": "A cold wind blew through the window.", "pos": "v."},
    "blight": {"def": "枯萎病、禍害、衰退、使枯萎、毀滅、枯萎的人 (或物)、毀滅地 (枯)", "ipa": "/blaɪt/", "trans": "blighted", "col": "urban blight, blight on", "ex": "The disease has blighted the apple trees.", "pos": "n./v./adv."},
    "blighter": {"def": "(英口)討厭鬼、可憐蟲", "ipa": "/ˈblaɪtə/", "trans": "fellow", "col": "poor blighter", "ex": "The poor blighter lost everything in the fire.", "pos": "n."},
    "blimp": {"def": "小型飛船、(軍)軟式飛船、(俚)老古板、飛船的人物、老古板地 (飛船)", "ipa": "/blɪmp/", "trans": "blimps", "col": "promotional blimp", "ex": "A promotional blimp was flying over the stadium.", "pos": "n./adv."},
    "blind": {"def": "盲的、盲目的、百葉窗、隱蔽、使看不見、盲目地 (盲)", "ipa": "/blaɪnd/", "trans": "blindly, blindness", "col": "blind spot, blind date, blind leading the blind, turn a blind eye", "ex": "He has been blind from birth.", "pos": "adj./n./v./adv."},
    "blinder": {"def": "馬眼罩、精彩的表現(美)、耀眼的人 (或物) (演)", "ipa": "/ˈblaɪndə/", "trans": "blinders", "col": "play a blinder", "ex": "The goalkeeper played a blinder today.", "pos": "n./adv."},
    "blindfold": {"def": "眼罩、蒙住雙眼、盲目的、蒙眼地 (蒙眼)", "ipa": "/ˈblaɪndfəʊld/", "trans": "blindfolds", "col": "wear a blindfold", "ex": "They put a blindfold on the hostage.", "pos": "n./v./adj./adv."},
    "blinding": {"def": "眩目的、眼花的、忙盲的人 (或物) (盲)", "ipa": "/ˈblaɪndɪŋ/", "trans": "blind (形容詞/名詞/動詞/副詞)", "col": "blinding light, blinding storm", "ex": "There was a blinding flash of light.", "pos": "adj./adv."},
    "blindingly": {"def": "耀眼地、極端地", "ipa": "/ˈblaɪndɪŋli/", "trans": "blinding (形容詞/副詞)", "col": "blindingly obvious", "ex": "The mistake was blindingly obvious.", "pos": "adv."},
    "blindly": {"def": "盲目地、冒失地、摸索地", "ipa": "/ˈblaɪndli/", "trans": "blind (形容詞/名詞/動詞/副詞)", "col": "follow blindly", "ex": "You shouldn't follow his advice blindly.", "pos": "adv."},
    "blindness": {"def": "盲目、無視、愚昧", "ipa": "/ˈbaʊndnəs/", "trans": "blind (形容詞/名詞/動詞/副詞)", "col": "color blindness, snow blindness", "ex": "Color blindness is more common in men.", "pos": "n."},
    "blindside": {"def": "出其不意地襲擊、(體)盲側", "ipa": "/ˈblaɪndsaɪd/", "trans": "ambush", "col": "caught on the blindside", "ex": "The news complete blindsided me.", "pos": "v./n."},
    "blink": {"def": "刷眼、閃爍、閃光、瞥視、閃爍的人物、閃光地 (閃)", "ipa": "/blɪŋk/", "trans": "blinking", "col": "in the blink of an eye (轉眼間), on the blink (出故障)", "ex": "He blinked in the bright sunlight.", "pos": "v./n./adv."},
    "blinker": {"def": "馬眼罩、(車)方向燈、(口)眼睛的人物、方向燈地 (方向燈)", "ipa": "/ˈblɪŋkə/", "trans": "blinkers", "col": "put blinkers on", "ex": "He was wearing blinkers and couldn't see the danger.", "pos": "n./adv."},
    "blinking": {"def": "閃爍的、(口)該地的、眨眼的人 (或物) (眨)", "ipa": "/ˈblɪŋkɪŋ/", "trans": "blink (動詞/名詞/副詞)", "col": "blinking light", "ex": "The blinking light on the dashboard caught my attention.", "pos": "adj./adv."},
    "blip": {"def": "(雷達)光點、(股市)暫時下跌、發嗶聲、光點的人 (或物)、暫時地下跌 (點)", "ipa": "/blɪp/", "trans": "blips", "col": "temporary blip", "ex": "The fall in sales was just a temporary blip.", "pos": "n./v./adv."},
    "bliss": {"def": "至福、天福、極樂、欣喜地 (福)", "ipa": "/blɪs/", "trans": "blissful", "col": "ignorant bliss (無知之福), sheer bliss", "ex": "Lying on the beach was sheer bliss.", "pos": "n./adv."},
    "blissful": {"def": "極其幸福的、樂在其中的", "ipa": "/ˈblɪsfl/", "trans": "bliss (名詞/副詞)", "col": "blissful smile", "ex": "She fell into a blissful sleep.", "pos": "adj."},
}