import json

# Level 5 Part 6: (Interpretation - Overtake)
L5_PART6 = {
    "interpretation": {"def": "解釋、詮釋、演繹、翻譯", "ipa": "/ɪnˌtɜːprɪˈteɪʃn/", "trans": "interpret, interpreter", "col": "literal interpretation, professional interpretation", "ex": "The rules are open to interpretation.", "pos": "n."},
    "generator": {"def": "發電機、產生器", "ipa": "/ˈdʒenəreɪtə/", "trans": "generate (動詞)", "col": "emergency generator", "ex": "The hospital has an emergency generator in case of a power failure.", "pos": "n."},
    "immense": {"def": "極大的、巨大的、無限的", "ipa": "/ɪˈmens/", "trans": "immensely", "col": "immense pressure", "ex": "The project was an immense success.", "pos": "adj."},
    "interval": {"def": "間隔、距離、幕間休息", "ipa": "/ˈɪntəvl/", "trans": "intervals", "col": "at regular intervals", "ex": "The buses run at regular intervals.", "pos": "n."},
    "genetic": {"def": "基因的、遺傳學的", "ipa": "/dʒəˈnetɪk/", "trans": "genes, genetics", "col": "genetic engineering, genetic code", "ex": "The disease is caused by a genetic defect.", "pos": "adj."},
    "intact": {"def": "完整無缺的、原封不動的", "ipa": "/ɪnˈtækt/", "trans": "tact", "col": "remain intact", "ex": "Most of the city remained intact after the earthquake.", "pos": "adj."},
    "maintenance": {"def": "維持、維修、贍養費", "ipa": "/ˈmeɪntənəns/", "trans": "maintain", "col": "routine maintenance", "ex": "The building needs regular maintenance.", "pos": "n."},
    "mammal": {"def": "哺乳動物", "ipa": "/ˈmæml/", "trans": "mammalian", "col": "marine mammal", "ex": "Whales and dolphins are marine mammals.", "pos": "n."},
    "mustard": {"def": "芥末、芥菜、熱情的人", "ipa": "/ˈmʌstəd/", "trans": "mustards", "col": "hot mustard", "ex": "I like to eat sausages with mustard.", "pos": "n."},
    "overtake": {"def": "追上、趕上、超過、(災難等)突然降臨於", "ipa": "/ˌəʊvəˈteɪk/", "trans": "overtook", "col": "overtake on the left", "ex": "The car overtook several trucks on the highway.", "pos": "v."},
    "bonfire": {"def": "營火、大營火", "ipa": "/ˈbɒnfaɪə/", "trans": "bonfires", "col": "build a bonfire", "ex": "They built a huge bonfire on the beach.", "pos": "n."},
    "bonus": {"def": "獎金、紅利、額外的好處", "ipa": "/ˈbəʊnəs/", "trans": "bonuses", "col": "annual bonus, incentive bonus", "ex": "The employees received an annual bonus this year.", "pos": "n."},
    "bony": {"def": "多骨的、瘦骨嶙峋的", "ipa": "/ˈbəʊni/", "trans": "bone", "col": "bony finger", "ex": "He has long, bony fingers.", "pos": "adj."},
    "book": {"def": "書、帳冊、篇章、預定、登記、將...編入冊內、本、冊", "ipa": "/bʊk/", "trans": "booking, booklet", "col": "book a flight, by the book (按規定)", "ex": "I'd like to book a table for two.", "pos": "n./v./adj."},
    "bookcase": {"def": "書櫃、書架", "ipa": "/ˈbʊkkeɪs/", "trans": "bookcases", "col": "filled with bookcases", "ex": "The wall was filled with bookcases.", "pos": "n."},
    "booklet": {"def": "小冊子", "ipa": "/ˈbʊklət/", "trans": "book (名詞/動詞/形容詞)", "col": "informational booklet", "ex": "The company produced an informational booklet about its products.", "pos": "n."},
    "boom": {"def": "隆隆聲、繁榮、激增、繁榮、激增、發出隆隆聲", "ipa": "/buːm/", "trans": "booming", "col": "baby boom, sonic boom, economic boom", "ex": "The economy is experiencing a booming period.", "pos": "n./v."},
    "boomerang": {"def": "迴力鏢、自食其果的行動、自食其果", "ipa": "/ˈbuːməræŋ/", "trans": "boomerangs", "col": "throw a boomerang", "ex": "If you are not careful, your actions may boomerang on you.", "pos": "n./v."},
    "boost": {"def": "推動、促進、增加、舉、推、提高、吹捧", "ipa": "/buːst/", "trans": "booster", "col": "boost confidence, morale boost", "ex": "The victory gave a boost to the team's confidence.", "pos": "n./v."},
    "booster": {"def": "支持者、推進器、效能增強器、追加劑", "ipa": "/ˈbuːstə/", "trans": "boost (名詞/動詞)", "col": "booster shot, rocket booster", "ex": "He received a booster shot for his vaccination.", "pos": "n."},
    "boot": {"def": "靴子、行李箱、解僱、穿靴、踢、啟動(電腦)", "ipa": "/buːt/", "trans": "boots", "col": "reboot, give someone the boot", "ex": "The computer takes a long time to boot.", "pos": "n./v."},
    "booth": {"def": "攤位、隔間、電話亭、公投箱", "ipa": "/buːð/", "trans": "booths", "col": "voting booth, telephone booth", "ex": "She went into the voting booth to cast her ballot.", "pos": "n."},
    "border": {"def": "邊界、邊緣、花壇、接界、鑲邊、沿著邊緣、構成...的邊界", "ipa": "/ˈbɔːdə/", "trans": "borderline", "col": "cross the border, border control", "ex": "The two countries share a long border.", "pos": "n./v."},
    "bore": {"def": "令人厭煩的人(或物)、孔、口徑、湧潮、使厭煩、鑽孔、挖", "ipa": "/bɔː/", "trans": "boredom, boring", "col": "bore to death", "ex": "The long speech bored everyone to death.", "pos": "n./v."},
    "boredom": {"def": "無聊、厭倦、乏味", "ipa": "/ˈbɔːdəm/", "trans": "bore (名詞/動詞), boring", "col": "die of boredom", "ex": "The children were complaining of boredom.", "pos": "n."},
    "boring": {"def": "無聊的、乏味的", "ipa": "/ˈbɔːrɪŋ/", "trans": "bore (名詞/動詞), boredom", "col": "boring job", "ex": "He found his job very boring.", "pos": "adj."},
    "born": {"def": "出生的、天生的、天賦的", "ipa": "/bɔːn/", "trans": "birth", "col": "born leader, born in", "ex": "He is a born leader.", "pos": "adj./v.pp."},
    "borrow": {"def": "借、借用、採用、借入", "ipa": "/ˈbɒrəʊ/", "trans": "borrower", "col": "borrow from", "ex": "Can I borrow your pen for a moment?", "pos": "v."},
    "bosom": {"def": "胸部、胸懷、內心、親切的、知心的、懷抱、把...藏在心中", "ipa": "/ˈbʊzəm/", "trans": "bosoms", "col": "bosom friend", "ex": "She is my bosom friend.", "pos": "n./adj./v."},
    "bossy": {"def": "愛指揮人的、跋扈的", "ipa": "/ˈbɒsi/", "trans": "boss", "col": "bossy attitude", "ex": "Nobody likes her because she is so bossy.", "pos": "adj."},
    "botany": {"def": "植物學、植物", "ipa": "/ˈbɒtəni/", "trans": "botanist, botanical", "col": "botanical garden", "ex": "She is studying botany at the university.", "pos": "n."},
    "bother": {"def": "煩惱、麻煩、吵鬧、打擾、煩惱、操心、麻煩", "ipa": "/ˈbɒðə/", "trans": "bothersome", "col": "bother with, sorry to bother you", "ex": "I'm sorry to bother you, but can you help me?", "pos": "n./v."},
    "bottle": {"def": "瓶子、酒、勇氣、酒精、裝入瓶中、抑制", "ipa": "/ˈbɒtl/", "trans": "bottled", "col": "bottled water, water bottle", "ex": "He drank a bottle of mineral water.", "pos": "n./v."},
    "bottleneck": {"def": "瓶頸、障礙、窄路", "ipa": "/ˈbɒtlnek/", "trans": "bottlenecks", "col": "traffic bottleneck, production bottleneck", "ex": "The construction work caused a major traffic bottleneck.", "pos": "n."},
    "bottom": {"def": "底部、臀部、末端、底部的、末端的、建立在...基礎上、到達底部", "ipa": "/ˈbɒtəm/", "trans": "bottomless", "col": "bottom line, at the bottom of", "ex": "The keys were at the bottom of her bag.", "pos": "n./adj./v."},
    "bough": {"def": "大樹枝", "ipa": "/baʊ/", "trans": "boughs", "col": "leafy bough", "ex": "The birds were singing on the leafy boughs.", "pos": "n."},
    "bounce": {"def": "彈跳、活力、回彈、彈起、跳、彈跳、(支票)退票、解僱", "ipa": "/baʊns/", "trans": "bouncy", "col": "bounce back", "ex": "The ball bounced off the wall.", "pos": "n./v."},
    "bound": {"def": "邊界、限制、跳躍、受約束的、一定的、前往...的、跳躍、接界、限制", "ipa": "/baʊnd/", "trans": "boundary, boundless", "col": "be bound to, outbound, inbound", "ex": "He is bound to win the competition.", "pos": "n./adj./v."},
    "boundary": {"def": "邊界、界限、分界線", "ipa": "/ˈbaʊndri/", "trans": "bound (名詞/形容詞/動詞)", "col": "national boundary, set a boundary", "ex": "The river forms the boundary between the two countries.", "pos": "n."},
    "bounty": {"def": "慷慨、補助金、獎金", "ipa": "/ˈbaʊnti/", "trans": "bountiful", "col": "generous bounty", "ex": "The king rewarded the hero with a generous bounty.", "pos": "n."},
    "bouquet": {"def": "花束、酒香、香氣", "ipa": "/buˈkeɪ/", "trans": "bouquets", "col": "bouquet of flowers", "ex": "He gave her a large bouquet of roses.", "pos": "n."},
    "bow": {"def": "弓、蝴蝶結、琴弓、船首、鞠躬、致意、鞠躬、彎曲、屈服、鞠躬的、彎曲的", "ipa": "/baʊ/ (v./n. 鞠躬) /bəʊ/ (n. 弓/蝴蝶結)", "trans": "bowing", "col": "take a bow, rainbow, bow tie", "ex": "The actors took a bow after the performance.", "pos": "n./v./adj."},
    "bowel": {"def": "腸、內臟、內部", "ipa": "/ˈbaʊəl/", "trans": "bowels", "col": "bowel movement", "ex": "He is suffering from a bowel infection.", "pos": "n."},
    "bowl": {"def": "碗、球、保齡球、木球、玩保齡球、滾球、快速行進、滾動", "ipa": "/bəʊl/", "trans": "bowls", "col": "mixing bowl, cereal bowl", "ex": "She ate a bowl of cereal for breakfast.", "pos": "n./v."},
    "box": {"def": "盒子、箱、專欄、拳擊、裝箱、拳擊、打耳光、方框狀的", "ipa": "/bɒks/", "trans": "boxing, boxer", "col": "post office box (P.O.Box), box office", "ex": "The shoes are in a cardboard box.", "pos": "n./v./adj."},
    "boycott": {"def": "杯葛、抵制、杯葛的人(或事)、聯合抵制、拒絕參加", "ipa": "/ˈbɔɪkɒt/", "trans": "boycotting", "col": "consumer boycott", "ex": "The students decided to boycott the cafeteria.", "pos": "n./v."},
    "brace": {"def": "支柱、撐柱、大括號、護具、支撐、加固、使防備、繃緊", "ipa": "/breɪs/", "trans": "bracing", "col": "orthodontic brace, brace yourself for", "ex": "The workers braced the wall to prevent it from falling.", "pos": "n./v."},
    "bracket": {"def": "括號、托架、等級、把...歸入一類、用括弧括起來、撐持", "ipa": "/ˈbrækɪt/", "trans": "bracketing", "col": "age bracket, income bracket", "ex": "The text was enclosed in square brackets.", "pos": "n./v."},
    "brag": {"def": "吹噓、自誇、吹噓的人、大話、吹牛、自誇、誇耀的", "ipa": "/bræɡ/", "trans": "braggart", "col": "brag about", "ex": "He is always bragging about his wealth.", "pos": "n./v./adj."},
    "braid": {"def": "辮子、帶子、飾帶、編辮子、編織、編成帶子", "ipa": "/breɪd/", "trans": "braided", "col": "hair braid", "ex": "She wore her hair in a long braid.", "pos": "n./v."},
    "brain": {"def": "大腦、智力、腦子、聰明人、打擊...的頭、打破...的腦袋", "ipa": "/breɪn/", "trans": "brainy", "col": "brain drain, brain trust, brainstorm", "ex": "The brain is the most complex organ in the body.", "pos": "n./v."},
    "brake": {"def": "煞車、阻礙物、煞車踏板、煞車、制動、放慢速度", "ipa": "/breɪk/", "trans": "braking", "col": "apply the brakes, emergency brake", "ex": "He slammed on the brakes to avoid the accident.", "pos": "n./v."},
    "branch": {"def": "分支、分店、分部、樹枝、分叉、分出、出現支脈、分枝的", "ipa": "/brɑːntʃ/", "trans": "branches", "col": "branch office, executive branch", "ex": "The company is opening a new branch in Tokyo.", "pos": "n./v./adj."},
    "brand": {"def": "品牌、烙印、類型、污點、打烙印、銘刻、污衊", "ipa": "/brænd/", "trans": "branding", "col": "well-known brand, fire brand", "ex": "Sony is a well-known brand of electronics.", "pos": "n./v."},
    "brandish": {"def": "揮舞、炫耀、揮動", "ipa": "/ˈbrændɪʃ/", "trans": "brandished", "col": "brandish a weapon", "ex": "The man was brandishing a knife.", "pos": "v."},
    "brash": {"def": "魯莽的、傲慢的、性急的、突發的", "ipa": "/bræʃ/", "trans": "brashness", "col": "brash young man", "ex": "He is a brash young man who thinks he knows everything.", "pos": "adj."},
    "brass": {"def": "黃銅、銅管樂器、厚臉皮、高官、黃銅製的、銅管樂器的", "ipa": "/brɑːs/", "trans": "brassy", "col": "brass instrument, brass band", "ex": "The trumpet is a brass instrument.", "pos": "n./adj."},
    "bravado": {"def": "逞強、虛張聲勢", "ipa": "/brəˈvɑːdəʊ/", "trans": "brave", "col": "show of bravado", "ex": "His confidence was just a show of bravado.", "pos": "n."},
    "brave": {"def": "勇敢的、華麗的、優秀的、勇敢的人、美洲印第安勇士、勇敢地面對、冒犯、英勇地", "ipa": "/breɪv/", "trans": "bravery, bravely", "col": "brave the elements", "ex": "The rescuers were very brave.", "pos": "adj./n./v./adv."},
    "bravery": {"def": "勇敢、勇氣、華美", "ipa": "/ˈbreɪvəri/", "trans": "brave (形容詞/名詞/動詞/副詞)", "col": "award for bravery", "ex": "He was awarded a medal for his bravery.", "pos": "n."},
    "breach": {"def": "違反、破裂、缺口、違反、破開、衝破", "ipa": "/briːtʃ/", "trans": "breached", "col": "breach of contract, breach of security", "ex": "The company was sued for breach of contract.", "pos": "n./v."},
    "bread": {"def": "麵包、生計、錢、在...上裹麵包粉", "ipa": "/bred/", "trans": "breaded", "col": "wholemeal bread, bread and butter (生計)", "ex": "I like to eat wholemeal bread.", "pos": "n./v."},
    "breadth": {"def": "寬度、幅度、廣度", "ipa": "/bredθ/", "trans": "broad", "col": "breadth of knowledge", "ex": "The breadth of his knowledge is amazing.", "pos": "n."},
    "break": {"def": "破裂、中斷、休息、進展、打破、折斷、違反、破曉、休息地", "ipa": "/breɪk/", "trans": "broken, breakable", "col": "coffee break, break down, break even", "ex": "Don't break the glass.", "pos": "n./v./adv."},
    "breakdown": {"def": "崩潰、故障、細目內容、分析", "ipa": "/ˈbreɪkdaʊn/", "trans": "break (名詞/動詞/副詞)", "col": "nervous breakdown, mechanical breakdown", "ex": "The machine suffered a mechanical breakdown.", "pos": "n."},
    "breakfast": {"def": "早餐、吃早餐", "ipa": "/ˈbrekfəst/", "trans": "breakfasts", "col": "eat breakfast, continental breakfast", "ex": "What did you have for breakfast?", "pos": "n./v."},
    "breakthrough": {"def": "突破、進展、滲透", "ipa": "/ˈbreɪkθruː/", "trans": "break (名詞/動詞/副詞)", "col": "major breakthrough, scientific breakthrough", "ex": "Scientists have made a major breakthrough in cancer research.", "pos": "n."},
    "breast": {"def": "胸部、乳房、心情、胸懷、挺胸走向、對付、用胸撞", "ipa": "/brest/", "trans": "breasts", "col": "breast cancer, breast feed", "ex": "She has been diagnosed with breast cancer.", "pos": "n./v."},
    "breath": {"def": "呼吸、氣息、瞬間", "ipa": "/breθ/", "trans": "breathe", "col": "take a deep breath, out of breath", "ex": "Take a deep breath and relax.", "pos": "n."},
    "breathe": {"def": "呼吸、注入、低語、呼出 (呼吸)", "ipa": "/briːð/", "trans": "breath (名詞), breathing", "col": "breathe in, breathe out", "ex": "It's important to breathe deeply while exercising.", "pos": "v."},
    "breathtaking": {"def": "驚人的、美得驚人的、刺激的", "ipa": "/ˈbreθteɪkɪŋ/", "trans": "breath (名詞), breathe (動詞)", "col": "breathtaking view", "ex": "The view from the mountain top was breathtaking.", "pos": "adj."},
    "breed": {"def": "品種、類型、族類、繁殖、養成、導致、生產、使繁殖 (品種)", "ipa": "/briːd/", "trans": "breeding, breeder", "col": "rare breed, breed contempt", "ex": "They breed horses on the farm.", "pos": "n./v."},
    "breeze": {"def": "微風、容易的事、小風波、輕盈地走、吹微風", "ipa": "/briːz/", "trans": "breezy", "col": "gentle breeze, ocean breeze", "ex": "A gentle breeze was blowing from the sea.", "pos": "n./v."},
    "brethren": {"def": "兄弟們、同胞們", "ipa": "/ˈbreðrən/", "trans": "brother", "col": "dear brethren", "ex": "My dear brethren, let us pray.", "pos": "n.pl."},
    "brevity": {"def": "簡約、短暫", "ipa": "/ˈbrevəti/", "trans": "brief", "col": "brevity of life", "ex": "Brevity is the soul of wit.", "pos": "n."},
    "brew": {"def": "釀造物、啤酒、混合、研發中、釀造、泡(茶、咖啡)、生起、即將發生", "ipa": "/bruː/", "trans": "brewer, brewery", "col": "home brew", "ex": "A storm is brewing.", "pos": "n./v."},
    "bribe": {"def": "賄賂、誘餌、向...行賄、收買", "ipa": "/braɪb/", "trans": "bribery", "col": "take a bribe, offer a bribe", "ex": "The official was accused of taking a bribe.", "pos": "n./v."},
    "bribery": {"def": "賄賂行為、行賄", "ipa": "/ˈbraɪbəri/", "trans": "bribe (名詞/動詞)", "col": "political bribery", "ex": "Political bribery is a serious crime.", "pos": "n."},
    "brick": {"def": "磚、方塊、厚道的人、用磚蓋、填滿、用磚造的", "ipa": "/brɪk/", "trans": "bricks", "col": "brick wall, brick by brick", "ex": "The house is built of red bricks.", "pos": "n./v./adj."},
    "bride": {"def": "新娘", "ipa": "/braɪd/", "trans": "bridal, bridesmaid", "col": "beautiful bride", "ex": "The bride looked beautiful in her white dress.", "pos": "n."},
    "bridegroom/groom": {"def": "新郎、馬夫、梳妝、修整、照料(馬)、培養", "ipa": "/ˈbraɪdɡruːm/ (n.) /ɡruːm/ (v./n.)", "trans": "groomsman", "col": "best man", "ex": "The bridegroom arrived on time.", "pos": "n./v."},
    "bridge": {"def": "橋、橋牌、鼻樑、艦橋、架橋於、渡過、彌補(差距)", "ipa": "/brɪdʒ/", "trans": "bridging", "col": "bridge the gap, draw bridge", "ex": "They are building a new bridge across the river.", "pos": "n./v."},
    "bridle": {"def": "馬勒、約束、仰頭(表傲慢)、裝上馬勒、約束、限制、昂首", "ipa": "/ˈbraɪdl/", "trans": "bridled", "col": "unbridled passion", "ex": "The rider fastened the bridle on the horse.", "pos": "n./v."},
    "brief": {"def": "短暫的、簡短的、正式委託、摘要、訴狀、摘要、委託、向...作簡報、正式委託、簡短地", "ipa": "/briːf/", "trans": "briefly, brevity", "col": "brief summary, in brief, brief encounter", "ex": "Please give a brief summary of the report.", "pos": "adj./n./v./adv."},
    "briefcase": {"def": "公事包", "ipa": "/ˈbriːfkeɪs/", "trans": "brief (名詞/動詞/形容詞/副詞)", "col": "leather briefcase", "ex": "He carried his documents in a leather briefcase.", "pos": "n."},
    "brigade": {"def": "旅、隊、群、編隊、成旅", "ipa": "/brɪˈɡeɪd/", "trans": "brigadier", "col": "fire brigade", "ex": "The fire brigade arrived within minutes.", "pos": "n./v."},
    "bright": {"def": "明亮的、聰明的、鮮豔的、歡快的、強烈地、響亮地、亮點、明亮表面", "ipa": "/braɪt/", "trans": "brightness, brighten", "col": "bright future, bright idea", "ex": "The sun is very bright today.", "pos": "adj./adv./n."},
    "brighten": {"def": "變亮、變快樂、使明亮、使更愉快", "ipa": "/ˈbraɪtn/", "trans": "bright (名詞/形容詞/副詞)", "col": "brighten up", "ex": "The weather began to brighten up in the afternoon.", "pos": "v."},
}

with open("batch_l5_p6.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART6, f, ensure_ascii=False, indent=2)
