import json

# Level 6 Part 12: (Aroma - Assail)
L6_PART12 = {
    "aroma": {"def": "香氣、香味、芬芳", "ipa": "/əˈrəʊmə/", "trans": "aromatic", "col": "pleasant aroma, aroma of coffee", "ex": "The air was filled with the pleasant aroma of coffee.", "pos": "n."},
    "aromatic": {"def": "芳香的、香味的、芳香植物", "ipa": "/ˌærəˈmætɪk/", "trans": "aroma (名詞)", "col": "aromatic herbs", "ex": "The soup was seasoned with aromatic herbs.", "pos": "adj./n."},
    "around": {"def": "在周圍、在附近、大約、大約、旋轉、在周圍地、在附近地 (在周圍)", "ipa": "/əˈraʊnd/", "trans": "round", "col": "all around, around the corner, around the clock", "ex": "There is a fence around the garden.", "pos": "prep./adv./adj."},
    "arouse": {"def": "喚醒、激起、引起", "ipa": "/əˈraʊz/", "trans": "arousal", "col": "arouse interest, arouse suspicion", "ex": "His behavior aroused suspicion among the neighbors.", "pos": "v."},
    "arousal": {"def": "覺醒、激勵、喚起", "ipa": "/əˈraʊzl/", "trans": "arouse (動詞)", "col": "emotional arousal", "ex": "The music leads to an emotional arousal in the listener.", "pos": "n."},
    "arraign": {"def": "提訊、控告、責難", "ipa": "/əˈreɪn/", "trans": "arraignment", "col": "arraign on charges", "ex": "He was arraigned on charges of conspiracy.", "pos": "v."},
    "arraignment": {"def": "提訊、控告", "ipa": "/əˈreɪnmənt/", "trans": "arraign (動詞)", "col": "formal arraignment", "ex": "The formal arraignment will take place next week.", "pos": "n."},
    "arrange": {"def": "安排、整理、約定、改編、整理的人 (或物)、整理地 (整理)", "ipa": "/əˈreɪndʒ/", "trans": "arrangement", "col": "arrange a meeting, arrange flowers", "ex": "Can you arrange a meeting for tomorrow?", "pos": "v./n./adv."},
    "arrangement": {"def": "安排、整理、協定、改編、整理的人 (或物)、整理地 (整理)", "ipa": "/əˈreɪndʒmənt/", "trans": "arrange (動詞/名詞/副詞)", "col": "security arrangement, flower arrangement, travel arrangement", "ex": "We need to make travel arrangements for the trip.", "pos": "n./adj./adv."},
    "arrant": {"def": "極惡的、徹頭徹尾的、名副其實的", "ipa": "/ˈærənt/", "trans": "outright", "col": "arrant nonsense", "ex": "What you are saying is arrant nonsense.", "pos": "adj."},
    "array": {"def": "陣容、大堆、衣服、排列、部署、打扮、部署的、打扮的、部署地 (部署)", "ipa": "/əˈreɪ/", "trans": "arrays", "col": "vast array, dazzling array", "ex": "The shop has a vast array of books.", "pos": "n./v./adj./adv."},
    "arrears": {"def": "欠款、逾期費、待做之事 (複數)", "ipa": "/əˈrɪəz/", "trans": "debts", "col": "rent arrears, in arrears", "ex": "He is in arrears with his rent.", "pos": "n."},
    "arrest": {"def": "逮捕、拘留、停止、吸引、逮捕、拘留、阻止的人 (或物)、逮捕地 (逮捕)", "ipa": "/əˈrest/", "trans": "arresting", "col": "under arrest, heart arrest (心臟驟停), place under arrest", "ex": "The police made a few arrests after the fight.", "pos": "n./v./adv."},
    "arresting": {"def": "引人注目的、有趣的、逮捕的", "ipa": "/əˈrestɪŋ/", "trans": "arrest (名詞/動詞/副詞)", "col": "arresting image", "ex": "The book has a very arresting cover.", "pos": "adj."},
    "arrival": {"def": "到達、到來、到達者、進場的人 (或物)", "ipa": "/əˈraɪvl/", "trans": "arrive (動詞/副詞), arriving", "col": "on arrival, time of arrival, late arrival", "ex": "We are waiting for the arrival of the train.", "pos": "n."},
    "arrive": {"def": "到達、來到、達成、成功、出現的人 (或物)、來到地 (來到)", "ipa": "/əˈraɪv/", "trans": "arrival", "col": "arrive at, arrive safely", "ex": "The flight arrived late due to the storm.", "pos": "v./n./adv."},
    "arrogance": {"def": "傲慢、自大、傲慢的人 (或事)", "ipa": "/ˈærəɡəns/", "trans": "arrogant, arrogantly", "col": "sheer arrogance", "ex": "He was shocked by the sheer arrogance of the man.", "pos": "n."},
    "arrogant": {"def": "傲慢的、自大的、自命不凡的、傲慢地、自大地 (傲慢)", "ipa": "/ˈærəɡənt/", "trans": "arrogance, arrogantly", "col": "arrogant attitude", "ex": "Nobody likes his arrogant attitude.", "pos": "adj./adv."},
    "arrogantly": {"def": "傲慢地、自大地", "ipa": "/ˈærəɡəntli/", "trans": "arrogant (形容詞/副詞), arrogance", "col": "speak arrogantly", "ex": "He spoke arrogantly to his subordinates.", "pos": "adv."},
    "arrogate": {"def": "冒稱、冒領、霸佔", "ipa": "/ˈærəɡeɪt/", "trans": "arrogation", "col": "arrogate power", "ex": "The committee arrogated more power to itself.", "pos": "v."},
    "arrow": {"def": "箭、箭號、用箭指示、射箭般的、快速地 (箭)", "ipa": "/ˈærəʊ/", "trans": "arrows", "col": "bow and arrow, follow the arrow", "ex": "Follow the arrow to the exit.", "pos": "n./v./adj./adv."},
    "arsenal": {"def": "兵工廠、軍械庫、武庫、大量資源", "ipa": "/ˈɑːsənl/", "trans": "armoury", "col": "nuclear arsenal, complete arsenal", "ex": "The country has a large nuclear arsenal.", "pos": "n."},
    "arsenic": {"def": "砷、砒霜、砒霜的、毒性的", "ipa": "/ˈɑːsnɪk/", "trans": "poison", "col": "poisoned with arsenic", "ex": "Arsenic is a highly poisonous chemical element.", "pos": "n./adj."},
    "arson": {"def": "縱火、縱火罪", "ipa": "/ˈɑːsn/", "trans": "arsonist", "col": "guilty of arson", "ex": "He was charged with arson after the warehouse fire.", "pos": "n."},
    "arsonist": {"def": "縱火犯、縱火者", "ipa": "/ˈɑːsənɪst/", "trans": "arson", "col": "suspected arsonist", "ex": "The police are looking for the suspected arsonist.", "pos": "n."},
    "art": {"def": "藝術、美術、技巧、技術、文科、(古)是、藝術的、美學的、藝術地 (藝術)", "ipa": "/ɑːt/", "trans": "artist, artistic", "col": "work of art, martial art, art gallery", "ex": "She is studying art history.", "pos": "n./v./adj./adv."},
    "arteriosclerosis": {"def": "動脈硬化、硬化", "ipa": "/ɑːˌtɪəriəʊskləˈrəʊsɪs/", "trans": "hardening of arteries", "col": "suffer from arteriosclerosis", "ex": "Smoking can lead to arteriosclerosis.", "pos": "n."},
    "artery": {"def": "動脈、幹線、要道", "ipa": "/ˈɑːtəri/", "trans": "arteries", "col": "main artery, blocked artery", "ex": "The highway is a main artery for the city.", "pos": "n."},
    "artful": {"def": "巧妙的、圓滑的、狡猾的", "ipa": "/ˈɑːtfl/", "trans": "cunning", "col": "artful dodger (機靈鬼)", "ex": "He was an artful liar who could convince anyone.", "pos": "adj."},
    "arthritis": {"def": "關節炎", "ipa": "/ɑːˈθraɪtɪs/", "trans": "joint inflammation", "col": "suffer from arthritis", "ex": "Older people often suffer from arthritis.", "pos": "n."},
    "arthropod": {"def": "節肢動物", "ipa": "/ˈɑːθrəpɒd/", "trans": "arthropods", "col": "various arthropods", "ex": "Insects and spiders are both types of arthropods.", "pos": "n."},
    "artichoke": {"def": "朝鮮薊、菜薊", "ipa": "/ˈɑːtɪtʃəʊk/", "trans": "artichokes", "col": "globe artichoke", "ex": "He likes to eat globe artichokes with garlic butter.", "pos": "n."},
    "article": {"def": "文章、條款、物品、冠詞、訂約、記載、契約地、條款地 (文章)", "ipa": "/ˈɑːtɪkl/", "trans": "articles", "col": "newspaper article, article of clothing, definite article", "ex": "I read an interesting article in the paper.", "pos": "n./v./adv."},
    "articular": {"def": "關節的", "ipa": "/ɑːˈtɪkjələ/", "trans": "joint", "col": "articular surface", "ex": "The injury affected the articular surface of the knee.", "pos": "adj."},
    "articulate": {"def": "發音清晰的、善於表達的、有節的、清晰地發(音)、用關節連接、接合的人 (或物)、清晰地 (發音)", "ipa": "/ɑːˈtɪkjələt/ (adj.) /ɑːˈtɪkjuleɪt/ (v.)", "trans": "articulation", "col": "articulate speaker, highly articulate", "ex": "She is a highly articulate and persuasive speaker.", "pos": "adj./v./n./adv."},
    "articulation": {"def": "發音、關節、接合、表達", "ipa": "/ɑːˌtɪkjuˈleɪʃn/", "trans": "articulate (形容詞/動詞/名詞/副詞)", "col": "clear articulation", "ex": "Good articulation is important for a singer.", "pos": "n."},
    "artifact/artefact": {"def": "文物、手工藝品、人造物品 (單數)", "ipa": "/ˈɑːtɪfækt/", "trans": "artifacts/artefacts (複數)", "col": "ancient artifact", "ex": "The museum displays many ancient Egyptian artifacts.", "pos": "n."},
    "artifice": {"def": "技巧、詭計、欺騙", "ipa": "/ˈɑːtɪfɪs/", "trans": "trickery", "col": "without artifice", "ex": "She preferred a life without artifice.", "pos": "n."},
    "artificial": {"def": "人造的、人工的、做作的、假裝、人造物、人工地 (人工)", "ipa": "/ˌɑːtɪˈfɪʃl/", "trans": "artificially, artificiality", "col": "artificial intelligence (AI), artificial flowers", "ex": "The room was lit by artificial light.", "pos": "adj./n./adv."},
    "artificiality": {"def": "人工、人造、不自然、做作", "ipa": "/ˌɑːtɪˌfɪʃiˈæləti/", "trans": "artificial (形容詞/名詞/副詞)", "col": "sheer artificiality", "ex": "He disliked the sheer artificiality of the Hollywood lifestyle.", "pos": "n."},
    "artificially": {"def": "人工地、人造地、做作地", "ipa": "/ˌɑːtɪˈfɪʃəli/", "trans": "artificial (形容詞/名詞/副詞)", "col": "artificially sweeteners", "ex": "The pond was artificially created.", "pos": "adv."},
    "artillery": {"def": "大炮、炮兵、炮術", "ipa": "/ɑːˈtɪləri/", "trans": "cannons", "col": "heavy artillery", "ex": "The heavy artillery bombarded the enemy lines.", "pos": "n."},
    "artisan": {"def": "工匠、技工、手工業者、工匠的", "ipa": "/ˌɑːtɪˈzæn/", "trans": "craftsman", "col": "skilled artisan", "ex": "The market is famous for its skilled artisans.", "pos": "n./adj."},
    "artist": {"def": "藝術家、美工、能手、藝術的人 (或物)", "ipa": "/ˈɑːtɪst/", "trans": "artistic", "col": "struggling artist, professional artist", "ex": "He is a struggling artist working in London.", "pos": "n."},
    "artistic": {"def": "藝術的、美學的、有藝術才能的、藝術地 (藝術)", "ipa": "/ɑːˈtɪstɪk/", "trans": "artist, artistically", "col": "artistic director, artistic achievement", "ex": "She has a lot of artistic talent.", "pos": "adj./adv."},
    "artistically": {"def": "藝術地、美學地、有術才能地", "ipa": "/ɑːˈtɪstɪkli/", "trans": "artistic (形容詞/副詞), artist", "col": "artistically designed", "ex": "The house is artistically designed.", "pos": "adv."},
    "artistry": {"def": "藝術技巧、藝術才華", "ipa": "/ˈɑːtɪstri/", "trans": "art", "col": "creative artistry", "ex": "The book shows a great deal of creative artistry.", "pos": "n."},
    "artless": {"def": "天真的、樸實的、無虛飾的、拙劣的", "ipa": "/ˈɑːtləs/", "trans": "natural", "col": "artless charm", "ex": "She won everyone over with her artless charm.", "pos": "adj."},
    "as": {"def": "像...一樣、作為、當...時、因為、正如、同時、正如地、作為地 (如)", "ipa": "/æz/", "trans": "like", "col": "as if, as though, as well as", "ex": "She works as a teacher.", "pos": "prep./conj./adv."},
    "asbestos": {"def": "石棉、石棉的、不燃的", "ipa": "/æsˈbestəs/", "trans": "insulation", "col": "remove asbestos", "ex": "Asbestos was widely used in insulation in the past.", "pos": "n./adj."},
    "ascend": {"def": "上升、攀登、登基", "ipa": "/əˈsend/", "trans": "ascent, ascending", "col": "ascend the stairs, ascend the throne", "ex": "He slowly ascended the stairs.", "pos": "v."},
    "ascendancy/ascendency": {"def": "支配地位、優勢、權勢", "ipa": "/əˈsendənsi/", "trans": "dominant", "col": "moral ascendancy", "ex": "The party is struggling to regain its moral ascendancy.", "pos": "n."},
    "ascendant/ascendent": {"def": "占優勢的、上升的、祖先、優勢、(星)上升星座", "ipa": "/əˈsendənt/", "trans": "ascending", "col": "in the ascendant (在上升中)", "ex": "He is an actor whose career is in the ascendant.", "pos": "adj./n."},
    "ascending": {"def": "上升的、向上的", "ipa": "/əˈsendɪŋ/", "trans": "ascend (動詞)", "col": "ascending order", "ex": "The numbers are arranged in ascending order.", "pos": "adj."},
    "ascent": {"def": "上升、攀登、坡度、追溯、上升的人 (或物)", "ipa": "/əˈsent/", "trans": "ascend (動詞), ascending", "col": "steep ascent, balloon ascent", "ex": "The balloon's ascent was smooth and steady.", "pos": "n."},
    "ascertain": {"def": "弄清、確定、查明", "ipa": "/ˌæsəˈteɪn/", "trans": "find out", "col": "ascertain the facts", "ex": "We need to ascertain the facts before making a decision.", "pos": "v."},
    "ascetic": {"def": "苦行的、禁慾的、苦行者、禁慾主義者、苦行地 (苦行)", "ipa": "/əˈsetɪk/", "trans": "asceticism", "col": "ascetic life", "ex": "He leads a very simple and ascetic life.", "pos": "adj./n./adv."},
    "asceticism": {"def": "苦行主義、禁慾主義", "ipa": "/əˈsetɪsɪzəm/", "trans": "ascetic", "col": "religious asceticism", "ex": "He practiced strict religious asceticism.", "pos": "n."},
    "ascribe": {"def": "歸因於、賦予", "ipa": "/əˈskraɪb/", "trans": "ascription", "col": "ascribe to", "ex": "The failure was ascribed to poor management.", "pos": "v."},
    "asexual": {"def": "無性的、無性生殖的、無性的人 (或物)、無性地 (無性)", "ipa": "/ˌeɪˈsekʃuəl/", "trans": "sexless", "col": "asexual reproduction", "ex": "Some plants reproduce by asexual means.", "pos": "adj./n./adv."},
    "ash": {"def": "灰、灰燼、白蠟樹、灰燼、化為灰、灰燼地 (灰)", "ipa": "/æʃ/", "trans": "ashes", "col": "cigarette ash, volcanic ash", "ex": "She flicked the cigarette ash into the tray.", "pos": "n./v./adv."},
    "ashamed": {"def": "羞愧的、害羞的、慚愧的", "ipa": "/əˈʃeɪmd/", "trans": "shame", "col": "ashamed of", "ex": "He was ashamed of his behavior.", "pos": "adj."},
    "ashore": {"def": "在岸上、向岸上、登陸", "ipa": "/əˈʃɔː/", "trans": "land", "col": "come ashore, go ashore", "ex": "The passengers went ashore for a few hours.", "pos": "adv."},
    "aside": {"def": "在旁邊、除...之外、撇開、旁白、離題的話、旁白的人 (或事)、旁白地 (旁白)", "ipa": "/əˈsaɪd/", "trans": "sideways", "col": "aside from, set aside, stand aside", "ex": "He set his work aside and went out for a walk.", "pos": "adv./n./adj."},
    "asinine": {"def": "驢的、愚蠢的、頑固的", "ipa": "/ˈæsɪnaɪn/", "trans": "stupid", "col": "asinine remark", "ex": "What an asinine things to say!", "pos": "adj."},
    "ask": {"def": "詢問、求取、要求、問侯、邀請、需求、詢問的人物、詢問地 (詢問)", "ipa": "/ɑːsk/", "trans": "asked", "col": "ask for, ask out, ask about", "ex": "Can I ask you a question?", "pos": "v./n./adv."},
    "askance": {"def": "斜視地、懷疑地、不滿地", "ipa": "/əˈskæns/", "trans": "suspiciously", "col": "look askance at", "ex": "They looked askance at the new proposta.", "pos": "adv."},
    "askew": {"def": "歪斜地、斜眼地、歪的 (歪斜)", "ipa": "/əˈskjuː/", "trans": "crooked", "col": "hat askew", "ex": "Her hat was slightly askew.", "pos": "adv./adj."},
    "asleep": {"def": "睡著的、麻木的、長眠的、睡著地 (睡著)", "ipa": "/əˈsliːp/", "trans": "sleeping", "col": "fall asleep, fast asleep", "ex": "The baby is fast asleep.", "pos": "adj./adv."},
    "aspect": {"def": "方面、樣子、面貌、方位", "ipa": "/ˈæspekt/", "trans": "aspects", "col": "important aspect, technical aspect", "ex": "We need to consider every aspect of the problem.", "pos": "n."},
    "aspen": {"def": "白楊、山楊、白楊的、顫抖的", "ipa": "/ˈæspən/", "trans": "poplar", "col": "aspen leaves", "ex": "The aspen leaves tremble in the breeze.", "pos": "n./adj."},
    "asperity": {"def": "粗魯、嚴厲、(氣候)嚴酷", "ipa": "/æˈsperəti/", "trans": "harshness", "col": "speak with asperity", "ex": "She spoke with some asperity.", "pos": "n."},
    "aspersion": {"def": "誹謗、中傷、(宗教)灑水", "ipa": "/əˈspɜːʃn/", "trans": "slander", "col": "cast aspersions on (誹謗)", "ex": "He cast aspersions on the character of his rival.", "pos": "n."},
    "asphalt": {"def": "瀝青、柏油、鋪瀝青、瀝青的、柏油的地 (瀝青)", "ipa": "/ˈæsfælt/", "trans": "bitumen", "col": "asphalt road", "ex": "The road was paved with asphalt.", "pos": "n./v./adj./adv."},
    "asphyxiate": {"def": "窒息、使窒息", "ipa": "/əsˈfɪksieɪt/", "trans": "suffocate", "col": "asphyxiate by smoke", "ex": "Many people were asphyxiated by the smoke from the fire.", "pos": "v."},
    "asphyxiation": {"def": "窒息", "ipa": "/əsˌfɪksiˈeɪʃn/", "trans": "suffocation", "col": "die of asphyxiation", "ex": "The cause of death was asphyxiation.", "pos": "n."},
    "aspiration": {"def": "抱負、志向、吸引、(語)送氣", "ipa": "/ˌæspəˈreɪʃn/", "trans": "aspire (動詞)", "col": "higher aspiration", "ex": "He has higher aspirations for the future.", "pos": "n."},
    "aspire": {"def": "嚮往、渴望、立志", "ipa": "/əˈspaɪə/", "trans": "aspiration", "col": "aspire to", "ex": "She aspires to become a world-famous singer.", "pos": "v."},
    "aspirin": {"def": "阿斯匹靈、止痛藥", "ipa": "/ˈæsprɪn/", "trans": "painkiller", "col": "take an aspirin", "ex": "Take an aspirin for your headache.", "pos": "n."},
    "ass": {"def": "驢子、混蛋、屁股 (美俚)、驢子般的、愚蠢的地 (驢)", "ipa": "/æs/", "trans": "asses", "col": "stupid ass, make an ass of oneself", "ex": "Don't be a stupid ass!", "pos": "n./adj./adv."},
    "assail": {"def": "攻擊、襲擊、質問、困擾", "ipa": "/əˈseɪl/", "trans": "assailant", "col": "assail with questions", "ex": "They were assailed with questions by the reporters.", "pos": "v."},
}