import json

# Level 6 Part 13: (Assailant - Astound)
L6_PART13 = {
    "assailant": {"def": "打擊者、襲擊者", "ipa": "/əˈseɪlənt/", "trans": "assail (動詞)", "col": "unknown assailant", "ex": "She managed to fight off her assailant.", "pos": "n."},
    "assassin": {"def": "刺客、暗殺者", "ipa": "/əˈsæsɪn/", "trans": "assassinate", "col": "political assassin", "ex": "The assassin was caught shortly after the shooting.", "pos": "n."},
    "assassinate": {"def": "暗殺、行刺、誹謗", "ipa": "/əˈsæsɪneɪt/", "trans": "assassination, assassin", "col": "assassinate a leader", "ex": "The president was assassinated in 1963.", "pos": "v."},
    "assassination": {"def": "暗殺、行刺、誹謗", "ipa": "/əˌsæsɪˈneɪʃn/", "trans": "assassinate (動詞), assassin", "col": "political assassination", "ex": "The political assassination shocked the nation.", "pos": "n."},
    "assault": {"def": "攻擊、襲擊、毆打、強姦、襲擊、攻擊、攻擊的、衝鋒的、攻擊地 (攻擊)", "ipa": "/əˈsɔːlt/", "trans": "assaulted", "col": "sexual assault, physical assault, committed an assault", "ex": "He was charged with sexual assault.", "pos": "n./v./adj./adv."},
    "assee/assay": {"def": "分析、化驗、考驗、(法)鑑定、分析的人 (或物)", "ipa": "/əˈseɪ/", "trans": "assays", "col": "assay gold", "ex": "The sample was sent to a laboratory to be assayed.", "pos": "n./v./adv."},
    "assemblage": {"def": "集合、集會、組件、裝配", "ipa": "/əˈsemblɪdʒ/", "trans": "assemble (動詞/副詞)", "col": "strange assemblage", "ex": "A strange assemblage of people gathered in the street.", "pos": "n."},
    "assemble": {"def": "集合、收集、裝配、集會、集合的人 (或物)、集合地 (集合)", "ipa": "/əˈsembl/", "trans": "assembly, assemblage", "col": "assemble furniture, assemble the team", "ex": "The students assembled in the hall.", "pos": "v./n./adv."},
    "assembly": {"def": "集合、集會、會議、組件、裝配、集會的、裝配的、集會地 (集會)", "ipa": "/əˈsembli/", "trans": "assemble (動詞/副詞), assemblage", "col": "general assembly, assembly line, legislative assembly", "ex": "The school holds an assembly every morning.", "pos": "n./adj./adv."},
    "assent": {"def": "同意、贊成、承認、贊成的人 (或事)", "ipa": "/əˈsent/", "trans": "consent", "col": "royal assent, nod in assent", "ex": "He nodded his head in silent assent.", "pos": "n./v./adv."},
    "assert": {"def": "斷言、聲稱、維護、堅持", "ipa": "/əˈsɜːt/", "trans": "assertion, assertive", "col": "assert dominance, assert one's rights", "ex": "She continued to assert her innocence.", "pos": "v."},
    "assertion": {"def": "斷言、聲稱、堅持、主張", "ipa": "/əˈsɜːʃn/", "trans": "assert (動詞), assertive", "col": "bold assertion", "ex": "We need evidence to support your assertion.", "pos": "n."},
    "assertive": {"def": "斷定的、過分自信的、肯定的", "ipa": "/əˈsɜːtɪv/", "trans": "assert (動詞), assertion", "col": "assertive behavior", "ex": "You need to be more assertive if you want a promotion.", "pos": "adj."},
    "assertively": {"def": "斷定地、過分自信地、肯定地", "ipa": "/əˈsɜːtɪvli/", "trans": "assertive (形容詞), assert", "col": "act assertively", "ex": "She spoke assertively to the committee.", "pos": "adv."},
    "assess": {"def": "評估、估價、徵(稅)、罰(款)", "ipa": "/əˈses/", "trans": "assessment, assessor", "col": "assess risk, assess damage", "ex": "Engineers are still assessing the damage caused by the earthquake.", "pos": "v."},
    "assessment": {"def": "評估、估價、評價、徵稅額", "ipa": "/əˈsesmənt/", "trans": "assess (動詞), assessor", "col": "environmental assessment, risk assessment", "ex": "We need to conduct an environmental assessment of the project.", "pos": "n."},
    "assessor": {"def": "評估員、顧問、副審理人", "ipa": "/əˈsesə/", "trans": "assess (動詞), assessment", "col": "tax assessor, external assessor", "ex": "The tax assessor valued the property at $200,000.", "pos": "n."},
    "asset": {"def": "資產、優點、財產、有用的東西", "ipa": "/ˈæset/", "trans": "assets", "col": "valuable asset, liquid assets, total assets", "ex": "Her knowledge of Spanish is a valuable asset to the company.", "pos": "n."},
    "assiduous": {"def": "勤勉的、刻苦的、不懈的", "ipa": "/əˈsɪdjuəs/", "trans": "diligent", "col": "assiduous student", "ex": "He is an assiduous student who always finishes his homework.", "pos": "adj."},
    "assign": {"def": "分配、指派、約定、賦予、分配的人 (或物)、分配地 (分配)", "ipa": "/əˈsaɪn/", "trans": "assignment", "col": "assign homework, assign blame", "ex": "The teacher assigned each student a partner.", "pos": "v./n./adv."},
    "assignment": {"def": "任務、作業、分配、約定地 (約定)", "ipa": "/əˈsaɪnmənt/", "trans": "assign (動詞/名詞/副詞)", "col": "written assignment, special assignment", "ex": "I have to finish my written assignment by tomorrow.", "pos": "n./adv."},
    "assimilate": {"def": "吸收、同化、消化、使相同、同化的人 (或物)、吸收地 (吸收)", "ipa": "/əˈsɪməleɪt/", "trans": "assimilation", "col": "assimilate information", "ex": "It takes time to assimilate all this new information.", "pos": "v./n./adv."},
    "assimilation": {"def": "吸收、同化、消化", "ipa": "/əˌsɪməˈleɪʃn/", "trans": "assimilate (動詞/名詞/副詞)", "col": "cultural assimilation", "ex": "The cultural assimilation of immigrants can take generations.", "pos": "n."},
    "assist": {"def": "協助、輔助、(體)助攻、協助的人 (或物)、協助地 (協助)", "ipa": "/əˈsɪst/", "trans": "assistance, assistant", "col": "assist someone with, rendered assist", "ex": "Can you assist me with these boxes?", "pos": "v./n./adv."},
    "assistance": {"def": "協助、援助、補助", "ipa": "/əˈsɪstəns/", "trans": "assist (動詞/名詞/副詞), assistant", "col": "financial assistance, technical assistance", "ex": "The company provides financial assistance to its employees.", "pos": "n."},
    "assistant": {"def": "助理、助手、助理的、輔助的、助理地 (助理)", "ipa": "/əˈsɪstənt/", "trans": "assist (動詞/名詞/副詞), assistance", "col": "research assistant, personal assistant", "ex": "He works as a research assistant at the university.", "pos": "n./adj./adv."},
    "associable": {"def": "可聯想的、好交際的", "ipa": "/əˈsəʊʃiəbl/", "trans": "associate", "col": "associable ideas", "ex": "These are not normally associable ideas.", "pos": "adj."},
    "associate": {"def": "關聯、交友、聯想、同事、合夥人、伴侶、副的、聯合的、同事般的、同事地 (同事)", "ipa": "/əˈsəʊʃieɪt/ (v.) /əˈsəʊʃiət/ (n./adj.)", "trans": "association, associated", "col": "business associate, associate member, associate degree", "ex": "I don't want to associate with those people.", "pos": "v./n./adj./adv."},
    "associated": {"def": "關聯的、聯合的、(建)聯合的", "ipa": "/əˈsəʊʃieɪtɪd/", "trans": "associate (動詞/名詞/形容詞/副詞), association", "col": "associated with, risks associated", "ex": "There are some risks associated with this surgery.", "pos": "adj."},
    "association": {"def": "協會、協會的、聯合的、聯合、關聯、聯想、協會的人 (或物)、協會地 (協會)", "ipa": "/əˌsəʊʃiˈeɪʃn/", "trans": "associate (動詞/名詞/形容詞/副詞), associated", "col": "professional association, housing association", "ex": "He is a member of the local football association.", "pos": "n./adj./adv."},
    "assonance": {"def": "類韻、諧音、相似的人 (或物)", "ipa": "/ˈæsənəns/", "trans": "rhyme", "col": "vowel assonance", "ex": "The poem uses a lot of vowel assonance.", "pos": "n./adv."},
    "assonant": {"def": "類韻的、諧音的、(語)諧音的", "ipa": "/ˈæsənənt/", "trans": "assonance", "col": "assonant words", "ex": "These two words are assonant.", "pos": "adj."},
    "assort": {"def": "分類、分級、相配、配合地 (配合)", "ipa": "/əˈsɔːt/", "trans": "assortment", "col": "assort with", "ex": "The goods are assorted by size and quality.", "pos": "v./adv."},
    "assorted": {"def": "各式各樣的、什錦的、匹配的", "ipa": "/əˈsɔːtɪd/", "trans": "assort (動詞/副詞), assortment", "col": "assorted chocolates, assorted biscuits", "ex": "The box contains assorted chocolates.", "pos": "adj."},
    "assortment": {"def": "品類、各式各樣、什錦、什錦地 (什錦)", "ipa": "/əˈsɔːtmənt/", "trans": "assort (動詞/副詞), assorted", "col": "wide assortment, assorted variety", "ex": "The shop has a wide assortment of gifts.", "pos": "n./adv."},
    "assuage": {"def": "平息、緩和、滿足", "ipa": "/əˈsweɪdʒ/", "trans": "soothe", "col": "assuage hunger, assuage guilt", "ex": "The news helped to assuage her fears.", "pos": "v."},
    "assumable": {"def": "可假定的、可承擔的", "ipa": "/əˈsjuːməbl/", "trans": "assume", "col": "assumable risk", "ex": "This is an assumable risk for the company.", "pos": "adj."},
    "assume": {"def": "假定、設想、承擔、呈現、假裝地 (假裝)", "ipa": "/əˈsjuːm/", "trans": "assumption, assumed", "col": "assume responsibility, assume the worst", "ex": "I assume that you are tired after the trip.", "pos": "v./adv."},
    "assumed": {"def": "假定的、假裝的、被承擔的", "ipa": "/əˈsjuːmd/", "trans": "assume (動詞/副詞), assumption", "col": "assumed name", "ex": "He traveled under an assumed name.", "pos": "adj."},
    "assuming": {"def": "假定、如果、傲慢的、假設地 (假設)", "ipa": "/əˈsjuːmɪŋ/", "trans": "assume (動詞/副詞), assumption", "col": "assuming that", "ex": "Assuming that it rains, what will we do?", "pos": "conj./adj./adv."},
    "assumption": {"def": "假定、設想、承擔、傲慢、假定地 (假定)", "ipa": "/əˈsʌmpʃn/", "trans": "assume (動詞/副詞/連接詞/形容詞), assumed", "col": "make an assumption, on the assumption that", "ex": "Your argument is based on a false assumption.", "pos": "n./adv."},
    "assurance": {"def": "保證、信心、保險、確實地 (確實)", "ipa": "/əˈʃʊərəns/", "trans": "assure (動詞/副詞), assured", "col": "give an assurance, quality assurance, life assurance", "ex": "He spoke with great assurance.", "pos": "n./adv."},
    "assure": {"def": "保證、使確信、弄清楚、確保地 (確保)", "ipa": "/əˈʃʊə/", "trans": "assurance, assured", "col": "assure someone of, rest assured", "ex": "I can assure you that everything will be fine.", "pos": "v./adv."},
    "assuredly": {"def": "確實地、無庸置疑地、自信地", "ipa": "/əˈʃʊərədli/", "trans": "assured (形容詞), assure", "col": "most assuredly", "ex": "Most assuredly, he will win the race.", "pos": "adv."},
    "aster": {"def": "紫菀、翠菊", "ipa": "/ˈæstə/", "trans": "asters", "col": "wild aster", "ex": "The garden was filled with colorful asters.", "pos": "n."},
    "asterisk": {"def": "星號 ( * )、星號標誌、星號地 (星號)", "ipa": "/ˈæstərɪsk/", "trans": "asterisks", "col": "marked with an asterisk", "ex": "I have marked the important items with an asterisk.", "pos": "n./v./adv."},
    "asteroid": {"def": "小行星、海星、星狀的、星狀地 (星狀)", "ipa": "/ˈæstərɔɪd/", "trans": "asteroids", "col": "asteroid belt", "ex": "Many asteroids are found in the asteroid belt.", "pos": "n./adj./adv."},
    "asthma": {"def": "氣喘、哮喘", "ipa": "/ˈæsmə/", "trans": "asthmatic", "col": "suffer from asthma", "ex": "She has been suffering from asthma since she was a child.", "pos": "n."},
    "asthmatic": {"def": "氣喘的、患氣喘的人、氣喘地 (氣喘)", "ipa": "/æsˈmætɪk/", "trans": "asthma (名詞)", "col": "asthmatic cough", "ex": "He has a persistent asthmatic cough.", "pos": "adj./n./adv."},
    "astigmatism": {"def": "散光、散光性", "ipa": "/əˈstɪɡmətɪzəm/", "trans": "vision problem", "col": "suffer from astigmatism", "ex": "He needs glasses to correct his astigmatism.", "pos": "n."},
    "astir": {"def": "起身的、活動的、騷動地、起身地 (騷動)", "ipa": "/əˈstɜː/", "trans": "stirring", "col": "all astir", "ex": "The whole house was astir early in the morning.", "pos": "adj./adv."},
    "astonish": {"def": "使大吃一驚、使驚訝", "ipa": "/əˈstɒnɪʃ/", "trans": "astonishment, astonishing", "col": "astonish everyone", "ex": "The news astonished everyone.", "pos": "v."},
    "astonishing": {"def": "令人驚訝的、驚人的", "ipa": "/əˈstɒnɪʃɪŋ/", "trans": "astonish (動詞), astonishment", "col": "astonishing discovery", "ex": "It's an astonishing discovery for the scientists.", "pos": "adj."},
    "astonishment": {"def": "大吃一驚、驚訝、驚人之事 (或人)", "ipa": "/əˈstɒnɪʃmənt/", "trans": "astonish (動詞), astonishing", "col": "stare in astonishment", "ex": "She stared at him in astonishment.", "pos": "n."},
    "astound": {"def": "使大吃一驚、使驚愕", "ipa": "/əˈstaʊnd/", "trans": "astounding", "col": "astound by", "ex": "The results of the test astounded the teachers.", "pos": "v."},
}