import json

# Level 3 Part 5: (Bar - Bone)
L3_PART5 = {
    "bar": {"def": "酒吧、條、塊、障礙、法庭、阻攔、不包括", "ipa": "/bɑː/", "trans": "barrier, barred", "col": "snack bar, bar code, chocolate bar, behind bars", "ex": "He was barred from entering the club.", "pos": "n./v./prep."},
    "barb": {"def": "倒鉤、刺、尖刻的話、裝倒鉤於", "ipa": "/bɑːb/", "trans": "barbed", "col": "barbed wire", "ex": "The fish hook has a sharp barb.", "pos": "n./v."},
    "barbecue/BBQ": {"def": "烤肉、戶外烤肉會、在火上烤", "ipa": "/ˈbɑːbɪkjuː/", "trans": "barbecued", "col": "have a barbecue", "ex": "We had a barbecue in the garden.", "pos": "n./v."},
    "barber": {"def": "理髮師、理髮店、理髮", "ipa": "/ˈbɑːbə/", "trans": "barbershop", "col": "go to the barber", "ex": "He went to the barber for a haircut.", "pos": "n./v."},
    "bare": {"def": "裸的、赤裸的、僅有的、露出、揭露", "ipa": "/beə/", "trans": "barely, bareness", "col": "bare feet, bare hands, bare of", "ex": "He was walking with bare feet.", "pos": "adj./v."},
    "barely": {"def": "僅僅、幾乎不、貧乏地", "ipa": "/ˈbeəli/", "trans": "bare (形容詞)", "col": "barely enough", "ex": "I can barely see you in the dark.", "pos": "adv."},
    "bargain": {"def": "特價商品、協議、交易、討價還價", "ipa": "/ˈbɑːɡən/", "trans": "bargaining", "col": "good bargain, bargain with", "ex": "I bought this shirt for $5; it was a real bargain.", "pos": "n./v."},
    "bark": {"def": "犬吠、樹皮、吠叫、咆哮", "ipa": "/bɑːk/", "trans": "barked", "col": "bark at", "ex": "The dog barked at the stranger.", "pos": "v./n."},
    "barn": {"def": "穀倉、馬廄、大而空蕩的建築", "ipa": "/bɑːn/", "trans": "barns", "col": "red barn", "ex": "The hay is stored in the barn.", "pos": "n."},
    "barrel": {"def": "大桶、槍管、裝入桶內、飛奔", "ipa": "/ˈbærəl/", "trans": "barrels", "col": "oil barrel, beer barrel", "ex": "Wine is often aged in wooden barrels.", "pos": "n./v."},
    "barrier": {"def": "障礙、柵欄、關卡", "ipa": "/ˈbæriə/", "trans": "bar (名詞/動詞)", "col": "language barrier, trade barrier", "ex": "The language barrier made communication difficult.", "pos": "n."},
    "base": {"def": "基礎、底部、基地、建立在...基礎上、卑鄙的", "ipa": "/beɪs/", "trans": "basic, basement", "col": "military base, based on", "ex": "The theory is based on facts.", "pos": "n./v./adj."},
    "basic": {"def": "基本的、基礎的、基本原理", "ipa": "/ˈbeɪsɪk/", "trans": "base (名詞), basically", "col": "basic needs, basic skills", "ex": "Food and shelter are basic needs.", "pos": "adj./n."},
    "basically": {"def": "基本上、在本質上", "ipa": "/ˈbeɪsɪkli/", "trans": "basic (形容詞)", "col": "basically the same", "ex": "Basically, it's a very simple idea.", "pos": "adv."},
    "basin": {"def": "盆、臉盆、流域、海灣", "ipa": "/ˈbeɪsn/", "trans": "basins", "col": "wash basin, river basin", "ex": "She filled the basin with warm water.", "pos": "n."},
    "basis": {"def": "基礎、根據、主要成份", "ipa": "/ˈbeɪsɪs/", "trans": "base (名詞)", "col": "on the basis of", "ex": "We meet on a regular basis.", "pos": "n."},
    "basket": {"def": "籃子、筐、籃框", "ipa": "/ˈbɑːskɪt/", "trans": "basketball", "col": "shopping basket, wastepaper basket", "ex": "He put the apples in the basket.", "pos": "n."},
    "bass": {"def": "低音的、男低音、低音樂器、鱸魚", "ipa": "/beɪs/", "trans": "bassoon", "col": "bass guitar, double bass", "ex": "He sings bass in the choir.", "pos": "adj./n."},
    "bat": {"def": "球棒、蝙蝠、用球棒打、眨眼(眼皮)", "ipa": "/bæt/", "trans": "batsman", "col": "baseball bat, blind as a bat", "ex": "He hit the ball with his bat.", "pos": "n./v."},
    "bath": {"def": "洗澡、浴缸、洗澡、浸泡", "ipa": "/bɑːθ/", "trans": "bathroom, bathe", "col": "take a bath, bubble bath", "ex": "I like to have a hot bath before bed.", "pos": "n./v."},
    "bathe": {"def": "沖洗、沈浸、洗澡、游泳", "ipa": "/beɪð/", "trans": "bath (名詞), bathing", "col": "bathe in sunlight", "ex": "She bathed her eyes with warm water.", "pos": "v."},
    "bathroom": {"def": "浴室、廁所", "ipa": "/ˈbɑːθruːm/", "trans": "bath (名詞)", "col": "master bathroom", "ex": "I need to go to the bathroom.", "pos": "n."},
    "batter": {"def": "擊球手、麵糊、連續猛擊、搗毀", "ipa": "/ˈbætə/", "trans": "battered", "col": "pancake batter", "ex": "The heavy rain battered the windows.", "pos": "n./v."},
    "battery": {"def": "電池、砲台、一連串", "ipa": "/ˈbætəri/", "trans": "batteries", "col": "rechargeable battery, battery charger", "ex": "My phone battery is low.", "pos": "n."},
    "battle": {"def": "戰鬥、戰役、競爭、鬥爭、戰鬥、奮鬥", "ipa": "/ˈbætl/", "trans": "battlefield", "col": "battle field, win a battle", "ex": "He fought a long battle against cancer.", "pos": "n./v."},
    "bay": {"def": "海灣、分隔間、長嘯、圍住", "ipa": "/beɪ/", "trans": "bays", "col": "keep at bay", "ex": "The boat was anchored in the bay.", "pos": "n./v."},
    "beach": {"def": "海灘、海濱、使船上岸", "ipa": "/biːtʃ/", "trans": "beaches", "col": "on the beach", "ex": "We spent the whole day at the beach.", "pos": "n./v."},
    "bead": {"def": "珠子、水珠、滴、裝珠飾於、成串珠狀", "ipa": "/biːd/", "trans": "beading", "col": "beads of sweat", "ex": "She was wearing a necklace of blue beads.", "pos": "n./v."},
    "beak": {"def": "（鳥類的）喙、口、鼻", "ipa": "/biːk/", "trans": "beaked", "col": "sharp beak", "ex": "The bird has a long, sharp beak.", "pos": "n."},
    "beam": {"def": "光束、樑、燦爛的面容、發光、微笑", "ipa": "/biːm/", "trans": "beamed", "col": "laser beam, balance beam", "ex": "A beam of sunlight came through the window.", "pos": "n./v."},
    "bean": {"def": "豆子、腦袋、擊中頭部", "ipa": "/biːn/", "trans": "bean curd, beanstalk", "col": "green bean, coffee bean, spill the beans", "ex": "I like baked beans on toast.", "pos": "n./v."},
    "bear": {"def": "熊、粗魯的人、負擔、忍受、生育", "ipa": "/beə/", "trans": "birth, born, bearing", "col": "bear in mind, teddy bear, polar bear", "ex": "I can't bear the heat.", "pos": "n./v."},
    "beard": {"def": "鬍鬚(下巴和兩頰的)、公然反對", "ipa": "/bɪəd/", "trans": "bearded", "col": "grow a beard", "ex": "He has a thick black beard.", "pos": "n./v."},
    "beast": {"def": "野獸、殘暴的人、討厭的人事物", "ipa": "/biːst/", "trans": "beastly", "col": "wild beast, beast of burden", "ex": "The tiger is a powerful beast.", "pos": "n."},
    "beat": {"def": "打、跳動、贏過、疲憊的、心跳聲、節拍、巡邏區", "ipa": "/biːt/", "trans": "beating", "col": "heart beat, beat the drum, dead beat", "ex": "He could feel his heart beat faster.", "pos": "v./adj./n."},
    "beautiful": {"def": "美麗的、精彩的", "ipa": "/ˈbjuːtɪfl/", "trans": "beauty, beautifully", "col": "beautiful sunset", "ex": "What a beautiful day!", "pos": "adj."},
    "beauty": {"def": "美、美貌、美人", "ipa": "/ˈbjuːti/", "trans": "beautiful, beautify", "col": "sleeping beauty, beauty salon", "ex": "She is a woman of great beauty.", "pos": "n."},
    "because": {"def": "因為", "ipa": "/bɪˈkɒz/", "trans": "as, since", "col": "because of", "ex": "I stayed home because I was sick.", "pos": "conj."},
    "become": {"def": "變成、成為、變得、適合", "ipa": "/bɪˈkʌm/", "trans": "became", "col": "become of", "ex": "He wants to become a doctor.", "pos": "v."},
    "bed": {"def": "床、河床、花壇、安置、固定", "ipa": "/bed/", "trans": "bedroom, bedding", "col": "go to bed, make the bed, flower bed", "ex": "It's time for bed.", "pos": "n./v."},
    "bedroom": {"def": "臥室、睡房", "ipa": "/ˈbedruːm/", "trans": "bed (名詞)", "col": "master bedroom", "ex": "Our house has three bedrooms.", "pos": "n."},
    "bee": {"def": "蜜蜂、繁忙的人", "ipa": "/biː/", "trans": "beehive, beeswax", "col": "honey bee, busy as a bee", "ex": "A bee is gathering honey from the flowers.", "pos": "n."},
    "beef": {"def": "牛肉、體力、抱怨、抱怨", "ipa": "/biːf/", "trans": "beefy", "col": "roast beef, beef cattle", "ex": "I'd like a medium-rare steak of beef.", "pos": "n./v."},
    "been": {"def": "be的過去分詞", "ipa": "/biːn/", "trans": "be (動詞)", "col": "have been to", "ex": "I've been to London twice.", "pos": "v."},
    "beer": {"def": "啤酒", "ipa": "/bɪə/", "trans": "beers", "col": "glass of beer", "ex": "He likes to drink a beer after work.", "pos": "n."},
    "beetle": {"def": "甲蟲、急速移動、懸垂", "ipa": "/ˈbiːtl/", "trans": "beetling", "col": "stag beetle", "ex": "A black beetle was crawling on the leaf.", "pos": "n./v."},
    "before": {"def": "在...之前、以前、在前面、以前地、之前地", "ipa": "/bɪˈfɔː/", "trans": "after", "col": "before long, days before", "ex": "I've seen him before.", "pos": "prep./conj./adv."},
    "beg": {"def": "請求、乞求、乞討", "ipa": "/beɡ/", "trans": "beggar", "col": "beg for money, beg your pardon", "ex": "He begged her for another chance.", "pos": "v."},
    "beggar": {"def": "乞丐、窮光蛋、使貧窮、使力竭", "ipa": "/ˈbeɡə/", "trans": "beg (動詞)", "col": "street beggar", "ex": "He gave some money to a beggar.", "pos": "n./v."},
    "begin": {"def": "開始、著手", "ipa": "/bɪˈɡɪn/", "trans": "beginning, beginner", "col": "to begin with, begin at", "ex": "Let's begin the meeting.", "pos": "v."},
    "beginner": {"def": "初學者、新手", "ipa": "/bɪˈɡɪnə/", "trans": "begin (動詞)", "col": "absolute beginner", "ex": "This course is for beginners.", "pos": "n."},
    "beginning": {"def": "開始、起頭、初期的", "ipa": "/bɪˈɡɪnɪŋ/", "trans": "begin (動詞)", "col": "at the beginning of", "ex": "I've read the book from the beginning.", "pos": "n./adj."},
    "behalf": {"def": "利益、方面", "ipa": "/bɪˈhɑːf/", "trans": "behalves", "col": "on behalf of", "ex": "I am writing on behalf of my client.", "pos": "n."},
    "behave": {"def": "舉止、行為表現、守規矩", "ipa": "/bɪˈheɪv/", "trans": "behavior", "col": "behave yourself", "ex": "The children behaved very well.", "pos": "v."},
    "behavior": {"def": "行為、舉止、性能", "ipa": "/bɪˈheɪvjə/", "trans": "behave (動詞)", "col": "good behavior, human behavior", "ex": "His behavior was very strange.", "pos": "n."},
    "behind": {"def": "在...後面、落後於、在後、落後地、屁股", "ipa": "/bɪˈhaɪnd/", "trans": "hind", "col": "behind time, leave behind", "ex": "The sun went behind a cloud.", "pos": "prep./adv./n."},
    "being": {"def": "存在、生命、生物、人、目前的", "ipa": "/ˈbiːɪŋ/", "trans": "be (動詞)", "col": "human being", "ex": "A strange being was seen in the forest.", "pos": "n./adj."},
    "belief": {"def": "信念、信仰、相信", "ipa": "/bɪˈliːf/", "trans": "believe (動詞)", "col": "religious belief, beyond belief", "ex": "It's my belief that he's telling the truth.", "pos": "n."},
    "believe": {"def": "相信、信任、認為", "ipa": "/bɪˈliːv/", "trans": "belief (名詞), believer", "col": "believe in", "ex": "I believe you.", "pos": "v."},
    "bell": {"def": "鐘、鈴、鐘聲、裝鈴於、使成鐘狀", "ipa": "/bel/", "trans": "bellows", "col": "doorbell, alarm bell", "ex": "The church bells were ringing.", "pos": "n./v."},
    "belly": {"def": "肚子、腹部、胃、膨脹、凸出", "ipa": "/ˈbeli/", "trans": "bellies", "col": "belly button, pot belly", "ex": "He has a big belly.", "pos": "n./v."},
    "belong": {"def": "屬於、應在...處", "ipa": "/bɪˈlɒŋ/", "trans": "belongings", "col": "belong to", "ex": "Does this book belong to you?", "pos": "v."},
    "belongings": {"def": "財產、攜帶物品", "ipa": "/bɪˈlɒŋɪŋz/", "trans": "belong (動詞)", "col": "personal belongings", "ex": "She put all her belongings in a suitcase.", "pos": "n."},
    "beloved": {"def": "心愛的、深愛的、愛人、親愛的人", "ipa": "/bɪˈlʌvɪd/", "trans": "love", "col": "beloved wife", "ex": "He was mourned by his beloved friends.", "pos": "adj./n."},
    "below": {"def": "在...下面、低於、在下面、在下方", "ipa": "/bɪˈləʊ/", "trans": "above", "col": "below zero, go below", "ex": "The temperature is below zero.", "pos": "prep./adv."},
    "belt": {"def": "皮帶、腰帶、地帶、用帶子捆、抽打、飛奔", "ipa": "/belt/", "trans": "belting", "col": "seat belt, green belt, black belt", "ex": "Please fasten your seat belt.", "pos": "n./v."},
    "bench": {"def": "長凳、工作台、法官席、在長凳上坐、使退場", "ipa": "/bentʃ/", "trans": "benches", "col": "park bench", "ex": "They sat on a bench in the park.", "pos": "n./v."},
    "bend": {"def": "彎曲、屈服、彎道、結節、彎曲", "ipa": "/bend/", "trans": "bent, bending", "col": "bend the truth, bend down", "ex": "The road bends to the left.", "pos": "v./n."},
    "beneath": {"def": "在...正下方、在...之下、在下方、在下面", "ipa": "/bɪˈniːθ/", "trans": "under", "col": "beneath notice", "ex": "They found a treasure buried beneath the floor.", "pos": "prep./adv."},
    "beneficial": {"def": "有益的、有利的", "ipa": "/ˌbenɪˈfɪʃl/", "trans": "benefit (名詞/動詞)", "col": "beneficial effect", "ex": "Exercise is beneficial to your health.", "pos": "adj."},
    "beneficiary": {"def": "受益人", "ipa": "/ˌbenɪˈfɪʃəri/", "trans": "benefit (名詞/動詞)", "col": "sole beneficiary", "ex": "She was the sole beneficiary of her husband's will.", "pos": "n."},
    "benefit": {"def": "利益、補助金、有益於、得益、義演", "ipa": "/ˈbenɪfɪt/", "trans": "beneficial", "col": "benefit from, for the benefit of", "ex": "I hope you will benefit from the experience.", "pos": "n./v."},
    "benevolence": {"def": "仁慈、善行", "ipa": "/bəˈnevələns/", "trans": "benevolent", "col": "act of benevolence", "ex": "The man was known for his benevolence.", "pos": "n."},
    "benevolent": {"def": "仁慈的、慈善的", "ipa": "/bəˈnevələnt/", "trans": "benevolence (名詞)", "col": "benevolent organization", "ex": "He is a benevolent old man.", "pos": "adj."},
    "berry": {"def": "漿果、子", "ipa": "/ˈberi/", "trans": "berries", "col": "strawberry, blueberry", "ex": "The birds are eating the red berries.", "pos": "n."},
    "beside": {"def": "在...旁邊、與...相比", "ipa": "/bɪˈsaɪd/", "trans": "besides", "col": "beside oneself", "ex": "He sat beside me.", "pos": "prep."},
    "besides": {"def": "此外、而且、除...之外（還有）", "ipa": "/bɪˈsaɪdz/", "trans": "beside", "col": "besides that", "ex": "Besides Spanish, she also speaks French.", "pos": "adv./prep."},
    "best": {"def": "最好的、最、最高、最好的作品、打敗、優於", "ipa": "/best/", "trans": "better, good", "col": "do one's best, at best, best friend", "ex": "He is my best friend.", "pos": "adj./adv./n./v."},
    "bestseller": {"def": "暢銷書、銷路最好的商品", "ipa": "/ˌbestˈselə/", "trans": "best-selling", "col": "New York Times bestseller", "ex": "His new novel is a bestseller.", "pos": "n."},
    "bet": {"def": "打賭、賭金、打賭、斷定", "ipa": "/bet/", "trans": "betting, bettor", "col": "you bet, place a bet", "ex": "I bet he'll be late.", "pos": "n./v."},
    "betray": {"def": "背叛、洩露、無意中露出", "ipa": "/bɪˈtreɪ/", "trans": "betrayal, betrayer", "col": "betray a secret", "ex": "He betrayed his country.", "pos": "v."},
    "betrayal": {"def": "背叛、洩露", "ipa": "/bɪˈtreɪəl/", "trans": "betray (動詞)", "col": "act of betrayal", "ex": "The betrayal by his friend was hard to bare.", "pos": "n."},
    "better": {"def": "更好的、更、較優者、長輩、改善、勝過", "ipa": "/ˈbetə/", "trans": "best, good", "col": "better off, had better, get better", "ex": "Are you feeling better now?", "pos": "adj./adv./n./v."},
    "between": {"def": "在...之間、在...兩者之間、介於...之間", "ipa": "/bɪˈtwiːn/", "trans": "among", "col": "between you and me, far between", "ex": "The city is between the mountains and the sea.", "pos": "prep./adv."},
    "beverage": {"def": "飲料", "ipa": "/ˈbevərɪdʒ/", "trans": "beverages", "col": "alcoholic beverage", "ex": "We offer a wide variety of beverages.", "pos": "n."},
    "beware": {"def": "當心、提防", "ipa": "/bɪˈweə/", "trans": "caution", "col": "beware of", "ex": "Beware of pickpockets.", "pos": "v."},
    "beyond": {"def": "在...的那邊、越出、在遠處、在更遠處、遠處", "ipa": "/bɪˈjɒnd/", "trans": "further", "col": "beyond doubt, beyond one's reach", "ex": "The house is just beyond the bridge.", "pos": "prep./adv./n."},
    "bias": {"def": "偏見、斜線、使有偏見、使偏斜、斜的", "ipa": "/ˈbaɪəs/", "trans": "biased", "col": "political bias, gender bias", "ex": "The judge has a bias against the defendant.", "pos": "n./v./adj./adv."},
    "Bible": {"def": "聖經、權威著作", "ipa": "/ˈbaɪbl/", "trans": "biblical", "col": "Holy Bible", "ex": "The Bible is the most translated book in the world.", "pos": "n."},
    "bicycle/bike": {"def": "自行車、騎自行車、騎自行車運送", "ipa": "/ˈbaɪsɪkl/", "trans": "biking, cyclist", "col": "ride a bicycle", "ex": "He goes to school by bicycle.", "pos": "n./v."},
    "bid": {"def": "出價、投標、吩咐、出價、企圖", "ipa": "/bɪd/", "trans": "bidder, bidding", "col": "bid for, make a bid", "ex": "She bid $100 for the painting.", "pos": "v./n."},
    "big": {"def": "大的、重要的、偉大的、慷慨地、大模大樣地", "ipa": "/bɪɡ/", "trans": "bigger, biggest", "col": "big brother, big deal, think big", "ex": "That's a big house.", "pos": "adj./adv."},
    "bike": {"def": "自行車、摩托車、騎自行車", "ipa": "/baɪk/", "trans": "biking", "col": "mountain bike", "ex": "I like biking in the mountains.", "pos": "n./v."},
    "bill": {"def": "帳單、鈔票、議案、鳥喙、給...開帳單、宣傳", "ipa": "/bɪl/", "trans": "billing", "col": "dollar bill, telephone bill, pass a bill", "ex": "Please give me the bill.", "pos": "n./v."},
    "billion": {"def": "十億、無數", "ipa": "/ˈbɪljən/", "trans": "billionaire", "col": "billions of", "ex": "The world population is over 8 billion.", "pos": "num./n."},
    "bin": {"def": "箱子、倉、垃圾箱、把...裝入箱內", "ipa": "/bɪn/", "trans": "bins", "col": "dustbin, recycle bin", "ex": "Throw your trash in the bin.", "pos": "n./v."},
    "bind": {"def": "綑綁、結合、裝訂、使受束縛、束縛、苦境", "ipa": "/baɪnd/", "trans": "bound, binding", "col": "bind together", "ex": "The soldiers were bound with ropes.", "pos": "v./n."},
    "bingo": {"def": "賓果遊戲、中啦！", "ipa": "/ˈbɪŋɡəʊ/", "trans": "bingos", "col": "play bingo", "ex": "Bingo is a popular game at parties.", "pos": "n./int."},
    "biography": {"def": "傳記", "ipa": "/baɪˈɒɡrəfi/", "trans": "biographical, biographer", "col": "official biography", "ex": "He is writing a biography of Steve Jobs.", "pos": "n."},
    "biology": {"def": "生物學、生物、生態", "ipa": "/baɪˈɒlədʒi/", "trans": "biological, biologist", "col": "marine biology", "ex": "She is studying biology at college.", "pos": "n."},
    "bird": {"def": "鳥、禽、傢伙", "ipa": "/bɜːd/", "trans": "birdie", "col": "early bird, bird's eye view", "ex": "The early bird catches the worm.", "pos": "n."},
    "birth": {"def": "出生、分娩、起源", "ipa": "/bɜːθ/", "trans": "born, birthday", "col": "give birth to, date of birth", "ex": "The birth of her child changed her life.", "pos": "n."},
    "birthday": {"def": "生日、創立紀念日", "ipa": "/ˈbɜːθdeɪ/", "trans": "birth (名詞)", "col": "happy birthday", "ex": "When is your birthday?", "pos": "n."},
    "biscuit": {"def": "餅乾、淡褐色", "ipa": "/ˈbɪskɪt/", "trans": "biscuits", "col": "chocolate biscuit", "ex": "I'd like a cup of tea and a biscuit.", "pos": "n."},
    "bishop": {"def": "主教、（西洋棋中的）象", "ipa": "/ˈbɪʃəp/", "trans": "bishops", "col": "Catholic bishop", "ex": "He was appointed bishop of the diocese.", "pos": "n."},
    "bit": {"def": "小塊、一點點、比特、一點點地、些微地", "ipa": "/bɪt/", "trans": "bite (動詞)", "col": "a bit of, quite a bit, little by little", "ex": "I'm a bit tired.", "pos": "n./adv."},
    "bite": {"def": "咬、刺痛、上鉤、咬、一口、尖銳", "ipa": "/baɪt/", "trans": "bit, bitten", "col": "bite off, take a bite", "ex": "The dog bit him on the leg.", "pos": "v./n."},
    "bitter": {"def": "苦的、嚴寒的、痛苦的、苦味、苦啤酒、苦澀地", "ipa": "/ˈbɪtə/", "trans": "bitterness, bitterly", "col": "bitter pill, bitter irony", "ex": "The coffee tastes very bitter.", "pos": "adj./n./adv."},
    "black": {"def": "黑色的、黑暗的、邪惡的、黑色、黑人、使變黑", "ipa": "/blæk/", "trans": "blackness, blacken", "col": "black market, black box, in the black", "ex": "She was wearing a black dress.", "pos": "adj./n./v."},
    "blackboard": {"def": "黑板", "ipa": "/ˈblækbɔːd/", "trans": "chalkboard", "col": "write on the blackboard", "ex": "The teacher wrote the homework on the blackboard.", "pos": "n."},
    "blade": {"def": "刀刃、葉片、槳葉", "ipa": "/bleɪd/", "trans": "blades", "col": "razor blade, shoulder blade", "ex": "The knife has a sharp blade.", "pos": "n."},
    "blame": {"def": "責備、歸咎於、過失、責備", "ipa": "/bleɪm/", "trans": "blameless", "col": "be to blame, blame someone for", "ex": "Don't blame me for your mistakes.", "pos": "v./n."},
    "blank": {"def": "空白的、茫然的、空白處、空彈、使模糊、使無效", "ipa": "/blæŋk/", "trans": "blankly", "col": "fill in the blanks", "ex": "My mind went completely blank.", "pos": "adj./n./v."},
    "blanket": {"def": "毯子、面、毯狀物、全面性的、覆蓋、掩蓋", "ipa": "/ˈblæŋkɪt/", "trans": "blanketing", "col": "electric blanket", "ex": "The ground was covered with a blanket of snow.", "pos": "n./adj./v."},
    "blast": {"def": "爆破、強風、狂歡、爆破、猛擊、抨擊", "ipa": "/blɑːst/", "trans": "blasting", "col": "blast off, at full blast", "ex": "Several people were killed in the blast.", "pos": "n./v."},
    "blaze": {"def": "火焰、烈火、閃耀、燃燒、照耀、宣布", "ipa": "/bleɪz/", "trans": "blazing", "col": "in a blaze of glory", "ex": "The fire blazed all night.", "pos": "n./v."},
    "bleach": {"def": "漂白劑、漂白、漂白、變白", "ipa": "/bliːtʃ/", "trans": "bleached", "col": "chlorine bleach", "ex": "She used bleach to get the stains out of her shirt.", "pos": "n./v."},
    "bleed": {"def": "流血、出血、勒索", "ipa": "/bliːd/", "trans": "bleeding, blood", "col": "my nose is bleeding", "ex": "His leg was bleeding badly.", "pos": "v."},
    "blend": {"def": "混合、摻和、混合物、調和", "ipa": "/blend/", "trans": "blender, blending", "col": "blend together", "ex": "Oil and water do not blend.", "pos": "v./n."},
    "bless": {"def": "賜福、保佑、求神保佑", "ipa": "/bles/", "trans": "blessing, blessed", "col": "God bless you", "ex": "May God bless you and your family.", "pos": "v."},
    "blessing": {"def": "賜福、幸事、同意", "ipa": "/ˈblesɪŋ/", "trans": "bless (動詞)", "col": "disguise in blessing", "ex": "The rain was a blessing for the farmers.", "pos": "n."},
    "blind": {"def": "失明的、盲目的、百葉窗、隱蔽物、使失明、盲目地", "ipa": "/blaɪnd/", "trans": "blindness, blindly", "col": "blind spot, blind date, color blind", "ex": "He has been blind since birth.", "pos": "adj./n./v./adv."},
    "blink": {"def": "眨眼、閃爍、眨眼、一瞬間", "ipa": "/blɪŋk/", "trans": "blinking", "col": "in a blink of an eye", "ex": "He blinked his eyes in the bright light.", "pos": "v./n."},
    "blizzard": {"def": "大風雪、暴風雪", "ipa": "/ˈblɪzəd/", "trans": "blizzards", "col": "survive a blizzard", "ex": "We got stuck in a blizzard.", "pos": "n."},
    "block": {"def": "街區、大塊、障礙、阻礙、阻塞", "ipa": "/blɒk/", "trans": "blockage", "col": "office block, traffic block, roadblocks", "ex": "The fallen tree blocked the road.", "pos": "n./v."},
    "blockade": {"def": "封鎖、障礙、封鎖、阻止", "ipa": "/blɒˈkeɪd/", "trans": "block (名詞/動詞)", "col": "naval blockade, raise a blockade", "ex": "The military established a blockade of the city.", "pos": "n./v."},
    "blond(e)": {"def": "金髮的、金髮女郎", "ipa": "/blɒnd/", "trans": "fair-haired", "col": "natural blonde", "ex": "She has long blonde hair.", "pos": "adj./n."},
    "blood": {"def": "血液、血統、生命、放血、流血", "ipa": "/blʌd/", "trans": "bloody, bleed", "col": "blood pressure, blood donor, in cold blood", "ex": "They are searching for a blood donor.", "pos": "n./v."},
    "bloody": {"def": "流血的、殘酷的、血腥的、該死的（罵人）", "ipa": "/ˈblʌdi/", "trans": "blood (名詞), bloodily", "col": "bloody Mary, bloody mess", "ex": "He had a bloody nose after the fight.", "pos": "adj./adv."},
    "bloom": {"def": "花、開花期、青春、開花、繁榮", "ipa": "/bluːm/", "trans": "blooming", "col": "in full bloom", "ex": "The cherry trees are in full bloom.", "pos": "n./v."},
    "blossom": {"def": "花、開花期、開花、繁榮、發展", "ipa": "/ˈblɒsəm/", "trans": "blossoming", "col": "cherry blossom", "ex": "The apple trees are covered in blossom.", "pos": "n./v."},
    "blot": {"def": "污點、瑕疵、吸乾(水分)、弄髒", "ipa": "/blɒt/", "trans": "blotting", "col": "blot out", "ex": "There was a large ink blot on the paper.", "pos": "n./v."},
    "blouse": {"def": "女襯衫、短衫、使寬鬆地垂下", "ipa": "/blaʊz/", "trans": "blouses", "col": "silk blouse", "ex": "She was wearing a white silk blouse.", "pos": "n./v."},
    "blow": {"def": "吹、打擊、喘氣、強風、擊、吹", "ipa": "/bləʊ/", "trans": "blew, blown", "col": "blow out, blow up, come to blows", "ex": "A cold wind began to blow.", "pos": "v./n."},
    "blue": {"def": "藍色的、憂鬱的、黃色的、藍色、天空、使變藍", "ipa": "/bluː/", "trans": "blueness, bluish", "col": "blue jeans, once in a blue moon, out of the blue", "ex": "The sky is clear and blue.", "pos": "adj./n./v."},
    "blueprint": {"def": "藍圖、計畫、製成藍圖、擬訂計畫", "ipa": "/ˈbluːprɪnt/", "trans": "blueprints", "col": "design blueprint", "ex": "This is a blueprint for our future cooperation.", "pos": "n./v."},
    "bluff": {"def": "虛張聲勢、懸崖、直率的、陡峭的、嚇唬、欺騙", "ipa": "/blʌf/", "trans": "bluffing", "col": "call someone's bluff", "ex": "He was just bluffing; he didn't have a gun.", "pos": "n./adj./v."},
    "blunder": {"def": "大錯、過失、犯大錯、跌跌撞撞地走", "ipa": "/ˈblʌndə/", "trans": "blundered", "col": "make a blunder", "ex": "I made a terrible blunder.", "pos": "n./v."},
    "blunt": {"def": "鈍的、直率的、使變鈍、減弱、鈍角", "ipa": "/blʌnt/", "trans": "bluntly, bluntness", "col": "blunt object, blunt pencil", "ex": "The knife is quite blunt.", "pos": "adj./v./n."},
    "blur": {"def": "模糊（不清）、模糊的東西、使模糊、弄髒", "ipa": "/blɜː/", "trans": "blurred, blurry", "col": "blurred vision", "ex": "His eyes were blurred with tears.", "pos": "n./v."},
    "blush": {"def": "臉紅、羞愧、臉紅、變紅", "ipa": "/blʌʃ/", "trans": "blushing", "col": "blush for/at", "ex": "She blushed when he complimented her.", "pos": "n./v."},
    "board": {"def": "板、董事會、伙食、甲板、登上、提供伙食", "ipa": "/bɔːd/", "trans": "boarding", "col": "bulletin board, board of directors, on board", "ex": "The board of directors is meeting today.", "pos": "n./v."},
    "boast": {"def": "自誇、以有...而自豪、吹牛、自滿的言語", "ipa": "/bəʊst/", "trans": "boastful", "col": "boast of/about", "ex": "He was boasting about his success.", "pos": "v./n."},
    "boat": {"def": "小船、艇、划船、乘船", "ipa": "/bəʊt/", "trans": "boating", "col": "life boat, row a boat, in the same boat", "ex": "We went for a boat ride on the lake.", "pos": "n./v."},
    "body": {"def": "身體、主體、大量、屍體、賦予形體", "ipa": "/ˈbɒdi/", "trans": "bodily", "col": "body language, dead body, heavenly body", "ex": "The human body is complex.", "pos": "n./v."},
    "bodyguard": {"def": "保鏢、護衛者", "ipa": "/ˈbɒdiɡɑːd/", "trans": "bodyguards", "col": "personal bodyguard", "ex": "The president is always accompanied by bodyguards.", "pos": "n."},
    "bog": {"def": "沼澤、泥塘、困住", "ipa": "/bɒɡ/", "trans": "boggy", "col": "get bogged down", "ex": "The car got bogged down in the mud.", "pos": "n./v."},
    "boil": {"def": "沸騰、煮沸、怒火中燒、沸點、癤子", "ipa": "/bɔɪl/", "trans": "boiler, boiled", "col": "hard-boiled, boil down to", "ex": "Water boils at 100 degrees Celsius.", "pos": "v./n."},
    "bold": {"def": "大膽的、勇敢的、黑體的、厚顏無恥的", "ipa": "/bəʊld/", "trans": "boldly, boldness", "col": "bold move, bold type", "ex": "He made a bold decision.", "pos": "adj."},
    "bolt": {"def": "螺栓、閃電、逃跑、鎖上、狼吞虎咽", "ipa": "/bəʊlt/", "trans": "bolted", "col": "thunder bolt, nut and bolt", "ex": "Don't forget to bolt the door.", "pos": "n./v."},
    "bomb": {"def": "炸彈、慘敗、投彈於、轟炸、慘敗", "ipa": "/bɒm/", "trans": "bomber, bombing", "col": "atomic bomb, time bomb", "ex": "The bomb exploded at midnight.", "pos": "n./v."},
    "bond": {"def": "聯結、債券、契約、束縛、粘合、結合", "ipa": "/bɒnd/", "trans": "bonding", "col": "family bond, junk bond, in bond", "ex": "There is a strong bond between the two brothers.", "pos": "n./v."},
    "bone": {"def": "骨頭、骨骼、挑出骨頭、苦幹", "ipa": "/bəʊn/", "trans": "bony", "col": "bone dry, make no bones about, jaw bone", "ex": "The x-ray showed that he had broken a bone.", "pos": "n./v."},
}

with open("batch_l3_p5.json", "w", encoding="utf-8") as f:
    json.dump(L3_PART5, f, ensure_ascii=False, indent=2)
