import json

# Level 6 Part 16: (Authorize - Awning)
L6_PART16 = {
    "authorize": {"def": "授權、委託、認可、(法)批准其行動、授權的人 (或物)、授權地 (授權)", "ipa": "/ˈɔːθəraɪz/", "trans": "authorization, authorized", "col": "authorized dealer, fully authorize", "ex": "The director has authorized the new project.", "pos": "v./n./adv."},
    "authorized": {"def": "經過授權的、認可的", "ipa": "/ˈɔːθəraɪzd/", "trans": "authorize (動詞/名詞/副詞), authorization", "col": "authorized personnel only", "ex": "Authorized personnel only in this area.", "pos": "adj."},
    "authorship": {"def": "作者身份、著述、來源", "ipa": "/ˈɔːθəʃɪp/", "trans": "author", "col": "doubtful authorship", "ex": "The authorship of the poem is still in doubt.", "pos": "n."},
    "autarchy/autarky": {"def": "獨裁、自給自足", "ipa": "/ˈɔːtɑːki/", "trans": "self-sufficiency", "col": "economic autarky", "ex": "The government is trying to achieve economic autarky.", "pos": "n."},
    "autism": {"def": "自閉症、孤獨症", "ipa": "/ˈɔːtɪzəm/", "trans": "autistic", "col": "suffer from autism", "ex": "Children with autism may have difficulty communicating.", "pos": "n."},
    "autistic": {"def": "自閉的、自閉症患者、自閉地 (自閉)", "ipa": "/ɔːˈtɪstɪk/", "trans": "autism (名詞)", "col": "autistic spectrum", "ex": "He is on the autistic spectrum.", "pos": "adj./n./adv."},
    "autobiographer": {"def": "自傳作者", "ipa": "/ˌɔːtəbaɪˈɒɡrəfə/", "trans": "autobiography", "col": "noted autobiographer", "ex": "He is a noted autobiographer who wrote about his childhood.", "pos": "n."},
    "autobiographic/autobiographical": {"def": "自傳的、自傳體的", "ipa": "/ˌɔːtəˌbaɪəˈɡræfɪkl/", "trans": "autobiography", "col": "autobiographical novel", "ex": "The book is largely autobiographical.", "pos": "adj."},
    "autobiography": {"def": "自傳、自傳文學", "ipa": "/ˌɔːtəbaɪˈɒɡrəfi/", "trans": "autobiographer", "col": "write an autobiography", "ex": "He published his autobiography last year.", "pos": "n."},
    "autocracy": {"def": "獨裁政治、專制制度、獨裁國家", "ipa": "/ɔːˈtɒkrəsi/", "trans": "autocrat, autocratic", "col": "absolute autocracy", "ex": "The country was ruled by an absolute autocracy.", "pos": "n."},
    "autocrat": {"def": "獨裁者、專制者", "ipa": "/ˈɔːtəkræt/", "trans": "autocracy, autocratic", "col": "benevolent autocrat", "ex": "He was a benevolent autocrat who cared for his people.", "pos": "n."},
    "autocratic": {"def": "獨裁的、專制的、專橫的", "ipa": "/ˌɔːtəˈkrætɪk/", "trans": "autocrat (名詞), autocracy", "col": "autocratic rule", "ex": "The company has an autocratic management style.", "pos": "adj."},
    "autograph": {"def": "親筆簽名、親筆、親筆簽名於、親筆的、簽名的地 (簽名)", "ipa": "/ˈɔːtəɡrɑːf/", "trans": "autographs", "col": "autograph hunter, ask for an autograph", "ex": "Can I have your autograph, please?", "pos": "n./v./adj./adv."},
    "automated": {"def": "自動化的", "ipa": "/ˈɔːtəmeɪtɪd/", "trans": "automate, automation", "col": "fully automated", "ex": "The assembly line is fully automated.", "pos": "adj."},
    "automatic": {"def": "自動的、無意識的、自動機械、自動步槍、自動地 (自動)", "ipa": "/ˌɔːtəˈmætɪk/", "trans": "automatically, automation", "col": "automatic transmission, automatic door", "ex": "The door opens automatically.", "pos": "adj./n./adv."},
    "automatically": {"def": "自動地、無意識地", "ipa": "/ˌɔːtəˈmætɪkli/", "trans": "automatic (形容詞/名詞/副詞), automation", "col": "renewed automatically", "ex": "The subscription is renewed automatically each year.", "pos": "adv."},
    "automaton": {"def": "自動機器、機器人、機械般行動的人 (單數)", "ipa": "/ɔːˈtɒmətən/", "trans": "automata/automatons (複數)", "col": "human automaton", "ex": "He worked like a human automaton.", "pos": "n."},
    "automobile": {"def": "汽車、汽車的、開汽車、汽車的人物、開車地 (汽車)", "ipa": "/ˈɔːtəməbiːl/", "trans": "car", "col": "automobile industry, automobile parts", "ex": "The automobile industry is a major part of the economy.", "pos": "n./adj./v./adv."},
    "autonomy": {"def": "自主權、自治、自治區", "ipa": "/ɔːˈtɒnəmi/", "trans": "autonomous", "col": "greater autonomy, local autonomy", "ex": "The region is seeking greater autonomy.", "pos": "n."},
    "autonomous": {"def": "自主的、自治的、獨立的", "ipa": "/ɔːˈtɒnəməs/", "trans": "autonomy (名詞)", "col": "autonomous region", "ex": "The province became an autonomous region in 1955.", "pos": "adj."},
    "autopsy": {"def": "驗屍、屍體解剖、實地調查、驗屍、解剖地 (驗屍)", "ipa": "/ˈɔːtɒpsi/", "trans": "post-mortem", "col": "perform an autopsy", "ex": "An autopsy was performed to determine the cause of death.", "pos": "n./v./adv."},
    "autumn": {"def": "秋天、秋季、成熟期、秋天的、成熟的、成熟期的人 (或物) (秋天)", "ipa": "/ˈɔːtəm/", "trans": "fall", "col": "golden autumn, in the autumn", "ex": "In the autumn, the leaves turn brown and fall.", "pos": "n./adj./adv."},
    "auxiliary": {"def": "輔助的、附助的、(語)助動詞、助手、附件", "ipa": "/ɔːɡˈzɪliəri/", "trans": "supporting", "col": "auxiliary staff, auxiliary power", "ex": "The hospital provides auxiliary services to the community.", "pos": "adj./n."},
    "avail": {"def": "有用、有利、利益、效用、可用的人 (或物)、有利地 (有用)", "ipa": "/əˈveɪl/", "trans": "available", "col": "to little avail, of no avail", "ex": "All our efforts were to no avail.", "pos": "v./n./adv."},
    "availability": {"def": "可用性、有效性、可得性", "ipa": "/əˌveɪləˈbɪləti/", "trans": "available (形容詞/名詞/副詞)", "col": "room availability, limited availability", "ex": "Please check the room availability before booking.", "pos": "n."},
    "available": {"def": "可用的、有效的、可得的、空閒的人、可用地 (可用)", "ipa": "/əˈveɪləbl/", "trans": "availability, avail (動詞/名詞/副詞)", "col": "readily available, not available", "ex": "Is the information available to the public?", "pos": "adj./n./adv."},
    "avalanche": {"def": "雪崩、崩坍、大批出現的人 (或事)、雪崩般崩下、雪崩般地 (雪崩)", "ipa": "/ˈævəlɑːnʃ/", "trans": "landslide", "col": "triggered an avalanche", "ex": "The mountain was closed due to the risk of an avalanche.", "pos": "n./v./adv."},
    "avenge": {"def": "報復、報仇、替...復仇", "ipa": "/əˈvendʒ/", "trans": "vengeance", "col": "avenge a death", "ex": "He vowed to avenge the death of his brother.", "pos": "v."},
    "avenue": {"def": "林蔭大道、大街、途徑、管道的人、管道地 (管道)", "ipa": "/ˈævənjuː/", "trans": "avenues", "col": "Fifth Avenue, explore all avenues", "ex": "We need to explore all legal avenues.", "pos": "n./adv."},
    "aver": {"def": "斷言、聲稱、証實", "ipa": "/əˈvɜː/", "trans": "assert", "col": "aver innocence", "ex": "She continued to aver that she was innocent.", "pos": "v."},
    "average": {"def": "平均數、平均的、一般的、平均分攤、平均的人物、平均地 (平均)", "ipa": "/ˈævərɪdʒ/", "trans": "averaging", "col": "above average, on average, average out", "ex": "The average age of the students is 20.", "pos": "n./adj./v./adv."},
    "averse": {"def": "反感的、不願意的、背向的", "ipa": "/əˈvɜːs/", "trans": "aversion", "col": "averse to risk", "ex": "He is not averse to a little hard work.", "pos": "adj."},
    "aversion": {"def": "反感、厭惡、討厭的人 (或事)", "ipa": "/əˈvɜːʃn/", "trans": "averse (形容詞)", "col": "strong aversion", "ex": "She has a strong aversion to snakes.", "pos": "n."},
    "avert": {"def": "避開、轉開、防止、避免", "ipa": "/əˈvɜːt/", "trans": "avoid", "col": "avert disaster", "ex": "The government is trying to avert a major disaster.", "pos": "v."},
    "aviation": {"def": "航空、飛行、航空器", "ipa": "/ˌeɪviˈeɪʃn/", "trans": "aviator", "col": "civil aviation, aviation industry", "ex": "He has a lifelong interest in aviation.", "pos": "n."},
    "aviator": {"def": "飛行員、飛行家", "ipa": "/ˈeɪvieɪtə/", "trans": "pilot", "col": "intrepid aviator", "ex": "The intrepid aviators were celebrated for their historic flight.", "pos": "n."},
    "avid": {"def": "渴求的、熱心的、貪婪的", "ipa": "/ˈævɪd/", "trans": "avidly", "col": "avid reader", "ex": "He is an avid reader of historical novels.", "pos": "adj."},
    "avidly": {"def": "渴求地、熱心地、貪婪地", "ipa": "/ˈævɪdli/", "trans": "avid (形容詞)", "col": "read avidly", "ex": "The children read the comic avidly.", "pos": "adv."},
    "avocado": {"def": "酪梨、鱷梨", "ipa": "/ˌævəˈkɑːdəʊ/", "trans": "alligator pear", "col": "avocado salad", "ex": "She likes to have avocado on her toast.", "pos": "n."},
    "avoid": {"def": "避免、躲避、撤銷(合約)、撤銷的人物、撤銷地 (避免)", "ipa": "/əˈvɔɪd/", "trans": "avoidance, avoidable", "col": "avoid contact, avoid taxes, avoid problems", "ex": "You should avoid eating too much sugar.", "pos": "v./n./adv."},
    "avoidable": {"def": "可避免的、可撤銷的", "ipa": "/əˈvɔɪdəbl/", "trans": "avoid (動詞/名詞/副詞), avoidance", "col": "avoidable mistake", "ex": "It was an avoidable mistake.", "pos": "adj."},
    "avoidance": {"def": "規避、逃避、撤銷", "ipa": "/əˈvɔɪdns/", "trans": "avoid (動詞/名詞/副詞), avoidable", "col": "tax avoidance", "ex": "The report focuses on tax avoidance by major companies.", "pos": "n."},
    "avow": {"def": "公開宣明、承認、坦承", "ipa": "/əˈvaʊ/", "trans": "avowal", "col": "avow one's faith", "ex": "He was willing to avow his faith openly.", "pos": "v."},
    "avowal": {"def": "公開承認、誓言", "ipa": "/əˈvaʊəl/", "trans": "avow (動詞)", "col": "frank avowal", "ex": "His frank avowal of his feelings was unexpected.", "pos": "n."},
    "avowed": {"def": "公開承認的、公然的", "ipa": "/əˈvaʊd/", "trans": "avow (動詞), avowal", "col": "avowed enemy", "ex": "They are avowed enemies who will never agree.", "pos": "adj."},
    "await": {"def": "等待、等候、期待", "ipa": "/əˈweɪt/", "trans": "waiting for", "col": "eagerly await", "ex": "The fans are eagerly awaiting the release of the new movie.", "pos": "v."},
    "awake": {"def": "醒著的、警覺的、喚醒、覺醒、覺醒的人 (或物)、覺醒地 (醒)", "ipa": "/əˈweɪk/", "trans": "awaking", "col": "wide awake, awake to danger", "ex": "Is the baby awake?", "pos": "adj./v./n./adv."},
    "awaken": {"def": "喚醒、覺醒、激起", "ipa": "/əˈweɪkn/", "trans": "awake (形容詞/動詞/名詞/副詞)", "col": "awaken interest", "ex": "The smell of coffee awakens me in the morning.", "pos": "v."},
    "award": {"def": "獎勵、獎品、判定、授予、授予人物、授予地 (獎)", "ipa": "/əˈwɔːd/", "trans": "awarded", "col": "win an award, Academy Award (奧斯卡獎), award a contract", "ex": "She was given an award for her bravery.", "pos": "n./v./adv."},
    "aware": {"def": "意識到的、知道的、警覺的、知道的人、知道地 (知道)", "ipa": "/əˈweə/", "trans": "awareness", "col": "be aware of, fully aware", "ex": "Were you aware of the problem?", "pos": "adj./n./adv."},
    "awareness": {"def": "意識、覺醒、警覺、意識的人 (或物)、意識地 (意識)", "ipa": "/əˈweənəs/", "trans": "aware (形容詞/名詞/副詞)", "col": "raise awareness, environmental awareness, sense of awareness", "ex": "We need to raise public awareness of environmental issues.", "pos": "n./adv."},
    "away": {"def": "離開、遠離、不斷地、離開的、遠離的、離開的人 (或物) (離開)", "ipa": "/əˈweɪ/", "trans": "far", "col": "straight away, right away, far away", "ex": "Please put your toys away.", "pos": "adv./adj./n."},
    "awe": {"def": "敬畏、畏懼、使敬畏、畏懼地 (敬畏)", "ipa": "/ɔː/", "trans": "awesome, awful", "col": "in awe of, stand in awe", "ex": "We were in awe of the beautiful scenery.", "pos": "n./v./adv."},
    "awesome": {"def": "極好的、令人敬畏的、宏偉的", "ipa": "/ˈɔːsəm/", "trans": "awe (名詞/動詞/副詞), awful", "col": "truly awesome", "ex": "The view from the top was truly awesome.", "pos": "adj."},
    "awful": {"def": "極壞的、糟糕的、可怕的、極其地、糟糕地 (極壞)", "ipa": "/ˈɔːfl/", "trans": "awfully, awesome", "col": "awful smell, awful weather", "ex": "What an awful thing to say!", "pos": "adj./adv."},
    "awfully": {"def": "極其地、糟糕地、非常", "ipa": "/ˈɔːfli/", "trans": "awful (形容詞/副詞), awesome", "col": "awfully sorry", "ex": "I'm awfully sorry for the delay.", "pos": "adv."},
    "awkward": {"def": "尷尬的、笨拙的、棘手的、尷尬地、笨拙地 (尷尬)", "ipa": "/ˈɔːkwəd/", "trans": "awkwardness", "col": "awkward silence, feel awkward, awkward situation", "ex": "There was an awkward silence after he spoke.", "pos": "adj./adv."},
    "awkwardly": {"def": "尷尬地、笨拙地、棘手地", "ipa": "/ˈɔːkwədli/", "trans": "awkward (形容詞/副詞), awkwardness", "col": "walk awkwardly", "ex": "He walked awkwardly because of his injury.", "pos": "adv."},
    "awkwardness": {"def": "尷尬、笨拙、棘手", "ipa": "/ˈɔːkwədnəs/", "trans": "awkward (形容詞/副詞)", "col": "moment of awkwardness", "ex": "The question caused a moment of awkwardness.", "pos": "n."},
    "awl": {"def": "鑽子、尖鑽", "ipa": "/ɔːl/", "trans": "punch", "col": "shoemaker's awl", "ex": "The shoemaker used an awl to make holes in the leather.", "pos": "n."},
    "awning": {"def": "遮陽篷、雨篷、遮陽蓬的人 (或物) (遮陽篷)", "ipa": "/ˈɔːnɪŋ/", "trans": "canopy", "col": "shop awning, waterproof awning", "ex": "We sat under the shop awning to avoid the rain.", "pos": "n./adv."},
}