import json

# Level 6 Part 17: (Awoke - Backbone)
L6_PART17 = {
    "awoke": {"def": "(awake的過去式)、醒來、覺醒", "ipa": "/əˈwəʊk/", "trans": "awake", "col": "awoke from sleep", "ex": "He awoke from a deep sleep.", "pos": "v."},
    "awoken": {"def": "(awake的過去分詞)、醒來、覺醒", "ipa": "/əˈwəʊkn/", "trans": "awake", "col": "been awoken by", "ex": "I was awoken by a loud noise.", "pos": "v."},
    "awry": {"def": "歪斜的、出錯的、歪斜地、出錯地 (出錯)", "ipa": "/əˈraɪ/", "trans": "wrong", "col": "go awry, plans went awry", "ex": "Our plans for the weekend went awry.", "pos": "adj./adv."},
    "axe/ax": {"def": "斧頭、削減、解僱、用斧砍、解僱的人物、被削減地 (斧)", "ipa": "/æks/", "trans": "axes", "col": "battle axe, have an axe to grind (另有目的), get the axe (被解僱)", "ex": "The woodsman used a sharp axe to fell the tree.", "pos": "n./v./adv."},
    "axial": {"def": "軸的、軸線的、中軸的", "ipa": "/ˈæksiəl/", "trans": "axis", "col": "axial skeleton", "ex": "The axial skeleton includes the skull and spine.", "pos": "adj."},
    "axiom": {"def": "公理、格言、原則", "ipa": "/ˈæksiəm/", "trans": "axiomatic", "col": "mathematical axiom", "ex": "It's a mathematical axiom that 1+1=2.", "pos": "n."},
    "axiomatic": {"def": "公理的、自明的、格言的", "ipa": "/ˌæksiəˈmætɪk/", "trans": "axiom (名詞)", "col": "axiomatic truth", "ex": "It is axiomatic that exercise is good for your health.", "pos": "adj."},
    "axis": {"def": "軸、中心線、樞軸、中軸 (單數)", "ipa": "/ˈæksɪs/", "trans": "axes (複數)", "col": "Earth's axis, central axis, X-axis, Y-axis", "ex": "The Earth rotates on its axis.", "pos": "n."},
    "axle": {"def": "輪軸、車軸", "ipa": "/ˈæksl/", "trans": "axles", "col": "rear axle", "ex": "The rear axle of the car was broken.", "pos": "n."},
    "ay/aye": {"def": "是、對、贊成、贊成票、贊成地 (是)", "ipa": "/aɪ/", "trans": "yes", "col": "aye-aye, sir", "ex": "The ayes have it (贊成票佔多數).", "pos": "adv./n."},
    "azalea": {"def": "杜鵑花", "ipa": "/əˈzeɪliə/", "trans": "azaleas", "col": "blooming azalea", "ex": "The garden was filled with blooming azaleas.", "pos": "n."},
    "azure": {"def": "天藍色、青天、天藍色的", "ipa": "/ˈæʒə/", "trans": "sky blue", "col": "azure sky", "ex": "The azure sky was clear and cloudless.", "pos": "n./adj."},
    "babble": {"def": "胡言亂語、咿呀學語、喋喋不休、胡言亂語地 (胡語)", "ipa": "/ˈbæbl/", "trans": "babbling", "col": "babbling brook, babble on", "ex": "The baby began to babble early this morning.", "pos": "v./n./adv."},
    "babbler": {"def": "喋喋不休的人、胡言亂語者", "ipa": "/ˈbæblə/", "trans": "babble (動詞/名詞/副詞)", "col": "known babbler", "ex": "Don't tell him your secrets, he's a known babbler.", "pos": "n."},
    "babe": {"def": "嬰兒、幼小的動物、天真的人、美女、尤物 (美俚)", "ipa": "/beɪb/", "trans": "babes", "col": "babe in the woods (天真的人)", "ex": "What a beautiful babe!", "pos": "n."},
    "baboon": {"def": "狒狒", "ipa": "/bəˈbuːn/", "trans": "baboons", "col": "troop of baboons", "ex": "A troop of baboons crossed the road.", "pos": "n."},
    "baby": {"def": "嬰兒、寶貝、幼稚的人、最年幼的、像嬰兒般的、嬌養成的人物 (嬰兒)", "ipa": "/ˈbeɪbi/", "trans": "babies", "col": "baby boom, baby shower, baby sit", "ex": "She has a six-month-old baby.", "pos": "n./adj./v./adv."},
    "babyish": {"def": "嬰兒般的、幼稚的", "ipa": "/ˈbeɪbiɪʃ/", "trans": "baby (名詞/形容詞/動詞/副詞)", "col": "babyish behavior", "ex": "His behavior was a bit babyish for his age.", "pos": "adj."},
    "babysit": {"def": "當臨時保姆、照顧嬰兒", "ipa": "/ˈbeɪbisɪt/", "trans": "babysitter, babysitting", "col": "babysit for a neighbor", "ex": "I'm going to babysit for my neighbor tonight.", "pos": "v."},
    "babysitter": {"def": "臨時保姆", "ipa": "/ˈbeɪbisɪtə/", "trans": "babysit (動詞)", "col": "reliable babysitter", "ex": "We need a reliable babysitter for Friday night.", "pos": "n."},
    "baccalaureate": {"def": "學士學位、畢業預備考試", "ipa": "/ˌbækəˈlɔːriət/", "trans": "degree", "col": "International Baccalaureate (IB)", "ex": "She is studying for the International Baccalaureate.", "pos": "n."},
    "baccarat": {"def": "百家樂 (紙牌遊戲)", "ipa": "/ˈbækərɑː/", "trans": "card game", "col": "play baccarat", "ex": "Baccarat is a popular game in casinos.", "pos": "n."},
    "bacchanal": {"def": "酒神節、縱酒狂歡、酒神信徒的、狂歡的", "ipa": "/ˈbækənl/", "trans": "revelry", "col": "bacchanal party", "ex": "The party turned into a wild bacchanal.", "pos": "n./adj."},
    "bachelor": {"def": "單身漢、學士、單身的、單身地 (單身漢)", "ipa": "/ˈbætʃələ/", "trans": "bachelors", "col": "eligible bachelor, Bachelor of Arts (BA), bachelor party", "ex": "He remained a bachelor all his life.", "pos": "n./adj./adv."},
    "bacillus": {"def": "桿菌、細菌 (單數)", "ipa": "/bəˈsɪləs/", "trans": "bacilli (複數)", "col": "tuberculosis bacillus", "ex": "The disease is caused by a specific bacillus.", "pos": "n."},
    "back": {"def": "背部、後面、支持、後退、後面的、過去的、後退地 (後)", "ipa": "/bæk/", "trans": "backing", "col": "back and forth, back down, back up, behind one's back", "ex": "Turn your back and count to ten.", "pos": "n./v./adj./adv."},
    "backache": {"def": "背痛、腰痛", "ipa": "/ˈbækeɪk/", "trans": "back pain", "col": "suffer from backache", "ex": "Sitting at a desk all day gives me a backache.", "pos": "n."},
    "backbiting": {"def": "背後誹謗、背後中傷", "ipa": "/ˈbækbɪtɪŋ/", "trans": "slander", "col": "stop backbiting", "ex": "I am tired of her constant backbiting.", "pos": "n."},
    "backbone": {"def": "脊椎、中樞、支柱、毅力、中樞的、脊椎骨的、堅毅地 (脊椎)", "ipa": "/ˈbækbəʊn/", "trans": "spine", "col": "economic backbone, have a backbone", "ex": "Farming is the economic backbone of this region.", "pos": "n./adj./adv."},
}