import json

# Level 6 Part 9: (Apathy - Apprise)
L6_PART9 = {
    "apathy": {"def": "冷淡、無動於衷、缺乏興趣", "ipa": "/ˈæpəθi/", "trans": "apathetic", "col": "voter apathy, public apathy", "ex": "There is growing voter apathy in the country.", "pos": "n."},
    "ape": {"def": "類人猿、模仿者、模仿、猴子的、愚蠢的、模仿地 (猿)", "ipa": "/eɪp/", "trans": "apes", "col": "great ape, anthropoid ape", "ex": "Chimpanzees are a type of great ape.", "pos": "n./v./adj./adv."},
    "apex": {"def": "頂點、最高點、尖端", "ipa": "/ˈeɪpeks/", "trans": "apexes/apices", "col": "apex of one's career", "ex": "She is currently at the apex of her career.", "pos": "n."},
    "aphid/aphis": {"def": "蚜蟲 (單數)", "ipa": "/ˈeɪfɪd/", "trans": "aphids (複數)", "col": "green aphid", "ex": "Aphids can damage many types of plants.", "pos": "n."},
    "aphorism": {"def": "格言、警句", "ipa": "/ˈæfərɪzəm/", "trans": "aphoristic", "col": "ancient aphorism", "ex": "He is fond of quoting ancient aphorisms.", "pos": "n."},
    "apiary": {"def": "養蜂場", "ipa": "/ˈeɪpiəri/", "trans": "beekeeping", "col": "scientific apiary", "ex": "He works in a large scientific apiary.", "pos": "n."},
    "apical": {"def": "尖端的、頂端的、舌尖音", "ipa": "/ˈæpɪkl/", "trans": "apex", "col": "apical dominance", "ex": "The apical part of the plant grows fastest.", "pos": "adj."},
    "apiece": {"def": "每個、每人、各個、每個地 (每個)", "ipa": "/əˈpiːs/", "trans": "each", "col": "ten dollars apiece", "ex": "The apples cost fifty cents apiece.", "pos": "adv./adj."},
    "aplomb": {"def": "沉著、泰然自若、垂直", "ipa": "/əˈplɒm/", "trans": "confidence", "col": "with great aplomb", "ex": "She handled the difficult situation with great aplomb.", "pos": "n."},
    "apocalyptic": {"def": "啟示錄的、天啟的、災難性的", "ipa": "/əˌpɒkəˈlɪptɪk/", "trans": "apocalypse", "col": "apocalyptic vision", "ex": "The move presents an apocalyptic vision of the future.", "pos": "adj."},
    "apocrypha": {"def": "偽經、外典、作者不明的作品", "ipa": "/əˈpɒkrɪfə/", "trans": "apocryphal", "col": "biblical apocrypha", "ex": "The story is included in the biblical apocrypha.", "pos": "n."},
    "apocryphal": {"def": "偽的、作者不明的、假託的", "ipa": "/əˈpɒkrɪfl/", "trans": "apocrypha (名詞)", "col": "apocryphal story", "ex": "The story is probably apocryphal, but it's very interesting.", "pos": "adj."},
    "apogee": {"def": "遠地點、最高點、全盛期", "ipa": "/ˈæpədʒiː/", "trans": "zenith", "col": "apogee of power", "ex": "The Roman Empire was at its apogee in the second century.", "pos": "n."},
    "apologetic": {"def": "道歉的、認錯的、辯護的", "ipa": "/əˌpɒləˈdʒetɪk/", "trans": "apology", "col": "apologetic tone", "ex": "He spoke in an apologetic tone.", "pos": "adj."},
    "apologize": {"def": "道歉、認錯、辯護", "ipa": "/əˈpɒlədʒaɪz/", "trans": "apology", "col": "apologize for", "ex": "I apologize for being late.", "pos": "v."},
    "apology": {"def": "道歉、認錯、辯護、勉強替代物、道歉的人 (或事)、道歉地 (道歉)", "ipa": "/əˈpɒlədʒi/", "trans": "apologize (動詞), apologetic", "col": "sincere apology, letter of apology", "ex": "Please accept my sincere apology.", "pos": "n./v./adv."},
    "apoplectic": {"def": "中風的、(醫)易患中風的、勃然大怒的", "ipa": "/ˌæpəˈplektɪk/", "trans": "apoplexy", "col": "apoplectic with rage", "ex": "He was apoplectic with rage when he heard the news.", "pos": "adj."},
    "apostasy": {"def": "變節、叛教、背叛", "ipa": "/əˈpɒstəsi/", "trans": "apostate", "col": "political apostasy", "ex": "He was accused of political apostasy.", "pos": "n."},
    "apostate": {"def": "變節者、叛教者、變節的、背叛的、變節地", "ipa": "/əˈpɒsteɪt/", "trans": "apostasy (名詞)", "col": "known apostate", "ex": "He is a known apostate of the church.", "pos": "n./adj./adv."},
    "apostle": {"def": "使徒、提倡者、先驅", "ipa": "/əˈpɒsl/", "trans": "apostles", "col": "the Twelve Apostles", "ex": "He was a leading apostle of non-violence.", "pos": "n."},
    "apostolic": {"def": "使徒的、教皇的、傳福音的", "ipa": "/ˌæpəˈstɒlɪk/", "trans": "apostle", "col": "apostolic succession", "ex": "The Pope claims apostolic authority.", "pos": "adj."},
    "apostrophe": {"def": "撇號 ( ' )、(修)呼告、呼語", "ipa": "/əˈpɒstrəfi/", "trans": "punctuation", "col": "omitted apostrophe", "ex": "Don't forget the apostrophe in 'don't'.", "pos": "n."},
    "appal/appall": {"def": "使驚駭、使大為吃驚、使大失所望", "ipa": "/əˈpɔːl/", "trans": "appalling", "col": "appalled by", "ex": "We were appalled by the news of the massacre.", "pos": "v."},
    "appalling": {"def": "令人驚駭的、極壞的、糟糕的", "ipa": "/əˈpɔːlɪŋ/", "trans": "appal (動詞), appalled", "col": "appalling conditions, appalling weather", "ex": "The living conditions were appalling.", "pos": "adj."},
    "appallingly": {"def": "令人驚駭地、極壞地、糟糕地", "ipa": "/əˈpɔːlɪŋli/", "trans": "appalling (形容詞), appal", "col": "appallingly bad", "ex": "The service was appallingly bad.", "pos": "adv."},
    "apparatus": {"def": "設備、儀器、器官、機構 (單數/複數)", "ipa": "/ˌæpəˈreɪtəs/", "trans": "apparatuses (複數)", "col": "scientific apparatus, breathing apparatus", "ex": "The divers use specialized breathing apparatus.", "pos": "n."},
    "apparel": {"def": "衣服、服裝、裝飾、給...穿衣、衣服的人 (或事)、正式地 (衣服)", "ipa": "/əˈpærəl/", "trans": "clothing", "col": "ready-made apparel", "ex": "She sells sports apparel.", "pos": "n./v./adv."},
    "apparent": {"def": "明顯的、顯而易見的、表面上的、明顯的人 (或物)、明顯地 (明顯)", "ipa": "/əˈpærənt/", "trans": "apparently", "col": "apparent success, heir apparent", "ex": "It was apparent that she was lying.", "pos": "adj./n./adv."},
    "apparently": {"def": "顯然地、表面上地、據說", "ipa": "/əˈpærəntli/", "trans": "apparent (形容詞/名詞/副詞)", "col": "apparently true", "ex": "Apparently, the wedding has been cancelled.", "pos": "adv."},
    "apparition": {"def": "幽靈、幻影、特異景象、出現", "ipa": "/ˌæpəˈrɪʃn/", "trans": "ghost", "col": "ghostly apparition", "ex": "The old woman claimed to have seen a ghostly apparition.", "pos": "n."},
    "appeal": {"def": "呼籲、上訴、吸引力、要求、求助、吸引、上訴的人 (或物)、呼籲地、上訴地 (呼籲)", "ipa": "/əˈpiːl/", "trans": "appealing", "col": "make an appeal, appeal to, lose appeal", "ex": "The government made an appeal for help.", "pos": "n./v./adv."},
    "appealing": {"def": "有吸引力的、動人的、呼籲的", "ipa": "/əˈpiːlɪŋ/", "trans": "appeal (名詞/動詞/副詞)", "col": "appealing look", "ex": "She gave him an appealing look.", "pos": "adj."},
    "appear": {"def": "出現、顯出、好像、出版、出現的人 (或物)、出現地 (出現)", "ipa": "/əˈpɪə/", "trans": "appearance", "col": "appear to be, suddenly appear", "ex": "A cat suddenly appeared in the garden.", "pos": "v./n./adv."},
    "appearance": {"def": "出現、外觀、樣子、出版、出現地 (出現)", "ipa": "/əˈpɪərəns/", "trans": "appear (動詞/名詞/副詞)", "col": "keep up appearances, first appearance", "ex": "He is very conscious of his appearance.", "pos": "n./adv."},
    "appease": {"def": "安撫、撫慰、滿足、平息", "ipa": "/əˈpiːz/", "trans": "appeasement", "col": "policy of appeasement", "ex": "The government tried to appease the angry crowds.", "pos": "v."},
    "appeasement": {"def": "安撫、平息、糾紛的調和", "ipa": "/əˈpiːzmənt/", "trans": "appease (動詞)", "col": "bitter appeasement", "ex": "The policy of appeasement failed to prevent the war.", "pos": "n."},
    "appellant": {"def": "上訴人、上訴的", "ipa": "/əˈpelənt/", "trans": "appeal", "col": "unsuccessful appellant", "ex": "The appellant argued that the trial was unfair.", "pos": "n./adj."},
    "appellate": {"def": "上訴的、受理上訴的", "ipa": "/əˈpelət/", "trans": "appeal", "col": "appellate court", "ex": "The case was heard in the appellate court.", "pos": "adj."},
    "appellation": {"def": "名稱、稱呼、(法)上訴", "ipa": "/ˌæpəˈleɪʃn/", "trans": "name", "col": "formal appellation", "ex": "He prefers a more formal appellation.", "pos": "n."},
    "append": {"def": "附加、掛上、蓋章、附加地、正式地 (附加)", "ipa": "/əˈpend/", "trans": "appendix", "col": "append a signature", "ex": "Please append your signature to the document.", "pos": "v./adv."},
    "appendage": {"def": "附屬物、肢、附加地", "ipa": "/əˈpendɪdʒ/", "trans": "append (動詞/副詞)", "col": "useless appendage", "ex": "The organization's latest project is merely an appendage.", "pos": "n."},
    "appendicitis": {"def": "盲腸炎", "ipa": "/əˌpendəˈsaɪtɪs/", "trans": "appendix", "col": "acute appendicitis", "ex": "He had an operation for acute appendicitis.", "pos": "n."},
    "appendix": {"def": "附錄、盲腸 (單數)", "ipa": "/əˈpendɪks/", "trans": "appendices/appendixes (複數)", "col": "illustrated appendix", "ex": "The list of references is in the appendix.", "pos": "n."},
    "appetite": {"def": "食慾、慾望、嗜好", "ipa": "/ˈæpətaɪt/", "trans": "appetizing", "col": "loss of appetite, healthy appetite", "ex": "I have no appetite today.", "pos": "n."},
    "appetizer": {"def": "開胃菜、開胃物", "ipa": "/ˈæpətaɪzə/", "trans": "starter", "col": "delicious appetizer", "ex": "We had some olives as an appetizer.", "pos": "n."},
    "appetizing": {"def": "開胃的、引人想吃的", "ipa": "/ˈæpətaɪzɪŋ/", "trans": "appetite (名詞), appetizer", "col": "appetizing smell", "ex": "The food has a very appetizing smell.", "pos": "adj."},
    "applaud": {"def": "鼓掌、稱讚、贊成", "ipa": "/əˈplɔːd/", "trans": "applause", "col": "applaud a decision", "ex": "We applaud your decision to change the policy.", "pos": "v."},
    "applause": {"def": "鼓掌、喝采、稱讚", "ipa": "/əˈplɔːz/", "trans": "applaud (動詞)", "col": "round of applause", "ex": "The audience gave him a loud round of applause.", "pos": "n."},
    "apple": {"def": "蘋果、蘋果的人 (或物)、蘋果地 (蘋果)", "ipa": "/ˈæpl/", "trans": "apples", "col": "apple pie, apple tree, Big Apple (紐約)", "ex": "An apple a day keeps the doctor away.", "pos": "n./adv."},
    "appliance": {"def": "器具、用具、應用、適用", "ipa": "/əˈplaɪəns/", "trans": "apply", "col": "domestic appliance, electrical appliance", "ex": "The shop sells many kinds of electrical appliances.", "pos": "n."},
    "applicable": {"def": "可應用的、適用的、合適的", "ipa": "/əˈplɪkəbl/", "trans": "apply (動詞/名詞/副詞), application", "col": "universally applicable", "ex": "The rule is not applicable in this case.", "pos": "adj."},
    "applicant": {"def": "申請人、應徵者", "ipa": "/ˈæplɪkənt/", "trans": "apply (動詞/名詞/副詞), application", "col": "job applicant, successful applicant", "ex": "There were over 100 applicants for the job.", "pos": "n."},
    "application": {"def": "申請、應用、用途、勤奮、申請書、應用的人 (或物)、應用地 (應用)", "ipa": "/ˌæplɪˈkeɪʃn/", "trans": "apply (動詞/名詞/副詞), applicant", "col": "job application, application form, mobile application", "ex": "I submitted my application for the scholarship.", "pos": "n./adj./adv."},
    "applicator": {"def": "敷塗器、塗藥器", "ipa": "/ˈæplɪkeɪtə/", "trans": "apply (動詞/名詞/副詞)", "col": "cosmetic applicator", "ex": "Use the applicator to apply the cream evenly.", "pos": "n."},
    "applied": {"def": "應用的、實用的", "ipa": "/əˈplaɪd/", "trans": "apply (動詞/名詞/副詞), application", "col": "applied science, applied mathematics", "ex": "He is studying applied mathematics at the university.", "pos": "adj."},
    "apply": {"def": "應用、申請、適用、塗抹、申請的人 (或物)、申請地 (應用)", "ipa": "/əˈplaɪ/", "trans": "application, applicant", "col": "apply for a job, apply to, apply a rule", "ex": "I'd like to apply for the position.", "pos": "v./n./adv."},
    "appoint": {"def": "任命、委派、約定、指定、約定的人 (或物)、約定地 (約定)", "ipa": "/əˈpɔɪnt/", "trans": "appointment, appointed", "col": "appoint someone as, newly appointed", "ex": "The board decided to appoint him as the new CEO.", "pos": "v./n./adv."},
    "appointed": {"def": "約定的、指定的、受任命的、裝備完善的", "ipa": "/əˈpɔɪntɪd/", "trans": "appoint (動詞/名詞/副詞), appointment", "col": "appointed time", "ex": "We met at the appointed time.", "pos": "adj."},
    "appointment": {"def": "約會、任命、職位、設施、約會地 (約會)", "ipa": "/əˈpɔɪntmənt/", "trans": "appoint (動詞/名詞/副詞), appointed", "col": "make an appointment, by appointment only", "ex": "I have an appointment with the doctor at 10 o'clock.", "pos": "n./adv."},
    "apportion": {"def": "分配、分派、分攤", "ipa": "/əˈpɔːʃn/", "trans": "apportionment", "col": "apportion blame", "ex": "It's difficult to apportion blame in this situation.", "pos": "v."},
    "appurtenant": {"def": "附屬的、從屬的", "ipa": "/əˈpɜːtɪnənt/", "trans": "accessory", "col": "appurtenant rights", "ex": "The rights are appurtenant to the ownership of the land.", "pos": "adj."},
    "apposite": {"def": "適當的、恰當的", "ipa": "/ˈæpəzɪt/", "trans": "appropriate", "col": "apposite remark", "ex": "The quote was very apposite to the situation.", "pos": "adj."},
    "apposition": {"def": "並列、同位語、靠近", "ipa": "/ˌæpəˈzɪʃn/", "trans": "side by side", "col": "noun in apposition", "ex": "The two phrases are in apposition.", "pos": "n."},
    "appraisal": {"def": "評估、估價、評價", "ipa": "/əˈpreɪzl/", "trans": "appraise (動詞)", "col": "performance appraisal, realistic appraisal", "ex": "We need a realistic appraisal of the situation.", "pos": "n."},
    "appraise": {"def": "評估、估價、評價", "ipa": "/əˈpreɪz/", "trans": "appraisal", "col": "appraise property", "ex": "The jeweler appraised the diamond at $10,000.", "pos": "v."},
    "appreciable": {"def": "可察覺的、相當可觀的", "ipa": "/əˈpriːʃəbl/", "trans": "appreciate, appreciation", "col": "appreciable difference", "ex": "There was an appreciable difference in the quality of the two products.", "pos": "adj."},
    "appreciably": {"def": "可察覺地、相當可觀地、明顯地", "ipa": "/əˈpriːʃəbli/", "trans": "appreciable (形容詞), appreciate", "col": "appreciably better", "ex": "The situation has improved appreciably.", "pos": "adv."},
    "appreciate": {"def": "感激、欣賞、體會、增值、感激地、欣賞地 (感激)", "ipa": "/əˈpriːʃieɪt/", "trans": "appreciation, appreciative", "col": "deeply appreciate, highly appreciated", "ex": "I really appreciate your help.", "pos": "v./adv."},
    "appreciation": {"def": "感激、欣賞、鑑賞力、增值、感激地 (感激)", "ipa": "/əˌpriːʃiˈeɪʃn/", "trans": "appreciate (動詞/副詞), appreciative", "col": "token of appreciation, show appreciation", "ex": "Please accept this gift as a token of my appreciation.", "pos": "n./adv."},
    "appreciative": {"def": "感激的、欣賞的、有鑑賞力的", "ipa": "/əˈpriːʃətɪv/", "trans": "appreciate (動詞/副詞), appreciation", "col": "appreciative audience", "ex": "The performers played to an appreciative audience.", "pos": "adj."},
    "apprehend": {"def": "逮捕、理解、擔心、憂慮", "ipa": "/ˌæprɪˈhend/", "trans": "apprehension, apprehensive", "col": "apprehend a suspect", "ex": "The police managed to apprehend the suspect.", "pos": "v."},
    "apprehension": {"def": "擔心、不安、逮捕、理解", "ipa": "/ˌæprɪˈhenʃn/", "trans": "apprehend (動詞), apprehensive", "col": "full of apprehension", "ex": "She was filled with apprehension about the future.", "pos": "n."},
    "apprehensive": {"def": "担心的、不安的、敏悟的", "ipa": "/ˌæprɪˈhensɪv/", "trans": "apprehension (名詞), apprehend", "col": "apprehensive about", "ex": "He is very apprehensive about the upcoming surgery.", "pos": "adj."},
    "apprentice": {"def": "學徒、生手、使當學徒、學徒的、生手的、學徒地 (學徒)", "ipa": "/əˈprentɪs/", "trans": "apprenticeship", "col": "apprentice electrician", "ex": "He works as an apprentice electrician.", "pos": "n./v./adj./adv."},
    "apprenticeship": {"def": "學徒身份、學徒期", "ipa": "/əˈprentɪʃɪp/", "trans": "apprentice (名詞/動詞/形容詞/副詞)", "col": "serve an apprenticeship", "ex": "She served a five-year apprenticeship with a local baker.", "pos": "n."},
    "apprise": {"def": "通知、告知", "ipa": "/əˈpraɪz/", "trans": "inform", "col": "apprise of the situation", "ex": "Please apprise me of any further developments.", "pos": "v."},
}