import json

# Level 6 Part 39: (Blister - Blue)
L6_PART39 = {
    "blister": {"def": "水泡、氣泡、起泡、猛烈抨擊、起泡的人 (或物)、猛烈地 (泡)", "ipa": "/ˈblɪstə/", "trans": "blistering", "col": "blister pack, blood blister", "ex": "The new shoes gave me a blister on my heel.", "pos": "n./v./adv."},
    "blistering": {"def": "猛烈的、極熱的、猛烈的人 (或物) (猛)", "ipa": "/ˈblɪstərɪŋ/", "trans": "blister (名詞/動詞/副詞)", "col": "blistering heat, blistering pace", "ex": "The runner kept a blistering pace during the race.", "pos": "adj./adv."},
    "blithe": {"def": "愉快的、無憂無慮的、輕率的、愉快地 (愉快)", "ipa": "/blaɪð/", "trans": "blithely", "col": "blithe disregard", "ex": "She showed a blithe disregard for the rules.", "pos": "adj./adv."},
    "blithely": {"def": "愉快地、無憂無慮地、輕率地", "ipa": "/ˈblaɪðli/", "trans": "blithe (形容詞/副詞)", "col": "continued blithely", "ex": "He blithely ignored the warnings.", "pos": "adv."},
    "blizzard": {"def": "暴風雪、大雪暴、大批的人 (或物)、暴風雪的人物、暴風雪地 (暴)", "ipa": "/ˈblɪzəd/", "trans": "snowstorm", "col": "crippling blizzard", "ex": "The city was paralyzed by a crippling blizzard.", "pos": "n./adv."},
    "bloat": {"def": "膨脹、使腫脹、發脹的人 (或物)、發脹地 (腫)", "ipa": "/bləʊt/", "trans": "bloated", "col": "bloated stomach, bloated ego", "ex": "The dead body was bloated with water.", "pos": "v./n./adv."},
    "bloated": {"def": "腫脹的、得意忘形的、浮腫的人 (或物)", "ipa": "/ˈbləʊtɪd/", "trans": "bloat (動詞/名詞/副詞)", "col": "bloated bureaucracy", "ex": "He had a bloated stomach after the heavy meal.", "pos": "adj./n."},
    "blob": {"def": "滴、珠、一小片顏色、弄髒、一滴的人 (或物)、一滴地 (滴)", "ipa": "/blɒb/", "trans": "blobs", "col": "blob of paint", "ex": "A blob of paint fell on the carpet.", "pos": "n./v./adv."},
    "bloc": {"def": "集團、陣營、團體、集團的人物、集體地 (集團)", "ipa": "/blɒk/", "trans": "group", "col": "eastern bloc, power bloc, торговый блок (貿易集團)", "ex": "The nations formed a new trading bloc.", "pos": "n./adv."},
    "block": {"def": "塊、障礙、街區、阻礙、封鎖、塊狀的、塊狀地 (塊)", "ipa": "/blɒk/", "trans": "blocking, blockage", "col": "building block, mental block, office block, block out (遮光)", "ex": "The road was blocked by a fallen tree.", "pos": "n./v./adj./adv."},
    "blockade": {"def": "封鎖、障礙物、封鎖的地方、封鎖的人物、封鎖地 (封鎖)", "ipa": "/blɒˈkeɪd/", "trans": "blockades", "col": "naval blockade, lift a blockade", "ex": "The navy imposed a naval blockade on the port.", "pos": "n./v./adv."},
    "blockage": {"def": "阻塞、障礙、封鎖", "ipa": "/ˈblɒkɪdʒ/", "trans": "block (名詞/動詞/副詞)", "col": "drain blockage", "ex": "There is a blockage in the main drain.", "pos": "n."},
    "blockhead": {"def": "笨蛋、木頭人 (單數)", "ipa": "/ˈblɒkhed/", "trans": "blockheads (複數)", "col": "stubborn blockhead", "ex": "Don't be such a stubborn blockhead!", "pos": "n."},
    "blocking": {"def": "阻塞的、阻礙的人 (或物) (阻)", "ipa": "/ˈblɒkɪŋ/", "trans": "block (名詞/動詞/副詞)", "col": "blocking agent", "ex": "The police are blocking the street.", "pos": "adj./adv."},
    "blockish": {"def": "笨拙的、呆頭呆腦的", "ipa": "/ˈblɒkɪʃ/", "trans": "stupid", "col": "blockish behavior", "ex": "He gave a blockish response to the question.", "pos": "adj."},
    "blog": {"def": "部落格、網誌、寫部落格、部落格的人物、部落格地 (網誌)", "ipa": "/blɒɡ/", "trans": "weblog", "col": "update blog, personal blog", "ex": "She writes a blog about her travel experiences.", "pos": "n./v./adv."},
    "blogger": {"def": "部落客、網誌作者", "ipa": "/ˈblɒɡə/", "trans": "blog (名詞/動詞/副詞)", "col": "popular blogger", "ex": "She is a popular blogger with thousands of followers.", "pos": "n."},
    "blogging": {"def": "寫網誌、寫網誌的人 (或物) (誌)", "ipa": "/ˈblɒɡɪŋ/", "trans": "blog (名詞/動詞/副詞)", "col": "fashion blogging", "ex": "Blogging has become a major industry.", "pos": "n./adv."},
    "bloke": {"def": "(英口)傢伙、男人 (單數)", "ipa": "/bləʊk/", "trans": "blokes (複數)", "col": "decent bloke", "ex": "He seems like a decent bloke.", "pos": "n."},
    "blonde/blond": {"def": "金髮的、白皙的、金髮女郎 (單數)、金髮人、金色、金髮地 (金)", "ipa": "/blɒnd/", "trans": "blondes/blonds", "col": "peroxide blonde, strawberry blonde", "ex": "She has long blonde hair.", "pos": "adj./n./adv."},
    "blood": {"def": "血液、生命、出身、傷害、流血、血統、血液的人物、血親地 (血)", "ipa": "/blʌd/", "trans": "bloody, bloodless", "col": "blood pressure, blood test, blood relation, in cold blood", "ex": "The nurse took a sample of his blood.", "pos": "n./v./adj./adv."},
    "bloodcurdling": {"def": "令人毛骨悚然的", "ipa": "/ˈblʌdkɜːdlɪŋ/", "trans": "terrifying", "col": "bloodcurdling scream", "ex": "We heard a bloodcurdling scream in the distance.", "pos": "adj."},
    "bloodhound": {"def": "尋血獵犬、追蹤者 (單數)", "ipa": "/ˈblʌdhaʊnd/", "trans": "bloodhounds (複數)", "col": "detective bloodhound", "ex": "The detective followed the suspect like a bloodhound.", "pos": "n."},
    "bloodless": {"def": "無血的、不流血的、蒼白的、無情的", "ipa": "/ˈblʌdləs/", "trans": "anemic", "col": "bloodless revolution", "ex": "The changes were achieved through a bloodless revolution.", "pos": "adj."},
    "bloodshot": {"def": "(眼睛)充血的", "ipa": "/ˈblʌdʃɒt/", "trans": "red", "col": "bloodshot eyes", "ex": "His eyes were bloodshot from lack of sleep.", "pos": "adj."},
    "bloodstained": {"def": "玷汙血跡的", "ipa": "/ˈblʌdsteɪnd/", "trans": "bloody", "col": "bloodstained knife", "ex": "A bloodstained knife was found at the scene.", "pos": "adj."},
    "bloodstream": {"def": "血流、血液循環系統", "ipa": "/ˈblʌdstriːm/", "trans": "blood", "col": "enter the bloodstream", "ex": "The medicine is quickly absorbed into the bloodstream.", "pos": "n."},
    "bloodthirsty": {"def": "嗜血的、殘忍的", "ipa": "/ˈblʌdθɜːsti/", "trans": "cruel", "col": "bloodthirsty pirates", "ex": "The movie was criticized for its bloodthirsty scenes.", "pos": "adj."},
    "bloody": {"def": "流血的、殘忍的、(英俚口語加重語氣)該死的、血腥地 (血)", "ipa": "/ˈblʌdi/", "trans": "blood (名詞/動詞/形容詞/副詞)", "col": "bloody Mary, bloody hell!", "ex": "He has a bloody nose after the fight.", "pos": "adj./adv."},
    "bloom": {"def": "花、開花、粉末、盛產、繁榮、開花的人物、開花地 (花)", "ipa": "/bluːm/", "trans": "blooming, blossom", "col": "in full bloom, bloom of youth", "ex": "The cherry trees are starting to bloom.", "pos": "n./v./adv."},
    "blooming": {"def": "開花的、繁榮的、(英俚)該地的、盛開的人 (或物) (花)", "ipa": "/ˈbluːmɪŋ/", "trans": "bloom (名詞/動詞/副詞)", "col": "blooming marvelous", "ex": "The roses are blooming in the garden.", "pos": "adj./adv."},
    "blooper": {"def": "(口)大錯、(廣播/影視)出差錯 (單數)", "ipa": "/ˈbluːpə/", "trans": "bloopers (複數)", "col": "hilarious blooper", "ex": "The news shows hilarious bloopers at Christmas.", "pos": "n."},
    "blossom": {"def": "花、開花、興旺、變好的人、興旺地 (花)", "ipa": "/ˈblɒsəm/", "trans": "blossomed", "col": "cherry blossom, in blossom, blossom into (發展成)", "ex": "Their friendship blossomed into love.", "pos": "n./v./adv."},
    "blot": {"def": "污漬、汙點、吸乾、塗掉、污點的人 (或物)、污點地 (汙)", "ipa": "/blɒt/", "trans": "blotted", "col": "blot on the landscape (大煞風景), blot out (掩蓋), ink blot", "ex": "There's an ink blot on your shirt.", "pos": "n./v./adv."},
    "blotch": {"def": "汙點、斑點、長斑點的人 (或物) (斑)", "ipa": "/blɒtʃ/", "trans": "blotchy", "col": "red blotch", "ex": "A red blotch appeared on his skin.", "pos": "n./adv."},
    "blotchy": {"def": "有汙點的、長斑點的", "ipa": "/ˈblɒtʃi/", "trans": "blotch (名詞/副詞)", "col": "blotchy skin", "ex": "His face was blotchy with anger.", "pos": "adj."},
    "blouse": {"def": "女襯衫、短上衣、穿襯衫的人物、穿襯衫地 (襯衫)", "ipa": "/blaʊz/", "trans": "blouses", "col": "silk blouse, white blouse", "ex": "She wore a white silk blouse to the interview.", "pos": "n./adv."},
    "blow": {"def": "吹、毆打、打擊、喘氣、不幸、風、吹的人 (或物)、吹地 (吹)", "ipa": "/bləʊ/", "trans": "blowing, blew, blown", "col": "blow out (吹滅), blow up (爆炸), blow one's own trumpet (自誇), blow a fuse (大發雷霆)", "ex": "A cold wind is blowing from the north.", "pos": "v./n./adv."},
    "blowhard": {"def": "(俚)吹牛角、自負的人 (單數)", "ipa": "/ˈbləʊhɑːd/", "trans": "blowhards (複數)", "col": "arrogant blowhard", "ex": "Don't listen to him, he's just an arrogant blowhead.", "pos": "n."},
    "blowing": {"def": "吹、吹的人 (或物) (吹)", "ipa": "/ˈbləʊɪŋ/", "trans": "blow (動詞/名詞/副詞)", "col": "blowing bubbles", "ex": "The blowing snow made visibility difficult.", "pos": "n./adv."},
    "blown": {"def": "(blow的過去分詞)、吹過的", "ipa": "/bləʊn/", "trans": "blow", "col": "full-blown (盛開的/全發展的)", "ex": "The storm had blown the roof off the barn.", "pos": "v."},
    "blowout": {"def": "爆胎、保險絲燒斷、(俚)盛宴、爆胎的人 (或物)、爆胎地 (爆)", "ipa": "/ˈbləʊaʊt/", "trans": "blowouts", "col": "tire blowout", "ex": "He had a tire blowout on the highway.", "pos": "n./adv."},
    "blowpipe": {"def": "吹管、吹矢、吹箭的人 (或物) (管)", "ipa": "/ˈbləʊpaɪp/", "trans": "blowpipes", "col": "medieval blowpipe", "ex": "The indigenous tribe uses a blowpipe for hunting.", "pos": "n./adv."},
    "blowtorch": {"def": "噴燈 (單數)", "ipa": "/ˈbləʊtɔːtʃ/", "trans": "blowtorches (複數)", "col": "industrial blowtorch", "ex": "The worker used an industrial blowtorch to melt the ice.", "pos": "n."},
    "blubber": {"def": "鯨脂、痛哭、發腫、痛哭的人、痛哭地 (哭)", "ipa": "/ˈblʌbə/", "trans": "blubbering", "col": "uncontrolled blubber", "ex": "He broke into an uncontrolled blubber.", "pos": "n./v./adv."},
    "bludgeon": {"def": "短棍、警棍、用棍痛打、強迫、痛打地 (打)", "ipa": "/ˈblʌdʒən/", "trans": "bludgeoned", "col": "heavy bludgeon", "ex": "He was beaten with a heavy bludgeon.", "pos": "n./v./adv."},
    "blue": {"def": "藍色的、憂鬱的、(俚)色情的、青、蔚藍、使變藍、憂鬱地 (藍)", "ipa": "/bluː/", "trans": "blues", "col": "navy blue, out of the blue (突然), once in a blue moon (罕見), feel blue (鬱悶)", "ex": "The sky is clear and blue.", "pos": "adj./n./v./adv."},
}