import json

# Level 5 Part 8: (Outlet - Rebellion)
L5_PART8 = {
    "outlet": {"def": "出口、出路、商店、電源插座", "ipa": "/ˈaʊtlet/", "trans": "outlets", "col": "retail outlet, emotional outlet", "ex": "Writing provides an emotional outlet for him.", "pos": "n."},
    "pirate": {"def": "海盜、剽竊者、盜版者、海上搶劫、剽竊、盜版、盜版的、海盜的", "ipa": "/ˈpaɪrət/", "trans": "piracy", "col": "pirate radio, software pirate", "ex": "The movie was a pirate copy.", "pos": "n./v./adj."},
    "motive": {"def": "動機、目的、主旨、發動的、運動的、導致運動的、給予動機", "ipa": "/ˈməʊtɪv/", "trans": "motivation, motivate", "col": "ulterior motive, political motive", "ex": "The police are looking for a motive for the crime.", "pos": "n./adj./v."},
    "output": {"def": "產量、輸出、產品、製作之量、產生、輸出、派員", "ipa": "/ˈaʊtpʊt/", "trans": "outputs", "col": "industrial output, power output", "ex": "The factory has increased its industrial output.", "pos": "n./v."},
    "pitcher": {"def": "投手、大口罐、水瓶", "ipa": "/ˈpɪtʃə/", "trans": "pitchers", "col": "starting pitcher", "ex": "He is the starting pitcher for the team.", "pos": "n."},
    "mount": {"def": "山、底殼、乘用馬、登上、爬上、安放、發動、增加", "ipa": "/maʊnt/", "trans": "mountain, mounted", "col": "Mount Everest, mount a challenge", "ex": "They are planning to mount a challenge to the decision.", "pos": "n./v."},
    "productivity": {"def": "生產力、生產率、豐饒", "ipa": "/ˌprɒdʌkˈtɪvəti/", "trans": "productive, produce", "col": "labor productivity", "ex": "The company is trying to improve labor productivity.", "pos": "n."},
    "reassure": {"def": "使放心、使消除疑慮、再保證", "ipa": "/ˌriːəˈʃɔː/", "trans": "reassurance", "col": "reassure someone of something", "ex": "The doctor tried to reassure the patient.", "pos": "v."},
    "ritual": {"def": "儀式、典禮、例行公事、儀式的、依儀式的、老套的", "ipa": "/ˈrɪtʃuəl/", "trans": "ritually", "col": "religious ritual, daily ritual", "ex": "Coffee in the morning is a daily ritual for him.", "pos": "n./adj."},
    "profile": {"def": "側面、輪廓、外形、簡介、描...的輪廓、概述、畫側面像", "ipa": "/ˈprəʊfaɪl/", "trans": "profiles", "col": "keep a low profile, social media profile", "ex": "He has a social media profile on several sites.", "pos": "n./v."},
    "rebellion": {"def": "造反、叛亂、反抗", "ipa": "/rɪˈbeljən/", "trans": "rebel", "col": "armed rebellion", "ex": "The government crushed the armed rebellion.", "pos": "n."},
    "bruise": {"def": "青腫、傷痕、挫傷、(水果等)撞出的傷痕、使挫傷、使受傷", "ipa": "/bruːz/", "trans": "bruised", "col": "bad bruise", "ex": "She has a bad bruise on her arm.", "pos": "n./v."},
    "brutal": {"def": "殘忍的、野蠻的、不講理的", "ipa": "/ˈbruːtl/", "trans": "brutality, brutally", "col": "brutal murder, brutal honesty", "ex": "The crime was committed with brutal violence.", "pos": "adj."},
    "brutality": {"def": "殘酷、野蠻、暴行", "ipa": "/bruːˈtæləti/", "trans": "brutal (形容詞/副詞)", "col": "police brutality", "ex": "There have been allegations of police brutality.", "pos": "n."},
    "bubble": {"def": "氣泡、水泡、泡影、沸騰、冒泡、滔滔不絕、發出氣泡", "ipa": "/ˈbʌbl/", "trans": "bubbles", "col": "soap bubble, financial bubble", "ex": "The child was blowing soap bubbles.", "pos": "n./v."},
    "buck": {"def": "雄鹿、元、雄兔、猛然跳起、反對、抵抗、馬跳、跳躍", "ipa": "/bʌk/", "trans": "bucks", "col": "make a fast buck, pass the buck (推諉)", "ex": "It cost me ten bucks.", "pos": "n./v."},
    "bucket": {"def": "桶、吊桶、一桶之量、裝入桶中、傾盆而下、拼命工作", "ipa": "/ˈbʌkɪt/", "trans": "buckets", "col": "bucket list, rain in buckets", "ex": "It's raining in buckets outside.", "pos": "n./v."},
    "buckle": {"def": "帶扣、扣子、變曲、扣住、扣緊、扭曲、屈服", "ipa": "/ˈbʌkl/", "trans": "buckles", "col": "buckle up", "ex": "Please buckle up before we start the car.", "pos": "n./v."},
    "bud": {"def": "芽、花蕾、初萌、發芽、萌芽、繁榮、像芽般的", "ipa": "/bʌd/", "trans": "buds", "col": "rose bud, nip in the bud (防微杜漸)", "ex": "The trees are already in bud.", "pos": "n./v./adj."},
    "Buddhism": {"def": "佛教", "ipa": "/ˈbʊdɪzəm/", "trans": "Buddhist", "col": "study Buddhism", "ex": "Buddhism is a major religion in Asia.", "pos": "n."},
    "Buddhist": {"def": "佛教徒、佛教的", "ipa": "/ˈbʊdɪst/", "trans": "Buddhism (名詞)", "col": "Buddhist monk", "ex": "He is a devout Buddhist.", "pos": "n./adj."},
    "buddy": {"def": "好朋友、夥伴、發出友好、結為夥伴", "ipa": "/ˈbʌdi/", "trans": "buddies", "col": "best buddy", "ex": "He and I are best buddies.", "pos": "n./v."},
    "budget": {"def": "預算、生活費、一大批、編列預算、安排、廉價的、預算的", "ipa": "/ˈbʌdʒɪt/", "trans": "budgetary", "col": "annual budget, on a budget", "ex": "The family is living on a tight budget.", "pos": "n./v./adj."},
    "buff": {"def": "米色、愛好者、軟皮、米色的、淺黃色的、拋光、增強、淺黃色地", "ipa": "/bʌf/", "trans": "buffs", "col": "movie buff, computer buff", "ex": "He is a real movie buff.", "pos": "n./adj./v./adv."},
    "buffalo": {"def": "水牛、野牛、威嚇、愚弄", "ipa": "/ˈbʌfələʊ/", "trans": "buffaloes (複數)", "col": "water buffalo", "ex": "We saw a herd of buffalo in the field.", "pos": "n./v."},
    "buffer": {"def": "緩衝器、減震器、中間人、緩衝、保護、減震、緩衝的", "ipa": "/ˈbʌfə/", "trans": "buffers", "col": "buffer zone", "ex": "A neutral country can act as a buffer between two powers.", "pos": "n./v./adj."},
    "buffet": {"def": "自助餐、餐車、打擊、打擊、搏鬥、連續打擊", "ipa": "/ˈbʌfeɪ/ (n.) /ˈbʌfɪt/ (v./n.打擊)", "trans": "buffets", "col": "buffet lunch, breakfast buffet", "ex": "We enjoyed a lavish breakfast buffet.", "pos": "n./v."},
    "bug": {"def": "蟲、病菌、竊聽器、故障、裝竊聽器、煩擾、竊聽、有蟲的", "ipa": "/bʌɡ/", "trans": "bugs, buggy", "col": "bed bug, computer bug", "ex": "There's a bug in the software.", "pos": "n./v./adj."},
    "build": {"def": "體格、體型、構造、建築、建造、建立、居住 (建築)", "ipa": "/bɪld/", "trans": "builder, building", "col": "slender build, build up", "ex": "He has a slender build.", "pos": "n./v."},
    "bulb": {"def": "電燈泡、球莖、球狀物", "ipa": "/bʌlb/", "trans": "bulbs", "col": "light bulb, tulip bulb", "ex": "I need to change the light bulb.", "pos": "n."},
    "bulk": {"def": "體積、大半、散裝貨、變得大、顯得重要、使擴大、散裝的、大宗的", "ipa": "/bʌlk/", "trans": "bulky", "col": "in bulk, bulk buy", "ex": "The bulk of the population lives in the cities.", "pos": "n./v./adj."},
    "bulky": {"def": "龐大的、笨重的", "ipa": "/ˈbʌlki/", "trans": "bulk (名詞/動詞/形容詞)", "col": "bulky parcel", "ex": "It was a very bulky parcel.", "pos": "adj."},
    "bull": {"def": "公牛、雄獸、買方持股者、多頭、強大的、大而重的、談論廢話、使上漲", "ipa": "/bʊl/", "trans": "bullock, bullish", "col": "bull market, bull fighter", "ex": "The bull is a powerful animal.", "pos": "n./adj./v."},
    "bullet": {"def": "子彈、彈丸、公報、告示、投彈、快速前進", "ipa": "/ˈbʊlɪt/", "trans": "bullets", "col": "silver bullet, stray bullet", "ex": "He was injured by a stray bullet.", "pos": "n./v."},
    "bulletin": {"def": "告示、公報、定期刊物、發佈公報、定期通報", "ipa": "/ˈbʊlətɪn/", "trans": "bulletins", "col": "news bulletin, bulletin board", "ex": "I saw the announcement on the bulletin board.", "pos": "n./v."},
    "bully": {"def": "惡棍、流氓、威嚇、以強凌弱、好極了、第一流的、威嚇地、傲慢地", "ipa": "/ˈbʊli/", "trans": "bullied", "col": "school bully", "ex": "Don't be a bully.", "pos": "n./v./adj./adv."},
    "bump": {"def": "撞擊、腫塊、隆起、撞、碰、顛簸而行、碰撞地、突然地", "ipa": "/bʌmp/", "trans": "bumpy", "col": "bump into, speed bump", "ex": "I bumped into an old friend yesterday.", "pos": "n./v./adv."},
    "bumpy": {"def": "顛簸的、崎嶇不平的", "ipa": "/ˈbʌmpi/", "trans": "bump (名詞/動詞/副詞)", "col": "bumpy road, bumpy flight", "ex": "The road was very bumpy.", "pos": "adj."},
    "bunch": {"def": "串、束、群、成串、糾結、成群、擠作一團", "ipa": "/bʌntʃ/", "trans": "bunches", "col": "bunch of flowers, bunch of grapes", "ex": "He gave her a bunch of flowers.", "pos": "n./v."},
    "bundle": {"def": "捆、卷、束、大筆錢、捆、打包、匆忙離開、收集、成捆地", "ipa": "/ˈbʌndl/", "trans": "bundles", "col": "bundle of joy (嬰兒), bundle up", "ex": "She carried a bundle of firewood.", "pos": "n./v./adv."},
    "bungalow": {"def": "平房、小屋", "ipa": "/ˈbʌŋɡələʊ/", "trans": "bungalows", "col": "luxury bungalow", "ex": "They live in a beautiful bungalow near the beach.", "pos": "n."},
    "bungle": {"def": "拙劣的工作、失誤、搞糟、拙劣地做", "ipa": "/ˈbʌŋɡl/", "trans": "bungler, bungling", "col": "bungle the task", "ex": "I'm afraid I've bungled the task.", "pos": "n./v."},
    "buoy": {"def": "浮標、浮筒、救生圈、使浮起、支持、鼓勵", "ipa": "/bɔɪ/", "trans": "buoyant", "col": "buoy up confidence", "ex": "The rescue team threw a buoy to the drowning man.", "pos": "n./v."},
    "buoyant": {"def": "有浮力的、能浮起的、慶快的、上漲的", "ipa": "/ˈbɔɪənt/", "trans": "buoy (名詞/動詞), buoyancy", "col": "buoyant economy", "ex": "The economy remains buoyant despite the global crisis.", "pos": "adj."},
    "burden": {"def": "負擔、重荷、主題、裝載、使負擔、煩擾、重擔地", "ipa": "/ˈbɜːdn/", "trans": "burdensome", "col": "financial burden, heavy burden", "ex": "His debts are a heavy burden on him.", "pos": "n./v./adv."},
    "bureau": {"def": "局、辦公署、抽屜、寫字台", "ipa": "/ˈbjʊərəʊ/", "trans": "bureaus, bureaux", "col": "FBI (Federal Bureau of Investigation), travel bureau", "ex": "I went to the travel bureau for some information.", "pos": "n."},
    "bureaucracy": {"def": "官僚主義、官僚、行政機關", "ipa": "/bjʊəˈrɒkrəsi/", "trans": "bureaucratic, bureaucrat", "col": "excessive bureaucracy", "ex": "The project was delayed by excessive bureaucracy.", "pos": "n."},
    "bureaucrat": {"def": "官僚、公務員", "ipa": "/ˈbjʊərəkræt/", "trans": "bureaucracy (名詞), bureaucratic", "col": "government bureaucrat", "ex": "He is a senior government bureaucrat.", "pos": "n."},
    "bureaucratic": {"def": "官僚的、繁瑣的", "ipa": "/ˌbjʊərəˈkrætɪk/", "trans": "bureaucracy (名詞), bureaucrat", "col": "bureaucratic procedures", "ex": "Applying for the visa was a long and bureaucratic process.", "adj": "adj."},
    "burglar": {"def": "竊賊、夜賊", "ipa": "/ˈbɜːɡlə/", "trans": "burglary", "col": "cat burglar", "ex": "The burglar broke into the house while they were asleep.", "pos": "n."},
    "burglary": {"def": "竊盜(罪)、闖空門", "ipa": "/ˈbɜːɡləri/", "trans": "burglar (名詞)", "col": "commit burglary", "ex": "He was charged with burglary.", "pos": "n."},
    "burial": {"def": "埋葬、葬禮、墳墓、埋葬的", "ipa": "/ˈberiəl/", "trans": "bury", "col": "burial ground", "ex": "The ceremony took place at the local burial ground.", "pos": "n./adj."},
    "burn": {"def": "燃燒、燙傷、曬黑、燃燒、燒毀、發光、曬黑、灼燒", "ipa": "/bɜːn/", "trans": "burned, burnt, burning", "col": "heart burn, burn out, burn up", "ex": "Don't burn the toast.", "pos": "n./v."},
    "burnout": {"def": "燒毀、倦怠、精脾力竭", "ipa": "/ˈbɜːnaʊt/", "trans": "burn (名詞/動詞)", "col": "suffer from burnout", "ex": "He is suffering from burnout after years of hard work.", "pos": "n."},
    "burst": {"def": "爆炸、破裂、衝刺、爆發、炸開、衝、爆發、爆裂的", "ipa": "/bɜːst/", "trans": "bursting", "col": "burst into tears, burst out laughing", "ex": "The balloon burst when he touched it.", "pos": "n./v./adj."},
    "bury": {"def": "埋葬、掩埋、隱藏、忘掉", "ipa": "/ˈberi/", "trans": "burial", "col": "bury the hatchet (和解)", "ex": "The dog buried its bone in the garden.", "pos": "v."},
}

with open("batch_l5_p8.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART8, f, ensure_ascii=False, indent=2)
