import json

# Level 6 Part 10: (Approach - Archery)
L6_PART10 = {
    "approach": {"def": "接近、方法、路徑、靠近、處理、接近的、靠近的、接近地 (接近)", "ipa": "/əˈprəʊtʃ/", "trans": "approachable", "col": "new approach, alternative approach, difficult to approach", "ex": "The summer is approaching.", "pos": "n./v./adj./adv."},
    "approachable": {"def": "可接近的、友好的、平易近人的", "ipa": "/əˈprəʊtʃəbl/", "trans": "approach (名詞/動詞/副詞/形容詞)", "col": "approachable boss", "ex": "He is a very friendly and approachable person.", "pos": "adj."},
    "approbation": {"def": "認可、贊成、稱讚", "ipa": "/ˌæprəˈbeɪʃn/", "trans": "approval", "col": "official approbation", "ex": "The plan was greeted with official approbation.", "pos": "n."},
    "approprate/appropriate": {"def": "適當的、撥出(款項)、挪用、佔用、撥給的人 (或物)、適當地 (適當)", "ipa": "/əˈprəʊpriət/ (adj.) /əˈprəʊprieɪt/ (v.)", "trans": "appropriation, appropriately", "col": "appropriate background, appropriate action, appropriate funds", "ex": "Is this film appropriate for children?", "pos": "adj./v./n./adv."},
    "appropriately": {"def": "適當地、恰當地", "ipa": "/əˈprəʊpriətli/", "trans": "appropriate (形容詞/動詞/名詞/副詞), appropriation", "col": "dress appropriately", "ex": "You should dress appropriately for the interview.", "pos": "adv."},
    "appropriation": {"def": "撥款、挪用、佔用、適當", "ipa": "/əˌprəʊpriˈeɪʃn/", "trans": "appropriate (形容詞/動詞/名詞/副詞), appropriately", "col": "cultural appropriation, government appropriation", "ex": "The project received a government appropriation of $1 million.", "pos": "n."},
    "approval": {"def": "贊成、認可、批准、贊成的、認可的、贊成地 (贊成)", "ipa": "/əˈpruːvl/", "trans": "approve (動詞/副詞), approved", "col": "gain approval, official approval, seal of approval", "ex": "The plan has received official approval.", "pos": "n./adj./adv."},
    "approve": {"def": "贊成、批准、滿意、贊成的人 (或物)、贊成地 (贊成)", "ipa": "/əˈpruːv/", "trans": "approval, approved", "col": "approve of, strongly approve", "ex": "I don't approve of smoking.", "pos": "v./n./adv."},
    "approved": {"def": "經過批准的、認可的、公認的", "ipa": "/əˈpruːvd/", "trans": "approve (動詞/副詞/名詞), approval", "col": "approved method, approved schools", "ex": "Is this an approved method of treatment?", "pos": "adj."},
    "approximate": {"def": "近似的、大約的、最近的、接近、約計、接近的人 (或物)、接近地 (近似)", "ipa": "/əˈprɒksɪmət/ (adj.) /əˈprɒksɪmeɪt/ (v.)", "trans": "approximately, approximation", "col": "approximate cost, approximate value", "ex": "The approximate cost will be $500.", "pos": "adj./v./n./adv."},
    "approximately": {"def": "大約地、近乎、幾乎", "ipa": "/əˈprɒksɪmətli/", "trans": "approximate (形容詞/動詞/名詞/副詞), approximation", "col": "approximately equal", "ex": "The journey takes approximately two hours.", "pos": "adv."},
    "approximation": {"def": "接近、近似值、粗略估算", "ipa": "/əˌprɒksɪˈmeɪʃn/", "trans": "approximate (形容詞/動詞/名詞/副詞), approximately", "col": "rough approximation", "ex": "The figure is only a rough approximation.", "pos": "n."},
    "appurtenance": {"def": "附屬物、從屬權", "ipa": "/əˈpɜːtɪnəns/", "trans": "adjunct", "col": "modern appurtenances", "ex": "The house is sold with all its modern appurtenances.", "pos": "n."},
    "apricot": {"def": "杏子、杏仁、杏色的", "ipa": "/ˈeɪprɪkɒt/", "trans": "apricots", "col": "apricot jam", "ex": "She made some delicious apricot jam.", "pos": "n./adj."},
    "April": {"def": "四月", "ipa": "/ˈeɪprəl/", "trans": "Aprils", "col": "April Fool's Day", "ex": "April is the fourth month of the year.", "pos": "n."},
    "apron": {"def": "圍裙、停機坪、(舞臺)前部、穿圍裙於、台口地 (圍裙)", "ipa": "/ˈeɪprən/", "trans": "aprons", "col": "cookery apron, airfield apron", "ex": "She put on an apron and started cooking.", "pos": "n./v./adv."},
    "apropos": {"def": "關於、至於、恰好、合時宜的、適當的、恰好地、適當地 (恰好)", "ipa": "/ˌæprəˈpəʊ/", "trans": "relevant", "col": "apropos of nothing (突如其來地), apropos to", "ex": "He made some very apropos remarks.", "pos": "prep./adj./adv."},
    "apse": {"def": "半圓形的壁龕、(建)後殿", "ipa": "/æps/", "trans": "apsis", "col": "church apse", "ex": "The altar is located in the church apse.", "pos": "n."},
    "apt": {"def": "恰當的、聰明的、易於...的、聰明的人、適當地 (恰當)", "ipa": "/æpt/", "trans": "aptly, aptitude", "col": "apt description, apt to change", "ex": "He is a very apt pupil.", "pos": "adj./n./adv."},
    "aptitude": {"def": "天資、資質、才能、傾向", "ipa": "/ˈæptɪtjuːd/", "trans": "apt (形容詞/名詞/副詞)", "col": "scholastic aptitude, natural aptitude", "ex": "He has a natural aptitude for music.", "pos": "n."},
    "aptly": {"def": "恰當地、適當地、聰明地", "ipa": "/ˈæptli/", "trans": "apt (形容詞/名詞/副詞), aptitude", "col": "aptly named", "ex": "The book is aptly named.", "pos": "adv."},
    "aquamarine": {"def": "海藍寶石、青綠色、海藍色的", "ipa": "/ˌækwəməˈriːn/", "trans": "blue-green", "col": "aquamarine eyes", "ex": "She has beautiful aquamarine eyes.", "pos": "n./adj."},
    "aquarium": {"def": "水族館、養魚缸 (單數)", "ipa": "/əˈkweəriəm/", "trans": "aquariums/aquaria (複數)", "col": "public aquarium", "ex": "We visited the public aquarium in the city.", "pos": "n."},
    "aquatic": {"def": "水生的、水棲的、水上的、水生動物、水上運動、水上地 (水生)", "ipa": "/əˈkwætɪk/", "trans": "aquatics", "col": "aquatic life, aquatic sports", "ex": "Dolphins are aquatic mammals.", "pos": "adj./n./adv."},
    "aqueduct": {"def": "導水管、渡槽、(醫)管", "ipa": "/ˈækwɪdʌkt/", "trans": "water bridge", "col": "Roman aqueduct", "ex": "The ruins of the Roman aqueduct are still standing.", "pos": "n."},
    "aqueous": {"def": "水的、水狀的、由水成的", "ipa": "/ˈeɪkwiəs/", "trans": "watery", "col": "aqueous solution (水溶液)", "ex": "The chemical is dissolved in an aqueous solution.", "pos": "adj."},
    "aquiline": {"def": "鷹的、鷹嘴狀的、(鼻)鉤狀的", "ipa": "/ˈækwɪlaɪn/", "trans": "hooked", "col": "aquiline nose", "ex": "He has a very distinguished aquiline nose.", "pos": "adj."},
    "Arab": {"def": "阿拉伯人、阿拉伯馬、阿拉伯的、阿拉伯人的、阿拉伯語地 (阿拉伯)", "ipa": "/ˈærəb/", "trans": "Arabic", "col": "Arab world, purebred Arab", "ex": "He is an Arab from Saudi Arabia.", "pos": "n./adj./adv."},
    "Arabic": {"def": "阿拉伯語、阿拉伯語的、阿拉伯式的", "ipa": "/ˈærəbɪk/", "trans": "Arab (名詞/形容詞/副詞)", "col": "Arabic numerals (阿拉伯數字), speak Arabic", "ex": "Can you read Arabic?", "pos": "n./adj."},
    "arable": {"def": "適於耕種的、可耕的、耕地", "ipa": "/ˈærəbl/", "trans": "farmable", "col": "arable land", "ex": "Only 10% of the land is arable.", "pos": "adj./n."},
    "arbiter": {"def": "仲裁者、裁決人", "ipa": "/ˈɑːbɪtə/", "trans": "arbitrate, arbitrary", "col": "final arbiter", "ex": "The Supreme Court is the final arbiter of the law.", "pos": "n."},
    "arbitrarily": {"def": "武斷地、專橫地、任意地", "ipa": "/ˈɑːbɪtrərəli/", "trans": "arbitrary (形容詞/名詞/副詞), arbitrate", "col": "chosen arbitrarily", "ex": "The winners were chosen arbitrarily.", "pos": "adv."},
    "arbitrary": {"def": "武斷的、專橫的、任意的、武斷的人、武斷地 (武斷)", "ipa": "/ˈɑːbɪtrəri/", "trans": "arbitrarily, arbitrate", "col": "arbitrary decision, arbitrary power", "ex": "The decision was completely arbitrary.", "pos": "adj./n./adv."},
    "arbitrate": {"def": "仲裁、公斷、決定", "ipa": "/ˈɑːbɪtreɪt/", "trans": "arbitration, arbitrator", "col": "arbitrate a dispute", "ex": "A neutral committee was appointed to arbitrate the dispute.", "pos": "v."},
    "arbitration": {"def": "仲裁、公斷、裁決", "ipa": "/ˌɑːbɪˈtreɪʃn/", "trans": "arbitrate (動詞), arbitrator", "col": "international arbitration, go to arbitration", "ex": "The matter was settled through international arbitration.", "pos": "n."},
    "arbitrator": {"def": "仲裁人、公斷人", "ipa": "/ˈɑːbɪtreɪtə/", "trans": "arbitrate (動詞), arbitration", "col": "appointed arbitrator", "ex": "An independent arbitrator was called in to help.", "pos": "n."},
    "arbor/arbour": {"def": "涼亭、綠蔭處、樹木、(機)軸、綠意的、涼亭地 (涼亭)", "ipa": "/ˈɑːbə/", "trans": "pergola", "col": "garden arbor", "ex": "We sat under the cool garden arbor.", "pos": "n./adj./adv."},
    "arboreal": {"def": "樹木的、棲於樹上的", "ipa": "/ɑːˈbɔːriəl/", "trans": "tree-dwelling", "col": "arboreal animals", "ex": "Monkeys are mainly arboreal animals.", "pos": "adj."},
    "arboretum": {"def": "植物園、樹木園 (單數)", "ipa": "/ˌɑːbəˈriːtəm/", "trans": "arboretums/arboreta (複數)", "col": "national arboretum", "ex": "The national arboretum has a vast collection of trees.", "pos": "n."},
    "arc": {"def": "弧形、電弧、天穹、成弧形、成弧形地、電弧地 (弧)", "ipa": "/ɑːk/", "trans": "arcs", "col": "arc of a circle, rainbow arc", "ex": "The ball flew through the air in a perfect arc.", "pos": "n./v./adv."},
    "arcade": {"def": "拱廊、走廊、有拱廊的街道、(電玩)遊藝室", "ipa": "/ɑːˈkeɪd/", "trans": "arcades", "col": "shopping arcade, video arcade", "ex": "We spent the afternoon in the shopping arcade.", "pos": "n."},
    "arch": {"def": "拱門、足弓、調皮的、主要的、成弓形、使成拱形、主要的、調皮地 (拱)", "ipa": "/ɑːtʃ/", "trans": "arched", "col": "triumphal arch, arch rival, arch enemy", "ex": "The bridge has five arches.", "pos": "n./adj./v./adv."},
    "archaeologist/archeologist": {"def": "考古學家", "ipa": "/ˌɑːkiˈɒlədʒɪst/", "trans": "archaeology", "col": "underwater archaeologist", "ex": "He is a famous underwater archaeologist.", "pos": "n."},
    "archaeology/archeology": {"def": "考古學、古物", "ipa": "/ˌɑːkiˈɒlədʒi/", "trans": "archaeologist", "col": "biblical archaeology", "ex": "She is interested in biblical archaeology.", "pos": "n."},
    "archaic": {"def": "古代的、古風的、過時的", "ipa": "/ɑːˈkeɪɪk/", "trans": "outdated", "col": "archaic language", "ex": "The use of 'thee' is archaic in modern English.", "pos": "adj."},
    "archaism": {"def": "古語、古風、古詞", "ipa": "/ˈɑːkeɪɪzəm/", "trans": "archaic", "col": "deliberate archaism", "ex": "The author uses deliberate archaisms in his writing.", "pos": "n."},
    "archangel": {"def": "大天使、天使長", "ipa": "/ˈɑːkeɪndʒl/", "trans": "angels", "col": "archangel Gabriel", "ex": "Gabriel is a famous archangel in the Bible.", "pos": "n."},
    "archbishop": {"def": "總教主、大主教", "ipa": "/ˌɑːtʃˈbɪʃəp/", "trans": "bishop", "col": "archbishop of Canterbury", "ex": "The archbishop conducted the ceremony.", "pos": "n."},
    "arched": {"def": "拱形的、有足弓的", "ipa": "/ɑːtʃt/", "trans": "arch (名詞/形容詞/動詞/副詞)", "col": "arched window", "ex": "The house has beautiful arched windows.", "pos": "adj."},
    "archer": {"def": "射手、弓箭手、(天)人馬宮 (人馬座)", "ipa": "/ˈɑːtʃə/", "trans": "archery", "col": "skilled archer", "ex": "He is a very skilled archer.", "pos": "n."},
    "archery": {"def": "箭術、弓箭、射箭運動", "ipa": "/ˈɑːtʃəri/", "trans": "archer", "col": "archery tournament", "ex": "Archery is one of the oldest sports in the world.", "pos": "n."},
}