import json

# Level 5 Part 9: (Rival - Stumble)
L5_PART9 = {
    "rival": {"def": "對手、競爭者、比得上、相匹敵、競爭、參加比賽、競爭的", "ipa": "/ˈraɪvl/", "trans": "rivalry", "col": "arch rival, without rival", "ex": "The two countries are arch rivals in the field of science.", "pos": "n./v./adj."},
    "profound": {"def": "深遠的、深刻的、深厚的、淵博的、深淵、深處", "ipa": "/prəˈfaʊnd/", "trans": "profoundly", "col": "profound impact, profound insight", "ex": "The news had a profound impact on the people.", "pos": "adj./n."},
    "recession": {"def": "經濟衰退、後退、撤回", "ipa": "/rɪˈseʃn/", "trans": "recess", "col": "economic recession, deep recession", "ex": "The country is experiencing a deep economic recession.", "pos": "n."},
    "rod": {"def": "桿、棒、懲罰、權力", "ipa": "/rɒd/", "trans": "rods", "col": "fishing rod, lightning rod", "ex": "He spent the afternoon fishing with his new rod.", "pos": "n."},
    "progressive": {"def": "進步的、先進的、漸進的、進步人士、開明的人", "ipa": "/prəˈɡresɪv/", "trans": "progress (名詞/動詞)", "col": "progressive policy, progressive taxation", "ex": "The government is introducing more progressive policies.", "pos": "adj./n."},
    "specialty": {"def": "專業、特產、專長", "ipa": "/ˈspeʃəlti/", "trans": "special, specialize", "col": "local specialty, medical specialty", "ex": "The restaurant's specialty is seafood.", "pos": "n."},
    "structural": {"def": "結構的、建築的", "ipa": "/ˈstrʌktʃərəl/", "trans": "structure (名詞/動詞)", "col": "structural change, structural adjustment", "ex": "The building needs some structural repairs.", "pos": "adj."},
    "shatter": {"def": "打碎、使破滅、破片、碎片、粉碎、瓦解", "ipa": "/ˈʃætə/", "trans": "shattered", "col": "shatter someone's dreams", "ex": "The news shattered all her hopes for the future.", "pos": "v./n."},
    "specify": {"def": "具體說明、明確規定、詳述", "ipa": "/ˈspesɪfaɪ/", "trans": "specific, specification", "col": "specify requirements", "ex": "Please specify your requirements in the form.", "pos": "v."},
    "stumble": {"def": "絆倒、出錯、結結巴巴、絆、錯誤、失足、絆倒地、偶然地", "ipa": "/ˈstʌmbl/", "trans": "stumbling", "col": "stumble across (偶然發現), stumble over", "ex": "He stumbled over a stone and fell.", "pos": "v./n./adv."},
    "burnout": {"def": "燒毀、倦怠、精疲力竭", "ipa": "/ˈbɜːnaʊt/", "trans": "burn (名詞/動詞)", "col": "suffer from burnout", "ex": "He is suffering from burnout after years of hard work.", "pos": "n."},
    "bust": {"def": "半身像、胸部、破產、逮捕、破裂的、破產的、爆發、捕獲、破產地", "ipa": "/bʌst/", "trans": "busted", "col": "go bust", "ex": "The company went bust last year.", "pos": "n./adj./v./adv."},
    "bustle": {"def": "忙亂、喧囂、群集、忙碌、奔忙、充滿", "ipa": "/ˈbʌsl/", "trans": "bustling", "col": "hustle and bustle", "ex": "I like the hustle and bustle of the city life.", "pos": "n./v."},
    "busyness": {"def": "忙碌、繁忙", "ipa": "/ˈbɪzinəs/", "trans": "busy (形容詞/動詞/副詞)", "col": "daily busyness", "ex": "The daily busyness of the office was overwhelming.", "pos": "n."},
    "butchery": {"def": "屠宰術、肉店、屠殺、殘酷行徑", "ipa": "/ˈbʊtʃəri/", "trans": "butcher (名詞/動詞/形容詞)", "col": "wholesale butchery", "ex": "He works in the wholesale butchery business.", "pos": "n."},
    "bygone": {"def": "過去的、過時的、往事", "ipa": "/ˈbaɪɡɒn/", "trans": "gone", "col": "let bygones be bygones (既往不咎)", "ex": "Let's let bygones be bygones.", "pos": "adj./n."},
    "bypass": {"def": "旁道、避開、繞過、繞道", "ipa": "/ˈbaɪpɑːs/", "trans": "heart bypass", "col": "bypass surgery", "ex": "The new road will bypass the town center.", "pos": "n./v."},
    "by-product": {"def": "副產品、副作用", "ipa": "/ˈbaɪprɒdʌkt/", "trans": "product", "col": "useful by-product", "ex": "Happiness is often a by-product of helping others.", "pos": "n."},
    "cacti": {"def": "仙人掌(複數)", "ipa": "/ˈkæktaɪ/", "trans": "cactus (單數)", "col": "rare cacti", "ex": "The collector specialized in rare cacti.", "pos": "n."},
    "cadaver": {"def": "屍體", "ipa": "/kəˈdævə/", "trans": "cadaverous", "col": "dissect a cadaver", "ex": "The medical students were dissecting a cadaver.", "pos": "n."},
    "cadence": {"def": "韻律、節奏、抑揚頓挫、降下、終結的", "ipa": "/ˈkeɪdns/", "trans": "cadent", "col": "natural cadence", "ex": "She spoke with the natural cadence of a native speaker.", "pos": "n./adj."},
    "cafe": {"def": "咖啡館、小餐館", "ipa": "/ˈkæfeɪ/", "trans": "cafeteria", "col": "sidewalk cafe", "ex": "They met for a coffee in a small sidewalk cafe.", "pos": "n."},
    "cafeteria": {"def": "自助餐廳", "ipa": "/ˌkæfəˈtɪəriə/", "trans": "cafe", "col": "school cafeteria", "ex": "The students are having lunch in the school cafeteria.", "pos": "n."},
    "caffeine": {"def": "咖啡因", "ipa": "/ˈkæfiːn/", "trans": "caffeinated", "col": "rich in caffeine", "ex": "Coffee and tea are rich in caffeine.", "pos": "n."},
    "cage": {"def": "籠子、牢房、升降機、關入籠中、束縛、關進監獄", "ipa": "/keɪdʒ/", "trans": "caged", "col": "bird cage", "ex": "The bird was kept in a small cage.", "pos": "n./v."},
    "cajole": {"def": "哄騙、誘騙、勸誘", "ipa": "/kəˈdʒəʊl/", "trans": "cajolery", "col": "cajole someone into", "ex": "He cajoled her into going with him.", "pos": "v."},
    "calamity": {"def": "災難、不幸的事", "ipa": "/kəˈlæməti/", "trans": "calamitous", "col": "sudden calamity", "ex": "The heavy floods were a sudden calamity for the farmers.", "pos": "n."},
    "calcium": {"def": "鈣", "ipa": "/ˈkælsiəm/", "trans": "calcify", "col": "rich in calcium", "ex": "Milk is rich in calcium.", "pos": "n."},
    "calculate": {"def": "計算、估計、預測、計畫", "ipa": "/ˈkælkjuleɪt/", "trans": "calculation, calculator", "col": "calculate the cost", "ex": "We need to calculate the total cost of the project.", "pos": "v."},
    "calculated": {"def": "計算出的、預謀的、蓄意的、適當的", "ipa": "/ˈkælkjuleɪtɪd/", "trans": "calculate (動詞), calculation", "col": "calculated risk", "ex": "Taking the challenge was a calculated risk.", "pos": "adj."},
    "calculating": {"def": "計算的、深謀遠慮的、狡猾的", "ipa": "/ˈkælkjuleɪtɪŋ/", "trans": "calculate (動詞), calculation", "col": "calculating mind", "ex": "He is a cold and calculating person.", "pos": "adj."},
    "calculation": {"def": "計算、估算、深謀遠慮、打算", "ipa": "/ˌkælkjuˈleɪʃn/", "trans": "calculate (動詞), calculator", "col": "statistical calculation", "ex": "The report is based on complicated calculations.", "pos": "n."},
    "calculator": {"def": "計算機、計算者", "ipa": "/ˈkælkjuleɪtə/", "trans": "calculate (動詞), calculation", "col": "electronic calculator", "ex": "You can use a calculator for the test.", "pos": "n."},
    "calendar": {"def": "日曆、曆法、日程表、列入日程表、分類、記下", "ipa": "/ˈkælɪndə/", "trans": "calendars", "col": "solar calendar, lunar calendar, social calendar", "ex": "Check the date on the calendar.", "pos": "n./v."},
    "calf": {"def": "小牛、幼獸、腓、小腿", "ipa": "/kɑːf/", "trans": "calves (複數)", "col": "calf muscles", "ex": "He has a cramp in his left calf.", "pos": "n."},
    "caliber/calibre": {"def": "口徑、才幹、水準", "ipa": "/ˈkælɪbə/", "trans": "calibrate", "col": "man of high caliber", "ex": "The company is looking for people of high caliber.", "pos": "n."},
    "calibrate": {"def": "校準、定口徑、劃分刻度", "ipa": "/ˈkælɪbreɪt/", "trans": "calibration", "col": "calibrate a scale", "ex": "The machine needs to be calibrated regularly.", "pos": "v."},
    "calibration": {"def": "校準、標定、刻度", "ipa": "/ˌkælɪˈbreɪʃn/", "trans": "calibrate (動詞)", "col": "regular calibration", "ex": "The instrument needs regular calibration.", "pos": "n."},
    "caliph": {"def": "哈里發、回教國王", "ipa": "/ˈkeɪlɪf/", "trans": "caliphate", "col": "Abbasid caliph", "ex": "Harun al-Rashid was a famous Abbasid caliph.", "pos": "n."},
    "call": {"def": "呼喚、通話、拜訪、招換、大喊、打電話、命名、拜訪、大聲地、出色地、名聲、稱號", "ipa": "/kɔːl/", "trans": "calling", "col": "call back, call on, call off", "ex": "Please call me this evening.", "pos": "n./v./adv."},
    "calling": {"def": "召喚、職業、天職", "ipa": "/ˈkɔːlɪŋ/", "trans": "call (名詞/動詞/副詞)", "col": "divine calling, true calling", "ex": "Teaching is his true calling.", "pos": "n."},
    "callous": {"def": "起繭的、無情的、硬心腸的、使起繭、使冷酷、起繭、變冷酷", "ipa": "/ˈkæləs/", "trans": "callosity", "col": "callous remark", "ex": "He made several callous remarks about the victims.", "pos": "adj./v."},
    "calm": {"def": "平靜的、鎮定的、氣候溫和的、平靜、平定、鎮定、使鎮定、平靜下來、鎮定地", "ipa": "/kɑːm/", "trans": "calmness, calmly", "col": "keep calm, calm down", "ex": "The sea was very calm today.", "pos": "adj./n./v./adv."},
    "calmly": {"def": "鎮定地、平靜地、冷淡地", "ipa": "/ˈkɑːmli/", "trans": "calm (形容詞/名詞/動詞/副詞)", "col": "respond calmly", "ex": "She responded calmly to the challenge.", "pos": "adv."},
    "calmness": {"def": "平靜、鎮定、冷淡", "ipa": "/ˈkːmnəs/", "trans": "calm (形容詞/名詞/動詞/副詞/副詞)", "col": "unusual calmness", "ex": "He faced the danger with unusual calmness.", "pos": "n."},
    "calorie/calory": {"def": "卡路里、熱量", "ipa": "/ˈkæləri/", "trans": "caloric", "col": "low calorie, calorie count", "ex": "This cake is high in calories.", "pos": "n."},
    "calumny": {"def": "誹謗、中傷", "ipa": "/ˈkæləmni/", "trans": "calumnious", "col": "sheer calumny", "ex": "The allegations are nothing but sheer calumny.", "pos": "n."},
    "camel": {"def": "駱駝、駝色、像駱駝般的、工作努的人、吃苦的人", "ipa": "/ˈkæml/", "trans": "camels", "col": "camel hair", "ex": "Camels are known as the ships of the desert.", "pos": "n./adj."},
    "camellia": {"def": "山茶花、山茶屬植物", "ipa": "/kəˈmiːliə/", "trans": "camellias", "col": "pink camellia", "ex": "The garden is full of pink camellias.", "pos": "n."},
    "cameo": {"def": "浮雕珠寶、(名演員的)客串演出、刻成浮雕 (浮雕)", "ipa": "/ˈkæmiəʊ/", "trans": "cameos", "col": "cameo appearance", "ex": "The famous actor made a cameo appearance in the movie.", "pos": "n./v."},
    "camera": {"def": "照相機、攝影機、私人隱密地 (照相機)", "ipa": "/ˈkæmrə/", "trans": "cameraman", "col": "digital camera, in camera (秘密地)", "ex": "Don't forget to bring your camera.", "pos": "n./adv."},
    "cameraman": {"def": "攝影師、照相師", "ipa": "/ˈkæmrəmæn/", "trans": "camera (名詞/副詞), camera operator", "col": "news cameraman", "ex": "He works as a news cameraman for the TV station.", "pos": "n."},
    "camouflage": {"def": "變裝、偽裝、掩飾、掩護、偽裝、變裝、掩飾、騙局", "ipa": "/ˈkæməflɑːʒ/", "trans": "camouflaged", "col": "natural camouflage", "ex": "Animals use natural camouflage to hide from predators.", "pos": "n./v."},
    "camp": {"def": "營地、陣營、兵營、露營、紮營、紮營的、兵營的、(裝飾)誇張地、極不自然地", "ipa": "/kæmp/", "trans": "camping, camper", "col": "summer camp, concentration camp", "ex": "They are planning to go camping this weekend.", "pos": "n./v./adj./adv."},
    "campaign": {"def": "戰役、活動、競選運動、參加活動、作戰、從事活動、運動的", "ipa": "/kæmˈpeɪn/", "trans": "campaigner", "col": "advertising campaign, election campaign", "ex": "The company has launched a major advertising campaign.", "pos": "n./v./adj."},
    "campus": {"def": "校園、校內、大學場地、校園的", "ipa": "/ˈkæmpəs/", "trans": "campuses", "col": "on campus, university campus", "ex": "Students are required to live on campus for the first year.", "pos": "n./adj."},
    "can": {"def": "罐頭、容器、監獄、能夠、可以、裝罐頭、解僱、罐頭裝的", "ipa": "/kæn/", "trans": "canning, canned", "col": "can opener, tin can", "ex": "I can help you with the project.", "pos": "n./v./aux./adj."},
    "canal": {"def": "運河、渠道、管、道、開運河、用溝渠聯接", "ipa": "/kəˈnæl/", "trans": "canals", "col": "Panama Canal, Suez Canal", "ex": "The Panama Canal connects the Atlantic and Pacific oceans.", "pos": "n./v."},
    "canary": {"def": "金絲雀、鮮黃色、密報者、鮮黃色的", "ipa": "/kəˈneəri/", "trans": "canaries", "col": "sing like a canary (告密)", "ex": "She has a yellow canary in a cage.", "pos": "n./adj."},
    "cancel": {"def": "取消、廢除、抵銷、註銷、取消的人 (或事)、註銷處、取消地 (取消)", "ipa": "/ˈkænsl/", "trans": "cancellation", "col": "cancel a flight, cancel a meeting", "ex": "The flight was cancelled due to bad weather.", "pos": "v./n./adv."},
    "cancellation": {"def": "取消、抹掉、註銷、取消物", "ipa": "/ˌkænsəˈleɪʃn/", "trans": "cancel (動詞/名詞/副詞)", "col": "flight cancellation", "ex": "There have been several flight cancellations today.", "pos": "n."},
    "cancer": {"def": "癌症、毒瘤、巨蟹座、弊端", "ipa": "/ˈkænsə/", "trans": "cancerous", "col": "lung cancer, breast cancer, skin cancer", "ex": "Smoking causes lung cancer.", "pos": "n."},
    "cancerous": {"def": "癌症的、如癌的、患癌的", "ipa": "/ˈkænsərəs/", "trans": "cancer (名詞)", "col": "cancerous tumor", "ex": "The tests showed that the tumor is cancerous.", "pos": "adj."},
    "candid": {"def": "正直的、坦白的、公正的、非正式的照片", "ipa": "/ˈkændɪd/", "trans": "candidly, candor", "col": "candid opinion, candid photo", "ex": "Let me give you my candid opinion.", "pos": "adj./n."},
    "candidate": {"def": "侯選人、應試者、投考者", "ipa": "/ˈkændɪdət/", "trans": "candidacy", "col": "presidential candidate, successful candidate", "ex": "He is a candidate for the presidential election.", "pos": "n."},
    "candle": {"def": "蠟燭、燭光、燭光的人 (或事)、用燭光檢查、對光檢查", "ipa": "/ˈkændl/", "trans": "candles", "col": "birthday candle, light a candle", "ex": "She blew out the birthday candles.", "pos": "n./v."},
    "candor/candour": {"def": "公正、坦白、正直、潔白", "ipa": "/ˈkændə/", "trans": "candid", "col": "speak with candor", "ex": "The report was written with remarkable candor.", "pos": "n."},
    "candy": {"def": "糖果、冰糖、精美的人(或物)、蜜餞、使結晶成糖、用糖煮、變成糖、糖果狀的", "ipa": "/ˈkændi/", "trans": "candies", "col": "hard candy, cotton candy", "ex": "The children are eating fruit candies.", "pos": "n./v./adj."},
}

with open("batch_l5_p9.json", "w", encoding="utf-8") as f:
    json.dump(L5_PART9, f, ensure_ascii=False, indent=2)
