import json

# Level 6 Part 52: (Broaden - Brow)
L6_PART52 = {
    "broaden": {"def": "變寬、拓寬、擴大、拓寬的人 (或物)、拓寬地 (寬)", "ipa": "/ˈbrɔːdn/", "trans": "broad", "col": "broaden horizons (開闊眼界), broaden one's knowledge", "ex": "Travel broadens the mind.", "pos": "v./n./adv."},
    "broadening": {"def": "拓寬、擴大、開闊的人 (或物) (拓)", "ipa": "/ˈbrɔːdnɪŋ/", "trans": "broaden (動詞/名詞/副詞)", "col": "cultural broadening", "ex": "The broadening of his experience was evident in his work.", "pos": "n./adv."},
    "broadly": {"def": "寬廣地、概括地、顯著地", "ipa": "/ˈbrɔːdli/", "trans": "broad (形容詞/名詞/副詞)", "col": "broadly speaking (廣義上說), smiled broadly", "ex": "Broadly speaking, there are two types of tourists.", "pos": "adv."},
    "broadness": {"def": "寬度、廣大、粗俗", "ipa": "/ˈbrɔːdnəs/", "trans": "broad (形容詞/名詞/副詞)", "col": "breadth and broadness", "ex": "The broadness of his shoulders made him look very strong.", "pos": "n."},
    "brocade": {"def": "織錦、錦緞、在...繡上花紋、錦緞的人、錦緞地 (錦)", "ipa": "/brəˈkeɪd/", "trans": "fabric", "col": "silk brocade", "ex": "The walls were covered in a rich silk brocade.", "pos": "n./v./adv."},
    "broccoli": {"def": "青花菜、西蘭花 (單數)", "ipa": "/ˈbrɒkəli/", "trans": "vegetables", "col": "steamed broccoli", "ex": "Broccoli is full of vitamins.", "pos": "n."},
    "brochure": {"def": "手冊、小冊子 (單數)", "ipa": "/ˈbrəʊʃə/", "trans": "brochures (複數)", "col": "holiday brochure, informative brochure", "ex": "Take a look at our latest holiday brochure.", "pos": "n."},
    "brock": {"def": "獾、臭傢伙 (單數)", "ipa": "/brɒk/", "trans": "badger", "col": "old brock", "ex": "Old brock was seen scurrying into its set.", "pos": "n."},
    "broderie": {"def": "刺繡、刺繡品 (法)", "ipa": "/ˈbrəʊdəri/", "trans": "embroidery", "col": "broderie anglaise", "ex": "She wore a white dress with delicate broderie anglaise.", "pos": "n."},
    "brogan": {"def": "粗皮鞋、粗布鞋 (單數)", "ipa": "/ˈbrəʊɡən/", "trans": "shoe", "col": "heavy brogan", "ex": "He wore heavy leather brogans for farm work.", "pos": "n."},
    "brogue": {"def": "粗皮鞋、(愛爾蘭)口音、穿粗皮鞋的人物、口音地 (口音)", "ipa": "/brəʊɡ/", "trans": "accent", "col": "thick Irish brogue", "ex": "He spoke with a thick Irish brogue.", "pos": "n./adv."},
    "broil": {"def": "烤、炙、爭吵、發熱、爭吵的人、爭吵地 (烤)", "ipa": "/brɔɪl/", "trans": "broiling", "col": "broil steaks", "ex": "You can broil the fish under the grill.", "pos": "v./n./adv."},
    "broiler": {"def": "烤架、用來烤的雞 (單數)", "ipa": "/ˈbrɔɪlə/", "trans": "grill", "col": "electric broiler", "ex": "Put the chicken in the broiler for fifteen minutes.", "pos": "n."},
    "broke": {"def": "(break的過去式)、一貧如洗的、破產的 (單數)", "ipa": "/brəʊk/", "trans": "penniless", "col": "go broke (破產), stone broke (身無分文)", "ex": "I'm completely broke until payday.", "pos": "v./adj."},
    "broken": {"def": "(break的過去分詞)、斷掉的、受打擊的、不流利的人物、破碎地 (碎)", "ipa": "/ˈbrəʊkən/", "trans": "damaged", "col": "broken heart, broken English, broken home, broken records", "ex": "My watch is broken.", "pos": "v./adj./adv."},
    "broken-hearted": {"def": "傷心欲絕的", "ipa": "/ˌbrəʊkən ˈhɑːtɪd/", "trans": "devastated", "col": "left him broken-hearted", "ex": "She was broken-hearted when her dog died.", "pos": "adj."},
    "brokenly": {"def": "斷斷續續地、破碎地", "ipa": "/ˈbrəʊkənli/", "trans": "broken (形容詞/副詞)", "col": "spoke brokenly", "ex": "He spoke brokenly about the tragedy.", "pos": "adv."},
    "broker": {"def": "經紀人、仲介、安排、仲介的人、仲介地 (經紀)", "ipa": "/ˈbrəʊkə/", "trans": "brokerage", "col": "stock broker, insurance broker, real estate broker, power broker", "ex": "The deal was arranged by a local insurance broker.", "pos": "n./v./adv."},
    "brokerage": {"def": "經紀業務、佣金、仲介處 (單數)", "ipa": "/ˈbrəʊkərɪdʒ/", "trans": "broker", "col": "brokerage firm, pay brokerage", "ex": "The brokerage firm handles millions in daily transactions.", "pos": "n."},
    "bromide": {"def": "溴化物、(口)陳詞濫調 (單數)", "ipa": "/ˈbrəʊmaɪd/", "trans": "cliché", "col": "calming bromide", "ex": "His speech was full of meaningless bromides.", "pos": "n."},
    "bronchi": {"def": "支氣管 (複數)", "ipa": "/ˈbrɒŋkaɪ/", "trans": "bronchus", "col": "inflamed bronchi", "ex": "The doctor examined the patient's inflamed bronchi.", "pos": "n."},
    "bronchial": {"def": "支氣管的", "ipa": "/ˈbrɒŋkiəl/", "trans": "bronchi", "col": "bronchial asthma, bronchial tubes", "ex": "He suffers from bronchial asthma.", "pos": "adj."},
    "bronchitis": {"def": "支氣管炎 (單數)", "ipa": "/brɒŋˈkaɪtɪs/", "trans": "inflammation", "col": "chronic bronchitis", "ex": "Chronic bronchitis is common among heavy smokers.", "pos": "n."},
    "bronchus": {"def": "支氣管 (單數)", "ipa": "/ˈbrɒŋkəs/", "trans": "bronchi", "col": "main bronchus", "ex": "A foreign object was stuck in his left main bronchus.", "pos": "n."},
    "bronze": {"def": "青銅、青銅製品、青銅色的、鍍青銅於、青銅地 (青銅)", "ipa": "/brɒnz/", "trans": "bronzed", "col": "bronze medal, bronze age, bronze statue", "ex": "He won the bronze medal in the high jump.", "pos": "n./adj./v./adv."},
    "bronzed": {"def": "鍍青銅的、曬成古銅色的的人 (或物)", "ipa": "/brɒnzd/", "trans": "bronze (名詞/動詞/副詞)", "col": "bronzed muscles", "ex": "He had a handsome, bronzed face from the sun.", "pos": "adj./n."},
    "brooch": {"def": "胸針、領針 (單數)", "ipa": "/brəʊtʃ/", "trans": "brooches (複數)", "col": "antique brooch", "ex": "She wore an antique silver brooch on her velvet jacket.", "pos": "n."},
    "brood": {"def": "一窩(幼鳥)、沈思、孵蛋、沈思地 (思)", "ipa": "/bruːd/", "trans": "brooding", "col": "brood over, brood of chickens", "ex": "A hen was sitting on a brood of eggs.", "pos": "n./v./adv."},
    "brooding": {"def": "沈思的、陰森的、憂鬱的人 (或物) (思)", "ipa": "/ˈbruːdɪŋ/", "trans": "brood (名詞/動詞/副詞)", "col": "brooding presence", "ex": "He sat in a corner, lost in a brooding silence.", "pos": "adj./adv."},
    "brook": {"def": "小溪、溪流、容忍、在溪邊人物、在溪邊地 (溪)", "ipa": "/brʊk/", "trans": "brooks", "col": "babbling brook, brook no delay (不容延誤)", "ex": "We sat by a small brook in the forest.", "pos": "n./v./adv."},
    "broom": {"def": "掃帚、金雀花、打掃的人物、打掃地 (掃)", "ipa": "/bruːm/", "trans": "brooms", "col": "new broom sweeps clean (新官上任三把火), broom handle", "ex": "She used a broom to sweep the floor.", "pos": "n./v./adv."},
    "broomstick": {"def": "掃帚柄 (單數)", "ipa": "/ˈbruːmstɪk/", "trans": "broomsticks (複數)", "col": "ride a broomstick", "ex": "Witches are often depicted riding broomsticks.", "pos": "n."},
    "broth": {"def": "肉湯、清湯 (單數)", "ipa": "/brɒθ/", "trans": "soup", "col": "chicken broth", "ex": "Mothers often make chicken broth for sick children.", "pos": "n."},
    "brothel": {"def": "妓院 (單數)", "ipa": "/ˈbrɒθl/", "trans": "brothels (複數)", "col": "notorious brothel", "ex": "The police raided a notorious brothel in the city center.", "pos": "n."},
    "brother": {"def": "兄弟、同胞、教友、(感嘆詞)我的天！、兄弟人物、兄弟地 (兄)", "ipa": "/ˈbrʌðə/", "trans": "brothers, brotherhood", "col": "elder brother, half brother, brother-in-law (姐夫/妹夫/內兄/內弟)", "ex": "My elder brother is an engineer.", "pos": "n./int./adv."},
    "brotherhood": {"def": "手足情誼、兄弟會、同業公會 (單數)", "ipa": "/ˈbrʌðəhʊd/", "trans": "fraternity", "col": "Universal Brotherhood", "ex": "They believe in the universal brotherhood of man.", "pos": "n."},
    "brotherly": {"def": "兄弟般的、親切的、博愛地", "ipa": "/ˈbrʌðəli/", "trans": "brother (名詞/副詞)", "col": "brotherly love", "ex": "He gave his friend some brotherly advice.", "pos": "adj./adv."},
    "brought": {"def": "(bring的過去式及過去分詞)、帶來的", "ipa": "/brɔːt/", "trans": "bring", "col": "brought up", "ex": "The incident brought about major changes in the law.", "pos": "v."},
    "brow": {"def": "額頭、眉毛、山脊、眉端的人、眉端地 (額)", "ipa": "/braʊ/", "trans": "brows", "col": "knit one's brows (皺眉), by the sweat of one's brow (辛勤工作)", "ex": "He wiped the sweat from his brow.", "pos": "n./adv."},
}