import json

# Level 6 Part 14: (Astounding - Attire)
L6_PART14 = {
    "astounding": {"def": "令人驚愕的、驚人的", "ipa": "/əˈstaʊndɪŋ/", "trans": "astound (動詞)", "col": "astounding achievement", "ex": "It's an astounding achievement for someone so young.", "pos": "adj."},
    "astoundingly": {"def": "令人驚愕地、驚人地", "ipa": "/əˈstaʊndɪŋli/", "trans": "astounding (形容詞), astound", "col": "astoundingly low", "ex": "The prices were astoundingly low.", "pos": "adv."},
    "astral": {"def": "星的、星狀的、精神世界的", "ipa": "/ˈæstrəl/", "trans": "stellar", "col": "astral body", "ex": "He believes in the existence of an astral body.", "pos": "adj."},
    "astray": {"def": "誤入歧途的、迷路的、誤入歧途地、迷路地 (迷路)", "ipa": "/əˈstreɪ/", "trans": "lost", "col": "go astray, led astray", "ex": "The letter seems to have gone astray.", "pos": "adj./adv."},
    "astride": {"def": "跨在...上、跨越地、兩腿分開地 (跨著)", "ipa": "/əˈstraɪd/", "trans": "across", "col": "sit astride a horse", "ex": "He sat astride the horse.", "pos": "prep./adv./adj."},
    "astringent": {"def": "收斂的、嚴酷的、澀的、收斂劑", "ipa": "/əˈstrɪndʒənt/", "trans": "harsh", "col": "astringent remark", "ex": "She made some very astringent remarks about his work.", "pos": "adj./n."},
    "astrolabe": {"def": "星盤、古代星位觀測儀", "ipa": "/ˈæstrəleɪb/", "trans": "astronomy instrument", "col": "ancient astrolabe", "ex": "The astrolabe was an important tool for early astronomers.", "pos": "n."},
    "astrologer": {"def": "占星家", "ipa": "/əˈstrɒlədʒə/", "trans": "astrology", "col": "famous astrologer", "ex": "She consulted a famous astrologer about her future.", "pos": "n."},
    "astrology": {"def": "占星術、占星學", "ipa": "/əˈstrɒlədʒi/", "trans": "astrologer", "col": "believe in astrology", "ex": "I don't really believe in astrology.", "pos": "n."},
    "astronaut": {"def": "宇航員、航天員", "ipa": "/ˈæstrənɔːt/", "trans": "cosmonaut", "col": "astronaut mission", "ex": "The astronaut spent six months on the space station.", "pos": "n."},
    "astronomer": {"def": "天文學家", "ipa": "/əˈstrɒnəmə/", "trans": "astronomy", "col": "amateur astronomer", "ex": "He is an amateur astronomer with a powerful telescope.", "pos": "n."},
    "astronomical/astronomic": {"def": "天文學的、天文學上的、巨大的", "ipa": "/ˌæstrəˈnɒmɪkl/", "trans": "astronomy", "col": "astronomical price, astronomical distance", "ex": "The cost of the project is astronomical.", "pos": "adj."},
    "astronomy": {"def": "天文學", "ipa": "/əˈstrɒnəmi/", "trans": "astronomer", "col": "professor of astronomy", "ex": "She is a professor of astronomy at the university.", "pos": "n."},
    "astrophysics": {"def": "天體物理學", "ipa": "/ˌæstrəʊˈfɪzɪks/", "trans": "astrophysicist", "col": "department of astrophysics", "ex": "He is studying astrophysics in New York.", "pos": "n."},
    "astute": {"def": "機敏的、精明的、狡猾的", "ipa": "/əˈstjuːt/", "trans": "astutely", "col": "astute observation", "ex": "He was an astute businessman who knew how to make a profit.", "pos": "adj."},
    "asunder": {"def": "分開地、分離地、碎裂地 (分開)", "ipa": "/əˈsʌndə/", "trans": "apart", "col": "torn asunder", "ex": "The country was torn asunder by the civil war.", "pos": "adv./adj."},
    "asylum": {"def": "庇護、收容、精神病院、庇護、收容、庇護的人 (或物)、庇護地 (庇護)", "ipa": "/əˈsaɪləm/", "trans": "shelter", "col": "political asylum, seek asylum, insane asylum (精神病院)", "ex": "She was granted political asylum in the US.", "pos": "n./v./adv."},
    "asymmetry": {"def": "不對稱、不勻稱", "ipa": "/ˌeɪˈsɪmətri/", "trans": "asymmetric", "col": "inherent asymmetry", "ex": "The designer uses asymmetry to create an interesting look.", "pos": "n."},
    "asymptomatic": {"def": "無症狀的", "ipa": "/ˌeɪsɪmptəˈmætɪk/", "trans": "no symptoms", "col": "asymptomatic carrier (無症狀帶原者)", "ex": "He was an asymptomatic carrier of the virus.", "pos": "adj."},
    "at": {"def": "在、在...上、在...點鐘、向、在...地、向著、(法)在 (在)", "ipa": "/æt/", "trans": "towards", "col": "at once, at least, at last", "ex": "She is at home.", "pos": "prep./n./adv."},
    "atavic/atavistic": {"def": "返祖的、隔代遺傳的", "ipa": "/ˌætəˈvɪstɪk/", "trans": "ancestral", "col": "atavistic fear", "ex": "He felt an atavistic fear of the dark.", "pos": "adj."},
    "atavism": {"def": "返祖、隔代遺傳", "ipa": "/ˈætəvɪzəm/", "trans": "atavistic", "col": "pure atavism", "ex": "The behavior was seen as a pure atavism.", "pos": "n."},
    "ate": {"def": "(eat的過去式)、吃", "ipa": "/et/", "trans": "eat", "col": "ate dinner", "ex": "I ate a sandwich for lunch.", "pos": "v."},
    "atheism": {"def": "無神論", "ipa": "/ˈeɪθiɪzəm/", "trans": "atheist", "col": "militant atheism", "ex": "He was accused of militant atheism.", "pos": "n."},
    "atheist": {"def": "無神論者", "ipa": "/ˈeɪθiɪst/", "trans": "atheism", "col": "avowed atheist", "ex": "He is an avowed atheist who openly rejects religion.", "pos": "n."},
    "athlete": {"def": "運動員、體育家", "ipa": "/ˈæθliːt/", "trans": "athletic", "col": "professional athlete, star athlete", "ex": "She is a star athlete in her school.", "pos": "n."},
    "athletic": {"def": "運動的、體育的、體壯的、運動的人 (或物)、體格強健地 (運動)", "ipa": "/æθˈletɪk/", "trans": "athletics", "col": "athletic club, athletic ability", "ex": "He has always been very athletic.", "pos": "adj./n./adv."},
    "athletics": {"def": "體育運動、競技", "ipa": "/æθˈletɪks/", "trans": "athletic", "col": "track and field athletics", "ex": "The school has a strong tradition in athletics.", "pos": "n."},
    "Atlantic": {"def": "大西洋的、大西洋地帶的、大西洋、大西洋區域", "ipa": "/ətˈlæntɪk/", "trans": "Ocean", "col": "Atlantic Ocean, across the Atlantic", "ex": "They sailed across the Atlantic.", "pos": "adj./n."},
    "atlas": {"def": "地圖集、地圖冊、(解)寰椎 (第一頸椎) (單數)", "ipa": "/ˈætləs/", "trans": "atlases (複數)", "col": "world atlas, road atlas", "ex": "I consulted the world atlas to find the country.", "pos": "n."},
    "atmosphere": {"def": "大氣、氣氛、大氣層、環境", "ipa": "/ˈætməsfɪə/", "trans": "atmospheric", "col": "pleasant atmosphere, Earth's atmosphere", "ex": "The Earth's atmosphere protects us from the sun.", "pos": "n."},
    "atmospheric": {"def": "大氣的、有氣氛的、充滿藝術氣息的", "ipa": "/ˌætməsˈferɪk/", "trans": "atmosphere", "col": "atmospheric pressure", "ex": "The atmospheric pressure is very low today.", "pos": "adj."},
    "atoll": {"def": "環礁", "ipa": "/ˈætɒl/", "trans": "coral island", "col": "coral atoll", "ex": "The boat anchored in the lagoon of the coral atoll.", "pos": "n."},
    "atom": {"def": "原子、微粒、點、一丁點的人物、原子般地 (原子)", "ipa": "/ˈætəm/", "trans": "atomic", "col": "splitting the atom, not an atom of truth", "ex": "An atom is the smallest unit of an element.", "pos": "n./adv."},
    "atomic": {"def": "原子的、原子能的、極小的", "ipa": "/əˈtɒmɪk/", "trans": "atom (名詞/副詞)", "col": "atomic bomb, atomic energy", "ex": "They are researching atomic energy for peaceful purposes.", "pos": "adj."},
    "atomize": {"def": "原子化、噴霧、使分裂", "ipa": "/ˈætəmaɪz/", "trans": "atomizer", "col": "atomize liquid", "ex": "The machine helps to atomize the liquid into a fine spray.", "pos": "v."},
    "atomizer": {"def": "噴霧器、香水噴霧器", "ipa": "/ˈætəmaɪzə/", "trans": "atomize (動詞)", "col": "perfume atomizer", "ex": "She used a perfume atomizer to apply the scent.", "pos": "n."},
    "atonal": {"def": "(音)無調性的", "ipa": "/ˌeɪˈtəʊnl/", "trans": "atonality", "col": "atonal music", "ex": "Many people find atonal music difficult to listen to.", "pos": "adj."},
    "atone": {"def": "彌補、補償、贖罪", "ipa": "/əˈtəʊn/", "trans": "atonement", "col": "atone for one's sins", "ex": "He spent the rest of his life trying to atone for his past crimes.", "pos": "v."},
    "atonement": {"def": "補償、贖罪", "ipa": "/əˈtəʊnmənt/", "trans": "atone (動詞)", "col": "day of atonement", "ex": "The poem is a work of atonement.", "pos": "n."},
    "atrium": {"def": "中庭、前廳、(解)心房 (單數)", "ipa": "/ˈeɪtriəm/", "trans": "atria/atriums (複數)", "col": "glass-roofed atrium", "ex": "The hotel has a beautiful glass-roofed atrium.", "pos": "n."},
    "atrocious": {"def": "殘暴的、極惡的、糟透的", "ipa": "/əˈtrəʊʃəs/", "trans": "atrocity", "col": "atrocious crime, atrocious weather", "ex": "The weather was absolutely atrocious yesterday.", "pos": "adj."},
    "atrocity": {"def": "暴行、極惡、極壞的東西", "ipa": "/əˈtrɒsəti/", "trans": "atrocious (形容詞)", "col": "commit atrocities", "ex": "The soldiers were accused of committing atrocities against civilians.", "pos": "n."},
    "atrophy": {"def": "萎縮、發育停止、枯萎、(生)萎縮的人 (或物)、萎縮地 (萎縮)", "ipa": "/ˈætrəfi/", "trans": "wither", "col": "muscle atrophy", "ex": "Lack of exercise can cause muscle atrophy.", "pos": "n./v./adv."},
    "attach": {"def": "附著、貼上、繫上、連結、使依戀、連結的人 (或物)、連結地 (連結)", "ipa": "/əˈtætʃ/", "trans": "attachment, attached", "col": "attach files, be attached to", "ex": "I'll attach the map to the email.", "pos": "v./n./adv."},
    "attached": {"def": "附著的、依戀的、附屬的", "ipa": "/əˈtætʃt/", "trans": "attach (動詞/名詞/副詞), attachment", "col": "deeply attached to, attached garage", "ex": "She is deeply attached to her old dog.", "pos": "adj."},
    "attachment": {"def": "附件、加載裝置、依戀、忠誠、附件的人 (或物)、附件地 (附件)", "ipa": "/əˈtætʃmənt/", "trans": "attach (動詞/名詞/副詞), attached", "col": "email attachment, emotional attachment", "ex": "Do not open the email attachment if you don't know the sender.", "pos": "n./adv."},
    "attack": {"def": "攻擊、襲擊、抨擊、發作、攻擊、襲擊、攻擊的人 (或物)、攻擊地 (攻擊)", "ipa": "/əˈtæk/", "trans": "assault", "col": "heart attack, panic attack, counter attack", "ex": "The enemy launched a surprise attack at dawn.", "pos": "v./n./adv."},
    "attain": {"def": "達到、獲得、實現、到達", "ipa": "/əˈteɪn/", "trans": "attainment, attainable", "col": "attain goals, attain maturity", "ex": "She finally attained her goal of winning the championship.", "pos": "v."},
    "attainable": {"def": "可達到的、可獲得的", "ipa": "/əˈteɪnəbl/", "trans": "attain (動詞), attainment", "col": "attainable goals", "ex": "We need to set clear and attainable goals.", "pos": "adj."},
    "attainment": {"def": "達到、獲得、成就、造詣", "ipa": "/əˈteɪnmənt/", "trans": "attain (動詞), attainable", "col": "educational attainment, outstanding attainment", "ex": "The university recognizes students with outstanding attainments.", "pos": "n."},
    "attempt": {"def": "嘗試、試圖、企圖、試圖、嘗試的人 (或物)、嘗試地 (嘗試)", "ipa": "/əˈtempt/", "trans": "attempted", "col": "suicide attempt, successful attempt, make an attempt", "ex": "He made a failed attempt to escape.", "pos": "n./v./adv."},
    "attend": {"def": "參加、出席、照顧、注意、出席的人 (或物)、出席地 (出席)", "ipa": "/əˈtend/", "trans": "attendance, attendant", "col": "attend school, attend a meeting, attend to someone", "ex": "How many people will attend the conference?", "pos": "v./n./adv."},
    "attendance": {"def": "出席、到場、參加人數、照顧", "ipa": "/əˈtendəns/", "trans": "attend (動詞/名詞/副詞), attendant", "col": "school attendance, average attendance", "ex": "Teachers must take the attendance every morning.", "pos": "n."},
    "attendant": {"def": "服務員、侍從、伴隨的、隨之而來的、服務的人 (或物)、伴隨地 (伴隨)", "ipa": "/əˈtendənt/", "trans": "attend (動詞/名詞/副詞), attendance", "col": "flight attendant, parking attendant", "ex": "The flight attendant served drinks to the passengers.", "pos": "n./adj./adv."},
    "attention": {"def": "注意、注意力、立正、立正的人 (或物)、立正地 (立正)", "ipa": "/əˈtenʃn/", "trans": "attentive, attentively", "col": "pay attention, center of attention, medical attention", "ex": "Please pay attention to the instructions.", "pos": "n./adj./adv."},
    "attentive": {"def": "注意的、留心的、体貼的", "ipa": "/əˈtentɪv/", "trans": "attention (名詞/形容詞/副詞), attentively", "col": "attentive host", "ex": "He is a very attentive host who takes care of every guest.", "pos": "adj."},
    "attentively": {"def": "注意地、留心地、體貼地", "ipa": "/əˈtentɪvli/", "trans": "attentive (形容詞), attention", "col": "listen attentively", "ex": "The children listened attentively to the story.", "pos": "adv."},
    "attenuate": {"def": "使變薄、使減退、變瘦、稀釋、變薄的、減弱的、稀釋的人 (或物)、稀釋地 (稀釋)", "ipa": "/əˈtenjueɪt/ (v.) /əˈtenjuət/ (adj.)", "trans": "attenuation", "col": "attenuate a signal", "ex": "The mask is designed to attenuate the sound of breathing.", "pos": "v./adj./n./adv."},
    "attest": {"def": "證明、証實、使宣誓、(法)証實的人 (或物)、証實地 (証實)", "ipa": "/əˈtest/", "trans": "attestation", "col": "attest to", "ex": "These documents attest to his character.", "pos": "v./n./adv."},
    "attic": {"def": "閣樓、屋頂室、古雅的、(建)閣樓的", "ipa": "/ˈætɪk/", "trans": "loft", "col": "dark attic", "ex": "I found some old photos in the dark attic.", "pos": "n./adj."},
    "attire": {"def": "服裝、衣服、裝飾、打扮、整理的人 (或物)、正式地 (服裝)", "ipa": "/əˈtaɪə/", "trans": "clothing", "col": "formal attire, business attire", "ex": "Formal attire is required for the ceremony.", "pos": "n./v./adv."},
}