import json

# Level 6 Part 42: (Boomer - Bossy)
L6_PART42 = {
    "boomer": {"def": "嬰兒潮世代的人、(澳洲)大袋鼠 (單數)", "ipa": "/ˈbuːmə/", "trans": "baby boomer", "col": "baby boomer generation", "ex": "The boomers are now approaching retirement age.", "pos": "n."},
    "boomerang": {"def": "回力標、自食其果的行動、飛回、自食其果地 (回)", "ipa": "/ˈbuːməræŋ/", "trans": "boomerangs", "col": "throw a boomerang", "ex": "The weapon he used against me will boomerang on himself.", "pos": "n./v./adv."},
    "booming": {"def": "繁榮的、轟鳴的、低沉的、繁榮的人 (或物) (旺)", "ipa": "/ˈbuːmɪŋ/", "trans": "boom (動詞/名詞/副詞)", "col": "booming economy, booming voice", "ex": "He has a loud, booming voice.", "pos": "adj./adv."},
    "boon": {"def": "恩惠、福利、好處、快活的、恩惠的人 (或物)、恩惠地 (恩)", "ipa": "/buːn/", "trans": "blessing", "col": "boon to, boon companion (密友)", "ex": "The new highway will be a boon to local commerce.", "pos": "n./adj./adv."},
    "boondocks": {"def": "(口)邊遠地區、窮山惡水 (複數)", "ipa": "/ˈbuːndɒks/", "trans": "sticks", "col": "live in the boondocks", "ex": "They live out in the boondocks somewhere.", "pos": "n."},
    "boondoggle": {"def": "(美口)浪費錢財的工作、無謂的工作、浪費、無謂地 (浪費)", "ipa": "/ˈbuːndɒɡl/", "trans": "wasteful", "col": "government boondoggle", "ex": "The new project is seen as a costly boondoggle.", "pos": "n./v./adv."},
    "boor": {"def": "粗魯的人、農民、粗鄙的人的人物、粗魯地 (粗)", "ipa": "/bʊə/", "trans": "boors", "col": "uneducated boor", "ex": "I can't believe she's married to such an uneducated boor.", "pos": "n./adv."},
    "boorish": {"def": "粗魯的、粗野的、笨拙的", "ipa": "/ˈbʊərɪʃ/", "trans": "boor (名詞/副詞)", "col": "boorish behavior", "ex": "His boorish behavior at the dinner party was embarrassing.", "pos": "adj."},
    "boorishly": {"def": "粗魯地、粗野地、笨拙地", "ipa": "/ˈbʊərɪʃli/", "trans": "boorish (形容詞)", "col": "behaved boorishly", "ex": "He behaved boorishly towards the staff.", "pos": "adv."},
    "boorishness": {"def": "粗魯、粗野、笨拙", "ipa": "/ˈbʊərɪʃnəs/", "trans": "boorish (形容詞/副詞)", "col": "unpardonable boorishness", "ex": "I was shocked by his unpardonable boorishness.", "pos": "n."},
    "boost": {"def": "推動、提高、增加、宣傳、推動的人 (或物)、提高地 (提)", "ipa": "/buːst/", "trans": "boosters", "col": "morale boost, price boost, boost performance, boost sales", "ex": "The tax cuts will boost consumer spending.", "pos": "v./n./adv."},
    "booster": {"def": "推動者、支持者、效能增強器、追加劑 (單數)", "ipa": "/ˈbuːstə/", "trans": "boosters (複數)", "col": "booster shot, rocket booster, morale booster", "ex": "I need a tetanus booster shot.", "pos": "n."},
    "boot": {"def": "靴子、(英)行李箱、踢、啟動、踢出、在靴子內的人、踢地 (靴)", "ipa": "/buːt/", "trans": "boots, booting", "col": "walking boots, car boot, give someone the boot (開除), to boot (而且)", "ex": "He was wearing traditional leather boots.", "pos": "n./v./adv."},
    "bootee/bootie": {"def": "嬰兒針織鞋、(女)短筒靴 (單數)", "ipa": "/ˈbuːti/", "trans": "baby shoes", "col": "crocheted bootees", "ex": "She knitted some woolly bootees for the new baby.", "pos": "n."},
    "booth": {"def": "貨攤、亭、小隔間、電話亭、亭子的人、亭子地 (亭)", "ipa": "/buːð/", "trans": "booths", "col": "phone booth, voting booth, polling booth, photo booth", "ex": "She entered the voting booth to cast her ballot.", "pos": "n./adv."},
    "bootie/booty": {"def": "掠奪物、戰利品、(俚)屁股、掠奪的人 (或物)、掠奪地 (奪)", "ipa": "/ˈbuːti/", "trans": "spoils", "col": "pirate booty", "ex": "The pirates buried their booty on a desert island.", "pos": "n./adv."},
    "booting": {"def": "啟動、踢、放逐的人 (或物) (啟)", "ipa": "/ˈbuːtɪŋ/", "trans": "boot (名詞/動詞/副詞)", "col": "system booting", "ex": "The computer is currently booting up.", "pos": "n./adv."},
    "bootlace": {"def": "鞋帶 (長)", "ipa": "/ˈbuːtleɪs/", "trans": "shoelace", "col": "tighten bootlace", "ex": "He stopped to tie his bootlace.", "pos": "n."},
    "bootleg": {"def": "非法釀造、私售、非法錄製、偷運的人物、非法地 (非法)", "ipa": "/ˈbuːtleɡ/", "trans": "bootlegged", "col": "bootleg recording, bootleg liquor", "ex": "It is illegal to sell bootleg recordings of concerts.", "pos": "v./n./adj./adv."},
    "bootlegger": {"def": "非法製造或販賣的人、走私者 (單數)", "ipa": "/ˈbuːtleɡə/", "trans": "smuggler", "col": "prohibition bootlegger", "ex": "He was a notorious bootlegger during Prohibition.", "pos": "n."},
    "bootless": {"def": "無用處的、無利的、徒勞的", "ipa": "/ˈbuːtləs/", "trans": "useless", "col": "bootless effort", "ex": "It was a bootless task and a waste of time.", "pos": "adj."},
    "bootlick": {"def": "(俚)拍馬屁、諂媚、拍馬的人 (或物) (諂)", "ipa": "/ˈbuːtlɪk/", "trans": "fawn over", "col": "stop bootlicking", "ex": "Don't bootlick the boss just to get a promotion.", "pos": "v./n./adv."},
    "booty": {"def": "掠奪物、戰利品、獎賞 (單數)", "ipa": "/ˈbuːti/", "trans": "loot", "col": "share of the booty", "ex": "The thieves divided the booty among themselves.", "pos": "n."},
    "booze": {"def": "酒、狂飲、痛飲的人、豪飲地 (酒)", "ipa": "/buːz/", "trans": "boozing", "col": "cheap booze, stay off the booze", "ex": "He's been on the booze again.", "pos": "n./v./adv."},
    "boozer": {"def": "(口)酒鬼、酒店 (單數)", "ipa": "/ˈbuːzə/", "trans": "boozers (複數)", "col": "local boozer", "ex": "He's a regular at the local boozer.", "pos": "n."},
    "boozy": {"def": "嗜酒的、醉醺醺的", "ipa": "/ˈbuːzi/", "trans": "booze (名詞/動詞/副詞)", "col": "boozy night out", "ex": "They had a boozy night out to celebrate.", "pos": "adj."},
    "borax": {"def": "硼砂、硼砂地 (硼砂)", "ipa": "/ˈbɔːræks/", "trans": "chemical", "col": "refined borax", "ex": "Borax is used in detergents and cosmetics.", "pos": "n./adv."},
    "border": {"def": "邊界、邊緣、鑲邊、接壤、邊境的、在邊界上地 (界)", "ipa": "/ˈbɔːdə/", "trans": "borders, boarding", "col": "cross the border, border control, border dispute, border guards", "ex": "The river forms the border between the two countries.", "pos": "n./v./adj./adv."},
    "borderland": {"def": "邊境地區、模糊地帶 (單數)", "ipa": "/ˈbɔːdəlænd/", "trans": "borderlands (複數)", "col": "cultural borderland", "ex": "They live in a remote borderland between the two nations.", "pos": "n."},
    "borderline": {"def": "邊界線、中界線、邊緣的、二疊的人物、二疊地 (邊緣)", "ipa": "/ˈbɔːdəlaɪn/", "trans": "marginal", "col": "borderline case, borderline personality", "ex": "He is a borderline candidate for the job.", "pos": "n./adj./adv."},
    "bore": {"def": "使厭煩、鑽孔、煩人的人、鑽孔、(bear的過去式)、在煩的人人物、在煩的人地 (煩)", "ipa": "/bɔː/", "trans": "boring, bored", "col": "bore to death, bore a hole, what a bore!", "ex": "Am I boring you?", "pos": "v./n./adv."},
    "bored": {"def": "無聊的、厭倦的、鑽了孔的", "ipa": "/bɔːd/", "trans": "bore (動詞/名詞/副詞)", "col": "get bored, bored to tears", "ex": "The children were bored on the long car journey.", "pos": "adj."},
    "boredom": {"def": "無聊、厭倦、乏味", "ipa": "/ˈbɔːdəm/", "trans": "bore (動詞/名詞/副詞), bored", "col": "sheer boredom", "ex": "He resigned out of sheer boredom with his job.", "pos": "n."},
    "boric": {"def": "硼的、含硼的", "ipa": "/ˈbɔːrɪk/", "trans": "borax", "col": "boric acid (硼酸)", "ex": "Boric acid can be used as an antiseptic.", "pos": "adj."},
    "boring": {"def": "無聊的、鑽孔的、鑽孔的人 (或物) (無)", "ipa": "/ˈbɔːrɪŋ/", "trans": "bore (動詞/名詞/副詞)", "col": "tedious and boring", "ex": "The movie was so boring I fell asleep.", "pos": "adj./n./adv."},
    "born": {"def": "出生的、天生的、具備...的人地 (生)", "ipa": "/bɔːn/", "trans": "bear", "col": "born and bred, first born, newly born", "ex": "She was born in 1995.", "pos": "v./adj./adv."},
    "borne": {"def": "(bear的過去分詞)、負擔的", "ipa": "/bɔːn/", "trans": "bear", "col": "air borne (空氣傳播的), water borne", "ex": "The costs will be borne by the company.", "pos": "v."},
    "boron": {"def": "硼 (化學元素)", "ipa": "/ˈbɔːrɒn/", "trans": "element", "col": "pure boron", "ex": "Boron is used in some types of glass.", "pos": "n."},
    "borough": {"def": "(英)自治市鎮、(美)區 (單數)", "ipa": "/ˈbʌrə/", "trans": "boroughs (複數)", "col": "London borough", "ex": "Hackney is a borough in East London.", "pos": "n."},
    "borrow": {"def": "借入、借用、借入的人 (或物)、借用地的 (借)", "ipa": "/ˈbɒrəʊ/", "trans": "borrowed", "col": "borrow from, borrowed time (晚年/殘生)", "ex": "Can I borrow your pen for a moment?", "pos": "v./n./adv."},
    "borrower": {"def": "借用者、借貸人 (單數)", "ipa": "/ˈbɒrəʊə/", "trans": "borrow (動詞/名詞/副詞)", "col": "institutional borrower", "ex": "The bank carefully checks the credit of each borrower.", "pos": "n."},
    "borrowing": {"def": "借貸、借用物、外來語、借入的人 (或物) (借)", "ipa": "/ˈbɒrəʊɪŋ/", "trans": "borrow (動詞/名詞/副詞)", "col": "heavy borrowing", "ex": "The government needs to reduce its heavy borrowing.", "pos": "n./adv."},
    "borscht": {"def": "羅宋湯 (單數)", "ipa": "/bɔːʃt/", "trans": "soup", "col": "traditional borscht", "ex": "Borscht is a traditional soup made with beetroot.", "pos": "n."},
    "bosom": {"def": "胸部、乳房、心懷、親密的、懷中、抱在懷裡、在胸中地 (胸)", "ipa": "/ˈbʊzəm/", "trans": "bosoms", "col": "bosom friend (知己), in the bosom of (在...懷抱中)", "ex": "He held the child to his bosom.", "pos": "n./adj./v./adv."},
    "boss": {"def": "老闆、首領、指揮、做首領、老闆的人物、做老闆地 (老)", "ipa": "/bɒs/", "trans": "bossy", "col": "big boss, boss around (頤指氣使)", "ex": "Who is the boss in this office?", "pos": "n./v./adv."},
    "bossiness": {"def": "專橫、好指揮、傲慢", "ipa": "/ˈbɒsinəs/", "trans": "bossy (形容詞/副詞)", "col": "annoying bossiness", "ex": "She was tired of her mother's constant bossiness.", "pos": "n."},
    "bossy": {"def": "愛指揮人的、專橫的、(俚)好的", "ipa": "/ˈbɒsi/", "trans": "boss (名詞/動詞/副詞)", "col": "bossy older sister", "ex": "He is a very bossy person who likes to tell everyone what to do.", "pos": "adj."},
}